### PR TITLE
Fix "Call to a member function getUID() on boolean" in Crypt

### LINKED ISSUE #19965: [8.2.0] After upgrade get white screen upon login, probably encryption related
screenshot from 2015-10-21 22-15-10
### Steps to reproduce
1. Upgrade from 8.1.3 with encryption enabled
2. Try to login
3. Tried running "occ encryption:migrate" just in case.

### Expected behaviour
Should be able to login and open files

### Actual behaviour
Something seemed to have gone wrong when I first tried 'occ upgrade' as seen in the screenshot.
After running 'occ upgrade' again everything seemed to have worked. But, when I try to login I'm shown a white screen.

Using occ I enabled files_locking and this allows me to login, but I always have the yellow banner ``Encryption App is enabled but your keys are not initialized, please log-out and log-in again``
Trying to download a file gives me an error ``Can't read file``

### Server configuration
**Operating system**: FreeBSD 10.1 64 bit

**Web server:** nginx

**Database:** MariaDB 10.0

**PHP version:** 5.6.11

**ownCloud version:** 8.2.0

**Updated from an older ownCloud or fresh install:**
Updated

**List of activated apps:**
```Enabled:
  - activity: 2.1.3
  - encryption: 1.1.0
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - gallery: 14.2.0
  - updater: 0.6
```
Previously I also had the mail, news, ownnote, documents, calendar, contacts enabled as seen in the attached screenshot.

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocb072aa2d38",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.jruehlig.com"
        ],
        "datadirectory": "\/mnt\/files",
        "dbtype": "mysql",
        "version": "8.2.0.12",
        "dbname": "owncloud",
        "dbhost": "localhost:\/mnt\/mysql\/mysql.sock",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_type": "syslog",
        "loglevel": 0,
        "forcessl": false,
        "mail_smtpmode": "smtp",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "465",
        "mail_domain": "jruehlig.com",
        "mail_from_address": "owncloud",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": true,
        "theme": "",
        "maintenance": false,
        "overwrite.cli.url": "https:\/\/www.jruehlig.com\/owncloud",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Markdown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font"
        ],
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using encryption:** yes

### Client configuration
**Browser:** Firefox & Chrome

**Operating system:**
Arch Linux 64bit

#### Syslog (nginx/php-fpm/owncloud)
```
Oct 22 00:55:35 192.168.1.11 php-fpm[918]: {PHP} Call to a member function getUID() on boolean at /usr/local/www/owncloud/apps/encryption/lib/crypto/crypt.php#92
Oct 22 00:55:35 192.168.1.11 kernel: Oct 22 00:55:35 webserver php-fpm[918]: {PHP} Call to a member function getUID() on boolean at /usr/local/www/owncloud/apps/encryption/lib/crypto/crypt.php#92
Oct 22 00:55:35 192.168.1.11 nginx: 2015/10/22 00:55:35 [error] 32699#0: *1663 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getUID() on boolean in /usr/local/www/owncloud/apps/encryption/lib/crypto/crypt.php on line 92" while reading response header from upstream, client: 192.168.3.185, server: www.jruehlig.com, request: "POST /owncloud/index.php HTTP/1.1", upstream: "fastcgi://unix:/usr/jails/owncloud/var/run/php-fpm.sock:", host: "www.jruehlig.com"
Oct 22 00:55:35 192.168.1.11 kernel: Oct 22 00:55:35 webserver webserver nginx: 2015/10/22 00:55:35 [error] 32699#0: *1663 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getUID() on boolean in /usr/local/www/owncloud/apps/encryption/lib/crypto/crypt.php on line 92" while reading response header from upstream, client: 192.168.3.185, server: www.jruehlig.com, request: "POST /owncloud/index.php HTTP/1.1", upstream: "fastcgi://unix:/usr/jails/owncloud/var/run/php-fpm.sock:", host: "www.jruehlig.com"
Oct 22 00:55:38 192.168.1.11 ownCloud[918]: {webdav} Exception: {"Message":"HTTP\/1.1 401 No basic authentication headers were found","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 \/usr\/local\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(148): Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#1 \/usr\/local\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(121): OC\\Connector\\Sabre\\Auth->auth(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#2 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php(118): OC\\Connector\\Sabre\\Auth->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#3 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/
Oct 22 00:55:39 192.168.1.11 php-fpm[918]: {PHP} Call to a member function getUID() on boolean at /usr/local/www/owncloud/apps/encryption/lib/crypto/crypt.php#92
Oct 22 00:55:39 192.168.1.11 kernel: Oct 22 00:55:39 webserver php-fpm[918]: {PHP} Call to a member function getUID() on boolean at /usr/local/www/owncloud/apps/encryption/lib/crypto/crypt.php#92
Oct 22 00:55:39 192.168.1.11 nginx: 2015/10/22 00:55:39 [error] 32699#0: *1667 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getUID() on boolean in /usr/local/www/owncloud/apps/encryption/lib/crypto/crypt.php on line 92" while reading response header from upstream, client: 98.207.83.15, server: www.jruehlig.com, request: "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1", upstream: "fastcgi://unix:/usr/jails/owncloud/var/run/php-fpm.sock:", host: "www.jruehlig.com"
Oct 22 00:55:39 192.168.1.11 kernel: Oct 22 00:55:39 webserver webserver nginx: 2015/10/22 00:55:39 [error] 32699#0: *1667 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getUID() on boolean in /usr/local/www/owncloud/apps/encryption/lib/crypto/crypt.php on line 92" while reading response header from upstream, client: 98.207.83.15, server: www.jruehlig.com, request: "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1", upstream: "fastcgi://unix:/usr/jails/owncloud/var/run/php-fpm.sock:", host: "www.jruehlig.com"
```

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #19965 

@schiesbn @MorrisJobke @LukasReschke

### CODE REVIEW

**Comment by schiesbn** [comment]
makes sense :+1:

**Comment by nickvergessen** [comment]
@schiesbn what do you think, should we backport this?

**Comment by schiesbn** [comment]
Low risk and improves error messages, so I think we can backport it... cc @karlitschek please confirm.

File: apps/encryption/lib/crypto/crypt.php [hunk 1]
```diff
@@ -73,7 +73,7 @@ class Crypt {
 	 */
 	public function __construct(ILogger $logger, IUserSession $userSession, IConfig $config) {
 		$this->logger = $logger;
-		$this->user = $userSession && $userSession->isLoggedIn() ? $userSession->getUser() : false;
+		$this->user = $userSession && $userSession->isLoggedIn() ? $userSession->getUser()->getUID() : '"no user given"';
```
Comment (DeepDiver1975) [inline apps/encryption/lib/crypto/crypt.php]: technically speaking getUser() can still return null here - very unlikely - but one never knows ....

Comment (schiesbn) [inline apps/encryption/lib/crypto/crypt.php]: if "$userSession->isLoggedIn()" is true? Do you have a example?

Comment (DeepDiver1975) [inline apps/encryption/lib/crypto/crypt.php]: > Do you have a example?

not really since isLoggedIn() basically checks if getUser is null. My comment was more on a logical level.

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by schiesbn** [comment]
@nickvergessen thanks for the backport? Did you also checked 8.1? It would probably make sense to backport it to oC8.1 too.
