### PR TITLE
Don't strip linebreaks in personal note #32036

### LINKED ISSUE #32036: Don't strip linebreaks in personal note
some customers have the following problem

---

### Steps to reproduce
1. Set up OC 10.0.8 (community or enterprise)
2. Allow users to notify others about public shares via e-mail
3. Create a public Share and notify someone via E-Mail

### Expected behaviour
The personal note Field is a TextArea. The customer expects the linebreaks from this field to show up in the e-mail.

### Actual behaviour
The linebreaks from the personal note field are stripped.

### Server configuration

**ownCloud version:** (see ownCloud admin page)
10.0.8

## Screenshots

**Create public share**
screenshot_2018-07-10 files - owncloud

**E-Mail HTML**
screenshot_2018-07-10 mailhog

**E-Mail Plain Text**
screenshot_2018-07-10 mailhog 1

### PR DESCRIPTION
**Pull request by micbar**
## Description

Removed the escaping of the personal note in the mail template. The content of this variable has already been sanitized by strip_tags().

Needs to be mentioned in Release Notes, that a core template file has been changed. Customers who have customized mail templates need to manually review their template file. If they don't do it, the behavior will stay the same, the line breaks will be stripped from the personal note.
## Related Issue
- Fixes #32036

## How Has This Been Tested?
- manually
- Unit tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Release Notes

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

File: core/templates/mail.php [hunk 1]
```diff
@@ -20,7 +20,11 @@
 
 if (isset($_['personal_note'])) {
 	// TRANSLATORS personal note in share notification email
-	p($l->t("Personal note from the sender: %s.", [$_['personal_note']]));
+	p($l->t("Personal note from the sender:"));
+	print_unescaped('<br>');
+	// Personal Note has already been sanitized by strip_tags();
+	// Convert Linebreaks to html
```
Comment (PVince81) [inline core/templates/mail.php]: this comment is obsolete since you moved the conversion to `MailNotifications`

**Review by PVince81 — DISMISSED** [review]
See comment

**Comment by PVince81** [comment]
@micbar mind checking if there is a unit test that can be adjusted ? (this might be in the "non-testable" zone)

File: core/templates/mail.php (hunk 1 above)
Comment (micbar) [reply core/templates/mail.php]: the conversion has already been there, i just switched to print_unescaped()

**Comment by micbar** [comment]
Found Test in /tests/lib/Share/MailNotificationsTest.php

```php
$message
    ->expects($this->once())
    ->method('setHtmlBody')
    ->with($this->stringContains('personal note'));
$message
    ->expects($this->once())
    ->method('setPlainBody')
    ->with($this->stringContains('personal note'));
```
This test doesn't need to be changed because it doesn't check the style of the personal note.

I run all tests with `make test`, all passed.

**Comment by PVince81** [comment]
@micbar can you extend the test to also check the newline conversion at least ?

**Comment by micbar** [comment]
ok, will do.

**Comment by micbar** [comment]
adapted unit tests to check for linebreak conversion.

**Review by DeepDiver1975 — APPROVED** [review]
