### PR TITLE
adapted solution for 5xx error on i10n vsprintf

### LINKED ISSUE #37799: Settings language to "Dansk" breaks settings page.
### Steps to reproduce
1. Do a fresh install of Owncloud with instructions from https://doc.owncloud.com/server/admin_manual/installation/docker/. No need to change any configuration parameters.
2. Do the first login with admin/admin. 
3. Navigate to settings and change language to "Dansk".

### Expected behaviour
Settings page displayed in Danish. 

### Actual behaviour
Internal server error page displayed. 

### Server configuration
**Operating system:** Docker host: Ubuntu 20.04.1. Running docker image owncloud/server:10.5.0

**Web server:** Server bundled with docker image. 

**Database:** Data bundled with docker image. 

**PHP version:** Bundled with docker image. 

**ownCloud version:** 10.5.0

**Updated from an older ownCloud or fresh install:** Happens on both fresh install and after upgrade from 10.4. 

**Where did you install ownCloud from:** Running docker image  owncloud/server:10.5.0

**Signing status (ownCloud 9.0 and above):** No errors have been found.

**The content of config/config.php:**
{
    "system": {
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/owncloud\/custom",
                "url": "\/custom",
                "writable": true
            }
        ],
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/mnt\/data\/files",
        "dbtype": "mysql",
        "dbhost": "db",
        "dbname": "owncloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "log_type": "owncloud",
        "supportedDatabases": [
            "sqlite",
            "mysql",
            "pgsql"
        ],
        "upgrade.disable-web": true,
        "default_language": "en",
        "overwrite.cli.url": "http:\/\/localhost\/",
        "htaccess.RewriteBase": "\/",
        "logfile": "\/mnt\/data\/files\/owncloud.log",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mysql.utf8mb4": true,
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "redis",
            "port": "6379"
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "version": "10.5.0.10",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "octqpqyu3935"
    }
}

**List of activated apps:**
  - activity: 2.5.3
  - comments: 0.3.0
  - configreport: 0.2.0
  - dav: 0.6.0
  - federatedfilesharing: 0.5.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_mediaviewer: 1.0.3
  - files_pdfviewer: 0.11.1
  - files_sharing: 0.13.0
  - files_texteditor: 2.3.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firstrunwizard: 1.2.0
  - market: 0.6.0
  - notifications: 0.5.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.4.0
  - updatenotification: 0.2.1

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox and Chrome

**Operating system:** Windows

#### Web server error log
ESC[36mowncloud_1  |ESC[0m 10.0.0.5 - - [10/Aug/2020:19:48:49 +0000] "POST /settings/ajax/setlanguage.php HTTP/1.1" 200 745 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Ch
rome/84.0.4147.105 Safari/537.36"
ESC[36mowncloud_1  |ESC[0m 10.0.0.5 - - [10/Aug/2020:19:48:49 +0000] "GET /settings/personal HTTP/1.1" 500 10169 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4
147.105 Safari/537.36"

#### ownCloud log (data/owncloud.log)
{"reqId":"5wyu9kMQtOfuCWNwwqIt","level":3,"time":"2020-08-10T19:48:49+00:00","remoteAddr":"10.0.0.5","user":"admin","app":"PHP","method":"GET","url":"\/settings\/personal","message":"vsprintf(): Too few arguments at \/var\/www\/owncloud\/lib\/private\/legacy\/l10n\/string.php#69"}
{"reqId":"5wyu9kMQtOfuCWNwwqIt","level":3,"time":"2020-08-10T19:48:49+00:00","remoteAddr":"10.0.0.5","user":"admin","app":"index","method":"GET","url":"\/settings\/personal","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Method OC_L10N_String::__toString() must return a string value\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Settings\\\/SettingsManager.php(215): OC\\\\L10N\\\\L10N->t()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Settings\\\/SettingsManager.php(447): OC\\\\Settings\\\\SettingsManager->getBuiltInSections()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Settings\\\/SettingsManager.php(421): OC\\\\Settings\\\\SettingsManager->loadSection()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Settings\\\/SettingsManager.php(164): OC\\\\Settings\\\\SettingsManager->loadPanels()\\n#4 \\\/var\\\/www\\\/owncloud\\\/settings\\\/Controller\\\/SettingsPageController.php(79): OC\\\\Settings\\\\SettingsManager->getAdminSections()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OC\\\\Settings\\\\Controller\\\\SettingsPageController->getPersonal()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(916): OC\\\\Route\\\\Router->match()\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/L10N\\\/L10N.php\",\"Line\":80}"}

#### Browser log
Nothing relevant from browser.

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
As we using the vsprintf links in the i10n translation provider and also translations provided via the community, there is always the possibility, that there might be an error in the translation string.

Especially if there is an unescaped % char in the text, without any parameter, this will provoke an error in the WebUi (Error Page).

Instead of showing a 5xx Error, the original text will be displayed.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/37799
- Patch of https://github.com/math221e/core/commit/965636c84987be32fd9aaeb09d4ec26e18645f51

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]
Please add a unit test for this. THX

File: changelog/unreleased/38103 [hunk 1]
```diff
@@ -0,0 +1,8 @@
+Bugfix: Prevent server error when loading invalid/corrupt translations
+
+This fix prevents server errors when loading invalid or corrupt translations
+form Transifex. This is critical as every user is able to contribute to
```
Comment (phil-davis) [inline changelog/unreleased/38103:4]:
```suggestion
from Transifex. This is critical as every user is able to contribute to
```

File: tests/lib/L10N/L10nTest.php [hunk 2]
```diff
@@ -46,6 +46,14 @@ public function testGermanPluralTranslations() {
 		$this->assertEquals('2 Dateien', (string) $l->n('%n file', '%n files', 2));
 	}
 
+	public function testMalformedTranslations() {
+		$lMock = $this->createMock('OC\L10N\L10N');
+		$lMock->method('getTranslations')->willReturn(['malformed' => 'malformed %']);
+
+		$lString = new \OC_L10N_String($lMock, "malformed", []);
+		$this->assertEquals('malformed', $lString->__toString());
```
Comment (DeepDiver1975) [inline tests/lib/L10N/L10nTest.php:54]: self:: please  
assertEquals is static

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]

File: .htaccess [hunk 3]
```diff
@@ -94,3 +94,7 @@ Options -Indexes
 <IfModule pagespeed_module>
   ModPagespeed Off
 </IfModule>
+#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
+
+ErrorDocument 403 /core/templates/403.php
```
Comment (DeepDiver1975) [inline .htaccess]: :see_no_evil:

File: Makefile [hunk 4]
```diff
@@ -54,7 +54,7 @@ PHPSTAN=php -d zend.enable_gc=0 vendor-bin/phpstan/vendor/bin/phpstan
 
 TEST_DATABASE=sqlite
 TEST_EXTERNAL_ENV=smb-silvershell
-TEST_PHP_SUITE=
+TEST_PHP_SUITE=tests/Core/Command/Config/App/SetConfigTest.php
```
Comment (DeepDiver1975) [inline Makefile]: :see_no_evil:

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]

**Comment by DeepDiver1975** [comment]
squash commits into one and we are ready to go @HieronymusPerro - THX

**Comment by HieronymusPerro** [comment]
Done, THX for reviewing!

**Review by DeepDiver1975 — APPROVED** [review]
