### PR TITLE
use empty control when trying to get existing home in user sync

### LINKED ISSUE #30853: A log is shown when we create a regular user
### Steps to reproduce
1. As admin User go to Users Page
2. Create a user
3. Check owncloud.log file

### Expected behaviour

No logs should be shown

### Actual behaviour

A log is shown in owncloud.log when creating a user

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.1.15

**ownCloud version:""10.1.0 prealpha" using owncloud-daily-master.tar.bz2 from 20 March 2018

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**

```
{"reqId":"HuAr8DBNhaIvOEfiHlGA","level":3,"time":"2018-03-21T08:02:10+00:00","remoteAddr":"85.57.168.79","user":"admin","app":"no app in context","method":"POST","url":"\/index.php\/settings\/users\/users","message":"User backend OC\\User\\Database is returning home: \/opt\/owncloud\/data\/pepe for user: pepe which differs from existing value: "}
```

Content of the account table:

```
select * from accounts;
+----+-------+---------+---------------+--------------+-------+------------+------------------+--------------------------+-------+
| id | email | user_id | lower_user_id | display_name | quota | last_login | backend          | home                     | state |
+----+-------+---------+---------------+--------------+-------+------------+------------------+--------------------------+-------+
|  1 | NULL  | admin   | admin         | admin        | NULL  | 1521619576 | OC\User\Database | /opt/owncloud/data/admin |     1 |
|  2 | NULL  | pepe    | pepe          | pepe         | NULL  | 1521619458 | OC\User\Database | /opt/owncloud/data/pepe  |     1 |
+----+-------+---------+---------------+--------------+-------+------------+------------------+--------------------------+-------+
```
### Client configuration

**browser**

Firefox

### LINKED ISSUE #32438: Confusing log message when creating a user (via occ)
### Steps to reproduce
1. sudo -uwww-data ./occ user:add --email="whoever@me.bu" --display-name="User Name" user_x

### Expected behaviour
A message which either tells success or fail + reason

### Actual behaviour
```
{"reqId":"aAKMnFQRmek08dZ2U7Wf","level":3,"time":"2018-08-25T18:36:00+02:00","remoteAddr":"",
"user":"--","app":"no app in context","method":"--","url":"--","message":
"User backend OC\\User\\Database is returning home: \/var\/www\/owncloud\/data\/user_x 
for user: user_x which differs from existing value: "}
```
### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7,1

**ownCloud version:** 10.0.9

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** tar

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**The content of config/config.php:**

```
```

**List of activated apps:**

```
```

**Are you using external storage, if yes which one:** local/smb/ftp/dropbox...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### ownCloud log (data/owncloud.log)
see above

### PR DESCRIPTION
**Pull request by karakayasemi**
## Description
The server is producing unintended error logs in every user creation.  This bug fixed with proper condition control. Also, since we are making lots of add/delete users in test scenarios, acceptance tests log files are full of this log, like https://drone.owncloud.com/owncloud/encryption/977/60/11 . This PR will make test log files more readable.

## Related Issue
- Fixes https://github.com/owncloud/core/issues/30853
- Fixes https://github.com/owncloud/core/issues/32438
## Motivation and Context
More readable log file without false positives.

## How Has This Been Tested?
Use test steps given in the related issues. The error log will not be generated.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

File: lib/private/User/SyncService.php [hunk 1]
```diff
@@ -248,13 +248,13 @@ private function syncHome(Account $a, UserInterface $backend) {
 			$existing = $a->getHome();
 			$backendHome = $backend->getHome($uid);
 			$class = \get_class($backend);
-			if ($existing !== '') {
+			if ($existing) {
```
Comment (phil-davis) [inline lib/private/User/SyncService.php]:
```suggestion
			if ($existing !== $backendHome) {
```
When I read the message, I feel like the test should be like what I suggest above.
Is there some reason why the test is just about `$existing` and does not involve `$backendHome` ?

File: lib/private/User/SyncService.php [hunk 2]
```diff
@@ -248,13 +248,13 @@ private function syncHome(Account $a, UserInterface $backend) {
...
 				$this->logger->error("User backend $class is returning home: $backendHome for user: $uid which differs from existing value: $existing");
 			}
 		}
 		// Home is handled differently, it should only be set on account creation, when there is no home already set
 		// Otherwise it could change on a sync and result in a new user folder being created
-		if ($a->getHome() === null) {
+		if (empty($a->getHome())) {
```
Comment (phil-davis) [inline lib/private/User/SyncService.php]: I hate `empty()` :)
I don't think it can happen, but what if `getHome()` returns the string "0"

File: lib/private/User/SyncService.php (hunk 1 above)
Comment (karakayasemi) [reply lib/private/User/SyncService.php]: https://github.com/owncloud/core/blob/3f6b17300a4a24c3d286185d0d2c1cfdb6c58d46/lib/private/User/SyncService.php#L247

This control already exists in the upper level. It is the outer condition of this condition.

File: lib/private/User/SyncService.php (hunk 2 above)
Comment (karakayasemi) [reply lib/private/User/SyncService.php]: I changed it the way you like it. :wink:

File: lib/private/User/SyncService.php [hunk 3]
```diff
@@ -248,13 +248,13 @@ private function syncHome(Account $a, UserInterface $backend) {
...
 			$class = \get_class($backend);
-			if ($existing !== '') {
+			if ($existing) {
 				$this->logger->error("User backend $class is returning home: $backendHome for user: $uid which differs from existing value: $existing");
 			}
 		}
 		// Home is handled differently, it should only be set on account creation, when there is no home already set
 		// Otherwise it could change on a sync and result in a new user folder being created
-		if ($a->getHome() === null) {
+		if (empty($a->getHome()) && $a->getHome() !== '0') {
```
Comment (VicDeo) [inline lib/private/User/SyncService.php]: The best way to go is  not expect `null` from the method  with signature  `* @method string getHome()` I understand that `Account::getHome` is more tricky to fix. But as for me I'd better cast `$a->getHome()` result to string and use a strict comparison here: `if ((string) $a->getHome() === '') {`

**Review by VicDeo — COMMENTED** [review]
@karakayasemi did you consider adding 
```
	public function getHome() {
		return (string) $this->getter('home');
	}
``` 
into `OC\User\Account` class to ensure that getHome can't be `null`?

**Comment by karakayasemi** [comment]
@VicDeo I tried to solve the return type problem in `Entity` class level, because `Entity` class has `addType` method for a similar purpose. However, this unnecessarily extended the scope of the PR, also some of the unit tests failed due to the changes in `Entity`.

Finally, I applied your suggestion to ensure `getHome` will return always string. Please, review one more time, thanks.

**Comment by karakayasemi** [comment]
Drone tests passed. I rebased the branch to trigger the missing codecov report.

**Review by VicDeo — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]
LGTM. I will look in the CI logs when CI is done.

**Comment by phil-davis** [comment]
An older example acceptance test run: https://drone.owncloud.com/owncloud/core/21169/39/11
has lots of:
```
{"reqId":"MDDmcuBjrFUVyBHlRHF4","level":3,"time":"2019-11-05T11:15:27+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"--","url":"--","message":"User backend OC\\User\\Database is returning home: \/drone\/src\/data\/admin for user: admin which differs from existing value: "}
```

The same acceptance test suite log from today, e.g. https://drone.owncloud.com/owncloud/core/21178/39/11 does not have those entries.

Good

**Comment by karakayasemi** [comment]
Good to see these results. I realized the problem from acceptance test suite logs. Make them readable was one of the aims.
