### PR TITLE
Keep "encryptedVersion" when calling `\OC\Files\View::copy`

### LINKED ISSUE #22781: Cannot restore previous file version with enabled encryption
### Steps to reproduce
1. Install ownCloud 9.0.0 beta 2 (testing) (Ubuntu server 14.04, owncloud's repository, PostgreSQL DB)
2. Enable Default encryption module.
3. Enable Server-side encryption
4. Create and enable recovery key.
5. Create a testuser.
6. Enable password recovery in testuser's personal settings.
7. Install and setup a desktop client on a Windows PC (use the testuser's account).
8. Create a .docx file in the folder which is synchronized by the desktop client, save the file and make sure that it is synchronized.
9.  Change the file (edit the file and change a random part of the text), save and make sure that it is synchronized.
10. Go to the web interface.
11. Select the file (with the check box).
12. Click Details->Versions.
13. Restore the previous version.
14. Open the file.

### Expected behaviour
Show the readable contents of the file or offer to save the file on the local computer in a readable state. The desktop client should successfully sync the file and the file should be in a readable and usable form.

### Actual behaviour
When I try to open the file from the web interface Firefox says:

> "Firefox can't find the file at http://owncloud.programista.pro/remote.php/webdav/5555.docx."

The desktop client says:

>  3/2/2016 3:55:08 PM,                                                       5555.docx,                      ownCloud,Continue blacklisting: Error downloading http://owncloud.programista.pro/remote.php/webdav/5555.docx - server replied: Internal Server Error

I find this error in Owncloud's log:

> Exception: {"Message":"Bad Signature","Exception":"OC\\HintException","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/encryption\/lib\/crypto\/crypt.php(457): OCA\\Encryption\\Crypto\\Crypt->checkSignature('CsuaoG1l5qKwUyI...', '???????#??????m...', 'e8c43d56a866cf9...')\n#1 \/var\/www\/owncloud\/apps\/encryption\/lib\/crypto\/encryption.php(364): OCA\\Encryption\\Crypto\\Crypt->symmetricDecryptFileContent('CsuaoG1l5qKwUyI...', '???????#??????m...', 'AES-256-CTR', 4, '0end')\n#2 \/var\/www\/owncloud\/lib\/private\/files\/stream\/encryption.php(458): OCA\\Encryption\\Crypto\\Encryption->decrypt('CsuaoG1l5qKwUyI...', '0end')\n#3 \/var\/www\/owncloud\/lib\/private\/files\/stream\/encryption.php(289): OC\\Files\\Stream\\Encryption->readCache()\n#4 [internal function]: OC\\Files\\Stream\\Encryption->stream_read(8192)\n#5 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php(67): fread(Resource id #45, 8192)\n#6 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(88): Icewind\\Streams\\Wrapper->stream_read(8192)\n#7 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_read(8192)\n#8 \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php(78): stream_copy_to_stream(Resource id #48, Resource id #50, '4')\n#9 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(470): Sabre\\HTTP\\Sapi::sendResponse(Object(Sabre\\HTTP\\Response))\n#10 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#11 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(54): Sabre\\DAV\\Server->exec()\n#12 \/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#13 {main}","File":"\/var\/www\/owncloud\/apps\/encryption\/lib\/crypto\/crypt.php","Line":477} 

### Server configuration
**Operating system**:

**Web server:**
Apache/2.4.7
**Database:**
PostgreSQL 9.3.11
**PHP version:**
HP/5.5.9-1ubuntu4.14
**ownCloud version:** (see ownCloud admin page)
9.0.0 beta 2 (testing)
**Updated from an older ownCloud or fresh install:**
No
**Where did you install ownCloud from:**
Official repository:
deb http://download.owncloud.org/download/repositories/9.0:/testing/xUbuntu_14.04/ /
**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.4
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - files: 1.4.3
  - files_external: 0.5.2
  - files_pdfviewer: true
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: true
  - gallery: 14.3.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: true
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - external
  - federation
  - user_external
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocbcskcyj9fv",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.programista.pro"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/owncloud.programista.pro",
        "dbtype": "pgsql",
        "version": "9.0.0.12",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false
    }
}
```

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** yes/no
Yes
**Are you using an external user-backend, if yes which one:** 
no, but I am planning to use LDAP

### Client configuration
**Browser:**
Firefox 44.0.2
**Operating system:**
Windows 10
#### Web server error log
```
Insert your webserver log here
[Wed Mar 02 14:23:40.376272 2016] [mpm_event:notice] [pid 6955:tid 140675243616128] AH00489: Apache/2.4.7 (Ubuntu) configured -- resuming normal operations
[Wed Mar 02 14:23:40.376378 2016] [core:notice] [pid 6955:tid 140675243616128] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 02 14:23:44.808521 2016] [mpm_event:notice] [pid 6955:tid 140675243616128] AH00491: caught SIGTERM, shutting down
[Wed Mar 02 14:23:45.859827 2016] [mpm_prefork:notice] [pid 8373] AH00163: Apache/2.4.7 (Ubuntu) configured -- resuming normal operations
[Wed Mar 02 14:23:45.859919 2016] [core:notice] [pid 8373] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 02 14:23:47.073793 2016] [mpm_prefork:notice] [pid 8373] AH00169: caught SIGTERM, shutting down
[Wed Mar 02 14:23:48.234223 2016] [mpm_prefork:notice] [pid 8459] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.14 configured -- resuming normal operations
[Wed Mar 02 14:23:48.234277 2016] [core:notice] [pid 8459] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 02 14:23:54.314176 2016] [mpm_prefork:notice] [pid 8459] AH00171: Graceful restart requested, doing restart
[Wed Mar 02 14:23:54.370299 2016] [mpm_prefork:notice] [pid 8459] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.14 configured -- resuming normal operations
[Wed Mar 02 14:23:54.370312 2016] [core:notice] [pid 8459] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 02 14:23:59.568825 2016] [mpm_prefork:notice] [pid 8459] AH00169: caught SIGTERM, shutting down
[Wed Mar 02 14:24:00.646129 2016] [mpm_prefork:notice] [pid 8594] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.14 configured -- resuming normal operations
[Wed Mar 02 14:24:00.646181 2016] [core:notice] [pid 8594] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 02 14:24:06.801894 2016] [mpm_prefork:notice] [pid 8594] AH00171: Graceful restart requested, doing restart
[Wed Mar 02 14:24:06.848893 2016] [mpm_prefork:notice] [pid 8594] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.14 configured -- resuming normal operations
[Wed Mar 02 14:24:06.848906 2016] [core:notice] [pid 8594] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 02 14:24:17.168842 2016] [:error] [pid 8662] [client 10.194.141.100:55332] script '/var/www/html/index.php' not found or unable to stat
[Wed Mar 02 14:27:17.082324 2016] [:error] [pid 8663] [client 10.194.141.100:55361] script '/var/www/html/index.php' not found or unable to stat
[Wed Mar 02 14:31:47.068842 2016] [mpm_prefork:notice] [pid 8594] AH00171: Graceful restart requested, doing restart
AH00112: Warning: DocumentRoot [/var/www/html/owncloud] does not exist
[Wed Mar 02 14:31:47.121540 2016] [mpm_prefork:notice] [pid 8594] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.14 configured -- resuming normal operations
[Wed Mar 02 14:31:47.121556 2016] [core:notice] [pid 8594] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 02 14:32:17.390504 2016] [mpm_prefork:notice] [pid 8594] AH00171: Graceful restart requested, doing restart
[Wed Mar 02 14:32:17.437593 2016] [mpm_prefork:notice] [pid 8594] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.14 configured -- resuming normal operations
[Wed Mar 02 14:32:17.437607 2016] [core:notice] [pid 8594] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 02 14:34:31.902036 2016] [authz_core:error] [pid 10579] [client 10.194.141.100:55489] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Wed Mar 02 14:45:59.615066 2016] [mpm_prefork:notice] [pid 8594] AH00169: caught SIGTERM, shutting down
[Wed Mar 02 14:46:16.433333 2016] [mpm_prefork:notice] [pid 1448] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.14 configured -- resuming normal operations
[Wed Mar 02 14:46:16.433963 2016] [core:notice] [pid 1448] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 02 14:51:08.857465 2016] [authz_core:error] [pid 1518] [client 10.194.141.100:38078] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Wed Mar 02 14:51:45.803462 2016] [authz_core:error] [pid 1453] [client 10.194.141.100:38086] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Wed Mar 02 14:54:43.007784 2016] [mpm_prefork:notice] [pid 1448] AH00169: caught SIGTERM, shutting down
[Wed Mar 02 14:54:44.035188 2016] [mpm_prefork:notice] [pid 1972] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.14 configured -- resuming normal operations
[Wed Mar 02 14:54:44.035237 2016] [core:notice] [pid 1972] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 02 14:56:40.467474 2016] [authz_core:error] [pid 1976] [client 10.194.141.100:38166] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Wed Mar 02 15:11:05.569522 2016] [authz_core:error] [pid 1991] [client 10.194.141.100:38276] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Wed Mar 02 15:20:24.227555 2016] [authz_core:error] [pid 2174] [client 10.194.141.100:38307] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Wed Mar 02 15:24:36.277161 2016] [authz_core:error] [pid 2036] [client 10.194.141.100:38347] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Wed Mar 02 15:41:44.599494 2016] [authz_core:error] [pid 2036] [client 10.194.141.100:38542] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata

```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
{"reqId":"Bd04WtTDqqYwFj\/ItZg8","remoteAddr":"10.194.141.100","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(55): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(143): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(617): include('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(568): OC_Installer::includeAppScript('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(542): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/owncloud\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(822): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":53}","level":3,"time":"2016-03-02T12:32:50+00:00"}
{"reqId":"Bd04WtTDqqYwFj\/ItZg8","remoteAddr":"10.194.141.100","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Calendar tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migratecalendars.php(57): OCA\\\\Dav\\\\Migration\\\\CalendarAdapter->setup()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(159): OCA\\\\Dav\\\\Migration\\\\MigrateCalendars->setup()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(27): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateCalendars()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(617): include('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(568): OC_Installer::includeAppScript('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(542): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/owncloud\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(822): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/calendaradapter.php\",\"Line\":49}","level":3,"time":"2016-03-02T12:32:50+00:00"}
{"reqId":"RKiKPFpNtJkqQ936B+Bk","remoteAddr":"10.194.141.100","app":"encryption","message":"no public key found for user \"test1\", user will not be able to read the file","level":2,"time":"2016-03-02T12:58:33+00:00"}
{"reqId":"RKiKPFpNtJkqQ936B+Bk","remoteAddr":"10.194.141.100","app":"PHP","message":"openssl_seal(): Fourth argument to openssl_seal() must be a non-empty array at \/var\/www\/owncloud\/apps\/encryption\/lib\/crypto\/crypt.php#669","level":3,"time":"2016-03-02T12:58:33+00:00"}
{"reqId":"qRY2zu6\/xNBP\/1ql4lWG","remoteAddr":"10.194.141.100","app":"encryption","message":"no public key found for user \"test2\", user will not be able to read the file","level":2,"time":"2016-03-02T12:58:40+00:00"}
{"reqId":"qRY2zu6\/xNBP\/1ql4lWG","remoteAddr":"10.194.141.100","app":"PHP","message":"openssl_seal(): Fourth argument to openssl_seal() must be a non-empty array at \/var\/www\/owncloud\/apps\/encryption\/lib\/crypto\/crypt.php#669","level":3,"time":"2016-03-02T12:58:40+00:00"}
{"reqId":"S\/VZGVSIIlykcqcsnjCG","remoteAddr":"10.194.141.100","app":"encryption","message":"no public key found for user \"test3\", user will not be able to read the file","level":2,"time":"2016-03-02T12:58:48+00:00"}
{"reqId":"S\/VZGVSIIlykcqcsnjCG","remoteAddr":"10.194.141.100","app":"PHP","message":"openssl_seal(): Fourth argument to openssl_seal() must be a non-empty array at \/var\/www\/owncloud\/apps\/encryption\/lib\/crypto\/crypt.php#669","level":3,"time":"2016-03-02T12:58:48+00:00"}
{"reqId":"PXc1nrLWjgJUoO1i8\/I1","remoteAddr":"10.194.141.100","app":"encryption","message":"no public key found for user \"test4\", user will not be able to read the file","level":2,"time":"2016-03-02T12:59:06+00:00"}
{"reqId":"PXc1nrLWjgJUoO1i8\/I1","remoteAddr":"10.194.141.100","app":"PHP","message":"openssl_seal(): Fourth argument to openssl_seal() must be a non-empty array at \/var\/www\/owncloud\/apps\/encryption\/lib\/crypto\/crypt.php#669","level":3,"time":"2016-03-02T12:59:06+00:00"}
{"reqId":"C84XLO6W7SIqpjknmgmX","remoteAddr":"10.194.141.100","app":"encryption","message":"no public key found for user \"test7\", user will not be able to read the file","level":2,"time":"2016-03-02T13:04:30+00:00"}
{"reqId":"C84XLO6W7SIqpjknmgmX","remoteAddr":"10.194.141.100","app":"PHP","message":"openssl_seal(): Fourth argument to openssl_seal() must be a non-empty array at \/var\/www\/owncloud\/apps\/encryption\/lib\/crypto\/crypt.php#669","level":3,"time":"2016-03-02T13:04:30+00:00"}
{"reqId":"97bxqb3zJ2oMOYepaaai","remoteAddr":"10.194.141.101","app":"webdav","message":"Exception: {\"Message\":\"Bad Signature\",\"Exception\":\"OC\\\\HintException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(457): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('3JZ3zEaJLDefOmX...', '?\\\"aQ??r??[;:???...', '6925631b1138c1a...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(364): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('3JZ3zEaJLDefOmX...', '?\\\"aQ??r??[;:???...', 'AES-256-CTR', 2, 0)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(458): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('3JZ3zEaJLDefOmX...', 0)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(289): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(67): fread(Resource id #45, 8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(88): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #48, Resource id #50, '260676')\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(54): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":477}","level":4,"time":"2016-03-02T13:10:24+00:00"}
{"reqId":"c37qp7DLhODx\/rT4BgP3","remoteAddr":"10.194.141.101","app":"webdav","message":"Exception: {\"Message\":\"Bad Signature\",\"Exception\":\"OC\\\\HintException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(457): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('3JZ3zEaJLDefOmX...', '?\\\"aQ??r??[;:???...', '6925631b1138c1a...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(364): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('3JZ3zEaJLDefOmX...', '?\\\"aQ??r??[;:???...', 'AES-256-CTR', 2, 0)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(458): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('3JZ3zEaJLDefOmX...', 0)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(289): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(67): fread(Resource id #45, 8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(88): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #48, Resource id #50, '260676')\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(54): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":477}","level":4,"time":"2016-03-02T13:10:32+00:00"}
{"reqId":"tpRFqmyyduRg78nk0Whr","remoteAddr":"10.194.141.101","app":"webdav","message":"Exception: {\"Message\":\"Bad Signature\",\"Exception\":\"OC\\\\HintException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(457): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('3JZ3zEaJLDefOmX...', '?\\\"aQ??r??[;:???...', '6925631b1138c1a...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(364): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('3JZ3zEaJLDefOmX...', '?\\\"aQ??r??[;:???...', 'AES-256-CTR', 2, 0)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(458): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('3JZ3zEaJLDefOmX...', 0)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(289): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(67): fread(Resource id #45, 8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(88): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #48, Resource id #50, '260676')\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(54): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":477}","level":4,"time":"2016-03-02T13:10:38+00:00"}
{"reqId":"2KqS0JCb4+A+zrVDi2J5","remoteAddr":"10.194.141.101","app":"webdav","message":"Exception: {\"Message\":\"Bad Signature\",\"Exception\":\"OC\\\\HintException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(457): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('3JZ3zEaJLDefOmX...', '?\\\"aQ??r??[;:???...', '6925631b1138c1a...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(364): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('3JZ3zEaJLDefOmX...', '?\\\"aQ??r??[;:???...', 'AES-256-CTR', 2, 0)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(458): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('3JZ3zEaJLDefOmX...', 0)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(289): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(67): fread(Resource id #45, 8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(88): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #48, Resource id #50, '260676')\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(54): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":477}","level":4,"time":"2016-03-02T13:11:37+00:00"}
{"reqId":"oS7mL5b1JMBhMYQZAxL3","remoteAddr":"10.194.141.101","app":"webdav","message":"Exception: {\"Message\":\"Bad Signature\",\"Exception\":\"OC\\\\HintException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(457): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('3JZ3zEaJLDefOmX...', '?\\\"aQ??r??[;:???...', '6925631b1138c1a...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(364): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('3JZ3zEaJLDefOmX...', '?\\\"aQ??r??[;:???...', 'AES-256-CTR', 2, 0)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(458): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('3JZ3zEaJLDefOmX...', 0)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(289): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(67): fread(Resource id #45, 8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(88): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #48, Resource id #50, '260676')\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(54): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":477}","level":4,"time":"2016-03-02T13:14:33+00:00"}
{"reqId":"tCheEpRm0KIU3aXymy4m","remoteAddr":"10.194.141.101","app":"webdav","message":"Exception: {\"Message\":\"Bad Signature\",\"Exception\":\"OC\\\\HintException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(457): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('3JZ3zEaJLDefOmX...', '?\\\"aQ??r??[;:???...', '6925631b1138c1a...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(364): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('3JZ3zEaJLDefOmX...', '?\\\"aQ??r??[;:???...', 'AES-256-CTR', 2, 0)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(458): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('3JZ3zEaJLDefOmX...', 0)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(289): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(67): fread(Resource id #45, 8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(88): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #48, Resource id #50, '260676')\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(54): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":477}","level":4,"time":"2016-03-02T13:15:19+00:00"}
{"reqId":"hseVu8qIpJYpzq5aXcWj","remoteAddr":"10.194.141.101","app":"webdav","message":"Exception: {\"Message\":\"Bad Signature\",\"Exception\":\"OC\\\\HintException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(457): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('3JZ3zEaJLDefOmX...', '?\\\"aQ??r??[;:???...', '6925631b1138c1a...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(364): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('3JZ3zEaJLDefOmX...', '?\\\"aQ??r??[;:???...', 'AES-256-CTR', 2, 0)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(458): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('3JZ3zEaJLDefOmX...', 0)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(289): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(67): fread(Resource id #45, 8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(88): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #48, Resource id #50, '260676')\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(54): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":477}","level":4,"time":"2016-03-02T13:15:37+00:00"}
{"reqId":"8OC0geEN4kde+vSJ9SXD","remoteAddr":"10.194.141.101","app":"webdav","message":"Exception: {\"Message\":\"Bad Signature\",\"Exception\":\"OC\\\\HintException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(457): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('6+0Bb6VY5pB8BF4...', '{E5???b???????....', '2839c5aeda3997c...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(364): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('6+0Bb6VY5pB8BF4...', '{E5???b???????....', 'AES-256-CTR', 2, '0end')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(458): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('6+0Bb6VY5pB8BF4...', '0end')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(289): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(67): fread(Resource id #45, 8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(88): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #48, Resource id #50, '8')\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(54): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":477}","level":4,"time":"2016-03-02T13:20:37+00:00"}
{"reqId":"fRLrXdaoOr3ONWX1fj41","remoteAddr":"10.194.141.101","app":"webdav","message":"Exception: {\"Message\":\"Bad Signature\",\"Exception\":\"OC\\\\HintException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(457): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('6+0Bb6VY5pB8BF4...', '{E5???b???????....', '2839c5aeda3997c...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(364): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('6+0Bb6VY5pB8BF4...', '{E5???b???????....', 'AES-256-CTR', 2, '0end')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(458): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('6+0Bb6VY5pB8BF4...', '0end')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(289): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(67): fread(Resource id #45, 8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(88): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #48, Resource id #50, '8')\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(54): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":477}","level":4,"time":"2016-03-02T13:20:38+00:00"}
{"reqId":"E9\/mvZhj1Of5b24ATDPo","remoteAddr":"10.194.141.101","app":"webdav","message":"Exception: {\"Message\":\"Bad Signature\",\"Exception\":\"OC\\\\HintException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(457): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('CsuaoG1l5qKwUyI...', '???????#??????m...', 'e8c43d56a866cf9...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(364): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('CsuaoG1l5qKwUyI...', '???????#??????m...', 'AES-256-CTR', 4, '0end')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(458): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('CsuaoG1l5qKwUyI...', '0end')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(289): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(67): fread(Resource id #45, 8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(88): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #48, Resource id #50, '4')\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(54): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":477}","level":4,"time":"2016-03-02T13:24:38+00:00"}
{"reqId":"\/Dpf7+3s15CL7U\/dNlhA","remoteAddr":"10.194.141.101","app":"webdav","message":"Exception: {\"Message\":\"Bad Signature\",\"Exception\":\"OC\\\\HintException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(457): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('CsuaoG1l5qKwUyI...', '???????#??????m...', 'e8c43d56a866cf9...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(364): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('CsuaoG1l5qKwUyI...', '???????#??????m...', 'AES-256-CTR', 4, '0end')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(458): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('CsuaoG1l5qKwUyI...', '0end')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(289): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(67): fread(Resource id #45, 8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(88): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #48, Resource id #50, '4')\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(54): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":477}","level":4,"time":"2016-03-02T13:25:38+00:00"}
{"reqId":"0IIPNylP9TZwDmvKBs\/d","remoteAddr":"10.194.141.101","app":"webdav","message":"Exception: {\"Message\":\"Bad Signature\",\"Exception\":\"OC\\\\HintException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(457): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('CsuaoG1l5qKwUyI...', '???????#??????m...', 'e8c43d56a866cf9...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(364): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('CsuaoG1l5qKwUyI...', '???????#??????m...', 'AES-256-CTR', 4, '0end')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(458): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('CsuaoG1l5qKwUyI...', '0end')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(289): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(67): fread(Resource id #45, 8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(88): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #48, Resource id #50, '4')\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(54): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":477}","level":4,"time":"2016-03-02T13:46:53+00:00"}
{"reqId":"+wb7L+NwVz4bipJPgpdn","remoteAddr":"10.194.141.101","app":"webdav","message":"Exception: {\"Message\":\"Bad Signature\",\"Exception\":\"OC\\\\HintException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(457): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('7rjfkA0Cfev6fGM...', '???F???Z?^????d...', '1917f8df5921f45...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(364): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('7rjfkA0Cfev6fGM...', '???F???Z?^????d...', 'AES-256-CTR', 2, 0)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(458): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('7rjfkA0Cfev6fGM...', 0)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(289): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(67): fread(Resource id #45, 8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(88): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #48, Resource id #50, '251914')\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(54): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":477}","level":4,"time":"2016-03-02T13:54:08+00:00"}
{"reqId":"3D7b0qQi9bBsIqHItnPy","remoteAddr":"10.194.141.101","app":"webdav","message":"Exception: {\"Message\":\"Bad Signature\",\"Exception\":\"OC\\\\HintException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(457): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('7rjfkA0Cfev6fGM...', '???F???Z?^????d...', '1917f8df5921f45...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(364): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('7rjfkA0Cfev6fGM...', '???F???Z?^????d...', 'AES-256-CTR', 2, 0)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(458): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('7rjfkA0Cfev6fGM...', 0)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(289): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(67): fread(Resource id #45, 8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(88): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #48, Resource id #50, '251914')\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(54): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":477}","level":4,"time":"2016-03-02T13:55:08+00:00"}
{"reqId":"35Kz4k12iYkk9Se5FwJi","remoteAddr":"10.194.141.101","app":"webdav","message":"Exception: {\"Message\":\"Bad Signature\",\"Exception\":\"OC\\\\HintException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(457): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('7rjfkA0Cfev6fGM...', '???F???Z?^????d...', '1917f8df5921f45...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(364): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('7rjfkA0Cfev6fGM...', '???F???Z?^????d...', 'AES-256-CTR', 2, 0)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(458): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('7rjfkA0Cfev6fGM...', 0)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(289): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(67): fread(Resource id #45, 8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(88): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #48, Resource id #50, '251914')\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(54): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":477}","level":4,"time":"2016-03-02T13:57:48+00:00"}
```

#### Browser log
```
```

### PR DESCRIPTION
**Pull request by LukasReschke**
When calling `\OC\Files\View::copy` we should also keep the version to ensure that the file will always have the correct version attached and can be successfully decrypted.

To test this the following steps are necessary (from https://github.com/owncloud/core/issues/22781#issuecomment-191328982):
1. setup a new ownCloud 9.0 beta2
2. enable encryption
3. upload a docx (5.7MB large)
4. upload the same file again and overwrite the existing file
5. I can download the original file and the first version
6. I restore the first version
7. restored version can no longer be downloaded with the error described above

The manual cache operation in `\OCA\Files_Versions\Storage` is unfortunately necessary since `\OCA\Files_Versions\Storage::copyFileContents` is not using `\OCP\Files\Storage::moveFromStorage` in the case when an object storage is used. Due to the workaround added in https://github.com/owncloud/core/commit/54cea05271b887f1c8062c034741df869bc0f055 the stream is directly copied and thus bypassing the FS.

Fixes https://github.com/owncloud/core/issues/22781

@schiesbn @shhristov Mind testing? Thanks a lot.
@karlitschek IMHO we should backport this into 9.0.0. While the actual issue is kinda low severity the fact that `\OC\Files\View::copy` has not copied the version kinda irritates me and could lead to other more severe issues at other places.

### CODE REVIEW

File: apps/files_versions/lib/storage.php [hunk 1]
```diff
@@ -191,12 +191,7 @@ public static function store($filename) {
 			$mtime = $users_view->filemtime('files/' . $filename);
 			$users_view->copy('files/' . $filename, 'files_versions/' . $filename . '.v' . $mtime);
 			// call getFileInfo to enforce a file cache entry for the new version
-			$newFileInfo = $users_view->getFileInfo('files_versions/' . $filename . '.v' . $mtime);
-
-			// Keep the "encrypted" value of the original file
-			$oldVersion = $files_view->getFileInfo($filename)->getEncryptedVersion();
-			$cache = $newFileInfo->getStorage()->getCache();
-			$cache->update($newFileInfo->getId(), ['encrypted' => $oldVersion, 'encryptedVersion' => $oldVersion]);
+			$users_view->getFileInfo('files_versions/' . $filename . '.v' . $mtime);
```
Comment (LukasReschke) [inline apps/files_versions/lib/storage.php]: This is what we had before https://github.com/owncloud/core/commit/5ccb9dfa7e35d78d61d7a973ee2a5fddfda7d766. The copy method now takes care of this.

File: apps/files_versions/lib/storage.php [hunk 2]
```diff
@@ -331,15 +326,22 @@ public static function rollback($file, $revision) {
...
 			}
 
+			$fileToRestore =  'files_versions' . $filename . '.v' . $revision;
+
+			// Restore encrypted version of the old file for the newly restored file
+			// This has to happen manually here since the file is manually copied below
+			$oldVersion = $users_view->getFileInfo($fileToRestore)->getEncryptedVersion();
+			$newFileInfo = $files_view->getFileInfo($filename);
+			$cache = $newFileInfo->getStorage()->getCache();
+			$cache->update($newFileInfo->getId(), ['encrypted' => $oldVersion, 'encryptedVersion' => $oldVersion]);
```
Comment (LukasReschke) [inline apps/files_versions/lib/storage.php]: The ugly mentioned hack due to the manual stream copy because of https://github.com/owncloud/core/commit/54cea05271b887f1c8062c034741df869bc0f055

**Comment by LukasReschke** [comment]
@icewind1991 I'd welcome if you could also take a look at this. Thanks a lot!

**Comment by karlitschek** [comment]
Hmm. I can see scenarios where this is seen as data lose. So I'm fine with backporting this.
@cmonteroluque FYI

File: lib/private/files/storage/wrapper/encryption.php [hunk 3]
```diff
@@ -689,15 +716,7 @@ private function copyBetweenStorage(Storage $sourceStorage, $sourceInternalPath,
...
-				$isEncrypted = $this->encryptionManager->isEnabled() && $this->mount->getOption('encrypt', true) ? 1 : 0;
-
-				// in case of a rename we need to manipulate the source cache because
-				// this information will be kept for the new target
-				if ($isRename) {
-					$sourceStorage->getCache()->put($sourceInternalPath, ['encrypted' => $isEncrypted]);
-				} else {
-					$this->getCache()->put($targetInternalPath, ['encrypted' => $isEncrypted]);
-				}
+				$this->updateEncryptedVersion($sourceStorage, $sourceInternalPath, $targetInternalPath, $isRename);
```
Comment (PVince81) [inline lib/private/files/storage/wrapper/encryption.php]: we should probably also test Webdav's COPY method between a local folder and shared folder as recipient, which is likely to use `copyBetweenStorage` as well

**Comment by PVince81** [comment]
@icewind1991 please review this too for cache manipulations

File: lib/private/files/storage/wrapper/encryption.php [hunk 4]
```diff
@@ -621,6 +621,32 @@ public function copyFromStorage(Storage $sourceStorage, $sourceInternalPath, $ta
...
+	 * @param string $targetInternalPath
+	 * @param bool $isRename
+	 */
+	private function updateEncryptedVersion(Storage $sourceStorage, $sourceInternalPath, $targetInternalPath, $isRename) {
+		$isEncrypted = $this->encryptionManager->isEnabled() && $this->mount->getOption('encrypt', true) ? 1 : 0;
+		$cacheInformation = [
+			'encrypted' => (bool)$isEncrypted,
+		];
+		if($isEncrypted === 1) {
+			$cacheInformation['encryptedVersion'] = $this->getCache('', $sourceStorage)->get($sourceInternalPath)['encryptedVersion'];
```
Comment (PVince81) [inline lib/private/files/storage/wrapper/encryption.php]: Shouldn't this be `$sourceStorage->getCache()` ?
@icewind1991 can you double check this ?

**Comment by PVince81** [comment]
- [x] TEST: original steps but with big mp4 file (I had it reproduced on 8.2.2)
- [x] TEST: delete shared file as recipient, copies to trash, restore, download works
- [x] TEST: Webdav COPY to shared folder as recipient, download works
- [x] TEST: Webdav COPY from local to ext storage, download works

**Comment by schiesbn** [comment]
tested and works :+1:

**Comment by schiesbn** [comment]
I still consider this a ugly hack. Why does the versions app needs to know about some internal file cache stuff regarding encryption. I fear that other apps will pop up as well where a copy/rename might kill encrypted files. For example we have apps in the app store which enable the user to move files to a random directory.

I think the file cache should take care to preserve all file cache meta data during copy/move... @icewind1991 what do you think?

**Comment by LukasReschke** [comment]
> I still consider this a ugly hack. Why does the versions app needs to know about some internal file cache stuff regarding encryption.

Because of the ugly hack added in https://github.com/owncloud/core/commit/54cea05271b887f1c8062c034741df869bc0f055. If we're on an object store the file system layer is not called and instead the stream is manually copied. There is not much that we can do instead of fixing https://github.com/owncloud/core/commit/54cea05271b887f1c8062c034741df869bc0f055 :wink: 

> I fear that other apps will pop up as well where a copy/rename might kill encrypted files. For example we have apps in the app store which enable the user to move files to a random directory.

Well. It will work fine if they use the internal FS functions. If they bypass it like 54cea05271b887f1c8062c034741df869bc0f055 it will fail, but would have failed anyways given the fact that the keys are not copied etc…

**Comment by LukasReschke** [comment]
But yes: It's a hack to workaround another hack. Not very cool :see_no_evil:

**Comment by schiesbn** [comment]
> Because of the ugly hack added in 54cea05. If we're on an object store the file system layer is not called and instead the stream is manually copied. There is not much that we can do instead of fixing 54cea05 :wink:

I agree, we should never by-pass the filesystem layer.

But at least it reduces the risk that other apps might fail as well, if this is the reason why it fails for versions.

File: lib/private/files/storage/wrapper/encryption.php (hunk 4 above)
Comment (icewind1991) [inline lib/private/files/storage/wrapper/encryption.php]: Yes it should

**Comment by icewind1991** [comment]
Long term we should look into fixing trashbin to properly use the fs layer, for now I'm fine with this once the `getCache` issue @PVince81 pointed out is fixed

**Comment by LukasReschke** [comment]
> Long term we should look into fixing trashbin to properly use the fs layer, for now I'm fine with this once the getCache issue @PVince81 pointed out is fixed

Adjusted.

**Comment by PVince81** [comment]
:+1:

Can we have a tech debt ticket to look into making this clean as mentioned by @schiesbn @icewind1991 ?

**Comment by icewind1991** [comment]
:+1:

**Comment by LukasReschke** [comment]
Tech debt ticket: https://github.com/owncloud/core/issues/22817

**Comment by LukasReschke** [comment]
Backport to 9.0: Backport to 9.0: https://github.com/owncloud/core/pull/22818
