### PR TITLE
[stable8.1] Backport scanfilesignature

### LINKED ISSUE #17455: After upgrade to 8.1 my log is spammed with Declaration of OCA\Files_Sharing\External\Scanner::scanFile() should be compatible with OC\Files\Cache\Scanner::scanFile(
Steps to reproduce

1. Upgrade from 8.0.4 to 8.1

### Expected behavior
ownCloud should upgrade to 8.1 without any issues and log shouldn't be spammed.

### Actual Behavior
Log gets spammed with 

```
Declaration of OCA\Files_Sharing\External\Scanner::scanFile() should be compatible with OC\Files\Cache\Scanner::scanFile($file, $reuseExisting = 0, $parentId = -1, $cacheData = NULL, $lock = true) at /var/www/owncloud/apps/files_sharing/lib/external/scanner.php#0 
```

### Server configuration
**Operating system**:
Ubuntu Server 14.04.2
**Web server:**

**Database:**
Server version: 5.5.43-0ubuntu0.14.04.1 (Ubuntu)

**PHP version:**
PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)
8.1

**Updated from an older ownCloud or fresh install:**
Updated from 8.0.4

**List of activated apps:**

```
Enabled:
 - activity: 2.0.1
 - calendar: 0.7.1
 - documents: 0.9.0
 - files: 1.1.9
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - mail: 0.1.3
 - tasks: 0.6.0
 - templateeditor: 0.1
Disabled:
 - encryption
 - external
 - files_external
 - music
 - provisioning_api
 - search_lucene
 - user_external
 - user_ldap
 - user_webdavauth

```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc106ccbdf7c',
  'passwordsalt' => 'SECRET',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud',
  'dbhost' => 'en0ch.se',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_enoch',
  'dbpassword' => 'SECRET',
  'installed' => true,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'session_lifetime' => 1800,
  'forcessl' => true,
  'updatechecker' => true,
  'loglevel' => 2,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' =>
  array (
    0 => 'en0ch.se',
    1 => 'www.en0ch.se',
  ),
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'enable_previews' => true,
  'app.mail.server-side-cache.enabled' => true,
  'app.mail.imaplog.enabled' => true,
  'logtimezone' => 'Europe/Stockholm',
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### ownCloud log (data/owncloud.log)
```
Error 	PHP 	Declaration of OCA\Files_Sharing\External\Scanner::scanFile() should be compatible with OC\Files\Cache\Scanner::scanFile($file, $reuseExisting = 0, $parentId = -1, $cacheData = NULL, $lock = true) at /var/www/owncloud/apps/files_sharing/lib/external/scanner.php#0 	2015-07-07T19:18:33+02:00
Error 	PHP 	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35 	2015-07-07T19:15:02+02:00
Error 	PHP 	Declaration of OCA\Files_Sharing\External\Scanner::scanFile() should be compatible with OC\Files\Cache\Scanner::scanFile($file, $reuseExisting = 0, $parentId = -1, $cacheData = NULL, $lock = true) at /var/www/owncloud/apps/files_sharing/lib/external/scanner.php#0 	2015-07-07T19:03:30+02:00
Error	PHP	Method OC_L10N_String::__toString() must return a string value at /var/www/owncloud/lib/private/util.php#1106	2015-07-07T19:03:16+02:00
Error	PHP	vsprintf(): Too few arguments at /var/www/owncloud/lib/private/l10n/string.php#76	2015-07-07T19:03:16+02:00
Error	PHP	Declaration of OCA\Files_Sharing\External\Scanner::scanFile() should be compatible with OC\Files\Cache\Scanner::scanFile($file, $reuseExisting = 0, $parentId = -1, $cacheData = NULL, $lock = true) at /var/www/owncloud/apps/files_sharing/lib/external/scanner.php#0	2015-07-07T19:03:10+02:00
Error	PHP	Class 'OC_FileProxy' not found at /var/www/owncloud/apps/documents/lib/genesis.php#90	2015-07-07T19:02:36+02:00
Error	PHP	Declaration of OCA\Files_Sharing\External\Scanner::scanFile() should be compatible with OC\Files\Cache\Scanner::scanFile($file, $reuseExisting = 0, $parentId = -1, $cacheData = NULL, $lock = true) at /var/www/owncloud/apps/files_sharing/lib/external/scanner.php#0	2015-07-07T19:02:27+02:00
```

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport of https://github.com/owncloud/core/pull/17295

Fixes #17455

### CODE REVIEW

**Comment by nickvergessen** [comment]
Can we please have a test that calls this code? Those two scanners (share + objectstore) broke like 5 times in the last two releases.

File: apps/files_sharing/lib/external/scanner.php [hunk 1]
```diff
@@ -48,9 +48,11 @@ public function scan($path, $recursive = self::SCAN_RECURSIVE, $reuse = -1, $loc
 	 * @param int $reuseExisting
 	 * @param int $parentId
 	 * @param array | null $cacheData existing data in the cache for the file to be scanned
+	 * @param bool $lock set to false to disable getting an additional read lock during scanning
+	 * @param array | null $cacheData existing data in the cache for the file to be scanned
```
Comment (nickvergessen) [inline apps/files_sharing/lib/external/scanner.php]: you cherry picked the duplication as well

Comment (nickvergessen) [inline apps/files_sharing/lib/external/scanner.php]: See the follow up PR of the original:  #17324

**Comment by PVince81** [comment]
@nickvergessen this is about the function signature that doesn't match. Is this unit-testable ?

**Comment by DeepDiver1975** [comment]
> Can we please have a test that calls this code? Those two scanners (share + objectstore) broke like 5 times in the last two releases.

go ahead ;-)

**Comment by nickvergessen** [comment]
> @nickvergessen this is about the function signature that doesn't match. Is this unit-testable ?

In the other PR you said you fix it to avoid "boring warnings". But now I see what you mean, it's "valid" php and just an IDE warning

**Comment by MorrisJobke** [comment]
@enoch85 Mind to test this?

**Comment by MorrisJobke** [comment]
cc @icewind1991 please review

**Comment by enoch85** [comment]
Have not tested but the code is the same as for 8.2 and that works, so :+1:

**Comment by MorrisJobke** [comment]
cc @karlitschek because this is a backport of a crucial fix.

**Comment by nickvergessen** [comment]
https://gist.github.com/nickvergessen/753f0f97970a16047aee

Will add this test in master and here

**Comment by nickvergessen** [comment]
Test for master is in #18262
I added the commit to this PR as well

**Comment by nickvergessen** [comment]
@owncloud-bot retest this please

**Comment by Xenopathic** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1:
