### PR TITLE
Correctly split and join group list with | instead of ,

### LINKED ISSUE #15377: Error Enabled Apps per groups
### Steps to reproduce

1. Enable Apps with "Enable only for specific groups "
2. Add several groups

### Expected behaviour

The apps are only enabled for these groups

### Actual behaviour

When there are multiple configured groups (local or LDAP), apps do not appear. 

### Server configuration

Debian 7.5
Apache2
MySQL
5.4.39
Owncloud 8.0.2
Fresh install
User-backend : LDAP/ActiveDirectory

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #15377

Partly backport of #15149
@LukasReschke @MorrisJobke @icewind1991

### CODE REVIEW

File: settings/js/apps.js [hunk 1]
```diff
@@ -125,7 +125,7 @@ OC.Settings.Apps = OC.Settings.Apps || {
 			page.find("label[for='groups_enable-"+app.id+"']").hide();
 			page.find(".groups-enable").attr('checked', null);
 		} else {
-			page.find('#group_select').val((app.groups || []).join(','));
+			page.find('#group_select').val((app.groups || []).join('|'));
```
Comment (nickvergessen) [inline settings/js/apps.js]: This was missed on the master PR: #15149
Will do a second PR

**Comment by MorrisJobke** [comment]
:+1:

**Comment by icewind1991** [comment]
:+1:
