### PR TITLE
Ignore favorites that are not available when creating the favorites list

### LINKED ISSUE #13475: Can not (de)favorite a file from external storage when oC can not connect to it
`$fileId = $this->homeFolder->get($path)->getId();` in `OCA\Files\Service\TagService::updateFileTags($path, $tags)` throws an exception.

### PR DESCRIPTION
**Pull request by nickvergessen**
Also correctly return the exception for all cases when adding/removing favos

Fix #13475

### CODE REVIEW

File: apps/files/controller/apicontroller.php [hunk 1]
```diff
@@ -76,6 +76,10 @@ public function updateFileTags($path, $tags = null) {
 				$this->tagService->updateFileTags($path, $tags);
 			} catch (\OCP\Files\NotFoundException $e) {
 				return new DataResponse($e->getMessage(), Http::STATUS_NOT_FOUND);
+			} catch (\OCP\Files\StorageNotAvailableException $e) {
+				return new DataResponse($e->getMessage(), Http::STATUS_SERVICE_UNAVAILABLE);
+			} catch (\Exception $e) {
+				return new DataResponse($e->getMessage(), Http::STATUS_NOT_FOUND);
```
Comment (nickvergessen) [inline apps/files/controller/apicontroller.php]: Would be nice, to print this information to the user, I think it is this JS:
https://github.com/owncloud/core/blob/d253ef51a567fc163fe2d3d7c3369553fb0cd965/apps/files/js/tagsplugin.js#L166-166

File: apps/files/service/tagservice.php [hunk 2]
```diff
@@ -84,11 +86,19 @@ public function getFilesByTag($tagName) {
...
 		);
-		foreach ($nodes as &$node) {
-			$node = $node->getFileInfo();
+		$fileInfos = [];
+		foreach ($nodes as $node) {
+			try {
+				/** @var \OC\Files\Node\Node $node */
+				$fileInfos[] = $node->getFileInfo();
+			} catch (\Exception $e) {
+				// FIXME Should notify the user, when this happens
```
Comment (nickvergessen) [inline apps/files/service/tagservice.php]: Not sure how to best do this, atm.
But ignoring one is better then ignoring all for now.

**Comment by nickvergessen** [comment]
@PVince81 please take over :)

File: apps/files/service/tagservice.php (hunk 2 above)
Comment (PVince81) [inline apps/files/service/tagservice.php]: Yes, should be fine.
In the future we might want to have something like "UnavailableFileInfo" or some "FileInfo" attribute.
This will especially be important once we bring the "storage unavailable" concept to core (the thing that WND already does)

File: apps/files/controller/apicontroller.php (hunk 1 above)
Comment (PVince81) [inline apps/files/controller/apicontroller.php]: Question is: what to do if one file in a list of 5 isn't available for tagging.
Should the whole operation fail ?
Or should we ignore the one ? And maybe return the status for every file ?

I'd say nothing for now.
I believe that WebDAV is able to return per-file status codes when calling PROPPATCH, so might be doable once we move the files app to WebDAV.

Comment (PVince81) [inline apps/files/controller/apicontroller.php]: Hmm, but in the favorites case we only ever tag a single file, so I see your point.
Then returning the exception like this might be fine for now.

Comment (nickvergessen) [inline apps/files/controller/apicontroller.php]: I would put it in one of that shiny yellow boxes at the top?

**Comment by nickvergessen** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
Not a showstopper, setting to 8.1

**Comment by nickvergessen** [comment]
Huuu? a favorite on a disconnected external storage disables the complete favorite list.

I'd say the yellow bar is not a show stopper, but at least the exception fix I made is.

**Comment by PVince81** [comment]
Ah, it disables the whole list ? I thought it just shows the entry but doesn't let you unshare.

Then your fix is fine. :+1: 

Show a notification on the specific broken entry will not be possible until we bring the WND/sharepoint red highlight logic to core.

File: apps/files/controller/apicontroller.php (hunk 1 above)
Comment (PVince81) [inline apps/files/controller/apicontroller.php]: This could be added here: https://github.com/owncloud/core/blob/master/apps/files/js/tagsplugin.js#L110
Need to figure out how to detect a failed promise (possibly .fail(function() {...} or something).
Then call `OC.Notification.showTemporary()` for the yellow box

**Comment by MorrisJobke** [comment]
> Show a notification on the specific broken entry will not be possible until we bring the WND/sharepoint red highlight logic to core.

Is there already a ticket for that?

**Comment by PVince81** [comment]
@MorrisJobke this one: https://github.com/owncloud/sharepoint/issues/120
It's in that repo because that's where the code is that needs to be reused.

File: apps/files/controller/apicontroller.php [hunk 3]
```diff
@@ -89,6 +94,7 @@ public function updateFileTags($path, $tags = null) {
 	 * @CORS
 	 *
 	 * @param array $tagName tag name to filter by
+	 * @return \OCP\AppFramework\Http\Response
```
Comment (LukasReschke) [inline apps/files/controller/apicontroller.php]: `DataResponse`?

Comment (nickvergessen) [inline apps/files/controller/apicontroller.php]: done

**Comment by nickvergessen** [comment]
@owncloud-bot re-test this please

**Comment by nickvergessen** [comment]
Second review @MorrisJobke or @LukasReschke

**Comment by LukasReschke** [comment]
:+1:
