### PR TITLE
Etc timezones don't exist for .5 and .75 offsets

### LINKED ISSUE #14176: OC8: DateTimeZone::__construct(): Unknown or bad timezone ()
Howdy,

I'm not sure if I'm conflating two issues here or not but the errors here are quite similar. This started happened as far as I can tell after the upgrade to 8.0 from 7 via the Suse Build service repo. This error occurs on Ubuntu 14.04.1.

### Steps to reproduce
1. start up apache and let own cloud run

### Expected behaviour
No errors :-)

### Actual behaviour
DateTimeZone::__construct() errors in own cloud.log  (see below)

### Server configuration
Ubuntu 14.04.1

**Web server:**
apache2 2.4.9

**Database:**
mysql 5.5.41

**PHP version:**
php5 5.5.9

**ownCloud version:**
owncloud 8.0.0-5

**Updated from an older ownCloud or fresh install:**
updated via repo

**List of activated apps:**
* activity
* app framework
* bookmarks
* deleted files
* documents
* external sites
* first run wizard
* full text search
* mail template editor
* pdf viewer
* pictures
* share files
* text editor
* versions
* video viewer

I should point out that I disabled calendar because I was also seeing these message in the calendar app sporadically. I left the Calendar app disabled for troubleshooting.

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'installed' => true,
  'dbtype' => 'mysql',
  'dbname' => 'owncloud',
  'dbuser' => 'owncloud',
  'dbpassword' => 'XXXX',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'passwordsalt' => 'XXX',
  'forcessl' => true,
  'blacklisted_files' =>
  array (
    0 => '.htaccess',
  ),
  'overwritehost' => '',
  'overwriteprotocol' => '',
  'overwritewebroot' => '/owncloud',
  'overwritecondaddr' => '',
  'proxy' => '',
  'proxyuserpwd' => '',
  'overwrite.cli.url' => 'owncloud',
  'trusted_domains' =>
  array (
    0 => 'ourowncloud.org',
    1 => 'www.ourowncloud.org',
  ),
  'theme' => '',
  'default_language' => 'en',
  '3rdpartyroot' => '',
  '3rdpartyurl' => '',
  'defaultapp' => 'files',
  'knowledgebaseenabled' => true,
  'appstoreenabled' => true,
  'appstoreurl' => 'http://api.apps.owncloud.com/v1',
  'mail_domain' => 'ourowncloud.org',
  'mail_smtpdebug' => false,
  'mail_smtpmode' => 'php',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => '25',
  'mail_smtptimeout' => 10,
  'mail_smtpauthtype' => 'LOGIN',
  'memcached_server' =>
  array (
    0 => 'localhost',
    1 => 11211,
  ),
  'trashbin_retention_obligation' => 30,
  'trashbin_auto_expire' => true,
  'allow_user_to_change_display_name' => true,
  'appcodechecker' => '',
  'updatechecker' => true,
  'has_internet_connection' => true,
  'check_for_working_webdav' => false,
  'check_for_working_htaccess' => true,
  'log_type' => 'owncloud',
  'logfile' => '',
  'loglevel' => '2',
  'logdateformat' => 'F d, Y H:i:s',
  'logtimezone' => 'America/Denver',
  'log_query' => false,
  'log_authfailip' => true,
  'log_rotate_size' => false,
  'remember_login_cookie_lifetime' => 1296000,
  'session_lifetime' => 86400,
  'session_keepalive' => true,
  'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-eval\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src *',
  'xframe_restriction' => true,
  'maintenance' => false,
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
  'customclient_desktop' => '',
  'customclient_android' => '',
  'customclient_ios' => '',
  'enable_previews' => true,
  'preview_max_x' => NULL,
  'preview_max_y' => NULL,
  'preview_max_scale_factor' => 10,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'preview_office_cl_parameters' => '',
  'enable_avatars' => true,
  'openssl' =>
  array (
  ),
  'singleuser' => false,
  'instanceid' => 'ocd217a6d34e',
  'version' => '8.0.0.7',
  'datadirectory' => '/srv/owncloud',
  'mail_from_address' => 'mail',
  'secret' => 'XXX',
);
```

**Are you using external storage, if yes which one:** 

data directory is mapped in the config to
/dev/sdb1   /srv/owncloud/ ext4     defaults    0 1

**Are you using encryption:**
no

#### Web server error log

There are no errors in apache2 error.log

#### ownCloud log (data/owncloud.log)
```
{"reqId":"d1732bb3cde2a7f41de017c05b9b4ed3","remoteAddr":"","app":"no app in context","message":"Error while running background job: DateTimeZone::__construct(): Unknown or bad timezone ()","level":3,"time":"February 12, 2015 12:00:02"}
{"reqId":"d1732bb3cde2a7f41de017c05b9b4ed3","remoteAddr":"","app":"PHP","message":"DateTimeZone::__construct(): Unknown or bad timezone () at \/var\/www\/owncloud\/apps\/activity\/lib\/mailqueuehandler.php#198","level":3,"time":"February 12, 2015 12:00:02"}
{"reqId":"1bedbab15f65c79363de798b47990240","remoteAddr":"","app":"no app in context","message":"Error while running background job: DateTimeZone::__construct(): Unknown or bad timezone ()","level":3,"time":"February 12, 2015 12:15:02"}
{"reqId":"1bedbab15f65c79363de798b47990240","remoteAddr":"","app":"PHP","message":"DateTimeZone::__construct(): Unknown or bad timezone () at \/var\/www\/owncloud\/apps\/activity\/lib\/mailqueuehandler.php#198","level":3,"time":"February 12, 2015 12:15:02"}
{"reqId":"127247bd596dbfa8a13e2bd83e43a420","remoteAddr":"","app":"no app in context","message":"Error while running background job: DateTimeZone::__construct(): Unknown or bad timezone ()","level":3,"time":"February 12, 2015 12:30:02"}
```

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #14176, #14391 

@phritter @rinchen @bit can you test this please?

cc @LukasReschke 

@DeepDiver1975 should backport
### To test:
1. Change your local Computer timezone to `Asia/Kathmandu`
2. Log in into ownCloud
3. Create a folder to trigger an activity
4. Wait until the activity email is sent, or force it by setting `oc_activity_mq`.`amq_latest_send` to `1` for the entry aswell as `oc_jobs`.`last_run` for `OCA\Activity\BackgroundJob\EmailNotification`

### CODE REVIEW

File: lib/private/datetimezone.php [hunk 1]
```diff
@@ -43,20 +43,52 @@ public function __construct(IConfig $config, ISession $session) {
...
+				return 'UTC';
+			} else if ($offset > 0) {
+				return 'Etc/GMT-' . $offset;
+			} else  {
+				return 'Etc/GMT+' . abs($offset);
+			}
+		}
+
+		switch ($offset) {
+			case -4.5:
```
Comment (bantu) [inline lib/private/datetimezone.php]: Use an array/map instead?

Comment (bantu) [inline lib/private/datetimezone.php]: Do these timezone offsets uniquely identify the timezone or are you just returning a candidate timezone? I don't think so. Should probably explain this in a comment. Also, if only returning a candidate, this can result in incorrect behaviour (e.g. due to DST definition tied to timezone).

Comment (bantu) [inline lib/private/datetimezone.php]: Can't use array. Floats are cast to integer. Add as comment?

File: lib/private/datetimezone.php [hunk 2]
```diff
@@ -43,20 +43,52 @@ public function __construct(IConfig $config, ISession $session) {
 	public function getTimeZone() {
 		$timeZone = $this->config->getUserValue($this->session->get('user_id'), 'core', 'timezone', null);
 		if ($timeZone === null) {
+			$timeZone = 'UTC';
 			if ($this->session->exists('timezone')) {
 				$offsetHours = $this->session->get('timezone');
```
Comment (bantu) [inline lib/private/datetimezone.php]: Receiving an actual timezone identifier instead of an offset here, would be a lot better. It would especially prevent issues with different DST definitions as per https://github.com/owncloud/core/pull/14429/files#r25171231 (assuming those timezones are not unique).

File: lib/private/datetimezone.php [hunk 3]
```diff
@@ -43,20 +43,52 @@ public function __construct(IConfig $config, ISession $session) {
...
+		try {
+			return new \DateTimeZone($timeZone);
+		} catch (\Exception $e) {
+			\OCP\Util::writeLog('datetimezone', 'Failed to created DateTimeZone "' . $timeZone . "'", \OCP\Util::DEBUG);
+			return new \DateTimeZone('UTC');
+		}
+	}
+
+	protected function getTimeZoneFromOffset($offset) {
+		if (is_int($offset)) {
```
Comment (bantu) [inline lib/private/datetimezone.php]: is_int() is a type check. Especially is_int('0') is false.

File: lib/private/datetimezone.php [hunk 4]
```diff
@@ -43,20 +43,52 @@ public function __construct(IConfig $config, ISession $session) {
...
+		switch ($offset) {
+			case -4.5:
+				return 'America/Caracas';
+			case -3.5:
+				return 'Canada/Newfoundland';
+			case 3.5:
+				return 'Asia/Tehran';
+			case 4.5:
+				return 'Asia/Kabul';
+			case 5.5:
```
Comment (bantu) [inline lib/private/datetimezone.php]: http://en.wikipedia.org/wiki/List_of_UTC_time_offsets#UTC.2B05:30.2C_E.E2.80.A0 lists two timezones, so these mappings don't appear to be unique.

File: lib/private/datetimezone.php (hunk 2 above)
Comment (nickvergessen) [inline lib/private/datetimezone.php]: Well that was my first idea aswell.
Then I checked back and found that code to store the timezone name is already there:
https://github.com/owncloud/core/blob/6a1a4880f0d556fb090f19a5019fec31916f5c36/lib/base.php#L1018
This name is also used as a first try, not sure why this is reached anyway.

File: lib/private/datetimezone.php [hunk 5]
```diff
@@ -43,20 +43,43 @@ public function __construct(IConfig $config, ISession $session) {
...
+
+		try {
+			return new \DateTimeZone($timeZone);
+		} catch (\Exception $e) {
+			\OCP\Util::writeLog('datetimezone', 'Failed to created DateTimeZone "' . $timeZone . "'", \OCP\Util::DEBUG);
+			return new \DateTimeZone('UTC');
+		}
+	}
+
+	protected function getTimeZoneFromOffset($offset) {
```
Comment (bantu) [inline lib/private/datetimezone.php]: This should be `guessTimeZoneFromOffset()` then.

**Comment by nickvergessen** [comment]
Will have some more thoughts about this tomorrow,
not quite sure atm, what the best way to do this actually looks like

**Comment by rinchen** [comment]
@nickvergessen that seems to have worked. :-)

File: lib/private/datetimezone.php [hunk 6]
```diff
@@ -43,20 +43,48 @@ public function __construct(IConfig $config, ISession $session) {
...
+				$timeZone = 'Etc/GMT-' . $offset;
 			} else {
-				return new \DateTimeZone('UTC');
+				$timeZone = 'Etc/GMT+' . abs($offset);
+			}
+
+			new \DateTimeZone($timeZone);
+			return $timeZone;
+		} catch (\Exception $e) {
+			// If the offset has no Etc/GMT* timezone, we try to find it manually
```
Comment (bantu) [inline lib/private/datetimezone.php]: Should make it clearer that this is a best guess.

Comment (nickvergessen) [inline lib/private/datetimezone.php]: Fixed locally but will wait for jenkins, before pushing again

**Comment by nickvergessen** [comment]
@owncloud-bot retest this please honey

**Comment by nickvergessen** [comment]
Tests passed in #14606

File: lib/private/datetimezone.php [hunk 7]
```diff
@@ -44,19 +44,54 @@ public function getTimeZone() {
...
 			}
+
+			return new \DateTimeZone($timeZone);
+		} catch (\Exception $e) {
+			// If the offset has no Etc/GMT* timezone,
+			// we try to guess one timezone that has the same offset
+			foreach (\DateTimeZone::listIdentifiers() as $timeZone) {
+				$dtz = new \DateTimeZone($timeZone);
+				$dtOffset = $dtz->getOffset(new \DateTime());
+				if ($dtOffset == 3600 * $offset) {
```
Comment (LukasReschke) [inline lib/private/datetimezone.php]: `===`? – As far I see both are numeric types?

**Comment by LukasReschke** [comment]
:+1:

**Comment by nickvergessen** [comment]
Changed it to fall back to `date_default_timezone_get()` now, before using `UTC`

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by nickvergessen** [comment]
Jenkins is at  #14606

**Comment by nickvergessen** [comment]
@bantu @DeepDiver1975 second +1 for the jenkins PR?

**Comment by nickvergessen** [comment]
bump, or @MorrisJobke maybe?

**Comment by MorrisJobke** [comment]
Tested, works :+1:
