### PR TITLE
Propagate shares etag when group membership changed

### LINKED ISSUE #17301: Owncloud server not reporting etag changes for newly added groups
In summary, the problem is that the owncloud server doesn't report etag changes if a user is added to a group which already has shares.

I intially reported this issue in the owncloud client project: https://github.com/owncloud/client/issues/3274
More information including used versions, steps to reproduce and a client log can be found there.

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/17301

@icewind1991 since you're the expert in propagation, I'd like to you to comment on this approach. If it is acceptable I will move the new inline code from setupPropagation() to PropagationManager or a new class. What do you think ?
- [x] TODO: also propagate etag on group removal
- [x] TODO: refactor in better structure
- [x] TODO: add unit tests

### CODE REVIEW

File: apps/files_sharing/lib/propagation/propagationmanager.php [hunk 1]
```diff
@@ -82,6 +82,21 @@ public function getChangePropagator($user) {
...
+	 * @param array array of shares for which to trigger etag change
+	 * @param string $user
+	 */
+	public function propagateSharesToUser($shares, $user) {
+		$changePropagator = $this->getChangePropagator($user);
+		foreach ($shares as $share) {
+			$changePropagator->addChange($share['file_target']);
+		}
+		$time = microtime(true);
+		$changePropagator->propagateChanges(floor($time));
```
Comment (PVince81) [inline apps/files_sharing/lib/propagation/propagationmanager.php]: @icewind1991 do we also need to update appconfig here ?

File: apps/files_sharing/appinfo/application.php [hunk 2]
```diff
@@ -134,5 +134,26 @@ public function registerMountProviders() {
...
+		$mountProvider = $this->getContainer()->query('MountProvider');
+		$sharesBefore = [];
+
+		$groupManager->listen('\OC\Group', 'preAddUser', function (\OCP\IGroup $group, \OCP\IUser $user) use ($propagationManager, $sharesBefore) {
+			$sharesBefore = \OCP\Share::getItemsSharedWithUser('file', $user->getUID());
+		});
+		$groupManager->listen('\OC\Group', 'postAddUser', function (\OCP\IGroup $group, \OCP\IUser $user) use ($propagationManager, $sharesBefore) {
+			$sharesAfter = \OCP\Share::getItemsSharedWithUser('file', $user->getUID());
+
+			$newShares = array_udiff(
```
Comment (PVince81) [inline apps/files_sharing/appinfo/application.php]: here basically we just check what shares existed before the group membership change, then propagate etags for the new ones.

**Comment by nickvergessen** [comment]
Should this also happen on removing a user from group?

**Comment by PVince81** [comment]
@nickvergessen yes, on removal also makes sense

**Comment by PVince81** [comment]
@icewind1991 still waiting for your feedback.

File: apps/files_sharing/lib/propagation/propagationmanager.php (hunk 1 above)
Comment (icewind1991) [inline apps/files_sharing/lib/propagation/propagationmanager.php]: For the dirty share logic? I dont think so

**Comment by icewind1991** [comment]
Approach looks good

File: apps/files_sharing/appinfo/application.php [hunk 3]
```diff
@@ -134,5 +134,26 @@ public function registerMountProviders() {
 	public function setupPropagation() {
 		$propagationManager = $this->getContainer()->query('PropagationManager');
 		\OCP\Util::connectHook('OC_Filesystem', 'setup', $propagationManager, 'globalSetup');
+		$groupManager = $this->getContainer()->getServer()->getGroupManager();
+
+		$mountProvider = $this->getContainer()->query('MountProvider');
+		$sharesBefore = [];
+
+		$groupManager->listen('\OC\Group', 'preAddUser', function (\OCP\IGroup $group, \OCP\IUser $user) use ($propagationManager, $sharesBefore) {
```
Comment (icewind1991) [inline apps/files_sharing/appinfo/application.php]: iirc you need to pass `$sharesBefore` by reference

**Comment by PVince81** [comment]
Introducing GroupPropagationManager, now the code is encapsulated there.

Also I have added the code for when removing a user from a group. (broken)

- [ ] BUG: remove from group doesn't propagate properly

The issue is probably that we're trying to resolve the internal path for a share that is not mounted any more here https://github.com/owncloud/core/blob/v8.1.3/lib/private/files/cache/changepropagator.php#L75. `resolvePath` returns "/user1/files" instead of "files" when resolving the parent path `/`.

**Comment by PVince81** [comment]
Ok, seems to be a missing `initMountPoints`.

**Comment by PVince81** [comment]
- [ ] BUG: when target folder was renamed/moved (different files_target), `getItemsSharedWithUser` still returns it

**Comment by PVince81** [comment]
- [ ] TODO: also test with reshares: group member is the reshare owner

**Comment by PVince81** [comment]
`getItemsSharedWithUser` bug for the FIXME: https://github.com/owncloud/core/issues/19541

**Comment by PVince81** [comment]
- [ ] BUG: make the group owner reshare with another user "user2", that other user's etag doesn't change. Probably need to tweak `getUserShare()` to also find all the reshares
- [ ] BUG: same when the reshare is done on a moved mount point (different "file_target")

**Comment by PVince81** [comment]
I've added unit tests for the cases already covered. They will fail due to https://github.com/owncloud/core/issues/19541 missing

**Comment by rullzer** [comment]
#19541 is fixed. But unit tests still failing ;)

**Comment by PVince81** [comment]
Let me rebase

**Comment by PVince81** [comment]
See, they pass now...

**Comment by PVince81** [comment]
@nickvergessen @schiesbn @DeepDiver1975 @icewind1991 please review. Let's move the reshare cases to a separate issue.

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by rullzer** [comment]
:+1: nice work!

File: apps/files_sharing/lib/propagation/grouppropagationmanager.php [hunk 4]
```diff
@@ -0,0 +1,126 @@
...
+
+	public function onPreProcessUser(IGroup $group, IUser $targetUser) {
+		$this->userShares[$targetUser->getUID()] = $this->getUserShares($targetUser->getUID());
+	}
+
+	public function onPostAddUser(IGroup $group, IUser $targetUser) {
+		$targetUserId = $targetUser->getUID();
+		$sharesAfter = $this->getUserShares($targetUserId);
+
+		$this->propagateSharesDiff($targetUserId, $sharesAfter, $this->userShares[$targetUserId]);
```
Comment (nickvergessen) [inline apps/files_sharing/lib/propagation/grouppropagationmanager.php]: This

File: apps/files_sharing/lib/propagation/grouppropagationmanager.php [hunk 5]
```diff
@@ -0,0 +1,126 @@
...
+		unset($this->userShares[$targetUserId]);
+	}
+
+	public function onPostRemoveUser(IGroup $group, IUser $targetUser) {
+		$targetUserId = $targetUser->getUID();
+		$sharesAfter = $this->getUserShares($targetUserId);
+
+		$this->propagateSharesDiff($targetUserId, $this->userShares[$targetUserId], $sharesAfter);
```
Comment (nickvergessen) [inline apps/files_sharing/lib/propagation/grouppropagationmanager.php]: has a different order then this,
intended?

Comment (PVince81) [inline apps/files_sharing/lib/propagation/grouppropagationmanager.php]: It is intended, because the diff is done in the opposite way.
In the first case we want to know which shares were added. In the second one which shares were removed.

Comment (nickvergessen) [inline apps/files_sharing/lib/propagation/grouppropagationmanager.php]: But then the variable names do not match: `$sharesBefore, $sharesAfter`

Comment (nickvergessen) [inline apps/files_sharing/lib/propagation/grouppropagationmanager.php]: It's not crucial, but will get someone confused some day, that after is actually before and the otherway around

File: apps/files_sharing/lib/propagation/grouppropagationmanager.php [hunk 6]
```diff
@@ -0,0 +1,126 @@
...
+		unset($this->userShares[$targetUserId]);
+	}
+
+	private function getUserShares($targetUserId) {
+		return \OCP\Share::getItemsSharedWithUser('file', $targetUserId);
+	}
+
+	private function propagateSharesDiff($targetUserId, $sharesBefore, $sharesAfter) {
```
Comment (PVince81) [inline apps/files_sharing/lib/propagation/grouppropagationmanager.php]: You probably mean these two params. Do you have a better suggestion for their names ? I didn't find anything better.

Comment (nickvergessen) [inline apps/files_sharing/lib/propagation/grouppropagationmanager.php]: shares1 and shares2 ? Less descriptive, but at least accurate :wink:

File: apps/files_sharing/lib/propagation/grouppropagationmanager.php [hunk 7]
```diff
@@ -0,0 +1,126 @@
...
+		$removedShares = array_udiff(
```
Comment (nickvergessen) [inline apps/files_sharing/lib/propagation/grouppropagationmanager.php]: its not `removedShares` but `sharesToPropagate`

Comment (PVince81) [inline apps/files_sharing/lib/propagation/grouppropagationmanager.php]: ok thanks, I'll make the changes

**Comment by PVince81** [comment]
@nickvergessen fixed the names and rebased again
