### PR TITLE
Fix for app:enable in case of not valid/not existing enterprise key

### LINKED ISSUE #36351: occ app:enable should exit with proper error message if enterprise key is invalid
### Steps to reproduce
1. Disable an enterprise app
2. Set an invalid Enterprise Key
3. Try to enable an enterprise app

### Expected behaviour
The `occ app:enable example-ee-app` command should exit with a proper error message and notify the user that the app will not be enabled due to an invalid license key.

### Actual behaviour
The `occ app:enable example-ee-app` command exited with a success message while the app is still disabled. Only if you look into the owncloud.log you will see an error message about the invalid license key.

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.2

**ownCloud version:** 10.3

### PR DESCRIPTION
**Pull request by pako81**
## Description

This PR fixes the current behaviour of the `app:enable` occ command in case of not valid/not existing enterprise key.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/36351

## Motivation and Context

Currently, when running the `app:enable` occ command for enabling an enterprise app and the enterprise key is not valid/not existing, the command does not return any warning/error message. Still, the enterprise app stays disabled. Only when looking into the owncloud.log file one will see an error message about the invalid license key.

## How Has This Been Tested?

Manually, by: - disabling an enterprise app, - setting an invalid enteprise key, - trying to re-enable that enterprise app. Now, the `$appId cannot be enabled because of invalid enteprise key` message is shown.

Implemented for both cases in case groups are/are not given as input to the command.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised 
- [x] Changelog item

### CODE REVIEW

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/21265/3/6
```
enabling apps
+ echo 'enabling apps'
+ php occ app:enable files_sharing
An unhandled exception has been thrown:
Error: Class 'OCA\Enterprise_Key\EnterpriseKey' not found in /drone/src/core/Command/App/Enable.php:74
```
It still needs to work for the community edition, when there is no `enterprise_key` app.

File: core/Command/App/Enable.php [hunk 1]
```diff
@@ -71,10 +71,19 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 		}
 
 		$groups = $input->getOption('groups');
+		$key = new \OCA\Enterprise_Key\EnterpriseKey(false, \OC::$server->getConfig());
 		if (empty($groups)) {
```
Comment (micbar) [inline core/Command/App/Enable.php]: Please inject config in constructor.

**Review by micbar — DISMISSED** [review]

File: core/Command/App/Enable.php (hunk 1 above)
Comment (pako81) [reply core/Command/App/Enable.php]: will do

File: core/Command/App/Enable.php [hunk 2]
```diff
@@ -71,10 +77,21 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 		}
 
 		$groups = $input->getOption('groups');
-		if (empty($groups)) {
+		if (\OC_App::isEnabled('enterprise_key')) {
+			$key = new \OCA\Enterprise_Key\EnterpriseKey(false, \OC::$server->getConfig());
+		}
```
Comment (micbar) [inline core/Command/App/Enable.php]: use the global property here: $this->config

**Comment by pako81** [comment]
better now?

File: core/Command/App/Enable.php [hunk 3]
```diff
@@ -71,10 +77,21 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 		}
 
 		$groups = $input->getOption('groups');
+		if (\OC_App::isEnabled('enterprise_key')) {
+			$key = new \OCA\Enterprise_Key\EnterpriseKey(false, $this->config);
+		}
 		if (empty($groups)) {
+			if ($key && !$key->isValid()) {
+				$output->writeln($appId . ' cannot be enabled because of invalid enteprise key');
```
Comment (phil-davis) [inline core/Command/App/Enable.php]:
```suggestion
				$output->writeln($appId . ' cannot be enabled because of invalid enterprise key');
```

File: core/Command/App/Enable.php [hunk 4]
```diff
@@ -71,10 +77,21 @@ protected function execute(InputInterface $input, OutputInterface $output) {
...
+				return 1;
+			}
 			\OC_App::enable($appId);
 			$output->writeln($appId . ' enabled');
 		} else {
+			if ($key && !$key->isValid()) {
+				$output->writeln($appId . ' cannot be enabled because of invalid enteprise key');
```
Comment (phil-davis) [inline core/Command/App/Enable.php]:
```suggestion
				$output->writeln($appId . ' cannot be enabled because of invalid enterprise key');
```

File: core/Command/App/Enable.php [hunk 5]
```diff
@@ -71,10 +77,21 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 		}
 
 		$groups = $input->getOption('groups');
+		if (\OC_App::isEnabled('enterprise_key')) {
+			$key = new \OCA\Enterprise_Key\EnterpriseKey(false, $this->config);
```
Comment (karakayasemi) [inline core/Command/App/Enable.php]: To prevent creating duplicate code block, you can validate the key directly after `$key` assignment. Also, in this way, you do not need to check whether the key exists.

Comment (pako81) [reply core/Command/App/Enable.php]: The duplicate code block is actually needed depending if the `$groups` option has been given or not as input to the occ command, and it was already there before this PR. Or did I misunderstand the suggestion?

File: core/Command/App/Enable.php [hunk 6]
```diff
@@ -71,10 +77,21 @@ protected function execute(InputInterface $input, OutputInterface $output) {
...
+		}
 		if (empty($groups)) {
+			if ($key && !$key->isValid()) {
```
Comment (phil-davis) [inline core/Command/App/Enable.php]: He means that this `if` test can be moved to before `if (empty($groups))` and then it is only needed once.

File: core/Command/App/Enable.php (hunk 5 above)
Comment (karakayasemi) [reply core/Command/App/Enable.php]: As the last step, just run `make test-php-style-fix` for code style adjustment.

File: core/Command/App/Enable.php [hunk 7]
```diff
@@ -70,6 +76,14 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 			return 1;
 		}
 
+		if (\OC_App::isEnabled('enterprise_key')) {
+		$key = new \OCA\Enterprise_Key\EnterpriseKey(false, $this->config);
```
Comment (phil-davis) [inline core/Command/App/Enable.php]: Indent is strange

File: core/Command/App/Enable.php [hunk 8]
```diff
@@ -70,6 +76,14 @@ protected function execute(InputInterface $input, OutputInterface $output) {
...
+		        if ($key && !$key->isValid()) {
+			$output->writeln($appId . ' cannot be enabled because of invalid enterprise key');
+			return 1;
```
Comment (phil-davis) [inline core/Command/App/Enable.php]: And these lines need indent inside the `if` block

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
@micbar is this progressing?
(could have an acceptance test added if it is planned for release...)

**Comment by phil-davis** [comment]
@pako81 @micbar I  rebased and fixed the code-style fail.
Let's see if the "real" CI passes...

File: core/Command/App/Enable.php (hunk 5 above)
Comment (micbar) [reply core/Command/App/Enable.php]: The enterprise key app is not enabled in CI. Therefore it fails.
@phil-davis

Comment (phil-davis) [reply core/Command/App/Enable.php]: Looking at it - when can likely give the code analysis tool(s) a clue to skip that line

**Comment by phil-davis** [comment]
And adjusted the unit test so it knows about the new param to the constructor.
Maybe this time CI will pass?

**Comment by micbar** [comment]
> And adjusted the unit test so it knows about the new param to the constructor.
> Maybe this time CI will pass?

PHpstan fails because the code of Enterprise Key is not available.

**Comment by phil-davis** [comment]
> > And adjusted the unit test so it knows about the new param to the constructor.
> > Maybe this time CI will pass?
> 
> PHpstan fails because the code of Enterprise Key is not available.

I "fixed" that by making it ignore that - phpstan CI is passing.

**Comment by phil-davis** [comment]
I added a changelog. I think this is ready for review.

There are existing `cliProvisioning/enableApp.feature` tests that cover enabling an ordinary app - so that ensures that this code change did not break anything for ordinary apps.

We are not easily able to get ourselves an enterprise app and the enterprise_key app etc during core CI. So this change will need manual testing during the release QA process.

**Review by karakayasemi — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]

File: core/Command/App/Enable.php [hunk 9]
```diff
@@ -70,6 +76,16 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 			return 1;
 		}
 
+		if (\OC_App::isEnabled('enterprise_key')) {
```
Comment (phil-davis) [inline core/Command/App/Enable.php]: The issue we found now is that if you have the enterprise app enabled, but have an invalid enterprise key, and you are just trying to enable a  non-enterprise app, then the app cannot be enabled. e.g. enabling the `testing` app does not work.

If there is some way to check if the app being enabled is an Enterprise app, then this could be fixed by:
```
if (\OC_App::isEnterpriseApp($appId) && \OC_App::isEnabled('enterprise_key')) {
```
