### PR TITLE
[Tests-Only] Remove admin auth error in log when running API acceptance tests

### LINKED ISSUE #179: admin auth erros in log when running API acceptance tests
Running API acceptance tests is introduced in PR #166 and they pass - great.

What can be done about the many messages in https://cloud.drone.io/owncloud/ocis/271/1/11 ocis-server log:
```
6:33AM WRN srv/app/pkg/mod/github.com/cs3org/reva@v0.1.1-0.20200320145721-40c4334849c3/internal/grpc/services/authprovider/authprovider.go:107 > error authenticating user error="authsvc: error in Authenticate: error: not found: admin" pid=306 pkg=rgrpc traceid=b642fa5c569ce1a933958d5017dec137
```
Is there "bonus" stuff happening in test setup/teardown or... that is trying to do stuff with an `admin` user that does not exist? Or what?

To-do: investigate if we need to adjust/control what the tests are doing in setup/teardown etc or some other change in OCIS itself or what should be done?

### PR DESCRIPTION
**Pull request by haribhandari07**
## Description

This PR removes admin auth error log when running API acceptance tests
## Related Issue

- Fixes https://github.com/owncloud/ocis/issues/179#event-3514779948

## How Has This Been Tested?

- https://github.com/owncloud/ocis/pull/371
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

File: tests/acceptance/run.sh [hunk 1]
```diff
@@ -524,15 +524,21 @@ then
 	DIR_URL="${TESTING_APP_URL}dir"
 	# test that server is up and running, and testing app is enabled.
 	assert_server_up ${TEST_SERVER_URL}
-	assert_testing_app_enabled ${TEST_SERVER_URL}
+	if [ "${TEST_OCIS}" == "false" ]
```
Comment (phil-davis) [inline tests/acceptance/run.sh:527]:
```suggestion
	if [ "${TEST_OCIS}" != "true" ]
```

I suspect that this will never happen - `TEST_OCIS` will never be set to the string "false", so `assert_testing_app_enabled` will never be done any more.

File: tests/acceptance/run.sh [hunk 2]
```diff
@@ -524,15 +524,21 @@ then
...
+	fi
 
 	if [ -n "${TEST_SERVER_FED_URL}" ]
 	then
 		TESTING_APP_FED_URL="${TEST_SERVER_FED_URL}/ocs/v2.php/apps/testing/api/v1/"
 		OCC_FED_URL="${TESTING_APP_FED_URL}occ"
 		# test that fed server is up and running, and testing app is enabled.
 		assert_server_up ${TEST_SERVER_FED_URL}
-		assert_testing_app_enabled ${TEST_SERVER_FED_URL}
+	if [ "${TEST_OCIS}" == "false" ]
```
Comment (phil-davis) [inline tests/acceptance/run.sh:538]:
```suggestion
	if [ "${TEST_OCIS}" != "true" ]
```

**Review by phil-davis — APPROVED** [review]
