### PR TITLE
Fixes WebDAV copy

### LINKED ISSUE #14501: WebDAV COPY creates empty folder when copying non-existing file
### Steps
1. Start cadaver
2. Type "cp nonexistingfile test.txt" (test.txt should not exist either)

### Expected
404

### Actual
An empty folder "test.txt" is created

### PR DESCRIPTION
**Pull request by PVince81**
- added existence check for source argument
- removed extra logic for folders, as $view->copy() already supports
  that internally

Fixes https://github.com/owncloud/core/issues/14501

### CODE REVIEW

**Comment by PVince81** [comment]
@icewind1991 as discussed

Please review @DeepDiver1975 @schiesbn @nickvergessen @LukasReschke

**Comment by icewind1991** [comment]
Looks good, litmus runs successful :+1:

**Comment by icewind1991** [comment]
This should give a nice performance increase when working with external storages that have native recursive copy

**Comment by PVince81** [comment]
Nice.

File: lib/private/connector/sabre/objecttree.php [hunk 1]
```diff
@@ -234,21 +234,11 @@ public function copy($source, $destination) {
...
-			} else {
-				$this->fileView->mkdir($destination);
-				$dh = $this->fileView->opendir($source);
-				if (is_resource($dh)) {
-					while (($subNode = readdir($dh)) !== false) {
-
-						if ($subNode == '.' || $subNode == '..') continue;
-						$this->copy($source . '/' . $subNode, $destination . '/' . $subNode);
+		// this will trigger existence check
+		$node = $this->getNodeForPath($source);
```
Comment (nickvergessen) [inline lib/private/connector/sabre/objecttree.php]: No need for `$node =` just run the method

Comment (PVince81) [inline lib/private/connector/sabre/objecttree.php]: Damn. I was hoping no one would find out (I knew it when I wrote that)

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by PVince81** [comment]
@karlitschek backport to 8.0, 7.0, 6.0 ? requested by @davivel 
We could add that extra line that checks for existence in the old versions to make sure that 404 is returned instead of creating a bogus empty file.

**Comment by karlitschek** [comment]
please backport. thanks

**Comment by PVince81** [comment]
To keep it safe I'll only partially backport this, basically only adding
```php
	// this will trigger existence check
	$this->getNodeForPath($source);
```
