### PR TITLE
Make sure user has access to file for system tag operations

### LINKED ISSUE #22061: Can assign and unassign tags to files I have no access to
To reproduce add a breakpoint in `apps/systemtags/js/systemtagsinfoview.js`:
```js
this.selectedTagsCollection.setObjectId(fileInfo.id);
```

And modify the ID to any file you have no access to.
Afterwards look in the DB or at the response of the request when assigning/unassigning a tag.

@PVince81

### PR DESCRIPTION
**Pull request by PVince81**
Fixes DAV's SystemTagsObjectTypeCollection to not give access to files
where the current user doesn't have access to.

To test:
- `curl -D - -X POST -H "Content-Type: application/json" -d '{"name":"test relation z", "userVisible": true, "userAssignable": true}' http://root:admin@localhost/owncloud/remote.php/dav/systemtags-relations/files/3/` where 3 is the fileid of an accessible file for "root", check Content-Location header for tag id of newly created tag
- same POST where the file id is from another user => must fail with 404
- `curl -D - -X PUT http://root:admin@localhost/owncloud/remote.php/dav/systemtags-relations/files/$fileId/$tagId`. Replace $tagId with the tag id from above. Replace $fileId with a fileid accessible by root
- same PUT but with file id from another user

POST is covered by the SystemTagsPlugin and any other operation is going through `getChild` to access subnodes. So the fact that `getChild` blocks access to unknown file ids will block any operations there.

Please review @Blizzz @LukasReschke @icewind1991 @DeepDiver1975 

Fix #22061

### CODE REVIEW

**Comment by nickvergessen** [comment]
Fixes #22061 which I just reported
:+1:

File: apps/dav/lib/systemtag/systemtagsobjecttypecollection.php [hunk 1]
```diff
@@ -134,6 +148,13 @@ function getChildren() {
 	 * @param string $name
 	 */
 	function childExists($name) {
+		// TODO: make this more abstract
```
Comment (nickvergessen) [inline apps/dav/lib/systemtag/systemtagsobjecttypecollection.php]: could dispatch an event :no_mouth:

Comment (PVince81) [inline apps/dav/lib/systemtag/systemtagsobjecttypecollection.php]: Maybe... something to think about when we introduce more types. Now even this collection's initialization is hard-coded to "files". We'll see when the time is right.

Comment (nickvergessen) [inline apps/dav/lib/systemtag/systemtagsobjecttypecollection.php]: okay, yeah was just a thought, fine as is for now

**Comment by PVince81** [comment]
Needs a second reviewer @blizzz @icewind1991 @rullzer

**Comment by rullzer** [comment]
:+1:
