### PR TITLE
Prevent files:checksum:verify from crashing on exception

### LINKED ISSUE #38782: Prevent `occ files:checksum:verify -r` from crashing on exception
### Steps to reproduce
1. Create an external storage for userA and add some files
2. Make the storage unavailable (not by removing the storage but by altering the access data or shutting down the remote server)
3. Run `occ files:checksum:verify -r`

### Expected behaviour
The command should do what it's supposed to do without crashing midterm because of any exception.

### Actual behaviour
The command crashes with `OCP\Files\StorageNotAvailableException`.

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
The command now skips files with exceptions instead of crashing. A proper message will be displayed to the user who fires the command.

## Related Issue
- Fixes https://github.com/owncloud/core/issues/38782

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

File: apps/files/lib/Command/VerifyChecksums.php [hunk 1]
```diff
@@ -200,11 +201,18 @@ private function verifyChecksumsForFile($file, InputInterface $input, OutputInte
 	private function verifyChecksumsForFolder($folder, InputInterface $input, OutputInterface $output) {
 		$folderQueue = [$folder];
 		while ($currentFolder = \array_pop($folderQueue)) {
+			'@phan-var \OCP\Files\Folder $currentFolder';
+			$currentFolderPath = $currentFolder->getPath();
 			try {
-				'@phan-var \OCP\Files\Folder $currentFolder';
 				$nodes = $currentFolder->getDirectoryListing();
 			} catch (NotFoundException $e) {
 				$nodes = [];
```
Comment (JanAckermann) [inline apps/files/lib/Command/VerifyChecksums.php:209]: No exception message here?

**Review by AlexAndBear — CHANGES_REQUESTED** [review]

File: apps/files/lib/Command/VerifyChecksums.php (hunk 1 above)
Comment (JammingBen) [reply apps/files/lib/Command/VerifyChecksums.php:209]: Didn't want to touch it was it was there already. But you're right, a message would be nice here too. Will add :)

**Review by karakayasemi — APPROVED** [review]
LGTM!

**Review by IljaN — APPROVED** [review]

**Review by AlexAndBear — APPROVED** [review]
