### PR TITLE
Prevent wrong matches in getRelativePath

### LINKED ISSUE #16475: File restore from trash to ext storage appears twice in web UI
### Steps to reproduce
1. Enable encryption + default encryption module
2. Log out, log in
3. Enable external storage
4. Mount a SFTP storage under "/sftp"
5. Create a folder "/sftp/enc".
6. Create a file "/sftp/enc/test.txt"
7. Edit and save the file several times to create versions
8. Delete the folder "/sftp/enc" to trash
9. Restore the folder "enc" from trash
10. Check the contents of "/sftp/enc" in the web UI

### Expected result
"test.txt" appears once.

### Atcual result
"test.txt" appears **twice** in the web UI.
Strangely oc_filecache only has a single entry for "test.txt"

### Versions
ownCloud 8.1 git master 39d1e99228a22e232795b9800503697b866f5023

### LINKED ISSUE #18509: view->getPath($id) returns strange path for delete files
If a file is deleted and moved to the trashbin, `getPath($id)` returns `_trashbin/$path.$timestamp`.
Looks like we just cut off `files` no ignoring whether it is `files/` or not.

Is this intended? @icewind1991 @PVince81

### PR DESCRIPTION
**Pull request by PVince81**
Before this fix, the root "/files" with path "/files_trashbin" would
return "_trashbin" as relative path...

Please review @icewind1991 @schiesbn 

I'm still having doubts whether this quickfix is safe or will break other parts of OC...

I raised https://github.com/owncloud/core/issues/16478 to look into a more extensive fix.

Fixes #16475
Fixes #18509

### CODE REVIEW

**Comment by PVince81** [comment]
The alternative would be to just detect these cases and log a warning and carry on... at least for 8.1.
My worry is about code that assumes that the return value has a leading slash. It doesn't always have it...

**Comment by PVince81** [comment]
I wonder what could go wrong if someone ever had a real "_trashbin" folder in their home storage...

File: tests/lib/files/view.php [hunk 1]
```diff
@@ -794,22 +794,29 @@ function absolutePathProvider() {
...
-			array('/files/false', 'false'),
-			array('/files/true', 'true'),
-			array('/files/test', 'test'),
-			array('/files/test/foo', 'test/foo'),
+			// TODO: add many more cases with mixed slashes, which is only possible
+			// once getRelativePath's behavior is made consistent
+
+			// with slashes
+			array('/files/', '/files/', '/'),
+			array('/files/', '/files', '/'),
```
Comment (nickvergessen) [inline tests/lib/files/view.php]: Mind adding `array('/files', '/files/', '/'),` aswell?

Comment (PVince81) [inline tests/lib/files/view.php]: I tried adding more cases initially, but they failed. This is because response we are getting will sometimes have a trailing slash and sometimes not. It's a real mess and I didn't want to "enforce" the expected behavior here until we fix it and decide what the API contract is for that method, as part of https://github.com/owncloud/core/issues/16478

I'm not sure about adding test cases that asserts that the behavior is still as buggy as it was before, basically giving a "wrong" answer.

Comment (nickvergessen) [inline tests/lib/files/view.php]: Well the case I mentioned is hardcoded before your patch:
```php
 		if (rtrim($path,'/') === rtrim($this->fakeRoot, '/')) {
 			return '/';
 		}
```
so that should always work (until someone breaks it)

Comment (PVince81) [inline tests/lib/files/view.php]: Ah yes, then it makes sense. I'll add it. (I'm a bit blinded by my :rage: regarding this method)

**Comment by nickvergessen** [comment]
Test coverage for the patch is good and the patch looks fine aswell.

>The alternative would be to just detect these cases and log a warning and carry on... at least for 8.1.

To not break anything I'd not backport it, but only fix in master. So I agree with that.

File: tests/lib/files/view.php (hunk 1 above)
Comment (nickvergessen) [inline tests/lib/files/view.php]: also empty fakeRoot should be easily testable

**Comment by PVince81** [comment]
I agree, this PR should only go to 8.1

File: lib/private/files/view.php [hunk 2]
```diff
@@ -141,7 +141,10 @@ public function getRelativePath($path) {
...
 		}
 
-		if (strpos($path, $this->fakeRoot) !== 0) {
+		// missing slashes can cause wrong matches!
+		$root = rtrim($this->fakeRoot, '/') . '/';
+
+		if (strpos($path, $root) !== 0) {
 			return null;
 		} else {
 			$path = substr($path, strlen($this->fakeRoot));
```
Comment (nickvergessen) [inline lib/private/files/view.php]: @PVince81 Should we use `strlen($root)` here? That would fix:
https://github.com/owncloud/core/pull/16479/files#diff-82902132462e0bedddfef05bdebb9373R855

Comment (PVince81) [inline lib/private/files/view.php]: I'd rather not take this risk. When I tried it it changed the behavior from "having a slash in the response" to "not having a slash in the response" in some cases. Keep in mind that some code that uses this API rely insanely on such slash to exist (or not exist). There is risk of breakage.

File: tests/lib/files/view.php [hunk 3]
```diff
@@ -792,24 +792,98 @@ function absolutePathProvider() {
...
+			// Root equals path - /
+			array('/files/', '/files/', '/'),
+			array('/files/', '/files', '/'),
+			array('/files', '/files/', '/'),
+			array('/files', '/files', '/'),
+
+			// False negatives: chroot fixes those by adding the leading slash.
+			// But setting them up with this root (instead of chroot($root))
+			// will fail them, althought they should be the same.
+			// TODO init should be fixed, so it also adds the leading slash
```
Comment (nickvergessen) [inline tests/lib/files/view.php]: I think we should fix the constructor method to add the leading slash aswell (one day™)

File: tests/lib/files/view.php [hunk 4]
```diff
@@ -792,24 +792,98 @@ function absolutePathProvider() {
...
+
+			// with trailing slashes
+			array('/files/', '/files/0', '0'),
+			array('/files/', '/files/false', 'false'),
+			array('/files/', '/files/true', 'true'),
+			array('/files/', '/files/test', 'test'),
+			array('/files/', '/files/test/foo', 'test/foo'),
+
+			// without trailing slashes
+			// TODO false expectation: Should match "with trailing slashes"
```
Comment (nickvergessen) [inline tests/lib/files/view.php]: See https://github.com/owncloud/core/pull/16479/files#r30784921

File: tests/lib/files/view.php (hunk 3 above)
Comment (PVince81) [inline tests/lib/files/view.php]: Try it, if you add `$this->fakeRoot = '/' . trim($this->fakeRoot, '/') . '/'` in the constructor it will break the unit test setup for some reason... when I saw this it told me how dangerous such changes are.
Yes... one day, see https://github.com/owncloud/core/issues/16478#issuecomment-103948491

File: lib/private/files/view.php (hunk 2 above)
Comment (nickvergessen) [inline lib/private/files/view.php]: Okay, option 2 would be `strlen(rtrim($this->fakeRoot, '/'))` but I guess this is all :hankey: until we freeze the method to one behaviour.

Comment (PVince81) [inline lib/private/files/view.php]: Yeah... I'd say just leave it. I tried to keep this PR to the minimum to just avoid the bad match, nothing more.

**Comment by PVince81** [comment]
Note: this PR isn't needed any more for https://github.com/owncloud/core/issues/16475

If we want to be on the safe side, we could just defer to 8.2

**Comment by MorrisJobke** [comment]
@PVince81 State of this?

**Comment by PVince81** [comment]
At this point, need to continue with the proper fix on top of this PR. (too late for quickfix anyway)

**Comment by PVince81** [comment]
Rebased.

**Comment by PVince81** [comment]
I'd still have to have this quickfix in as it would potentially solve https://github.com/owncloud/core/issues/18509 and https://github.com/owncloud/core/pull/18524

The proper fix is much more risky.

**Comment by PVince81** [comment]
```
12:04:32 Waiting for Oracle initialization ... 
12:06:32 Kill the docker d5a96359bc65de09304097bd002b23d3cdb0f593344042c3d8245c3507b31eb7
12:06:44 d5a96359bc65de09304097bd002b23d3cdb0f593344042c3d8245c3507b31eb7
12:06:44 Build step 'Conditional step (single)' marked build as failure
```

**Comment by PVince81** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
I did some sometests and all went good :+1:

**Comment by nickvergessen** [comment]
Mind also fixing getPath() ?

**Comment by PVince81** [comment]
@nickvergessen separately then. Since @icewind1991 is off then I'll have a look myself.

**Comment by PVince81** [comment]
@nickvergessen what's left to fix in getPath ? getPath uses getRelativePath and  I thought this would fix it already ?

**Comment by PVince81** [comment]
I hereby :+1: the commit from @nickvergessen for the unit tests.

Needs a second thumbs up for the original fix.

**Comment by PVince81** [comment]
@nickvergessen anything left to be done here ? Does it fix https://github.com/owncloud/core/issues/18509 ?

**Comment by icewind1991** [comment]
:+1:

**Comment by nickvergessen** [comment]
@PVince81 works for the activity app atm

**Comment by PVince81** [comment]
Rebased to wake up CI.

**Comment by MorrisJobke** [comment]
@PVince81 OCI fails :(

**Comment by nickvergessen** [comment]
> 	Testergebnis (6 fehlgeschlagene Tests / +6)
>
>    Test\BackgroundJob\JobList::testAddRemove.testAddRemove with data set #0
    Test\BackgroundJob\JobList::testAddRemove.testAddRemove with data set #1
    Test\BackgroundJob\JobList::testAddRemove.testAddRemove with data set #2
    Test\BackgroundJob\JobList::testAddRemove.testAddRemove with data set #3
    Test\BackgroundJob\JobList::testAddRemove.testAddRemove with data set #4
    Test\BackgroundJob\JobList::testRemoveDifferentArgument.testRemoveDifferentArgument with data set #0

Failing OCI is unlikely to be related:

> Failed asserting that OCA\Files_Trashbin\BackgroundJob\ExpireTrash Object (...) is an instance of class "\Test\BackgroundJob\TestJob"

---

Also fixes #18509 

:+1:

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Merge or retrigger CI?
