### PR TITLE
Fix to make sure expiration date is properly set

### LINKED ISSUE #15611: Enforce expiration date not working correctly if password is enforced
Hi guys,

the enforcement of an expiration date for a link seems to not work correctly if password protection is enforced. I get this behaviour in version 8.0.2, with the following sharing settings:

image

The result is this:
image

Password is enforced, but not the expiration date. Only the message that the link will expire appears. If you send the link per mail, there also is no information about the expiration.

if you disable the password enforcement, the following appears:
image
The expiration date enforcement works like it should do.

Could you please try to reproduce it?

### PR DESCRIPTION
**Pull request by rullzer**
This should fix #15611

Unit tests are still needed as this is bad UX.

### CODE REVIEW

File: core/js/share.js [hunk 1]
```diff
@@ -1132,8 +1132,19 @@ $(document).ready(function() {
 				permissions = OC.PERMISSION_READ;
 			}
 
+			var expireDateString = '';
+			if (oc_appconfig.core.defaultExpireDateEnabled) {
+				var date = new Date().getTime();
+				var expireAfterMs = oc_appconfig.core.defaultExpireDate * 24 * 60 * 60 * 1000;
+				var expireDate = new Date(date + expireAfterMs);
+				var month = expireDate.getMonth() + 1;
```
Comment (MorrisJobke) [inline core/js/share.js]: Plus one month?

Comment (MorrisJobke) [inline core/js/share.js]: This whole thing looks fishy ... what about overflows?

Comment (rullzer) [inline core/js/share.js]: I got that part from https://github.com/owncloud/core/blob/master/core/js/share.js#L985-L994 to make sure those code paths align.

Seems we need more proper unit tests for this anyway.....

Comment (MorrisJobke) [inline core/js/share.js]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth ... all is fine. It's just another JS weirdness. Months are a number between 0 and 11 -.- month 1 is February

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
sharing code: :see_no_evil: :hear_no_evil: :speak_no_evil:

File: core/js/share.js (hunk 1 above)
Comment (PVince81) [inline core/js/share.js]: Ideally we should use momentJS in the future for date computations as it can accomodate for DST and other traps.
The old code hasn't been adapted yet.

**Comment by PVince81** [comment]
@rullzer do you have time to add JS unit tests for this ?

**Comment by PVince81** [comment]
there should be some existing tests you could copy and adapt.

**Comment by rullzer** [comment]
Soo, finally some time to add a unit test.
Also moved the shared code into a separate function.

@PVince81 @MorrisJobke please retest

The switch to momentJS is still welcome :-)

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by PVince81** [comment]
Tested, works :+1: 

I saw that on master the expiration date was visible in the UI, but not saved in the database.
Here in this PR it is correctly saved in the database.

**Comment by PVince81** [comment]
@karlitschek do we want a backport for this to stable8 ?

**Comment by PVince81** [comment]
As always, thanks a lot @rullzer :smile:

**Comment by karlitschek** [comment]
We should back port this. :+1:

**Comment by PVince81** [comment]
@rullzer can you submit a PR for this to stable8 ? Thanks.

**Comment by rullzer** [comment]
backport in #16423
