### PR TITLE
filelist only refreshed if directory changes

### LINKED ISSUE #15520: OC.History - don't fire reload if URL hasn't changed any value
If for example via a click on a `<a href='#'>' the URL is changed, but the actual pointer of the URL is still the same no reload of the files app should happen.

Noticed together with @pvince81

See https://github.com/owncloud/core/pull/15512#issuecomment-91241159 for a real world example

### LINKED ISSUE #26318: Closing photo preview reloads file list
### Steps to reproduce
1. Open the WebGUI and navigate to a folder containing enough photos to require scrolling
2. Scroll down a ways and click on a photo to view the full-screen preview
3. Close the photo preview
### Expected behaviour

The page should just return to the file list at the same position it was when you clicked the photo, and should still have the photo thumbnails loaded so it responds quickly.
### Actual behaviour

The entire folder list reloads, scrolled back to the beginning of the list.  This requires not only scrolling back to where you were, but reloading all of the photo thumbnails as you go.
### Server configuration

**Operating system:** FreeNAS (custom BSD jail, not the default plugin)

**Web server:** nginx

**Database:** MySQL

**PHP version:** 5.6.19

**ownCloud version:** (see ownCloud admin page) 9.1.0 stable

**Updated from an older ownCloud or fresh install:** upgrade

**Where did you install ownCloud from:** https://download.owncloud.org/community/owncloud-9.1.0.tar.bz2

**Signing status:** No errors have been found

**List of activated apps:**
Enabled:
- activity: 2.3.2
- comments: 0.3.0
- dav: 0.2.5
- federatedfilesharing: 0.3.0
- federation: 0.1.0
- files: 1.5.1
- files_external: 0.6.0
- files_pdfviewer: 0.8.1
- files_sharing: 0.10.0
- files_texteditor: 2.1
- files_trashbin: 0.9.0
- files_versions: 1.3.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 15.0.0
- notifications: 0.3.0
- provisioning_api: 0.5.0
- systemtags: 0.3.0
- templateeditor: 0.1
- updatenotification: 0.2.1
  Disabled:
- encryption
- external
- files_antivirus
- files_mv
- user_external
- user_ldap

**The content of config/config.php:**
{
    "system": {
        "enable_previews": true,
        "preview_libreoffice_path": "\/usr\/local\/bin\/libreoffice",
        "memcache.local": "\OC\Memcache\APCu",
        "memcache.locking": "\OC\Memcache\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "instanceid": "ocrnlx64nnw4",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "**_localip**_",
            "**_public DNS hostname**_"
        ],
        "datadirectory": "\/mnt\/owncloud",
        "overwrite.cli.url": "http:\/\/**_localip**_",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "localhost:\/var\/run\/mysql\/mysql.sock",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "loglevel": 0,
        "htaccess.RewriteBase": "\/"
    }
}

**Are you using external storage, if yes which one:** Yes, local

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No
### Client configuration

**Browser:** Chrome/Firefox

**Operating system:** Windows 10 x64
### Logs

N/A

### PR DESCRIPTION
**Pull request by noveens**
## Description

Fixes #15520 
Fixes #26318 

The filelist is refreshed if and only if the directory is changed and not otherwise.

## Related Issue

https://github.com/owncloud/core/issues/15520
https://github.com/owncloud/core/issues/26318

## How Has This Been Tested?

Tested at all directories.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: apps/files/js/filelist.js [hunk 1]
```diff
@@ -1416,6 +1416,9 @@
 			if (!force && currentDir === targetDir) {
 				return;
 			}
+			if(this._currentDirectory && currentDir === targetDir) {
```
Comment (PVince81) [inline apps/files/js/filelist.js]: it seems this is what the previous `if` statement is doing.

Note that there is a `force` attribute to let callers force a refresh. With your approach this would break.

Did you have a look if it is possible to add this check much earlier, maybe inside app.js ?

Comment (noveens) [inline apps/files/js/filelist.js]: @PVince81 ,
I had a look, it's not possible to do this at a previous state.

Comment (PVince81) [inline apps/files/js/filelist.js]: Have a look in FileList._onUrlChanged. Try adding the check there instead.

Comment (noveens) [inline apps/files/js/filelist.js]: @PVince81 ,
I dont't think there's another method to force to NOT refresh.
maybe introduce another parameter?

**Comment by noveens** [comment]
@PVince81 ,
updated changes, please review :-)

File: apps/files/js/filelist.js [hunk 2]
```diff
@@ -549,6 +549,10 @@
 		 */
 		_onUrlChanged: function(e) {
 			if (e && _.isString(e.dir)) {
+				var currentDir = this.getCurrentDirectory();
+				if(this._currentDirectory && currentDir === e.dir) {
```
Comment (PVince81) [inline apps/files/js/filelist.js]: Yes, looks better. Does it work ?

Also, why did you add `this._currentDirectory` in the check ? What's the purpose ?

Comment (noveens) [inline apps/files/js/filelist.js]: Yes, this works now as well.

The ```this._currentDirectory``` check is there because we wouldn't want to skip file loading at the root directory ( '/' ).

Comment (noveens) [inline apps/files/js/filelist.js]: if we are at root directory the initialised values of currentDir and e.dir turn out to be same, hence the loading doesn't complete at the root page.
To solve this, I introduced the check.

Comment (PVince81) [inline apps/files/js/filelist.js]: Ah, I see. That makes sense. Please add a comment in the code to clarify this.

So basically `this._currentDirectory` is null/empty when the file list is first initialized

Comment (noveens) [inline apps/files/js/filelist.js]: Exactly

**Comment by PVince81** [comment]
Now curious if some unit test will fail.

Would be good to have a JS unit test for that case too.

**Comment by noveens** [comment]
@PVince81 ,
For which case are you talking about?

**Comment by PVince81** [comment]
> For which case are you talking about?

The case you just fixed here. Add the following tests for FileList:
- if triggering the event for url changed with the same as the current path, the file list is not refreshed (`changeDirectory` is not called, you can use a stub to check that)
- if triggering the event for url changed with the root path directly after FileList creation, the file list is refreshed (`changeDirectory` is called, that's the case you explained in the code comment)

I'll first let you look at the "fileListSpec.js" file to find existing tests you could based this on.
Let me know if you get lost there.

**Comment by noveens** [comment]
@PVince81 ,
On it.

File: apps/files/js/filelist.js [hunk 3]
```diff
@@ -551,7 +551,7 @@
 			if (e && _.isString(e.dir)) {
 				var currentDir = this.getCurrentDirectory();
 				// this._currentDirectory is NULL when fileList is first initialised
-				if(this._currentDirectory && currentDir === e.dir) {
+				if( (this._currentDirectory || this.$el.find('#dir').val()) && currentDir === e.dir) {
```
Comment (PVince81) [inline apps/files/js/filelist.js]: no, don't use the old crappy '#dir' element. This should be the same value like `this.getCurrentDirectory()` already.

File: apps/files/tests/js/filelistSpec.js [hunk 4]
```diff
@@ -2991,4 +2991,42 @@ describe('OCA.Files.FileList tests', function() {
...
+			$('#app-content-files').trigger(new $.Event('urlChanged', {dir: '/subdir'}));
+			expect(fileListStub.notCalled).toEqual(true);
+		});
+	});
+	describe('after file list creation file list should refresh', function() {
+		var fileListStub;
+
+		beforeEach(function() {
+			if (fileList) {
+				fileList.destroy();
```
Comment (PVince81) [inline apps/files/tests/js/filelistSpec.js]: You don't need to destroy here, remove this. The `afterEach` in a higher level at the top of the file already takes care of this.

File: apps/files/tests/js/filelistSpec.js [hunk 5]
```diff
@@ -2991,4 +2991,42 @@ describe('OCA.Files.FileList tests', function() {
...
+			}
+			fileList = new OCA.Files.FileList($('#app-content-files'), {
```
Comment (PVince81) [inline apps/files/tests/js/filelistSpec.js]: also no need to create, the very first `beforeEach` does that already.

File: apps/files/tests/js/filelistSpec.js [hunk 6]
```diff
@@ -2991,4 +2991,42 @@ describe('OCA.Files.FileList tests', function() {
...
+				enableUpload: true
+			});
+
+			fileListStub = sinon.stub(OCA.Files.FileList.prototype, 'changeDirectory');
+		});
+		afterEach(function() {
+			fileListStub.restore();
+		})
+		it('File list must be refreshed', function() {
+			console.log(fileList.getCurrentDirectory());
```
Comment (PVince81) [inline apps/files/tests/js/filelistSpec.js]: remove this

File: apps/files/tests/js/filelistSpec.js [hunk 7]
```diff
@@ -2991,4 +2991,42 @@ describe('OCA.Files.FileList tests', function() {
...
+			$('#app-content-files').trigger(new $.Event('urlChanged', {dir: '/'}));
+			expect(fileListStub.notCalled).toEqual(false);
```
Comment (PVince81) [inline apps/files/tests/js/filelistSpec.js]: use `fileListStub.calledOnce` here, it's better

File: apps/files/js/filelist.js (hunk 3 above)
Comment (noveens) [inline apps/files/js/filelist.js]: This is neccesary, otherwise the first test fails
in the test, this._currentDirectory remains null for some reason.

File: apps/files/tests/js/filelistSpec.js [hunk 8]
```diff
@@ -2991,4 +2991,42 @@ describe('OCA.Files.FileList tests', function() {
 			testMountType(123, 'external-root', 'external', 'external');
 		});
 	});
+	describe('file list should not refresh if url does not change', function() {
```
Comment (PVince81) [inline apps/files/tests/js/filelistSpec.js]: You only need one `describe` block to group your two tests.

```js
describe('file list url refresh tests', function() {
    beforeEach(...);
    afterEach(...);

    it('does not reload the file list if path in url does not change', ...);
    it('refreshes the file list after list creation', ...);
});

File: apps/files/tests/js/filelistSpec.js (hunk 4 above)
Comment (noveens) [inline apps/files/tests/js/filelistSpec.js]: okay :-)

File: apps/files/tests/js/filelistSpec.js (hunk 5 above)
Comment (noveens) [inline apps/files/tests/js/filelistSpec.js]: okay :-)

File: apps/files/tests/js/filelistSpec.js (hunk 6 above)
Comment (noveens) [inline apps/files/tests/js/filelistSpec.js]: oh, sorry :p

File: apps/files/js/filelist.js (hunk 3 above)
Comment (PVince81) [inline apps/files/js/filelist.js]: Then we should rather fix the test instead. Maybe something is missing in the test initialization.

File: apps/files/tests/js/filelistSpec.js (hunk 7 above)
Comment (noveens) [inline apps/files/tests/js/filelistSpec.js]: should that be called exactly once?

File: apps/files/js/filelist.js (hunk 3 above)
Comment (noveens) [inline apps/files/js/filelist.js]: should I remove this then and look into why it's not initialised?

Comment (PVince81) [inline apps/files/js/filelist.js]: Yes please.

Comment (noveens) [inline apps/files/js/filelist.js]: On it.

**Comment by noveens** [comment]
@PVince81 ,
As per your suggestion of removing the test for homepage refresh, 
It turned out that if I remove ```this.$el.find('#dir').val()``` , the test for not refreshing when directory hasn't changed seems to fail and not the other way round.
Maybe you can look into this further?

Thanks.

**Comment by noveens** [comment]
@butonic ,
can you please review?

**Comment by PVince81** [comment]
@noveens I looked into it and it seems that it's more complicated than I thought. We can't easily get rid of '#dir' at this point. So I'm willing to accept the PR as it is, with the '#dir' check inside the event handler, for now.

If you also agree, feel free to merge this directly as the tests pass 👍

File: apps/files/tests/js/filelistSpec.js [hunk 9]
```diff
@@ -2991,4 +2991,22 @@ describe('OCA.Files.FileList tests', function() {
...
+		var fileListStub;
+
+		beforeEach(function() {
+			fileListStub = sinon.stub(OCA.Files.FileList.prototype, 'changeDirectory');
+		});
+		afterEach(function() {
+			fileListStub.restore();
+		})
```
Comment (PVince81) [inline apps/files/tests/js/filelistSpec.js]: one more thing: missing semicolon here.

If you run jshint/jslint on JS files it will tell you that. Maybe your IDE has an option for this.

**Comment by noveens** [comment]
@PVince81 ,
Many thanks for the review :-)
I updated the changes, it would be great if you could merge this instead of me this time :-)

Thanks.
