### PR TITLE
Do not load previews for unsupported mimes

### LINKED ISSUE #24216: TBD: Don't throw 404 in /core/preview.png?file= if no preview exists
### Steps to reproduce
1. Having https://ossec.github.io/ installed
2. Open folder with ~20 files for which oC can't create previews
3. Get blocked with rule "Rule: 31151 (level 10) -> 'Multiple web server 400 error codes from same source ip.'"

The rule can be easily updated to not jump in if 404s are happening on /core/preview.png but still it might be better to not throw that much 404s.
### Expected behaviour

https://demo.owncloud.org/core/preview.png?file=/foo should return a placeholder preview
### Actual behaviour

https://demo.owncloud.org/core/preview.png?file=/foo is returning a 404 causing a HIDS to jump in
### Server configuration

**ownCloud version:** 9.0.1

### PR DESCRIPTION
**Pull request by VicDeo**
## Description
~- As suggested, set response to 204 instead of 404 if there is no preview~
- Pass supported mimetypes via `oc_appconfig.core.enabledPreviewProviders` and test mime against this list on js side.

## Related Issue
Fixes https://github.com/owncloud/core/issues/24216

## Motivation and Context
https://github.com/owncloud/core/issues/24216#issue-150533780

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by VicDeo** [comment]
I'd skip loading unsupported previews completely but I haven't found a way to grab all available mimetypes at once yet :/

another option is to extend DAV response with
 `<oc:previewurl>urlToPreview</oc:previewurl>`
and kill that funky construction part in js completely 
Trashbin    are still using old non-dav endpoint (what about other apps(?))

cc @PVince81

**Comment by PVince81** [comment]
I think just returning 204 should be enough.

Now I wonder if mobile clients might break with this... @davivel 

If yes, then let's add a special header or query param that only the web UI gives to get that 204 response.

**Comment by VicDeo** [comment]
ok, reverting my local miserable attempts to pass supported mimes via `oc_appconfig.core`

**Comment by DeepDiver1975** [comment]
404 is the status if a resource is not found. This is the correct behaviour in this case. :-1:

**Comment by PVince81** [comment]
In this case the only solution I can think of is to pass the list of supported previews through config.php or other means (like the mimetype JS thing) and prevent the client to request the preview URLs when it is known to not have previews.

That or send back the icon instead of a preview. But this could break the expectation of mobile client.

**Comment by DeepDiver1975** [comment]
> In this case the only solution I can think of is to pass the list of supported previews through config.php or other means (like the mimetype JS thing) and prevent the client to request the preview URLs when it is known to not have previews.

👍  this is the way it is already supposed to work

**Comment by PVince81** [comment]
@DeepDiver1975 it doesn't, because the web UI currently has no idea what preview types are supported. There used to be an attribute `isPreviewSupported` that was returned with the old ajax/list.php endpoint which we replaced by Webdav. Webdav doesn't have such attribute.

Well, we could maybe add that attribute in Webdav and call it "oc:preview-url". If set, the web UI uses it to fetch the preview. If not set, fetch the icon instead.

**Comment by VicDeo** [comment]
@DeepDiver1975 @PVince81 oook... Finally I've found how to make this lazy-registered stuff less lazy.
Is it better now?

File: core/ajax/preview.php [hunk 1]
```diff
@@ -51,7 +51,7 @@
 $info = \OC\Files\Filesystem::getFileInfo($file);
 
 if (!$info instanceof OCP\Files\FileInfo || !$always && !\OC::$server->getPreviewManager()->isAvailable($info)) {
-	\OC_Response::setStatus(404);
+	\OC_Response::setStatus(204);
```
Comment (PVince81) [inline core/ajax/preview.php]: please revert

**Comment by PVince81** [comment]
Tested, works.

However you need to revert the error code to 404.

**Comment by VicDeo** [comment]
@PVince81 reverted

**Comment by PVince81** [comment]
:+1:

Let's hope you don't need to massage Jenkins again

**Comment by VicDeo** [comment]
@PVince81 Tests passed

**Comment by dercorn** [comment]
@VicDeo @PVince81 @DeepDiver1975 Excellent work! 👍

**Comment by PVince81** [comment]
Regression https://github.com/owncloud/core/issues/27932
