### PR TITLE
Handle invalid ext storage backend to keep mount point visible

### LINKED ISSUE #26538: Disable ext storage provider app must keep mount point
### Steps

1. Setup WND from EE (or any other app that provides a custom external storage backend/storage)
1. Setup a mount point "/mount" with WND (or the other storage)
1. Access the mount point "/mount" and see that files appear
1. Disable the WND app (or other app)
1. Access the mount point again

### Expected result
Mount point exists but returns "storage not available" when accessing or syncing.

### Actual result
Mount point disappears completely. This would cause sync clients to delete the local files for every user in the event that an app got disabled by mistake. This can happen also at update time where third party apps get disabled.

To avoid this kind of needless data loss through syncing, the mount point must stay visible but any access to it must throw `StorageNotAvailableException`.

### Versions
Tested on 9.2 prealpha / git master.

Since we want to move many storage backends from files_external to separate apps, the probability that one of the separate app is not enabled on time gets higher and people might see their mount points disappear. Fixing this issue would help ease the migration in case the admin has not enabled the separate apps yet.

medium because there is a workaround: set OC to maintenance mode after an update and make sure to enable the missing storage apps before exiting maintenance mode.

@owncloud/qa @DeepDiver1975 @butonic

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Keep mount point visible and also ext storage config visible when
dealing with configs relating to storage backends or auth mechanisms
that were provided by an app that is currently disabled.

Introduces InvalidBackend and InvalidAuth placeholders to be able to properly pass around the StorageConfig. This makes it possible to keep the mount point visible but have it be a `FailedStorage` that gracefully throws `StorageNotAvailableException` which results in 503 Storage not available for clients.

## Related Issue
Fixes https://github.com/owncloud/core/issues/26538

## Motivation and Context
See original ticket.
Basically an admin might forget to reenable storage apps for which there are existing configs.
The current code would remove the mount point completely which would cause sync clients to delete local files.

## How Has This Been Tested?
- [x] TEST: invalid backend keeps mount point
- [x] TEST: sync client behavior with invalid backend
- [x] TEST: invalid auth keeps mount point
- [x] TEST: broken config is read-only in web UI (admin + personal page)
- [x] TEST: broken config can be deleted in web UI
- [x] TEST: broken config cannot be modified with CLI commands
- [x] TEST: broken config can be deleted with CLI commands
- [x] TEST: broken config cannot be exported with CLI commands, shows warning (because storage class is missing)
- [x] TEST: reenable storage app (ex: WND), mount point available again, sync client functions normally (no redownload)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

@owncloud/filesystem @butonic

### CODE REVIEW

**Comment by PVince81** [comment]
Rebased

**Comment by PVince81** [comment]
Bringing to "development" as discussed with @pmaier1.

This will ease the migration to external storage apps. It will preserve the mount points and configs present but not editable (not editable for technical reasons), so that when the user installs the external storage app the mounts will work again.

**Comment by PVince81** [comment]
Rebased.

I have tested this with the app "files_external_gdrive":

1. Install "files_external_gdrive"
1. Configure a GDrive mount point
1. Access it and see that downloading work
1. Disable the "files_external_gdrive" app
1. Refresh web UI
1. Check mount point
1. Reenable app

Before the fix: web UI would crash with some errors about missing storage classes
After the fix: web UI shows the "/gdrive" mount point in red. Accessing it through Webdav returns 503 Storage not available. After reenabling the app, the mount point works again.

@jvillafanez please review

File: lib/private/Files/External/InvalidStorage.php [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+ */
+
+namespace OC\Files\External;
+
+use OCP\Files\StorageNotAvailableException;
+use OC\Files\Storage\FailedStorage;
+
+class InvalidStorage extends FailedStorage {
+	public function __construct($params) {
+		throw new StorageNotAvailableException();
```
Comment (jvillafanez) [inline lib/private/Files/External/InvalidStorage.php]: This seems too "artificial" for me. Creating a class that would throw an exception in the constructor implies that you want to throw the exception in the first place, which makes me wonder why do we need to create a class for that.

It probably makes more sense if the exception is thrown in specific methods even if those methods are almost all of them. My point is that the InvalidStorage should behave as another storage, but that exception doesn't allow it.

Comment (PVince81) [reply lib/private/Files/External/InvalidStorage.php]: The actual reason is that at the location where we specify the class name we don't actually instantiate it. Remember that the external storage backend class must specify a name for the storage class to be instantiated, it doesn't instantiate it itself, but MountPoint->createStorage will instantiate it later. Throwing an exception in the constructor is to make sure this never happens.

Comment (jvillafanez) [reply lib/private/Files/External/InvalidStorage.php]: My worry is that this is something that wasn't originally planned.

Due to there isn't an oficial storage factory, other apps like WND have to create the storages on their own. Throwing the exception like that will likely affect them even if the storage won't be used. I'll have to recheck the behaviour.
Creating the storage and throwing the exception in the rest of the methods seems a more compatible option.

Comment (jvillafanez) [reply lib/private/Files/External/InvalidStorage.php]: ok, it seems WND will check the backend class and won't try to create an storage instance if it isn't for the WND backend

Comment (PVince81) [reply lib/private/Files/External/InvalidStorage.php]: There is a `StorageFactory` class: https://github.com/owncloud/core/blob/v10.0.3/lib/private/Files/Storage/StorageFactory.php and here is the code that instantiates storages: https://github.com/owncloud/core/blob/v10.0.3/lib/private/Files/Mount/MountPoint.php#L138 (the $loader is actually an instance of `StorageFactory`.

In general third party apps should never instantiate the storage class themselves.

The use case of this InvalidStorage class should also never be accessible for apps as it's designed for use by core when accessing a storage for which the actual storage class does not exist due to the app being disabled.

Comment (jvillafanez) [reply lib/private/Files/External/InvalidStorage.php]: I'm out of arguments against it, but it still feels like adding tomato to the spaghetti code... 🤕

Comment (PVince81) [reply lib/private/Files/External/InvalidStorage.php]: Hahaha, it does.

Unfortunately the backends came after the storages. If we designed storages to have backends first, we could have designed it so that the backend is responsible of instantiating storages, in which case this mess above wouldn't required.

**Comment by PVince81** [comment]
rebased

**Comment by PVince81** [comment]
```
    Test\Files\External\Service\GlobalStoragesServiceTest.testCreateStorageInvalidClass
    Test\Files\External\Service\GlobalStoragesServiceTest.testCreateStorageInvalidAuthMechanismClass
    Test\Files\External\Service\UserGlobalStoragesServiceTest.testCreateStorageInvalidClass
    Test\Files\External\Service\UserGlobalStoragesServiceTest.testCreateStorageInvalidAuthMechanismClass
    Test\Files\External\Service\UserStoragesServiceTest.testCreateStorageInvalidClass
    Test\Files\External\Service\UserStoragesServiceTest.testCreateStorageInvalidAuthMechanismClass
```

**Comment by PVince81** [comment]
failing tests, moving to planned for next release

**Comment by PVince81** [comment]
rebased, fixed tests

**Comment by PVince81** [comment]
I've retested all cases from the first ticket.
The only missing thing is:

- [ ] BUG: prevent exporting incomplete config from CLI when backend is not known.

**Comment by PVince81** [comment]
I decided to only display a warning when listing configs on the CLI. The warning tells about how many invalid storages there are and that the admin must enable apps, else the config is incomplete.
The warning doesn't appear when exporting to JSON because we can't output to stderr directly from OutputInterface.

**Comment by PVince81** [comment]
@jvillafanez second review ?

**Comment by PVince81** [comment]
Squashed a few unit test additions to increase coverage.

File: apps/files_external/lib/Command/ListCommand.php [hunk 2]
```diff
@@ -256,6 +262,20 @@ public function listMounts($userId, array $mounts, InputInterface $input, Output
 			$table->setHeaders($headers);
 			$table->setRows($rows);
 			$table->render();
+
+			if ($countInvalid > 0) {
+				$is = 'is';
```
Comment (jvillafanez) [inline apps/files_external/lib/Command/ListCommand.php]: I'd rather use 2 different messages or use a different message such as "number of invalid storages: $countInvalid"

**Comment by PVince81** [comment]
- [ ] BUG: when only auth plugin is not available, the config that had it selected looks broken:

This is with SFTP and keypair, but I commented out registration of the keypair plugin after creation:
screenshot_20171113_120206

The right approach might be to do display something selected in the list but remove any other controls and add a text "Missing plugin for backend auth".

- [ ] add admin-friendly message whenever a storage backend is not found, something like "please verify that the apps providing the storage backend are installed and enabled". We can't tell which app it is though.

File: lib/public/Files/External/Auth/InvalidAuth.php [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+	/**
+	 * Constructs a new InvalidAuth with the id of the invalid auth
+	 * for display purposes
+	 *
+	 * @param string $invalidId invalid id
+	 *
+	 * @since 10.0.5
+	 */
+	public function __construct($invalidId) {
+		$this
```
Comment (jvillafanez) [inline lib/public/Files/External/Auth/InvalidAuth.php]: I think the following style is the most used, so we should keep it for consistency. The same for the `InvalidBackend`
```
$this->setIdentifier($invalidId)
	->setScheme(self::SCHEME_NULL)
	->setText('Unknown auth mechanism backend ' . $invalidId);
```

**Review by jvillafanez — APPROVED** [review]

**Comment by PVince81** [comment]
UI fixed:

- invalid storage backend:
screenshot_20171113_123316

- invalid auth backend:
screenshot_20171113_123237

**Comment by PVince81** [comment]
@jvillafanez adjusted styles and fixed the failiing test

**Comment by PVince81** [comment]
bah, of course I should have adjusted the tested message:
`OCA\Files_External\Tests\Command\ListCommandTest.testDisplayWarningForIncomplete`

**Comment by PVince81** [comment]
Fixed last test.

Also, I checked the codecov https://codecov.io/gh/owncloud/core/pull/26539/diff and all is green 😄

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/29562
