### PR TITLE
Use correct user and password when finding fileid in tag tests

### LINKED ISSUE #32912: Acceptance test TagsHelper assumes the password of sharer and sharee are the same
In ``tags.feature`` create ``user0`` and ``user1`` with different passwords.

Scenarios fail that receive a share from ``user0`` and try to add a tag to the shared file as ``user1``.

There is nothing wrong with ownCloud itself, just ``TagsHelper::tag`` uses the wrong user-password combination at one point.

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
1) Enhance ``TagsHelper`` so it can be passed the password of the file owner.
2) Use that password when the file owner is specified, otherwise use the tagging user name and password. (Because the tagging user could already be the file owner also)
3) Adjust calls in ``Tags.php`` trait.
4) Adjust Gherkin steps for tagging - when a user is tagging a file that they have proper access to, then they do not need to know/mention the UID and password of the file owner.

## Related Issue
- Fixes #32912 

## Motivation and Context
See issue description.

## How Has This Been Tested?
Local run of ``tags.feature``

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

File: tests/TestHelpers/TagsHelper.php [hunk 1]
```diff
@@ -38,22 +38,33 @@ class TagsHelper {
...
+			$fileOwner = $taggingUser;
+		}
+
+		if ($fileOwnerPassword === null) {
+			$fileOwnerPassword = $password;
+		}
+
 		$fileID = WebDavHelper::getFileIdForPath(
-			$baseUrl, $fileOwner, $password, $fileName
+			$baseUrl, $fileOwner, $fileOwnerPassword, $fileName
```
Comment (phil-davis) [inline tests/TestHelpers/TagsHelper.php]: This is the critical diff - the old code assumed that the password of the tagging user would be valid as the password of the file owner.

**Comment by phil-davis** [comment]
Backport ``stable10`` #32914

**Review by individual-it — APPROVED** [review]
