### PR TITLE
Fix decrypt of single user in decrypt-all command

### LINKED ISSUE #32161: decrypt-all does not work when a user is passed as an argument
decrypt-all command does not work when a user is passed as an argument.
 
### Steps to reproduce
1. Create 2 users `admin` and `user1`
2. Enable encryption with user-keys. ( for testing purpose I enabled recovery-keys for the 2 users )
3. Try to run decrypt-all for `user1`

### Expected behaviour
`user1` files should be decrypted

### Actual behaviour
`user1` files are not decrypted.

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
Tested against master branch of core + master branch of encryption app.

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

### PR DESCRIPTION
**Pull request by sharidas**
When a user is passed as an argument to decrypt-all
command the decryption was failing. This change helps
to fix the issue.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

When a user is passed as an argument to `decrypt-all` command the decryption was not happening. The root cause of the issue found was `prepareEncryptionModules()` was not called when single user is passed to `decrypt-all` command.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/32161

## Motivation and Context

When a user is passed as an argument to `decrypt-all` command the decryption was not happening.

## How Has This Been Tested?

- test environment: master branch of core + master branch of encryption app
- create 2 users `admin` and `user1`
- Try to enable encryption with user keys. And then login to both `admin` and `user1`
- Now try to run `decrypt-all` command with `user1`
- The files under `user1` are decrypted.
- This is also tested with masterkey encryption.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

File: lib/private/Encryption/DecryptAll.php [hunk 1]
```diff
@@ -180,6 +180,14 @@ protected function decryptAllUsersFiles($user = '') {
 				$userNo++;
 			});
 		} else {
+			if (\OC::$server->getConfig()->getAppValue('encryption', 'userSpecificKey', '0') !== '0') {
```
Comment (PVince81) [inline lib/private/Encryption/DecryptAll.php]: so the bug only affect user-key mode ?

File: lib/private/Encryption/DecryptAll.php [hunk 2]
```diff
@@ -180,6 +180,14 @@ protected function decryptAllUsersFiles($user = '') {
...
+				$userObject = $this->userManager->get($user);
+				if ($userObject !== null) {
+					if ($this->prepareEncryptionModules($userObject->getUID()) === false) {
```
Comment (PVince81) [inline lib/private/Encryption/DecryptAll.php]: shouldn't we also prepare the modules for master key anyway, even if their impl might not do anything?

File: lib/private/Encryption/DecryptAll.php (hunk 1 above)
Comment (sharidas) [reply lib/private/Encryption/DecryptAll.php]: Yes. This issue is found in user-key mode.

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@sharidas please backport

**Comment by sharidas** [comment]
Backport PR: https://github.com/owncloud/core/pull/32168
