### PR TITLE
modal parameter added while showing confirmation alert

### LINKED ISSUE #27357: Many pop-ups show if keep clicking wrongly mounted external storage
### Steps to reproduce
1. Wrongly mount an external storage of your choice ( I chose Local )
2. Go to file list, the wrongly mounted folder must be in red, keep clicking on it

### ScreenShots
a

### Expected behaviour
Only one pop-up should show

### Actual behaviour
Many pop-ups appear

### Server configuration
**Operating system**:
Ubuntu 16.10

**Web server:**
Apache

**Database:**
Sqlite

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
10.0.0.1

**Updated from an older ownCloud or fresh install:**
fresh

**Where did you install ownCloud from:**
GitHub

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - dav: 0.2.8
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_sharing: 0.10.0
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - example-theme
  - testing
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocopyznqq7cy",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/var\/www\/core\/data",
        "overwrite.cli.url": "http:\/\/localhost\/core",
        "dbtype": "sqlite3",
        "version": "10.0.0.1",
        "logtimezone": "UTC",
        "installed": true,
        "dbname": "owncloud",
        "dbhost": "localhost:5432",
        "dbtableprefix": "oc_"
    }
}
```

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** NO

### Client configuration
**Browser:**
Google Chrome Stable

**Operating system:**
ubuntu 16.10

#### Web server error log
```
Not Necessary
```

#### ownCloud log (data/owncloud.log)
```
Not Necessary
```

#### Browser log
```
Not Necessary
```

@PVince81 @tomneedham @owncloud/design

### PR DESCRIPTION
**Pull request by noveens**
## Description

Fixes #27357 

Single pop-up shown if keep clicking wrongly mounted external storage

## Related Issue

https://github.com/owncloud/core/issues/27357

## How Has This Been Tested?

Tested both as admin and non-admin user.

Even added that if user is non-admin, and at the alert "Yes" is pressed, a full page non-admin error wouldn't be shown ( in reference to #27285 ).

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

@PVince81

### CODE REVIEW

File: apps/files_external/js/statusmanager.js [hunk 1]
```diff
@@ -182,16 +182,21 @@ OCA.External.StatusManager = {
 					} else {
 						OC.dialogs.confirm(t('files_external', 'There was an error with message: ') + mountData.error + '. Do you want to review mount point config in admin settings page?', t('files_external', 'External mount error'), function (e) {
 							if (e === true) {
-								OC.redirect(OC.generateUrl('/settings/admin?sectionid=storage'));
+								if (OC.isUserAdmin()) {
```
Comment (noveens) [inline apps/files_external/js/statusmanager.js]: check introduced in reference to #27285

**Comment by jvillafanez** [comment]
👍

**Comment by SergioBertolinSG** [comment]
Works fine.

Nothing for this pull request but the error message doesn't look very nice.
The error messages are not translated, directly shows what exception has happened.

screen shot 2017-03-13 at 09 20 57

screen shot 2017-03-13 at 09 21 24

Something to take into account @felixheidecke @PVince81 .

**Review by SergioBertolinSG — APPROVED** [review]
