### PR TITLE
Check for redis to be 2.2.5+

### LINKED ISSUE #16113: Cannot enable or disable apps having redis cache active
### Steps to reproduce
1. Setup and configure a redis server (installed php5-redis, redis-server, and redis-tools from ubuntu repos; default configuration)
2. Configure ownCloud to use redis

    ```
     'memcache.local' => '\OC\Memcache\redis',
  'redis' => array(
        'host' => 'localhost', // can also be a unix domain socket: '/tmp/redis.sock'
        'port' => 6379,
        'timeout' => 0.0,
        'dbindex' => 0, // Optional, if undefined SELECT will not run and will use Redis Server's default DB Index.
  ),

    ```

3. Disable an enabled app

### Expected behaviour
App is disabled correctly

### Actual behaviour
Errors are thrown. The CLI also crashes with the same error.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 3

**Updated from an older ownCloud or fresh install:** fresh install

#### Web server error log
```
[Wed May 06 12:19:27.697092 2015] [:error] [pid 12475] [client 10.40.30.21:57928] PHP   3. OC\\Route\\Router->match() /home/jvillafanez/src/owncloud/owncloud2/lib/base.php:858, referer: http://10.40.30.21:8120/index.php/settings/apps
[Wed May 06 12:19:27.697142 2015] [:error] [pid 12475] [client 10.40.30.21:57928] PHP   4. call_user_func() /home/jvillafanez/src/owncloud/owncloud2/lib/private/route/router.php:272, referer: http://10.40.30.21:8120/index.php/settings/apps
[Wed May 06 12:19:27.697176 2015] [:error] [pid 12475] [client 10.40.30.21:57928] PHP   5. __lambda_func() /home/jvillafanez/src/owncloud/owncloud2/lib/private/route/router.php:272, referer: http://10.40.30.21:8120/index.php/settings/apps
[Wed May 06 12:19:27.697211 2015] [:error] [pid 12475] [client 10.40.30.21:57928] PHP   6. require_once() /home/jvillafanez/src/owncloud/owncloud2/lib/private/route/route.php(153) : runtime-created function:1, referer: http://10.40.30.21:8120/index.php/settings/apps
[Wed May 06 12:19:27.697256 2015] [:error] [pid 12475] [client 10.40.30.21:57928] PHP   7. OC_App::disable() /home/jvillafanez/src/owncloud/owncloud2/settings/ajax/disableapp.php:34, referer: http://10.40.30.21:8120/index.php/settings/apps
[Wed May 06 12:19:27.697299 2015] [:error] [pid 12475] [client 10.40.30.21:57928] PHP   8. OC\\App\\AppManager->disableApp() /home/jvillafanez/src/owncloud/owncloud2/lib/private/app.php:357, referer: http://10.40.30.21:8120/index.php/settings/apps
[Wed May 06 12:19:27.697343 2015] [:error] [pid 12475] [client 10.40.30.21:57928] PHP   9. OC\\App\\AppManager->clearAppsCache() /home/jvillafanez/src/owncloud/owncloud2/lib/private/app/appmanager.php:200, referer: http://10.40.30.21:8120/index.php/settings/apps
[Wed May 06 12:19:27.697387 2015] [:error] [pid 12475] [client 10.40.30.21:57928] PHP  10. OC\\Memcache\\Redis->clear() /home/jvillafanez/src/owncloud/owncloud2/lib/private/app/appmanager.php:208, referer: http://10.40.30.21:8120/index.php/settings/apps

```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"kDNpZBjWan50YOa3MfmJ","remoteAddr":"","app":"PHP","message":"Undefined class constant 'OPT_SCAN' at \/home\/jvillafanez\/src\/owncloud\/owncloud2\/lib\/private\/memcache\/redis.php#105","level":3,"time":"2015-05-06T10:17:16+00:00"}
{"reqId":"E5lxaDKGR49NPXrY7\/kN","remoteAddr":"","app":"PHP","message":"Undefined class constant 'OPT_SCAN' at \/home\/jvillafanez\/src\/owncloud\/owncloud2\/lib\/private\/memcache\/redis.php#105","level":3,"time":"2015-05-06T10:18:59+00:00"}
{"reqId":"mmy08xkXUHo847TU2zOH","remoteAddr":"10.40.30.21","app":"PHP","message":"Undefined class constant 'OPT_SCAN' at \/home\/jvillafanez\/src\/owncloud\/owncloud2\/lib\/private\/memcache\/redis.php#105","level":3,"time":"2015-05-06T10:19:27+00:00"}

```

### PR DESCRIPTION
**Pull request by nickvergessen**
In order to test the output of the warning, when you don't have one of the memcaches installed,
add `$outdatedCaches = $caches;` after the foreach in settings/admin.php

Fix #16113 
Documentation PR: https://github.com/owncloud/documentation/pull/1180

@DeepDiver1975 @jvillafanez

### CODE REVIEW

**Comment by nickvergessen** [comment]
cc @LukasReschke

File: lib/private/memcache/redis.php [hunk 1]
```diff
@@ -151,7 +151,8 @@ public function dec($key, $step = 1) {
 	}
 
 	static public function isAvailable() {
-		return extension_loaded('redis');
+		return extension_loaded('redis')
+			&& version_compare(phpversion('redis'), '2.2.5') !== -1;
```
Comment (MorrisJobke) [inline lib/private/memcache/redis.php]: can this be made more readable by using the third parameter with `>=`

File: settings/admin.php [hunk 2]
```diff
@@ -128,13 +129,23 @@
...
-	extension_loaded('apcu') && version_compare(phpversion('apc'), '4.0.6') === -1);
+// warn if outdated version of a memcache module is used
+$caches = [
+	'apcu'	=> ['name' => $l->t('APCu'), 'version' => '4.0.6'],
+	'redis'	=> ['name' => $l->t('Redis'), 'version' => '2.2.5'],
+];
+
+$outdatedCaches = [];
+foreach ($caches as $php_module => $data) {
+	$isOutdated = extension_loaded($php_module) && version_compare(phpversion($php_module), $data['version']) === -1;
```
Comment (MorrisJobke) [inline settings/admin.php]: Same as above applies here too

File: lib/private/memcache/redis.php (hunk 1 above)
Comment (nickvergessen) [inline lib/private/memcache/redis.php]: this is because I copied it from the apcu one, might change it there aswell

Comment (MorrisJobke) [inline lib/private/memcache/redis.php]: I'm fine with fixing this only, because APCu is completely unrelated. Do what you prefer :)

File: settings/admin.php (hunk 2 above)
Comment (nickvergessen) [inline settings/admin.php]: pushed

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by DeepDiver1975** [comment]
:+1:
