### PR TITLE
Drop OC_SubAdmin and replace usages

### LINKED ISSUE #20070: PHP fatal in subadmin
@rullzer 

````
Mon Oct 26 22:06:54 2015] PHP Fatal error:  Call to a member function getUID() on null in /home/deepdiver/Development/ownCloud/master/lib/private/subadmin.php on line 190
[Mon Oct 26 22:06:54 2015] PHP Stack trace:
[Mon Oct 26 22:06:54 2015] PHP   1. {main}() /home/deepdiver/Development/ownCloud/master/index.php:0
[Mon Oct 26 22:06:54 2015] PHP   2. OC::handleRequest() /home/deepdiver/Development/ownCloud/master/index.php:39
[Mon Oct 26 22:06:54 2015] PHP   3. OC\Route\Router->match() /home/deepdiver/Development/ownCloud/master/lib/base.php:852
[Mon Oct 26 22:06:54 2015] PHP   4. call_user_func:{/home/deepdiver/Development/ownCloud/master/lib/private/route/router.php:282}() /home/deepdiver/Development/ownCloud/master/lib/private/route/router.php:282
[Mon Oct 26 22:06:54 2015] PHP   5. OC\AppFramework\routing\RouteActionHandler->__invoke() /home/deepdiver/Development/ownCloud/master/lib/private/route/router.php:282
[Mon Oct 26 22:06:54 2015] PHP   6. OC\AppFramework\App::main() /home/deepdiver/Development/ownCloud/master/lib/private/appframework/routing/routeactionhandler.php:45
[Mon Oct 26 22:06:54 2015] PHP   7. Pimple\Container->offsetGet() /home/deepdiver/Development/ownCloud/master/lib/private/appframework/routing/routeactionhandler.php:100
[Mon Oct 26 22:06:54 2015] PHP   8. OC\AppFramework\DependencyInjection\DIContainer->OC\AppFramework\DependencyInjection\{closure}() /home/deepdiver/Development/ownCloud/master/3rdparty/pimple/pimple/src/Pimple/Container.php:113
[Mon Oct 26 22:06:54 2015] PHP   9. Pimple\Container->offsetGet() /home/deepdiver/Development/ownCloud/master/3rdparty/pimple/pimple/src/Pimple/Container.php:265
[Mon Oct 26 22:06:54 2015] PHP  10. OC\AppFramework\DependencyInjection\DIContainer->OC\AppFramework\DependencyInjection\{closure}() /home/deepdiver/Development/ownCloud/master/3rdparty/pimple/pimple/src/Pimple/Container.php:113
[Mon Oct 26 22:06:54 2015] PHP  11. Pimple\Container->offsetGet() /home/deepdiver/Development/ownCloud/master/3rdparty/pimple/pimple/src/Pimple/Container.php:312
[Mon Oct 26 22:06:54 2015] PHP  12. OC\Settings\Application->OC\Settings\{closure}() /home/deepdiver/Development/ownCloud/master/3rdparty/pimple/pimple/src/Pimple/Container.php:113
[Mon Oct 26 22:06:54 2015] PHP  13. OC\AppFramework\Utility\SimpleContainer->query() /home/deepdiver/Development/ownCloud/master/settings/application.php:169
[Mon Oct 26 22:06:54 2015] PHP  14. Pimple\Container->offsetGet() /home/deepdiver/Development/ownCloud/master/lib/private/appframework/utility/simplecontainer.php:104
[Mon Oct 26 22:06:54 2015] PHP  15. OC\Settings\Application->OC\Settings\{closure}() /home/deepdiver/Development/ownCloud/master/3rdparty/pimple/pimple/src/Pimple/Container.php:113
[Mon Oct 26 22:06:54 2015] PHP  16. OC_SubAdmin::isSubAdmin() /home/deepdiver/Development/ownCloud/master/settings/application.php:202
[Mon Oct 26 22:06:54 2015] PHP  17. OC\SubAdmin->isSubAdmin() /home/deepdiver/Development/ownCloud/master/lib/private/legacy/subadmin.php:143
[Mon Oct 26 22:06:54 2015] ::1:46908 [500]: /index.php/settings/apps - Call to a member function getUID() on null in /home/deepdiver/Development/ownCloud/master/lib/private/subadmin.php on line 190

### PR DESCRIPTION
**Pull request by LukasReschke**
Replaces https://github.com/owncloud/core/pull/20071 and fixes https://github.com/owncloud/core/issues/20070

Most of the lines are unit-tests adjustments or new unit-tests as some had to be completely thrown away.

@rullzer @MorrisJobke @DeepDiver1975 Please review carefully.

### CODE REVIEW

**Comment by LukasReschke** [comment]
Also summoning our chief regression expert @PVince81 :wink:

File: apps/provisioning_api/lib/users.php [hunk 1]
```diff
@@ -355,44 +383,47 @@ public function addToGroup($parameters) {
...
+		if(!$this->groupManager->isAdmin($loggedInUser->getUID()) && !$subAdminManager->isSubAdminofGroup($loggedInUser, $group)) {
 			return new OC_OCS_Result(null, 104);
 		}
 		// Check they aren't removing themselves from 'admin' or their 'subadmin; group
-		if($parameters['userid'] === $user->getUID()){
-			if($this->groupManager->isInGroup($user->getUID(), 'admin')){
-				if($group === 'admin'){
+		if($parameters['userid'] === $loggedInUser->getUID()) {
+			if($this->groupManager->isAdmin($loggedInUser->getUID())) {
+				if($group->getGID() === 'admin') {
```
Comment (PVince81) [inline apps/provisioning_api/lib/users.php]: I suppose we might want to have "admin" in a constant at some point

**Comment by PVince81** [comment]
Tested various combinations of subadmin setting + changing quota/displayname, etc. All worked :+1:

File: lib/public/igroupmanager.php [hunk 2]
```diff
@@ -134,4 +134,12 @@ public function isAdmin($userId);
...
 	 */
 	public function isInGroup($userId, $group);
+
+	/**
+	 * Returns the subadmin manager
+	 *
+	 * @return \OC\Subadmin
+	 * @since 9.0.0
+	 */
+	public function getSubAdmin();
```
Comment (blizzz) [inline lib/public/igroupmanager.php]: Oh, hello API change. In case of IGroupManager this most likely does not affect anyone at all, but should be mentioned in release notes anyway.

**Comment by blizzz** [comment]
Reviewed, tested and confirmed that users page does not give me BPoD, looks all good to me :+1:

File: lib/public/igroupmanager.php (hunk 2 above)
Comment (DeepDiver1975) [inline lib/public/igroupmanager.php]: Do we need to add this to the public api? Especially returning a private api class is :puke:

Comment (LukasReschke) [inline lib/public/igroupmanager.php]: We can also drop this but then we'd have no type hinting. I don't care TBH.

Comment (LukasReschke) [inline lib/public/igroupmanager.php]: *sigh* - actually this would require some other changes as well on the code :speak_no_evil:

Comment (LukasReschke) [inline lib/public/igroupmanager.php]: Option A) Change our code to reference `\OC\Group\Manager` instead of `IGroupManager` and access it.
Option B) Public API gets this.

Let me try A then…

Comment (LukasReschke) [inline lib/public/igroupmanager.php]: Moved out of public API.

Comment (blizzz) [inline lib/public/igroupmanager.php]: Stashing is nice, however with such a big changeset it's now somewhat inconvenient to follow your recent changes…

Comment (MorrisJobke) [inline lib/public/igroupmanager.php]: > Stashing

Squashing ;)

Comment (blizzz) [inline lib/public/igroupmanager.php]: yes, that one. thx for correcting  me.

Comment (LukasReschke) [inline lib/public/igroupmanager.php]: > it's now somewhat inconvenient to follow your recent changes…

That's the goal. I somehow got to hide our NSA compliance gateway - right?

Comment (blizzz) [inline lib/public/igroupmanager.php]: Be careful what you say in the Internets. The chance is very likely that 
people take this as a joke instead. Don't forget the serious-tags in such 
delicate cases.

File: apps/provisioning_api/lib/groups.php [hunk 3]
```diff
@@ -85,9 +84,16 @@ public function getGroup($parameters) {
 		if(!$this->groupManager->groupExists($parameters['groupid'])) {
 			return new OC_OCS_Result(null, \OCP\API::RESPOND_NOT_FOUND, 'The requested group could not be found');
 		}
+
+		$isSubadminOfGroup = false;
+		$targetGroupObject =$this->groupManager->get($parameters['groupid']);
+		if($targetGroupObject !== null) {
+			$isSubadminOfGroup =$this->groupManager->getSubAdmin()->isSubAdminofGroup($user, $targetGroupObject);
```
Comment (DeepDiver1975) [inline apps/provisioning_api/lib/groups.php]: What about simply instanciate the \OC\SubAdmin class here?

Comment (LukasReschke) [inline apps/provisioning_api/lib/groups.php]: Dependency Injection. If we instantiate \OC\SubAdmin then I'd have to mock the function arguments which actually would mean testing \OC\SubAdmin instead of this class.

Comment (DeepDiver1975) [inline apps/provisioning_api/lib/groups.php]: I know ..... grrr

**Comment by DeepDiver1975** [comment]
:+1:
