### PR TITLE
try token login first

### LINKED ISSUE #24727: 'Login failed' log entries when using token auth
### Steps to reproduce
1. Create a device password (PR #24703)
2. Configure desktop sync client with generated password
3. Watch the log file

### Expected behaviour
Client syncs without error

### Actual behaviour
``Login failed: 'username' (Remote IP: '::1')`` logged to owncloud.log

Sync seems to work though.

### Server configuration
**Operating system**:

**Web server:**
PHP built-in

**Database:**
Sqlite

**PHP version:**
7.0.6

**ownCloud version:** (see ownCloud admin page)
master

### PR DESCRIPTION
**Pull request by ChristophWurst**
When checking password login first, the user manager logs a failed login attempt to owncloud.log. To prevent that the order is inverted and token auth is tried first.

partially fixes #24727

and fixes the unreported (found it while fixing) bug that the login hook was triggered with the token instead of the actual login password :boom: 

@rullzer @LukasReschke

### CODE REVIEW

File: lib/private/User/Session.php [hunk 1]
```diff
@@ -287,12 +287,20 @@ public function getLoginName() {
...
+		if ($this->validateToken($password)) {
+			$user = $this->getUser();
+
+			// When logging in with token, the password must be decrypted first before passing to login hook
+			try {
+				$token = $this->tokenProvider->getToken($password);
+				$password = $this->tokenProvider->getPassword($token, $password);
+				$this->manager->emit('\OC\User', 'preLogin', array($uid, $password));
+			} catch (InvalidTokenException $ex) {
+
```
Comment (PVince81) [inline lib/private/User/Session.php]: please add a comment why this exception isn't handled, else it looks like a mistake

**Comment by PVince81** [comment]
Code looks good otherwise, please add the missing comment :+1: 

Second review ? @nickvergessen @schiesbn @rullzer @LukasReschke @MorrisJobke

File: lib/private/User/Session.php (hunk 1 above)
Comment (ChristophWurst) [inline lib/private/User/Session.php]: fixed

**Comment by nickvergessen** [comment]
works :+1:
