### PR TITLE
Adjust expiration logic for shares to account for share attributes registered with apps

### LINKED ISSUE #36813: [OC-8] Problems setting sharing permissions in the webUI when user and group have same name
### Steps to reproduce
1. create user "finance" and group "finance"
2. using the webUI, share a file or folder with both the user and then the group "finance"
3. open the sharing permissions of both in the webUI
4. change the sharing permissions of the group "finance"

### Expected behaviour
The sharing permissions of the group change.
The sharing permissions of the user do not change.

### Actual behaviour
The sharing permissions of the user change.
The sharing permissions of the group do not change.

### Server configuration
current master

### PR DESCRIPTION
**Pull request by mrow4a**
related issue: https://github.com/owncloud/core/issues/36751

also last commit fixes #36813 

- [x] rollback html and css structure changes from https://github.com/owncloud/core/pull/36573 that broke compatibility with advanced share attributes that get registered by apps (example: https://github.com/owncloud/richdocuments/blob/master/js/viewer/shareoptions.js#L222-L260 and https://github.com/ONLYOFFICE/onlyoffice-owncloud/blob/master/js/share.js#L322-L372)
- [x] make sure expiration code works as expected
- [x] adjust required unit and acceptance tests
- [x] add js test to share attributes v2 checking proper rendering

ezgif com-video-to-gif-2

### CODE REVIEW

File: lib/private/Share20/Manager.php [hunk 1]
```diff
@@ -1824,31 +1824,17 @@ private function strictSubsetOfPermissions($allowedPermissions, $newPermissions)
...
 	/**
-	 * Check $newAttributes attribute is a subset of $allowedAttributes
+	 * Check $newAttributes attribute is a subset of $allowedAttributes.
+	 * Attributes cannot be modified or removed
 	 *
 	 * @param IAttributes $allowedAttributes
 	 * @param IAttributes $newAttributes
 	 * @return boolean ,true if $allowedAttributes enabled is super set of $newAttributes enabled, else false
 	 */
 	private function strictSubsetOfAttributes($allowedAttributes, $newAttributes) {
```
Comment (jvillafanez) [inline lib/private/Share20/Manager.php]: Maybe we should add the `IAttributes` type hint here

**Review by jvillafanez — COMMENTED** [review]
Code looks good

File: core/js/shareitemmodel.js [hunk 2]
```diff
@@ -695,11 +686,15 @@
...
+				// update model properties,
+				// this should cause rerendering of the object
 				model.set(model.parse({
 					shares: sharesMap,
 					reshare: reshare
 				}), {
-					silent: options.silent
+					// do not allow silent, as apps might rely on reacting to
+					// changes to the model
+					silent: false,
```
Comment (mrow4a) [inline core/js/shareitemmodel.js]: @jvillafanez @felixheidecke @micbar this was the biggest cause of problems. advanced share attributes rely on changes in the model (they hook to it), and even if attributes switched the model rendering was not triggered.

Comment (mrow4a) [reply core/js/shareitemmodel.js]: This is also why acceptance tests were successful. They check that in DB (!) the attributes are properly set, and they were. The UI was broken.

Comment (phil-davis) [reply core/js/shareitemmodel.js]: I guess that acceptance tests are checking via the sharing API that the expected share settings have happened.
Should we add some checks in relevant webUI scenarios to make sure that the expected/correct share settings boxes are checked/unchecked on the UI?

(and I guess that some of this depends on being running an app that has extended share permissions - so some rich-documents UI  scenarios would be needed?)

**Comment by phil-davis** [comment]
I  rebased and force-pushed because this was getting weird drone errors. Let's see what an up-to-date CI run says.

**Comment by micbar** [comment]
@phil-davis We need to make sure, that this JS api does not break again.

@mrow4a 
We target a new RC2 on monday.

**Comment by mrow4a** [comment]
@phil-davis could you have a look now?

**Comment by phil-davis** [comment]
Here is a strange behaviour:
1) have richdocuments Secure View enabled
2) share something with Secure View checkbox checked, (and an expiration date set, optional)
3) click the `x` to the right of the expiration date field, to clear the expiration date

Expected behaviour: the expiration date is cleared, and all permissions checkboxes remain as they are.

Actual behaviour: the expiration date is cleared, and the Secure View checkbox gets "automagically" unchecked.

This "normal" core scenario works fine:
1) have richdocuments Secure View enabled
2) share something with "can edit", "creat", "change", "delete" checkboxes checked, (and an expiration date set, optional)
3) click the `x` to the right of the expiration date field, to clear the expiration date

The expiration date is cleared, the permissions checkboxes remain as they are - correct.

@mrow4a

File: lib/private/Share20/Manager.php [hunk 3]
```diff
@@ -1824,31 +1829,17 @@ private function strictSubsetOfPermissions($allowedPermissions, $newPermissions)
 	}
 
 	/**
-	 * Check $newAttributes attribute is a subset of $allowedAttributes
+	 * Check $newAttributes attribute is a subset of $allowedAttributes.
```
Comment (phil-davis) [inline lib/private/Share20/Manager.php]: the parameters are called `requiredAttributes` and `newAttributes` but this description mentions `allowedAttributes` ???

File: lib/private/Share20/Manager.php [hunk 4]
```diff
@@ -1824,31 +1829,17 @@ private function strictSubsetOfPermissions($allowedPermissions, $newPermissions)
...
+	 * Existing attributes cannot be modified
 	 *
-	 * @param IAttributes $allowedAttributes
+	 * @param IAttributes $requiredAttributes
 	 * @param IAttributes $newAttributes
 	 * @return boolean ,true if $allowedAttributes enabled is super set of $newAttributes enabled, else false
```
Comment (phil-davis) [inline lib/private/Share20/Manager.php]: the parameters are called `requiredAttributes` and `newAttributes` but this return value description mentions `allowedAttributes` ???

File: lib/private/Share20/Manager.php [hunk 5]
```diff
@@ -372,14 +372,19 @@ protected function validatePermissions(IShare $share) {
...
 			throw new GenericShareException($message_t, $message_t, 404);
 		}
 
-		/* Check that we do not share with more attributes than we have */
-		if ($maxAttributes !== null && !$this->strictSubsetOfAttributes($maxAttributes, $share->getAttributes())) {
+		/**
+		 * Check that all required share attributes that were set on the file
+		 * will be respected when reshared.
+		 */
+		if ($maxAttributes !== null && !$this->checkRequiredAttributes($maxAttributes, $share->getAttributes())) {
```
Comment (phil-davis) [inline lib/private/Share20/Manager.php]: unit tests are failing because `$share->getAttributes()` is null:
```
make test-php-unit NOCOVERAGE=true TEST_PHP_SUITE=apps/files_sharing/tests/EtagPropagationTest.php
Runtime:       PHP 7.3.13-1+ubuntu18.04.1+deb.sury.org+1 with Xdebug 2.9.0
Configuration: /home/phil/git/owncloud/core/tests/phpunit-autotest.xml

EEEEEEEEEEEEEEEEEEEEEEEEE                                         25 / 25 (100%)

Time: 3.31 seconds, Memory: 24.00 MB

There were 25 errors:

1) OCA\Files_Sharing\Tests\EtagPropagationTest::testOwnerWritesToShare
TypeError: Argument 2 passed to OC\Share20\Manager::checkRequiredAttributes() must implement interface OCP\Share\IAttributes, null given, called in /home/phil/git/owncloud/core/lib/private/Share20/Manager.php on line 387

/home/phil/git/owncloud/core/lib/private/Share20/Manager.php:1839
/home/phil/git/owncloud/core/lib/private/Share20/Manager.php:387
/home/phil/git/owncloud/core/lib/private/Share20/Manager.php:297
/home/phil/git/owncloud/core/lib/private/Share20/Manager.php:697
/home/phil/git/owncloud/core/apps/files_sharing/tests/EtagPropagationTest.php:133
/home/phil/git/owncloud/core/apps/files_sharing/tests/PropagationTestCase.php:40
...
```

`$share->getAttributes()` somehow is returning NULL here???

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/22714/46/13
acceptance test fails, here I run it locally:
```
make test-acceptance-api BEHAT_FEATURE=tests/acceptance/features/apiShareManagementBasic/createShare.feature:427
Running apiShareManagementBasic tests tagged ~@skipOnOcV10&&~@skipOnOcV10.4&&~@skipOnOcV10.4.0&&@api&&~@skip 
@api @TestAlsoOnExternalUserBackend @files_sharing-app-required
Feature: sharing

  Background:                                                                    # /home/phil/git/owncloud/core/tests/acceptance/features/apiShareManagementBasic/createShare.feature:4
    Given using old DAV path                                                     # FeatureContext::usingOldOrNewDavPath()
    And user "user0" has been created with default attributes and skeleton files # FeatureContext::userHasBeenCreatedWithDefaultAttributes()

  Scenario: Share a file by multiple channels and download from sub-folder and direct file share                                        # /home/phil/git/owncloud/core/tests/acceptance/features/apiShareManagementBasic/createShare.feature:427
    Given these users have been created with default attributes and skeleton files:                                                     # FeatureContext::theseUsersHaveBeenCreated()
      | username |
      | user1    |
      | user2    |
    And group "grp1" has been created                                                                                                   # FeatureContext::groupHasBeenCreated()
    And user "user1" has been added to group "grp1"                                                                                     # FeatureContext::userHasBeenAddedToGroup()
    And user "user2" has been added to group "grp1"                                                                                     # FeatureContext::userHasBeenAddedToGroup()
    And user "user0" has created folder "/common"                                                                                       # FeatureContext::userHasCreatedFolder()
    And user "user0" has created folder "/common/sub"                                                                                   # FeatureContext::userHasCreatedFolder()
    And user "user0" has shared folder "common" with group "grp1"                                                                       # FeatureContext::userHasSharedFileWithGroupUsingTheSharingApi()
    And user "user1" has shared file "textfile0.txt" with user "user2"                                                                  # FeatureContext::userHasSharedFileWithUserUsingTheSharingApi()
    And user "user1" has moved file "/textfile0.txt" to "/common/textfile0.txt"                                                         # FeatureContext::userHasMovedFile()
      Failed asserting that 500 matches expected 201.
    And user "user1" has moved file "/common/textfile0.txt" to "/common/sub/textfile0.txt"                                              # FeatureContext::userHasMovedFile()
    When user "user2" uploads file "filesForUpload/file_to_overwrite.txt" to "/textfile0 (2).txt" using the WebDAV API                  # FeatureContext::userUploadsAFileTo()
    And user "user2" downloads file "/common/sub/textfile0.txt" with range "bytes=0-8" using the WebDAV API                             # FeatureContext::userDownloadsFileWithRange()
    Then the downloaded content should be "BLABLABLA"                                                                                   # FeatureContext::downloadedContentShouldBe()
    And the downloaded content when downloading file "/textfile0 (2).txt" for user "user2" with range "bytes=0-8" should be "BLABLABLA" # FeatureContext::downloadedContentWhenDownloadingForUserWithRangeShouldBe()
    And user "user2" should see the following elements                                                                                  # FeatureContext::userShouldSeeTheElements()
      | /common/sub/textfile0.txt |
      | /textfile0%20(2).txt      |

--- Failed scenarios:

    /home/phil/git/owncloud/core/tests/acceptance/features/apiShareManagementBasic/createShare.feature:427

1 scenario (1 failed)
17 steps (10 passed, 1 failed, 6 skipped)
0m16.46s (17.70Mb)
```

and `owncloud.log` has:
```
{"reqId":"MELQdktltc7pEPCF19bn","level":4,"time":"2020-01-17T05:26:25+00:00","remoteAddr":"192.168.1.25","user":"user1","app":"webdav","method":"MOVE","url":"\/remote.php\/webdav\/textfile0.txt","message":"Exception: Argument 2 passed to OC\\Share20\\Manager::checkRequiredAttributes() must implement interface OCP\\Share\\IAttributes, null given, called in \/home\/phil\/git\/owncloud\/core\/lib\/private\/Share20\/Manager.php on line 387: {\"Exception\":\"TypeError\",\"Message\":\"Argument 2 passed to OC\\\\Share20\\\\Manager::checkRequiredAttributes() must implement interface OCP\\\\Share\\\\IAttributes, null given, called in \\\/home\\\/phil\\\/git\\\/owncloud\\\/core\\\/lib\\\/private\\\/Share20\\\/Manager.php on line 387\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/phil\\\/git\\\/owncloud\\\/core\\\/lib\\\/private\\\/Share20\\\/Manager.php(387): OC\\\\Share20\\\\Manager->checkRequiredAttributes(Object(OC\\\\Share20\\\\ShareAttributes), NULL)\\n#1 \\\/home\\\/phil\\\/git\\\/owncloud\\\/core\\\/lib\\\/private\\\/Share20\\\/Manager.php(297): OC\\\\Share20\\\\Manager->validatePermissions(Object(OC\\\\Share20\\\\Share))\\n#2 \\\/home\\\/phil\\\/git\\\/owncloud\\\/core\\\/lib\\\/private\\\/Share20\\\/Manager.php(942): OC\\\\Share20\\\\Manager->generalChecks(Object(OC\\\\Share20\\\\Share))\\n#3 \\\/home\\\/phil\\\/git\\\/owncloud\\\/core\\\/apps\\\/files_sharing\\\/lib\\\/Updater.php(82): OC\\\\Share20\\\\Manager->updateShare(Object(OC\\\\Share20\\\\Share))\\n#4 \\\/home\\\/phil\\\/git\\\/owncloud\\\/core\\\/apps\\\/files_sharing\\\/lib\\\/Updater.php(34): OCA\\\\Files_Sharing\\\\Updater::moveShareToShare('\\\/common\\\/textfil...')\\n#5 \\\/home\\\/phil\\\/git\\\/owncloud\\\/core\\\/lib\\\/private\\\/legacy\\\/hook.php(103): OCA\\\\Files_Sharing\\\\Updater::renameHook(Array)\\n#6 \\\/home\\\/phil\\\/git\\\/owncloud\\\/core\\\/lib\\\/private\\\/Files\\\/View.php(903): OC_Hook::emit('OC_Filesystem', 'post_rename', Array)\\n#7 \\\/home\\\/phil\\\/git\\\/owncloud\\\/core\\\/lib\\\/public\\\/Events\\\/EventEmitterTrait.php(50): OC\\\\Files\\\\View->OC\\\\Files\\\\{closure}(Array)\\n#8 \\\/home\\\/phil\\\/git\\\/owncloud\\\/core\\\/lib\\\/private\\\/Files\\\/View.php(918): OC\\\\Files\\\\View->emittingCall(Object(Closure), Array, 'file', 'rename')\\n#9 \\\/home\\\/phil\\\/git\\\/owncloud\\\/core\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(481): OC\\\\Files\\\\View->rename('\\\/textfile0.txt', '\\\/common\\\/textfil...')\\n#10 \\\/home\\\/phil\\\/git\\\/owncloud\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(164): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->moveInto('textfile0.txt', 'textfile0.txt', Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File))\\n#11 \\\/home\\\/phil\\\/git\\\/owncloud\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(641): Sabre\\\\DAV\\\\Tree->move('textfile0.txt', 'common\\\/textfile...')\\n#12 \\\/home\\\/phil\\\/git\\\/owncloud\\\/core\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(96): Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/home\\\/phil\\\/git\\\/owncloud\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(474): Sabre\\\\DAV\\\\Server->emit('method:MOVE', Array)\\n#14 \\\/home\\\/phil\\\/git\\\/owncloud\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(251): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#15 \\\/home\\\/phil\\\/git\\\/owncloud\\\/core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(319): Sabre\\\\DAV\\\\Server->start()\\n#16 \\\/home\\\/phil\\\/git\\\/owncloud\\\/core\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(65): Sabre\\\\DAV\\\\Server->exec()\\n#17 \\\/home\\\/phil\\\/git\\\/owncloud\\\/core\\\/remote.php(165): require_once('\\\/home\\\/phil\\\/git\\\/...')\\n#18 {main}\",\"File\":\"\\\/home\\\/phil\\\/git\\\/owncloud\\\/core\\\/lib\\\/private\\\/Share20\\\/Manager.php\",\"Line\":1839}"}
```
Which is the same problem as in the unit tests.

**Comment by mrow4a** [comment]
@davitol @phil-davis thank you for your excellent work in helping to spot an issue and review ! This was very helpful 

Regarding issue with secure-view+expiration, good catch - fix for richdocuments https://github.com/owncloud/richdocuments/pull/313 and onlyoffice https://github.com/ONLYOFFICE/onlyoffice-owncloud/pull/299 apps

**Comment by mrow4a** [comment]
@davitol @phil-davis just tested with onlyoffice/collabora in reshare and some complicated scenarious also manually, and all good.

**Comment by micbar** [comment]
@phil-davis @mrow4a are we sure now, that we have this JS api covered with acceptance tests?

**Comment by phil-davis** [comment]
I rebased just now, there were other changes merged in master today, so I want to be able to run with the latest acceptance test etc code.

I am looking at what other acceptance test scenarios we can add to core that can verify that permissions checkboxes and the expiration date field do not mess with each other.

**Comment by mrow4a** [comment]
@phil-davis I actually though maybe acceptance tests are ok. Maybe we can add 1 more scenario in JS unit tests https://github.com/owncloud/core/blob/e7e433ecd00828cd0c8eeba90711049b3b69d4e7/core/js/tests/specs/shareitemmodelSpec.js#L724-L756 but instead also using jQuery and guarding HTML with div etc? thoughts?

**Comment by phil-davis** [comment]
Yes sure if you are good at JS tests!

File: core/js/sharedialogshareelistview.js [hunk 6]
```diff
@@ -16,90 +16,84 @@
...
+		'				<button class="removeExpiration">Remove</button>' +
+		'			</label>' +
 		'			{{/if}}' +
-		'			<span class="has-tooltip username" title="{{shareWith}}">{{shareWithDisplayName}}</span>' +
-		'		</div>' + 
-		'		<div class="shareWithList__container--right">'+
-		'			{{#if expirationDate}}' +
-		'			<div class="action-item"><span class="icon icon-time"></span><span class="hidden-visually">{{unshareLabel}}</span></div>' +
+		'			{{#if isGroupShare}}' +
+		'			<label for="expiration-{{name}}-{{cid}}-{{shareWith}}">Expire share on: ' +
```
Comment (phil-davis) [inline core/js/sharedialogshareelistview.js]:
```suggestion
		'			<label for="expiration-{{name}}-{{cid}}-{{shareWith}}">Expiration: ' +
```
(we noticed that this text was different from the text for users - IMO it should be the same)

File: core/js/sharedialogshareelistview.js [hunk 7]
```diff
@@ -16,90 +16,84 @@
...
+		'				<input type="text" id="expiration-{{name}}-{{cid}}-{{shareWith}}" value="{{expirationDate}}" class="expiration expiration-group"/>' +
```
Comment (phil-davis) [inline core/js/sharedialogshareelistview.js]:
```suggestion
		'				<input type="text" id="expiration-{{name}}-{{cid}}-{{shareWith}}" value="{{expirationDate}}" class="expiration expiration-group" placeholder="Choose an expiration date" />' +
```
also IMO this should be the same as for a user

File: core/js/sharedialogshareelistview.js (hunk 6 above)
Comment (phil-davis) [reply core/js/sharedialogshareelistview.js]: fixed

File: core/js/sharedialogshareelistview.js (hunk 7 above)
Comment (phil-davis) [reply core/js/sharedialogshareelistview.js]: fixed

**Comment by micbar** [comment]
@mrow4a @phil-davis We will wait with the 10.4 until we are fully sure that the api is stable.
We just discussed this in the BTR standup.

**Comment by mrow4a** [comment]
@micbar @phil-davis I added a new test to `core/js/tests/specs/sharedialogshareelistview.js` that should do what we require. I noticed that this class is full of checks for attributes v1, but not for attributes v2 (this was somehow overlooked, and probably this is why we had the #36751)

**Comment by phil-davis** [comment]
@mrow4a my commit from yesterday got lost - please make sure to pull the latest code from GitHub before making more changes.

I added the code back - https://github.com/owncloud/core/pull/36766/commits/21c20905672e208bce916b0af338fa1a15e80829 - "Make group and user expiration texts the same"

My question is:
https://github.com/owncloud/core/pull/36766/files#diff-e8d8565fb4fcb24d2ff551b5e127cf6a `core/js/sharedialogshareelistview.js` has stuff about `expirationOption` with `if isUserShare` and `if isGroupShare` and that has code like:
```
		'		<div class="expirationOption">' +
		'			{{#if isUserShare}}' +
		'			<label for="expiration-{{name}}-{{cid}}-{{shareWith}}">Expiration: ' +
		'				<input type="text" id="expiration-{{name}}-{{cid}}-{{shareWith}}" value="{{expirationDate}}" class="expiration expiration-user" placeholder="Choose an expiration date" />' +
		'				<button class="removeExpiration">Remove</button>' +
		'			</label>' +
		'			{{/if}}' +
		'			{{#if isGroupShare}}' +
		'			<label for="expiration-{{name}}-{{cid}}-{{shareWith}}">Expiration: ' +
		'				<input type="text" id="expiration-{{name}}-{{cid}}-{{shareWith}}" value="{{expirationDate}}" class="expiration expiration-group" placeholder="Choose an expiration date" />' +
		'				<button class="removeExpiration">Remove</button>' +
		'			</label>' +
		'			{{/if}}' +
		'		</div>' +
```

But also https://github.com/owncloud/core/blob/master/core/js/sharedialogexpirationview.js has code like:
```
			this.$el.html(this.template({
				cid: this.cid,
				setExpirationLabel: t('core', 'Set expiration date'),
				expirationLabel: t('core', 'Expiration'),
				expirationDatePlaceholder: t('core', 'Choose an expiration date'),
				defaultExpireMessage: defaultExpireMessage,
				isExpirationSet: isExpirationSet,
				isExpirationEnforced: isExpirationEnforced,
				disableCheckbox: isExpirationEnforced && isExpirationSet,
				expirationValue: expiration
			}));
```
which also has the text "Expiration" and "Choose an expiration date"

why is there that duplication? what code is actually used???

File: core/js/sharedialogshareelistview.js [hunk 8]
```diff
@@ -16,90 +16,84 @@
...
-		'			<span class="has-tooltip username" title="{{shareWith}}">{{shareWithDisplayName}}</span>' +
-		'		</div>' + 
-		'		<div class="shareWithList__container--right">'+
-		'			{{#if expirationDate}}' +
-		'			<div class="action-item"><span class="icon icon-time"></span><span class="hidden-visually">{{unshareLabel}}</span></div>' +
+		'			{{#if isGroupShare}}' +
+		'			<label for="expiration-{{name}}-{{cid}}-{{shareWith}}">Expiration: ' +
+		'				<input type="text" id="expiration-{{name}}-{{cid}}-{{shareWith}}" value="{{expirationDate}}" class="expiration expiration-group" placeholder="Choose an expiration date" />' +
+		'				<button class="removeExpiration">Remove</button>' +
+		'			</label>' +
```
Comment (mrow4a) [inline core/js/sharedialogshareelistview.js]: @phil-davis seems some `template` values from JS are not filled here (unfinished code from https://github.com/owncloud/core/pull/36573). We can finish that

Comment (phil-davis) [reply core/js/sharedialogshareelistview.js]: will need to happen for both user and group cases

Comment (mrow4a) [reply core/js/sharedialogshareelistview.js]: @phil-davis I might be able to do it in the evening. Wanna take it?

Comment (phil-davis) [reply core/js/sharedialogshareelistview.js]: I had a quick look, but I don't really know what I am doing. I tried replacing `Choose an expiration date` test with `{{expirationDatePlaceholder}}` and got no joy. Time for home here!
@mrow4a feel free to look...

Comment (mrow4a) [reply core/js/sharedialogshareelistview.js]: @phil-davis just amended your commit with proper implementation. It all should be good now

Comment (mrow4a) [reply core/js/sharedialogshareelistview.js]: have a look into https://github.com/owncloud/core/pull/36766/commits/94377bc2201d983d1d58ae11ea3dfbd2db037d41 to understand better

Comment (phil-davis) [reply core/js/sharedialogshareelistview.js]: That works - I would never have guessed to do all that.
Now see commit https://github.com/owncloud/core/pull/36766/commits/b17659d8fe7b9fd7e5befeab57c5d539a738414c
I removed various items from  `core/js/sharedialoglinkexpirationview.js`

Why is stuff duplicated there?

Comment (mrow4a) [reply core/js/sharedialogshareelistview.js]: @phil-davis why did you do that? User/Group expiration != Link expiration. These are two different things.. We need both!

Comment (mrow4a) [reply core/js/sharedialogshareelistview.js]: Link Share expiration template - https://github.com/owncloud/core/blob/b17659d8fe7b9fd7e5befeab57c5d539a738414c/core/js/sharedialoglinkexpirationview.js#L18-L28
User/Group expiration template - https://github.com/owncloud/core/blob/b17659d8fe7b9fd7e5befeab57c5d539a738414c/core/js/sharedialogshareelistview.js#L40-L57

Comment (phil-davis) [reply core/js/sharedialogshareelistview.js]: Hmmm - I got my search wrong somehow. Surprisingly CI passed!
`setExpirationLabel` is not used (I can't find it)
`expirationLabel` is used
`expirationDatePlaceholder` is used
`disableCheckbox` is not used (I can't find it)
Anyway, I will remove the commit.

Unfortunately text like `Choose an expiration date` is duplicated in both places, but I guess that is life and is not fr this PR to fix.

**Comment by phil-davis** [comment]
This LGTM now. I tried with richdocuments and the secure-view checkboxes work for me along with the other "ordinary" permissions checkboxes.

@micbar can someone review the code? If all OK then we could merge.

**Comment by phil-davis** [comment]
Note: issue #36813 is an existing problem when sharing with a user and a group that have the same name. Now that we have an expiration date field, that field has the same issue when there is this "duplicate" sharing. So that is not the fault of the new expiration date code.

**Comment by micbar** [comment]
@mrow4a Please create a changelog item https://github.com/owncloud/core/pull/36766#issuecomment-574450660

File: core/css/share.css [hunk 9]
```diff
@@ -134,6 +140,37 @@
 	margin: 0 3px 0 8px;
 	vertical-align: middle;
 }
+a.showCruds {
+	display: inline;
+	opacity: 0.5;
+}
+
+a.unshare {
```
Comment (PVince81) [inline core/css/share.css]: this feels a bit too generic and could clash with other parts, especially considering that this isn't specifying general rules for an unshare button but rules specific for a given contain.

can you add a more specific selector, like for example adding the class of the target container ?

the same comment applies for the other "a.*" rules in this file

File: core/js/sharedialogshareelistview.js [hunk 10]
```diff
@@ -122,13 +120,15 @@
 		/** @type {Function} **/
 		_template: undefined,
 
+		_currentlyToggled: [],
```
Comment (PVince81) [inline core/js/sharedialogshareelistview.js]: this has been declared as indexed array but its usage looks like it's a hash array instead, so would need to be declared as `{}`

File: core/js/sharedialogshareelistview.js [hunk 11]
```diff
@@ -431,25 +450,50 @@
...
-			$target.closest('.shareWithList__item').toggleClass('shareWithList__item--detailed').find('.shareWithList__details').toggleClass('hidden');
+			this._toggleShareDetails(event);
+		},
+
+		_toggleShareDetails: function(event) {
+			var $li = $(event.target).closest('li');
+			var shareId = $li.data('share-id');
+
+			if (!_.isUndefined(this._currentlyToggled[shareId])) {
+				this._currentlyToggled.splice(shareId, 1);
```
Comment (PVince81) [inline core/js/sharedialogshareelistview.js]: if `_currentlyToggled` is meant to be used as a hash array (aka object), use `delete(this._currentlyToggled[shareId])` to delete the key.

I'm a bit surprised the current approach even worked

File: core/js/sharedialogshareelistview.js [hunk 12]
```diff
@@ -431,25 +450,50 @@
...
+			} else {
+				this._currentlyToggled[shareId] = true;
+				this._toggleShareDivs(shareId, true);
+			}
+		},
+
+		_toggleShareDivs: function(shareId, enabled) {
+			var $li = this.$el.find('li[data-share-id=' + shareId + ']');
+			$li.children("div").each(function()
+			{
```
Comment (PVince81) [inline core/js/sharedialogshareelistview.js]: move this to the previous line

File: core/js/sharedialogshareelistview.js [hunk 13]
```diff
@@ -431,25 +450,50 @@
...
+				this._currentlyToggled.splice(shareId, 1);
+				this._toggleShareDivs(shareId, false);
+			} else {
+				this._currentlyToggled[shareId] = true;
+				this._toggleShareDivs(shareId, true);
+			}
+		},
+
+		_toggleShareDivs: function(shareId, enabled) {
+			var $li = this.$el.find('li[data-share-id=' + shareId + ']');
```
Comment (PVince81) [inline core/js/sharedialogshareelistview.js]: this is fine for integer share ids. normally you should use `.filterAttr('data-share-id', shareId)` for proper escaping

File: core/js/tests/specs/sharedialogshareelistview.js [hunk 14]
```diff
@@ -126,7 +126,31 @@ describe('OC.Share.ShareDialogShareeListView', function () {
...
+				}]
+			);
+
+			listView.render();
+
+			var $li = listView.$el.find('li[data-share-id=100]');
+
+			var $editCheckbox = $li.find("input[name='edit']");
+			expect($editCheckbox.is(':checked')).toEqual(true);
+			expect($editCheckbox.parent().attr('class')).toEqual('shareOption');
```
Comment (PVince81) [inline core/js/tests/specs/sharedialogshareelistview.js]: use `.hasClass()` in case other classes would be set there

File: core/js/tests/specs/sharedialogshareelistview.js [hunk 15]
```diff
@@ -126,7 +126,31 @@ describe('OC.Share.ShareDialogShareeListView', function () {
...
+			expect($editCheckbox.parent().parent().is('div')).toEqual(true);
+			expect($editCheckbox.parent().parent().parent().is('li')).toEqual(true);
```
Comment (PVince81) [inline core/js/tests/specs/sharedialogshareelistview.js]: not sure why asserting this is useful, especially when tied that closely to a precise DOM structure ?

**Review by PVince81 — COMMENTED** [review]
See comments

**Comment by PVince81** [comment]
mostly minor comments, most critical is likely https://github.com/owncloud/core/pull/36766/files/2df82086ff878d95a8ec1e05fdf77cc20fb9a1a4#diff-e8d8565fb4fcb24d2ff551b5e127cf6a

**Comment by phil-davis** [comment]
> @mrow4a Please create a changelog item [#36766 (comment)](https://github.com/owncloud/core/pull/36766#issuecomment-574450660)

@micbar do we need to add changelog items for bugfixes to features that were never released yet?

There will already be a changelog for feature "user/group share expiration". This PR simply fixes that feature, before the feature ever got released.

**Comment by micbar** [comment]
> > @mrow4a Please create a changelog item [#36766 (comment)](https://github.com/owncloud/core/pull/36766#issuecomment-574450660)
> 
> @micbar do we need to add changelog items for bugfixes to features that were never released yet?
> 
> There will already be a changelog for feature "user/group share expiration". This PR simply fixes that feature, before the feature ever got released.

Good question, we need to consider that we released 10.4.0RC1 already and the PR will show up zj the detailed git compare list anyway.

I don't have a strong opinion on that, we could kind of merge it into the Original item by adding this pr link.

That seems like the best solution.
@mrow4a just add it to https://github.com/owncloud/core/blob/master/changelog/unreleased/36573

File: core/js/tests/specs/sharedialogshareelistview.js (hunk 15 above)
Comment (mrow4a) [reply core/js/tests/specs/sharedialogshareelistview.js]: @PVince81 because the regression was exactly introduced by moving around the div - if you move the div out it might affect the display off attributes in general

File: core/js/tests/specs/sharedialogshareelistview.js (hunk 14 above)
Comment (mrow4a) [reply core/js/tests/specs/sharedialogshareelistview.js]: I would prefer to assert on class attr explicitely. Just to avoid adding more classes there, and if they are added, one will know.

File: core/css/share.css (hunk 9 above)
Comment (mrow4a) [reply core/css/share.css]: @PVince81 this is a rollback to previous implementation https://github.com/owncloud/core/blob/v10.3.2/core/css/share.css#L151 . I wont change this in the scope of this PR.

File: core/js/sharedialogshareelistview.js (hunk 13 above)
Comment (mrow4a) [reply core/js/sharedialogshareelistview.js]: I would prefer to keep it like this for a moment.

File: core/js/sharedialogshareelistview.js (hunk 12 above)
Comment (mrow4a) [reply core/js/sharedialogshareelistview.js]: done

File: core/js/sharedialogshareelistview.js (hunk 10 above)
Comment (mrow4a) [reply core/js/sharedialogshareelistview.js]: thanks! I overlooked it!

File: core/js/sharedialogshareelistview.js (hunk 11 above)
Comment (mrow4a) [reply core/js/sharedialogshareelistview.js]: Yes, good point, overlooked.

**Comment by mrow4a** [comment]
@micbar @phil-davis @PVince81 adjusted to the review

**Comment by phil-davis** [comment]
I added a changelog for #36813 to the last commit.

**Review by phil-davis — COMMENTED** [review]
LGTM and tested manually.
I will think about how I can add some automated UI acceptance tests for the sharing with both user and group scenario. But that could be added later (does not have to hold up merging this PR).

@PVince81 please review the code again.

**Review by PVince81 — APPROVED** [review]
:+1: looks fine now, thanks for fixing

**Comment by phil-davis** [comment]
Issue to make generally better acceptance test coverage of these UI sharing permissions/expiration date for when there are multiple shares of the the same resource: #36818
