### PR TITLE
Fix links to settings admin panels in JS and PHP

### LINKED ISSUE #27251: Rescan integrity check link does not accomplish the scan of files
### Steps to reproduce

1. In your oC server, create some files that won't passed the integrity check (integrity check warning is shown)
2. As admin user go to settings-->admin--> General Menu
3. Click on Rescan…

### Expected behaviour

The scan should be accomplished

### Actual behaviour

The scan is not done and an exception is thrown in the logs

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:**

"version":"10.0.0.0"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```

{"reqId":"iBtVIcAM+vgiDRBL1iFP","remoteAddr":"82.159.139.58","app":"no app in context","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"settings_admin\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(339): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('settings_admin', Array, 1)\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/URLGenerator.php(74): OC\\\\Route\\\\Router->generate('settings_admin', Array)\\n#2 \\\/opt\\\/owncloud\\\/settings\\\/Controller\\\/CheckSetupController.php(261): OC\\\\URLGenerator->linkToRoute('settings_admin')\\n#3 [internal function]: OC\\\\Settings\\\\Controller\\\\CheckSetupController->rescanFailedIntegrityCheck()\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\CheckSetupController), 'rescanFailedInt...')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\CheckSetupController), 'rescanFailedInt...')\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('CheckSetupContr...', 'rescanFailedInt...', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/base.php(898): OC\\\\Route\\\\Router->match('\\\/settings\\\/integ...')\\n#11 \\\/opt\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","level":3,"time":"2017-02-24T14:03:17+00:00","method":"GET","url":"\/index.php\/settings\/integrity\/rescan?requesttoken=LGpeLwgiQVQEMix4Ij0FWG1TORcUPwYYK1pUAwVldwM%3D%3Ag2mZmTtb5PV3uSi%2F91aPajAncm0dKU5zFRzc5gXKzRs%3D","user":"admin"}
```

### Client configuration

**browser**

 Mozilla
screen shot 2017-02-24 at 14 56 58

@tomneedham

### PR DESCRIPTION
**Pull request by tomneedham**
## Description
Fixes several calls to linkToRoute which still use the old `settings_admin` named route. Instead, they now call `SettingsPage#getAdmin` with the correct additional parameters to ensure users arrive at the correct location.

## Related Issue
Fixes https://github.com/owncloud/core/issues/27251

## Motivation and Context
Links pointing the user to settings pages will currently receive errors if the url generation is not updated.

## How Has This Been Tested?
Updated tests + tested in UI.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@tomneedham please remove the submodule to user_ldap - THX

File: apps/updatenotification/lib/Notification/BackgroundJob.php [hunk 1]
```diff
@@ -96,7 +96,7 @@ protected function checkCoreUpdate() {
 
 		$status = $updater->check();
 		if (isset($status['version'])) {
-			$url = $this->urlGenerator->linkToRouteAbsolute('settings_admin') . '#updater';
+			$url = $this->urlGenerator->linkToRouteAbsolute('SettingsPage#getAdmin') . '#updater';
```
Comment (PVince81) [inline apps/updatenotification/lib/Notification/BackgroundJob.php]: I hacked the updater to call this method and it doesn't work:
```
\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"SettingsPage#getAdmin\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(339): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('SettingsPage#ge...', Array, 1)\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/URLGenerator.php(77): OC\\\\Route\\\\Router->generate('SettingsPage#ge...', Array)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/URLGenerator.php(90): OC\\\\URLGenerator->linkToRoute('SettingsPage#ge...', Array)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/updatenotification\\\/lib\\\/Notification\\\/BackgroundJob.php(90): OC\\\\URLGenerator->linkToRouteAbsolute('SettingsPage#ge...')\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/updatenotification\\\/lib\\\/Notification\\\/BackgroundJob.php(83): OCA\\\\UpdateNotification\\\\Notification\\\\BackgroundJob->checkCoreUpdate()\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(57): OCA\\\\UpdateNotification\\\\Notification\\\\BackgroundJob->run(NULL)\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/cron.php(121): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#8 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","level":3,"time":"2017-03-20T10:57:18+00:00","method":"--","url":"--","user":"--"}
{"reqId":"StnsT+RgJupzdEvXqp9+","remoteAddr":"","app":"PHP","message":"Uninitialized string offset: 0 at \/srv\/www\/htdocs\/owncloud\/lib\/private\/URLGenerator.php#224","level":3,"time":"2017-03-20T10:57:18+00:00","method":"--","url":"--","user":"--"}
```

Also it seems that calling this settings route from an app doesn't work either: https://github.com/owncloud/customgroups/pull/28/files#diff-c8d4be5ecbca729f531c7848b5157a87R266

I'm getting the same error there, that's why I looked at how you did it here...

**Comment by tomneedham** [comment]
Rebased

**Comment by tomneedham** [comment]
failing tests seem unrelated?

**Comment by PVince81** [comment]
:+1:

Weird failures indeed...

**Comment by PVince81** [comment]
Rebased to try more CI luck

**Comment by tomneedham** [comment]
🎉
