### PR TITLE
Decouple change email from 'allow_user_to_change_display_name' setting

### LINKED ISSUE #35103: Can´t change email address
### Steps to reproduce
1. Login as normal user (no admin and no groupadmin)
2. open the personal setting page
3. 

### Expected behaviour
Tell us what should happen
I can´t change my display name, but I can change my email address.

### Actual behaviour
Tell us what happens instead
I can´t change my display name and my email address.

### Server configuration
**Operating system**:

**Web server:**
Server version: Apache/2.4.25 (Raspbian)
**Database:**

**PHP version:**
PHP 7.0.33-0+deb9u3
**ownCloud version:** (see ownCloud admin page)
10.0.10
**Updated from an older ownCloud or fresh install:**
updated
**Where did you install ownCloud from:**
tarball
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocoq89hwbqzx",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nas",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/media\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***\/owncloud",
        "htaccess.RewriteBase": "\/owncloud",
        "dbtype": "mysql",
        "version": "10.0.10.4",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "mail_smtpmode": "smtp",
        "default_language": "de",
        "trashbin_retention_obligation": "auto, 30",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "loglevel": 2,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "defaultapp": "files",
        "overwriteprotocol": "https",
        "updatechecker": false,
        "blacklisted_files": [
            ".htaccess"
        ],
        "enable_avatars": true,
        "asset-pipeline.enabled": true,
        "activity_expire_days": 365,
        "quota_include_external_storage": false,
        "versions_retention_obligation": "auto, 7",
        "allow_user_to_change_display_name": false,
        "knowledgebaseenabled": false,
        "session_lifetime": 86400,
        "check_for_working_htaccess": true,
        "maintenance": false,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "log_rotate_size": 104857600,
        "session_keepalive": true,
        "mail_smtpsecure": "ssl",
        "mail_smtpdebug": true,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "integrity.ignore.missing.app.signature": [
            "theme-***REMOVED SENSITIVE VALUE***"
        ]
    }
}
```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
Bugfix: Decouple change email from 'allow_user_to_change_display_name' setting

Before this change, with setting 'allow_user_to_change_display_name' false,
the user was not able to change the mail address in Settings->Personal->General
via the webUI.

With this change, the setting 'allow_user_to_change_mail_address' has been
introduced and change mail address has been decoupled from  setting
`allow_user_to_change_display_name`.

'allow_user_to_change_mail_address' must be set explicitly to false, to take effect.

## Related Issue

- Fixes #35103

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [x] Documentation ticket raised: https://github.com/owncloud/docs/issues/4087
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by JanAckermann** [comment]
NOTE: After PR gets merged, create doc issue for run config-to-docs 
FYI @mmattel

**Comment by JanAckermann** [comment]
FYI @pmaier1

File: settings/templates/panels/personal/profile.php [hunk 1]
```diff
@@ -59,7 +59,7 @@
 ?>
 
 <?php
-if ($_['displayNameChangeSupported']) {
+if ($_['mailAddressChangeSupported']) {
 	?>
 <form id="lostpassword" class="section" autocapitalize="none">
```
Comment (phil-davis) [inline settings/templates/panels/personal/profile.php:64]: A different issue to this PR - why is the id `lostpassword` ?

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiAuthOcs-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32668/47/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUITags-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32668/146/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIWebdavLockProt-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32668/149/1

File: settings/templates/panels/personal/profile.php (hunk 1 above)
Comment (JanAckermann) [reply settings/templates/panels/personal/profile.php]: :face_with_head_bandage: fixed that

**Comment by JanAckermann** [comment]
Fixed unit tests, IHMO they were already pretty useful, just chasing the wrong config var, so I don't think we need to add more.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/32673/10/7
```
There was 1 failure:

1) Tests\Settings\Panels\Personal\ProfileTest::testGetPanel
OCP\IUserSession::getUser() was not expected to be called more than 7 times.

/drone/src/settings/Panels/Personal/Profile.php:106
/drone/src/tests/Settings/Panels/Personal/ProfileTest.php:69
```

**Comment by JanAckermann** [comment]
Thx, yes saw that, will fix it as soon as I am back on a pc

**Comment by JanAckermann** [comment]
We might need to implement a backend action, still trying to figure out what they are for

**Comment by jvillafanez** [comment]
Do we need / want a migration? If the displayname setting was false, I guess we'd want the email setting to be also false.

**Comment by JanAckermann** [comment]
@jvillafanez I don't know @pmaier1 needs to decide

**Comment by phil-davis** [comment]
> If the displayname setting was false, I guess we'd want the email setting to be also false.

IMO this was a genuine unexpected bug, not an accidental feature. We should just document in the release notes so that installations can decide what they want.

But @pmaier1 will decide.

**Comment by phil-davis** [comment]
I push 2 acceptance test scenarios.

I  don't see where we currently test either of these config options at the API level.

File: tests/Settings/Controller/UsersControllerTest.php [hunk 2]
```diff
@@ -2011,10 +2011,10 @@ public function setEmailAddressData() {
 	 * @param string $mailAddress
 	 * @param bool $isValid
 	 * @param bool $expectsUpdate
-	 * @param bool $canChangeDisplayName
+	 * @param bool $chanChangeMailAddress
 	 * @param bool $responseCode
 	 */
-	public function testSetEmailAddress($mailAddress, $isValid, $expectsUpdate, $canChangeDisplayName, $responseCode) {
+	public function testSetEmailAddress($mailAddress, $isValid, $expectsUpdate, $chanChangeMailAddress, $responseCode) {
```
Comment (JanAckermann) [inline tests/Settings/Controller/UsersControllerTest.php:2017]: @phil-davis API Level testing should be here

**Comment by JanAckermann** [comment]
@michaelstingl Do we need to add this to the capabilities API or so ?

**Comment by michaelstingl** [comment]
> @michaelstingl Do we need to add this to the capabilities API or so ?

Not a feature in desktop or mobile apps, but maybe needed for new web UI? /cc @kulmann

**Comment by kulmann** [comment]
No plans so far to allow changing profile information in the new web ui. Thanks for the ping @JanAckermann @michaelstingl

**Comment by JanAckermann** [comment]
Nice, so the last item on this PR: @pmaier1 needs to decide if we need migrations

**Comment by pmaier1** [comment]
> Nice, so the last item on this PR: @pmaier1 needs to decide if we need migrations

For existing installations the behavior should not change after upgrading. Please also check whether documentation needs to be updated.

**Comment by JanAckermann** [comment]
@pmaier1 Documentation is covered after command `config to docs`  has been run in docs repo

File: core/Migrations/Version20210928123126.php [hunk 3]
```diff
@@ -0,0 +1,25 @@
+<?php
+namespace OC\Migrations;
+
+use OCP\Migration\ISimpleMigration;
+use OCP\Migration\IOutput;
+
+/**
+ * Set allow_user_to_change_mail_address to false as
+ * allow_user_to_change_display_name was explicit set to false
```
Comment (phil-davis) [inline core/Migrations/Version20210928123126.php:9]:
```suggestion
 * allow_user_to_change_display_name was explicitly set to false
```

File: core/Migrations/Version20210928123126.php [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+ */
+class Version20210928123126 implements ISimpleMigration {
+
+	/**
+	 * @param IOutput $out
+	 */
+	public function run(IOutput $out) {
+		if (\OC::$server->getSystemConfig()->getValue('allow_user_to_change_display_name') !== false) {
+			// Do nothing as allow_user_to_change_display_name has not explicit disabled
```
Comment (phil-davis) [inline core/Migrations/Version20210928123126.php:18]:
```suggestion
			// Do nothing as allow_user_to_change_display_name was not explicitly disabled
```

File: settings/css/settings.css [hunk 5]
```diff
@@ -51,6 +51,7 @@ input#webdav {
 #groups,
 #language,
 #lostpassword,
```
Comment (phil-davis) [inline settings/css/settings.css:53]: Is this used anywhere?
(it got renamed in https://github.com/owncloud/core/pull/39288/files#diff-34464ca7e7b32c684858ebb2a4837f83d2aadbed195cadf608ee2fd62648cf1d )

File: tests/lib/User/DeletedUserTest.php [hunk 6]
```diff
@@ -137,6 +137,10 @@ public function testCanChangeDisplayName() {
 		$this->assertFalse($this->deletedUser->canChangeDisplayName());
 	}
 
+	public function testCanMailAddressName() {
```
Comment (phil-davis) [inline tests/lib/User/DeletedUserTest.php:140]:
```suggestion
	public function testCanChangeMailAddress() {
```

The function name seemed a bit scrambled.

File: core/Migrations/Version20210928123126.php [hunk 7]
```diff
@@ -0,0 +1,25 @@
...
+ * Set allow_user_to_change_mail_address to false as
+ * allow_user_to_change_display_name was explicit set to false
+ */
+class Version20210928123126 implements ISimpleMigration {
+
+	/**
+	 * @param IOutput $out
+	 */
+	public function run(IOutput $out) {
+		if (\OC::$server->getSystemConfig()->getValue('allow_user_to_change_display_name') !== false) {
```
Comment (jvillafanez) [inline core/Migrations/Version20210928123126.php:17]: What about something like:
```
$value = \OC::$server->getSystemConfig()->getValue('allow_user_to_change_display_name');
if ($value !== null) {
  \OC::$server->getSystemConfig()->setValue('allow_user_to_change_mail_address', $value);
}
```

In addition, I'm not sure if the dependency injection works in the migrations, but we should use it if possible.

File: config/config.sample.php [hunk 8]
```diff
@@ -205,6 +205,13 @@
  */
 'allow_user_to_change_display_name' => true,
 
+/**
+ * Allow or disallow users to change their email addresses
```
[the remark this answers is not in the document]
Comment (JanAckermann) [reply config/config.sample.php:209]: Please contribute

File: settings/css/settings.css (hunk 5 above)
Comment (JanAckermann) [reply settings/css/settings.css:53]: seems it not get used elsewhere, so I'll remove it

File: core/Migrations/Version20210928123126.php (hunk 7 above)
Comment (JanAckermann) [reply core/Migrations/Version20210928123126.php:17]: Commited your suggestion, DI does not work

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiComments-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32725/50/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProvisioningGroups-v2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32725/56/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProvisioningGroups-v1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32725/55/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareUpdateToRoot-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32725/78/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareReshareToRoot3-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32725/76/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-5-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32725/169/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiSharePublicLink1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32725/70/1

**Comment by phil-davis** [comment]
What happened to the latest CI  run?
https://drone.owncloud.com/owncloud/core/32739 looks like it was cancelled.

**Review by jvillafanez — APPROVED** [review]
