### PR TITLE
Fix getItemSharedWithUser for groups

### LINKED ISSUE #12475: Resharing via Link appears to be broken after Update to 7.0.3
### Steps to reproduce
1.Share a File that has been shared with you via link
2. Try to Open the Link

### Expected behaviour
Link should open the Download Page for the shared file

### Actual behaviour
Link leads to a error message saying this link does not exist

### Server configuration
**Operating system**: 

Debian 7

**Web server:** 

Apache2

**Database:** 

MariaDB 10.0

**PHP version:** 

5.4.35

**ownCloud version:** 

7.0.3

**Updated from an older ownCloud or fresh install:** 

Updated from 7.0.2

**List of activated apps:** 

Activity, Delete Files, Documents, First Run Wizard, Full Text Search, PDF Viewer, Share Files, Text Editor, Updater, Files Move

**Are you using external storage, if yes which one:**

  No

**Are you using encryption:**

 No

### Client configuration
**Browser:** 

Firefox

**Operating system:**

 Windows 7

#### Web server error log 

Nothing

#### ownCloud log (data/owncloud.log)

{"reqId":"547739393b36c","app":"share","message":"could not resolve linkItem","level":0,"time":"2014-11-27T14:46:17+00:00","method":"GET","url":"\/public.php?service=files&t=

If that Helps: I'm forcing the use of a Password and expiry Date for Link sharing.

I hope that has not been reported yet.

### PR DESCRIPTION
**Pull request by PVince81**
Fixed SQL query for whenever a user has more than one group.
Added missing $owner where clause for group lookup.
Added unit tests for the group cases.

Fixes https://github.com/owncloud/core/issues/12475

Please review @icewind1991 @schiesbn @LukasReschke @MorrisJobke @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
To test, use these steps: https://github.com/owncloud/core/issues/13361#issuecomment-70136056

Also fixes https://github.com/owncloud/core/issues/13361

**Comment by PVince81** [comment]
@karlitschek backport to stable7 would be good, at least 4 cases were observed there here: https://github.com/owncloud/core/issues/12475

File: lib/private/share/share.php [hunk 1]
```diff
@@ -337,17 +337,26 @@ public static function getItemSharedWithUser($itemType, $itemSource, $user, $own
...
 
-			$query = \OC_DB::prepare(
-				'SELECT *
-						FROM
-						`*PREFIX*share`
-						WHERE
-						`' . $column . '` = ? AND `item_type` = ? AND `share_with` in (?)'
+			$where = 'WHERE `' . $column . '` = ? AND `item_type` = ? AND `share_with` in (?)';
+			$arguments = array($itemSource, $itemType, $groups);
+			$types = array(null, null, \Doctrine\DBAL\Connection::PARAM_STR_ARRAY);
```
Comment (MorrisJobke) [inline lib/private/share/share.php]: Nice :) Didn't know of that one. You can pass in an array and it will resolve one `?`with all group elements? :rocket: science ;)

**Comment by karlitschek** [comment]
@PVince81 agreed. Please backport :-)

**Comment by LukasReschke** [comment]
Confirmed to work by @GreenArchon in https://github.com/owncloud/core/issues/12475#issuecomment-70330817

**Comment by LukasReschke** [comment]
:+1: – would love getting some feedback from others more familiar with the sharing code before merging though.

**Comment by MorrisJobke** [comment]
I followed the steps but updated from 7.0.2 to this branch. I got following: 
reshare

Is this intended?

**Comment by PVince81** [comment]
Yes. In the absence of child entry it will set the "parent" field to the group share instead.
For now this is intended. We can look into making it auto-create the child entry later (but I'll need help from @schiesbn for that).

**Comment by PVince81** [comment]
@schiesbn can you review this ?

**Comment by MorrisJobke** [comment]
@PVince81 Then you get the :+1: from me. Because everything else works. u3 has the share and can work with it.

**Comment by MorrisJobke** [comment]
@PVince81 Please backport ;)

**Comment by PVince81** [comment]
I'm on it. There are conflicts, so I'll submit a PR for the backport.

**Comment by PVince81** [comment]
There are complications during the backport, needs an additional fix: https://github.com/owncloud/core/pull/13463

**Comment by PVince81** [comment]
Backport to stable7 is in this PR: https://github.com/owncloud/core/pull/13470
It also includes the fix from https://github.com/owncloud/core/pull/13463
