### PR TITLE
Bugfix/30078

### LINKED ISSUE #30078: Malformed vCard downloads trough the new webDAV endpoint result in a server error
Note that contact app is not even enabled.

### Steps to reproduce
1. Create an empty `.vcf` file (`touch test.vcf`)
2. Upload to ownCloud with the webUI
3. Connect a Desktop Client > 2.3.0 (since it uses the new WebDAV endpoint: https://github.com/owncloud/client/issues/4007)

### Expected behavior
The file gets downloaded regardless of its contents. Like it gets uploaded in step no.2 (old endpoint)

### Actual behavior
`GET`-ing a file trough the new endpoint is somehow triggering the CardDAV plugin which checks if the `.vcf` file is well-formed/contains errors **and returns an error 500 in that case.** (which propagates to the client)

Upload from the new endpoint is working though.

#### Web server error log
```
172.17.0.1 - - [09/Jan/2018:16:14:07 +0000] "PUT /remote.php/webdav/test.vcf HTTP/1.1" 201 728 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0"
[...]
172.17.0.1 - admin [09/Jan/2018:16:14:14 +0000] "GET /remote.php/dav/files/admin/test.vcf HTTP/1.1" 500 1070 "-" "Mozilla/5.0 (Macintosh) mirall/2.4.0 (build 8801)"
```

#### ownCloud log (data/owncloud.log)

```
{
   "reqId":"cf09c5f5-33d3-4d08-97ce-4adf7515f675",
   "level":4,
   "time":"2018-01-09T16:14:14+00:00",
   "remoteAddr":"172.17.0.1",
   "user":"admin",
   "app":"webdav",
   "method":"GET",
   "url":"/remote.php/dav/files/admin/test.vcf",
   "message":"Exception: 
    {
        "Message":"End of document reached prematurely","Exception":"Sabre\VObject\EofException","Code":0,"Trace":"#0 /var/www/owncloud/lib/composer/sabre/vobject/lib/Parser/MimeDir.php(150): Sabre\VObject\Parser\MimeDir->readLine()
        #1 /var/www/owncloud/lib/composer/sabre/vobject/lib/Parser/MimeDir.php(89): Sabre\VObject\Parser\MimeDir->parseDocument()
        #2 /var/www/owncloud/lib/composer/sabre/vobject/lib/Reader.php(46): Sabre\VObject\Parser\MimeDir->parse('', 0)
        #3 /var/www/owncloud/lib/composer/sabre/dav/lib/CardDAV/Plugin.php(857): Sabre\VObject\Reader::read('')
        #4 /var/www/owncloud/lib/composer/sabre/dav/lib/CardDAV/Plugin.php(782): Sabre\CardDAV\Plugin->convertVCard('', 'vcard3')
        #5 [internal function]: Sabre\CardDAV\Plugin->httpAfterGet(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
        #6 /var/www/owncloud/lib/composer/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
        #7 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(491): Sabre\Event\EventEmitter->emit('afterMethod:GET', Array)
        #8 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
        #9 /var/www/owncloud/apps/dav/lib/Server.php(256): Sabre\DAV\Server->exec()
        #10 /var/www/owncloud/apps/dav/appinfo/v2/remote.php(31): OCA\DAV\Server->exec()
        #11 /var/www/owncloud/remote.php(165): require_once('/var/www/ownclo...')
        #12 {main}","File":"/var/www/owncloud/lib/composer/sabre/vobject/lib/Parser/MimeDir.php","Line":296,"User":"admin"
    }"
}
```

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Outside of the CardDAV collection we shall not change the file content.

In addition:
 - also only load calendar plugins when inside the calendar collection
 - fix avatar output - jpg was putput for png as well

## Related Issue
fixes #30078 

## How Has This Been Tested?
- manual testing
- unit tests added for avatar

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: apps/dav/lib/Server.php [hunk 1]
```diff
@@ -117,7 +125,7 @@ public function __construct(IRequest $request, $baseUri) {
 		// with performance and locking issues because it will query
 		// every parent node which might trigger an implicit rescan in the
 		// case of external storages with update detection
-		if (strpos($this->server->getRequestUri(), 'files/') !== 0) {
+		if (!$this->requestIsForSubtree('files')) {
```
Comment (PVince81) [inline apps/dav/lib/Server.php]: I'd have gone with `isRequestForSubtree` as starting method name with `is` is some kind of convention.
Optional, up to you.

**Review by PVince81 — APPROVED** [review]
:+1: code looks good

**Comment by DeepDiver1975** [comment]
again mariadb timout - :godmode: :damn:
