### PR TITLE
Fix files_external:list --mount-options output

### LINKED ISSUE #36839: files_external:list options column does not display the current settings of the storage
### Steps to reproduce
1. as the admin, setup some local storage that provides files on the local server to the ownCloud users
2. set the storage settings option read-only (or change some other settings option from the defaults)
3. `files_external:list`
4. `files_external:list --mount-options`

### Expected behaviour
The read-only setting is mentioned in the `Options` column. (any options that are not set differently from the ssystem defaults should be reported)

The read-only setting is mentioned with value true (not false) in the `Options` column. (i.e. all options should be reported with their actual currently-set values)

### Actual behaviour
The options column is empty:
```
$ php occ files_external:list
+----------+-------------+---------+---------------------+------------------------------+---------+------------------+-------------------+
| Mount ID | Mount Point | Storage | Authentication Type | Configuration                | Options | Applicable Users | Applicable Groups |
+----------+-------------+---------+---------------------+------------------------------+---------+------------------+-------------------+
| 22       | /zzz        | Local   | None                | datadir: "\/home\/phil\/zzz" |         | All              |                   |
+----------+-------------+---------+---------------------+------------------------------+---------+------------------+-------------------+
```

The options column shows the system defaults, not the current settings:
```
$ php occ files_external:list --mount-options
+----------+-------------+---------+---------------------+------------------------------+------------------------------------------------------------------------------------------------------------------------------------+------------------+-------------------+
| Mount ID | Mount Point | Storage | Authentication Type | Configuration                | Options                                                                                                                            | Applicable Users | Applicable Groups |
+----------+-------------+---------+---------------------+------------------------------+------------------------------------------------------------------------------------------------------------------------------------+------------------+-------------------+
| 22       | /zzz        | Local   | None                | datadir: "\/home\/phil\/zzz" | encrypt: true, previews: true, filesystem_check_changes: 1, read_only: false, enable_sharing: false, encoding_compatibility: false | All              |                   |
+----------+-------------+---------+---------------------+------------------------------+------------------------------------------------------------------------------------------------------------------------------------+------------------+-------------------+

```

### Server configuration
current core master github

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Display the correct output in the Options column of `files_external:list` (with and without `--mount-options` )

The 1st commit adds acceptance tests that demonstrate the old (bad) behaviour.

The 2nd commit fixes the code, adds some unit tests (for more general unit test coverage of this code), adjusts the acceptance tests to demonstrate the new (correct) behaviour and adds a changelog entry.

## Related Issue
- Fixes #36839 

## How Has This Been Tested?
CI

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

File: apps/files_external/tests/Command/ListCommandTest.php [hunk 1]
```diff
@@ -169,4 +169,78 @@ public function testShortView($options, $expectedResult, $mountOptions) {
 			$this->assertEquals($expectedResult, $output);
 		}
 	}
+
+	public function providesLongView() {
```
Comment (phil-davis) [inline apps/files_external/tests/Command/ListCommandTest.php]: There was already unit tests for "shortView". I copied the "framework" of that and made these tests for the "longView". At least that will increase coverage a bit.

Of course there are a heap more unit test combinations that could be added here!

**Review by micbar — APPROVED** [review]
