### PR TITLE
Encryption - fix moving/copying files between storages

### LINKED ISSUE #15619: [enc2] Move file into share as owner doesn't create share keys
### Steps:
1. Enable encryption + default encryption module
2. Create two users "user1" and "user2"
3. Login as "user1"
4. Create a folder "test"
5. Share "test" with "user2" (the sharing happens first)
6. Create a local text file "test.txt" and put some contents in it
7. Move "test.txt" into "test"
8. Login as "user2"
9. Try opening or downloading "test.txt"

### Expected result
"test.txt" can be downloaded by "user2"

### Actual result
"test.txt" contains garbage when opened with the text editor (I'd expect it to throw an exception and not return anything at all if a key is missing!)

### Versions
ownCloud master (4f0437fbdef8e729167c1a8078e790c7983f69ef)

@schiesbn @th3fallen

### LINKED ISSUE #15963: Moving encrypted files to an external storage folder with encryption enabled decrypts them.
### Steps to reproduce
1. Enable encryption app.
2. In admin page enable encryption.
3. Relogin.
4. Upload some files. Be sure they are encrypted.
5. Mount an amazon S3 folder and be sure encryption is enabled on it (gear on the right).
6. Move one of those files into S3 folder.
7. Open file in S3 using some program for connect like cyberduck or others. 

### Expected behaviour
File is encrypted.

### Actual behaviour
File is not encrypted.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
8.1 alpha2

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes S3.

**Are you using encryption:** 
Yes.

**Logs**
```

```

### PR DESCRIPTION
**Pull request by schiessle**
Fix move/copy files between different storages.

fix https://github.com/owncloud/core/issues/15963 (see the issue for concrete steps to test it)

cc @PVince81 

Ignore the failing tests, Jenkins doesn't like this branch any more... passing tests are here: https://github.com/owncloud/core/pull/16046

### CODE REVIEW

File: lib/private/files/storage/wrapper/encryption.php [hunk 1]
```diff
@@ -300,6 +313,65 @@ public function fopen($path, $mode) {
...
+
+
+	/**
+	 * @param \OCP\Files\Storage $sourceStorage
+	 * @param string $sourceInternalPath
+	 * @param string $targetInternalPath
+	 * @param bool $preserveMtime
+	 * @return bool
+	 */
+	public function copyFromStorage(\OCP\Files\Storage $sourceStorage, $sourceInternalPath, $targetInternalPath, $preserveMtime = false) {
```
Comment (PVince81) [inline lib/private/files/storage/wrapper/encryption.php]: It seems that you rewrote your own copyFromStorage ?
Does this operate only on keys or on the real storage ?

CC @icewind1991

File: lib/private/encryption/update.php [hunk 2]
```diff
@@ -102,18 +102,30 @@ private function update($fileSource) {
...
-		if ($this->view->is_dir($absPath)) {
-			$allFiles = $this->util->getAllFiles($absPath, $mountPoint);
+		if ($this->view->is_dir($path)) {
+			$allFiles = $this->util->getAllFiles($path, $mountPoint);
 		} else {
-			$allFiles = array($absPath);
+			$allFiles = array($path);
 		}
 
 		$encryptionModule = $this->encryptionManager->getDefaultEncryptionModule();
```
Comment (nickvergessen) [inline lib/private/encryption/update.php]: get the module first, because we don't need to get any paths then?

File: lib/private/files/storage/wrapper/encryption.php [hunk 3]
```diff
@@ -191,6 +199,9 @@ public function rename($path1, $path2) {
 				$keyStorage = $this->getKeyStorage($encryptionModule->getId());
 				$keyStorage->renameKeys($source, $target);
 			}
+
+			// TODO is the mount point correct?
+			$this->update->update($target, $this->mountPoint);
```
Comment (nickvergessen) [inline lib/private/files/storage/wrapper/encryption.php]: update is optional in the constructor, so you'd need to check it here?
But why is it even optional?

Comment (schiesbn) [inline lib/private/files/storage/wrapper/encryption.php]: It will be always there. We just need to make it optional because the base clas doesn't know this parameters and PHP doesn't allow you to extend the constructor from the base class with mandatory parameters

File: lib/private/files/storage/wrapper/encryption.php (hunk 1 above)
Comment (schiesbn) [inline lib/private/files/storage/wrapper/encryption.php]: This operates on the real storage. We need this in order not to bypass the encryption wrapper for the target in line 355

Comment (PVince81) [inline lib/private/files/storage/wrapper/encryption.php]: We need to find a better way.
I'm worried not only about code duplication from https://github.com/owncloud/core/blob/master/lib/private/files/storage/common.php#L536 but also there's a risk that if someone fixes common.php, that this class here would be forgotten.

@icewind1991 can you advise on an alternative approach ?
We could move the copy logic into a separate utility method that can be called by both somehow ?

**Comment by PVince81** [comment]
- [ ] BUG: move file from non-encrypted ext storage to encrypted ext storage fails with WebDAV (works on master):
   1. Mount two SFTP storages, "/SFTP" and "/SFTP2"
   2. For "/SFTP2", disable encryption
   3. With cadaver, upload a picture to "/SFTP2"
   4. With cadaver, move the picture to "/SFTP"

Getting this:
```
{"reqId":"LLnalEMm4RCjGa9D12z9","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"path needs to be relative to the system wide data folder and point to a user specific file\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/encryption\\\/file.php(44): OC\\\\Encryption\\\\Util->getUidAndFilename('.')\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(239): OC\\\\Encryption\\\\File->getAccessList('.')\\n#2 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_open('ocencryption:\\\/\\\/', 'w', 0, NULL)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(178): fopen('ocencryption:\\\/\\\/', 'w', false, Resource id #437)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(160): OC\\\\Files\\\\Stream\\\\Encryption::wrapSource(Resource id #433, 'w', Resource id #437, 'ocencryption', 'OC\\\\\\\\Files\\\\\\\\Stream...')\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(308): OC\\\\Files\\\\Stream\\\\Encryption::wrap(Resource id #433, 'Huoguo.jpg', '\\\/root\\\/files\\\/SFT...', Array, 'root', Object(OCA\\\\Encryption\\\\Crypto\\\\Encryption), Object(OCA\\\\Files_Trashbin\\\\Storage), Object(OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption), Object(OC\\\\Encryption\\\\Util), Object(OC\\\\Encryption\\\\File), 'w', 0, 0)\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(355): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->fopen('Huoguo.jpg', 'w')\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(323): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->copyFromStorage(Object(OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption), 'Huoguo.jpg', 'Huoguo.jpg', true)\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(644): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->moveFromStorage(Object(OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption), 'Huoguo.jpg', 'Huoguo.jpg')\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/objecttree.php(222): OC\\\\Files\\\\View->rename('SFTP2\\\/Huoguo.jp...', 'SFTP\\\/Huoguo.jpg')\\n#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(630): OC\\\\Connector\\\\Sabre\\\\ObjectTree->move('SFTP2\\\/Huoguo.jp...', 'SFTP\\\/Huoguo.jpg')\\n#11 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#13 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#14 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#15 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#16 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(84): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#17 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/encryption\\\/util.php\",\"Line\":242}","level":4,"time":"2015-04-15T15:39:34+00:00","method":"MOVE","url":"\/owncloud\/remote.php\/webdav\/SFTP2\/Huoguo.jpg"}
```

**Comment by PVince81** [comment]
- [ ] BUG: can't upload file directly into "SFTP", also getting notification that says "path needs to be relative to the system wide data folder and point to a user specific file" (possibly related to the previous entry)

Note: here I setup my OC + keys using the enc2_migration branch, just to be sure.

**Comment by schiesbn** [comment]
@PVince81 did you also used this PR for testing: https://github.com/owncloud/core/pull/15616 ? This fixes are needed in order to work properly.

**Comment by PVince81** [comment]
I don't remember. Let's get https://github.com/owncloud/core/pull/15616 merged first then.

**Comment by PVince81** [comment]
https://github.com/owncloud/core/pull/15616 was just merged.

Please rebase to get the latest changes and get more accurate testing :smile:

**Comment by PVince81** [comment]
Well I'll do it myself then test this.

**Comment by PVince81** [comment]
Rebased

**Comment by PVince81** [comment]
- [x] move file in/out of a shared folder as recipient works now

The external storage bugs are not related to this PR, so I raised them here: https://github.com/owncloud/core/issues/15688

Please have a look at my comment regarding duplicate code before this can be merged.
Thanks.

File: lib/private/files/storage/wrapper/encryption.php (hunk 1 above)
Comment (schiesbn) [inline lib/private/files/storage/wrapper/encryption.php]: Maybe there is a way to call fopen here https://github.com/owncloud/core/blob/master/lib/private/files/storage/common.php#L548 in a way that it will go again through all wrappers? But I don't know how this could be done if you are already down at the storage level.

**Comment by PVince81** [comment]
Fixes https://github.com/owncloud/core/issues/15840

**Comment by nickvergessen** [comment]
Needs another loop of rebasing, sorry

**Comment by PVince81** [comment]
And we still have no good solution for the duplicate code :frowning: 
Looks like we'll have to keep it in short term and add a big fat TODO/WARNING in the code

**Comment by schiesbn** [comment]
I will rebase it once https://github.com/owncloud/core/pull/15839 was merged because there is some overlapping.

**Comment by PVince81** [comment]
@schiesbn please rebase :smile:

**Comment by schiesbn** [comment]
rebased

**Comment by schiesbn** [comment]
@PVince81 now it is no longer a 1:1 copy from the base storage. I changed the code to also adjust the "encrypted"-flag in the filecache entry if files gets moved between encrypted and un-encrypted storage. Otherwise a unencrypted file can be detected as a legacy encrypted file.

**Comment by schiesbn** [comment]
@owncloud-bot retest this please

File: lib/private/files/storage/wrapper/encryption.php [hunk 4]
```diff
@@ -357,6 +358,89 @@ public function fopen($path, $mode) {
...
 
 	/**
+	 * @param \OCP\Files\Storage $sourceStorage
+	 * @param string $sourceInternalPath
+	 * @param string $targetInternalPath
+	 * @param bool $preserveMtime
+	 * @return bool
+	 */
+	public function moveFromStorage(\OCP\Files\Storage $sourceStorage, $sourceInternalPath, $targetInternalPath, $preserveMtime = true) {
+		$result = $this->copyBetweenStorage($sourceStorage, $sourceInternalPath, $targetInternalPath, $preserveMtime, true);
```
Comment (PVince81) [inline lib/private/files/storage/wrapper/encryption.php]: The reason "moveFromStorage" was introduced was to be able to move files when needed (like this one 
Here, assuming that the encryption wrapper is always specified, it would cancel that effort by always doing a copy.
You probably copied this from https://github.com/owncloud/core/blob/master/lib/private/files/storage/common.php. But in many cases it's about the local storage, so the code would be https://github.com/owncloud/core/blob/master/lib/private/files/storage/local.php#L382

Would it possible to add a check "if encryption actually enabled", then do the special logic, else just call the underlying storage's "moveFromStorage" ?

File: lib/private/files/storage/wrapper/encryption.php [hunk 5]
```diff
@@ -357,6 +358,89 @@ public function fopen($path, $mode) {
...
+	 * copy file between two storages
+	 *
+	 * @param \OCP\Files\Storage $sourceStorage
+	 * @param $sourceInternalPath
+	 * @param $targetInternalPath
+	 * @param $preserveMtime
+	 * @param $isRename
+	 * @return bool
+	 */
+	private function copyBetweenStorage(\OCP\Files\Storage $sourceStorage, $sourceInternalPath, $targetInternalPath, $preserveMtime, $isRename) {
```
Comment (PVince81) [inline lib/private/files/storage/wrapper/encryption.php]: Did the duplicate code just move down and hid itself in this private method ? :wink:

Comment (schiesbn) [inline lib/private/files/storage/wrapper/encryption.php]: No it was also modified to update the file cache table to set the encryption flag to '1' or '2' when the file was moved to a encrypted/unencrypted storage

**Comment by schiesbn** [comment]
@owncloud-bot retest this please

**Comment by schiesbn** [comment]
@owncloud-bot retest this please

**Comment by schiesbn** [comment]
Seems like Jenkins don't want to test this branch any longer... I opened a new PR just for Jenkins: https://github.com/owncloud/core/pull/16046

**Comment by schiesbn** [comment]
Would be great to get this reviewed and merged... cc @th3fallen @nickvergessen @DeepDiver1975

File: lib/private/files/storage/wrapper/encryption.php [hunk 6]
```diff
@@ -61,19 +61,20 @@ class Encryption extends Wrapper {
...
-	 * @param \OCP\Encryption\IManager $encryptionManager
-	 * @param \OC\Encryption\Util $util
-	 * @param \OCP\ILogger $logger
-	 * @param \OCP\Encryption\IFile $fileHelper
-	 * @param string $uid user who perform the read/write operation (null for public access)
+	 * @param IManager $encryptionManager
+	 * @param Util $util
+	 * @param ILogger $logger
+	 * @param IFile $fileHelper
+	 * @param null $uid
```
Comment (nickvergessen) [inline lib/private/files/storage/wrapper/encryption.php]: wrong!

Comment (schiesbn) [inline lib/private/files/storage/wrapper/encryption.php]: fixed

**Comment by nickvergessen** [comment]
@owncloud-bot retest this please

**Comment by schiesbn** [comment]
@nickvergessen you can ignore the failing tests... passing tests are here https://github.com/owncloud/core/pull/16046

**Comment by schiesbn** [comment]
rebased to resolve merge conflicts

**Comment by nickvergessen** [comment]
tested and still works as expected :+1: 
additionally I fixed a little doc block

**Comment by nickvergessen** [comment]
rebased again

**Comment by SergioBertolinSG** [comment]
:+1:  Working fine, tested with SFTP external storage and shared folder (in same OC server)
