### PR TITLE
Check if the key exists, before trying to delete it

### LINKED ISSUE #279: Travis fails because of new encryption app
We disabled the old one on running tests, need to fix the name

### PR DESCRIPTION
**Pull request by nickvergessen**
Currently the activity tests fail, because they delete a user for whome the filesystem was never set up.

```
1) OCA\Activity\Tests\ApiTest::testGet with data set #2 ('activity-api-user1', 0, 1, array(array('link', 'file', null, null, '', 'Subject2 @User #A/B.txt')))
filemtime(): stat failed for /home/travis/build/owncloud/core/data-autotest/activity-api-user1/files_encryption/OC_DEFAULT_MODULE
/home/travis/build/owncloud/core/lib/private/files/storage/local.php:165
/home/travis/build/owncloud/core/lib/private/files/storage/wrapper/wrapper.php:220
/home/travis/build/owncloud/core/lib/private/files/cache/updater.php:186
/home/travis/build/owncloud/core/lib/private/files/cache/updater.php:120
/home/travis/build/owncloud/core/lib/private/files/view.php:989
/home/travis/build/owncloud/core/lib/private/files/view.php:567
/home/travis/build/owncloud/core/lib/private/encryption/keys/storage.php:147
/home/travis/build/owncloud/core/apps/encryption/lib/keymanager.php:456
/home/travis/build/owncloud/core/apps/encryption/hooks/userhooks.php:187
/home/travis/build/owncloud/core/lib/private/hook.php:103
/home/travis/build/owncloud/core/lib/private/server.php:157
/home/travis/build/owncloud/core/lib/private/hooks/basicemitter.php:99
/home/travis/build/owncloud/core/lib/private/hooks/publicemitter.php:32
/home/travis/build/owncloud/core/lib/private/user/user.php:197
/home/travis/build/owncloud/core/lib/private/user.php:224
/home/travis/build/owncloud/core/apps/activity/tests/apitest.php:85
```

Fix owncloud/activity#279

Please review @DeepDiver1975 @schiesbn @th3fallen

### CODE REVIEW

File: lib/private/encryption/keys/storage.php [hunk 1]
```diff
@@ -140,11 +140,11 @@ public function setSystemUserKey($keyId, $key) {
 	 * @param string $uid ID if the user for whom we want to delete the key
 	 * @param string $keyId id of the key
 	 *
-	 * @return boolean
+	 * @return boolean False when the key could not be deleted
 	 */
 	public function deleteUserKey($uid, $keyId) {
 		$path = $this->constructUserKeyPath($keyId, $uid);
-		return $this->view->unlink($path);
+		return !$this->view->file_exists($path) || $this->view->unlink($path);
```
Comment (PVince81) [inline lib/private/encryption/keys/storage.php]: or `$this->view->file_exists($path) && $this->view->unlink($path)` :smile: 

Doesn't `unlink()` simply return false when it couldn't delete in case of non-existence, which removes the need for a prior check ?

I don't mind the fix though, at least it is more explicit.

Comment (nickvergessen) [inline lib/private/encryption/keys/storage.php]: > Doesn't unlink() simply return false when it couldn't delete in case of non-existence, which removes the need for a prior check ?

Apparently it doesn't otherwise the activity tests wouldn't fail?

`$this->view->file_exists($path) && $this->view->unlink($path)` changes the return value from true to false, when the key did not exist. so It wouldn't match the docs anymore.

Comment (PVince81) [inline lib/private/encryption/keys/storage.php]: Ah, I see.

Maybe the tests fail because we returned the value of `unlink()` even when false.
Another idea would be to ignore the return value of `unlink()` and assume that the deletion worked even if it returns false (in case it didn't exist). However this doesn't account for other possible errors.

So your fix is good.

**Comment by schiesbn** [comment]
as discussed :+1:

**Comment by DeepDiver1975** [comment]
:+1:
