### PR TITLE
Restore DB connection after failure

### LINKED ISSUE #21315: Unit test without database cannot properly throw errors
### Steps
1. Create a unit test that extends from "TestCase"
1. Do not enable database access
1. Create a test that does a failed assertion: `$this->assertTrue(false);`

### Expected result
Error displayed properly in console

### Actual result
No error, but console shows "Your test case is not allowed to access the database."

This makes it very hard to debug errors in tests while developing them.

This is because while we forbid database usage in `TestCase`, we still need it in `tearDownAfterClass`.
In a regular run, it will call `tearDown` first which will restore the database connection.
However in an error case, it will skip `tearDown`...

I'll provide a quickfix for this.
This is with PHPUnit 4.4.4

@DeepDiver1975 FYI

### PR DESCRIPTION
**Pull request by PVince81**
In case of failure, PHPUnit seems to skip `tearDown`, so any useful
assertion messages cannot be shown because `tearDownAfterClass` is
throwing an error because of database usage.

This commit makes sure we also restore the database in
`tearDownAfterClass` to prevent the data root restoration to fail

Fixes https://github.com/owncloud/core/issues/21315

Note: haven't run the full suite locally, let's see what Jenkins says.

### CODE REVIEW

File: tests/lib/testcase.php [hunk 1]
```diff
@@ -33,7 +33,8 @@
 	private $commandBus;
 
 	/** @var IDBConnection */
-	static private $realDatabase;
+	static protected $realDatabase = null;
```
Comment (PVince81) [inline tests/lib/testcase.php]: I need to make it protected, else the closure at line 165 cannot access it...

**Comment by DeepDiver1975** [comment]
:+1:
