### PR TITLE
Fix new DAV quota check target path

### LINKED ISSUE #28159: Quota check for shared storage doesn't kick in for received shares in new DAV endpoint
### Steps

1. Create two users "user1" and "user2"
1. Set quota of "user1" to unlimited
1. Set quota of "user2" to 2 MB
1. Login as "user2"
1. Create a folder "shared_by_user2"
1. Share it with "user1"
1. Login as "user1"
1. Start cadaver using the **new** dav endpoint: "remote.php/dav/files/user1"
1. Upload a 10+ MB file into the root
1. Upload a 10+ MB file into the received folder "shared_by_user2"

### Expected result
Upload works into the root.
Upload fails into the received folder due to quota.

### Actual result
Upload works in both cases. The quota check doesn't kick in for mounted shared folders.

### Versions
Observed in 10.0.2 using the desktop client 2.3.2.
Reported as regression here https://github.com/owncloud/core/issues/14600#issuecomment-309518329

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Fixes the following:
- use correct actual path in `QuotaPlugin` when coming from the new DAV endpoint
- add quota check when moving FutureFile using chunked upload to new DAV endpoint

Also adds quota test hypercube to make sure we didn't forget anything, from https://github.com/owncloud/QA/issues/461

## Related Issue
Fixes https://github.com/owncloud/core/issues/28159
Fixes https://github.com/owncloud/QA/issues/461

## Motivation and Context
One **must not** be able to bypass quotas

## How Has This Been Tested?
Automated tests.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## TODO:
- [x] integration tests (test first!)
- [ ] the actual fix

cc @SergioBertolinSG

### CODE REVIEW

**Review by SergioBertolinSG — APPROVED** [review]

**Comment by PVince81** [comment]
@SergioBertolinSG it's too early for review but thanks for confirming the two cases I added.

**Comment by PVince81** [comment]
I'm done, please review:

@SergioBertolinSG please review my test changes and additions.

@DeepDiver1975 please review the QuotaPlugin additions which are related to new dav. I know they're not ideal but I'm aiming for a backportable fix here. (we could use `getNodeForPath` for a cleaner fix)

**Comment by PVince81** [comment]
I'll address the failing unit tests

**Comment by PVince81** [comment]
@SergioBertolinSG I have now added overwrite upload test cases for everything to make sure all is covered.

Now QuotaPlugin was switched to always use `getNodeForPath` instead of using path trickery. The automated tests confirm that it still works.

@DeepDiver1975 @jvillafanez please review

**Comment by PVince81** [comment]
Rebased to restart unstable CI env

**Comment by SergioBertolinSG** [comment]
:+1: for the integration tests part.

**Comment by PVince81** [comment]
rebased due to Jenkins' sudden death

**Comment by PVince81** [comment]
Aha, finally a legit failure:
```
23:20:56     /var/lib/jenkins/workspace/owncloud-core_core_PR-28160-GE6VZMPMYVCIQXV7U5Z2R262UNHGEWXD3YK3XVDVFGZDMDFAFJXQ/tests/integration/features/checksums.feature:145
```

File: tests/integration/features/bootstrap/WebDav.php [hunk 1]
```diff
@@ -742,7 +897,7 @@ public function userMovesNewChunkFileWithIdToMychunkedfile($user, $id, $dest)
 	{
 		$source = '/uploads/' . $user . '/' . $id . '/.file';
 		$destination = substr($this->baseUrl, 0, -4) . $this->getDavFilesPath($user) . $dest;
-		$this->makeDavRequest($user, 'MOVE', $source, [
+		$this->response = $this->makeDavRequest($user, 'MOVE', $source, [
```
Comment (PVince81) [inline tests/integration/features/bootstrap/WebDav.php]: looks like storing the response here makes the checksum test fail, weird...

**Comment by PVince81** [comment]
Fixed checksum test by making it check the HTTP status earlier.

**Comment by jvillafanez** [comment]
👍

**Comment by PVince81** [comment]
@owncloud-bot I hate you
```
10:05:08 Fire up the mysql docker
10:05:09 Waiting for MySQL(utf8mb4) initialisation ...
10:06:05 ...........................
10:06:06 MySQL(utf8mb4)  is up.
10:06:06 Installing ....
10:06:06 ownCloud is not installed - only a limited number of commands are available
10:06:11 Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'oc_autotest4'@'172.17.0.1' (using password: YES)
10:06:11  -> 
10:06:11 Kill the docker cc8c93196e8ade792a9dc1db92eb226b25bdfb0b17fa570f03be2a5d5df0f424
10:06:11 cc8c93196e8ade792a9dc1db92eb226b25bdfb0b17fa570f03be2a5d5df0f424
10:06:11 cc8c93196e8ade792a9dc1db92eb226b25bdfb0b17fa570f03be2a5d5df0f424
10:06:11 Makefile:179: recipe for target 'test-php' failed
10:06:11 make: *** [test-php] Error 1
```

**Comment by PVince81** [comment]
anotherrrrr rrrrebase

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/28261
