### PR TITLE
Only set the default expiration date on share creation

### LINKED ISSUE #19685: Changing sharing password activates default sharing expiration date
### Steps to reproduce
1. Configure "Set default expiration date" for link shares in admin panel
2. Share a folder by link; the default expiration time is applied
3. Uncheck the default expiration date
4. Set a password

### Expected behaviour
The default expiration date is applied again.

### Actual behaviour
The password should be set without affecting the expiration date.

### Server configuration
**Operating system**: CentOS 6.6

**Web server:** Apache httpd 2.2.15

**Database:** MySQL 5.1.73

**PHP version:** PHP 5.4.43

**ownCloud version:** 8.1.3

**Updated from an older ownCloud or fresh install:** updated several times since ownCloud 4.0.1

**List of activated apps:** Activity, Deleted files, External storage support, First Run Wizard, PDF Viewer, Pictures, Share Files, Text Editor, Video Viewer

**Are you using external storage, if yes which one:** N/A

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** N/A

### Client configuration
**Browser:** Firefox 41.0.1

**Operating system:** Fedora 22

#### Web server error log
No output shown

#### ownCloud log (data/owncloud.log)
No output shown

#### Browser log
No output shown in JS console

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #19685

The default expiration date should only be set when we create a new
share. So if a share is created and the expiration date is unset. And
after that the password is updated the expiration date should remain
unset.

CC: @MorrisJobke @PVince81 @nickvergessen @schiesbn

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
Code also looks good :)

File: lib/private/share20/share.php [hunk 1]
```diff
@@ -90,6 +90,9 @@ public function getId() {
 	 * @inheritdoc
 	 */
 	public function getFullId() {
+		if ($this->providerId === null || $this->id === null) {
+			return null;
```
Comment (LukasReschke) [inline lib/private/share20/share.php]: Seems like a violation of the PHPDoc as that seems to document only string?

Comment (rullzer) [inline lib/private/share20/share.php]: mmmm suggestions for an exception to use here then?

Comment (rullzer) [inline lib/private/share20/share.php]: Ok fixed... just added | null in the phpdoc...

File: lib/public/share/ishare.php [hunk 2]
```diff
@@ -46,7 +46,7 @@ public function getId();
 	 * Get the full share id. This is the <providerid>:<internalid>.
 	 * The full id is unique in the system.
 	 *
-	 * @return string
+	 * @return string|null null is returned when the fullId can't be constructed
```
Comment (MorrisJobke) [inline lib/public/share/ishare.php]: It always feels bad and it caused a lot of trouble in the past. Can't we handle this via exception?

Comment (rullzer) [inline lib/public/share/ishare.php]: sure... which one do you suggest...

Comment (MorrisJobke) [inline lib/public/share/ishare.php]: Something like `AttributeNotAvailableException` ? cc @DeepDiver1975

Comment (rullzer) [inline lib/public/share/ishare.php]: mmm we already have such a zoo of exceptions. i'd rather not have yet another custom one here... The exception name is fine from my POV but for something such generic it shouldnot be in specifc to the share...

Comment (rullzer) [inline lib/public/share/ishare.php]: Maybe UnexceptedValueException? (http://php.net/manual/en/class.unexpectedvalueexception.php)

Comment (MorrisJobke) [inline lib/public/share/ishare.php]: > Maybe UnexceptedValueException?

Sounds good.

Comment (rullzer) [inline lib/public/share/ishare.php]: Fixed

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
@rullzer Please check out the failing integration tests ;)

**Comment by rullzer** [comment]
Should be fixed now...

File: lib/public/share/ishare.php [hunk 3]
```diff
@@ -48,6 +48,7 @@ public function getId();
 	 *
 	 * @return string
 	 * @since 9.0.0
+	 * @throws \UnexpectedValueException If either the fullId could not be constructed
```
Comment (nickvergessen) [inline lib/public/share/ishare.php]: `if either` ? This english not is :yoda:

Comment (rullzer) [inline lib/public/share/ishare.php]: I have no idea what I wanted to write there...

**Comment by MorrisJobke** [comment]
Tested and still works :+1:

**Comment by PVince81** [comment]
:+1:
