### PR TITLE
Unlock sharee input field when sharing fails

### LINKED ISSUE #22441: Share the folder with a group and then with a user included in the group , the icon continues to spin
### Steps to reproduce
1. Go to the Server Web with v 9.0 with one user (e.g yellow)
2. Create a new folder/file (e.g hello)
3. Share the folder with the group call colors
4. Share the folder with the red user (this user is include to the group colors)
screen shot 2016-02-16 at 16 59 33
5. Click on OK for the "Error while sharing"

### Expected behaviour
Tell us what should happen

### Actual behaviour
And the sharing option is disabled and the icon continues to spin 
screen shot 2016-02-16 at 16 59 49

screen shot 2016-02-16 at 17 20 52

### Server configuration
Server v {"installed":true,"maintenance":false,"version":"9.0.0.11","versionstring":"9.0 beta 1","edition":"Enterprise"}

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #22441

When addShares fails (for whatever reason) we should unlock the sharee input field so the user does not have to reload the page.

@Dianafg76 please verify

CC: @PVince81 @nickvergessen @MorrisJobke

### CODE REVIEW

File: core/js/sharedialogview.js [hunk 1]
```diff
@@ -281,6 +281,12 @@
 					.attr('disabled', false);
 				$loading.addClass('hidden')
 					.removeClass('inlineblock');
+			}, error: function(obj, msg) {
+				OC.dialogs.alert(msg, t('core', 'Error while sharing'));
```
Comment (nickvergessen) [inline core/js/sharedialogview.js]: I hate that, can't we use a non-popup?
Maybe the yellow notification, or even OC.msg?

Comment (rullzer) [inline core/js/sharedialogview.js]: Sure we can... I just copied what we used to use... which do you prefer

Comment (tomneedham) [inline core/js/sharedialogview.js]: I'd vote for OC.Notification.showTemporary() to show it failed

**Comment by Dianafg76** [comment]
:+1:

File: core/js/sharedialogview.js (hunk 1 above)
Comment (rullzer) [inline core/js/sharedialogview.js]: Done

**Comment by nickvergessen** [comment]
Btw, while on it. In case a remote share failed, because you made a typo in your URL, it would be nice to readd the old value in the dropdown, so the user doesn't have to type the hole thing again.

**Comment by rullzer** [comment]
@nickvergessen sure we can! Done..

**Comment by nickvergessen** [comment]
:+1:
