### PR TITLE
[Tests-Only] Fix theseUsersHaveBeenCreatedUsingTheOccCommand so it works with mixed-case usernames

### LINKED ISSUE #37850: Test fails: Given this user has been created using the occ command
If the user has a mixed-case username, e.g. https://drone.owncloud.com/owncloud/user_ldap/2718/48/11
```
  Background:                                                    # /var/www/owncloud/testrunner/apps/user_ldap/tests/acceptance/features/cliProvisioning/groups.feature:7
    Given the administrator has invoked occ command "group:list" # OccContext::theAdministratorHasInvokedOccCommand()
    And this user has been created using the occ command:        # OccUsersGroupsContext::theseUsersHaveBeenCreatedUsingTheOccCommand()
      | username | displayname  |
      | Alice    | Alice Hansen |
      User: /var/www/owncloud/server/Alice was not created
      Failed asserting that false is true.
```

And the message `User: /var/www/owncloud/server/Alice was not created`  is also strange - it should just say `User: Alice was not created`

The relevant code was added yesterday in #37839 

Actually it could be made much simpler...

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
1) fixup the code that checks that the user exists, so that it works for mixed-case usernames.
2) use a simpler test that the user exists.

## Related Issue
- Fixes #37850 

## How Has This Been Tested?
Locally trying with modified versions of tests/acceptance/features/cliProvisioning/getUsers.feature:7 with a mixed-case username.

CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

File: tests/acceptance/features/bootstrap/OccUsersGroupsContext.php [hunk 1]
```diff
@@ -91,6 +91,8 @@ public function createUsersUsingOccCommand(TableNode $table) {
 				$password
 			);
 
+			$this->occContext->theCommandShouldHaveBeenSuccessful();
```
Comment (phil-davis) [inline tests/acceptance/features/bootstrap/OccUsersGroupsContext.php:94]: Note: this needs to be here inside the loop that creates users with the occ command. Checking it outside this loop will only check the status of the last user:add command.

**Review by individual-it — APPROVED** [review]
