### PR TITLE
Pass on the error message from the user manager to the UI

### LINKED ISSUE #24512: Users with umlaute like ü cannot be added manually
### Steps to reproduce
1.login as admin
2. add user "Michael Müller"
3.

### Expected behaviour
Michael Müller is happily added to owncloud

### Actual behaviour
Screen prompt: Error creating user: Benutzer konnte nicht erstellt werden.

### Server configuration
**Operating system**:
ubuntu 14.04
**Web server:**
apache
**Database:**
mysql  Ver 14.14 Distrib 5.5.49
**PHP version:**
php 5.5.9
**ownCloud version:** (see ownCloud admin page)
9.0.2 stable
**Updated from an older ownCloud or fresh install:**
fresh 
**Where did you install ownCloud from:**
packages
**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - admin_audit: 0.7
  - comments: 0.2
  - dav: 0.1.6
  - enterprise_key: 0.1.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_drop: 0.4.1
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firewall: 2.3.0
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - windows_network_drive: 0.2.33
  - workflow: 0.1.3

**The content of config/config.php:**

```

{
    "system": {
        "updatechecker": false,
        "supportedDatabases": [
            "mysql",
            "pgsql",
            "oci"
        ],
        
        "memcache.local": "\\OC\\Memcache\\APCu",
        "DISABLED.memcache.locking": "\\OC\\Memcache\\Redis",
        "DISABLED.memcache.distributed": "\\OC\\Memcache\\Redis",
        "Redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "instanceid": "oc2fr2dacmsb",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/var\/lib\/owncloud",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "dbname": "oc",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true
    }
}

```

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Chrome Version 50.0.2661.94 (64-bit)

**Operating system:**
OSX
#### Web server error log
```
192.168.99.1 - - [09/May/2016:12:47:15 +0000] "GET /settings/users/users?offset=0&limit=250&gid=&pattern= HTTP/1.1" 200 2103 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
::1 - - [09/May/2016:12:47:22 +0000] "OPTIONS * HTTP/1.0" 200 125 "-" "Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.16 OpenSSL/1.0.1f (internal dummy connection)"
192.168.99.1 - - [09/May/2016:12:47:25 +0000] "POST /settings/users/users HTTP/1.1" 403 1037 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
192.168.99.1 - - [09/May/2016:12:47:29 +0000] "POST /settings/users/users HTTP/1.1" 403 899 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"lyRcCYWCDQ5Bl379Xr9O","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(83): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(186): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(640): include('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(591): OC_Installer::includeAppScript('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(562): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/owncloud\\\/core\\\/command\\\/maintenance\\\/install.php(84): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Maintenance\\\\Install->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(840): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Maintenance\\\\Install), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/console\\\/application.php(145): Symfony\\\\Component\\\\Console\\\\Application->run(NULL, NULL)\\n#13 \\\/var\\\/www\\\/owncloud\\\/console.php(84): OC\\\\Console\\\\Application->run()\\n#14 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":72}","level":3,"time":"2016-05-09T12:06:18+00:00","method":"--","url":"--","user":"--"}
{"reqId":"lyRcCYWCDQ5Bl379Xr9O","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Calendar tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migratecalendars.php(84): OCA\\\\Dav\\\\Migration\\\\CalendarAdapter->setup()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(202): OCA\\\\Dav\\\\Migration\\\\MigrateCalendars->setup()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(27): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateCalendars()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(640): include('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(591): OC_Installer::includeAppScript('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(562): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/owncloud\\\/core\\\/command\\\/maintenance\\\/install.php(84): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Maintenance\\\\Install->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(840): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Maintenance\\\\Install), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/console\\\/application.php(145): Symfony\\\\Component\\\\Console\\\\Application->run(NULL, NULL)\\n#13 \\\/var\\\/www\\\/owncloud\\\/console.php(84): OC\\\\Console\\\\Application->run()\\n#14 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/calendaradapter.php\",\"Line\":68}","level":3,"time":"2016-05-09T12:06:18+00:00","method":"--","url":"--","user":"--"}
```

#### Browser log
```
jquery.min.js?v=b573819…:6 POST https://192.168.99.100/settings/users/users 403 (Forbidden)send @ jquery.min.js?v=b573819…:6x.extend.ajax @ jquery.min.js?v=b573819…:6x.(anonymous function) @ jquery.min.js?v=b573819…:6(anonymous function) @ users.js?v=b573819…:800(anonymous function) @ jquery.min.js?v=b573819…:4c @ jquery.min.js?v=b573819…:4p.add @ jquery.min.js?v=b573819…:4(anonymous function) @ jquery.min.js?v=b573819…:4x.extend.each @ jquery.min.js?v=b573819…:4(anonymous function) @ jquery.min.js?v=b573819…:4x.extend.Deferred @ jquery.min.js?v=b573819…:4r.then @ jquery.min.js?v=b573819…:4(anonymous function) @ users.js?v=b573819…:798x.event.dispatch @ jquery.min.js?v=b573819…:5v.handle @ jquery.min.js?v=b573819…:5
```

### PR DESCRIPTION
**Pull request by nickvergessen**
Currently the UI always shows `Unable to create user.` instead of:
- `Only the following characters are allowed in a username: "a-z", "A-Z", "0-9", and "_.@-\'"`
- `Username contains whitespace at the beginning or at the end`
- `The username is already being used`

I think we should also backport this to at least 9.0 @karlitschek 

Fix #24512

@LukasReschke @DeepDiver1975

### CODE REVIEW

**Comment by karlitschek** [comment]
awesome. please backport. I actually saw this problem myself a few days ago :-) 👍

**Comment by rullzer** [comment]
Yes makes total sense :+1:

File: settings/Controller/UsersController.php [hunk 1]
```diff
@@ -355,9 +355,13 @@ public function create($username, $password, array $groups=array(), $email='') {
 		try {
 			$user = $this->userManager->createUser($username, $password);
 		} catch (\Exception $exception) {
+			$message = $exception->getMessage();
```
Comment (MorrisJobke) [inline settings/Controller/UsersController.php]: @LukasReschke Wasn't the idea to only pass messages for HintExceptions? Otherwise the error message could contain sensitive data.

Comment (nickvergessen) [inline settings/Controller/UsersController.php]: Wrong context? this is inside the create user endpoint, the only exceptions that are thrown are known:
https://github.com/owncloud/core/blob/b10dcfc3b7e84c97d4dba4f7c63b4dff2fbc310b/lib/private/user/manager.php#L269-L289
They also are translated, so it is intended to be publicly visible.

**Comment by MorrisJobke** [comment]
I like this, but the error handling in the UI needs some refinements: issue-24512-forward-user-manager-error-messages-to-ui

**Comment by nickvergessen** [comment]
Fixed the quote problem

**Comment by MorrisJobke** [comment]
Tested and works 👍

File: settings/js/users/users.js [hunk 2]
```diff
@@ -840,7 +840,7 @@ $(document).ready(function () {
 				}).fail(function(result) {
 					OC.Notification.showTemporary(t('settings', 'Error creating user: {message}', {
 						message: result.responseJSON.message
-					}));
+					}, undefined, {escape: false}));
```
Comment (MorrisJobke) [inline settings/js/users/users.js]: cc @LukasReschke

Comment (nickvergessen) [inline settings/js/users/users.js]: Well this is required for the quote signs from your above screenshot.

Comment (MorrisJobke) [inline settings/js/users/users.js]: I know, I just want to get feedback from Lukas, because there is a reason we introduced this ;9

Comment (nickvergessen) [inline settings/js/users/users.js]: Well showTemporary encodes it again, when isHTML is not set, so this is save
