### PR TITLE
triger the propagator from the command line scanner

### LINKED ISSUE #24255: Scanner doesn't propagate etags any more when file changed
### Steps:

1. Pick an external storage type (SFTP or SMB)
1. Directly on the storage, create a folder "updatetest/sub/test.txt"
1. Setup that external storage in ownCloud
1. Close the web browser to avoid interferences (buildstoragestats, etc)
1. Run `occ files:scan --all`
1. Check database: `select fileid,path,size,mtime,storage_mtime,etag from oc_filecache where storage=3 order by path;`. Take note of etags.
1. Change the contents of the file "test.txt" directly on the storage, not through ownCloud.
1. Run `occ files:scan --all`
1. Check database: `select fileid,path,size,mtime,storage_mtime,etag from oc_filecache where storage=3 order by path;`. Compare etags.

### Expected result
After the second scan, the etag and size of all parents were updated up to the storage root.

### Actual result
After the second scan, only the size changed but not the etag.
Only the etag of "test.txt" changed, and so does its "storage_mtime".

### Versions
Works in ownCloud 8.2.3
Broken in ownCloud 9.0.1

@icewind1991 please help fixing this regression, thanks.

CC @MorrisJobke @bboule

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes https://github.com/owncloud/core/issues/24255

cc @PVince81

### CODE REVIEW

File: lib/private/Files/Utils/Scanner.php [hunk 1]
```diff
@@ -168,5 +180,9 @@ public function scan($dir = '') {
 			}
 		}
 	}
+
+	private function triggerPropagator(IStorage $storage, $internalPath) {
+		$storage->getPropagator()->propagateChange($internalPath, time());
```
Comment (PVince81) [inline lib/private/Files/Utils/Scanner.php]: @icewind1991 can you remind me whether this is debounced on the path ?

Because if we detect several changes within the same folder, it would be expensive to propagate the etag to the parents several times for every found file.

**Comment by PVince81** [comment]
Tested, works :+1: 

@karlitschek backport to 9.0.2 ?

**Comment by karlitschek** [comment]
great. please backport

**Comment by PVince81** [comment]
@icewind1991 please submit the backport PR, thanks

**Comment by icewind1991** [comment]
stable9: https://github.com/owncloud/core/pull/24261

**Comment by MorrisJobke** [comment]
👍
