### PR TITLE
Deletion of user should also delete applicable users for the storage

### LINKED ISSUE #32637: [10.0.10RC1] Deleting user doesn't delete them from external storages
### Steps to reproduce
1. Create four users "user1", "user2", "user3", "user4"
1. Allow users mounting external storages and limit it to only "SFTP"
1. Create an external storage "/sftp" applicable to all
1. Create a global external storage "/sftpuser4" applicable to "user1", "user2", "user4", "user3" (in that order, because why not)
1. Login as "user4"
1. Create a personal storage "/sftpdirect"
1. Check that all three storages are accessible
1. Login as admin
1. Delete user4
1. Navigate to storages settings page
1. Check database tables oc_external_*

### Expected behaviour
- user4 disappeared from the applicable list fo "/sftpuser4"
- database contains no trace of "/sftpuser4"
- database contains no applicable entries for "user4"

### Actual behaviour
- user4 disappeared in the web UI but is present in database:
```
MariaDB [owncloudtest]> select * from oc_external_applicable;
+---------------+----------+------+-------+
| applicable_id | mount_id | type | value |
+---------------+----------+------+-------+
|             1 |        1 |    1 | NULL  |
|             3 |        2 |    3 | user1 |
|             4 |        2 |    3 | user2 |
|             5 |        2 |    3 | user3 |
|             6 |        3 |    3 | user4 |
+---------------+----------+------+-------+
5 rows in set (0.01 sec)
```
- database still contains the mount:
```
MariaDB [owncloudtest]> select * from oc_external_mounts;
+----------+------------------+-----------------+--------------------+----------+------+
| mount_id | mount_point      | storage_backend | auth_backend       | priority | type |
+----------+------------------+-----------------+--------------------+----------+------+
|        1 | /sftp            | sftp            | password::password |      100 |    1 |
|        2 | /sftpuser4       | sftp            | password::password |      100 |    1 |
|        3 | /sftpuser4direct | sftp            | password::password |      100 |    2 |
+----------+------------------+-----------------+--------------------+----------+------+
```

### Server configuration
ownCloud 10.0.10 RC1
openSUSE Tumbleweed 20180731
php7-7.2.7-1.4.x86_64

### Logs
Nothing relevant since the moment I accessed some files on the storage when testing:
```
{"reqId":"VRyjj0SY1prlOZXeRHwb","level":0,"time":"2018-09-07T10:14:19+00:00","remoteAddr":"127.0.0.1","user":"--","app":"webdav","method":"GET","url":"\/owncloudtest\/remote.php\/dav\/files\/user4\/sftp\/20180518_201208.jpg?c=5b924ef680a6c&x=32&y=32&forceIcon=0&preview=1","message":"Exception: HTTP\/1.1 401 No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Message\":\"No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/apps\\\/dav\\\/lib\\\/Server.php(298): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/remote.php(165): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#7 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168}"}
{"reqId":"u2OkDQ5YjLwvVa1QrZHQ","level":0,"time":"2018-09-07T10:14:19+00:00","remoteAddr":"127.0.0.1","user":"--","app":"webdav","method":"GET","url":"\/owncloudtest\/remote.php\/dav\/files\/user4\/sftp\/20180521_140435.jpg?c=5b924ef6820f0&x=32&y=32&forceIcon=0&preview=1","message":"Exception: HTTP\/1.1 401 No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Message\":\"No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/apps\\\/dav\\\/lib\\\/Server.php(298): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/remote.php(165): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#7 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168}"}
{"reqId":"i6zSZ6z6I4I9bWb8dDtz","level":0,"time":"2018-09-07T10:14:19+00:00","remoteAddr":"127.0.0.1","user":"user4","app":"core","method":"GET","url":"\/owncloudtest\/remote.php\/dav\/files\/user4\/sftp\/20180502_141728.jpg?c=5b924ef678fb9&x=32&y=32&forceIcon=0&preview=1","message":"OC_Image->fixOrientation() Image is not a JPEG."}
{"reqId":"i6zSZ6z6I4I9bWb8dDtz","level":0,"time":"2018-09-07T10:14:19+00:00","remoteAddr":"127.0.0.1","user":"user4","app":"core","method":"GET","url":"\/owncloudtest\/remote.php\/dav\/files\/user4\/sftp\/20180502_141728.jpg?c=5b924ef678fb9&x=32&y=32&forceIcon=0&preview=1","message":"OC_Image->fixOrientation() Orientation: -1"}
{"reqId":"IzsS1q1fUu8ZpVd99ZsP","level":0,"time":"2018-09-07T10:14:20+00:00","remoteAddr":"127.0.0.1","user":"user4","app":"core","method":"GET","url":"\/owncloudtest\/remote.php\/dav\/files\/user4\/sftp\/20180502_141717.jpg?c=5b924ef676d6d&x=32&y=32&forceIcon=0&preview=1","message":"OC_Image->fixOrientation() Image is not a JPEG."}
{"reqId":"IzsS1q1fUu8ZpVd99ZsP","level":0,"time":"2018-09-07T10:14:20+00:00","remoteAddr":"127.0.0.1","user":"user4","app":"core","method":"GET","url":"\/owncloudtest\/remote.php\/dav\/files\/user4\/sftp\/20180502_141717.jpg?c=5b924ef676d6d&x=32&y=32&forceIcon=0&preview=1","message":"OC_Image->fixOrientation() Orientation: -1"}
{"reqId":"bemYOnIPrG8yWp7zymQI","level":0,"time":"2018-09-07T10:14:20+00:00","remoteAddr":"127.0.0.1","user":"user4","app":"core","method":"GET","url":"\/owncloudtest\/remote.php\/dav\/files\/user4\/sftp\/20180516_174802.jpg?c=5b924ef67ec72&x=32&y=32&forceIcon=0&preview=1","message":"OC_Image->fixOrientation() Image is not a JPEG."}
{"reqId":"bemYOnIPrG8yWp7zymQI","level":0,"time":"2018-09-07T10:14:20+00:00","remoteAddr":"127.0.0.1","user":"user4","app":"core","method":"GET","url":"\/owncloudtest\/remote.php\/dav\/files\/user4\/sftp\/20180516_174802.jpg?c=5b924ef67ec72&x=32&y=32&forceIcon=0&preview=1","message":"OC_Image->fixOrientation() Orientation: -1"}
{"reqId":"tuUx0CWOSKrtvRVpAIEd","level":0,"time":"2018-09-07T10:14:21+00:00","remoteAddr":"127.0.0.1","user":"--","app":"webdav","method":"GET","url":"\/owncloudtest\/remote.php\/dav\/files\/user4\/sftp\/20180521_140946.jpg?c=5b924ef683809&x=32&y=32&forceIcon=0&preview=1","message":"Exception: HTTP\/1.1 401 No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Message\":\"No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/apps\\\/dav\\\/lib\\\/Server.php(298): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/remote.php(165): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#7 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168}"}
{"reqId":"1WdgNHkAkA2rm2AOMz4i","level":0,"time":"2018-09-07T10:14:39+00:00","remoteAddr":"127.0.0.1","user":"--","app":"no app in context","method":"POST","url":"\/owncloudtest\/index.php\/login","message":"CSRF check failed"}
{"reqId":"YF7ppCdVslDeELsKQA0p","level":0,"time":"2018-09-07T10:14:42+00:00","remoteAddr":"127.0.0.1","user":"--","app":"OC\\User\\Session::login","method":"POST","url":"\/owncloudtest\/index.php\/login","message":"regenerating session id for uid admin, password set"}
{"reqId":"G9KaBZAruJIy54Zlv6HR","level":3,"time":"2018-09-07T10:14:50+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"GET","url":"\/owncloudtest\/index.php\/settings\/users","message":"Undefined index: add_password at \/srv\/www\/htdocs\/owncloudtest\/settings\/templates\/users\/main.php#85"}
```

@sharidas

### PR DESCRIPTION
**Pull request by sharidas**
When a user is deleted the storage added by the user
should be removed from the db. This change helps to
remove the user from the applicable with the help
of DBConfigService.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

When a user is deleted, the storages created by user should be cleaned from the db. That is the applicable array should not have any more residues about the user.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/32637

## Motivation and Context

When a user is deleted, the storages created by user should be cleaned from the db. That is the applicable array should not have any more residues about the user.

## How Has This Been Tested?

Following the procedure from steps to produce in https://github.com/owncloud/core/issues/32637#issue-358009322:
- In the newly installed machine before deleting `user4` the tables were like this:
```
sqlite> select * from oc_mounts;
id          storage_id  root_id     user_id     mount_point
----------  ----------  ----------  ----------  -----------
1           1           1           admin       /admin/    
2           4           23          user4       /user4/    
3           3           28          user4       /user4/file
sqlite> select * from oc_external_applicable;
applicable_id  mount_id    type        value     
-------------  ----------  ----------  ----------
1              1           1                     
3              2           3           user1     
4              2           3           user2     
5              2           3           user4     
6              2           3           user3     
7              3           3           user4     
sqlite> select * from oc_external_mounts;
mount_id    mount_point  storage_backend  auth_backend        priority    type      
----------  -----------  ---------------  ------------------  ----------  ----------
1           /sftp        sftp             password::password  100         1         
2           /sftpuser4   sftp             password::password  100         1         
3           /sftpdirect  sftp             password::password  100         2         
sqlite> select * from oc_external_config;
config_id   mount_id    key         value     
----------  ----------  ----------  ----------
1           1           host        localhost 
2           1           root        /tmp/a    
3           1           user        sujith    
4           1           password    9f16a17347
5           2           host        localhost 
6           2           root        /tmp/a    
7           2           user        sujith    
8           2           password    aaafba9dc9
9           3           host        localhost 
10          3           root        /tmp/a    
11          3           user        sujith    
12          3           password    6c9d98c910
sqlite>
```
- After `user4` is deleted table is as shown below:
```
sqlite> select * from oc_mounts;
id          storage_id  root_id     user_id     mount_point
----------  ----------  ----------  ----------  -----------
1           1           1           admin       /admin/    
4           3           28          admin       /admin/file
sqlite> select * from oc_external_applicable;
applicable_id  mount_id    type        value     
-------------  ----------  ----------  ----------
1              1           1                     
3              2           3           user1     
4              2           3           user2     
6              2           3           user3     
sqlite> select * from oc_external_mounts;
mount_id    mount_point  storage_backend  auth_backend        priority    type      
----------  -----------  ---------------  ------------------  ----------  ----------
1           /sftp        sftp             password::password  100         1         
2           /sftpuser4   sftp             password::password  100         1         
sqlite> select * from oc_external_config;
config_id   mount_id    key         value     
----------  ----------  ----------  ----------
1           1           host        localhost 
2           1           root        /tmp/a    
3           1           user        sujith    
4           1           password    9f16a17347
5           2           host        localhost 
6           2           root        /tmp/a    
7           2           user        sujith    
8           2           password    aaafba9dc9
sqlite>
```
- Create `user4` again and the table is as shown:
```
sqlite> select * from oc_mounts;
id          storage_id  root_id     user_id     mount_point
----------  ----------  ----------  ----------  -----------
1           1           1           admin       /admin/    
4           3           28          admin       /admin/file
5           3           28          user4       /user4/file
6           5           33          user4       /user4/    
sqlite> select * from oc_external_applicable;
applicable_id  mount_id    type        value     
-------------  ----------  ----------  ----------
1              1           1                     
3              2           3           user1     
4              2           3           user2     
6              2           3           user3     
8              2           3           user4     
9              4           3           user4     
sqlite> select * from oc_external_mounts;
mount_id    mount_point  storage_backend  auth_backend        priority    type      
----------  -----------  ---------------  ------------------  ----------  ----------
1           /sftp        sftp             password::password  100         1         
2           /sftpuser4   sftp             password::password  100         1         
4           /sftpdirect  sftp             password::password  100         2         
sqlite> select * from oc_external_config;
config_id   mount_id    key         value     
----------  ----------  ----------  ----------
1           1           host        localhost 
2           1           root        /tmp/a    
3           1           user        sujith    
4           1           password    9f16a17347
5           2           host        localhost 
6           2           root        /tmp/a    
7           2           user        sujith    
8           2           password    aaafba9dc9
13          4           host        localhost 
14          4           root        /tmp/a    
15          4           user        sujith    
16          4           password    7e35de472a
sqlite>
```
- Again delete `user4` and the table is as shown below:
```
sqlite> select * from oc_mounts;
id          storage_id  root_id     user_id     mount_point
----------  ----------  ----------  ----------  -----------
1           1           1           admin       /admin/    
4           3           28          admin       /admin/file
sqlite> select * from oc_external_applicable;
applicable_id  mount_id    type        value     
-------------  ----------  ----------  ----------
1              1           1                     
3              2           3           user1     
4              2           3           user2     
6              2           3           user3     
sqlite> select * from oc_external_mounts;
mount_id    mount_point  storage_backend  auth_backend        priority    type      
----------  -----------  ---------------  ------------------  ----------  ----------
1           /sftp        sftp             password::password  100         1         
2           /sftpuser4   sftp             password::password  100         1         
sqlite> select * from oc_external_config;
config_id   mount_id    key         value     
----------  ----------  ----------  ----------
1           1           host        localhost 
2           1           root        /tmp/a    
3           1           user        sujith    
4           1           password    9f16a17347
5           2           host        localhost 
6           2           root        /tmp/a    
7           2           user        sujith    
8           2           password    aaafba9dc9
sqlite>
```
- Also verified after the deletion the admin settings never showed user4 for the storage  `sftpuser4`.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by mmattel** [comment]
For the record, [stable10] already merged: https://github.com/owncloud/core/pull/32069

**Comment by PVince81** [comment]
@mmattel that one didn't work as expected, reported here: https://github.com/owncloud/core/issues/32637

the PR here brings in some missing bits

**Comment by PVince81** [comment]
@sharidas please double check if there are missing references

**Comment by sharidas** [comment]
Let me add my results here:

1. Create four users "user1", "user2", "user3", "user4"
2. Allow users mounting external storages and limit it to only "SFTP"
3. Create an external storage "/sftp" applicable to all
4. Create a global external storage "/sftpuser4" applicable to "user1", "user2", "user4", "user3" 
5. Create a global external storage with "owncloud" for "user4"
6. Login as "user4"
7. Create a personal storage "/ownclouddirect"
8. Check that all four storages are accessible
9. Login as admin
10. Delete user4
11. Result from database query to prove it worked:
```
sqlite> select * from oc_external_mounts;
mount_id    mount_point  storage_backend  auth_backend        priority    type      
----------  -----------  ---------------  ------------------  ----------  ----------
1           /sftp        sftp             password::password  100         1         
2           /sftpuser4   sftp             password::password  100         1         
sqlite> select * from oc_mounts;
id          storage_id  root_id     user_id     mount_point
----------  ----------  ----------  ----------  -----------
1           1           1           admin       /admin/    
4           3           34          admin       /admin/file
sqlite> 
sqlite> 
sqlite> 
sqlite> 
sqlite> select * from oc_mounts;
id          storage_id  root_id     user_id     mount_point
----------  ----------  ----------  ----------  -----------
1           1           1           admin       /admin/    
4           3           34          admin       /admin/file
sqlite> select * from oc_external_applicable;
applicable_id  mount_id    type        value     
-------------  ----------  ----------  ----------
1              1           1                     
3              2           3           user1     
4              2           3           user2     
5              2           3           user3     
sqlite> select * from oc_external_mounts;
mount_id    mount_point  storage_backend  auth_backend        priority    type      
----------  -----------  ---------------  ------------------  ----------  ----------
1           /sftp        sftp             password::password  100         1         
2           /sftpuser4   sftp             password::password  100         1         
sqlite>
```
There is no reference of "user4" here.

Another test to have 2 personal storages for user4:
1. Create "user4"
2. Login as "user4"
3. Allow user4 to create 2 personal storages "/ownclouddirect" and "/sftpdirect"
4. Now delete user4.
5. There should be no traces of "user4" in the db.
6. Traces of "user4" not found in db:
```
sqlite> select * from oc_mounts;
id          storage_id  root_id     user_id     mount_point
----------  ----------  ----------  ----------  -----------
1           1           1           admin       /admin/    
sqlite> select * from oc_external_mounts;
sqlite> select * from oc_external_applicable;
sqlite> select * from oc_external_config;
sqlite> 
```
Another test to have global storages  for user4 and no personal storages:
1. Create "user4"
2. Create "/owncloud" and "/sftp", which are available for users like "user1", "user2", "user3" and "user4" only
3. Login as "user4"
4. Now delete user4.
5. There should be no traces of "user4" in the db.
6. Db table results are as shown below:
```
sqlite> select * from oc_mounts;
id          storage_id  root_id     user_id     mount_point
----------  ----------  ----------  ----------  -----------
1           1           1           admin       /admin/    
7           5           33          user1       /user1/file
8           4           32          user1       /user1/file
9           5           33          user2       /user2/file
10          4           32          user2       /user2/file
11          5           33          user3       /user3/file
12          4           32          user3       /user3/file
sqlite> select * from oc_external_mounts;
mount_id    mount_point  storage_backend  auth_backend        priority    type      
----------  -----------  ---------------  ------------------  ----------  ----------
3           /owncloud    owncloud         password::password  100         1         
4           /sftp        sftp             password::password  100         1         
sqlite> select * from oc_external_config;
config_id   mount_id    key         value                    
----------  ----------  ----------  -------------------------
10          3           host        http://localhost/testing2
11          3           root                                 
12          3           secure                               
13          3           user        admin                    
14          3           password    65f3f06859c35cffc0c3fadc5
15          4           host        localhost                
16          4           root        /tmp/a                   
17          4           user        sujith                   
18          4           password    e1d93e49a590b170156e0955d
sqlite> select * from oc_external_applicable;
applicable_id  mount_id    type        value     
-------------  ----------  ----------  ----------
5              4           3           user1     
6              4           3           user2     
9              4           3           user3     
10             3           3           user1     
12             3           3           user2     
13             3           3           user3     
sqlite>
```

The above tests do cover global storages only, personal storages only and both global + personal storages. Which in my humble opinion covers most of the cases.

File: lib/private/Files/External/Service/UserStoragesService.php [hunk 1]
```diff
@@ -158,6 +159,21 @@ public function deleteAllMountsForUser(IUser $user) {
 				$result = true;
 			}
 		}
+		if (\count($allMounts)) {
+			foreach ($allMounts as $userMount) {
+				/**
+				 * Remove any mounts which are applicable to only this user
+				 * Specifically targeted to, mounts created by the user.
+				 */
+				if (\count($userMount['applicable']) === 1) {
```
Comment (PVince81) [inline lib/private/Files/External/Service/UserStoragesService.php]: so are we removing the user from the applicable list in a different location in the code ? (when applicable is more than one user). from your test results it seems to work so properly different existing code ?

**Comment by sharidas** [comment]
> The referenced PR is stable10 and as far as I have seen there is no corresponding master PR (even it would not work properly).
> Pls correct me, if this PR does its job, master is fixed, but needs backporting to stable10 to be clean

The not working pr merged to master branch -> https://github.com/owncloud/core/pull/30712 and stable10 branch pr -> https://github.com/owncloud/core/pull/32069 ( not working ).
So we do have a master branch pr here. Let me know if I answered your query?

File: lib/private/Files/External/Service/UserStoragesService.php (hunk 1 above)
Comment (sharidas) [reply lib/private/Files/External/Service/UserStoragesService.php]: The `GlobalStoragesService` does remove user from applicable list, here https://github.com/owncloud/core/blob/master/lib/private/Files/External/Service/GlobalStoragesService.php#L199-L214. So as per the test https://github.com/owncloud/core/issues/32637#issue-358009322 -> the global storages does remove `user4` from the applicable list. 

Let me know if this was the information, that you are looking for. If not I would need your helping hand in understanding the query.

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@sharidas please backport
