### PR TITLE
LDAP fix quota and case, fixes #20043

### LINKED ISSUE #20043: [8.2] LDAP - Quota not delivered
### Steps to reproduce
1. Set up ownCloud 8.2
2. Configure LDAP
3. Login with User / Wait for quota refresh time

### Expected behaviour
Quota in ownCloud should be set to the value given by LDAP ('Quota Field')
This was working with the same LDAP-Configuration using Version 8.1.3.

### Actual behaviour
Quota is set to 1073741824 ('Quota Default'); Quota is not refreshed when logging or after waiting 24h.

### Server configuration
**Operating system**:
Redhat 7
**Web server:**
Apache/2.4.6
**Database:**
MariaDB
**PHP version:**
5.4.16
**ownCloud version:** (see ownCloud admin page)
8.2
**Updated from an older ownCloud or fresh install:**
Fresh Install

#### LDAP configuration

+-------------------------------+------------------------------------------------------+
| Configuration                 |                                                      |
+-------------------------------+------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                    |
| hasPagedResultSupport         |                                                      |
| homeFolderNamingRule          |                                                      |
| lastJpegPhotoLookup           | 0                                                    |
| ldapAgentName                 | cn=ownCloudUser,ou=Special Users,dc=...,dc=de        |
| ldapAgentPassword             | ***                                                  |
| ldapAttributesForGroupSearch  | description                                          |
| ldapAttributesForUserSearch   | mail;givenName;uid;displayName;sn                    |
| ldapBackupHost                |                                                      |
| ldapBackupPort                |                                                      |
| ldapBase                      | dc=...,dc=de                                  	   |
| ldapBaseGroups                | ou=Groups,dc=...,dc=de                        	   |
| ldapBaseUsers                 | ou=People,dc=...,dc=de                        	   |
| ldapCacheTTL                  | 600                                                  |
| ldapConfigurationActive       | 1                                                    |
| ldapEmailAttribute            | mail                                                 |
| ldapExperiencedAdmin          | 1                                                    |
| ldapExpertUUIDGroupAttr       | cn                                                   |
| ldapExpertUUIDUserAttr        | uid                                                  |
| ldapExpertUsernameAttr        |                                                      |
| ldapGroupDisplayName          | description                                          |
| ldapGroupFilter               | (cn=*)                                               |
| ldapGroupFilterGroups         |                                                      |
| ldapGroupFilterMode           | 0                                                    |
| ldapGroupFilterObjectclass    |                                                      |
| ldapGroupMemberAssocAttr      | memberUid                                            |
| ldapHost                      | 							                           |
| ldapIgnoreNamingRules         |                                                      |
| ldapLoginFilter               | (&(OwnCloudQuota=*)(uid=%uid))                   	   |
| ldapLoginFilterAttributes     |                                                      |
| ldapLoginFilterEmail          | 0                                                    |
| ldapLoginFilterMode           | 0                                                    |
| ldapLoginFilterUsername       | 1                                                    |
| ldapNestedGroups              | 0                                                    |
| ldapOverrideMainServer        |                                                      |
| ldapPagingSize                | 499                                                  |
| ldapPort                      | 636                                                  |
| ldapQuotaAttribute            | OwnCloudQuota                                 	   |
| ldapQuotaDefault              | 1073741824                                           |
| ldapTLS                       | 0                                                    |
| ldapUserDisplayName           | displayName                                          |
| ldapUserFilter                | (OwnCloudQuota=*)                            		   |
| ldapUserFilterGroups          |                                                      |
| ldapUserFilterMode            | 0                                                    |
| ldapUserFilterObjectclass     |                                                      |
| ldapUuidGroupAttribute        | auto                                                 |
| ldapUuidUserAttribute         | auto                                                 |
| turnOffCertCheck              | 0                                                    |
| useMemberOfToDetectMembership | 1                                                    |
+-------------------------------+------------------------------------------------------+

### PR DESCRIPTION
**Pull request by blizzz**
This is a forward port of two issues found only when backporting #18469 to stable8.1 (https://github.com/owncloud/core/pull/19427, https://github.com/owncloud/core/pull/19427#discussion_r40670112). This also fixes https://github.com/owncloud/core/issues/20043.

It needs to be backported to 8.2. Please confirm @karlitschek 

Please test and review @davitol @eidota @MorrisJobke

### CODE REVIEW

**Comment by karlitschek** [comment]
makes sense. please backport :+1:

**Comment by eidota** [comment]
Working as expected - Quota is delivered and even the mass 'displayName' errors in our logfile are gone :thumbsup:

**Comment by MorrisJobke** [comment]
Tested and still works :+1:

**Comment by MorrisJobke** [comment]
@blizzz Can you please prepare the backport? Thanks

**Comment by eidota** [comment]
Contrary to my last comment my logs still show the displayname error:
`{"reqId":"aKzMlvmDUGzMFNVLD3lX","remoteAddr":"","app":"PHP","message":"Undefined index: displayname at \/disk1\/webserver\/owncloud\/apps\/user_ldap\/lib\/access.php#696","level":3,"time":"2015-10-28T12:15:08+01:00"}`
Before i edited the code with your changes the log showed the same message but with the index 'displayName'.
Is this error a separate issue?

**Comment by blizzz** [comment]
@eidota in that case it seems that the attribute was either not read or not available at all for the record. Can you give me reproduction steps?

**Comment by eidota** [comment]
The error doesn't occur on demand, e.g. when i reload the users page. I get block of 66 entries of this error message about once per hour. Seems to happen when checking the ldap data in the background.
The 66 entries match our 66 users in our testing environment. I checked the ldap-records - the attribute displayName is filled for all of them.

Is this attribute used to fill the 'Full Name' field on the users page? Because they are shown correctly there.

File: apps/user_ldap/lib/access.php [hunk 1]
```diff
@@ -691,8 +691,9 @@ public function fetchListOfUsers($filter, $attr, $limit = null, $offset = null)
 	 * @param array $ldapRecords
 	 */
 	public function batchApplyUserAttributes(array $ldapRecords){
+		$displayNameAttribute = strtolower($this->connection->ldapUserDisplayName);
 		foreach($ldapRecords as $userRecord) {
-			$ocName  = $this->dn2ocname($userRecord['dn'][0], $userRecord[$this->connection->ldapUserDisplayName]);
+			$ocName  = $this->dn2ocname($userRecord['dn'][0], $userRecord[$displayNameAttribute]);
```
Comment (blizzz) [inline apps/user_ldap/lib/access.php]: $userRecord[$displayNameAttribute] must be [0]. Thanks to @eidota 's hint, i rechecked that part. I does not cause any trouble, because in dn2ocname this is used just for mapping a group. With that inside, i could cleanup dn2ocname() a bit… So, actually we can just leave the part displayNameAttribute part away, which will save any undefined index warning (which is probably a user record without display name).

**Comment by blizzz** [comment]
> I get blocks of 66 entries of this error message about once per hour. Seems to happen when checking the ldap data in the background.

Yes, it's the background job, calling usersInGroup() which only looks for the DN. This can also happen when viewing selecting groups on the Users page. It makes sense to read the other attributes in this case as well. There are more places in group_ldap where we are fetching users like that. But in countUsersInGroup() and inGroup() it is good keep it simple and don't read and do any more than necessary.

So, Todos for me:
* [ ] don't provide the displayname (and asssume it is there) when passing it to dn2ocname
* [ ] usersInGroup() should also read additional meta data about users

I will do this for master in a new PR and backport both together.

**Comment by blizzz** [comment]
Please see https://github.com/owncloud/core/issues/20124 which fixes remaining tasks
