### PR TITLE
[10.9.0] Return all quota fields in Provisioning API get-user requests

### LINKED ISSUE #39577: provisioning API report is incomplete when user name casing is not exact
Seen in 10.9.0 beta1

In https://github.com/owncloud/core/issues/36139#issuecomment-923832433 @phil-davis reported that quota details are missing, when unexpected upper case is used on a username.
This is still reproduced in 10.9.0 beta1

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Pass the exact actual username to `fillStorageInfo` so that it will find the storage and calculate the quota fields, even if the username in the incoming API request has different case.

## Related Issue
- Fixes #39577 

## How Has This Been Tested?
Acceptance tests. Without the code change, these tests scenarios fail for me locally:
```
--- Failed scenarios:

    /home/phil/git/owncloud/core/tests/acceptance/features/apiProvisioning-v1/getUser.feature:42
    /home/phil/git/owncloud/core/tests/acceptance/features/apiProvisioning-v1/getUser.feature:129
    /home/phil/git/owncloud/core/tests/acceptance/features/apiProvisioning-v1/getUser.feature:142

--- Failed scenarios:

    /home/phil/git/owncloud/core/tests/acceptance/features/apiProvisioning-v2/getUser.feature:42
    /home/phil/git/owncloud/core/tests/acceptance/features/apiProvisioning-v2/getUser.feature:129
    /home/phil/git/owncloud/core/tests/acceptance/features/apiProvisioning-v2/getUser.feature:142
```

With the back-end code change, the tests all pass.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
@JammingBen I didn't add any unit tests. I just added an extra test step in the existing getUser acceptance test scenarios to verify that the quota fields look reasonable.

Maybe you could add some unit tests? Or not?

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIUpload-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34011/150/1

File: apps/provisioning_api/lib/Users.php [hunk 1]
```diff
@@ -218,7 +218,7 @@ public function getUser($parameters) {
 		}
 
 		// Find the data
-		$data['quota'] = $this->fillStorageInfo($userId);
+		$data['quota'] = $this->fillStorageInfo($targetUserObject->getUID());
```
Comment (jvillafanez) [inline apps/provisioning_api/lib/Users.php:221]: We might need to test this with the ldap backend to ensure it doesn't do anything weird

**Review by jvillafanez — APPROVED** [review]

**Comment by JammingBen** [comment]
> Maybe you could add some unit tests? Or not needed?

I looked at `fillStorageInfo()`, it uses "real" functionality and is therefore mocked. That means we would mock the return which is at the same time the thing we need to test here. I'd say we're fine with the acceptance tests.

File: apps/provisioning_api/lib/Users.php (hunk 1 above)
Comment (JammingBen) [reply apps/provisioning_api/lib/Users.php:221]: Tested with Ldap, works fine here. The UID (accounts table) gets fetched from the DB anyway, so LDAP is not even involved here.

**Review by JammingBen — APPROVED** [review]
