### PR TITLE
Fix uploading avatar and root certs in IE8

### LINKED ISSUE #18007: Uploading of profile picture doesn't work on IE8
### Steps to reproduce

Using internet explorer 8 do:
1. Go to personal page.
2. Upload a picture (anyone of any size).

### Expected behaviour
Profile picture is updated.

### Actual behaviour
Profile picture is not shown.

### Server configuration

Operating system:
Ubuntu 14.04 LTS

Web server:
Apache

Database:
MySQL

PHP version:
5.5.9

ownCloud version: (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.1.1","versionstring":"8.1.1 beta1","edition":"Enterprise"}

Updated from an older ownCloud or fresh install:
fresh

List of activated apps:
Default ones.

Are you using external storage, if yes which one: local/smb/sftp/...
No.

Are you using encryption: 
No.

### Client configuration
Internet Explorer 8

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/18007

Avatar tests:
- [x] TEST: upload avatar with IE8, with cropping
- [x] TEST: select avatar from files in IE8, with cropping
- [x] TEST: upload avatar with Chromium, with cropping
- [x] TEST: select avatar from files with Chromium, with cropping

Root cert tests:
- [x] TEST: upload invalid cert file in IE8
- [x] TEST: upload invalid cert file in Chromium
- [x] TEST: upload valid cert file in IE8
- [x] TEST: upload valid cert file in Chromium

To be able to upload root certs you need to enable the "External storage" app and select at least one backend in "Allow users to mount the following external storage"
- [x] REQUIRE: https://github.com/owncloud/core/issues/18585 due to a bug on master uploading certs is broken and cannot be tested.

CC @SergioBertolinSG @DeepDiver1975

### CODE REVIEW

File: core/avatar/avatarcontroller.php [hunk 1]
```diff
@@ -139,12 +139,21 @@ public function postAvatar($path) {
 		$userId = $this->userSession->getUser()->getUID();
 		$files = $this->request->getUploadedFile('files');
 
+		$headers = [];
+		if (\OCP\Util::isIE8()) {
```
Comment (LukasReschke) [inline core/avatar/avatarcontroller.php]: Can we use `\OCP\IRequest::isUserAgent` instead? 

Something like:
```php
if (\OC::$server->getRequest()->isUserAgent([\OC\AppFramework\Http\Request::USER_AGENT_IE_8]));
```

Would allow us to keep the API smaller :speak_no_evil:

**Comment by PVince81** [comment]
Basically this PR does the following to make IE8 happy:
1) add jquery.iframe-transport for jquery.fileupload, it will use a hidden iframe and POST to it
2) fix response parsing to be able to handle responses coming from the iframe hack
3) make the server set Content-Type to "text/plain" to prevent IE8 to download the JSON body (see http://stackoverflow.com/questions/13295184/jquery-file-upload-plugin-internet-explorer-and-iframe-transport), we had this for files upload too
4) change the input elements to make the user action click it directly (through labels) instead of indirect clicks, see http://stackoverflow.com/a/14886477

File: core/avatar/avatarcontroller.php (hunk 1 above)
Comment (LukasReschke) [inline core/avatar/avatarcontroller.php]: Also makes this actually unit testable

Comment (PVince81) [inline core/avatar/avatarcontroller.php]: Ah cool, I didn't know about that one.

**Comment by PVince81** [comment]
- [ ] TODO: fix IE8 detection

**Comment by MorrisJobke** [comment]
I rebased this on current master and will test it.

**Comment by MorrisJobke** [comment]
Avatar tests:
- [ ] TEST: upload avatar with IE8, with cropping
- [ ] TEST: select avatar from files in IE8, with cropping
- [ ] TEST: upload avatar with Firefox, with cropping
- [ ] TEST: select avatar from files with Firefox, with cropping

Root cert tests:
- [ ] TEST: upload invalid cert file in IE8
- [ ] TEST: upload invalid cert file in Firefox
- [ ] TEST: upload valid cert file in IE8
- [ ] TEST: upload valid cert file in Firefox


I can't test the valid cert upload, because I can't find a "valid" cert. I tried multiple formats and all seem to be "invalid".

Beside that everything looks fine

**Comment by MorrisJobke** [comment]
:+1: from me

**Comment by MorrisJobke** [comment]
> I can't test the valid cert upload, because I can't find a "valid" cert. I tried multiple formats and all seem to be "invalid".

I tested this on current master with Firefox to not run into bugs that occur with this new code.

**Comment by MorrisJobke** [comment]
> I tested this on current master with Firefox to not run into bugs that occur with this new code.
 
If #19602 is merged into this branch also the valid cert uploads work. Here is my final :+1:

**Comment by MorrisJobke** [comment]
> TODO: fix IE8 detection

I will take over this one.

**Comment by MorrisJobke** [comment]
> TODO: fix IE8 detection

Done and tested. All still works.

This is now ready for review :)

**Comment by PVince81** [comment]
:+1: for @MorrisJobke's additions (IE8 detection fix)

**Comment by PVince81** [comment]
Tests fail:
```
OC\Core\Avatar\AvatarControllerTest::testPostAvatarNoPathOrImage
Undefined index: HTTP_USER_AGENT
```

File: settings/controller/certificatecontroller.php [hunk 2]
```diff
@@ -66,19 +66,25 @@ public function __construct($appName,
 	 * @return array
 	 */
 	public function addPersonalRootCertificate() {
+		$headers = [];
+		if (\OC::$server->getRequest()->isUserAgent([\OC\AppFramework\Http\Request::USER_AGENT_IE_8])) {
```
Comment (MorrisJobke) [inline settings/controller/certificatecontroller.php]: @PVince81 we maybe should inject the request :see_no_evil:  then we can mock it

File: core/avatar/avatarcontroller.php [hunk 3]
```diff
@@ -139,12 +139,21 @@ public function postAvatar($path) {
 		$userId = $this->userSession->getUser()->getUID();
 		$files = $this->request->getUploadedFile('files');
 
+		$headers = [];
+		if (\OC::$server->getRequest()->isUserAgent([\OC\AppFramework\Http\Request::USER_AGENT_IE_8])) {
```
Comment (MorrisJobke) [inline core/avatar/avatarcontroller.php]: @PVince81 Same here

**Comment by PVince81** [comment]
Turns out the request object was already available, so just needed to use `$this->request`

**Comment by PVince81** [comment]
Needs re-review @MorrisJobke

**Comment by MorrisJobke** [comment]
Retested everything and all still works. I did a rebase to include the latest fixes for SSL cert upload.

**Comment by MorrisJobke** [comment]
:+1:

File: core/avatar/avatarcontroller.php [hunk 4]
```diff
@@ -179,16 +197,32 @@ public function postAvatar($path) {
...
+				return new DataResponse(
+					['data' => ['message' => $this->l->t('Invalid image')]],
+					Http::STATUS_OK,
+					$headers
+				);
 			}
 		} catch (\Exception $e) {
-			return new DataResponse(['data' => ['message' => $e->getMessage()]]);
+			return new DataResponse(
+				['data' => ['message' => $e->getMessage()]],
```
Comment (LukasReschke) [inline core/avatar/avatarcontroller.php]: Unrelated side remark: I'm not a fan of showing the plain error message. But unrelated :wink:

File: core/js/js.js [hunk 5]
```diff
@@ -85,6 +85,7 @@ var OC={
 	appConfig: window.oc_appconfig || {},
 	theme: window.oc_defaults || {},
 	coreApps:['', 'admin','log','core/search','settings','core','3rdparty'],
+	requestToken: oc_requesttoken,
```
Comment (LukasReschke) [inline core/js/js.js]: That's cool :+1:

**Comment by LukasReschke** [comment]
Rebased it locally on newest master and everything seems to work just fine :+1:
