### PR TITLE
Fix persistent lock retrieval by path

### LINKED ISSUE #33885: Don't apply persistent lock on received declined shares
From https://github.com/owncloud/core/pull/32250#issuecomment-434615887

### Steps

1. as user "sharer" create a folder called "parent" and inside that a folder called "subfolder"
1. from user "sharer" share a folder "parent" with the user "receiver"
1. as user "sharer" set a lock on the folder "parent"
1. as user "receiver" decline the share "parent" from the "Shared with you" page
1. as user "receiver" create a folder called "parent" and inside that a folder called "subfolder"

### Expected result
- the folder "parent/subfolder" of the user "receiver" not locked

### Actual result

- the folder "parent/subfolder" of the user "receiver" will be locked by sharer
- deleting that lock as "receiver" results in Unlock failed with status: 409
- deleting/renaming parent/subfolder" as "receiver" is not possible because its locked

### Version
discovered on https://github.com/owncloud/core/pull/32250

It is likely that whatever checks for locks is retrieving the full list of share mount points and does not filter it by state. Need to check what APIs are used there as there is already an existing way to only get visible mount points.

### PR DESCRIPTION
**Pull request by PVince81**
## Description
- Fix query to make it strictly search in the given storage.
- Fix query to prevent LIKE bleeding into unrelated folders (trailing slash issue).
- Added enforcement of Depth 0 or -1 as per RFC 4918 Section 9.10.3.
- Added many more unit tests to test the query from different angles, making sure that locks from parent and child paths are returned when the correct conditions are met and also not returned when not met.

## Related Issue
Fixes https://github.com/owncloud/core/issues/33885

## How Has This Been Tested?
- [x] Unit test
- [x] Reenable acceptance tests after https://github.com/owncloud/core/pull/32250 is merged

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)
- [x] actually fix the issue

### CODE REVIEW

**Comment by PVince81** [comment]
@DeepDiver1975 please carefully review. I added a lot of comments in the code to clarify the tested scenarios and the SQL query. Seems there were a few more bugs in there which I fixed (see PR description for detail)

File: lib/private/Lock/Persistent/Lock.php [hunk 1]
```diff
@@ -39,6 +39,9 @@
  */
 class Lock extends Entity implements ILock {
 
+	const DEPTH_ZERO = 0;
```
Comment (PVince81) [inline lib/private/Lock/Persistent/Lock.php]: ok seems I missed that this is already on ILock

will change after the first review pass

File: lib/private/Lock/Persistent/LockMapper.php [hunk 2]
```diff
@@ -34,54 +35,117 @@ public function __construct(IDBConnection $db, ITimeFactory $timeFactory) {
...
 					$query->expr()->neq('depth', $query->createPositionalParameter(0)),
-					$query->expr()->eq('path', $query->createPositionalParameter($currentPath))
+					// here we are assuming that the number of path sections will be less than 1000
+					$query->expr()->in('path', $query->createPositionalParameter($parentPaths, IQueryBuilder::PARAM_STR_ARRAY))
 				)
 			);
 		}
 
-		return $this->findEntities($query->getSQL(), $query->getParameters());
+		$query->andWhere($pathMatchClauses);
```
Comment (PVince81) [inline lib/private/Lock/Persistent/LockMapper.php]: I should probably also add "ORDER BY" as some databases will mess up the order and break the tests...

Order by path ?

**Comment by PVince81** [comment]
- [ ] add sort order by path in query
- [ ] fix Lock constants

File: lib/private/Lock/Persistent/LockMapper.php (hunk 2 above)
Comment (PVince81) [reply lib/private/Lock/Persistent/LockMapper.php]: ok, fix the unit test instead

**Comment by PVince81** [comment]
- [ ] check how our endpoint behaves with depth = 1, 500 or 400 ?

**Review by DeepDiver1975 — APPROVED** [review]
Looks good - THX .. adjust remaining topics as discussed .... :+1:

**Comment by PVince81** [comment]
Adjusted. Now hoping Oracle will pass...

**Comment by PVince81** [comment]
acceptance test, something weird:
```
Updating .htaccess for proper rewrites
Could not set mail_domain on https://server/ocs/v2.php/apps/testing/api/v1/occ. Result:
'<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>500</statuscode>
  <message>Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services.</message>
 </meta>
 <data/>
</ocs>'
```

**Comment by PVince81** [comment]
seems the id with Oracle is shifted. it almost looks like the insert id that was returned does not match the actual one returned by subsequent select

**Comment by PVince81** [comment]
now sorting by id instead of fileid, let's see...

**Comment by PVince81** [comment]
maybe the "testing" app did not enable for some reason?? @phil-davis @individual-it

**Comment by phil-davis** [comment]
After PR #33956 has been merged to ``master`` then rebase this and the acceptance test issue will be fixed

**Comment by PVince81** [comment]
Rebased. Fixed Oracle by properly sorting the expected output before asserting...

**Comment by phil-davis** [comment]
> stable10: #33957

Removed backport-request label because backport is done.
