### PR TITLE
always write file, if fseek doesn't work we write the whole file

### LINKED ISSUE #16356: Cannot upload a file to a SMB storage with encryption enabled
### Steps to reproduce
1. Install and enable external storage and encryption
2. Create a new SMB mount in the external storage, with a correct configuration available for all users
3. Upload a file inside the SMB mount (bigger than 1MB)

### Expected behaviour
The file is uploaded correctly in the external storage

### Actual behaviour
Only a part of the file is uploaded. It's being cut at 16kB. Smaller files can be uploaded correctly.

screenshot from 2015-05-14 15 27 12

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 beta 1

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:**
 - encryption: 1.0.0
 - files: 1.1.9
 - files_external: 0.2.3
 - files_locking: 
 - files_sharing: 0.6.1
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5

#### ownCloud log (data/owncloud.log)
```
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u16\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u17\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u18\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u19\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u2\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u20\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u3\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u4\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u5\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u6\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u7\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u8\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u9\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}

{"reqId":"JCsAkBwa3TtV3patra2+","remoteAddr":"10.40.30.21","app":"PHP","message":"imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: \b\n at \/home\/jvillafanez\/src\/owncloud\/owncloud2\/lib\/private\/image.php#512","level":3,"time":"2015-05-14T13:27:01+00:00"}

```

### Notes
I've also checked with the storage only available for the current user in order to prevent the "key not found" logs. Those logs doesn't appear, but the behaviour is the same

### PR DESCRIPTION
**Pull request by schiessle**
fix https://github.com/owncloud/core/issues/16356

@jknockaert please have a look. I have the feeling that this is to simple and fear that I missed something.

The problem is that if we upload a large file to a storage which doesn't support fseek and ftell, which is the case for some ftp storages, we don't get the correct size after the first write. So  $positionInFile will no longer be equal to $this->size and fseek will be false. This means that we will stop writing after the first block.

My assumption: Either we write in the middle of the file and fseek works, or fseek failed because it is not supported by the storage back-end in this case we always write the complete file and we don't need a additional check, which lead us to 

```
if (!($this->readOnly) && ($resultFseek || !$resultFseek || $positionInFile === $this->size)) {
```

which again lead us to 

```
if (!$this->readOnly) {
```

All tests pass with this changes and the issue above is fixed.

### CODE REVIEW

**Comment by jknockaert** [comment]
@schiesbn I will have a look at it. The code is designed to work on nonseekable streams but I never tested it to see if there are any bugs left. The fix you suggest has the drawback that it corrupts nonseekable streams in r+ mode; I will see how to work around that.

**Comment by jknockaert** [comment]
OK; the bug is that I didn't understand that ftell wouldn't work on nonseekable streams. PHP is really poorly documented in this respect. So the bug is in `flush()` at line 415. Is there something else we can call to update the encrypted filesize upon write?

**Comment by jknockaert** [comment]
An alternative would actually be to use the position in the unencrypted stream to check if we're writing at the end of the file (encrypted or not) and use the outcome of that test to update the size of the encrypted stream. But that should be carefully crafted, as in `flush()` you have little information on the context.

**Comment by schiesbn** [comment]
> An alternative would actually be to use the position in the unencrypted stream to check if we're writing at the end of the file

That's a good ideas, we could use the same check as in readCache(): ````$this->position === $this->unencryptedSize````

>  and use the outcome of that test to update the size of the encrypted stream.

Probably we can then even ignore the encrypted size completely. Because then we no longer use it, neither for a read nor for a write operation.

**Comment by jknockaert** [comment]
@schiesbn I am already working on the alternative approach. It's as expected not very straightforward and a bit more complicated than you suggest here, but I'm making progress.

**Comment by schiesbn** [comment]
@jknockaert great... looking forward to it! :smile:

**Comment by jknockaert** [comment]
OK. It'll be in a new PR as I still don't fully understand this github thing.

**Comment by schiesbn** [comment]
@jknockaert you can push your changes directly to this branch, if you want

**Comment by jknockaert** [comment]
OK; I'll see if I manage

**Comment by schiesbn** [comment]
@jknockaert can you explain why we need to calculate the encrypted size if we only need it for the check if we write at the end of a file? Why can't we use the check from readCache() which does the same and doesn't need the encrypted size?

**Comment by jknockaert** [comment]
@schiesbn A call to stream_write does not result in a call to flush when the write does not hit the end of the block; but still it must be able to determine if flush will happen correctly whenever it is called in order to return the correct write result to whatever process is calling stream_write. The encrypted filesize is needed to evaluate the possibility to write on an unseekable stream. But the encrypted filesize can only be determined by flush(), as that is where the encryption happens.

**Comment by jknockaert** [comment]
@schiesbn Maybe to further clarify: we're not merely checking if we are writing at the end of an unseekbale stream, but also if that end corresponds to an entire block.

**Comment by schiesbn** [comment]
Does it metter? Shouldn't be enough to determine if the the next block will be attached to the end of the file or not, no matter if flush() was already called or not?

Anyway, I just tried it with a large picture (~6MB), the file size looks good at the end of the upload but if I try to download the image again it is corrupted.

**Comment by schiesbn** [comment]
> Maybe to further clarify: we're not merely checking if we are writing at the end of an unseekbale stream, but also if that end corresponds to an entire block.

readCache() also check both without the encrypted size: ````$this->position === $this->unencryptedSize && $this->position % $this->unencryptedBlockSize ===  0````

**Comment by jknockaert** [comment]
that readcache() test needs only to work when the pointer is at the beginning of the block; whereas two partial writes to a block should still result in the full block be written upon the second write but then the pointer is not at the beginning of the block

**Comment by jknockaert** [comment]
Give me some more time to reflect on it; I'll give it a second attempt later today.

**Comment by schiesbn** [comment]
OK: Just one update to my test. It seems that it doesn't fail always. I uploaded the file now multiple time and sometimes it fail 3-5 times in a row and then it succeed again 3-5 times in a row.  But I also see some "Segmentation fault" and ftp errors. Maybe this is more a issue of a unreliable connection to the ftp server than to your changes.

**Comment by jknockaert** [comment]
In the case of an unseekable encrypted stream stream_write must know whether it is writing to the last block (for that you do not need to know the encrypted filesize metrics) AND whether that last block has already been partially written to the encrypted stream (here I cannot think of anything other than using the encrypted filesize).

**Comment by jknockaert** [comment]
If there's ftp errors I guess that we're in the process of identifying another bug. We'll not soon end without work that way.

**Comment by jknockaert** [comment]
Any ideas for a unit test?

**Comment by schiesbn** [comment]
We could move the parent::fseek() call to a separate method. This way we could mock the method call to always return false to simulate a non-seekable storage, write a large file and check if we can read it again. Do you want to give it a try?

**Comment by jknockaert** [comment]
Sounds reasonable. We don't even need a large file for that. But I've no idea how to do the move-method thing (that should catch parent::fseek() and parent::ftell()). Could you design a simple test to open in 'w' mode a "nonseekable" file and write 'foobar' to it? I will then extend it with reads/writes to cover the bug fixed in this PR.

**Comment by schiesbn** [comment]
@jknockaert OK, I will prepare a test

**Comment by schiesbn** [comment]
It was not as easy as I thought because you can't instantiate a stream wrapper in advance, so I helped myself with a dummy class.... Not perfect but it works. For now I use the same data provider like testWriteReadBigFile(), feel free to add additional tests files to cover the specific cases you want to test or replace it with a new data provider.

**Comment by jknockaert** [comment]
OK; I'll first wait till Jenkins' opinion on the matter is in.
These nonseekable streams are quite tricky to handle in the context of an asynchronous stream_wrapper. But provided that we support nonseekable streams it is a good idea to have a testing mechanism for them anyway.

**Comment by jknockaert** [comment]
@schiesbn Any idea why that last test fails? It correctly refuses to write in r+ on a nonseekable stream, but then it doesn't read from it. Maybe something in the interaction between fread/fwrite and the stream_wrapper, which is handled by php?

**Comment by schiesbn** [comment]
I run the test through my debugger. I'm not sure what the entire problem is. But the first fread (https://github.com/owncloud/core/commit/07c2ceccb5cb732f910f50e01971bd6eb4cabd85#diff-d9c73b2da669dd1876e468ced7a036b6R307) doesn't read only 3 byte but a complete block (8192 byte) and then PHP "magically" cuts out the first 3 characters ('foo') and return them, so the first assertion is true. If you run the next fread directly after the first one we don't  call the stream_read() method of the stream wrapper again. I assume that PHO still has the complete block in the cache and returns the second 3 chars ('bar'). 

But if we call fwrite in between be break this caching, or whatever happens internally, the data is gone because we already read the whole file and are at the end of the file, so the next fread will return an empty string. I will try to debug this further tomorrow and also compare it with the behavior of a unencrypted stream.

Another think I observed if that we don't calculate $count and $this->position correctly.

This is how we calculate the position: https://github.com/owncloud/core/blob/a0e79f3c3468300a825a0ba8b2d628a2c908ba3b/lib/private/files/stream/encryption.php#L339 But in your test case this means position = 0 + (6126 - 0) = 6126 while the whole file is only 6 byte large, so position should be never larger then 6. A similar error happens here https://github.com/owncloud/core/blob/a0e79f3c3468300a825a0ba8b2d628a2c908ba3b/lib/private/files/stream/encryption.php#L330. A easy fix is to alsways use the min. from this calculation and $this->unencryptedSize, but I'm not yet sure if this will work in all circumstances.

A similar problem we have with the way we calculate $count here: https://github.com/owncloud/core/blob/a0e79f3c3468300a825a0ba8b2d628a2c908ba3b/lib/private/files/stream/encryption.php#L293. As described above in your test case the first fread reads a complete block which is already larger then the file. After the first iteration of the while loop we already read the complete string ('foobar' in this example), but count gets set to 8192 - (6126 - 0) = 2066. So we iterate over the while loop a second time, but we already read the complete file.

I will look  into this in more detail tomorrow. But maybe this information already helps you to come up with a idea how to fix/improve it.

**Comment by jknockaert** [comment]
With reading/writing a file with only 6 bytes it should never get to line 293 or line 339 which are only called when the block is filled. In my test case the read will happen in one pass within the cache of the first block after which the count is set to 0 at line 287. And the write will also happen in one pass (and only manipulating the cache of the first block which is flushed upon closing), and the position will be changed by the length of the write at line 330. I don't think there's a bug in this area.
As for the obscure behaviour of php in manipulating unseekable streams in r+ mode we may decide to disable r+ mode for now. Too bad.

**Comment by schiesbn** [comment]
> When reading/writing a file with only 6 bytes it should never get to line 293 or line 339 which are only called when the block is filled. In my test case the read will happen in one pass within the cache of the first block after which the count is set to 0 at line 287.

Doesn't happen here. Because as explained above stream_read() will be called with $count = 8129 (also for  fread($stream, 3)), so https://github.com/owncloud/core/blob/a0e79f3c3468300a825a0ba8b2d628a2c908ba3b/lib/private/files/stream/encryption.php#L327 will be false (````(8129 < (6126 - 0)) ````) and we will execute the else statement. I would be really surprised if on your system $count, $remainingLength, $this->unencryptedBlockSize and $blockPosition have a different value than on my system.

**Comment by schiesbn** [comment]
See also this discussion about stream_read and why $count is always 8129: https://bugs.php.net/bug.php?id=21641

**Comment by jknockaert** [comment]
So I fixed the count thing and multiplied the testing to find what drives the failed one. I am still inclined to think this to be a bug in php where after a failed write it declines to read (although according to the documentation it should return FALSE when fread doesn't work).

**Comment by schiesbn** [comment]
@jknockaert count seems to be correct now, great!

Redarding the other issue: I also tried to return directly false (and 0) at the top of stream_write() for the write operation between the two fread operation. But it still fails. It seems like as soon as another stream operation is called between the first and the second fread() we lose the remaining data in the cache and PHP can no longer return the right value.

Another indicator is that if I remove the fwrite() between the first fread() the second fread(), the second freas() will not call the stream_read() method of the wrapper. But if we do a fwrite() in between the second fread() will call the stream_read() wrapper again which indicates that the internal caching from PHP is gone. Maybe we could do some cache in our stream wrapper class to return the right value on the second fread()? But probably not that easy to do it in a way that it works in this special case without breaking in other situations.

**Comment by schiesbn** [comment]
Maybe for now we should forbid all '+' operations (r+, w+, a+, x+, c+). We don't use them anyway in ownCloud and I don't see a way to make them work with the stream wrapper in all circumstances.

@DeepDiver1975 Do you see any reasons why we can't block this operations for encryption?

**Comment by jknockaert** [comment]
According to the php doc stream_write should not return FALSE but just 0. fread itself may return 0 or FALSE (I fail to see the difference between a failed write or a zero-length write). The fread operation actually works correctly (nothing gets written as it is in the middle of a nonseekable stream). But the subsequent read fails. We technically could try to program around this bug, but accommodating for undocumented behaviour is very tricky. The encryption wrapper is definitely not designed for this purpose; there's already enough complex logic to make the different parts work together.
Honestly the only way I see for now is disable r+ mode. W+ will still be fine, as you start with an empty file and cannot move the pointer back on a non-seekable stream (w+ effectively behaves as w with a nonseekable stream).
As far as I know r+ mode is not used currently in owncloud. But I designed the wrapper to work in that mode as I expected that support for r+ mode has quite some potential in the context of apps like the text editor.

**Comment by schiesbn** [comment]
I would suggest to split this PR up into two:

1. For this PR we keep this commits:
https://github.com/owncloud/core/commit/b93fd5b15c2452d6d16396afcb3597a420c625f5
https://github.com/owncloud/core/commit/087b48abcfb124fe1c32aaaa76f0850db9b86bc8
https://github.com/owncloud/core/commit/7cc5993e69cc9c2ee7f879d29f42bf39f1fb03f2
https://github.com/owncloud/core/commit/a0e79f3c3468300a825a0ba8b2d628a2c908ba3b

This fixes the initial issue #16356

Then we create a second pr where we block fopen with 'r+', throw a exception and write a error log.

@jknockaert If you agree I would clean up this PR and maybe you can prepare the second one. What do you think?

**Comment by jknockaert** [comment]
@schiesbn Agree on cleaning up this one like you set out.
Blocking r+ should not happen at the level of encryption wrapper in my opinion, but rather elsewhere in a place that controls file access (not sure where). We should avoid a situation where someone develops some code using r+ mode and then someone files a bug that it doesn't work with encryption enabled.

**Comment by jknockaert** [comment]
maybe you should also enable the count-fixing line on top of the commits you suggest

**Comment by schiesbn** [comment]
Yes, I will add this, thanks for mentioning.

**Comment by schiesbn** [comment]
cleaned up and ready to review

**Comment by PVince81** [comment]
Tested by @jvillafanez https://github.com/owncloud/core/issues/16356#issuecomment-104611003 , counting as :+1:

File: lib/private/files/stream/encryption.php [hunk 1]
```diff
@@ -412,7 +414,14 @@ protected function flush() {
 			$encrypted = $this->encryptionModule->encrypt($this->cache);
 			parent::stream_write($encrypted);
 			$this->writeFlag = false;
-			$this->size = max($this->size, parent::stream_tell());
+			// If the write concerns the last block then then update the encrypted filesize
+			// Note that the unencrypted pointer and filesize are NOT yet updated when flush() is called
+			// We recalculate the encrypted filesize as we do not know the context of calling flush()
+			if ((int)floor($this->unencryptedSize/$this->unencryptedBlockSize) === (int)floor($this->position/$this->unencryptedBlockSize)) {
```
Comment (PVince81) [inline lib/private/files/stream/encryption.php]: From my experience (at least with game development), it is usually not a good idea to use too many divisions as they can be slow when run in a loop.
I see you're doing the same division twice, can you cache the result ?

Comment (PVince81) [inline lib/private/files/stream/encryption.php]: The comment doesn't seem to be clear about what this division checks is about, is it about detecting whether we are in the last block ? (please update the comment to make it clearer then)

Comment (PVince81) [inline lib/private/files/stream/encryption.php]: Doesn't stream_write() tell you how many bytes were written ? You could do `$this->position += bytesWritten` to find the current position ? (I might be completely misunderstanding what this is about, sorry)

File: lib/private/files/stream/encryption.php [hunk 2]
```diff
@@ -412,7 +414,14 @@ protected function flush() {
...
+				$this->size = $this->util->getBlockSize() * (int)floor($this->unencryptedSize/$this->unencryptedBlockSize);
+				$this->size += strlen($encrypted);
```
Comment (PVince81) [inline lib/private/files/stream/encryption.php]: Since strlen can be slow, maybe we could use the result from `stream_write` here too ? (if that's the correct value)

**Comment by jknockaert** [comment]
@PVince81 Thank you for your comments. I reworked the code along the lines you suggested.

**Comment by PVince81** [comment]
Thanks a lot @jknockaert

**Comment by schiesbn** [comment]
@jknockaert I squashed the last two commits to one commit. Otherwise it looks good to me... @PVince81 do you want to review it?

**Comment by PVince81** [comment]
Works with vsftpd :+1: 
Still works with SFTP (which supports seeking)

**Comment by jknockaert** [comment]
I guess this one can be merged now and after that close #16356

**Comment by PVince81** [comment]
@schiesbn second thumbs up for the latest changes ?

**Comment by schiesbn** [comment]
great work, thanks @jknockaert  :+1:
