### PR TITLE
Properly expire ext storage versions

### LINKED ISSUE #24161: Versions on external storage never expire
### Steps
1. Mount an external storage (ex: SMB) as "/smb" system-wide, apply to all users
2. Login as any user
3. Create a file "/smb/test.txt"
4. Edit the file and save many times to create 10-20 versions
5. Check the version files for that user: `find data/user1 -iname \*.v\*`
6. `update oc_jobs set last_run=0`
7. Run cron.php
### Expected result

Some version expired
### Actual result

No versions expired.
### Versions

ownCloud 9.0.1

The reason is because the `expire()` method calls `getUidAndFilename` and the external storage has no owner, so it bails out with `NoUserException` without doing any expiration.

According to @schiesbn, versions on system-wide ext storage are always specific to the current user viewing the folder. So the correct logic would be to make it fallback to the user that was specified in the expire job.

CC @nickvergessen @VicDeo

### PR DESCRIPTION
**Pull request by PVince81**
## Description
System-wide external storages have no real owner so the current user is
used as owner. However when running cron.php there is no current user,
so no expiry can be done.

This fix adds an user argument to the expire() function to tell for
which user to expire files. This information is anyway always available
now through the expire command job.

## Related Issue
Fixes https://github.com/owncloud/core/issues/24161

## How Has This Been Tested?
See ticket for details
- [x] TEST: versions on ext storage are expired properly
- [x] TEST: versions on regular storage are expired properly
- [x] TEST: versions expired properly when file was edited from share recipient

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### Backports
- [ ] stable9.1
- [ ] stable9

Please review @VicDeo @jvillafanez @DeepDiver1975

### CODE REVIEW

File: apps/files_versions/lib/Command/Expire.php [hunk 1]
```diff
@@ -58,7 +58,7 @@ public function handle() {
 		}
 
 		\OC_Util::setupFS($this->user);
-		Storage::expire($this->fileName);
+		Storage::expire($this->fileName, $this->user);
```
Comment (jvillafanez) [inline apps/files_versions/lib/Command/Expire.php]: I find weird that you have to setup the FS for a user and then provide the same user to expire the versions. One of those shouldn't be needed from my point of view.
With the new code it's possible to setup the FS for one sure and expire versions for other... not from the command, but from other parts of the code.

Comment (PVince81) [inline apps/files_versions/lib/Command/Expire.php]: I prefer this explicit way. If we don't it means we need to find out who is the user that was currently set up and extract the name from the mount point paths... super-ugly.

Or would you prefer if we moved the setupFS into the expire function instead ?

Comment (jvillafanez) [inline apps/files_versions/lib/Command/Expire.php]: As long as we make clear that the "expire" function will unset the previous FS and set the new one, I think it's fine. It's acceptable from my point of view.

I don't know if it's being used outside of the CLI though.

Comment (PVince81) [inline apps/files_versions/lib/Command/Expire.php]: Ok, now I moved `setupFS` into the expire function.

I also removed `tearDownFS` because recently we added automatic tear down between background jobs (which is the other usage outside of CLI)

**Comment by PVince81** [comment]
@jvillafanez second review ?

File: apps/files_versions/lib/Storage.php [hunk 2]
```diff
@@ -683,28 +683,34 @@ private static function scheduleExpire($uid, $fileName) {
...
+
 		if($config->getSystemValue('files_versions', Storage::DEFAULTENABLED)=='true' && $expiration->isEnabled()) {
+			// get available disk space for user
+			$user = \OC::$server->getUserManager()->get($uid);
+			if (is_null($user)) {
+				\OCP\Util::writeLog('files_versions', 'Backends provided no user object for ' . $uid, \OCP\Util::ERROR);
+				throw new \OC\User\NoUserException('Backends provided no user object for ' . $uid);
+			}
+
+			\OC_Util::setupFS($uid);
```
Comment (jvillafanez) [inline apps/files_versions/lib/Storage.php]: Shouldn't we tearDown the FS first? What happens if there is another FS already set up?

If the method won't re-set the previous FS after finishing the operation (which might be fine), then we should document this properly. Other users might consider that after this function is called, the FS would be the same, which isn't true right now.

Comment (PVince81) [inline apps/files_versions/lib/Storage.php]: In general calling `setupFS` with the same user will do nothing. And calling it with another user will just add that user's FS to the existing mount points, making the new mount points available as well. This is done for sharing for example.

I don't think we should tear down here at all, especially considering that this isn't used anywhere else and is private API anyway.

This whole setupFS/tearDown FS needs to be redesigned from the ground up...

Comment (jvillafanez) [inline apps/files_versions/lib/Storage.php]: Ok, but let's write that in the docs in order to make clear what is the expected behaviour for the function.

**Comment by PVince81** [comment]
@jvillafanez done https://github.com/owncloud/core/pull/26601/commits/e71b59fd4a3e71c4c1a35cb60de89a80a4d06689

**Comment by jvillafanez** [comment]
👍

**Comment by PVince81** [comment]
stable9.1: https://github.com/owncloud/core/pull/26681

**Comment by PVince81** [comment]
stable9: https://github.com/owncloud/core/pull/26682
