### PR TITLE
[Tests-Only] Added check for special characters in username while creating a user

### LINKED ISSUE #37380: Acceptance test createUser fails to create users with special characters
For example, edit `tests/acceptance/features/apiShareOperations/uploadToShare.feature:7` so it creates and shares with user `abc.def`
```
make test-acceptance-api BEHAT_FEATURE=tests/acceptance/features/apiShareOperations/uploadToShare.feature:7
Running apiShareOperations tests tagged ~@skipOnOcV10&&~@skipOnOcV10.5&&~@skipOnOcV10.5.0&&@api&&~@skip 
@api @TestAlsoOnExternalUserBackend @files_sharing-app-required @skipOnOcis @issue-ocis-reva-11
Feature: sharing

  Background:                                                                      # /home/phil/git/owncloud/core/tests/acceptance/features/apiShareOperations/uploadToShare.feature:4
    Given user "user0" has been created with default attributes and skeleton files # FeatureContext::userHasBeenCreatedWithDefaultAttributes()

  Scenario: Uploading file to a user read-only share folder does not work                                            # /home/phil/git/owncloud/core/tests/acceptance/features/apiShareOperations/uploadToShare.feature:7
    Given user "abc.def" has been created with default attributes and skeleton files                                 # FeatureContext::userHasBeenCreatedWithDefaultAttributes()
    And user "user0" has created a share with settings                                                               # FeatureContext::userHasCreatedAShareWithSettings()
      | path        | FOLDER  |
      | shareType   | user    |
      | permissions | read    |
      | shareWith   | abc.def |
    When user "abc.def" uploads file "filesForUpload/textfile.txt" to "FOLDER (2)/textfile.txt" using the WebDAV API # FeatureContext::userUploadsAFileTo()
    Then the HTTP status code should be "403"                                                                        # FeatureContext::thenTheHTTPStatusCodeShouldBe()

1 scenario (1 passed)
5 steps (5 passed)
```

Now edit the scenario so it creates and shares with user `abc@def` :
```
make test-acceptance-api BEHAT_FEATURE=tests/acceptance/features/apiShareOperations/uploadToShare.feature:7
Running apiShareOperations tests tagged ~@skipOnOcV10&&~@skipOnOcV10.5&&~@skipOnOcV10.5.0&&@api&&~@skip 
@api @TestAlsoOnExternalUserBackend @files_sharing-app-required @skipOnOcis @issue-ocis-reva-11
Feature: sharing

  Background:                                                                      # /home/phil/git/owncloud/core/tests/acceptance/features/apiShareOperations/uploadToShare.feature:4
    Given user "user0" has been created with default attributes and skeleton files # FeatureContext::userHasBeenCreatedWithDefaultAttributes()

  Scenario: Uploading file to a user read-only share folder does not work                                            # /home/phil/git/owncloud/core/tests/acceptance/features/apiShareOperations/uploadToShare.feature:7
    Given user "abc@def" has been created with default attributes and skeleton files                                 # FeatureContext::userHasBeenCreatedWithDefaultAttributes()
      Provisioning::createUser could not create user. 400 <?xml version="1.0"?>
      <ocs>
       <meta>
        <status>failure</status>
        <statuscode>400</statuscode>
        <message/>
       </meta>
       <data/>
      </ocs>
       (Exception)
    And user "user0" has created a share with settings                                                               # FeatureContext::userHasCreatedAShareWithSettings()
      | path        | FOLDER  |
      | shareType   | user    |
      | permissions | read    |
      | shareWith   | abc@def |
    When user "abc@def" uploads file "filesForUpload/textfile.txt" to "FOLDER (2)/textfile.txt" using the WebDAV API # FeatureContext::userUploadsAFileTo()
    Then the HTTP status code should be "403"                                                                        # FeatureContext::thenTheHTTPStatusCodeShouldBe()

--- Failed scenarios:

    /home/phil/git/owncloud/core/tests/acceptance/features/apiShareOperations/uploadToShare.feature:7

1 scenario (1 failed)
5 steps (1 passed, 1 failed, 3 skipped)
```

The following special characters seem to work OK:
`+` `-` `_` `.` numbers

These are not working:
`@`, space (I think that the space char is allowed in a username (UID) - e.g. `John Smith`)

Need to sort out where this goes wrong in the `createUser` accceptance test code.

space,

### PR DESCRIPTION
**Pull request by kiranparajuli589**
## Description
Inside acceptance tests, while creating user, provided username is used to generate fake email of a username. During the process, special characters like `@`,  ` ` are conflicting characters to be a valid email address. 
This PR adds a conditional logic to check provided username and remove such charactes if found present! 

## Related Issue

- Fixes https://github.com/owncloud/core/issues/37380

## How Has This Been Tested?

- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

File: tests/acceptance/features/bootstrap/Provisioning.php [hunk 1]
```diff
@@ -2096,7 +2096,8 @@ public function createUser(
 			$email = $this->getEmailAddressForUser($user);
 
 			if ($email === null) {
-				$email = $user . '@owncloud.org';
+				# escape @ & space if present in userId
```
Comment (kiranparajuli589) [inline tests/acceptance/features/bootstrap/Provisioning.php:2099]:
```suggestion
				// escape @ & space if present in userId
```

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Works with usernames with space:
```
make test-acceptance-api BEHAT_FEATURE=tests/acceptance/features/apiShareOperations/uploadToShare.feature:7
Running apiShareOperations tests tagged ~@skipOnOcV10&&~@skipOnOcV10.5&&~@skipOnOcV10.5.0&&@api&&~@skip 
@api @TestAlsoOnExternalUserBackend @files_sharing-app-required @skipOnOcis @issue-ocis-reva-11
Feature: sharing

  Background:                                                                      # /home/phil/git/owncloud/core/tests/acceptance/features/apiShareOperations/uploadToShare.feature:4
    Given user "user0" has been created with default attributes and skeleton files # FeatureContext::userHasBeenCreatedWithDefaultAttributes()

  Scenario: Uploading file to a user read-only share folder does not work                                            # /home/phil/git/owncloud/core/tests/acceptance/features/apiShareOperations/uploadToShare.feature:7
    Given user "abc def" has been created with default attributes and skeleton files                                 # FeatureContext::userHasBeenCreatedWithDefaultAttributes()
    And user "user0" has created a share with settings                                                               # FeatureContext::userHasCreatedAShareWithSettings()
      | path        | FOLDER  |
      | shareType   | user    |
      | permissions | read    |
      | shareWith   | abc def |
    When user "abc def" uploads file "filesForUpload/textfile.txt" to "FOLDER (2)/textfile.txt" using the WebDAV API # FeatureContext::userUploadsAFileTo()
    Then the HTTP status code should be "403"                                                                        # FeatureContext::thenTheHTTPStatusCodeShouldBe()

1 scenario (1 passed)
5 steps (5 passed)
```
And with `@`:
```
make test-acceptance-api BEHAT_FEATURE=tests/acceptance/features/apiShareOperations/uploadToShare.feature:7
Running apiShareOperations tests tagged ~@skipOnOcV10&&~@skipOnOcV10.5&&~@skipOnOcV10.5.0&&@api&&~@skip 
@api @TestAlsoOnExternalUserBackend @files_sharing-app-required @skipOnOcis @issue-ocis-reva-11
Feature: sharing

  Background:                                                                      # /home/phil/git/owncloud/core/tests/acceptance/features/apiShareOperations/uploadToShare.feature:4
    Given user "user0" has been created with default attributes and skeleton files # FeatureContext::userHasBeenCreatedWithDefaultAttributes()

  Scenario: Uploading file to a user read-only share folder does not work                                            # /home/phil/git/owncloud/core/tests/acceptance/features/apiShareOperations/uploadToShare.feature:7
    Given user "abc@def" has been created with default attributes and skeleton files                                 # FeatureContext::userHasBeenCreatedWithDefaultAttributes()
    And user "user0" has created a share with settings                                                               # FeatureContext::userHasCreatedAShareWithSettings()
      | path        | FOLDER  |
      | shareType   | user    |
      | permissions | read    |
      | shareWith   | abc@def |
    When user "abc@def" uploads file "filesForUpload/textfile.txt" to "FOLDER (2)/textfile.txt" using the WebDAV API # FeatureContext::userUploadsAFileTo()
    Then the HTTP status code should be "403"                                                                        # FeatureContext::thenTheHTTPStatusCodeShouldBe()

1 scenario (1 passed)
5 steps (5 passed)
```
