### PR TITLE
Remember previous state of remember login checkbox

### LINKED ISSUE #22205: »Stay logged in« checkbox resets to unchecked when wrong password was put in
1. Put in credentials, check the »Stay logged in« checkbox
2. If the credentials are wrong, the site is reloaded with the »Forgot password« etc message

Expected: The checkbox for »Stay logged in« is in the same state as before, in this case checked.

What actually happens: It always resets to being unchecked.

cc @owncloud/javascript

### PR DESCRIPTION
**Pull request by vincchan**
fixes #22205

### CODE REVIEW

File: core/templates/login.php [hunk 1]
```diff
@@ -68,7 +68,12 @@
 		<?php if ($_['rememberLoginAllowed'] === true) : ?>
 		<div class="remember-login-container">
 			<input type="checkbox" name="remember_login" value="1" id="remember_login" class="checkbox checkbox--white">
-			<label for="remember_login"><?php p($l->t('Stay logged in')); ?></label>
+			<?php if ($_POST['remember_login'] !== '1') { ?>
```
Comment (LukasReschke) [inline core/templates/login.php]: There is a little PHP annoyance here that would break here. If you use `$_POST` (or one of the other superglobals) on an not existing key this will throw an error in the error log:

> ➜  master git:(remember-login-state) ✗ tail -f data/owncloud.log
> {"reqId":"0z0JSUoucxFosykwVUj+","remoteAddr":"::1","app":"PHP","message":"Undefined index: remember_login at \/Users\/lukasreschke\/Documents\/Programming\/master\/core\/templates\/login.php#71","level":3,"time":"2016-02-10T11:50:06+00:00"}

To fix this we usually use a ternary operator like `isset($_POST['remember_login']) ? $_POST['remember_login'] : 0`. Also it would make sense to move this piece into [`\OC_Util::displayLoginPage`](https://github.com/owncloud/core/blob/9a2c517ca8eaf25bf142696e1479355112b1f108/lib/private/util.php#L939-L974) to move it out of the template. Something like:

`$parameters['rememberLoginState'] = isset($_POST['remember_login']) ? $_POST['remember_login'] : 0;` 

You can then access this in this template using `$_['rememberLoginState']`.

Comment (LukasReschke) [inline core/templates/login.php]: But besides my comment: :rocket: :smile:

Comment (blizzz) [inline core/templates/login.php]: why don't you set checked="checked" on the checkbox directly instead of doing the roundtrip with the attribute?

Comment (vincchan) [inline core/templates/login.php]: @blizzz Yeah, you are right. I don't know what went through my head. I'm gonna fix that :)

**Comment by vincchan** [comment]
@LukasReschke @blizzz 

Thanks for the input, please have another look :)

**Comment by blizzz** [comment]
looks good and works :+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by LukasReschke** [comment]
Thanks again @vincchan for the contribution :rocket: :beers:

**Comment by jancborchardt** [comment]
Nice @vincchan, thanks for fixing the issue! :)
