### PR TITLE
In case of exception we return an html page in case the client is a b…

### LINKED ISSUE #23500: Error page is missing, just a xml appear.
### Steps to reproduce

1. Recreate an error situation, for example try to access to encrypted files without encryption app enabled, or make firewall (EE) block access from a specific user agent and access using that user agent.

### Expected behaviour
Error page appears.

### Actual behaviour
An xml is returned.

Example while trying to open an encrypted file without encryption enabled:
screen shot 2016-03-23 at 09 14 50

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"9.0.1.0","versionstring":"9.0.1 beta","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**

```
{"reqId":"0V0fSwdCSmGNacysgO7n","remoteAddr":"HIDDEN_IP","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Encryption not ready: Module with id: OC_DEFAULT_MODULE does not exist.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(83): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/opt\\\/owncloud\\\/remote.php(138): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#7 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php\",\"Line\":311,\"User\":\"admin\"}","level":4,"time":"2016-03-23T08:25:59+00:00"}
```

### Client configuration

**browser**
Chrome

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…rowser

@PVince81 @LukasReschke the plugin approach to fix #23500

### CODE REVIEW

File: apps/dav/lib/files/browsererrorpageplugin.php [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+
+	/**
+	 * @param IRequest $request
+	 * @return bool
+	 */
+	public static function isBrowserRequest(IRequest $request) {
+		if ($request->getMethod() !== 'GET') {
+			return false;
+		}
+		return $request->isUserAgent([Request::USER_AGENT_IE_8]);
```
Comment (DeepDiver1975) [inline apps/dav/lib/files/browsererrorpageplugin.php]: @LukasReschke this is where I need all the mighty regex :see_no_evil:

Comment (LukasReschke) [inline apps/dav/lib/files/browsererrorpageplugin.php]: :godmode:

Comment (DeepDiver1975) [inline apps/dav/lib/files/browsererrorpageplugin.php]: :bow:

Comment (PVince81) [inline apps/dav/lib/files/browsererrorpageplugin.php]: In 9.0 we don't support IE8 any more :fire: 
Only IE >= 9
See https://github.com/owncloud/core/issues/15567#issuecomment-166754301

**Comment by PVince81** [comment]
Wow, nicely done!

**Comment by PVince81** [comment]
```
  % curl -D - -X GET http://admin:admin@localhost/owncloud/remote.php/webdav/unexist.txt
HTTP/1.1 404 Not Found
Date: Thu, 24 Mar 2016 13:53:17 GMT
Server: Apache/2.4.18 (Linux/SUSE)
X-Powered-By: PHP/5.6.17
Set-Cookie: ockbfur1449k=f7fmc1arrtqi598dllgfb6l366n7pie51e9pbuil3bakk7jgc2t0; path=/owncloud; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=8llD2Q0WIFsVE%2BR2B4jwmE1lPUe3xjCeIpUaDf09EryVbncZvLtT0iUZogjAOWTr%2BlRfMRLfo2sbYGrU7juCQZcBE%2Fuj%2BErg0nxXTa1Ewq3VgWaAGkC7j98iNOmlHrCf; path=/owncloud; httponly
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Robots-Tag: none
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Set-Cookie: ockbfur1449k=ho2b75ldlig380825usce0o5o207mrpd6ndja1k6fueln2iqlv40; path=/owncloud; HttpOnly
Content-Length: 239
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File with name unexist.txt could not be located</s:message>
</d:error>
```

Browser doesn't display a page:
webdav-error-unexist

**Comment by PVince81** [comment]
Haha, maybe another trick would be to produce a XSLT file with style information ? :stuck_out_tongue:

**Comment by PVince81** [comment]
`isBrowserRequest` is **always** false ??

**Comment by LukasReschke** [comment]
> Browser doesn't display a page:

https://github.com/owncloud/core/pull/23557#discussion_r57315852

… I'm still writing that magical Regex :wink: …

**Comment by DeepDiver1975** [comment]
> Browser doesn't display a page:

@LukasReschke has to add his :godmode: regex - sorry - I was adding the 'to review' label too early

File: apps/dav/lib/files/browsererrorpageplugin.php (hunk 1 above)
Comment (LukasReschke) [inline apps/dav/lib/files/browsererrorpageplugin.php]: https://github.com/owncloud/core/pull/23557/commits/09af2bd15945554d380511e5fbdd390c1487e34d

File: lib/private/template.php [hunk 2]
```diff
@@ -333,7 +333,7 @@ public static function printErrorPage( $error_msg, $hint = '' ) {
 	 * print error page using Exception details
 	 * @param Exception $exception
 	 */
-	public static function printExceptionErrorPage($exception) {
+	public static function printExceptionErrorPage($exception, $fetchPage = false) {
```
Comment (LukasReschke) [inline lib/private/template.php]: PHPDoc :wink:

File: apps/dav/lib/files/browsererrorpageplugin.php [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+	public static function isBrowserRequest(IRequest $request) {
+		if ($request->getMethod() !== 'GET') {
+			return false;
+		}
+		return $request->isUserAgent([
+			Request::USER_AGENT_IE,
+			Request::USER_AGENT_MS_EDGE,
+			Request::USER_AGENT_CHROME,
+			Request::USER_AGENT_FIREFOX,
+			Request::USER_AGENT_SAFARI,
```
Comment (PVince81) [inline apps/dav/lib/files/browsererrorpageplugin.php]: Too bad we can't just rely on "Accept" headers

Comment (LukasReschke) [inline apps/dav/lib/files/browsererrorpageplugin.php]: Yep. Clients are fun :see_no_evil:

Once we have tokens this will be easy though since we know where the token belongs to.

**Comment by PVince81** [comment]
We're almost there. The page says "Internal Server Error".
Can we make it display the actual error ? Like "File not found" for a 404 ?

**Comment by DeepDiver1975** [comment]
> We're almost there. The page says "Internal Server Error".
> Can we make it display the actual error ? Like "File not found" for a 404 ?

how are you triggering the error?

**Comment by PVince81** [comment]
See https://github.com/owncloud/core/pull/23557#issuecomment-200846191

It has the Webdav download link with a non-existing file.

**Comment by PVince81** [comment]
Just open "http://localhost/owncloud/remote.php/webdav/unexist.txt" in Chromium 48 (after being logged in)

**Comment by DeepDiver1975** [comment]
Okay - the real http status code is 404 and the explicit exception message is listed as well.

I simply used out exception error page which always prints 'internal server error'

**Comment by PVince81** [comment]
It's not listed in my case:
chrome-error

**Comment by DeepDiver1975** [comment]
> It's not listed in my case:

ah - yes - the excption details are only displayed in debug mode.

What was the behavior with the ajax download? Which page did we display there?

**Comment by PVince81** [comment]
It used to look like this in 8.2 with ajax download:
chrome-old-error

**Comment by DeepDiver1975** [comment]
I see it explicitly renders the 404 template ....

**Comment by DeepDiver1975** [comment]
I'm also getting a permanent reload loop here - due to NotAuthenticated

**Comment by DeepDiver1975** [comment]
Okay - special 404 template added - any other cases we want to handle different?

**Comment by PVince81** [comment]
403 in case it's blocked by the firewall or the file could not be decrypted, 423 if the file is locked.

Do these have to be handled one by one ?

**Comment by PVince81** [comment]
Let me have a quick test with encryption

**Comment by PVince81** [comment]
Tried with encryption and on stable8.2 the download runs forever... no page displayed :frowning: 
On this branch no page, but Chromium shows its own "Invalid request" page.
I guess the "DecryptionFailedException" was never caught properly.

**Comment by PVince81** [comment]
I thought we could just take whatever status code we have + exception name + exception description (if any) from the XML and display it as is in a page. But not "Internal Server Error".

**Comment by PVince81** [comment]
Firewall blocking also shows "Internal Server Error" instead of "Forbidden" on this PR.

**Comment by DeepDiver1975** [comment]
> I thought we could just take whatever status code we have + exception name + exception description (if any) from the XML and display it as is in a page. But not "Internal Server Error".

I'll take care of that ....

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2016-03-24 17-50-17

**Comment by PVince81** [comment]
webdav-firewall

Looks great :+1:

**Comment by DeepDiver1975** [comment]
let me squash that stuff a bit and then we can merge

@karlitschek do we want to backport this?

**Comment by karlitschek** [comment]
agreed. please backport :+1

**Comment by DeepDiver1975** [comment]
> agreed. please backport :+1

THX - here we go https://github.com/owncloud/core/pull/23574
