### PR TITLE
Don't send password notification email if null

### LINKED ISSUE #27654: Exceptions raise when changing user password and no email was configured
### Steps to reproduce

1. As a regular user go to settings and to personal/general.
2. Try to change password.

### Expected behaviour
You change the password and the ui says it has been changed correctly.

### Actual behaviour
It changes the password, but feels like blocked. Checking dev tools we can see a 500 error.

### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
current master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.0.6","versionstring":"10.0.0 beta2","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

```
{"reqId":"JHtaxm7gq3AjGhPSQyXs","level":3,"time":"2017-04-18T12:05:30+00:00","remoteAddr":"HIDDEN_IP","user":"grant","app":"PHP","method":"POST","url":"\/index.php\/settings\/personal\/changepassword","message":"Undefined offset: 1 at \/opt\/owncloud\/lib\/private\/Mail\/Message.php#59"}
{"reqId":"JHtaxm7gq3AjGhPSQyXs","level":3,"time":"2017-04-18T12:05:30+00:00","remoteAddr":"HIDDEN_IP","user":"grant","app":"index","method":"POST","url":"\/index.php\/settings\/personal\/changepassword","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Couldn't send reset email. Please contact your administrator.\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/settings\\\/ChangePassword\\\/Controller.php(58): OC\\\\Settings\\\\ChangePassword\\\\Controller::sendNotificationMail('grant')\\n#1 [internal function]: OC\\\\Settings\\\\ChangePassword\\\\Controller::changePersonalPassword(Array)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Array, Array)\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/base.php(910): OC\\\\Route\\\\Router->match('\\\/settings\\\/perso...')\\n#4 \\\/opt\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#5 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/settings\\\/ChangePassword\\\/Controller.php\",\"Line\":193}"}
```
### Client configuration

**Browser**
Chrome

**Logs**
```
jquery.js:8630 POST http://HIDDEN_HOST/index.php/settings/personal/changepassword 500 (Internal Server Error)
send	@	jquery.js:8630
ajax	@	jquery.js:8166
n.(anonymous function)	@	jquery.js:8311
(anonymous)	@	profile.js?v=9949793…:178
dispatch	@	jquery.js:4435
r.handle	@	jquery.js:4121
```

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/27654

- [x] TEST: admin can change password of user who has no email
- [x] TEST: user can change own password when no email set

@SergioBertolinSG @jvillafanez please review

### CODE REVIEW

**Comment by jvillafanez** [comment]
👍

File: settings/ChangePassword/Controller.php [hunk 1]
```diff
@@ -178,7 +178,7 @@ private static function sendNotificationMail($username) {
 		$mailer = \OC::$server->getMailer();
 		$lion = \OC::$server->getL10N('lib');
 
-		if ($email !== '') {
+		if ($email !== null && $email !== '') {
```
Comment (IljaN) [inline settings/ChangePassword/Controller.php]: Use !empty() ?

Comment (PVince81) [inline settings/ChangePassword/Controller.php]: I'll never use empty again in PHP with strings because `empty("0")` is true

Comment (IljaN) [inline settings/ChangePassword/Controller.php]: I think it adds a lot to readability and a email shouldn`t be "0" anyways. But you are correct from a defensive programming point of view :)

Comment (PVince81) [inline settings/ChangePassword/Controller.php]: yep, see https://github.com/owncloud/core/issues/22522 ...
