### PR TITLE
Lock zip content

### LINKED ISSUE #16960: Download directory as zip while an inner file is being overwritten causes the download to be corrupted
### Steps to reproduce
1. Create a folder and upload several files on it
2. Overwrite one of those files with a big one
3. While the file is being uploaded / overwritten, download the parent folder as a zip

### Expected behaviour
A locked exception should be thrown

### Actual behaviour
A corrupted zip file is downloaded.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 8.1 beta 2 (daily) Build:2015-06-12T03:13:02+00:00 cda9685c0ece25fe99a8046a94f06f145191a09d 

**Updated from an older ownCloud or fresh install:** fresh install

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes https://github.com/owncloud/core/issues/16960

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

File: lib/private/files.php [hunk 1]
```diff
@@ -166,6 +176,16 @@ public static function get($dir, $files, $onlyHeader = false) {
 			if ($getType === self::FILE) {
 				$view->unlockFile($filename, ILockingProvider::LOCK_SHARED);
 			}
+			if ($getType === self::ZIP_FILES) {
+				foreach ($files as $file) {
+					$file = $dir . '/' . $file;
+					$view->unlockFile($file, ILockingProvider::LOCK_SHARED);
```
Comment (PVince81) [inline lib/private/files.php]: a possible improvement would be to call `unlockFile` as soon as the file was added to the Zip to avoid keeping it locked until the complete end of the Zip building operation. :smile:

Comment (DeepDiver1975) [inline lib/private/files.php]: So that we only lock it during streaming of that single file? Hmmm ... maybe

**Comment by DeepDiver1975** [comment]
Anyway - I hat that code - needs proper structuring ....

**Comment by DeepDiver1975** [comment]
> Anyway - I hate that code - needs proper structuring ....

Bääh .... is it really worth the effort? Especially the exception handling code pieces are a pain
- https://github.com/owncloud/core/blob/lock-zip-content/lib/private/files.php#L144
- https://github.com/owncloud/core/blob/lock-zip-content/lib/private/files.php#L147

As of today we have no mechanism to throw an exception which is caught in index.php and will result in a different http status code then 500 or 503.

To make the work properly we need to add more error handling code logic to index.php - but for which effort?

From my pov in 9.0 we should completly kill this file and rely on webdav.

@PVince81 @karlitschek @schiesbn @icewind1991 objections? THX

**Comment by karlitschek** [comment]
@DeepDiver1975 I think the direction is fine. We should do everything through WebDAV. Not sure yet about the timeframe.

**Comment by PVince81** [comment]
Just tested this, add this code in basicOperation before the `$this->runHooks()` line:
```php
			if (in_array('write', $hooks) || in_array('delete', $hooks)) {
				sleep(10);
			}

```

Then delete files inside the folder, and while the deletion occurs, download a zip for the folder.

The result: empty zip file.

@DeepDiver1975 is that the intended behavior ? Empty zip is better than corrupt zip though.
Throwing a 500 might be better.

**Comment by DeepDiver1975** [comment]
@PVince81 thanks for testing - I assume the zip creation code does not yet handle lock exceptions properly - will have a look - THX

Anything in the error log?

**Comment by PVince81** [comment]
There was nothing relevant the logs as far as I recall

**Comment by DeepDiver1975** [comment]
> The result: empty zip file.

Just tried to reproduce this - while the delete was still being processed the zip was created and contained all files - including the deleted file.

**Comment by DeepDiver1975** [comment]
Ah - might be because TarStreamer::addFileFromStream() is handling the case where the given stream is not valid - ZipStreamer might break apart ....

**Comment by jvillafanez** [comment]
I guess that's what I'm seeing.

Upload a file and then download the zip directory (the file is uploaded inside the directory we're zipping), the browser (firefox) tries to download but fails, so the file isn't downloaded. This is a potential issue because there isn't any info about why the download failed. In addition, if I click in the retry download button (the one that firefox provides in his download manager) sometimes it works and others not, probably depending if the download started and failed or it never started.

screenshot from 2015-10-02 13 19 43


If the zipping starts first, and then delete files, It's possible to delete the files that are already zipped and streamed, but not those what are pending to do so. I can also upload files while the folder is being zipped, but those files won't be added to the zip file. I'm not seeing issues in this scenario.

**Comment by DeepDiver1975** [comment]
@jvillafanez thx - no error messages on your system as well?

**Comment by DeepDiver1975** [comment]
hmmm .. I'm still having issues to reproduce this

**Comment by jvillafanez** [comment]
@DeepDiver1975 No error messages in the ownCloud logs

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 No error messages in the ownCloud logs

@jvillafanez did you retest this with the latest changes? 132f778 adds some more logging. THX

**Comment by jvillafanez** [comment]
I've tried to overwrite an existing file and then download the folder, but no luck trying to make it fail today :sob:

**Comment by DeepDiver1975** [comment]
@PVince81 mind retesting?

**Comment by PVince81** [comment]
I tried again. Make sure to delete a file at the end of the folder and have it stay locked for 10 seconds while the zip is getting created. It still gives me an empty zip file.

I found this in the log:
```
{"reqId":"ZLT0gvRQat6YKB\/MS0jG","remoteAddr":"127.0.0.1","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\Lock\\\\LockedException\",\"Message\":\"\\\"passive aggressive folder\\\/Huoguo.jpg\\\" is locked\",\"Code\":0,\"Trace\":\"
#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1878): OC\\\\Files\\\\View->lockPath('\\\/passive aggres...', 1, false)\\n
#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1009): OC\\\\Files\\\\View->lockFile('\\\/passive aggres...', 1)\\n
#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(870): OC\\\\Files\\\\View->basicOperation('fopen', '\\\/\\\/passive aggre...', Array, 'r')\\n
#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(723): OC\\\\Files\\\\View->fopen('\\\/\\\/passive aggre...', 'r')\\n
#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/streamer.php(80): OC\\\\Files\\\\Filesystem::fopen('\\\/\\\/passive aggre...', 'r')\\n
#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files.php(169): OC\\\\Streamer->addDirRecursive('\\\/\\\/passive aggre...')\\n
#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/download.php(53): OC_Files::get('\\\/', Array, false)\\n
#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/htdocs...')\\n
#8 [internal function]: __lambda_func(Array)\\n
#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(281): call_user_func('\\\\x00lambda_3', Array)\\n
#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(829): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n
#12 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php\",\"Line\":1786}","level":3,"time":"2015-10-05T14:03:10+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2F&files=passive%20aggressive%20folder&downloadStartSecret=pi93g067lvnjc3di"}
```

It doesn't always happen, only had it twice.

The downloaded zip file is 12MB and corrupt. I suspect it was aborted in the middle due to the lock exception. A successful zip file for my test dir has about 130 MB.

**Comment by DeepDiver1975** [comment]
hmmm ... the lock exception is throw far to late in the call.

All files are to be locked before we start to stream - in this case we make sure no exception in the middle will break the zip generation/streaming ...

````
> #0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1878): OC\\\\Files\\\\View->lockPath('\\\/passive aggres...', 1, false)\\n #1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1009): OC\\\\Files\\\\View->lockFile('\\\/passive aggres...', 1)\\n #2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(870): OC\\\\Files\\\\View->basicOperation('fopen', '\\\/\\\/passive aggre...', Array, 'r')\\n #3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(723): OC\\\\Files\\\\View->fopen('\\\/\\\/passive aggre...', 'r')\\n #4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/streamer.php(80): OC\\\\Files\\\\Filesystem::fopen('\\\/\\\/passive aggre...', 'r')\\n #5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files.php(169): OC\\\\Streamer->addDirRecursive('\\\/\\\/passive aggre...')\\n

**Comment by PVince81** [comment]
I just saw in the code that you're only locking the parent folder ? You need to put a shared lock in every file inside it too.

If that's not acceptable, then set an exclusive lock on the folder alone, but that will exclude anyone wanting to read...

**Comment by DeepDiver1975** [comment]
> I just saw in the code that you're only locking the parent folder ? You need to put a shared lock in every file inside it too.

This will be quite expensive - and can take some time thinking about folders with many files inside.

Alternative approach: we catch the exception on the single file operation and skip the locked file?

**Comment by DeepDiver1975** [comment]
> Alternative approach: we catch the exception on the single file operation and skip the locked file?

That's stupid - the user expects all files ...

**Comment by DeepDiver1975** [comment]
> If that's not acceptable, then set an exclusive lock on the folder alone, but that will exclude anyone wanting to read...

So we are left with this approach?

**Comment by PVince81** [comment]
Yes, but it means no one will be able to download anything inside that folder in the meantime. Exclusive lock is usually what we use when the folder is being moved/renamed/deleted.

This sucks when someone sends a link to a shared folder to everyone, and many people want to download it at the same time.

**Comment by DeepDiver1975** [comment]
> This sucks when someone sends a link to a shared folder to everyone, and many people want to download it at the same time.

hmmm - true ....

**Comment by icewind1991** [comment]
> This will be quite expensive - and can take some time thinking about folders with many files inside.

We already need to iterate all files to add it to the zip so we could re-use that

**Comment by DeepDiver1975** [comment]
> We already need to iterate all files to add it to the zip so we could re-use that

hmmm .... let's give that a try .... will adjust the PR ...

**Comment by DeepDiver1975** [comment]
@PVince81 @icewind1991 mind another look? THX

File: lib/private/files.php [hunk 2]
```diff
@@ -258,4 +285,28 @@ public static function setUploadLimit($size, $files = []) {
...
+	 * @param $filename
+	 */
+	private static function unlockAllTheFiles($dir, $files, $getType, $view, $filename) {
+		if ($getType === self::FILE) {
+			$view->unlockFile($filename, ILockingProvider::LOCK_SHARED);
+		}
+		if ($getType === self::ZIP_FILES) {
+			foreach ($files as $file) {
+				$file = $dir . '/' . $file;
+				$view->unlockFile($file, ILockingProvider::LOCK_SHARED);
```
Comment (PVince81) [inline lib/private/files.php]: this doesn't cover all the files any more

Comment (PVince81) [inline lib/private/files.php]: or can `$files` contain full paths too ?

File: lib/private/files.php [hunk 3]
```diff
@@ -178,6 +155,56 @@ public static function get($dir, $files, $onlyHeader = false) {
...
+		foreach ($files as $file) {
+			$file = $dir . '/' . $file;
+			$view->lockFile($file, ILockingProvider::LOCK_SHARED);
+			if ($view->is_dir($file)) {
+				$contents = $view->getDirectoryContent($file);
+				$contents = array_map(function($fileInfo) use ($file) {
+					/** @var \OCP\Files\FileInfo $fileInfo */
+					return $file . '/' . $fileInfo->getName();
+				}, $contents);
+				self::lockFiles($view, $dir, $contents);
```
Comment (PVince81) [inline lib/private/files.php]: recursion ? that can be dangerous :wink: 

But let's test the concept first.

**Comment by PVince81** [comment]
Seems to work now:
busypage

File: lib/private/files.php (hunk 3 above)
Comment (PVince81) [inline lib/private/files.php]: So, the concept works. I'd suggest to change this to use a while loop instead to make sure we don't run into issues when people have too deep folder structures.

Comment (icewind1991) [inline lib/private/files.php]: Dont think recursion will be a problem here, you'll probably run into path length issues before that.

(also we do recursion on folder structures in other places)

Comment (DeepDiver1975) [inline lib/private/files.php]: well ... having an iterator on the view would be great ......

**Comment by PVince81** [comment]
Anyway, I'm ok with the current fix :+1:

**Comment by icewind1991** [comment]
Looks good :+1:

**Comment by DeepDiver1975** [comment]
THX @icewind1991 @PVince81 - with 9.0 I want to finally see files.php die ....

**Comment by DeepDiver1975** [comment]
@jvillafanez mind testing this again as well? THX

**Comment by jvillafanez** [comment]
I needed to hack the code to put it to sleep to reproduce it easier. Basic test looks good, but it might need a more in depth testing for some cases. Anyway :+1:

**Comment by DeepDiver1975** [comment]
> Basic test looks good, but it might need a more in depth testing for some cases. Anyway :+1:

@rperezb can we add this to the test plan for 8.2? THX

**Comment by PVince81** [comment]
Regression in public link download: https://github.com/owncloud/core/issues/19614
