### PR TITLE
Fix #24219: Added hint for specifying a port.

### LINKED ISSUE #24219: PostgreSQL setup: allow specifying a TCP port
### Steps to reproduce
1. install
2. go to /owncloud URI to do setup
3. select PostgreSQL database backend
### Expected behaviour

Be able to specify a TCP port, in addition to hostname, for the database
### Actual behaviour

No field exists to specify a port

**ownCloud version:** (see ownCloud admin page)
8.1.6

**Where did you install ownCloud from:**
http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_8.0/

### PR DESCRIPTION
**Pull request by souravbadami**
## Description

Added hint for specifying a port.
## Related Issue

#24219 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by butonic** [comment]
👍

File: core/templates/installation.php [hunk 1]
```diff
@@ -142,6 +142,9 @@
 					value="<?php p($_['dbhost']); ?>"
 					autocomplete="off" autocapitalize="off" autocorrect="off">
 			</p>
+			<p class="info">
+				<?php p($l->t( 'Please specify the port number alongwith the host name (e.g., localhost: 5432).' )); ?>
```
Comment (souravbadami) [inline core/templates/installation.php]: Done.

**Comment by PVince81** [comment]
Thanks, merged
