### PR TITLE
Store storage availability in database

### LINKED ISSUE #13531: Auto-umount / ignore / blacklist broken storages
With server to server sharing and other external storages, it can happen that a storage becomes unavailable for various reason. (ex: no route to host, host is down, etc).

Instead of trying to connect there and wait until timeout, OC should blacklist broken storages for a given time and try again later instead of trying for every PHP request.

Because trying every time can slow down significantly when accessing the folder where the mount point is in.

@icewind1991 @Xenopathic

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Storage status is saved in the database. Failed storages are rechecked every 10 minutes, while working storages are rechecked every request. Using the files_external app will recheck all external storages when the settings page is viewed, or whenever an external storage is saved.

The advantage of this is that failed external storages will not impede page loading, apart from every 10 minutes when a recheck is performed. To test, simply create several external storages will valid details other than the credentials (SFTP is nice and slow for this), then load the files page. On master, it will load slowly as timeouts occur. With this PR, it will load slowly once, then be fast for 10 minutes.

The counterpart to this is #13515, which eliminates the slowdown on the settings pages.

Fixes #13531

cc @PVince81 @icewind1991 @DeepDiver1975 

P.S. This is my first work involving database stuff. It's likely that I got something wrong, so review those bits in particular! The unit tests should help though :smile:

### CODE REVIEW

File: lib/private/files/cache/storage.php [hunk 1]
```diff
@@ -91,6 +99,36 @@ public static function getNumericStorageId($storageId) {
 	}
 
 	/**
+	 * @return bool
```
Comment (LukasReschke) [inline lib/private/files/cache/storage.php]: May also return null

**Comment by LukasReschke** [comment]
``` 
17:06:08 .....................................PHP Fatal error:  Call to undefined method Mock_Storage_77aba13b::test() in /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/files/mount/mountpoint.php on line 207
17:06:11 PHP Stack trace:
17:06:11 PHP   1. {main}() /usr/local/bin/phpunit:0
17:06:11 PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:612
17:06:11 PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:138
17:06:11 PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:186
17:06:11 PHP   5. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:423
17:06:11 PHP   6. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:751
17:06:11 PHP   7. PHPUnit_Framework_TestCase->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:751
17:06:11 PHP   8. PHPUnit_Framework_TestResult->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:722
17:06:11 PHP   9. PHP_Invoker->invoke() phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php:641
17:06:11 PHP  10. call_user_func_array:{phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93}() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
17:06:11 PHP  11. PHPUnit_Framework_TestCase->runBare() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
17:06:11 PHP  12. PHPUnit_Framework_TestCase->runTest() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:766
17:06:11 PHP  13. ReflectionMethod->invokeArgs() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:881
17:06:11 PHP  14. Test\Files\Node\Root->testGet() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:881
17:06:11 PHP  15. OC\Files\Node\Root->mount() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/tests/lib/files/node/root.php:54
17:06:11 PHP  16. OC\Files\Mount\Manager->addMount() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/files/node/root.php:112
17:06:11 PHP  17. OC\Files\Mount\MountPoint->isAvailable() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/files/mount/manager.php:23
```

File: lib/private/files/cache/storage.php (hunk 1 above)
Comment (Xenopathic) [inline lib/private/files/cache/storage.php]: Specifically cannot return null - see database schema

Comment (LukasReschke) [inline lib/private/files/cache/storage.php]: What is L108 then for?

Comment (Xenopathic) [inline lib/private/files/cache/storage.php]: Ah, sorry, it was late and I wasn't thinking properly :smile:

**Comment by Xenopathic** [comment]
Hmm, I'm trying to fix these test failures, and it seems there is a cyclic dependency. This PR introduces the `isAvailable()` test before allowing a storage to be mounted, which checks if the storage can be `stat()`'d. However, during login, the filesystem is set up before the home storage is created (for a new user where it doesn't already exist), which fails because the home storage is unreachable at that stage.

There are a couple of solutions that I can see: either move the home storage creation so that it occurs before the filesystem is set up, or create the home storage while the storage is being mounted (so trigger that from `test()` or `isAvailable()`). This is going deep into things-may-break-horribly territory though, perhaps @icewind1991 can help?

**Comment by PVince81** [comment]
Nice work. I wonder if it's too early for this, as we wanted to revamp the DB anyway here: https://github.com/owncloud/core/issues/11261#issuecomment-61234239

But that might fit with the new scheme, too.
I'll review this later for 8.1.

File: lib/private/files/cache/storage.php [hunk 2]
```diff
@@ -91,6 +99,36 @@ public static function getNumericStorageId($storageId) {
...
+	 */
+	public function getAvailability() {
```
Comment (DeepDiver1975) [inline lib/private/files/cache/storage.php]: I'd merge this into one function where all information is returned. With the current design two queries will be fired to get availability and last checked

File: lib/private/files/storage/wrapper/wrapper.php [hunk 3]
```diff
@@ -477,4 +477,31 @@ public function __call($method, $args) {
...
 		return $this->storage->getDirectDownload($path);
 	}
+
+	/**
+	 * Get availability of the storage
+	 *
+	 * @return bool
+	 */
+	public function getAvailability() {
+		return $this->getStorageCache()->getAvailability();
```
Comment (icewind1991) [inline lib/private/files/storage/wrapper/wrapper.php]:
```php
return $this->storage->getAvailability();
```
would be better here (and for the other 2 methods)

File: lib/private/files/mount/manager.php [hunk 4]
```diff
@@ -20,7 +20,9 @@ class Manager {
 	 * @param MountPoint $mount
 	 */
 	public function addMount(MountPoint $mount) {
-		$this->mounts[$mount->getMountPoint()] = $mount;
+		if ($mount->isAvailable()) {
```
Comment (icewind1991) [inline lib/private/files/mount/manager.php]: :-1: 
This causes a call to `$storage->test()` (which can be very expensive) every time a storage is mounted whether it's used or not

Comment (Xenopathic) [inline lib/private/files/mount/manager.php]: Any suggestions for an alternative? Perhaps the only way to avoid this is wrapping every filesystem function with a check to `isAvailable()`?

**Comment by Xenopathic** [comment]
Right, I think I've got it now. The availability checker is implemented as a storage wrapper, and uses the following algorithm for every storage call:

1. If marked as available in storage cache, continue with normal call.
2. If recheck TTL reached, perform storage test, update storage cache and go to 1. with new availability information
3. Otherwise, throw a `StorageNotAvailableException`

If the call to the storage itself throws a `StorageNotAvailableException`, the storage will be marked as not available in the storage cache, then the exception is rethrown up the call stack.

One issue noticed with this new code: `getDirectoryContent()` in a view will break if an exception is thrown at any point, such as when external storages visible in the root directory are probed. I added a try catch block to stop this, so that `StorageNotAvailableException`s are silently ignored.

For this PR to be useful, storages need to throw `StorageNotAvailableException` when they fail. At the moment, very few actually do, but for testing purposes the SFTP changes I made in #13390 work well. As mentioned earlier, SFTP is very good for noticing the timeouts, since an authentication failure typically has a long timeout.

@icewind1991 Tell me if I'm doing anything wrong :smile:

**Comment by icewind1991** [comment]
This approach seems fine by me

**Comment by PVince81** [comment]
Please rebase.

**Comment by Xenopathic** [comment]
Rebase conflict was the `version.php` update. No other code is changed.

**Comment by LukasReschke** [comment]
Rebase required.

**Comment by Xenopathic** [comment]
Rebase conflict was license headers and version.php.

**Comment by Xenopathic** [comment]
@icewind1991 @LukasReschke @DeepDiver1975 @PVince81 Review please :smile:

File: lib/private/files/storage/wrapper/availability.php [hunk 5]
```diff
@@ -0,0 +1,396 @@
...
+ */
+namespace OC\Files\Storage\Wrapper;
+
+/**
+ * Availability checker for storages
+ *
+ * Throws a StorageNotAvailableException for storages with known failures
+ */
+class Availability extends Wrapper {
+	const RECHECK_TTL = 600; // 10 minutes
```
Comment (LukasReschke) [inline lib/private/files/storage/wrapper/availability.php]: Maybe use something like `RECHECK_TTL_SEC` so that people don't have to look at the actual meaning of it :)

File: lib/private/files/storage/wrapper/availability.php [hunk 6]
```diff
@@ -0,0 +1,396 @@
...
+		$this->checkAvailability();
+		try {
+			return parent::getETag($path);
+		} catch (\OCP\Files\StorageNotAvailableException $e) {
+			$this->setAvailability(false);
+			throw $e;
+		}
+	}
+
+	public function getDirectDownload($path) {
```
Comment (LukasReschke) [inline lib/private/files/storage/wrapper/availability.php]: Inherit the PHPDocs so my PHPStorm with strict settings won't complain? :see_no_evil:

Comment (Xenopathic) [inline lib/private/files/storage/wrapper/availability.php]: For you? Anything :laughing:

**Comment by Xenopathic** [comment]
Hmm, that's the second time that's happened:

```
09:15:57 PHP  13. Test\Files\Filesystem->tearDown() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:793
09:15:57 PHP  14. OC\Files\Filesystem::mount() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/tests/lib/files/filesystem.php:56
09:15:57 PHP  15. OC\Files\Mount\MountPoint->__construct() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/files/filesystem.php:466
09:15:57 PHP  16. OC\Files\Storage\StorageFactory->wrap() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/files/mount/mountpoint.php:76
09:15:57 PHP  17. OC_Util::{closure:/var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/util.php:103-123}() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/files/storage/storagefactory.php:74
09:15:57 PHP  18. OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/util.php:110
09:15:57 PHP  19. OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/files/storage/wrapper/wrapper.php:455
09:15:57 PHP  20. OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/files/storage/wrapper/wrapper.php:455
09:15:57 PHP  21. OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/files/storage/wrapper/wrapper.php:455
09:15:57 PHP  22. OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/files/storage/wrapper/wrapper.php:455
... continue until function nesting level overload ...
```

Thing is, when this happened the last time, I scheduled a retest and it all worked fine.

@owncloud-bot retest this please

**Comment by Xenopathic** [comment]
@owncloud-bot retest this please

**Comment by Xenopathic** [comment]
@icewind1991 Please check that latest commit to make sure I'm doing it right :smile:

**Comment by MorrisJobke** [comment]
@Xenopathic This needs another rebase :( But it is moved to 8.2 ... maybe wait until 8.1 is out and then again try to work on this :)

File: lib/private/util.php [hunk 7]
```diff
@@ -138,6 +138,11 @@ public static function setupFS($user = '') {
 			//trigger creation of user home and /files folder
 			\OC::$server->getUserFolder($user);
 
+			// install storage availability wrapper
+			\OC\Files\Filesystem::addStorageWrapper('oc_availability', function ($mountPoint, $storage) {
+				return new \OC\Files\Storage\Wrapper\Availability(['storage' => $storage]);
```
Comment (icewind1991) [inline lib/private/util.php]: maybe dont apply the wrapper to local storages.

Comment (icewind1991) [inline lib/private/util.php]: Maybe it's best to not register the wrapper here at all but have file_external add the wrapper to any external storage

Comment (Xenopathic) [inline lib/private/util.php]: @icewind1991 What about the internal DAV storage for S2S?

Comment (icewind1991) [inline lib/private/util.php]: right, maybe then just have a check on `isLocal()`

**Comment by Xenopathic** [comment]
@owncloud-bot retest this please

**Comment by icewind1991** [comment]
:+1: nice work

**Comment by MorrisJobke** [comment]
* I added a SMB backend in the admin panel
* green dot appears
* I shut down the SMB service
* I modified the last_accessed column to value-1000
* accessed the mounted folder to retrigger the check
* database still holds the available value `1`

**Comment by Xenopathic** [comment]
@MorrisJobke This only works if the storage cooperates and throws StorageNotAvailableException. Try merging `sftp_exceptions` (#13390) with this branch and set up an SFTP storage. Then it will work as you expect. This PR just lays the groundwork for storage availability

**Comment by MorrisJobke** [comment]
@Xenopathic rebase needed

**Comment by Xenopathic** [comment]
@owncloud-bot retest this please

**Comment by Xenopathic** [comment]
@MorrisJobke Could you re-review this please?

**Comment by Xenopathic** [comment]
Also cc @PVince81

File: lib/private/files/mount/mountpoint.php [hunk 8]
```diff
@@ -92,7 +93,11 @@ public function __construct($storage, $mountpoint, $arguments = null, $loader =
 		$this->mountPoint = $mountpoint;
 		if ($storage instanceof Storage) {
 			$this->class = get_class($storage);
-			$this->storage = $this->loader->wrap($this, $storage);
+			$this->storage = $storage;
+			// only wrap if not already wrapped
+			if (!($this->storage instanceof Wrapper)) {
+				$this->storage = $this->loader->wrap($this, $this->storage);
```
Comment (PVince81) [inline lib/private/files/mount/mountpoint.php]: Is this required by this PR or is an additional fix ?

File: lib/private/files/cache/storage.php [hunk 9]
```diff
@@ -130,6 +136,28 @@ public static function getNumericStorageId($storageId) {
 	}
 
 	/**
+	 * @return array|null [ available, last_checked ]
+	 */
+	public function getAvailability() {
+		if ($row = self::getStorageById($this->storageId)) {
```
Comment (PVince81) [inline lib/private/files/cache/storage.php]: I guess it's not possible to retrieve + cache this together when reading the full storage entry ? (to avoid extra SQL calls)

File: lib/private/files/mount/mountpoint.php (hunk 8 above)
Comment (Xenopathic) [inline lib/private/files/mount/mountpoint.php]: Without this fix, unit tests will fail, since our unit tests attempt to re-wrap storages sometimes causing function nesting limit failures. In the actual codebase it makes no difference, since we never pass a wrapped storage to be re-wrapped.

File: lib/private/files/cache/storage.php (hunk 9 above)
Comment (Xenopathic) [inline lib/private/files/cache/storage.php]: The caching would be done in `getStorageById()`, since a couple of functions use that. But, prior to this PR, we never cached it (see `getNumericStorageId()` above, and the constructor). Do we want that in the scope of this PR?

File: lib/private/files/mount/mountpoint.php (hunk 8 above)
Comment (Xenopathic) [inline lib/private/files/mount/mountpoint.php]: Actually, this is a poor fix. There may be usecases where instead of a Storage being passed in, a Wrapper is (aka pre-wrapped storage) but still needs to be wrapped with the other storage wrappers too.

**Comment by PVince81** [comment]
Didn't destroy the known universe :+1: (ran a few smashbox tests and encryption + ext storage)

**Comment by PVince81** [comment]
Regression, cannot create user: https://github.com/owncloud/core/issues/18129
