### PR TITLE
Accessing sharetab directly for a long list of files

### LINKED ISSUE #35200: browsing directly to details does not work for files far down the list
### Steps to reproduce
1. have a long list of file e.g. from https://github.com/owncloud/testing/tree/master/data/webUISkeleton
2. try to navigate directly to the sharing tab of last file e.g. `localhost/owncloud-core/index.php/apps/files/?dir=/&scrollto=zzzz-must-be-last-file-in-folder.txt&details=shareTabView`

### Expected behaviour
Sharing tab of the file should open

### Actual behaviour
image

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache2
**Database:**
SQLite
**PHP version:**
7.1
**ownCloud version:** (see ownCloud admin page)
11.0.0
10.1.1
**Updated from an older ownCloud or fresh install:**
fresh

seems not to be a regression
bayernbox has a similar issue https://github.com/owncloud/enterprise/issues/3310#issuecomment-490865700

CC @patrickjahns

### PR DESCRIPTION
**Pull request by sharidas**
Accessing sharetab directly for a long list of
files caused problems. The pages need to be fetched
appropriately to get the data. This changeset fixes
the problem.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Lets say we have 30 files listed in the the UI. The maximum page size we have is 18. And hence when user tries to access the 19th file from the UI using `http://localhost/testing3/index.php/apps/files/?dir=/test&&scrollto=file19.txt&details=shareTabView` ( where `file19.txt` ) is the 19th file in the list, then the sharetab would be shown without any details. The reason for this is its the 19th element and hence the filelist doesn't have the `tr` added. So to solve this issue, the index of the file from the `this.files` is taken. And this would help to calculate the number of attempts required to fetch the page so that we get the data.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/35200

## Motivation and Context

We need to fetch the pages to get the data populated, so that when they are accessed for the share tab field, the tab does not show empty.

## How Has This Been Tested?

-  Create a folder test
- Upload 150 files
- [x] Access 15th elements sharetab field
- [x] Access 110th file's share tab field
- [x] Access 150th files share tab field
- [x] Access 190th files share tab field
- [x] Access 210th files share tab field shows 
beyondarray

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by jvillafanez** [comment]
Some questions:
* Is there any element loaded before the scrollTo method is called? We don't really want to make unnecessary calls.
* How does this affect to "normal" scrolling? You can have 500 files inside a folder, you enter the folder normally and start scrolling down to see the last element. I expect the minimum number of calls to the `_nextPage()` method needed to do so. I want to avoid having to call 3 times that method to get the 3rd page, and then 4 times to get the next one, and then 5 times to get the 5th page.

There are minor style things we can adjust in the code, but I'd prefer to check those couple of things first in case there are changes needed.

**Comment by sharidas** [comment]
> * Is there any element loaded before the scrollTo method is called? We don't really want to make unnecessary calls.

The `scrollTo` method is called from `setFiles` method which calls `_nextPage` method once. Thats the one which populates the data where the call reaches `updateDetailsView` method. Inside `updateDetailsView` method the call `this.findFileEl(fileName);` would return nothing. And hence call to `this.getModelForFile($tr);` would return null making the `model`, in the code path null.

> * How does this affect to "normal" scrolling? You can have 500 files inside a folder, you enter the folder normally and start scrolling down to see the last element. I expect the minimum number of calls to the `_nextPage()` method needed to do so. I want to avoid having to call 3 times that method to get the 3rd page, and then 4 times to get the next one, and then 5 times to get the 5th page.
> 

This does not affect normal scrolling. Because the code path is a little different, but eventually it calls `nextPage` method subsequntly while scrolling. So the containers scroll is binded to `onScroll` method ( in the same filelist.js file ). And this method calls nextPage method while user scrolls down. So lets say there are 100 files in a folder. The nextPage method from `onScroll` would be called 6 times.

Let me know if this addresses your query?

File: apps/files/js/filelist.js [hunk 1]
```diff
@@ -2539,6 +2539,16 @@
 			}
 			if (!_.isUndefined(detailTabId)) {
 				var filename = file[file.length - 1];
+				//Double check if the area that you are scrolling is beyond the page limit?
+				var pageSize = this.pageSize();
+				var index = _.findIndex(this.files, function (obj) { return obj.name === filename});
```
Comment (jvillafanez) [inline apps/files/js/filelist.js]:
```
var index = _.findIndex(this.files, function (obj) {
    return obj.name === filename;
});
```
This is more common.

File: apps/files/js/filelist.js [hunk 2]
```diff
@@ -2539,6 +2539,16 @@
...
+				if (index > pageSize) {
+					for (var numberOfMorePagesToScroll = Math.floor(index / pageSize);
```
Comment (jvillafanez) [inline apps/files/js/filelist.js]:
```
var numberOfMorePagesToScroll = Math.floor(index / pageSize);
while (numberOfMorePagesToScroll > 0) {
  this._nextPage();
  numberOfMorePagesToScroll--;
}
```
this feels a bit more readable.

In addition, "for" loops usually go upwards (from 0 to X) not downwards (from X to 0). The "while" loop also seems for readable in this case.

File: apps/files/js/filelist.js (hunk 1 above)
Comment (sharidas) [reply apps/files/js/filelist.js]: Updated the change.

**Review by jvillafanez — APPROVED** [review]
