### PR TITLE
shorten quota usage wording, fix overflow on mobile, fix #21129

### LINKED ISSUE #21129: Horizontal scroll bar on small screens due to quota bar
Noticed in https://github.com/owncloud/core/pull/20994#issuecomment-163696560 but also in master

bildschirmfoto 2015-12-10 um 18 33 19

cc @owncloud/designers

### PR DESCRIPTION
**Pull request by jancborchardt**
Wanted to fix the strange wording here since some time, and https://github.com/owncloud/core/issues/21129 gave me a good reason to make it short and succinct.

Please review @owncloud/designers @MorrisJobke @Henni

### CODE REVIEW

File: settings/templates/personal.php [hunk 1]
```diff
@@ -58,7 +58,7 @@
 	<div style="width:<?php p($_['usage_relative']);?>%"
 		<?php if($_['usage_relative'] > 80): ?> class="quota-warning" <?php endif; ?>>
 		<p id="quotatext">
-			<?php print_unescaped($l->t('You have used <strong>%s</strong> of the available <strong>%s</strong>',
+			<?php print_unescaped($l->t('You use <strong>%s</strong> of <strong>%s</strong>',
```
Comment (icewind1991) [inline settings/templates/personal.php]: `are using` ?

Comment (jancborchardt) [inline settings/templates/personal.php]: The -ing form is not really elegant and refers to something that happes at this moment. Of course that usage constantly happens, but still »You use« seems simpler.

@MTRichards native speaker advice?

**Comment by MorrisJobke** [comment]
I like it :+1:

File: settings/templates/personal.php (hunk 1 above)
Comment (PVince81) [inline settings/templates/personal.php]: or @Xenopathic @tomneedham native speaking advice ? :smile:

Comment (Xenopathic) [inline settings/templates/personal.php]: Should definitely be 'are using' or 'have used', probably 'are using' is more suitable since the usage can both increase and decrease

Comment (jancborchardt) [inline settings/templates/personal.php]: Fixed, please review again. :)

**Comment by jancborchardt** [comment]
Rebased, second review please @owncloud/designers  :)

**Comment by Xenopathic** [comment]
:+1:

**Comment by jancborchardt** [comment]
@DeepDiver1975 check and merge please. :)
