### PR TITLE
[encryption] fix download of public shared files

### LINKED ISSUE #13270: Encryption is broken with public sharing
On current master when installing new:

1. Install ownCloud as user "admin"
2. Enable encryption app
3. Log out
4. Login
5. Create a file "shared.txt"
6. Share that file publicly
7. Access the file
8. Try to download it

Get the following error:
```
[Mon Jan 12 13:58:57.889593 2015] [:error] [pid 44077] [client 192.168.0.17:55522] PHP Fatal error:  Call to a member function getUID() on null in /Users/lreschke/Programming/core/apps/files_encryption/lib/stream.php on line 139, referer: http://192.168.0.17/index.php/s/6eh2VfEbVfPgcGT
```

@schiesbn

### PR DESCRIPTION
**Pull request by schiessle**
if we download a public shared file we need to retrieve the user from the path

fix #13270

cc @LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
We now have https://github.com/owncloud/core/pull/13275 and this one – which one to take? – Which one doesn't break login? (https://github.com/owncloud/core/pull/13275#issuecomment-69586760)

**Comment by oparoz** [comment]
OK, so this doesn't break login for both the private and public side (token + pwd)
BUT
it breaks the preview manager (for me) on the public side because of the thumbnail cache
```
#0 \apps\files_encryption\lib\helper.php(283): OCA\Files_Encryption\Helper::getUserFromPath('\myuser\thumbna...')
#1 \apps\files_encryption\lib\proxy.php(96): OCA\Files_Encryption\Helper::getUser('\myuser\thumbna...')
#2 \apps\files_encryption\lib\proxy.php(246): OCA\Files_Encryption\Proxy->shouldEncrypt('\myuser\thumbna...', 'r')
#3 \lib\private\fileproxy.php(99): OCA\Files_Encryption\Proxy->preFopen('\myuser\thumbna...', 'r')
#4 \lib\private\files\view.php(767): OC_FileProxy::runPreProxies('fopen', '\myuser\thumbna...', 'r')
#5 \lib\private\files\view.php(665): OC\Files\View->basicOperation('fopen', 'thumbnails\550\...', Array, 'r')
#6 \lib\private\preview.php(497): OC\Files\View->fopen('thumbnails\550\...', 'r')
#7 \apps\galleryplus\preview\preview.php(231): OC\Preview->getPreview()
```

**Comment by nickvergessen** [comment]
`case Util::FILE_TYPE_CACHE:` needs the same tweak?

**Comment by schiesbn** [comment]
@nickvergessen maybe for public uploads... I will check.

**Comment by schiesbn** [comment]
@oparoz can you try it once more... The last changes should fix it. Thanks!

**Comment by LukasReschke** [comment]
https://scrutinizer-ci.com/g/owncloud/core/inspections/fd70f1f1-562b-481a-af35-0c06a4b7e6ca/issues/files/apps/files_encryption/lib/proxy.php?status=new&orderField=path&order=asc

**Comment by LukasReschke** [comment]
Seems to be fixed in the newest push as far I can see.

File: apps/files_encryption/lib/stream.php [hunk 1]
```diff
@@ -136,7 +136,8 @@ public function stream_open($path, $mode, $options, &$opened_path) {
 		switch ($fileType) {
 			case Util::FILE_TYPE_FILE:
 				$this->relPath = Helper::stripUserFilesPath($this->rawPath);
-				$this->userId = \OC::$server->getUserSession()->getUser()->getUID();
+				$user = \OC::$server->getUserSession()->getUser();
+				$this->userId = $user ? $user->getUID() : Helper::getUserFromPath($this->rawPath);
```
Comment (PVince81) [inline apps/files_encryption/lib/stream.php]: Hmmm, does it mean that when opening a file in public mode we'd use the owner's share key ? But even that wouldn't work, right ? Does this somehow trigger using the public share key ?

File: apps/files_encryption/lib/proxy.php [hunk 2]
```diff
@@ -47,31 +47,30 @@ class Proxy extends \OC_FileProxy {
...
-	 * @param string $uid user
 	 * @return boolean
 	 */
-	protected function isExcludedPath($path, $uid) {
+	protected function isExcludedPath($path) {
 
 		$view = new \OC\Files\View();
 
-		$path = \OC\Files\Filesystem::normalizePath($path);
+		$normalizedPath = \OC\Files\Filesystem::normalizePath($path);
```
Comment (PVince81) [inline apps/files_encryption/lib/proxy.php]: Why the sudden need to normalize ? Did the path have duplicate "/" on master now ?

Comment (schiesbn) [inline apps/files_encryption/lib/proxy.php]: as you can see "normalizePath" was already there, line 57, I just changed the variable name for better readability.

**Comment by PVince81** [comment]
@schiesbn how did it work in the past but now needs to get the user ? Just wondering :smile:

File: apps/files_encryption/lib/proxy.php (hunk 2 above)
Comment (PVince81) [inline apps/files_encryption/lib/proxy.php]: oops sorry

**Comment by oparoz** [comment]
```
Patching file apps/files_encryption/lib/proxy.php using Plan A...
Hunk #1 failed at 47.
Hunk #2 succeeded at 101 (offset 9 lines).
1 out of 2 hunks failed--saving rejects to apps/files_encryption/lib/proxy.php.rej
```

File: apps/files_encryption/lib/proxy.php (hunk 2 above)
Comment (nickvergessen) [inline apps/files_encryption/lib/proxy.php]: it was normalized before, he just changed the name of the variable?

**Comment by nickvergessen** [comment]
@PVince81 that is exactly the problem, it did not work in the past ;)

**Comment by schiesbn** [comment]
In the past (OC7 and earlier) we had the user. As mentioned by @LukasReschke  the bug was introduced here where we changed the way to get the user to fix the download of versions from shared files: https://github.com/owncloud/core/pull/13182

**Comment by oparoz** [comment]
Once applied, it seems to work, good job :).
I need to check the logs more thoroughly to confirm a 100%

**Comment by PVince81** [comment]
#### public link folder
- [x] download single file
- [x] download single file in subdir
- [x] download whole folder
- [ ] upload file (files_locking enabled) :no_entry_sign: FAIL: "Could not obtain lock type 2 on "/srv/www/htdocs/owncloud/data/root/files_encryption/keys/abc/1391249528060.jpg/fileKey", will raise separately
- [x] upload file (without files_locking):

**Comment by PVince81** [comment]
#### Mount as remote share (server to server sharing)
- [x] download single file
- [x] download folder
- [x] upload
- [x] delete
- [x] move into subdir

File: apps/files_encryption/lib/stream.php (hunk 1 above)
Comment (PVince81) [inline apps/files_encryption/lib/stream.php]: Okay, so it's the incognito mode detection that was broken. That settles it.

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
Raised upload locking issue as https://github.com/owncloud/core/issues/13337

**Comment by schiesbn** [comment]
@LukasReschke or @nickvergessen do you want to have a final look? Thanks!

**Comment by LukasReschke** [comment]
Works :+1:
