### PR TITLE
Display the module settings in the list of the encryption modules

### LINKED ISSUE #15987: Can the UI encryption configuration bits be closer together on the screen?
### Steps to reproduce

1. Install 8.1
2. Enable an encryption module
3. Navigate to admin page

### Expected behaviour

The encryption configuration UI bits should all be near each other

### Actual behaviour

The encryption configuration UI bits are spread out

p337

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 alpha 2 (daily) Build:2015-04-30T03:08:25+00:00 4209757d61685346b9b3eb476035b4e86597ed64

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #15987 

@schiesbn @jancborchardt @MorrisJobke 

admin-settings

part of https://github.com/owncloud/core/issues/16021 (added by @schiesbn to keep track of all pull requests)

### CODE REVIEW

**Comment by jancborchardt** [comment]
Better. Some details:
* there’s too much indentation on the text »Select default encryption module:«, it should align left with the text of the »Enable server-side encryption« label
* change the label to »Select encryption module:«
* remove the left border line
* why is there an enable/disable radio button set _below_ the password boxes? It should be a checkbox next to the »Enable recovery key« text, which then reveals the fields
* unbold the »Change recovery key password« text
* also not show these bunch of fields by default but only when clicking the »Change recovery key password« text (which should be just a link/text below the recovery key password fields)

**Comment by nickvergessen** [comment]
> * there’s too much indentation on the text »Select default encryption module:«, it should align left with the text of the »Enable server-side encryption« label

well currently there is only one module, but a second one would have its checkbox aligned with the first one, causing a major mess:
too-many-modules


> * remove the left border line

I think it helps to spot, which settings belong to which module

I ignore the other comments for now, because they are not affected/changed by this PR

**Comment by schiesbn** [comment]
@jancborchardt 

> change the label to »Select encryption module:«

No, it should be "Select default encryption module" because that's what you select here. The default module which is used if no other module is defined either in the file header or in the storage settings for a specific storage, etc.

**Comment by jancborchardt** [comment]
@nickvergessen I never said to shift the whole block to the left. Here’s what I mean:

a093d9ba-f254-11e4-863a-7778578e99aa

**Comment by jancborchardt** [comment]
Also please ideally work with inline labels/placeholders for the password fields, so you can just put them next to each other. There’s too many levels, complexity and text in this interface already.

**Comment by nickvergessen** [comment]
@jancborchardt I will remove the gray border then, although I think it's very helpful to not loose track on which level you are atm.

But please note, that all the redesign can be dealt with in another PR. This one is about grouping the settings, not how the existing settings should be redesigned, etc.

**Comment by jancborchardt** [comment]
> I will remove the gray border then, although I think it's very helpful to not loose track on which level you are atm.

That problem just results in the section being veery large. This needs to be properly solved by only showing the fields when needed, as well as putting the 2 input fields on one line as I said.

**Comment by nickvergessen** [comment]
@jancborchardt can we merge this now, @karlitschek already closed the ticket Oo

**Comment by MorrisJobke** [comment]
I will fix the placeholder attribute here.

File: settings/templates/admin.php [hunk 1]
```diff
@@ -344,6 +344,8 @@
 						<label
 							for="<?php p($id) ?>"><?php p($module['displayName']) ?></label>
 						<br/>
+
+						<?php if ($id === 'OC_DEFAULT_MODULE') print_unescaped($_['ocDefaultEncryptionModulePanel']); ?>
```
Comment (MorrisJobke) [inline settings/templates/admin.php]: BTW: What happens with the next encryption module? Does it also need to be added here?

**Comment by MorrisJobke** [comment]
> I will fix the placeholder attribute here.

Okay. Misunderstood this PR. Let's move the redesign to another PR. This is only to move the section.

File: settings/templates/admin.php (hunk 1 above)
Comment (nickvergessen) [inline settings/templates/admin.php]: Ideally yes, but we might as well have a look at a good way to do this, once we reach that point.

Comment (MorrisJobke) [inline settings/templates/admin.php]: > Ideally yes

This isn't "ideal" ... this is really bad :(

Comment (nickvergessen) [inline settings/templates/admin.php]: Well for the correct solution we need to extend the encryption manager to keep a list of module setting panels (like `OC_App::registerAdmin` then we can easily do this. But this is not on the todo for 8.1 anymore, 8.2 will have the place for improvement there.

Comment (schiesbn) [inline settings/templates/admin.php]: Maybe we need a even more generic solution. We have a similar "problem" in sharing where we have the core sharing settings and the file sharing settings and you can imagine that other apps using the share API also want to register some share specific settings.

Maybe this could be solved by adding to the info.xml as type the corresponding core module. So all encryption modules could be from type "encryption". When we build the settings page we could then collect all settings from apps related to a core feature and put them together. But this needs quite some changes how the setting page is build and nothing we can fix easily. Here we just use the same hack we already use for sharing to improve the UX for now.

**Comment by schiesbn** [comment]
> Okay. Misunderstood this PR. Let's move the redesign to another PR. This is only to move the section.

I agree, let's merge this PR which does what it is supposed to do and improve/discuss additional improvements in another PR. Inline labels are easy to add and I completely agree to do it. But there are other suggestions by @jancborchardt which needs to be discussed first because some of them not matches the way the feature works as I already explained in some comments above.

So from my point of view :+1:

**Comment by MorrisJobke** [comment]
:+1: from me as well

**Comment by schiesbn** [comment]
@jancborchardt I prepare another PR which implements (most) of your suggestions... stay tuned. :wink:
