### PR TITLE
fix OCS Share API response for requests contain "include_tags" parameter

### LINKED ISSUE #37084: Duplicate link share entry in OCS response with favorites
### Steps

1. Create a folder "test"
1. Create three link shares with different names for that folder
1. Mark folder as favorite
1. Go to "Shared with link"
1. Observe the network console for "/ocs/v1.php/apps/files_sharing/api/v1/shares?format=json&include_tags=true"

### Expected result
Three share entries with different ids, each corresponding to the three link shares.

### Actual result
Three identical share entries, all with the same id

### Version
ownCloud 10.4.1 pre-alpha from git master 433ba3ee41cedb7387424f108534bfd62ae6eb28

I suspect that this is a very old bug and never got discovered before. Probably related to the way how "include_tags" is working to inject the favorite information which is considered a tag, the problem will likely happen as well when setting tags on the entry.

### PR DESCRIPTION
**Pull request by karakayasemi**
## Description
This PR simplifies tag generations for shares and fixes the duplicate share entry problem described in #37084 .
`populateTags` helper method is only used for tag generation for shares. There is no other usage of it in Github organization-wide. The method had too many nested loops. I simplified this method by customizing it for only shares.

@PVince81 Can you confirm the response with this PR so that I don't miss a thing?

## Related Issue
- Fixes #37084 

## How Has This Been Tested?
- Described steps of #37084

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

File: apps/files/lib/Helper.php [hunk 1]
```diff
@@ -207,42 +207,28 @@ public static function getFiles($dir, $sortAttribute = 'name', $sortDescending =
...
 		}
 
-		if (!empty($tags)) {
-			foreach ($tags as $fileId => $fileTags) {
-				$filesById[$fileId]['tags'] = $fileTags;
-			}
-
-			foreach ($filesById as $key => $fileWithTags) {
-				foreach ($fileList as $key2 => $file) {
-					if ($file[$fileIdentifier] == $key) {
```
Comment (PVince81) [inline apps/files/lib/Helper.php]: I can't remember the reason for such complex code back then :-/

**Review by PVince81 — COMMENTED** [review]
Code looks fine. Can you add unit tests ?

**Comment by karakayasemi** [comment]
> 
> 
> Code looks fine. Can you add unit tests ?

If the response is okay, I can add some tests.

**Comment by PVince81** [comment]
I've retested on Phoenix with my scenario and there are no more duplicates. Thanks!

**Comment by karakayasemi** [comment]
@PVince81 Manipulating ShareController tests is pretty complicated. I changed some ApiTest tests to cover requests with "include_tags = true" parameter.

**Review by PVince81 — APPROVED** [review]
:+1: from me. Would be good to also get approval from @micbar

File: changelog/unreleased/37088 [hunk 2]
```diff
@@ -0,0 +1,7 @@
+Bugfix: fix OCS Share API response for requests contain "include_tags" parameter
+
+Sending "include_tags" request parameter for OCS Share API was led to duplicated share entries in API response.
+This problem has been fixed.
```
Comment (micbar) [inline changelog/unreleased/37088]: @karakayasemi Can you describe the way it was fixed? "Reduced the complexity of ..."

Comment (karakayasemi) [reply changelog/unreleased/37088]: @micbar I extended the changelog entry with more details. Please, review one more time. Thanks.

**Review by micbar — APPROVED** [review]

File: changelog/unreleased/37088 (hunk 2 above)
Comment (micbar) [reply changelog/unreleased/37088]: 👍
