### PR TITLE
Properly show the warning about the missing composer autoloader

### LINKED ISSUE #13808: Fatal error: Call to a member function getSession() on a non-object
### Steps to reproduce
1. Download owncloud
2. Open URL on Browser
3.

### Expected behaviour
Show the owncloud Installer

### Actual behaviour
Fatal error:  Call to a member function getSession() on a non-object in .\owncloud\lib\private\template.php on line 53

### Server configuration
**Operating system**: Windows 7 x64

**Web server:** Apache 2.4.7

**Database:** MySQL 5.6.15

**PHP version:** 5.6.4

**ownCloud version:** 8 RC1

**Updated from an older ownCloud or fresh install:** No

**List of activated apps:** N/A (Default)

**The content of config/config.php:** No config available.

```
No config available.
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 7 x64
#### Web server error log
```
[Sat Jan 31 14:19:26.059290 2015] [:error] [pid 7460:tid 764] [client 127.0.0.1:51893] PHP Fatal error:  Call to a member function getSession() on a non-object in .\\owncloud\\lib\\private\\template.php on line 53, referer: http://127.0.0.1/projects/
```

#### ownCloud log (data/owncloud.log)
```
N/A
```

### Additional Infos:

I added a own debug_print_backtrace before line 56
````
#0  OC_Template->__construct(, error, error, ) called at [.\owncloud\lib\private\template.php:206]
#1  OC_Template::printErrorPage(Composer autoloader not found, unable to continue.) called at [.\owncloud\lib\base.php:481]
#2  OC::init() called at [.\owncloud\lib\base.php:1007]
#3  require_once(.\owncloud\lib\base.php) called at [.\owncloud\index.php:26]


Fatal error:  Call to a member function getSession() on a non-object in .\owncloud\lib\private\template.php on line 53
````

Btw, Now I know, the composer is missing.

### PR DESCRIPTION
**Pull request by MorrisJobke**
fixes #13808 

cc @DeepDiver1975 @LukasReschke 

Steps to reproduce:
- `rm 3rdparty/autoload.php`

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Should I also improve the wording to something like this?

> Composer autoloader not found, unable to continue. Check if 3rdparty files are correct.

**Comment by LukasReschke** [comment]
I guess this *partially* addresses https://github.com/owncloud/core/issues/12089.

:+1:

**Comment by MorrisJobke** [comment]
@LukasReschke Correct

**Comment by MorrisJobke** [comment]
@LukasReschke should I add `Check the folder 3rdparty/`?

**Comment by LukasReschke** [comment]
Yes. That would indeed makes sense. Still does not help if somebody has an older 3rdparty checkout but great improvement anyways :) Thanks Morris!

**Comment by MorrisJobke** [comment]
@LukasReschke Added ;)

File: lib/base.php [hunk 1]
```diff
@@ -478,7 +478,10 @@ public static function init() {
 			require_once $vendorAutoLoad;
 		} else {
 			OC_Response::setStatus(OC_Response::STATUS_SERVICE_UNAVAILABLE);
-			OC_Template::printErrorPage('Composer autoloader not found, unable to continue.');
+			// we can't use the template error page here, because this needs the
+			// DI container which isn't available yet
+			print('Composer autoloader not found, unable to continue. Check the folder "3rdparty".');
```
Comment (DeepDiver1975) [inline lib/base.php]: What about simply throwing an exception?

Comment (MorrisJobke) [inline lib/base.php]: Then the same page will be rendered and this rendering will then cause an error. I tried to unwrangle this, but OC_Template needs L10n which will be fetched from `OC::$server` which itself isn't initialized yet -> This is the best solution yet.

Comment (MorrisJobke) [inline lib/base.php]: https://github.com/owncloud/core/blob/master/index.php#L44 <- this is just a wrapper for the same as printErrorPage but with the `exception` template instead of the `error` template. And it will log the exception in advance.

Comment (Xenopathic) [inline lib/base.php]: Eww, we depend on `lib/base.php` being loaded in the `catch` blocks that run if `lib/base.php` *can't* be loaded? :game_die: :game_die: :game_die: :gun:

Comment (MorrisJobke) [inline lib/base.php]: @Xenopathic You're wrong with the dices ... there is no chance to win, so you need to decide on one of the following  :gun: :gun: :gun: or you could take the :gun: ;)

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@karlitschek I'd suggest to backport this to all stable branches - really helps to detect wrong setups - THX

**Comment by karlitschek** [comment]
please backport

**Comment by MorrisJobke** [comment]
stable8 #14259

**Comment by MorrisJobke** [comment]
For stable7 and before we need an individual fix if this is wanted, because the code changed a lot.

**Comment by DeepDiver1975** [comment]
> For stable7 and before we need an individual fix if this is wanted, because the code changed a lot.

let's postpone this then for now - thx
