### PR TITLE
Fix DAV stat cache to properly cache 404

### LINKED ISSUE #26323: DAV client / fed share client doesn't properly stat cache 404
### Steps
1. Setup two servers OC_A and OC_B
2. From OC_B share a folder "test" with OC_A
3. Create a folder in OC_A inside "test" as "sub1"
4. Observe access log
### Expected result

Only a single PROPFIND on "test/sub1" that returns 404.
### Actual result

6 PROPFINDS !
Quick debugging shows that the exception isn't caught properly, so the 404 result isn't stored in the stat cache.
### Versions

Observed on 9.2 pre-alpha / master. Likely to exist on previous versions.

### PR DESCRIPTION
**Pull request by PVince81**
## Description

404 errors were not properly cached due to catching the wrong
exception. Now catching ClientHttpException and checking the error
code. In case of 404, adjust the stat cache accordingly.

Since now the local propfind() call throws NotFound, there is no need
to catch ClientHttpException everywhere any more but need to catch
NotFound exception instead and act accordingly.
## Related Issue

Fixes https://github.com/owncloud/core/issues/26323
## Motivation and Context

Improve performance when creating new file/folders which usually first do a PROPFIND on the remote server to check for file/folder existence. Not caching these 404 would cause at least 6 additional PROPFIND requests to get the status. (this is because we use a lot of `file_exists` call everywhere...)
## How Has This Been Tested?

See issue steps.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
### Backports
- [ ] TODO: evaluate to which versions to backport this

@DeepDiver1975 @butonic @jvillafanez

### CODE REVIEW

**Comment by PVince81** [comment]
also:
- [ ] do proper regression testing, I'm not sure this is really covered by CI ...

**Comment by PVince81** [comment]
Okay, the storage impl is covered by the DAV ext storage tests at least. The bug itself wouldn't trigger any failure since it was a caching issue.

**Comment by DeepDiver1975** [comment]
````
21:49:28 There was 1 failure:
21:49:28 
21:49:28 1) OCA\Files_Sharing\Tests\CacheTest::testGetFolderContentsInRoot
21:49:28 Failed asserting that 10 matches expected 3.
21:49:28 
21:49:28 /var/lib/jenkins/workspace/owncloud-core_core_PR-26324-CAYE3ELZQFIMHVKICLMMAFO6AP4X6ZQLHJBL3TNLCB4KDPW5UN2A/apps/files_sharing/tests/CacheTest.php:444
21:49:28 /var/lib/jenkins/workspace/owncloud-core_core_PR-26324-CAYE3ELZQFIMHVKICLMMAFO6AP4X6ZQLHJBL3TNLCB4KDPW5UN2A/apps/files_sharing/tests/CacheTest.php:349

File: lib/private/Files/Storage/DAV.php [hunk 1]
```diff
@@ -274,11 +269,15 @@ protected function propfind($path) {
 					]
 				);
 				$this->statCache->set($path, $response);
-			} catch (NotFound $e) {
-				// remember that this path did not exist
-				$this->statCache->clear($path . '/');
-				$this->statCache->set($path, false);
-				throw $e;
+			} catch (ClientHttpException $e) {
```
Comment (PVince81) [inline lib/private/Files/Storage/DAV.php]: It's a bit messy...

Basically Sabre's propfind itself only ever throws `ClientHttpException` or `ClientException`, never `NotFound` (that one belongs to sabre server, not sabre client btw).

But here we do want to throw a known exception for the consumers of our own `$this->propfind`, so we throw `NotFound` and they all catch it.

Maybe it would be cleaner to simply rethrow `ClientHttpException` as is to avoid confusion ?

Comment (PVince81) [inline lib/private/Files/Storage/DAV.php]: Argh, looks like I can't easily replace with only ClientHttpException, because when a 404 propfind was cached, I'd need to create a virtual ClientHttpException to simulate failure here: https://github.com/owncloud/core/pull/26324/files#diff-eaf59cbf225a9e583d7cda98942ed6abR253

That's the reason why I picked this exception. Not sure if there is a better solution.

Comment (jvillafanez) [inline lib/private/Files/Storage/DAV.php]: If there is no easy solution, let's go with this. Just write a comment to remind why we've chosen this decision.

Comment (PVince81) [inline lib/private/Files/Storage/DAV.php]: Sounds good, will do

**Comment by PVince81** [comment]
Oh, PHP 7.1 specific failure... fancy!

**Comment by PVince81** [comment]
hmm, tests pass for me in PHP 7.0.12... will need to setup PHP 7.1 then

**Comment by PVince81** [comment]
I've setup 7.1.0RC4 with phpenv (yay, it worked!) but the tests do pass.
On Jenkins it's 7.1.0RC1, not sure if related.
Let's restart the build and see...

If it fails again, then we can try upgrading Jenkins to 7.1.0RC4.
And if it still fails, then it's possibly due to test order...

**Comment by PVince81** [comment]
This is the failure on Jenkins:
```
15:10:51 1) OCA\Files_Sharing\Tests\CacheTest::testGetFolderContentsInRoot
15:10:51 Failed asserting that 10 matches expected 3.
15:10:51 
15:10:51 /var/lib/jenkins/workspace/owncloud-core_core_PR-26324-CAYE3ELZQFIMHVKICLMMAFO6AP4X6ZQLHJBL3TNLCB4KDPW5UN2A/apps/files_sharing/tests/CacheTest.php:444
15:10:51 /var/lib/jenkins/workspace/owncloud-core_core_PR-26324-CAYE3ELZQFIMHVKICLMMAFO6AP4X6ZQLHJBL3TNLCB4KDPW5UN2A/apps/files_sharing/tests/CacheTest.php:349
15:10:51 
```

**Comment by PVince81** [comment]
Rebased, let's hope the test magically passes now...

**Comment by PVince81** [comment]
Even with PHP 7.1.0RC1 the problem doesn't appear on my local env.

So it seems that all I can do now is guessing and trial and error.

**Comment by PVince81** [comment]
The failure itself seems completely unrelated to this change.
I could imagine that the failure is rather related to another PR that was merged into master related to etag propagation. But then it should all also fail on master then.

**Comment by PVince81** [comment]
Jenkins PR: https://github.com/owncloud/core/pull/26466

Let's see if it also fails if restarted in that separate test env...

**Comment by PVince81** [comment]
Ha, the Jenkins PR healed it...

**Comment by PVince81** [comment]
@jvillafanez I decided to use the `return false` approach for the private `propfind` method when an entry was not found. It seems to work fine.

Please rereview.

**Comment by PVince81** [comment]
@jvillafanez please re-review

File: lib/private/Files/Storage/DAV.php [hunk 2]
```diff
@@ -248,15 +242,11 @@ public function opendir($path) {
 	 *
 	 * @return array propfind response
 	 *
-	 * @throws NotFound
+	 * @throws ClientHttpException
```
Comment (jvillafanez) [inline lib/private/Files/Storage/DAV.php]: This doc should be updated with the conditions under it returns "false"

**Comment by jvillafanez** [comment]
I don't see anything strange so 👍

**Comment by PVince81** [comment]
Adjusted comment, squashed and rebased.

**Comment by PVince81** [comment]
Grrrr, that unrelated failure again:
```
10:13:15 1) OCA\Files_Sharing\Tests\CacheTest::testGetFolderContentsInRoot
10:13:15 Failed asserting that 10 matches expected 3.
10:13:15 
10:13:15 /var/lib/jenkins/workspace/owncloud-core_core_PR-26324-CAYE3ELZQFIMHVKICLMMAFO6AP4X6ZQLHJBL3TNLCB4KDPW5UN2A/apps/files_sharing/tests/CacheTest.php:444
10:13:15 /var/lib/jenkins/workspace/owncloud-core_core_PR-26324-CAYE3ELZQFIMHVKICLMMAFO6AP4X6ZQLHJBL3TNLCB4KDPW5UN2A/apps/files_sharing/tests/CacheTest.php:349
10:13:15 
```

Jenkins PR for the rescue: https://github.com/owncloud/core/pull/26564

**Comment by PVince81** [comment]
Tests passed here https://github.com/owncloud/core/pull/26574 and travis failure unrelated.

**Comment by PVince81** [comment]
stable9.1: https://github.com/owncloud/core/pull/26791

**Comment by PVince81** [comment]
stable9: https://github.com/owncloud/core/pull/26792
