### PR TITLE
Fix occ migrations:status Executed Unavailable Migrations and New Migrations

### LINKED ISSUE #40084: Executed Unavailable Migrations is non-zero for occ migrations:status core
### Steps to reproduce
1.
2.
3.

### Expected behaviour
WIP
### Server configuration
current core master

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
`getAvailableVersions()` returns an array with the migration date-timestamps as values. The code incorrectly used the keys of the array. This PR removes the incorrect `array_keys()` in 2 places.

## Related Issue
- Fixes #40084 

## How Has This Been Tested?
Manual run of the command:

Before:
```
$ php occ migrations:status core
    >> App:                                                core
    >> Version Table Name:                                 oc_migrations
    >> Migrations Namespace:                               OC\Migrations
    >> Migrations Directory:                               /home/phil/git/owncloud/core/core/Migrations
    >> Previous Version:                                   20200610110817
    >> Current Version:                                    20210928123126
    >> Next Version:                                       Already at latest migration step
    >> Latest Version:                                     20210928123126
    >> Executed Migrations:                                28
    >> Executed Unavailable Migrations:                    28
    >> Available Migrations:                               28
    >> New Migrations:                                     28
```

After:
```
$ php occ migrations:status core
    >> App:                                                core
    >> Version Table Name:                                 oc_migrations
    >> Migrations Namespace:                               OC\Migrations
    >> Migrations Directory:                               /home/phil/git/owncloud/core/core/Migrations
    >> Previous Version:                                   20200610110817
    >> Current Version:                                    20210928123126
    >> Next Version:                                       Already at latest migration step
    >> Latest Version:                                     20210928123126
    >> Executed Migrations:                                28
    >> Executed Unavailable Migrations:                    0
    >> Available Migrations:                               28
    >> New Migrations:                                     0
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

File: core/Command/Db/Migrations/StatusCommand.php [hunk 1]
```diff
@@ -67,7 +67,7 @@ public function execute(InputInterface $input, OutputInterface $output) {
 	public function getMigrationsInfos(MigrationService $ms) {
 		$executedMigrations = $ms->getMigratedVersions();
 		$availableMigrations = $ms->getAvailableVersions();
-		$executedUnavailableMigrations = \array_diff($executedMigrations, \array_keys($availableMigrations));
+		$executedUnavailableMigrations = \array_diff($executedMigrations, $availableMigrations);
 
 		$numExecutedUnavailableMigrations = \count($executedUnavailableMigrations);
 		$numNewMigrations = \count(\array_diff(\array_keys($availableMigrations), $executedMigrations));
```
Comment (jvillafanez) [inline core/Command/Db/Migrations/StatusCommand.php:73]: I think this should also be adjusted. In your example, there are 28 executed migrations but also 28 new migrations. There shouldn't be new migrations.

Comment (phil-davis) [reply core/Command/Db/Migrations/StatusCommand.php]: fixed - thanks for noticing.

**Review by jvillafanez — APPROVED** [review]

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/35767/26/8
```
+ wait-for-it -t 600 fsweb.test.owncloud.com:445
services aren't ready in 10m0s
```
I hope that fsweb is still working - I restarted CI.
