### PR TITLE
Fix appwebpath detection when OC installed into the subdir and approot is a sibling of oc root dir

### LINKED ISSUE #31170: Enabled theme app outside of OC folder doesn't work
### Steps

1. Install OC 10.0.8 RC2 from tarball inside "/srv/www/htdocs/owncloudtest"
2. Create a folder "/srv/www/htdocs/temp" and give web server permissions
3. Move the example theme from "/srv/www/htdocs/owncloudtest/apps/theme-example" to "/srv/www/htdocs/temp/theme-example"
4. Adjust config.php: 
```
 'apps_paths' => 
    array (
      0 => 
      array (
        'path' => '/srv/www/htdocs/owncloudtest/apps',
        'url' => '/apps',
        'writable' => 'false',
      ),
      1 => 
      array (
        'path' => '/srv/www/htdocs/temp',
        'url' => '/apps-temp',
        'writable' => 'true',
      ),
    ),
```
5. Open the web UI as admin
6. Go to settings and enable the theme-example app
7. Refresh the page / log out then log in again

### Expected result
Example theme applied

### Actual result
Default theme still visible

### Logs
Nothing

### Version
ownCloud 10.0.8 RC2

@VicDeo please have a look, this is supposed to work after https://github.com/owncloud/core/pull/30477

### PR DESCRIPTION
**Pull request by VicDeo**
## Description
Fixes css/js resolution for a case when owncloud installed into the first descendant of the server root directory and app-theme is located outside owncloud root directory.

## Related Issue
Fixes #31170 

## Motivation and Context
rewritten code produced double slash in the case described above and this broke proper URL generation for themes

## How Has This Been Tested?
Steps are listed in the issue https://github.com/owncloud/core/issues/31170#issue-315066079

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: lib/private/App/AppManager.php [hunk 1]
```diff
@@ -531,7 +531,11 @@ public function getAppWebPath($appId) {
 				$appRoot['url'] = substr($appRoot['url'], 3);
 				$ocWebRoot = dirname($ocWebRoot);
 			}
-			return $ocWebRoot . '/' . ltrim($appRoot['url'], '/');
+			return sprintf(
```
Comment (PVince81) [inline lib/private/App/AppManager.php]: so no way to just use `trim()` instead of this exotic approach ?

Comment (VicDeo) [reply lib/private/App/AppManager.php]: @PVince81 we need to concatenate to two parts with slash and both of them potentially could already have trailing and leading slash respectively. 
this is not exotic as we officially prefer interpolation  ;)
indeed it look like this
```
$trimmedOcWebRoot = $rtrim($ocWebRoot, '/');
$trimmedAppRoot = ltrim($appRoot['url'], '/');
return "$trimmedOcWebRoot/$trimmedAppRoot";
```

**Comment by VicDeo** [comment]
@PVince81 ready for review.

**Review by PVince81 — APPROVED** [review]
:+1: code looks good, please backport for RC3

**Comment by VicDeo** [comment]
Stable10: https://github.com/owncloud/core/pull/31178
