### PR TITLE
Keep fileId for deleted Items in a separate cache

### LINKED ISSUE #30762: 'Could not get node for path' messages in log file when deleting a file/folder
### Steps to reproduce
1. create a folder
2. delete the folder
3. check the logfile

### Expected behaviour
no new messages in the log-file

### Actual behaviour
log content:
```
{"reqId":"yN2bBgP0f4ZlsxbW6o2u","level":2,"time":"2018-03-13T10:14:32+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"dav","method":"DELETE","url":"\/owncloud-core\/remote.php\/dav\/files\/admin\/folder1","message":"Could not get node for path: \"files\/admin\/folder1\" : File with name folder1 could not be located"}
```

### Server configuration
**Operating system**:
Ubuntu 17.10
**Web server:**
Apache2
**Database:**
SQLite
**PHP version:**
7.1.15
**ownCloud version:** (see ownCloud admin page)
10.1.0 prealpha (git) 
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git

**The content of config/config.php:**

```
{
    "system": {
        "license-key": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "oc35rjhx6uol",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/home\/artur\/www\/owncloud-core\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud-core",
        "dbtype": "sqlite3",
        "version": "10.1.0.0",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "loglevel": 0,
        "maintenance": false,
        "default_language": "en",
        "skeletondirectory": "\/home\/artur\/www\/owncloud-core\/tests\/acceptance\/webUISkeleton\/",
        "csrf.disabled": true,
        "enable_previews": false,
        "theme": ""
    }
}
```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - dav: 0.3.2
  - diagnostics: 0.1.0
  - enterprise_key: 0.1.3
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_texteditor: 2.2
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firewall: 2.4.2
  - gallery: 16.0.2
  - market: 0.2.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - testing: 0.1.0
  - updatenotification: 0.2.1
Disabled:
  - customgroups
  - files_antivirus
  - multidirtest
  - notifications
  - password_policy
  - security
  - theme-example
  - user_ldap
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
FF 58
**Operating system:**
Ubuntu 17.10

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes https://github.com/owncloud/core/issues/30762

## Description
Store items as `path->id` before deletion and resolve path into fileId using this cache in FileCustomPropertiesBackend.

## Motivation and Context
node is already deleted and the tree cache is purged when the property storage backend is processing the `delete` callback so it is not possible to resolve the path into id using `getNodeForPath`
As soon as file custom properties are referenced by fileId it leads to orphaned properties and log entries like this when files/directories are deleted
```
{"reqId":"yN2bBgP0f4ZlsxbW6o2u","level":2,"time":"2018-03-13T10:14:32+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"dav","method":"DELETE","url":"\/owncloud-core\/remote.php\/dav\/files\/admin\/folder1","message":"Could not get node for path: \"files\/admin\/folder1\" : File with name folder1 could not be located"}
```

## How Has This Been Tested?
1. Create a directory *folder1*
2. Delete a directory *folder1*

### expected 
No log entries

### actual
```
{"reqId":"yN2bBgP0f4ZlsxbW6o2u","level":2,"time":"2018-03-13T10:14:32+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"dav","method":"DELETE","url":"\/owncloud-core\/remote.php\/dav\/files\/admin\/folder1","message":"Could not get node for path: \"files\/admin\/folder1\" : File with name folder1 could not be located"}
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: apps/dav/lib/DeletedItemsCacheTrait.php [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+ * Provides ability to store/retrieve deleted file ids by path
+ *
+ * @package OCA\DAV
+ */
+Trait DeletedItemsCacheTrait {
+
+	/**
+	 * @var int[]
+	 */
+	protected $deletedItems = [];
```
Comment (PVince81) [inline apps/dav/lib/DeletedItemsCacheTrait.php]: use a CappedCache to avoid overflows ? in case of overflow we'd then still see the warnings that this PR is protecting against.

**Comment by PVince81** [comment]
This approach reminds me of what we do with trashbin where we take note of information before a delete and use it after, so it matches an existing pattern. I think it's a good idea.

@VicDeo would be good to know if we have any Webdav route that would cause this cache to contain lots of entries. As far as I understand we'd usually only have one entry as DELETE only applies to one item. But maybe if you delete a parent node this would contain all children ?

**Comment by VicDeo** [comment]
@PVince81 
>  if you delete a parent node this would contain all children 

can't say that for sure, need to check.

Regarding coverage: my local tests include the part of the trait that is claimed to be uncovered by codecov. Do I need to refactor the trait into a trivial C&P to convince codecov that real coverage is more than 45%?

**Comment by VicDeo** [comment]
@PVince81 According to xdebug, DELETE invoked on parent doesn't propagate to children. 
The cache is not persistent, it persists within a request only.

File: apps/dav/lib/DeletedItemsCacheTrait.php (hunk 1 above)
Comment (PVince81) [reply apps/dav/lib/DeletedItemsCacheTrait.php]: I meant CappedCache to avoid having too many items inside this array.

Good that you also checked about string overflow

**Comment by PVince81** [comment]
> my local tests include the part of the trait that is claimed to be uncovered by codecov

I'd expect codecov to pick it up if the trait's code is running during your unit tests.

> DELETE invoked on parent doesn't propagate to children.

Good to know, so it is possible that your new array in the trait will only ever contain a single item. I'd still prefer if you'd use the `CappedMemoryCache` there in case other people start using this trait so we have no memory overflow surprises. (might need a good doc, maybe rename the attribute to something about "cache" so it's clear that there is expiration involved)

**Comment by VicDeo** [comment]
@PVince81 
- refactored trait into abstract base class, let's see would it be 45% or more.
- replaced array with `CappedMemoryCache` as you like :)

**Comment by VicDeo** [comment]
@PVince81 rebased, retested manually, added more unit tests

File: apps/dav/lib/BaseServer.php [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+namespace OCA\DAV;
+
+use OC\Cache\CappedMemoryCache;
+use OCA\DAV\Connector\Sabre\Directory;
+use OCA\DAV\Connector\Sabre\File;
+
+/**
+ * Class BaseSever
+ *
+ * Provides ability to store/retrieve deleted file ids by path
```
Comment (PVince81) [inline apps/dav/lib/BaseServer.php]: this doesn't seem to be the responsibility of a class with the name "BaseServer"

it would more be along the lines of "provides base functionality for a server"

File: apps/dav/lib/BaseServer.php [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+
+
+namespace OCA\DAV;
+
+use OC\Cache\CappedMemoryCache;
+use OCA\DAV\Connector\Sabre\Directory;
+use OCA\DAV\Connector\Sabre\File;
+
+/**
+ * Class BaseSever
```
Comment (PVince81) [inline apps/dav/lib/BaseServer.php]: s/Sever/Server/

File: apps/dav/lib/BaseServer.php [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+	protected $deletedItemsCache;
+
+	/**
+	 * Get fileId by path
+	 *
+	 * @param string $path
+	 *
+	 * @return int|false
+	 */
+	public function getDeletedItemFileId($path) {
```
Comment (PVince81) [inline apps/dav/lib/BaseServer.php]: now I wonder if this could be done in a Sabre "before" event handler

Comment (VicDeo) [reply apps/dav/lib/BaseServer.php]: @PVince81 I'm afraid I'm not Sabre proficient that much. Is there any sample that I can use as a reference?

**Comment by VicDeo** [comment]
@PVince81 if I get the concept correct `BackendInterface` and `Tree` are not designed to handle events in opposite to the plugins.

Thanks for spotting out that I took a misleading class name. It's not a 'Server' but actually a 'Tree'
So I renamed it.

**Comment by VicDeo** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Review by DeepDiver1975 — DISMISSED** [review]

File: apps/dav/lib/BaseTree.php [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+				|| $node instanceof File)
+				&& $node->getId()
+			) {
+				if ($this->deletedItemsCache === null) {
+					$this->deletedItemsCache = new CappedMemoryCache();
+				}
+				$this->deletedItemsCache->set($path, $node->getId());
+			}
+		} catch (\Exception $e) {
+			// do nothing, delete will throw the same exception anyway
```
[the remark this answers is not in the document]
Comment (VicDeo) [reply apps/dav/lib/BaseTree.php]: @DeepDiver1975 ...and have two similar log entries? :)

File: apps/dav/lib/Connector/Sabre/ObjectTree.php [hunk 6]
```diff
@@ -31,12 +31,13 @@
...
 use OCA\DAV\Connector\Sabre\Exception\Forbidden;
 use OCA\DAV\Connector\Sabre\Exception\InvalidPath;
+use OCA\DAV\BaseTree;
 use OCP\Files\ForbiddenException;
 use OCP\Files\StorageInvalidException;
 use OCP\Files\StorageNotAvailableException;
 use OCP\Lock\LockedException;
 
-class ObjectTree extends \Sabre\DAV\Tree {
+class ObjectTree extends BaseTree {
```
[the remark this answers is not in the document]
Comment (VicDeo) [reply apps/dav/lib/Connector/Sabre/ObjectTree.php]: but build fails nevertheless

File: apps/dav/lib/BaseTree.php [hunk 7]
```diff
@@ -0,0 +1,84 @@
...
+	}
+
+	/**
+	 * Store fileId before deletion
+	 *
+	 * @param string $path
+	 *
+	 * @return void
+	 */
+	public function beforeDelete($path) {
```
[the remark this answers is not in the document]
Comment (VicDeo) [reply apps/dav/lib/BaseTree.php]: How this plugin should interact with the Backend?

File: apps/dav/lib/BaseTree.php (hunk 5 above)
[the remark this answers is not in the document]
Comment (DeepDiver1975) [reply apps/dav/lib/BaseTree.php]: but we need to know the excpetion - this is of interest.

**Comment by VicDeo** [comment]
@DeepDiver1975 could you have another look please?

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by VicDeo** [comment]
@PVince81 @DeepDiver1975 another review please

**Review by PVince81 — APPROVED** [review]
:+1: looks great now

**Comment by PVince81** [comment]
please backport

**Comment by VicDeo** [comment]
Stable10: https://github.com/owncloud/core/pull/31479
