### PR TITLE
Enhancement: Add test receiver mail in Email Settings Admin Panel

### LINKED ISSUE #33018: Instance server eMail address issue
### Steps to reproduce
1. Setup a new instance from scratch, but do not set the admin-user eMail address
2. Define the servers eMail settings including sender address
3. Press ``Send eMail``

Server and admin-user eMail settings see screenshots below.

### Expected behaviour
The server eMail settings with the senders address set are sufficient and the server can send(test) eMails generated. 

### Actual behaviour
You need to define a user (admin) eMail address.
This is wired and makes no sense to define a users eMail address for sending an instance eMail ?
You also should NOT send an instance eMail with the admin-user eMail address as sender as this is/can be a security breach...
And, the instance sender eMail address can be totally different from the admin-user address.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** 10.0.10.4 (stable)

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** tar

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

image

image

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
Enhancement: Add test receiver mail in Email Settings Admin Panel

With this change the admin needs to provide a test receiver mail address while
sending test mails in the Email Settings Admin Panel.
This has the advantage that the admin does not need to go back to user settings
and set the own mail address.
The user's own email will be set as preselected value if set.

## Related Issue

- Fixes #33018 

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [x] Documentation ticket raised: https://github.com/owncloud/docs/issues/4091 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiFederationToShares1-git-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32700/107/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareManagementToShares-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32700/63/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliBackground-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32700/113/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareManagementToRoot-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32700/62/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiWebdavMove1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32700/91/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiWebdavOperations-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32700/93/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareOperationsToRoot1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32700/66/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProvisioning-v2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32700/54/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliProvisioning-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32700/116/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProvisioning-v2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32703/54/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiSharePublicLink2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32703/71/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareManagementToRoot-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32703/62/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32703/166/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32703/165/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareOperationsToShares2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32704/69/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareOperationsToRoot1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32705/66/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIRenameFiles-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32705/133/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiComments-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32705/50/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareCreateSpecialToRoot1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32705/57/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingAutocomp2-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32705/139/1

File: settings/js/panels/mail.js [hunk 1]
```diff
@@ -43,11 +43,22 @@ $(document).ready(function() {
 	});
 
 	$('#sendtestmail').click(function (event) {
+		var mailToAddress = $("#mail_to_address").val().trim();
+
+		if(mailToAddress=== ''){
```
Comment (jvillafanez) [inline settings/js/panels/mail.js:48]: It might be better to add some text so it's explained what happens if the textbox is empty. Something like "if the email address is empty, the email will be sent to the configured admin's email".
We might also include a notification to say "the test email was sent to myemail@example.org" to make clear where the email has been sent.

Comment (JanAckermann) [reply settings/js/panels/mail.js:48]: ? If the address is empty, we show a notification and don't send any email

Comment (jvillafanez) [reply settings/js/panels/mail.js:48]: Ah, ok, the admin's email will be prefilled in the textbox. Yes, that's better. :+1:

**Review by jvillafanez — APPROVED** [review]

**Comment by JanAckermann** [comment]
@micbar can you merge, currently, there are no js tests for the admin panels. Adding them for 1 line of code would take a lot of time and not being accurate anyways.

**Comment by mmattel** [comment]
Please add a docs issue,
lets tell the good things !

**Review by phil-davis — APPROVED** [review]
Works - tested manually in the webUI.

Note:  there is a webUI acceptance test scenario for this in https://github.com/owncloud/core/blob/master/tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature and it passes because the admin email address is already set in the scenario.

I don't think we need to add more acceptance test permutations for the other "edge" cases.
