### PR TITLE
Disable search field in case there is no search available to the curr…

### LINKED ISSUE #14544: Nothing happens when users use the search field in most apps
As mentioned [here](https://github.com/owncloud/core/issues/11635#issuecomment-59767816), [here](https://github.com/owncloud/gallery/issues/156) and [here](https://github.com/interfasys/galleryplus/issues/37), the search field **is broken** for most apps because the mechanism has changed in oC8 and **there is no fallback in place**.

The fallback could be for the field to work like in previous versions, giving users access to a dropdown or a more drastic change could be implemented by removing the field if the app hasn't registered with the search engine.

To me, this is a regression, but I'll let the people in charge be judge of that.
@butonic @jancborchardt @DeepDiver1975

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…ent selected app - fixes #14544 

@oparoz @jancborchardt @nickvergessen @PVince81 @butonic 

@karlitschek we have this non working search field in some apps since oc8 - backport is kind of reasonable

### CODE REVIEW

**Comment by karlitschek** [comment]
yep. noticed this too. Please back port :+1:

File: core/search/js/search.js [hunk 1]
```diff
@@ -359,6 +364,14 @@
 			placeStatus();
 
 			OC.Plugins.attach('OCA.Search', this);
+
+			// hide search file if search is not enabled
+			if(self.hasFilter(getCurrentApp())) {
+				return;
+			}
+			if ($searchResults.length === 0) {
```
Comment (MorrisJobke) [inline core/search/js/search.js]: Why? This is always !== 0, because it is the div with the selector '#searchResults` and if it not exists it get created. If I remove the if statement it works as intended.

**Comment by oparoz** [comment]
Which apps can we test this with?
I've tested with galleryplus, after having disabled the part in the app which already hides the field and it did not re-appear.

**Comment by DeepDiver1975** [comment]
Files should show the search - same for the mail app.

**Comment by MorrisJobke** [comment]
@oparoz Personal/admin settings should not show the search box

File: core/search/js/search.js (hunk 1 above)
Comment (nickvergessen) [inline core/search/js/search.js]: Same issue here

**Comment by oparoz** [comment]
OK, so I can confirm that it doesn't work properly when reaching the settings page :)

File: core/search/js/search.js (hunk 1 above)
Comment (DeepDiver1975) [inline core/search/js/search.js]: I was testing this with gallery and $searchResults is empty - I took this as criteria to disable search .... let me have a second look

Comment (DeepDiver1975) [inline core/search/js/search.js]: aha - gallery has no div for app-content and the search result tag cannot be inserted

Maybe we shall not automatically add that div - if an app implements the search is should add the div explicitly.

@PVince81 @butonic @jancborchardt @MorrisJobke @nickvergessen @oparoz objections?

Comment (PVince81) [inline core/search/js/search.js]: Yes, and make the "search results" opt-in instead of opt-out.

**Comment by DeepDiver1975** [comment]
search is not opt-in - please review and test

@MorrisJobke @oparoz @jancborchardt @PVince81 @blizzz THX

**Comment by nickvergessen** [comment]
settings/apps does not have the search box anymore, although it allowed to filter the long lists.

**Comment by DeepDiver1975** [comment]
> settings/apps does not have the search box anymore, although it allowed to filter the long lists.

damn :imp:

File: core/search/js/search.js [hunk 2]
```diff
@@ -366,19 +379,16 @@
...
+			OC.Search = new OCA.Search($('#searchbox'), $('#searchresults'));
+		});
 	} else {
-		$searchResults = $('<div id="searchresults" class="hidden"/>');
-		$('#app-content')
-			.append($searchResults)
-			.find('.viewcontainer').css('min-height', 'initial');
-	}
-	$searchResults.load(OC.webroot + '/core/search/templates/part.results.html', function () {
 		OC.Search = new OCA.Search($('#searchbox'), $('#searchresults'));
```
Comment (DeepDiver1975) [inline core/search/js/search.js]: @PVince81 because the search object here is not instanciated right away the plugins are not all loaded and therefor filtering is not longer working.

What would be the ideal solution to get some kind of execution order into this?

Comment (PVince81) [inline core/search/js/search.js]: The non-ideal hacky way:
`_.defer(function() { OC.Search = ... }`.

I'll need to dig deeper into this.

Comment (PVince81) [inline core/search/js/search.js]: I do think the search box should be opt-in (at least in the future).
An app/page should tell whether it needs the search box so it can be shown and trigger events.
Else it's all just guessing / hackery.

Comment (DeepDiver1975) [inline core/search/js/search.js]: > The non-ideal hacky way:
> _.defer(function() { OC.Search = ... }.
> 
> I'll need to dig deeper into this.

THX - works - but I guess this is not deterministic?

**Comment by DeepDiver1975** [comment]
@nickvergessen fixed - care to take a second look? THX

File: core/search/js/search.js (hunk 2 above)
Comment (oparoz) [inline core/search/js/search.js]: Agreed

**Comment by nickvergessen** [comment]
Works better good now and also resolves #16823

**Comment by jancborchardt** [comment]
Good call on not showing the search box when it’s not available. Also serves as a visual reminder that we need to introduce it in some places. :+1:

**Comment by oparoz** [comment]
Removes the field in Gallery+, Settings
Keeps the field in Files, Apps

Seems to work
:+1:

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Please create the backport PRs
