### PR TITLE
Fix quota with federated sharing

### LINKED ISSUE #29169: Federation: Upload reports insufficient storage but we are far from any limit
### Steps to reproduce
1. having a federation between 10.0.2 remote (shares the folder) - 10.0.3 local (recieves the folder)
2. try uploading a file (browser or client) with 24MB to the federation recieved folder at 10.0.3

### Expected behaviour
No errors

### Actual behaviour
Error reported about insufficient storage via oC client or browser
Upload to the local 10.0.3 instance or 10.0.2 instance works (no federation) 
Upload to the federation target (10.0.2) directly, works and is distributed afterwards to 10.0.3 and W10
Free space local: 37GB
Free space remote: >200GB
No change if set in config.php ``quota_include_external_storage = false``
No local/remote user quota limit reached
Creating 2 nested directories with some smaller files in but in total 33MB (which is  of course higher than the single 24MB file) than the upload via 10.0.3 to the federation works = single filesize matters.
It worked before in this combination and suddenly stopped. The federation accepted filesizes of 350MB+ without any problems.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** 10.0.3

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** tar

**Signing status (ownCloud 9.0 and above):** no problems

**The content of config/config.php:**
[config_report_20171008.txt](https://github.com/owncloud/core/files/1366886/config_report_20171008.txt)

**List of activated apps:**
```
Enabled:
  - activity: 2.3.6
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_external_dropbox: 1.0.0
  - files_external_ftp: 0.2.0
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.2.2
  - music: 0.5.2
  - notifications: 0.3.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - theme-example
  - user_external
```

**Are you using external storage, if yes which one:** smb, federation

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Opera

**Operating system:** W10x64

#### ownCloud log (data/owncloud.log)
```
"user":"xyz","app":"webdav","method":"MOVE","url":"\/remote.php\/dav\/uploads\/xyz\/1488037006\/.file","message":"Exception: {\"Message\":\"HTTP\\\/1.1 507 Insufficient Storage\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\InsufficientStorage\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/QuotaPlugin.php(105): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\QuotaPlugin->checkQuota('\\\/abc...', 25116827)\\
n#1 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\QuotaPlugin->handleBeforeMove('uploads\\\/xyz...', 'files\\\/xyz\\\/...')\\
n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\
n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(633): Sabre\\\\Event\\\\EventEmitter->emit('beforeMove', Array)\\
n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\
n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\
n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\
n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\
n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(234): Sabre\\\\DAV\\\\Server->exec()\\
n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\
n#10 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/w...')\\
n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/QuotaPlugin.php\",\"Line\":170,\"User\":\"xyz\"}"}
```

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Fix quota with federated sharing and add tests for that.

- quota check needs to ignore -3 (unlimited) quota value (returned by federated shares with no quota)
- if unknown quota when checking a file on a federated share, check the parent
- when not checking the parent, uploading a file to a federated share through DAV upload should still properly forward the insufficient storage exception and others

## Related Issue
Fixes https://github.com/owncloud/core/issues/29169

## How Has This Been Tested?
Run federation_features/federated.feature:240 and quota.feature.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Note: I might want to move the DAV additions to a separate PR as I currently don't know how to properly automatically test this without commenting out the "check the parent instead" logic.

**Comment by PVince81** [comment]
- [ ] remove commented out code

At least this way we'll let the remote server decide in some cases whether there is enough quota when the quota is not retrievable. For that we need to properly forward the 507 error in the DAV code.

**Comment by PVince81** [comment]
- [ ] suspicious entries when running the tests:
```
[Thu Oct 12 16:45:52 2017] 127.0.0.1:51582 [201]: /public.php/webdav/testquota.txt-olddav-regular
[Thu Oct 12 16:45:53 2017] 127.0.0.1:51586 [207]: /public.php/webdav/testquota.txt-olddav-regular
[Thu Oct 12 16:45:53 2017] 127.0.0.1:51590 [207]: /public.php/webdav/
[Thu Oct 12 16:45:53 2017] Undefined index: size at /srv/www/htdocs/owncloud/lib/private/Files/View.php#1296
```

I didn't see this View warning on master, but also master doesn't have this one test.

**Comment by PVince81** [comment]
Why can't I catch this with ??
```diff
diff --git a/lib/private/Files/View.php b/lib/private/Files/View.php
index 3e4af7cf3d..9cb9bb482f 100644
--- a/lib/private/Files/View.php
+++ b/lib/private/Files/View.php
@@ -1294,6 +1294,10 @@ class View {
                try {
                        // if the file is not in the cache or needs to be updated, trigger the scanner and reload the data
                        if (!$data || $data['size'] === -1) {
+                               if (!!$data && !isset($data['size'])) {
+                                       $stack = json_encode(debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 50));
+                                       \OCP\Util::writeLog('DEBUG', 'Size not set: Stack: ' . $stack, \OCP\Util::WARN);
+                               }
                                $this->lockFile($relativePath, ILockingProvider::LOCK_SHARED);

```

**Comment by PVince81** [comment]
Ok, caught its stack trace:
```
[Thu Oct 12 17:20:32 2017] Undefined index: size at /srv/www/htdocs/owncloud/lib/private/Files/View.php#1296
[Thu Oct 12 17:20:32 2017] $data is {"checksum":"","mimetype":"application\/octet-stream","parent":"2147483889"}
[Thu Oct 12 17:20:32 2017] Size not set: Stack: [{"file":"\/srv\/www\/htdocs\/owncloud\/lib\/private\/Files\/View.php","line":1351,"function":"getCacheEntry","class":"OC\\Files\\View","type":"->"},{"file":"\/srv\/www\/htdocs\/owncloud\/apps\/files_versions\/lib\/Storage.php","line":195,"function":"getFileInfo","class":"OC\\Files\\View","type":"->"},{"file":"\/srv\/www\/htdocs\/owncloud\/apps\/files_versions\/lib\/Hooks.php","line":60,"function":"store","class":"OCA\\Files_Versions\\Storage","type":"::"},{"file":"\/srv\/www\/htdocs\/owncloud\/lib\/private\/legacy\/hook.php","line":105,"function":"write_hook","class":"OCA\\Files_Versions\\Hooks","type":"::"},{"file":"\/srv\/www\/htdocs\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php","line":283,"function":"emit","class":"OC_Hook","type":"::"},{"file":"\/srv\/www\/htdocs\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php","line":189,"function":"emitPreHooks","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"\/srv\/www\/htdocs\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","line":162,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"\/srv\/www\/htdocs\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php","line":1095,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->"},{"file":"\/srv\/www\/htdocs\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":525,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->"},{"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"\/srv\/www\/htdocs\/owncloud\/lib\/composer\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array"},{"file":"\/srv\/www\/htdocs\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->"},{"file":"\/srv\/www\/htdocs\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"\/srv\/www\/htdocs\/owncloud\/apps\/dav\/lib\/Server.php","line":236,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"\/srv\/www\/htdocs\/owncloud\/apps\/dav\/appinfo\/v2\/remote.php","line":31,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"\/srv\/www\/htdocs\/owncloud\/remote.php","line":175,"args":["\/srv\/www\/htdocs\/owncloud\/apps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}]
```

to be formatted soon...

**Comment by PVince81** [comment]
If I remove the quota from the integration test, the warning disappears... Weird.

**Comment by PVince81** [comment]
also if I set the quota high enough in the test, the warning disappears as well.

**Comment by PVince81** [comment]
If I revert every code change and keep the test, the error appears... so this existed before.

**Comment by PVince81** [comment]
I've raised https://github.com/owncloud/core/issues/29245 to explain and analyze this bug. It seems unrelated to this PR. It's just that adding the new tests brought it into view.

**Comment by PVince81** [comment]
Ok, now that we know the warning is unrelated, let's focus on finishing this.

**Review by jvillafanez — COMMENTED** [review]
Code looks good, but tests are failing

**Comment by PVince81** [comment]
Relevant failing tests:
```
19:19:53     /var/lib/jenkins/workspace/owncloud-core_core_PR-29220-7DOBZKU5OFHAVV4BVOWUOKNOOB2WEMRXAXPN3EVSUD4HDB6XAU2Q/tests/integration/features/external-storage.feature:63
19:19:53     /var/lib/jenkins/workspace/owncloud-core_core_PR-29220-7DOBZKU5OFHAVV4BVOWUOKNOOB2WEMRXAXPN3EVSUD4HDB6XAU2Q/tests/integration/features/sharing-v1.feature:597
```

**Comment by PVince81** [comment]
Ha... failing tests are failing because I added an extra check to assert that setting the quota worked. And apparently here it didn't but the test still passed.

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/29259

**Comment by PVince81** [comment]
I went through great lengths to make codecov happy: https://github.com/owncloud/core/pull/29220/commits/5b5689c0b64110afa43a2ce6407c5d0b6975cca2

- make the DAV class testable by introducing a WebdavClientService  and IWebdavClientService in core to be able to mock an instance of the Sabre Client
- add tests for the exceptions

Now waiting to see the new coverage and I'll continue adding tests for that.

**Comment by PVince81** [comment]
Let's watch the test coverage for the DAV class increase now!

**Comment by PVince81** [comment]
@jvillafanez @DeepDiver1975 please review again. To make codecov happy I had to go to great length and bootstrap unit tests for the Storage\DAV class. In my way of doing this I decided to cover all methods and discovered some small issues on the way which I fixed right away, some others which I will raise later.

File: tests/lib/Files/Storage/DavTest.php [hunk 1]
```diff
@@ -0,0 +1,1320 @@
+<?php
+/**
+ * ownCloud
+ *
+ * @author Robin Appelman
+ * @copyright 2012 Robin Appelman icewind@owncloud.com
```
Comment (PVince81) [inline tests/lib/Files/Storage/DavTest.php]: going to fix that right away...

**Comment by PVince81** [comment]
Rebased and squashed the DAV test (+fix) commits together into one.

DAV.php coverage is now 88%

File: lib/private/Http/Client/WebdavClientService.php [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+	public function __construct(IConfig $config,
+								ICertificateManager $certificateManager) {
+		$this->config = $config;
+		$this->certificateManager = $certificateManager;
+	}
+
+	/**
+	 * Instantiate new Sabre client
+	 *
+	 * @param array $settings
```
Comment (jvillafanez) [inline lib/private/Http/Client/WebdavClientService.php]: Valid settings should be known both here and in the interface

**Review by jvillafanez — APPROVED** [review]

File: lib/private/Http/Client/WebdavClientService.php [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+use OCP\IConfig;
+use OCP\ICertificateManager;
+use Sabre\DAV\Client;
+
+/**
+ * Class WebdavClientService
+ *
+ * @package OC\Http
+ */
+class WebdavClientService implements IWebdavClientService {
```
Comment (DeepDiver1975) [inline lib/private/Http/Client/WebdavClientService.php]: Should be named WebDav

File: tests/lib/Files/Storage/DavTest.php [hunk 4]
```diff
@@ -0,0 +1,1319 @@
...
+		$this->httpClientService = $this->createMock(IClientService::class);
+		$this->overwriteService('HttpClientService', $this->httpClientService);
+
+		$this->webdavClientService = $this->createMock(IWebdavClientService::class);
+		$this->overwriteService('WebdavClientService', $this->webdavClientService);
+
+		$this->timeFactory = $this->createMock(ITimeFactory::class);
+		$this->overwriteService('TimeFactory', $this->timeFactory);
+
+		$this->httpClient = $this->createMock(IClient::class);
```
Comment (DeepDiver1975) [inline tests/lib/Files/Storage/DavTest.php]: missing use of IClient

**Comment by PVince81** [comment]
I've copied the Sabre client settings PHPDoc into the interface and WebdavClientService.

Since CI was all green and the PHPDoc will not affect it, I'm merging this directly.

**Comment by DeepDiver1975** [comment]
I was still right in the middle of review ....

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/29325

**Comment by PVince81** [comment]
@DeepDiver1975 sorry, please continue then. I'll adjust in a subsequent PR.

File: tests/lib/Files/Storage/DavTest.php [hunk 5]
```diff
@@ -0,0 +1,1319 @@
...
+	public function testHasUpdatedRootPathMethodNotAllowed() {
+		$this->davClient->expects($this->once())
+			->method('propfind')
+			->willThrowException($this->createClientHttpException(Http::STATUS_METHOD_NOT_ALLOWED));
+
+		$this->instance->hasUpdated('', 1508496363);
+	}
+
+	/**
+	 * @expectedException OCP\Files\StorageNotAvailableException
```
Comment (DeepDiver1975) [inline tests/lib/Files/Storage/DavTest.php]: namespace looks strange

bildschirmfoto von 2017-10-23 12-20-52

File: tests/lib/Files/Storage/DavTest.php [hunk 6]
```diff
@@ -0,0 +1,1319 @@
...
+	 */
+	private $httpClientService;
+
+	/**
+	 * @var IWebdavClientService
+	 */
+	private $webdavClientService;
+
+	/**
+	 * @var Client
```
Comment (DeepDiver1975) [inline tests/lib/Files/Storage/DavTest.php]: please add | PHPUnit_Framework_MockObject_MockObject - this will fix issues with calling mock methods on these objects

bildschirmfoto von 2017-10-23 12-23-03

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 sorry, please continue then. I'll adjust in a subsequent PR.

done

File: tests/lib/Files/Storage/DavTest.php (hunk 4 above)
Comment (PVince81) [reply tests/lib/Files/Storage/DavTest.php]: it's there: https://github.com/owncloud/core/pull/29220/files/4ba6cda1191234542d58f0b5be415392adca214b#diff-52c6f7ef7e46328fff29098af83d4b3cR26

**Comment by PVince81** [comment]
Follow up PR for the review items: https://github.com/owncloud/core/pull/29327

**Comment by PVince81** [comment]
regression: https://github.com/owncloud/core/pull/29422
