### PR TITLE
Treat send attempt as unsuccessful when there is a message.

### LINKED ISSUE #35218: Sharer gets "Email notification was sent!" message even when the email was not sent
# Steps to reproduce
``` behat
Scenario 1: user should get an error message when trying to send notification by email to a user who has not setup their email
    Given parameter "shareapi_allow_mail_notification" of app "core" has been set to "yes"
    And user "user1" has logged in using the webUI
    And user "user1" has shared file "lorem.txt" with user "user2"
    And the user has opened the share dialog for file "lorem.txt"
    When the user sends the share notification by email using the webUI
    Then a notification should be displayed on the webUI with the text "Email notification was not sent!"
```

- Note: In the first scenario the email of the receiver is not set.

``` behat
Scenario 2: user should get an error message when trying to send notification when email server setting is invalid
    Given parameter "shareapi_allow_mail_notification" of app "core" has been set to "yes"
    And user "user1" has logged in using the webUI
    And user "user1" has shared file "lorem.txt" with user "user2"
    And the user has opened the share dialog for file "lorem.txt"
    When the user sends the share notification by email using the webUI
    Then a notification should be displayed on the webUI with the text "Email notification was not sent!"
```
- Note: In the second scenario set the receiver's email but change your Email Server setting in Admin General settings page to invalid one.

# Actual behaviour
User should get an error message saying "Email notification was sent!"

# Expected behaviour
User should get an error message saying "Email notification was not sent!"

c.c @individual-it @phil-davis @PVince81 

# Response in DevTools
`{"ocs":{"meta":{"status":"ok","statuscode":200,"message":"Couldn't send mail to following recipient(s): arkouser ","totalitems":"","itemsperpage":""},"data":[]}}`

### PR DESCRIPTION
**Pull request by VicDeo**
## Description
`result.ocs.meta.status` is 200 when the email was not sent.

## Related Issue
- Fixes #35218 

## Motivation and Context
Frontend says that email is  successfully sent even when it has been not sent.

## How Has This Been Tested?
See #35218 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by VicDeo** [comment]
10.2.0: https://github.com/owncloud/core/pull/35221

File: core/js/sharedialogshareelistview.js [hunk 1]
```diff
@@ -369,7 +369,7 @@
 			$loading.removeClass('hidden');
 
 			this.model.sendNotificationForShare(shareType, shareWith, true).then(function(result) {
-				if (result.ocs.meta.status === 'ok') {
+				if (result.ocs.meta.message === null) {
```
Comment (PVince81) [inline core/js/sharedialogshareelistview.js]: does it mean the server sends "ok" even for failures??

Comment (phil-davis) [reply core/js/sharedialogshareelistview.js]: comment https://github.com/owncloud/core/issues/35218#issuecomment-492172983

Comment (VicDeo) [reply core/js/sharedialogshareelistview.js]: @PVince81 ok and numeric 200. There are some tricky situations e.g. when we have a group of recipients and some have been notified while others have been not. 
I think it would be better to rely on the message content directly instead of checking the status.

Comment (PVince81) [reply core/js/sharedialogshareelistview.js]: what was the logic before we cleant up the code ?
I'd align to whatever logic we had before the cleanup

Comment (PVince81) [reply core/js/sharedialogshareelistview.js]: with cleanup I mean https://github.com/owncloud/core/pull/33180

Comment (PVince81) [reply core/js/sharedialogshareelistview.js]: clarified here https://github.com/owncloud/core/issues/35218#issuecomment-492249886

in the light of this, the change makes sense. thanks

**Comment by VicDeo** [comment]
@PVince81  is it better now?

**Comment by paurakhsharma** [comment]
Acceptance test related to this feature is here: https://github.com/owncloud/core/pull/35215

**Comment by PVince81** [comment]
@VicDeo yes.

would be good to update unit tests where possible

**Review by PVince81 — APPROVED** [review]
:+1:
