### PR TITLE
[full-ci] Trigger file scan after accepting a federated share

### LINKED ISSUE #970: [QA] Activity when receiving a federated share is missing in sidebar and `Activities by others`
### Steps to reproduce
1. Receive and accept a share from a federated OC system
2. Check the sidebar and you activity stream

### Expected behaviour
The activity should be listed in the file sidebar and in the activity stream in `Activities by others`

### Actual behaviour
The activity is missing in the file sidebar as well as in `Activities by others`

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
This is necessary as we need the `fileId` to pass it to the `remoteshare.accepted` event. The activity app can then hook in to this event and update the activity by setting the correct `fileId` (see https://github.com/owncloud/activity/pull/972). The `shareId` has been added to the published activity which is used to retrieve the activity later when it is updated.

Also added a short translation for the `SUBJECT_REMOTE_SHARE_RECEIVED` activity.

## Related Issue

- Fixes https://github.com/owncloud/activity/issues/970

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>cliExternalStorage-latest-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

File: apps/files_sharing/lib/External/Manager.php [hunk 1]
```diff
@@ -208,15 +208,43 @@ public function acceptShare($id) {
...
+				'owner'		=> $share['owner']
+			];
+
+			$mount = $this->getMount($options);
+			$storage = $mount->getStorage();
+			$fileId = null;
+
+			if ($storage) {
+				$scanner = $storage->getScanner('');
+				$file = $scanner->scanFile('');
```
Comment (jvillafanez) [inline apps/files_sharing/lib/External/Manager.php:224]: We might need some comments here. I was confused because it seems you'll be scanning the same file regardless of what's being accepted.
I guess the storage will be different per accepted share, as well as the scanner, which would point to a different file depending on the share, so the "root" which will be scanned will be different.

In addition, it might be a good idea to include a comment explaining why you need a `scanFile` and not a `scan`. In case the share points to a folder, I think you'll only scan the folder itself without going deeper. I'm not sure if that's what we want or not. Note that a swallow scan (not just a simple `scanFile`) can be very expensive.

**Comment by phil-davis** [comment]
This is a bit behind `master` (9 commits behind) - I noticed because the message about "Acceptance tests failed" is in an old format.

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>cliExternalStorage-latest-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>cliExternalStorage-10.6.0-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>cliExternalStorage-git-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by JammingBen** [comment]
Rebased 👍

File: apps/files_sharing/lib/External/Manager.php [hunk 2]
```diff
@@ -208,15 +208,43 @@ public function acceptShare($id) {
...
 
-			$event = new GenericEvent(null, ['sharedItem' => $share['name'], 'shareAcceptedFrom' => $share['owner'],
-				'remoteUrl' => $share['remote']]);
+			$event = new GenericEvent(
+				null,
+				[
+					'sharedItem' => $share['name'],
+					'shareAcceptedFrom' => $share['owner'],
+					'remoteUrl' => $share['remote'],
+					'fileId' => $fileId,
```
Comment (jvillafanez) [inline apps/files_sharing/lib/External/Manager.php:242]: the fileId could be null, so it's a good idea to include a comment to clarify it's intended or it's handled.

**Comment by JanAckermann** [comment]
@phil-davis @jvillafanez 
After accepting a share we trigger the file scan for the home folder of the user, to get the file cache entry for the share, this is why the ETag is changing and results in failing tests, IHMO we should to the opposite and test if the ETag will change, agree?

**Comment by jvillafanez** [comment]
I think it makes sense that we trigger an etag change because, from the user's perspective, it's a new file / folder that appears in the tree.
You can also check what happens when the `share_folder` configuration is present in the config.php file.

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliExternalStorage-git-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30778/124/1

**Comment by phil-davis** [comment]
> @phil-davis @jvillafanez
> After accepting an external share we trigger the file scan for the home folder of the user, to get the file cache entry for the share, this is why the ETag is changing and results in failing tests, IHMO we should to the opposite and test if the ETag will change, agree?

Agree.

I edited the PR title to say `[full-ci]` - that will prevent the "fail early" CI behavior. So next time you trigger CI, every pipeline will run to completion and you get to see all the failing test scenarios.

**Comment by phil-davis** [comment]
I restarted CI just now.

File: apps/files_sharing/lib/External/Manager.php (hunk 1 above)
Comment (JammingBen) [reply apps/files_sharing/lib/External/Manager.php:228]: Added some comments, do you think it's more clear now?

**Comment by jvillafanez** [comment]
".htaccess" and "Makefile" files shouldn't be touched.

**Comment by JammingBen** [comment]
> I think it makes sense that we trigger an etag change because, from the user's perspective, it's a new file / folder that appears in the tree.

Actually this is not happening with the file scan. But it's not related to our change.

To test this, I shared a folder with a local user. After logging in with that user the new folder was inserted in the filecache table. But the etag of the home folder did not change. So it seems to behave like this in general.

**Review by jvillafanez — APPROVED** [review]
