### PR TITLE
Fix namespace XML output of files and tags dav

### LINKED ISSUE #20930: Sabre namespaces weirdness in response since upgrade to 3.0
In the past, Sabre properly added the OC namespace in the "?xml" tag.

But now it just adds the namespace inline in the response, which might disturb our hacky XML parsing workaround for IE:

sabre-namespace

Maybe there's a new API that we forgot to call to make it look right ? @DeepDiver1975 @evert

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/20930

To test, open the web UI and inspect the "webdav/" call and see if the response contains "oc:xxx" elements instead of "x:xxx" elements.

@DeepDiver1975 @icewind1991 @MorrisJobke @nickvergessen

### CODE REVIEW

**Comment by icewind1991** [comment]
Tested, looks good :+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

File: apps/dav/lib/connector/sabre/tagsplugin.php [hunk 1]
```diff
@@ -107,7 +107,7 @@ public function __construct(\Sabre\DAV\Tree $tree, \OCP\ITagManager $tagManager)
 	 */
 	public function initialize(\Sabre\DAV\Server $server) {
 
-		$server->xmlNamespaces[self::NS_OWNCLOUD] = 'oc';
+		$server->xml->namespacesMap[self::NS_OWNCLOUD] = 'oc';
```
Comment (phil-davis) [inline apps/dav/lib/connector/sabre/tagsplugin.php:110]: This as a typo, it should be 
`namespaceMap`
See PR #40943 for the fix.
