### PR TITLE
Fixing email sent to recipient using recipients language code

### LINKED ISSUE #33397: Language of internal sharing email notification should be in recipient language
### Steps to reproduce
1. Share folder/file to another internal ownCloud user
2. Notify user by email

### Expected behaviour
The ownCloud user should get the notification email in his language

### Actual behaviour
The email is sent in the language from the user who shared the folder, but this not necessarily the language of the email recipient.

### Server configuration
**ownCloud version:** 10.0.10

**Updated from an older ownCloud or fresh install:** updated

### PR DESCRIPTION
**Pull request by sharidas**
The recipient, internal to owncloud instance should
recieve the email from the sender ( internal to owncloud )
in the language chosen by the recipient.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

While sharing the file/folders to internal user(s), the notification mail sent should be based on the language configured for recipient(s). Currently that is not the case. ownCloud instance is aware of the internal users. Hence this change tries to grab the recipients language stored in the preferences table. And then tries to compare with the senders setting. If they are different, then recipients language is used.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/33397

## Motivation and Context

Try to use recipients language while sending notification mails. At least this should be for the internal users of oC instance.

## How Has This Been Tested?

- Create 2 users `admin`, `user1`
- Set the language for `user1` as `castellano`.
- In the settings page of `admin` set the option `Allow users to send mail notification for shared files`
- Now try to share a folder to `user1`. User would see a button `notify by email`. Click the button.
- Once the `Email notification sent succesfully` notification is displayed, check the email
- The email is in the language opted by the `user1`.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by sharidas** [comment]
- [ ] Investigate if there are any more details to look at. Like if there are any other mail notification changes required?

File: lib/private/Share/MailNotifications.php [hunk 1]
```diff
@@ -180,8 +180,16 @@ public function sendInternalShareMail($node, $shareType, $recipientList) {
 			$filename = $filter->getFile();
 			$link = $filter->getLink();
 
-			$subject = (string) $this->l->t('%s shared »%s« with you', [$this->senderDisplayName, $unescapedFilename]);
-			list($htmlBody, $textBody) = $this->createMailBody($filename, $link, $expiration, null, 'internal');
+			$recipientLanguageCode = $this->config->getUserValue($recipient->getUID(), 'core', 'lang', 'en');
+			$recipientL10 = \OC::$server->getL10N('core');
```
Comment (PVince81) [inline lib/private/Share/MailNotifications.php]: `recipientL10N`

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@sharidas please backport
