### PR TITLE
Do not allow to store boolean configs, they behave unexpected on postgres

### LINKED ISSUE #23776: Should not allow to store boolean values in oc_preferences
As per https://github.com/owncloud/core/issues/23761 

Failing test scenario:
```php
	public function testGetUserValueBoolean() {
		$config = $this->getConfig();

		$config->setUserValue('userGetUnset', 'appGetUnset', 'keyGetUnset1', false);
		$config->setUserValue('userGetUnset', 'appGetUnset', 'keyGetUnset2', true);

		$config = $this->getConfig();
		$this->assertEquals(false, $config->getUserValue('userGetUnset', 'appGetUnset', 'keyGetUnset1'));
		$this->assertEquals(true, $config->getUserValue('userGetUnset', 'appGetUnset', 'keyGetUnset2'));
	}
```

I think we should simply throw an exception in 9.1+ when someone tries to store a boolean, to make people aware of the problem. Opinions @DeepDiver1975 @MorrisJobke @LukasReschke

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #23776

### CODE REVIEW

File: lib/private/AllConfig.php [hunk 1]
```diff
@@ -201,8 +202,13 @@ public function deleteAppValues($appName) {
 	 * @param string $value the value that you want to store
 	 * @param string $preCondition only update if the config value was previously the value passed as $preCondition
 	 * @throws \OCP\PreConditionNotMetException if a precondition is specified and is not met
+	 * @throws \UnexpectedValueException when trying to store an unexpected value
 	 */
 	public function setUserValue($userId, $appName, $key, $value, $preCondition = null) {
+		if (is_bool($value) || is_null($value)) {
+			throw new \UnexpectedValueException('Only strings and integers are allowed as value');
```
Comment (ChristophWurst) [inline lib/private/AllConfig.php]: what if someone passes a float? Or an object?

Comment (nickvergessen) [inline lib/private/AllConfig.php]: Well that is not a big thing I'd say, the most problematic case is bool and null which are stored as string `t`, string `f` and string `n` on postgres.

But sure could also check for is_int and is_string

Comment (ChristophWurst) [inline lib/private/AllConfig.php]: In my opinion that would make the code less error-prone if we check for the types that *are* allowed (some kind of whitelisting instead of blacklisting)

Comment (nickvergessen) [inline lib/private/AllConfig.php]: done

**Comment by ChristophWurst** [comment]
one failing test
```
04:59:44 There was 1 failure:
04:59:44 
04:59:44 1) Test\PublicNamespace\OCPConfigTest::testSetAppValueIfSetToNull
04:59:44 Failed asserting that false is true.
04:59:44 
04:59:44 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/PublicNamespace/OCPConfigTest.php:31
```
:+1: but changes look good

Should we drop a mail to the mailing list? I assume this could break some apps

**Comment by georgehrke** [comment]
👍 change looks good, but the failing test should obviously be fixed 🙈 

> Should we drop a mail to the mailing list? I assume this could break some apps

+1 and don't backport

**Comment by nickvergessen** [comment]
> Should we drop a mail to the mailing list?

Yes

> I assume this could break some apps

Well not more then they already have been on postgres, see https://github.com/owncloud/core/issues/23761

**Comment by icewind1991** [comment]
Woudn't it be enough to just cast the bool to an int?

**Comment by nickvergessen** [comment]
Not really, since if someone is trying to store a boolean and does a get() === true or something later, its failing as well. To prevent that we just make sure on storing, that we can store the value correctly

**Comment by guruz** [comment]
👍

**Comment by nickvergessen** [comment]
Mail sent: https://mailman.owncloud.org/pipermail/devel/2016-June/002540.html
