### PR TITLE
Move methods to the factory that are not related to translating, but to guessing/finding the language

### LINKED ISSUE #14663: L10N epic ticket
There are several things wrong with our L10N classes/methods.

- [x] The `OC\L10N\Factory` has no public interface and there for can not be used by apps: https://github.com/owncloud/core/pull/18620
- [x] The public interface is missing a stub for some of the methods
- [x] The OC_L10N class should be using a namespace
- [x] The methods related to guessing the language, should be moved to the factory,
same applies to all find, exists and force methods aswell
- [x] the L10N class should not have a static method `get()`, instead the factory should be used
- [x] `t()` should return a string, instead of a OC_L10N_String object by default, for saver usage: https://github.com/owncloud/activity/pull/215#issuecomment-69944160

@DeepDiver1975

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #14663
- Move methods to the factory that are not related to translating, but to guessing/finding the language
- Create a new L10N object that uses DI, namespace and returns strings, instead of objects of a private type

cc @MorrisJobke @LukasReschke @DeepDiver1975

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
looks good - can we add more tests to the new factory methods? THX

**Comment by nickvergessen** [comment]
On the way

**Comment by DeepDiver1975** [comment]
> On the way

youre-awesome

File: lib/private/l10n/factory.php [hunk 1]
```diff
@@ -25,16 +25,49 @@
 
 namespace OC\L10N;
 
+use OCP\IConfig;
+use OCP\IRequest;
+use OCP\ISession;
```
Comment (nickvergessen) [inline lib/private/l10n/factory.php]: woops, not needed

**Comment by DeepDiver1975** [comment]
````
07:53:03 ...........................................PHP Fatal error:  Uncaught TypeError: Argument 1 passed to OC\L10N\Factory::__construct() must implement interface OCP\IConfig, none given, called in phar:///usr/local/bin/phpunit/phpunit-mock-objects/Framework/MockObject/Generator.php on line 254 and defined in /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/lib/private/l10n/factory.php:67
07:53:08 Stack trace:
07:53:08 #0 phar:///usr/local/bin/phpunit/phpunit-mock-objects/Framework/MockObject/Generator.php(254): OC\L10N\Factory->__construct()
07:53:08 #1 phar:///usr/local/bin/phpunit/phpunit-mock-objects/Framework/MockObject/Generator.php(225): PHPUnit_Framework_MockObject_Generator->getObject('class Mock_Fact...', 'Mock_Factory_71...', '\\OC\\L10N\\Factor...', true, true, Array, false, NULL)
07:53:08 #2 phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php(1259): PHPUnit_Framework_MockObject_Generator->getMock('\\OC\\L10N\\Factor...', Array, Array, '', true, true, true, false, false)
07:53:08 #3 /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/apps/fi in /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/lib/private/l10n/factory.php on line 67

**Comment by nickvergessen** [comment]
- [ ] Add tests for findLanguage
- [ ] Add tests for findAvailableLanguages
- [ ] Add tests for get

**Comment by nickvergessen** [comment]
Ready to review @DeepDiver1975 @MorrisJobke

File: apps/files_sharing/tests/activity.php [hunk 2]
```diff
@@ -41,11 +41,13 @@ class Activity extends \OCA\Files_Sharing\Tests\TestCase {
 	protected function setUp() {
 		parent::setUp();
 		$this->activity = new \OCA\Files_Sharing\Activity(
-			$this->getMock('\OC\L10N\Factory'),
-			$this->getMockBuilder('\OCP\IURLGenerator')
+			$this->getMockBuilder('OCP\L10N\IFactory')
 				->disableOriginalConstructor()
 				->getMock(),
-			$this->getMockBuilder('\OCP\Activity\IManager')
+			$this->getMockBuilder('OCP\IURLGenerator')
```
Comment (rullzer) [inline apps/files_sharing/tests/activity.php]: small tip. When mocking interfaces: `$this->getMock('OCP\IURLGenerator')` is good enough... since there is no constructor.

File: lib/private/l10n.php [hunk 3]
```diff
@@ -82,56 +83,29 @@ class OC_L10N implements \OCP\IL10N {
...
+			$lang = \OC::$server->getL10NFactory()->findLanguage($app);
+		}
+
+		$this->lang = $lang;
 	}
 
 	/**
 	 * @param $transFile
-	 * @param bool $mergeTranslations
 	 * @return bool
```
Comment (rullzer) [inline lib/private/l10n.php]: also `@deprecated`?

**Comment by rullzer** [comment]
Probably a good idea to move ` lib/private/l10n.php` to `lib/private/legacy/l10n.php`. To cleanup `lib/private` a bit.

**Comment by rullzer** [comment]
All still works! And a lot cleaner.
:+1:

File: apps/files_sharing/tests/activity.php (hunk 2 above)
Comment (nickvergessen) [inline apps/files_sharing/tests/activity.php]: I know, for interfaces that is okay, but when you deal with an instance and then someone adds a constructor later on the test fails...
So in order to prevent that I only use this one way

File: lib/private/l10n.php (hunk 3 above)
Comment (nickvergessen) [inline lib/private/l10n.php]: The hole class is deprecated...

**Comment by nickvergessen** [comment]
Moved and rebased

**Comment by MorrisJobke** [comment]
Tested and still works :+1:

**Comment by LukasReschke** [comment]
This breaks the setup: https://github.com/owncloud/core/issues/21955
