### PR TITLE
CORS add url only allow http or https protocol

### LINKED ISSUE #37644: CORS domain accepts weird protocols
### Steps to reproduce
1. Go to setting > personal > security
2. Add "fifif://localhost"

### Expected behaviour
Only http(s) protocols should be accepted. That domain should fail.

### Actual behaviour
CORS domain is saved

### Server configuration
**Operating system**:

**Web server:** apache

**Database:** mysql

**PHP version:** 7.4

**ownCloud version:** 10.5.0 RC3

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
In Settings->Security you can add CORS urls.
Due not checking the protocol it is easy for the user to make mistakes without knowing the reason.
From now, we validate CORS url protocol is http or https based and also trim white spaces. 

## Related Issue

- Fixes https://github.com/owncloud/core/issues/37644

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [x] Documentation ticket raised: <https://github.com/owncloud/docs/issues/2869> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

File: settings/Controller/CorsController.php [hunk 1]
```diff
@@ -163,6 +163,14 @@ public function removeDomain($domain) {
 	 * @return boolean      whether URL is valid
 	 */
 	private function isValidUrl($url) {
-		return (\filter_var($url, FILTER_VALIDATE_URL) !== false);
+		$path = \parse_url($url, PHP_URL_PATH);
+		$encoded_path = \array_map('urlencode', \explode('/', $path));
```
Comment (DeepDiver1975) [inline settings/Controller/CorsController.php:167]: Why all this encode-fu?

```
$schem = parse_url($url, PHP_URL_SCHEME)
return $scheme === 'http || $scheme === 'https;

File: settings/js/panels/cors.js [hunk 2]
```diff
@@ -48,7 +48,7 @@ $(document).ready(function () {
         $('#corsAddNewDomain').attr('disabled', true);
         $.post(
             OC.generateUrl('/settings/domains'),
-            { domain : $('#domain').val()},
+            { domain : $('#domain').val().trim()},
```
Comment (DeepDiver1975) [inline settings/js/panels/cors.js:51]: should be done server side .... generally speaking ....

**Review by DeepDiver1975 — DISMISSED** [review]

File: changelog/unreleased/37664 [hunk 3]
```diff
@@ -0,0 +1,5 @@
+Bugfix: Only allow http/https protocol on CORS
+
+Adding a white-listed domain allowed strange protocols like kkk://google.de, restricted to http/https
```
Comment (phil-davis) [inline changelog/unreleased/37664:3]:
```suggestion
Adding a white-listed domain allowed strange protocols like zzz://google.de, restricted to http/https
```

"kkk" is an unfortunate acronym in conjunction with "white"-list. Maybe don't issue a changelog with those 2 things on the same line.

**Review by phil-davis — COMMENTED** [review]
Looks OK to me. But @DeepDiver1975 please review again.

**Comment by mmattel** [comment]
@DeepDiver1975 I know that you are very busy, but could you add a statement if you agree to the PR? If ok, we could proceed :smile: Many thanks

File: settings/Controller/CorsController.php [hunk 4]
```diff
@@ -103,7 +103,7 @@ public function getDomains() {
 	 * @return JSONResponse
 	 */
 	public function addDomain($domain) {
-		if ($this->isValidUrl($domain)) {
+		if ($this->isValidUrl($domain) && $this->isValidProtocol($domain)) {
```
Comment (jvillafanez) [inline settings/Controller/CorsController.php:106]: You can move the check for the protocol inside the `isValidUrl` method, and include a comment here about what we expect. For me, a domain doesn't include the protocol, but it's seems required here.

In addition, note that we might need to parse the whole url. It seems you can add something like `https://example.com:7777/oc/test?myping=abcd#info`, which could be validated as true, but I don't think is a valid CORS value

Comment (HieronymusPerro) [reply settings/Controller/CorsController.php:106]: Why this should not be a valid CORS value https://example.com:7777/oc/test?myping=abcd#info 
If you look to the RFC port is an important part of CORS and paths and queries should be ignored.

Comment (HieronymusPerro) [reply settings/Controller/CorsController.php:106]: But yeah I will have a look at this very soon!

**Comment by HieronymusPerro** [comment]
According to @jvillafanez this has now updated in favor of:
- Only allow http / https protocol
- Don't allow url paths like http://example.com/hello world
- Don't allow url querys like http://example.com?test=true

File: settings/Controller/CorsController.php [hunk 5]
```diff
@@ -163,6 +154,26 @@ public function removeDomain($domain) {
...
 	 */
 	private function isValidUrl($url) {
-		return (\filter_var($url, FILTER_VALIDATE_URL) !== false);
+		// Check if uri is valid
+		if (\filter_var($url, FILTER_VALIDATE_URL) === false) {
+			return false;
+		}
+
+		// Check if uri protocol is http or https
+		if (\parse_url($url, PHP_URL_SCHEME) !== 'http' && \parse_url($url, PHP_URL_SCHEME) !== 'https') {
```
Comment (jvillafanez) [inline settings/Controller/CorsController.php:163]: not sure how the function is implemented, but I'm confident that calling the `parse_url` function once in order to parse the whole string is more efficient than calling it several times.

In addition, the `filter_var` might be obsolete if we rely on the `parse_url` because it should return false if it can't parse the url.

Comment (HieronymusPerro) [reply settings/Controller/CorsController.php:163]: >In addition, the filter_var might be obsolete if we rely on the parse_url
that's not true.

parse_url(1);

returns the following

array(1) {
  ["path"]=>
  string(1) "1"
}

Comment (HieronymusPerro) [reply settings/Controller/CorsController.php]: @jvillafanez 
Please review again. I don't like this approach that much, even if it is more efficient, it lacks of readability.

Comment (jvillafanez) [reply settings/Controller/CorsController.php]: what about using type hinting in the function definition to ensure the url is a string? is it good enough to remove the filter_var check?

for the other checks, you could try:
```
// parsed url mustn't contain the following pieces
$mustBeMissing = ['user', 'pass', 'path', 'query', 'fragment'];
foreach ($mustBeMissing as $piece) {
  if (isset($parsedUrl[$piece])) {
    return false;
  }
}
```
you'd still need to check the scheme, but the current code is fine

File: settings/Controller/CorsController.php [hunk 6]
```diff
@@ -162,7 +153,26 @@ public function removeDomain($domain) {
 	 * @param  string  $url URL to check
 	 * @return boolean      whether URL is valid
 	 */
-	private function isValidUrl($url) {
-		return (\filter_var($url, FILTER_VALIDATE_URL) !== false);
+	private function isValidUrl(string $url) {
+		$notAllowedUrlComponents = ['user', 'pass', 'path', 'query', 'fragment'];
```
Comment (jvillafanez) [inline settings/Controller/CorsController.php:157]: I'd prefer to move this close to where it's going to be used. It's up to you if you want to make this change or not.

File: settings/Controller/CorsController.php [hunk 7]
```diff
@@ -162,7 +153,26 @@ public function removeDomain($domain) {
...
+		$parsedUrl = \parse_url($url);
+
+		if (!$parsedUrl) {
+			return  false;
```
Comment (jvillafanez) [inline settings/Controller/CorsController.php:161]: double space between "return" and "false"

**Review by jvillafanez — APPROVED** [review]
Just a couple of minor details. Note that you still need to adjust the code style according to drone.
I'm approving since these are minor optional changes (other than the drone's ones) which won't affect the functionality.

**Comment by mmattel** [comment]
@HieronymusPerro 
> ...this has now updated in favor of:
> - Only allow http / https protocol
> - Don't allow url paths like http://example.com/hello_world
> - Don't allow url querys like http://example.com?test=true

Please file a doc issue, because this needs a doc change in: https://github.com/owncloud/docs/blob/master/modules/user_manual/pages/personal_settings/security.adoc

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/27686/2/7
code style failed.

**Comment by mmattel** [comment]
@HieronymusPerro ping regarding https://github.com/owncloud/core/pull/38101#issuecomment-732810945 as this PR is now merged, thanks.

**Comment by HieronymusPerro** [comment]
> @HieronymusPerro ping regarding [#38101 (comment)](https://github.com/owncloud/core/pull/38101#issuecomment-732810945) as this PR is now merged, thanks.

Can you explain exactly what action is required from my side or link an explanation?
Thx

**Comment by mmattel** [comment]
This is easy :smile:
open an issue in docs and describe that there is a change necessary for the CORS documentation (user manual) and add the link to the cors doc I provided above so it can be easier identified where to write. Add a reference to this core PR so we see in docs where it belongs to and here that an issue has been created. When the docs PR has been merged, the issue will be closed and we can see from all sides nothing is open. Please also add in the issue that this will be part of the 10.6 release.

**Comment by HieronymusPerro** [comment]
Thank you, done =)
> Please also add in the issue that this will be part of the 10.6 release.
Can you explain where? There is no milestone/project or label for 10.6

**Comment by HieronymusPerro** [comment]
> This is easy 
> open an issue in docs and describe that there is a change necessary for the CORS documentation (user manual) and add the link to the cors doc I provided above so it can be easier identified where to write. Add a reference to this core PR so we see in docs where it belongs to and here that an issue has been created. When the docs PR has been merged, the issue will be closed and we can see from all sides nothing is open. Please also add in the issue that this will be part of the 10.6 release.

Thank you, done =)
> Please also add in the issue that this will be part of the 10.6 release.

Can you explain where? There is no milestone/project or label for 10.6
