### PR TITLE
Fix "invalid date" on share expiration

### LINKED ISSUE #32056: empty Expiration date results in "invalid date" entry
### Steps to reproduce
1. enforce public link expiration date
2. create a new public link, delete the expiration date
3. click Share
4. click Share again
5. click Cancel
6. view the settings of new link

### Expected behaviour
the UI should tell you that the expiration date is required and let you enter a correct date

### Actual behaviour
after point 3 its not possible to enter a new date
image

after point 6 "Invalid date" is shown
image

problem happens only on master branch, cannot reproduce on stable10

### Server configuration
**Operating system**:
Ubuntu 17.10

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.1

**ownCloud version:** (see ownCloud admin page)
10.1 (master branch)

**Updated from an older ownCloud or fresh install:**
fresh

**Where did you install ownCloud from:**
git

**The content of config/config.php:**

```
{
    "system": {
        "license-key": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "ocuv4s8d5xsv",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/home\/artur\/www\/owncloud-core\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud-core",
        "dbtype": "mysql",
        "version": "10.1.0.1",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 1,
        "maintenance": false,
        "skeletondirectory": "\/home\/artur\/www\/owncloud-core\/tests\/acceptance\/skeleton",
        "default_language": "en",
        "singleuser": false,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "1025",
        "csrf.disabled": "true",
        "ldapIgnoreNamingRules": false,
        "sharing.federation.allowHttpFallback": true,
        "files_external_allow_create_new_local": "true",
        "enable_previews": false,
        "cors.allowed-domains": [
            "http:\/\/localhost:8300"
        ],
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - dav: 0.3.2
  - diagnostics: 0.1.0
  - enterprise_key: 0.1.4
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firewall: 2.5.0
  - gallery: 16.0.2
  - market: 0.2.3
  - notifications: 0.3.3
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
  - windows_network_drive: 0.7.0
Disabled:
  - customgroups
  - files_antivirus
  - files_primary_s3
  - guests
  - multidirtest
  - oauth2
  - password_policy
  - security
  - testing
  - user_ldap
  - user_management

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
FF 61

**Operating system:**
Ununtu 17.10

#### Browser log
after point 3 POST Request:

|field|data|
|--|--|
|expireDate |  |
|name | FOLDER link|
|path | /FOLDER|
|permissions | 1|
|shareType | 3|

Response:
```
{"ocs":{"meta":{"status":"ok","statuscode":200,"message":null},"data":{"id":"5","share_type":3,"uid_owner":"admin","displayname_owner":"admin","permissions":1,"stime":1531741345,"parent":null,"expiration":"2018-07-23 00:00:00","token":"3LLLdfwFBIsxrm8","uid_file_owner":"admin","displayname_file_owner":"admin","path":"\/FOLDER","item_type":"folder","mimetype":"httpd\/unix-directory","storage_id":"home::admin","storage":1,"item_source":"9","file_source":"9","file_parent":"2","file_target":"\/FOLDER","share_with":null,"share_with_displayname":null,"name":"FOLDER link","url":"http:\/\/localhost\/owncloud-core\/index.php\/s\/3LLLdfwFBIsxrm8","mail_send":0}}}
```

after point 4 PUT request:

|field|data|
|--|--|
|expireDate |  |
|name | FOLDER link|
|permissions | 1|
|shareType | 3|

response:
```
{"ocs":{"meta":{"status":"failure","statuscode":400,"message":"Expiration date is enforced"},"data":[]}}
```

### PR DESCRIPTION
**Pull request by lordelix**
## Description

* LinkExpirationView does no longer update the model on date change
* Save if all inputs are valid

## Related Issue

- Fixes https://github.com/owncloud/core/issues/32056

## Motivation and Context
see ticket

## How Has This Been Tested?

Visual test in Google Chrome

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

File: core/js/sharedialoglinkshareview.js [hunk 1]
```diff
@@ -117,6 +122,14 @@
 			}
 		},
 
+		_writeModelBackup: function () {
+			this.modelBackup = JSON.stringify(this.model);
```
Comment (PVince81) [inline core/js/sharedialoglinkshareview.js]: `this.model.toJSON()`, not sure about stringify as the model is a complex object

Comment (PVince81) [reply core/js/sharedialoglinkshareview.js]: also note that `toJSON()` would already provide a copy

**Comment by PVince81** [comment]
@felixheidecke as discussed yesterday, the model.set in the expiration view is a mistake and shouldn't be there. The model should only be updated when saving.

**Comment by PVince81** [comment]
@felixheidecke any update ?

**Comment by felixheidecke** [comment]
While going thru the expiration and save process, I (think I) discovered a greater flaw. Wich need's to be discussed with @PVince81 … or maybe I'm not getting it.

It saves the share even if it doesn't validate correctly. This sneaks in "wrong" values.

**Comment by felixheidecke** [comment]
Instead of manually writing error messages to "wherever", we now have the `_addError(string)` in place, that appends a message to the modal header.

This requires sub-view initialisation to map the new option accordingly:
`this._addError   = options.addError;`

**Comment by felixheidecke** [comment]
@PVince81 let's look at applications that also write errors to the share dialog (eg. files_classifier) to see if changes are also needed.

## Todo:

- [ ] Add CSS Styling for new approach
- [ ] Check other applications that use the share dialog

**Comment by felixheidecke** [comment]
@individual-it @PVince81 ready to review

File: core/js/sharedialoglinkshareview.js [hunk 2]
```diff
@@ -128,8 +128,10 @@
 				$inputs = $el.find('.linkPassText, .expirationDate, .permission'), // all input fields combined
 				$errorMessageGlobal = $el.find('.error-message-global'),
 				$loading = $el.find('.loading'),
+				$expirationDate = $el.find('.expirationDate'),
```
Comment (PVince81) [inline core/js/sharedialoglinkshareview.js]: call the subview's `getExpirationDate()` method instead of directly going to its DOM ? (add the method if not exists)
the current view is not supposed to know about the subview's DOM

**Review by PVince81 — COMMENTED** [review]
Logic looks good except for a small detail about scope violation

File: core/js/sharedialoglinkshareview.js (hunk 2 above)
Comment (felixheidecke) [reply core/js/sharedialoglinkshareview.js]: Updated

**Review by PVince81 — APPROVED** [review]
:+1: test failure unrelated

**Comment by PVince81** [comment]
@felixheidecke please backport
