### PR TITLE
Fix duplicate key value violation in setValues DB function

### LINKED ISSUE #23213: duplicate key value violates unique constraint "oc_preferences_pkey" on every login
### Steps to reproduce
1. Login to Owncloud Website
2. Open postgresql Serverlog
### Expected behaviour

No Error in logs
### Actual behaviour

Logfile is being spammed with errors:
2016-03-14 09:48:10 GMT STATEMENT:  INSERT INTO "oc_preferences" ("userid", "appid", "configkey", "configvalue") VALUES($1, $2, $3, $4)
2016-03-14 09:48:34 GMT ERROR:  duplicate key value violates unique constraint "oc_preferences_pkey"
2016-03-14 09:48:34 GMT DETAIL:  Key (userid, appid, configkey)=(testuser, files, quota) already exists.

(I already cleaned up the table, entries being set after next login. After logout und relogin Errors appear again).
### Server configuration

**Operating system**:
Debian 8.3

**Web server:**
Package: apache2
Version: 2.4.10-10+deb8u1

**Database:**
Package: postgresql
Version: 9.4+165

**PHP version:**
Package: php5
Version: 5.6.17+dfsg-0+deb8u1

**ownCloud version:** (see ownCloud admin page)
9.0.0 (stable)

**Updated from an older ownCloud or fresh install:**
Update: 7 > 8 > 9

**Where did you install ownCloud from:**
deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/ /

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
Enabled:
- activity: 2.2.1
- calendar: 1.0
- comments: 0.2
- contacts: 1.0.0.0
- dav: 0.1.5
- external: 1.2
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_external: 0.5.2
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
  Disabled:
- encryption
- user_external
- user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "**_REMOVED**_",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "**_REMOVED**_"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbtype": "pgsql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "installed": true,
        "mail_from_address": "cloud",
        "mail_smtpmode": "php",
        "mail_domain": "**_REMOVED**_",
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "loglevel": 2,
        "memcache.local": "\OC\Memcache\APC",
        "trashbin_retention_obligation": "auto",
        "updatechecker": false
    }
}

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:** 
no
### Client configuration

**Browser:**
Firefox 45

**Operating system:**
Debian 8

### PR DESCRIPTION
**Pull request by mrow4a**
This fixes https://github.com/owncloud/core/issues/23213 issue when one changes the oc_preferences in OC10. 

- [x] Unit tests
- [x] Backport - maybe fixes more?

### CODE REVIEW

**Comment by mrow4a** [comment]
@DeepDiver1975 is extremely hard to debug, OCA\Encryption\Tests\MigrationTest::testUpdateDBExistingNewConfig. How can I run this one test as single? I guess I need to setup encryption on local instance, sth else ? 

It fails because I removed preconditions from setValue, and I need to adjust it to use updateValue instead.

File: lib/private/DB/Connection.php [hunk 1]
```diff
@@ -285,28 +321,7 @@ public function setValues($table, array $keys, array $values, array $updatePreco
 			return $insertQb->execute();
 		} catch (ConstraintViolationException $e) {
```
Comment (mrow4a) [inline lib/private/DB/Connection.php]: I am extremely unhappy with this line -> we have 3 options:

- writing specialized queries everywhere instead of universal "set"
- doing workeround as it is now
-writing this properly as "set", but this will require additional query, and we would need a transaction here to ensure ACID principles are preserved in case of concurent accesses and be sure the ConstraintViolationException never happens

Comment (mrow4a) [inline lib/private/DB/Connection.php]: And we already are doing transaction to `oc_properties` properly https://github.com/owncloud/core/blob/7f4a4e7d16a11474071b4b06089e0597c1a989ed/apps/dav/lib/Files/CustomPropertiesBackend.php#L212-L212 as transaction, shall I do it? @DeepDiver1975 @PVince81 ?

**Comment by mrow4a** [comment]
Current implementation will basicaly first perform select and insert if possible or knowing record does not exists (NOT EXISTS even wrapped by INSERT is verr quick), it will do update. Simple and easy. 

Tried also with ON DUPLICATE KEY UPDATE, but this is not working in SQLLite, so we cannot do it in one query and we need transaction :1234:

File: lib/private/DB/Connection.php [hunk 2]
```diff
@@ -263,7 +263,7 @@ private function getType($value) {
 	}
 
 	/**
-	 * Insert or update a row value
+	 * Insert or update a row value. For safety, user of the method should lock table and begin/end transaction
```
Comment (DeepDiver1975) [inline lib/private/DB/Connection.php]: don't lock - lock is bad - doesn't work with galery cluster and breaks on mysql master replicatin

Comment (mrow4a) [inline lib/private/DB/Connection.php]: but transaction I think is supported isnt it?

**Comment by mrow4a** [comment]
@DeepDiver1975 Any decision regarding the comment there? Should I play with transaction there or leave as it is, since it solves the general issue?

**Comment by jvillafanez** [comment]
I'm not convinced with the solution. We should keep using the query builder if possible.

In addition, the `insertIfNotExist` might not be standard and we might be wrapping it for some DB providers (I might be wrong). If the DB doesn't provide a native method for this, I think it's better to use it just as a convenience function, otherwise we have a risk of different behaviour depending on the target DB.

**Comment by mrow4a** [comment]
Should I write another PR killing \OC\DB\Adapter @jvillafanez ? Can we lock table with QueryBuilder as in adapter and replicate other functions ? @DeepDiver1975 @PVince81 What was the reasoning behind the Adapter?

**Comment by mrow4a** [comment]
Any update and input here? In the issue https://github.com/owncloud/core/issues/23213 it seems really problem to solve, and this fixes it.

**Comment by jvillafanez** [comment]
I guess we can go with this solution in order to fix the issue.

**Comment by mrow4a** [comment]
@PVince81 @DeepDiver1975 anything I did not think here and could be important? This is quick change actualy.

**Comment by mrow4a** [comment]
@PVince81  @DeepDiver1975 @jvillafanez Just retested everything, and this fixes the issue for PostgreSQL https://github.com/owncloud/core/issues/23213. It would be good to have it, to avoid the issues and save time of e.g. @pako81 which customer changed that query so that it does not log warning.

**Comment by PVince81** [comment]
`insertIfNotExists` is AFAIK already adjusted in the adapters for different database types.

So the change looks ok.

@mrow4a did you find out from old commit logs / PRs if there are clues why this wasn't directly done with `insertIfNotExists` ? Maybe the function didn't exist yet ? Am just wondering whether there was another legitimate reason for this choice.

**Comment by mrow4a** [comment]
@PVince81 what do we do with this PR?

**Comment by PVince81** [comment]
> @mrow4a did you find out from old commit logs / PRs if there are clues why this wasn't directly done with insertIfNotExists ? Maybe the function didn't exist yet ? Am just wondering whether there was another legitimate reason for this choice.

**Comment by mrow4a** [comment]
I dont know, my quick guess is that someone though it will just be faster or that function did not exist yet there. I can research if you want, but it needs to be done like it is now, or we drop the support for sqlite and write it properly with ON DUPLICATE KEY UPDATE (which I guess is no go :>)

**Comment by PVince81** [comment]
@mrow4a I'm fine with your change. I just want to make sure there wasn't an explicit decision in the past to not use it. I hope you're right and it's simply that the method did not exist yet.

**Comment by PVince81** [comment]
@mrow4a how was the research ?

**Comment by tomneedham** [comment]
Original implementation: https://github.com/owncloud/core/pull/18531. Seems insertIfNotExists was considered but ignored for no real reason. We should use insertIfNotExists as this is polluting SQL error logs at the moment.

**Comment by PVince81** [comment]
@tomneedham sounds good, then let's get this in. Thanks

**Comment by PVince81** [comment]
- stable10: TODO
- stable9.1: https://github.com/owncloud/core/issues/28484
- stable9: https://github.com/owncloud/core/issues/28485
