### PR TITLE
make sure that we always create a public share key for remote shares

### LINKED ISSUE #13579: Unsuccessful remote share of a file from an encrypted system to a non encrypted system
### Steps to reproduce

1. Install owncloud on two systems
2. on system one, enable encryption
3. on system one, remote share a text file with a user on system two
3. on system two, accept share and edit file

### Expected behaviour

User on system two should see file text

### Actual behaviour

User on system two sees html for error page:

```
<!DOCTYPE html>
<!--[if lt IE 7]><html class="ng-csp ie ie6 lte9 lte8 lte7" data-placeholder-focus="false" lang="en"><![endif]-->
<!--[if IE 7]><html class="ng-csp ie ie7 lte9 lte8 lte7" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if IE 8]><html class="ng-csp ie ie8 lte9 lte8" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if IE 9]><html class="ng-csp ie ie9 lte9" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if gt IE 9]><html class="ng-csp ie" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if !IE]><!--><html class="ng-csp" data-placeholder-focus="false" lang="en" ><!--<![endif]-->

	<head data-requesttoken="2ufR/RZ0nC0VSc17Uy51LkpON7Qyh0">
		<title>
		ownCloud Enterprise Edition		</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
		<meta name="apple-itunes-app" content="app-id=543672169">
		<link rel="shortcut icon" type="image/png" href="/owncloud/themes/default/core/img/favicon.png" />
		<link rel="apple-touch-icon-precomposed" href="/owncloud/themes/default/core/img/favicon-touch.png" />
					<link rel="stylesheet" href="/owncloud/core/css/styles.css?v=8f44592f8b87b1d8f2497a86038fa4d0" type="text/css" media="screen" />
					<link rel="stylesheet" href="/owncloud/core/css/header.css?v=8f44592f8b87b1d8f2497a86038fa4d0" type="text/css" media="screen" />
					<link rel="stylesheet" href="/owncloud/core/css/mobile.css?v=8f44592f8b87b1d8f2497a86038fa4d0" type="text/css" media="screen" />
					<link rel="stylesheet" href="/owncloud/core/css/icons.css?v=8f44592f8b87b1d8f2497a86038fa4d0" type="text/css" media="screen" />
					<link rel="stylesheet" href="/owncloud/core/css/fonts.css?v=8f44592f8b87b1d8f2497a86038fa4d0" type="text/css" media="screen" />
					<link rel="stylesheet" href="/owncloud/core/css/apps.css?v=8f44592f8b87b1d8f2497a86038fa4d0" type="text/css" media="screen" />
					<link rel="stylesheet" href="/owncloud/core/css/fixes.css?v=8f44592f8b87b1d8f2497a86038fa4d0" type="text/css" media="screen" />
					<link rel="stylesheet" href="/owncloud/core/css/multiselect.css?v=8f44592f8b87b1d8f2497a86038fa4d0" type="text/css" media="screen" />
					<link rel="stylesheet" href="/owncloud/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=8f44592f8b87b1d8f2497a86038fa4d0" type="text/css" media="screen" />
					<link rel="stylesheet" href="/owncloud/core/css/jquery-ui-fixes.css?v=8f44592f8b87b1d8f2497a86038fa4d0" type="text/css" media="screen" />
					<link rel="stylesheet" href="/owncloud/core/css/jquery-tipsy.css?v=8f44592f8b87b1d8f2497a86038fa4d0" type="text/css" media="screen" />
					<link rel="stylesheet" href="/owncloud/core/css/jquery.ocdialog.css?v=8f44592f8b87b1d8f2497a86038fa4d0" type="text/css" media="screen" />
					<link rel="stylesheet" href="/owncloud/themes/default/core/css/styles.css?v=8f44592f8b87b1d8f2497a86038fa4d0" type="text/css" media="screen" />
							<script type="text/javascript" src="/owncloud/index.php/core/js/oc.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/vendor/jquery/jquery.min.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/vendor/jquery/jquery-migrate.min.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/vendor/underscore/underscore.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/vendor/moment/min/moment-with-locales.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/vendor/handlebars/handlebars.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/js/placeholders.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/js/jquery-tipsy.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/js/compatibility.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/js/jquery.ocdialog.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/js/oc-dialogs.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/js/js.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/js/l10n.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/js/octemplate.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/js/eventsource.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/js/config.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/search/js/search.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/js/oc-requesttoken.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/js/apps.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/vendor/snapjs/dist/latest/snap.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/js/placeholder.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/vendor/blueimp-md5/js/md5.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/js/jquery.avatar.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/js/avatar.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/core/js/backgroundjobs.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/apps/files_encryption/js/encryption.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					<script type="text/javascript" src="/owncloud/apps/files_encryption/js/detect-migration.js?v=8f44592f8b87b1d8f2497a86038fa4d0"></script>
					</head>
	<body id="body-login">
		<noscript><div id="nojavascript"><div>This application requires JavaScript for correct operation. Please <a href="http://enable-javascript.com/" target="_blank">enable JavaScript</a> and reload the page.</div></div></noscript>
		<div class="wrapper"><!-- for sticky footer -->
			<div class="v-align"><!-- vertically centred box -->
									<header>
						<div id="header">
							<div class="logo svg">
								<h1 class="hidden-visually">
									ownCloud								</h1>
							</div>
							<div id="logo-claim" style="display:none;">Enterprise Edition</div>
						</div>
					</header>
								<ul>
	<li class='error'>
		
		Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.		<br/>
				<br/>
	</li>
</ul>
				<div class="push"></div><!-- for sticky footer -->
			</div>
		</div>

		<footer>
			<p class="info">
				© 2015 <a href="https://owncloud.com" target="_blank">ownCloud Inc.</a><br/>Your Cloud, Your Data, Your Way!			</p>
		</footer>
	</body>
</html>


```

### Server log file

```

{"reqId":"426dc91010d7b2d8e5923e240431aa73","remoteAddr":"x.x.x.x","app":"webdav client","message":"curl GET http:\/\/x.x.x.x\/owncloud\/apps\/files_encryption\/files\/error.php?p=0&errorCode=3 returned status code 403","level":3,"time":"2015-01-21T21:50:59+00:00"}
{"reqId":"df55cc044a49957c6eed93a0dde6884b","remoteAddr":"x.x.x.x","app":"webdav client","message":"curl GET http:\/\/x.x.x.x\/owncloud\/apps\/files_encryption\/files\/error.php?p=0&errorCode=3 returned status code 403","level":3,"time":"2015-01-21T21:51:02+00:00"}

```

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud Enterprise Edition 8.0 beta 1 (daily) Build:2015-01-21T04:13:37+00:00

### PR DESCRIPTION
**Pull request by schiessle**
fix #13579 

cc @nickvergessen  @jnfrmarks maybe you can give it a try

### CODE REVIEW

File: lib/private/share/share.php [hunk 1]
```diff
@@ -189,6 +188,26 @@ public static function getUsersSharingFile($path, $ownerUser, $includeOwner = fa
 				}
 			}
 
+			//check for remote share
+			if (!$remoteShare) {
+				$remoteShare = false;
```
Comment (nickvergessen) [inline lib/private/share/share.php]: is this intentional?
Seems like it does nothing, since you already added it way up there?

File: lib/private/share/share.php [hunk 2]
```diff
@@ -189,6 +188,26 @@ public static function getUsersSharingFile($path, $ownerUser, $includeOwner = fa
...
+				$query = \OC_DB::prepare('
+					SELECT `share_with`
+					FROM `*PREFIX*share`
+					WHERE `item_source` = ? AND `share_type` = ? AND `item_type` IN (\'file\', \'folder\')'
+				);
+
+				$result = $query->execute(array($source, self::SHARE_TYPE_REMOTE));
```
Comment (nickvergessen) [inline lib/private/share/share.php]: limit the query to 1 row please (`OC_DB::prepare()` takes limit as a second argument)

File: lib/private/share/share.php [hunk 3]
```diff
@@ -170,18 +171,16 @@ public static function getUsersSharingFile($path, $ownerUser, $includeOwner = fa
...
-					'SELECT `share_with`
-					FROM
-					`*PREFIX*share`
-					WHERE
-					`item_source` = ? AND `share_type` = ? AND `item_type` IN (\'file\', \'folder\')'
+				$query = \OC_DB::prepare('
+					SELECT `share_with`
+					FROM `*PREFIX*share`
+					WHERE `item_source` = ? AND `share_type` = ? AND `item_type` IN (\'file\', \'folder\')'
 				);
```
Comment (nickvergessen) [inline lib/private/share/share.php]: limit the query to 1 row please (`OC_DB::prepare()` takes limit as a second argument)

File: apps/files_encryption/tests/share.php [hunk 4]
```diff
@@ -607,7 +612,63 @@ function testReShareFolder($withTeardown = true) {
...
+		// disable encryption proxy to prevent recursive calls
+		$proxyStatus = \OC_FileProxy::$enabled;
+		\OC_FileProxy::$enabled = false;
+
+		// get the file info from previous created file
+		$fileInfo = $this->view->getFileInfo(
+			'/' . self::TEST_ENCRYPTION_SHARE_USER1 . '/files/' . $this->filename);
+
+		// check if we have a valid file info
+		$this->assertTrue($fileInfo instanceof \OC\Files\FileInfo);
```
Comment (nickvergessen) [inline apps/files_encryption/tests/share.php]: Use `$this->assertInstanceOf()` https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertInstanceOf

Much better in case you are faced with "false did not match expected true" someday

File: apps/files_encryption/tests/share.php [hunk 5]
```diff
@@ -607,7 +612,63 @@ function testReShareFolder($withTeardown = true) {
...
-	function testPublicShareFile() {
+	function testRemoteShareFile() {
+		// login as admin
+		//self::loginHelper(self::TEST_ENCRYPTION_SHARE_USER1);
+
+		// save file with content
+		$cryptedFile = file_put_contents('crypt:///' . self::TEST_ENCRYPTION_SHARE_USER1 . '/files/'  . $this->filename, $this->dataShort);
+
+		// test that data was successfully written
+		$this->assertTrue(is_int($cryptedFile));
```
Comment (nickvergessen) [inline apps/files_encryption/tests/share.php]: `assertInternalType()` https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertInternalType

**Comment by nickvergessen** [comment]
:+1: works as intended now

**Comment by nickvergessen** [comment]
Fixed the assertions myself, just have a look at the possibilities for future work ;)

**Comment by MorrisJobke** [comment]
@schiesbn Can I ask you to add the "To review" label (or the developing label) to your PRs. Then it's easier to spot if review power is already needed. And don't forget to assign the milestone ;) Then it's nicely listed in the github overview for the 8.0 ;)

**Comment by schiesbn** [comment]
@MorrisJobke sure, I always try to add the labels but sometimes it get lost ;-)

**Comment by MorrisJobke** [comment]
@schiesbn No problem ;) just a friendly reminder ;)

**Comment by MorrisJobke** [comment]
Works :+1: (first verified the broken behaviour and then tested the working state)
