### PR TITLE
Fix: Bugs in shared link with video #24331

### LINKED ISSUE #24331: Bugs in shared link with video
### Steps to reproduce (owncloud 9.0.1):
1) Set in config.php:
'enabledPreviewProviders' => array ( 0 => 'OC\\\\Preview\\\\Movie' )

on share link it will looks like that:

keyb1

keyb2

2) Upload video with large size - preview_max_x / preview_max_y options are not used to set max video size in share link.

### Solution:

1. Disable video preview in shared link

2. Set &lt;video&gt; style: max-width, max-height with parameters from preview_max_x / preview_max_y

Patch:
[owncloud9_download_video_display_bugs.zip](https://github.com/owncloud/core/files/240582/owncloud9_download_video_display_bugs.zip)

### PR DESCRIPTION
**Pull request by lenz1111**
Fixes: https://github.com/owncloud/core/issues/24331

### CODE REVIEW

**Comment by PVince81** [comment]
Any chance to test this too @davitol ? Thanks

@oparoz @georgehrke what do you think ?

File: apps/files_sharing/templates/public.php [hunk 1]
```diff
@@ -21,11 +21,13 @@
 OCP\Util::addScript('files', 'filelist');
 OCP\Util::addscript('files', 'keyboardshortcuts');
 
-$thumbSize = 1024;
+$sysConfig = \OC::$server->getConfig();
+$thumbSizeX = $sysConfig->getSystemValue('preview_max_x', 1024);
+$thumbSizeY = $sysConfig->getSystemValue('preview_max_y', 1024);
```
Comment (nickvergessen) [inline apps/files_sharing/templates/public.php]: should be done in the code that generates the template instead of the template it self

Comment (lenz1111) [inline apps/files_sharing/templates/public.php]: @nickvergessen You're right - I wrote it here because `$thumbSize` was set here before... I will move out it from template

File: apps/files_sharing/templates/public.php [hunk 2]
```diff
@@ -94,7 +96,7 @@
 			<?php else: ?>
 				<?php if ($_['previewEnabled'] && substr($_['mimetype'], 0, strpos($_['mimetype'], '/')) == 'video'): ?>
 					<div id="imgframe">
-						<video tabindex="0" controls="" preload="none">
+						<video tabindex="0" controls="" preload="none" style="max-width: <?php echo p($thumbSizeX); ?>px; max-height: <?php p($thumbSizeY); ?>px">
```
Comment (georgehrke) [inline apps/files_sharing/templates/public.php]: `echo` is not necessary here. `p()` will already print it.

**Comment by georgehrke** [comment]
@davitol Apparently you tested this (according to your comments in the issue).
Did you find any issues?

**Comment by davitol** [comment]
@georgehrke https://github.com/owncloud/core/issues/24331#issuecomment-221182492

IMHO Not showing the preview is not the best way to solve https://github.com/owncloud/core/issues/24331. Maybe this PR can be improved with https://github.com/owncloud/core/issues/24331#issuecomment-221195328
@lenz1111

**Comment by lenz1111** [comment]
@georgehrke @davitol added html5 video poster

**Comment by davitol** [comment]
> added html5 video poster

@lenz1111 Tested and looks good. WFM :+1:

**Comment by PVince81** [comment]
Code looks good :+1: 

JS unit tests ran locally.

If there's no objection I'd like to merge this soon. @oparoz @georgehrke

**Comment by georgehrke** [comment]
No objections from my side 👍

**Comment by PVince81** [comment]
Thanks guys!

**Comment by PVince81** [comment]
Looks like this broken unit tests on master, see https://github.com/owncloud/core/pull/24811#issuecomment-221487817
Will make a ticket after confirming.

CI was clumsy these days so it was likely that we'd miss that

**Comment by PVince81** [comment]
PR that fixes the tests https://github.com/owncloud/core/pull/24824
