### PR TITLE
Disable app that bricks the server after enabling

### LINKED ISSUE #17411: [Apps Management] enabling an incompatible app results in broken installation
Looks like in case a incompatible app is installed it is still enabled which break the installation

````
{"reqId":"GVjIvUygaF5oVj0Yihc4","remoteAddr":"::1","app":"core","message":"App \"Contacts\" cannot be installed because it is not compatible with this version of ownCloud.","level":3,"time":"2015-07-06T10:07:25+00:00"}
{"reqId":"sXZOpGTAHsxgieRDpwxb","remoteAddr":"::1","app":"PHP","message":"Access to undeclared static property: Sabre\\VObject\\Component::$classMap at \/home\/deepdiver\/Development\/ownCloud\/881\/apps\/contacts\/appinfo\/app.php#15","level":3,"time":"2015-07-06T10:07:44+00:00"}

### PR DESCRIPTION
**Pull request by PVince81**
If an app is getting enabled in the web UI, an ajax call is now made to
make sure the server still works. If it doesn't, it sends an emergency
app disabling call to disable the breaking app.

Fix #17411

@Raydiation @oparoz @LukasReschke

### CODE REVIEW

**Comment by PVince81** [comment]
Note, this is a Proof Of Concept.

To test:
1. Setup this branch for core
2. Setup the calendar app, but use the "stable8" branch
3. Remove the version restriction in the calendar app's info.xml
4. Enable the calendar app in the web UI

Before this PR: it hangs, then OC is broken.
After this PR: app is disabled after the health check

File: lib/base.php [hunk 1]
```diff
@@ -848,6 +848,17 @@ public static function handleRequest() {
 			self::checkUpgrade();
 		}
 
+		// emergency app disabling
+		if ($request === '/disableapp' && $_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['appid'])) {
```
Comment (PVince81) [inline lib/base.php]: I know, a bit barbaric... is there a better way ?
This has to happen before the first call to `OC_App::loadApps`

File: settings/js/apps.js [hunk 2]
```diff
@@ -201,11 +201,52 @@ OC.Settings.Apps = OC.Settings.Apps || {
...
 
+	/**
+	 * Checks the server health.
+	 *
+	 * If the promise fails, the server is broken.
+	 *
+	 * @return {Promise} promise
+	 */
+	_checkServerHealth: function() {
+		return $.get(OC.generateUrl('apps/files'));
```
Comment (PVince81) [inline settings/js/apps.js]: The URL could be changed, or we could use multiple URLs to check for web pages, WebDAV, etc in parallel.

File: settings/js/apps.js [hunk 3]
```diff
@@ -201,11 +201,52 @@ OC.Settings.Apps = OC.Settings.Apps || {
...
+	},
+
 	enableApp:function(appId, active, element, groups) {
+		var self = this;
 		OC.Settings.Apps.hideErrorMessage(appId);
 		groups = groups || [];
 		var appItem = $('div#app-'+appId+'');
 		element.val(t('settings','Please wait....'));
+
+		function showAppEnabled() {
```
Comment (PVince81) [inline settings/js/apps.js]: This ugly code was just moved from below... I hope to refactor it some day.

**Comment by PVince81** [comment]
also @nickvergessen @icewind1991 @karlitschek @DeepDiver1975 for additional cheerfulness ? :wink:

**Comment by PVince81** [comment]
Fixes https://github.com/owncloud/core/issues/17435

File: settings/js/apps.js (hunk 2 above)
Comment (oparoz) [inline settings/js/apps.js]: I think it would be wise to test several aspects as apps can touch multiple aspects.
Bad code will probably still go through as it's difficult to determine if a JS method is going to break the files app.

Comment (PVince81) [inline settings/js/apps.js]: Yeah, thought of it too. Could have a few endpoints to test.
It could even be a "healthcheck" endpoint that purposefully call several APIs (filesystem, user management, etc) to make sure they still work.

Comment (PVince81) [inline settings/js/apps.js]: A JS method usually would not brick the instance. In the worst case the admin can still go to the admin page and disable the app manually. The purpose of this PR is to protect against the "totally bricked" case where you only get a white page due to autoloading errors.

File: lib/base.php (hunk 1 above)
Comment (Raydiation) [inline lib/base.php]: I think thats fine.

Comment (Xenopathic) [inline lib/base.php]: I'd suggest making it a GET parameter if possible, so the admin can open `http://example.com/owncloud/disableapp?appid=broken-app` manually if they refresh the page before the server health check completes (or if it breaks for some reason). Much easier than crafting a fake form to push a POST request.

Comment (Raydiation) [inline lib/base.php]: @Xenopathic there are multiple browser addons that make POST a breeze.

Comment (Raydiation) [inline lib/base.php]: GET is definitely wrong.

Comment (Xenopathic) [inline lib/base.php]: Hmm, OK.

**Comment by Xenopathic** [comment]
Fixes #18315

**Comment by MorrisJobke** [comment]
Alternative approach #18599

**Comment by DeepDiver1975** [comment]
@PVince81 needs rebase - 9.0 or later? THX

File: lib/base.php [hunk 4]
```diff
@@ -848,6 +848,17 @@ public static function handleRequest() {
...
+			\OCP\JSON::checkAdminUser();
```
Comment (nickvergessen) [inline lib/base.php]: Missing CSRF check?

**Comment by PVince81** [comment]
Rebased and adjusted.
Added CSRF check.

Please review @MorrisJobke @nickvergessen @rullzer @schiesbn @blizzz 

To simulate a broken app, just edit "user_ldap/appinfo/app.php" and add a syntax error. Then try enabling the app.

**Comment by PVince81** [comment]
Make sure to use https://github.com/owncloud/core/pull/17451/files?w=1 for the review, the JS code was mostly indented.

**Comment by MorrisJobke** [comment]
Nice! Tested and works :+1: 

Also the code looks straight forward.

**Comment by rullzer** [comment]
Does not seem to work over here... the error page just returns code 200 here...

File: lib/base.php [hunk 5]
```diff
@@ -823,12 +823,28 @@ public static function handleRequest() {
...
+		$requestPath = $request->getPathInfo();
+		if (substr($requestPath, -3) !== '.js') { // we need these files during the upgrade
 			self::checkMaintenanceMode();
 			self::checkUpgrade();
 		}
 
+		// emergency app disabling
+		if ($requestPath === '/disableapp'
+			&& $request->getMethod() === 'POST'
+			&& $request->getParam('appid') !== ''
```
Comment (nickvergessen) [inline lib/base.php]: default is null, which is `!== ''`  so you will try to disable the app `null`, not sure what happens then, but should be adjusted:
```php
((string) $request->getParam('appid')) !== ''
```

The casting to string is a good idea here anyway

Comment (PVince81) [inline lib/base.php]: Thanks for the info, I wasn't sure either. Usually I'd do a `isset` on `$_POST`

**Comment by PVince81** [comment]
@nickvergessen I added the string casting.

File: settings/js/apps.js [hunk 6]
```diff
@@ -254,35 +268,48 @@ OC.Settings.Apps = OC.Settings.Apps || {
...
 						}
-					}
+					}).fail(function() {
+						// server borked, emergency disable app
+						$.post(OC.webroot + '/index.php/disableapp', {appid: appId}, function() {
+							OC.Settings.Apps.showErrorMessage(
+								appId,
+								t('settings', 'Error: this app cannot be enabled because it makes the server unstable')
+							);
+							appItem.data('errormsg', t('settings', 'Error while disabling app'));
```
Comment (nickvergessen) [inline settings/js/apps.js]: while enabling?

File: settings/js/apps.js [hunk 7]
```diff
@@ -254,35 +268,48 @@ OC.Settings.Apps = OC.Settings.Apps || {
...
+							if (groups) {
+								appItem.data('groups', JSON.stringify(groups));
+							} else {
+								appItem.data('groups', '');
+							}
 						}
-					}
+					}).fail(function() {
+						// server borked, emergency disable app
+						$.post(OC.webroot + '/index.php/disableapp', {appid: appId}, function() {
```
Comment (nickvergessen) [inline settings/js/apps.js]: this has no handle for a failure case? Should mention that we tried to disable it again, but failed?

**Comment by PVince81** [comment]
@nickvergessen fixed the error handling

**Comment by PVince81** [comment]
@nickvergessen second review ?

@rullzer can you elaborate how you tested this ?

**Comment by nickvergessen** [comment]
Works as expected, at least when the error is triggered in app.php or when displaying the files list.

:+1:

**Comment by PVince81** [comment]
@rullzer mind giving it another test ? Would be good to know why it didn't work for you.

**Comment by rullzer** [comment]
@PVince81 still not working as expected.

Steps I took.

1. checkout branch :wink: 
2. navigate to app page
3. add some random noise into apps/user_ldap/appinfo/app.php
4. enable app

The app does not get disabled.

I see the ajax call being made. And the error page is returned. But it just has a http status code of 200.

**Comment by PVince81** [comment]
@rullzer hmmm, maybe your random noise produced different errors.

I just added some text like "test" in app.php in the middle of the code, technically a syntax error.

**Comment by PVince81** [comment]
I remember that there are some cases where ownCloud would just return an exception page, and that page would return the status code 200. Maybe my detection code isn't accurate enough.

Another idea would be to query the capabilities API, which I suppose should also cover many cases.

**Comment by rullzer** [comment]
@PVince81 I added "foo"... but that should not really matter

**Comment by PVince81** [comment]
Ok got it, you added `foo` at the very top of the file.

I added it between some lines.

That causes another exception...

**Comment by PVince81** [comment]
Actually, no. It doesn't brick ownCloud at all.
If you add `foo` before the `<?php` block then it's treated as content and likely ignored.

@rullzer please confirm / retest.

**Comment by rullzer** [comment]
@PVince81 no I added it in the actual php code.

But I don't think the issue here is with your code actually. The issue is that the error page return HTTP status code 200...

**Comment by PVince81** [comment]
@rullzer please post the diff of your change and also the exception from the error page you see.

**Comment by rullzer** [comment]
The diff:

```diff
diff --git a/apps/user_ldap/appinfo/app.php b/apps/user_ldap/appinfo/app.php
index dab47ee..d744979 100644
--- a/apps/user_ldap/appinfo/app.php
+++ b/apps/user_ldap/appinfo/app.php
@@ -25,7 +25,7 @@
  */
 
 OCP\App::registerAdmin('user_ldap', 'settings');
-
+foobar
 $helper = new \OCA\user_ldap\lib\Helper();
 $configPrefixes = $helper->getServerConfigurationPrefixes(true);
 $ldapWrapper = new OCA\user_ldap\lib\LDAP();
```

Error stuff:

```
Internal Server Error

The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.

More details can be found in the server log.

Technical details

    Remote Address: 127.0.0.1
    Request ID: cvvZM3EB/y+YC1aFMNTk
    Type: ParseError
    Code: 0
    Message: syntax error, unexpected '$helper' (T_VARIABLE)
    File: /home/roeland/oc/core/apps/user_ldap/appinfo/app.php
    Line: 29


Trace

#0 /home/roeland/oc/core/lib/private/app.php(145): OC_App::requireAppFile('user_ldap')
#1 /home/roeland/oc/core/lib/private/app.php(118): OC_App::loadApp('user_ldap')
#2 /home/roeland/oc/core/lib/base.php(849): OC_App::loadApps(Array)
#3 /home/roeland/oc/core/index.php(39): OC::handleRequest()
#4 {main}
```

**Comment by PVince81** [comment]
@rullzer very strange... I get a proper 500 Internal Server Error even with your patch. Possibly an env difference.

**Comment by PVince81** [comment]
I applied this PR and your patch against 9.0beta2 and it also worked fine. Something seems wrong in your env.

Let's move forward and merge this.
