### PR TITLE
[enc2] fixing return values and adding tests

### LINKED ISSUE #15746: [enc2] Missing return values in RecoveryController
https://github.com/owncloud/core/blob/master/apps/encryption/controller/recoverycontroller.php#L100
https://github.com/owncloud/core/blob/master/apps/encryption/controller/recoverycontroller.php#L178

In addition: the controllers have zero unit tests - please improve - THX

@schiesbn @th3fallen

### PR DESCRIPTION
**Pull request by th3fallen**
resolves https://github.com/owncloud/core/issues/15746

### CODE REVIEW

File: apps/encryption/controller/recoverycontroller.php [hunk 1]
```diff
@@ -108,42 +113,43 @@ public function adminRecovery($recoveryPassword, $confirmPassword, $adminEnableR
...
-						'message' => (string) $this->l->t('Password successfully changed.'))
-					)
-				);
+						'message' => (string)$this->l->t('Password successfully changed.'))
+				)
+			);
 		} else {
 			return new DataResponse(
 				array(
 					'data' => array
```
Comment (nickvergessen) [inline apps/encryption/controller/recoverycontroller.php]: Please put the bracket on this line, or use the new array syntax `[` + `]`

File: apps/encryption/controller/recoverycontroller.php [hunk 2]
```diff
@@ -161,19 +167,19 @@ public function userSetRecovery($userEnableRecovery) {
...
+						'status' => 'success',
+						'data' => array(
+							'message' => (string)$this->l->t('Recovery Key enabled'))
 					)
 				);
 			}
+
+			return new DataResponse(
+				array(
+					'data' => array
```
Comment (nickvergessen) [inline apps/encryption/controller/recoverycontroller.php]: Please put the bracket on this line, or use the new array syntax `[` + `]`

File: apps/encryption/controller/recoverycontroller.php (hunk 1 above)
Comment (th3fallen) [inline apps/encryption/controller/recoverycontroller.php]: this was just formatted i didn't actually touch it, but will do....

File: apps/encryption/tests/controller/RecoveryControllerTest.php [hunk 3]
```diff
@@ -0,0 +1,182 @@
+<?php
+/**
+ * @author Clark Tomlinson  <clark@owncloud.com>
+ *
+ * @copyright Copyright (c) 2015, ownCloud, Inc.
+ * @license AGPL-3.0
+ */
+
+
+namespace OC\apps\encryption\tests\lib\controller;
```
Comment (nickvergessen) [inline apps/encryption/tests/controller/RecoveryControllerTest.php]: `OCA\Encryption\Tests\Controller`

Comment (th3fallen) [inline apps/encryption/tests/controller/RecoveryControllerTest.php]: damn you phpstorm....

File: apps/encryption/tests/controller/RecoveryControllerTest.php [hunk 4]
```diff
@@ -0,0 +1,182 @@
+<?php
```
Comment (nickvergessen) [inline apps/encryption/tests/controller/RecoveryControllerTest.php]: we use lowercase file names, would be nice if you can adjust that ;)

Comment (LukasReschke) [inline apps/encryption/tests/controller/RecoveryControllerTest.php]: Well. I for one also use upper-case ones for tests. Actually not for the real ownCloud code as the autoloader does run amok then :see_no_evil:

Comment (th3fallen) [inline apps/encryption/tests/controller/RecoveryControllerTest.php]: Unit test filenames are supposed to be in studly caps....

File: apps/encryption/tests/controller/RecoveryControllerTest.php [hunk 5]
```diff
@@ -0,0 +1,182 @@
...
+		$this->recoveryMock->expects($this->any())
+			->method('enableAdminRecovery')
+			->willReturn(true);
+
+		$response = $this->controller->adminRecovery($recoveryPassword,
+			$recoveryPassword,
+			$enableRecovery)->getData();
+
+
+		$this->assertEquals('Recovery key successfully enabled',
```
Comment (nickvergessen) [inline apps/encryption/tests/controller/RecoveryControllerTest.php]: please also assert the HTTP status of the response object

File: apps/encryption/controller/recoverycontroller.php [hunk 6]
```diff
@@ -161,19 +167,19 @@ public function userSetRecovery($userEnableRecovery) {
...
+					('message' => (string)$this->l->t('Could not enable the recovery key, please try again or contact your administrator'))
+				)
```
Comment (nickvergessen) [inline apps/encryption/controller/recoverycontroller.php]: Should not return HTTP status 200 OK, but some failure, maybe 500

File: apps/encryption/controller/recoverycontroller.php [hunk 7]
```diff
@@ -108,42 +113,43 @@ public function adminRecovery($recoveryPassword, $confirmPassword, $adminEnableR
...
+			);
 		} else {
 			return new DataResponse(
 				array(
 					'data' => array
-						('message' => (string) $this->l->t('Could not change the password. Maybe the old password was not correct.'))
-					)
-				);
+					('message' => (string)$this->l->t('Could not change the password. Maybe the old password was not correct.'))
+				)
```
Comment (nickvergessen) [inline apps/encryption/controller/recoverycontroller.php]: Should not return HTTP status 200 OK, but some failure, maybe 500

File: apps/encryption/controller/recoverycontroller.php [hunk 8]
```diff
@@ -108,42 +113,43 @@ public function adminRecovery($recoveryPassword, $confirmPassword, $adminEnableR
...
 		if (empty($confirmPassword)) {
-			$errorMessage = (string) $this->l->t('Please repeat the new recovery password');
+			$errorMessage = (string)$this->l->t('Please repeat the new recovery password');
 			return new DataResponse(array('data' => array('message' => $errorMessage)));
 		}
 
 		if ($newPassword !== $confirmPassword) {
-			$errorMessage = (string) $this->l->t('Repeated recovery key password does not match the provided recovery key password');
+			$errorMessage = (string)$this->l->t('Repeated recovery key password does not match the provided recovery key password');
 			return new DataResponse(array('data' => array('message' => $errorMessage)));
```
Comment (nickvergessen) [inline apps/encryption/controller/recoverycontroller.php]: Should not return HTTP status 200 OK, but some failure, maybe 500

File: apps/encryption/controller/recoverycontroller.php [hunk 9]
```diff
@@ -108,42 +113,43 @@ public function adminRecovery($recoveryPassword, $confirmPassword, $adminEnableR
...
 		if (empty($newPassword)) {
-			$errorMessage = (string) $this->l->t('Please provide a new recovery password');
+			$errorMessage = (string)$this->l->t('Please provide a new recovery password');
 			return new DataResponse (array('data' => array('message' => $errorMessage)));
 		}
 
 		if (empty($confirmPassword)) {
-			$errorMessage = (string) $this->l->t('Please repeat the new recovery password');
+			$errorMessage = (string)$this->l->t('Please repeat the new recovery password');
 			return new DataResponse(array('data' => array('message' => $errorMessage)));
```
Comment (nickvergessen) [inline apps/encryption/controller/recoverycontroller.php]: Should not return HTTP status 200 OK, but some failure, maybe 500

File: apps/encryption/controller/recoverycontroller.php [hunk 10]
```diff
@@ -108,42 +113,43 @@ public function adminRecovery($recoveryPassword, $confirmPassword, $adminEnableR
...
 		if (empty($oldPassword)) {
-			$errorMessage = (string) $this->l->t('Please provide the old recovery password');
+			$errorMessage = (string)$this->l->t('Please provide the old recovery password');
 			return new DataResponse(array('data' => array('message' => $errorMessage)));
 		}
 
 		if (empty($newPassword)) {
-			$errorMessage = (string) $this->l->t('Please provide a new recovery password');
+			$errorMessage = (string)$this->l->t('Please provide a new recovery password');
 			return new DataResponse (array('data' => array('message' => $errorMessage)));
```
Comment (nickvergessen) [inline apps/encryption/controller/recoverycontroller.php]: Should not return HTTP status 200 OK, but some failure, maybe 500

File: apps/encryption/controller/recoverycontroller.php [hunk 11]
```diff
@@ -108,42 +113,43 @@ public function adminRecovery($recoveryPassword, $confirmPassword, $adminEnableR
 	public function changeRecoveryPassword($newPassword, $oldPassword, $confirmPassword) {
 		//check if both passwords are the same
 		if (empty($oldPassword)) {
-			$errorMessage = (string) $this->l->t('Please provide the old recovery password');
+			$errorMessage = (string)$this->l->t('Please provide the old recovery password');
 			return new DataResponse(array('data' => array('message' => $errorMessage)));
```
Comment (nickvergessen) [inline apps/encryption/controller/recoverycontroller.php]: Should not return HTTP status 200 OK, but some failure, maybe 500

File: apps/encryption/controller/recoverycontroller.php [hunk 12]
```diff
@@ -72,31 +72,36 @@ public function __construct($AppName,
...
 		} elseif (isset($adminEnableRecovery) && $adminEnableRecovery === '0') {
 			if ($this->recovery->disableAdminRecovery($recoveryPassword)) {
-				return new DataResponse(['data' => array('message' => (string) $this->l->t('Recovery key successfully disabled'))]);
+				return new DataResponse(['data' => array('message' => (string)$this->l->t('Recovery key successfully disabled'))]);
 			}
-			return new DataResponse(['data' => array('message' => (string) $this->l->t('Could not disable recovery key. Please check your recovery key password!'))]);
+			return new DataResponse(['data' => array('message' => (string)$this->l->t('Could not disable recovery key. Please check your recovery key password!'))]);
 		}
+		// this response should never be sent but just in case.
+		return new DataResponse(['data' => ['message' => (string)$this->l->t('Missing parameters')]]);
```
Comment (nickvergessen) [inline apps/encryption/controller/recoverycontroller.php]: Should not return HTTP status 200 OK, but some failure, maybe 500

File: apps/encryption/controller/recoverycontroller.php [hunk 13]
```diff
@@ -72,31 +72,36 @@ public function __construct($AppName,
...
 			}
-			return new DataResponse(['data' => array('message' => (string) $this->l->t('Could not enable recovery key. Please check your recovery key password!'))]);
+			return new DataResponse(['data' => array('message' => (string)$this->l->t('Could not enable recovery key. Please check your recovery key password!'))]);
 		} elseif (isset($adminEnableRecovery) && $adminEnableRecovery === '0') {
 			if ($this->recovery->disableAdminRecovery($recoveryPassword)) {
-				return new DataResponse(['data' => array('message' => (string) $this->l->t('Recovery key successfully disabled'))]);
+				return new DataResponse(['data' => array('message' => (string)$this->l->t('Recovery key successfully disabled'))]);
 			}
-			return new DataResponse(['data' => array('message' => (string) $this->l->t('Could not disable recovery key. Please check your recovery key password!'))]);
+			return new DataResponse(['data' => array('message' => (string)$this->l->t('Could not disable recovery key. Please check your recovery key password!'))]);
```
Comment (nickvergessen) [inline apps/encryption/controller/recoverycontroller.php]: Should not return HTTP status 200 OK, but some failure, maybe 500

File: apps/encryption/controller/recoverycontroller.php [hunk 14]
```diff
@@ -72,31 +72,36 @@ public function __construct($AppName,
...
+				500);
 		}
 
 		if (isset($adminEnableRecovery) && $adminEnableRecovery === '1') {
 			if ($this->recovery->enableAdminRecovery($recoveryPassword)) {
-				return new DataResponse(['status'	=>'success', 'data' => array('message' => (string) $this->l->t('Recovery key successfully enabled'))]);
+				return new DataResponse(['status' => 'success', 'data' => array('message' => (string)$this->l->t('Recovery key successfully enabled'))]);
 			}
-			return new DataResponse(['data' => array('message' => (string) $this->l->t('Could not enable recovery key. Please check your recovery key password!'))]);
+			return new DataResponse(['data' => array('message' => (string)$this->l->t('Could not enable recovery key. Please check your recovery key password!'))]);
```
Comment (nickvergessen) [inline apps/encryption/controller/recoverycontroller.php]: Should not return HTTP status 200 OK, but some failure, maybe 500

File: apps/encryption/tests/controller/RecoveryControllerTest.php [hunk 15]
```diff
@@ -0,0 +1,182 @@
...
+			$response['data']['message']);
+
+		$response = $this->controller->adminRecovery('',
```
Comment (nickvergessen) [inline apps/encryption/tests/controller/RecoveryControllerTest.php]: Please use a data provider instead of calling it multiple times in one test, so we know all the failing cases in one go, if they fail some day:
https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers

File: apps/encryption/tests/controller/RecoveryControllerTest.php [hunk 16]
```diff
@@ -0,0 +1,182 @@
...
+
+	public function testChangeRecoveryPassword() {
+		$password = 'test';
+		$oldPassword = 'oldtest';
+
+		$data = $this->controller->changeRecoveryPassword($password,
+			$oldPassword,
+			$password)->getData();
+
+		$this->assertEquals('Could not change the password. Maybe the old password was not correct.',
```
Comment (nickvergessen) [inline apps/encryption/tests/controller/RecoveryControllerTest.php]: Same here, assert status + use provider

File: apps/encryption/tests/controller/RecoveryControllerTest.php [hunk 17]
```diff
@@ -0,0 +1,182 @@
...
+	}
+
+	public function testUserSetRecovery() {
+		$this->recoveryMock->expects($this->exactly(2))
+			->method('setRecoveryForUser')
+			->willReturnOnConsecutiveCalls(true, false);
+
+		$data = $this->controller->userSetRecovery('1')->getData();
+
+		$this->assertEquals('Recovery Key enabled', $data['data']['message']);
```
Comment (nickvergessen) [inline apps/encryption/tests/controller/RecoveryControllerTest.php]: Assert status

**Comment by th3fallen** [comment]
@nickvergessen all fixed. Had to move from onConsecutiveCalls to a valuemap but all is well now.

File: apps/encryption/controller/recoverycontroller.php [hunk 18]
```diff
@@ -72,31 +72,36 @@ public function __construct($AppName,
...
-			return new DataResponse(['data' => ['message' => $errorMessage]], 500);
+			$errorMessage = (string)$this->l->t('Repeated recovery key password does not match the provided recovery key password');
+			return new DataResponse(['data' => ['message' => $errorMessage]],
+				500);
 		}
 
 		if (isset($adminEnableRecovery) && $adminEnableRecovery === '1') {
 			if ($this->recovery->enableAdminRecovery($recoveryPassword)) {
-				return new DataResponse(['status'	=>'success', 'data' => array('message' => (string) $this->l->t('Recovery key successfully enabled'))]);
+				return new DataResponse(['status' => 'success', 'data' => array('message' => (string)$this->l->t('Recovery key successfully enabled'))]);
```
Comment (nickvergessen) [inline apps/encryption/controller/recoverycontroller.php]: status should be replaced (one day™) https://github.com/owncloud/core/commit/04674c06cca5884e6269461b2ae9a6e64a00953d

Comment (nickvergessen) [inline apps/encryption/controller/recoverycontroller.php]: PS it is not there in line old96/new99, so is it even needed anymore?

File: apps/encryption/controller/recoverycontroller.php [hunk 19]
```diff
@@ -108,43 +113,43 @@ public function adminRecovery($recoveryPassword, $confirmPassword, $adminEnableR
...
-					)
-				);
-		} else {
-			return new DataResponse(
-				array(
-					'data' => array
-						('message' => (string) $this->l->t('Could not change the password. Maybe the old password was not correct.'))
-					)
-				);
+					'status' => 'success',
```
Comment (nickvergessen) [inline apps/encryption/controller/recoverycontroller.php]: Remove one day

File: apps/encryption/controller/recoverycontroller.php [hunk 20]
```diff
@@ -161,20 +166,20 @@ public function userSetRecovery($userEnableRecovery) {
...
-					'data' => array(
-						'message' => (string) $this->l->t('Recovery Key enabled'))
-					)
-				);
-			} else {
-				return new DataResponse(
-					array(
-					'data' => array
-						('message' => (string) $this->l->t('Could not enable the recovery key, please try again or contact your administrator'))
+						'status' => 'success',
```
Comment (nickvergessen) [inline apps/encryption/controller/recoverycontroller.php]: Remove one day

**Comment by nickvergessen** [comment]
Looks good to me atm

File: apps/encryption/controller/recoverycontroller.php (hunk 20 above)
Comment (th3fallen) [inline apps/encryption/controller/recoverycontroller.php]: changes to these atm are going to take some big js changes in the app that are not in scope of this pr.

Comment (nickvergessen) [inline apps/encryption/controller/recoverycontroller.php]: yeah, which is why I said one day and gave a +1 never the less

Comment (th3fallen) [inline apps/encryption/controller/recoverycontroller.php]: I was just trying to be clear for whoever else reviews this so they know what's going on. Thanks again @nickvergessen

**Comment by th3fallen** [comment]
summoning @DeepDiver1975

**Comment by th3fallen** [comment]
possibly @PVince81 ?

File: apps/encryption/controller/recoverycontroller.php [hunk 21]
```diff
@@ -108,43 +113,43 @@ public function adminRecovery($recoveryPassword, $confirmPassword, $adminEnableR
...
+						'message' => (string)$this->l->t('Password successfully changed.')]
+				)
+			);
 		}
+		return new DataResponse(
+			array(
+				'data' => [
+					'message' => (string)$this->l->t('Could not change the password. Maybe the old password was not correct.')
+				]
+			), 500);
```
Comment (PVince81) [inline apps/encryption/controller/recoverycontroller.php]: 500 for an invalid password ?

Comment (th3fallen) [inline apps/encryption/controller/recoverycontroller.php]: all of this is via ajax so its so JS will know there was a failure.

Comment (th3fallen) [inline apps/encryption/controller/recoverycontroller.php]: actually no you're right will correct. GREAT catch @PVince81

**Comment by th3fallen** [comment]
@nickvergessen Wanna take another look had to adjust the js anyway so went ahead and dropped the status's

@PVince81 care to take a look since your the JS master :)

**Comment by th3fallen** [comment]
rebased

File: apps/encryption/js/settings-personal.js [hunk 22]
```diff
@@ -4,40 +4,41 @@
...
+		})
+		.fail(function (jqXHR) {
+			OC.msg.finishedError('#encryption .msg', JSON.parse(jqXHR.responseText).data.message);
 		});
-	}
-};
+}
 
-$(document).ready(function(){
+$(document).ready(function () {
```
Comment (PVince81) [inline apps/encryption/js/settings-personal.js]: Please don't add spaces between "function" and "()" https://doc.owncloud.org/server/8.0/developer_manual/general/codingguidelines.html#objects-functions-arrays-variables

I guess our JSHint rules don't catch that ? (there's a .jshintrc file)

File: apps/encryption/js/settings-personal.js [hunk 23]
```diff
@@ -4,40 +4,41 @@
...
-		var newPrivateKeyPassword = $('input:password[id="newPrivateKeyPassword"]').val();
-		OC.msg.startSaving('#encryption .msg');
-		$.post(
-			OC.generateUrl('/apps/encryption/ajax/updatePrivateKeyPassword'),
-			{oldPassword: oldPrivateKeyPassword, newPassword: newPrivateKeyPassword}
-		).success(function (response) {
-			OC.msg.finishedSuccess('#encryption .msg', response.message);
-		}).fail(function (response) {
-			OC.msg.finishedError('#encryption .msg', response.responseJSON.message);
+function updatePrivateKeyPasswd () {
```
Comment (PVince81) [inline apps/encryption/js/settings-personal.js]: Why did you get rid of the namespace ?

File: apps/encryption/js/settings-personal.js (hunk 22 above)
Comment (th3fallen) [inline apps/encryption/js/settings-personal.js]: guess not my ide did it automatically, will look into

File: apps/encryption/js/settings-personal.js (hunk 23 above)
Comment (th3fallen) [inline apps/encryption/js/settings-personal.js]: again ide stripped in a format.... No idea didn't notice. Let me readd

File: apps/encryption/js/settings-personal.js (hunk 22 above)
Comment (th3fallen) [inline apps/encryption/js/settings-personal.js]: ah this was done before the rebase, i missed those changes!!!! Makes a lot more sense now.

File: apps/encryption/js/settings-personal.js (hunk 23 above)
Comment (th3fallen) [inline apps/encryption/js/settings-personal.js]: Ahh this was done before the rebase and i missed those changes makes a lot more sense now!

**Comment by th3fallen** [comment]
@PVince81 should have fixed the js issues,

**Comment by th3fallen** [comment]
@owncloud-bot retest this please

**Comment by th3fallen** [comment]
failed tests are due to stupid jenkins and rebase force push @nickvergessen @PVince81 fyi

**Comment by PVince81** [comment]
Code looks good :+1:

**Comment by PVince81** [comment]
:-1: just had a quick test and find a bug

- [ ] BUG: as admin, change the password of a user. Login as that user, go to the enc password section and enter wrong passwords. It stays stuck on "Saving..." with a JS error "Uncaught TypeError: Cannot read property 'message' of undefined"

**Comment by th3fallen** [comment]
That's because the settings controller doesn't have responses like all the other controllers.... Fixed now.

**Comment by PVince81** [comment]
Works now :+1:

File: apps/encryption/tests/controller/RecoveryControllerTest.php (hunk 4 above)
Comment (DeepDiver1975) [inline apps/encryption/tests/controller/RecoveryControllerTest.php]: > Unit test filenames are supposed to be in studly caps....

in the non-owncloud world ... we have everything lowercase - please adjust (can be done in a separate PR)

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
# **THAT BRANCH IS DEAD**

zed-is-dead

**Comment by DeepDiver1975** [comment]
Can somebody please submit a jenkins pr? @nickvergessen @MorrisJobke THX

**Comment by MorrisJobke** [comment]
> Can somebody please submit a jenkins pr? @nickvergessen @MorrisJobke THX

I will

**Comment by MorrisJobke** [comment]
#15829

**Comment by DeepDiver1975** [comment]
> I will

THX a lot!

**Comment by MorrisJobke** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.owncloud.org//job/pull-request-analyser-ng-simple/11759/
:rocket: Test PASSed.:rocket:
chuck

File: apps/encryption/controller/recoverycontroller.php [hunk 24]
```diff
@@ -108,43 +114,42 @@ public function adminRecovery($recoveryPassword, $confirmPassword, $adminEnableR
...
+						'message' => (string)$this->l->t('Password successfully changed.')]
+				]
+			);
 		}
+		return new DataResponse(
+			[
+				'data' => [
+					'message' => (string)$this->l->t('Could not change the password. Maybe the old password was not correct.')
+				]
+			], Http::STATUS_INTERNAL_SERVER_ERROR);
```
Comment (DeepDiver1975) [inline apps/encryption/controller/recoverycontroller.php]: I could now argue that 500/Internal Server Error is the wrong error code.
500 is :boom: and indicates big trouble in little web server ....

Furthermore 5xx are by definition server errors

But because the issue is at the end that e.g. the user did enter wrong password a client error shall be thrown back. 4xx errors are used in this case.

**Comment by th3fallen** [comment]
I agree @DeepDiver1975 they've been changed to 400's

**Comment by nickvergessen** [comment]
@owncloud-bot retest this please

**Comment by th3fallen** [comment]
Meh whatever it passed....

**Comment by PVince81** [comment]
Still :+1: 

Can we get this merged ?

File: apps/encryption/js/settings-personal.js [hunk 25]
```diff
@@ -9,35 +9,43 @@ if (!OC.Encryption) {
...
-		});
+			{
+				oldPassword: oldPrivateKeyPassword,
+				newPassword: newPrivateKeyPassword
+			}
+		).done(function (data) {
+				OC.msg.finishedSuccess('#encryption .msg', data.message);
+			})
+			.fail(function (jqXHR) {
+				OC.msg.finishedError('#encryption .msg', JSON.parse(jqXHR.responseText).message);
```
Comment (nickvergessen) [inline apps/encryption/js/settings-personal.js]: any reason why you JSON.parse() yourself now, instead of using the `responseJSON` child?

Comment (th3fallen) [inline apps/encryption/js/settings-personal.js]: honestly no, just didn't think about it. Since its such a trivial json object were dealing with i dont see any big advantages to changing it now. (performance wise) if you would like to change it please feel free though.

**Comment by th3fallen** [comment]
@DeepDiver1975 can we get this merged in.....

**Comment by DeepDiver1975** [comment]
:+1:
