### PR TITLE
[webdav] Check if source can be deleted before move

### LINKED ISSUE #5251: File is deleted when it shouldn't after trying to move a file (from a shared folder) with the same name as one that is already in root
### Expected behaviour
The file "photo.JPG" shouldn't be deleted from root and it is been deleted
The file "photo.JPG" shouldn't be deleted from folder "A" inside "Shared" folder and it doesn't

### Actual behaviour
The file "photo.JPG" is deleted from root when it shouldn't

### Steps to reproduce
1. There are two users in the server (user1 and user2)
2. In the server, log in owncloud as user 1
3. Share a folder called "A" with user2. 
4. Give him only update permission
5. Log in own cloud as user2
6. Upload in root a file, for instance photo.JPG
7. Now using webdav protocol, try to move a file called "photo.JPG" from a shared folder "A" to root. Notice that you don't have the correct permission so in the end the file isn't going to be moved.
We are going to see do it using poster (complement in firefox) (screenshot is attached)

         * URL:server/remote.php/webdav/Shared/A/photo.JPG
         * User: user2 
         * password:
         * Action:MOVE
         * Headers
                  - Destination: server/remote.php/webdav/photo.JPG
                  - Overwrite: T
screen shot 2013-10-09 at 6 40 39 pm 2
5. An error 403 is sent
6. In the server, logged as user2 account, refresh the account and then photo.JPG is deleted from root when it shouldn't

### Server configuration
Operating system: openSUSE

Database: SQLite 3

ownCloud version: {"installed":"true","version":"5.80.8.1","versionstring":"6.0 pre alpha","edition":""}

### Client configuration
Browser: Chrome

Operating system: MaOs 10.7.5

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #5251

If a file/folder is moved from one storage to the other we have to have create permissions on the destination and delete permissions on the source.
- Unit tests included

My first attemt at Sabre/DAV stuff so @DeepDiver1975 @PVince81 please review :)

### CODE REVIEW

File: lib/private/connector/sabre/serverfactory.php [hunk 1]
```diff
@@ -91,6 +90,7 @@ public function createServer($baseUri, $requestUri, BackendInterface $authBacken
 			}
 			$objectTree->init($root, $view, $this->mountManager);
 
+			$server->addPlugin(new \OC\Connector\Sabre\FilesPlugin($objectTree, $view, $this->mountManager));
```
Comment (PVince81) [inline lib/private/connector/sabre/serverfactory.php]: not sure but you might need to specify a plugin priority to make sure the LockPlugin is applied after this one, to preserve the original order

Comment (rullzer) [inline lib/private/connector/sabre/serverfactory.php]: I don't think you can set priorities on plugins... on on the `server->on` calls...

Comment (PVince81) [inline lib/private/connector/sabre/serverfactory.php]: You can, @icewind1991 did it before

Comment (PVince81) [inline lib/private/connector/sabre/serverfactory.php]: or was it @nickvergessen

Comment (nickvergessen) [inline lib/private/connector/sabre/serverfactory.php]: https://github.com/owncloud/core/blob/master/lib/private/connector/sabre/maintenanceplugin.php#L69

Comment (nickvergessen) [inline lib/private/connector/sabre/serverfactory.php]: And note **important** lower number means it is executed first

Comment (rullzer) [inline lib/private/connector/sabre/serverfactory.php]: yeah that is what I mean. It priority on the events. Not on the plugin in general. The lock plugin listens to other events

File: lib/private/connector/sabre/filesplugin.php [hunk 2]
```diff
@@ -106,6 +123,40 @@ public function initialize(\Sabre\DAV\Server $server) {
...
+	 */
+	function checkMove($source, $destination) {
+		$sourceMountPoint = $this->mountManager->find($this->fileView->getAbsolutePath($source));
+		$sourceStorage = $sourceMountPoint->getStorage();
+
+		$destinationMountPoint = $this->mountManager->find($this->fileView->getAbsolutePath($destination));
+		$destinationStorage = $destinationMountPoint->getStorage();
+
+		// Moving within the same storage is a different case
+		if ($sourceStorage === $destinationStorage) {
```
Comment (icewind1991) [inline lib/private/connector/sabre/filesplugin.php]: I dont think we should check if the storages are the same but instead check if the source/target folder is the same, iirc we require delete/create permissions any time a file is moved to a different storage but only update if we rename within the storagwe

Comment (rullzer) [inline lib/private/connector/sabre/filesplugin.php]: exactly.. so we do not need delete/create permissions if it is the same storage. Then we only need update.

source and target folder can still be different while staying on the same storage.

Comment (icewind1991) [inline lib/private/connector/sabre/filesplugin.php]: I meant to say "if we rename with the same folder"

afaik we also need to create/delete permissions if we move to a different folder within the same storage

Comment (rullzer) [inline lib/private/connector/sabre/filesplugin.php]: Lets look at that for a different PR... before everything was passed. this is just to fix the issue... we can go into more detail later.

Comment (PVince81) [inline lib/private/connector/sabre/filesplugin.php]: Shouldn't we simply use view-based permissions and not care about storages here ?
And then resort to folder's move permissions logic, see https://github.com/owncloud/smashbox/blob/master/lib/oc-tests/test_sharePermissions.py#L78

Comment (rullzer) [inline lib/private/connector/sabre/filesplugin.php]: That is the whole problem of the issue... if you have update permissions you can rename the file within the storage... but if you move it out you need create/delete permissions...

Comment (rullzer) [inline lib/private/connector/sabre/filesplugin.php]: Ah no rename is only within the same folder...

Comment (rullzer) [inline lib/private/connector/sabre/filesplugin.php]: Ok let me fix that later.

Comment (PVince81) [inline lib/private/connector/sabre/filesplugin.php]: Argh, I see... permissions mess

**Comment by rullzer** [comment]
Ok tried to do a bit more checking related to the ownCloud permissions.
Please have a look.

File: lib/private/connector/sabre/filesplugin.php [hunk 3]
```diff
@@ -106,6 +116,87 @@ public function initialize(\Sabre\DAV\Server $server) {
...
+	function checkMove($source, $destination) {
+		list($sourceDir,) = \Sabre\HTTP\URLUtil::splitPath($source);
+		$sourceDir = $this->fileView->getAbsolutePath($sourceDir);
+
+		list($destinationDir,) = \Sabre\HTTP\URLUtil::splitPath($destination);
+		$destinationDir = $this->fileView->getAbsolutePath($destinationDir);
+
+		if ($source === $destination) {
+			throw new \Sabre\DAV\Exception\Forbidden('Source and destination are the same');
+		} else if ($sourceDir === $destinationDir) {
```
Comment (rullzer) [inline lib/private/connector/sabre/filesplugin.php]: So this is not the webdav spec. The webdav specs does not know renames. A move is a move. I think this is how we handle renames in ownCloud...

File: lib/private/connector/sabre/filesplugin.php [hunk 4]
```diff
@@ -106,6 +116,87 @@ public function initialize(\Sabre\DAV\Server $server) {
...
+				/*
+				 * We meed update permissions to perform a rename
+				 * See https://github.com/owncloud/smashbox/blob/master/lib/oc-tests/test_sharePermissions.py#L78-L164
+				 */
+				if (!$this->fileView->isUpdatable($source)) {
+					throw new \Sabre\DAV\Exception\PreconditionFailed('Update permissions required for rename on ' . $source);
+				}
+			}
+		} else {
+			/*
```
Comment (rullzer) [inline lib/private/connector/sabre/filesplugin.php]: I just followed the webdav spec here.

**Comment by rullzer** [comment]
Some unit tests are missing but it is time for bed!

File: lib/private/connector/sabre/filesplugin.php [hunk 5]
```diff
@@ -106,6 +116,87 @@ public function initialize(\Sabre\DAV\Server $server) {
...
+				 * http://www.webdav.org/specs/rfc4918.html#HEADER_Overwrite
+				 */
+				if (!$this->server->httpRequest->hasHeader("Overwrite") ||
+				    $this->server->httpRequest->getHeader("Overwrite") === "T") {
+
+					/*
+					 * If the Overwrite header is true and the resource exists we must first issue a DELETE
+					 * http://www.webdav.org/specs/rfc4918.html#rfc.section.9.9.3
+					 */
+					if ($this->fileView->isDeletable($destination)) {
```
Comment (icewind1991) [inline lib/private/connector/sabre/filesplugin.php]: I think we only need update permissions for overwrite

Comment (rullzer) [inline lib/private/connector/sabre/filesplugin.php]: Yeah so I'm not sure what we want to do here. Since the webdav specs says:

DELETE dest
COPY src dest
DELETE src

I'd like to follow webdav spec here.

Comment (rullzer) [inline lib/private/connector/sabre/filesplugin.php]: Also, if you move directories is only update enough then?

File: lib/private/connector/sabre/filesplugin.php [hunk 6]
```diff
@@ -106,6 +116,87 @@ public function initialize(\Sabre\DAV\Server $server) {
...
+		$destinationDir = $this->fileView->getAbsolutePath($destinationDir);
+
+		if ($source === $destination) {
+			throw new \Sabre\DAV\Exception\Forbidden('Source and destination are the same');
+		} else if ($sourceDir === $destinationDir) {
+			/*
+			 * ownCloud considers this a rename
+			 */
+			if ($this->fileView->file_exists($destination)) {
+				throw new \Sabre\DAV\Exception\PreconditionFailed('Cannot rename. ' . $destination . ' already exists');
```
Comment (nickvergessen) [inline lib/private/connector/sabre/filesplugin.php]: We have a smashbox test for rename overwrite :no_mouth: ?

**Comment by nickvergessen** [comment]
```
nickv@nickv-think ~/ownCloud/Smashbox/smashbox $ ./bin/smash lib/oc-tests/test_sharePermissions.py -a

....

ERROR - recipient_worker - Unexpected response: Status code: 412 - SabreDAV Exception: Sabre\DAV\Exception\PreconditionFailed - Message: Create permissions required in 
ERROR - recipient_worker - Operation "move_in" must be allowed when share permissions are 31 'Operation "%s" must be %s when share permissions are %i' % (operation, success_message, perms) failed in recipient_worker() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_sharePermissions.py" at line 251]
ERROR - recipient_worker - Unexpected response: Status code: 412 - SabreDAV Exception: Sabre\DAV\Exception\PreconditionFailed - Message: Create permissions required in 
ERROR - recipient_worker - Operation "move_in_overwrite" must be allowed when share permissions are 31 'Operation "%s" must be %s when share permissions are %i' % (operation, success_message, perms) failed in recipient_worker() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_sharePermissions.py" at line 251]
ERROR - recipient_worker - Unexpected response: Status code: 412 - SabreDAV Exception: Sabre\DAV\Exception\PreconditionFailed - Message: Create permissions required in 
ERROR - recipient_worker - Operation "move_in_subdir" must be allowed when share permissions are 31 'Operation "%s" must be %s when share permissions are %i' % (operation, success_message, perms) failed in recipient_worker() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_sharePermissions.py" at line 251]
ERROR - recipient_worker - Unexpected response: Status code: 412 - SabreDAV Exception: Sabre\DAV\Exception\PreconditionFailed - Message: Create permissions required in 
ERROR - recipient_worker - Operation "move_in_subdir_overwrite" must be allowed when share permissions are 31 'Operation "%s" must be %s when share permissions are %i' % (operation, success_message, perms) failed in recipient_worker() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_sharePermissions.py" at line 251]
ERROR - recipient_worker - Unexpected response: Status code: 412 - SabreDAV Exception: Sabre\DAV\Exception\PreconditionFailed - Message: Create permissions required in 
ERROR - recipient_worker - Operation "move_out" must be allowed when share permissions are 31 'Operation "%s" must be %s when share permissions are %i' % (operation, success_message, perms) failed in recipient_worker() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_sharePermissions.py" at line 251]
ERROR - recipient_worker - Unexpected response: Status code: 412 - SabreDAV Exception: Sabre\DAV\Exception\PreconditionFailed - Message: Create permissions required in 
ERROR - recipient_worker - Operation "move_out_subdir" must be allowed when share permissions are 31 'Operation "%s" must be %s when share permissions are %i' % (operation, success_message, perms) failed in recipient_worker() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_sharePermissions.py" at line 251]
ERROR - recipient_worker - 6 error(s) reported

```

**Comment by nickvergessen** [comment]
Since the ticket is from 2013, I think we shouldn't try to force this in after an RC1
cc @cmonteroluque @DeepDiver1975

**Comment by PVince81** [comment]
The fix is also risky, touching Webdav in a way that I'm afraid could break things.

**Comment by rullzer** [comment]
I agree we with @nickvergessen and @PVince81 to risky to get into 8.2 for my point of view.

**Comment by rullzer** [comment]
I rewrote it to a very minimal patch that solves the issue but nothing else. Lets do that for 9.0

Smashbox still passes!

**Comment by PVince81** [comment]
Nice!

I'm still worried about the plugin priorities

**Comment by rullzer** [comment]
> I'm still worried about the plugin priorities

I can change all the priorities on the listners to 99. But that still might break stuff.

I'm not convinced anything is wrong here. The plugins that now get added before the files pluing (that wern't before):

* ExceptionLoggerPlugin
* LockPlugin
* ListenerPlugin

But none of those listen to the same events as the filesplugin.

**Comment by nickvergessen** [comment]
> Smashbox still passes!

No :x: 
Only the first test from the testsuite passes (`#0`), the second one fails (`#1`):
```
SUMMARY:smash.:running lib/oc-tests/test_sharePermissions.py in /home/nickv/ownCloud/Smashbox/ramdir/test_sharePermissions-151007-115011-testset1 as test testset #1 {'sharePermissions_matrix': {'allowed_operations': [], 'permission': 1}}
...
ERROR - recipient_worker - Unexpected response: Status code: 412 - SabreDAV Exception: Sabre\DAV\Exception\PreconditionFailed - Message: shared-dir/move_this_to_subdir.dat cannot be deleted
ERROR - recipient_worker - Operation "move_in_subdir" must be forbidden when share permissions are 1 'Operation "%s" must be %s when share permissions are %i' % (operation, success_message, perms) failed in recipient_worker() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_sharePermissions.py" at line 251]
ERROR - recipient_worker - Unexpected response: Status code: 412 - SabreDAV Exception: Sabre\DAV\Exception\PreconditionFailed - Message: shared-dir/move_this_to_subdir_for_overwrite.dat cannot be deleted
ERROR - recipient_worker - Operation "move_in_subdir_overwrite" must be forbidden when share permissions are 1 'Operation "%s" must be %s when share permissions are %i' % (operation, success_message, perms) failed in recipient_worker() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_sharePermissions.py" at line 251]
ERROR - recipient_worker - Unexpected response: Status code: 412 - SabreDAV Exception: Sabre\DAV\Exception\PreconditionFailed - Message: shared-dir/move_this_out.dat cannot be deleted
ERROR - recipient_worker - Operation "move_out" must be forbidden when share permissions are 1 'Operation "%s" must be %s when share permissions are %i' % (operation, success_message, perms) failed in recipient_worker() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_sharePermissions.py" at line 251]
ERROR - recipient_worker - Unexpected response: Status code: 412 - SabreDAV Exception: Sabre\DAV\Exception\PreconditionFailed - Message: shared-dir/subdir/move_this_out.dat cannot be deleted
ERROR - recipient_worker - Operation "move_out_subdir" must be forbidden when share permissions are 1 'Operation "%s" must be %s when share permissions are %i' % (operation, success_message, perms) failed in recipient_worker() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_sharePermissions.py" at line 251]
ERROR - recipient_worker - 4 error(s) reported
```

**Comment by rullzer** [comment]
@nickvergessen smashbox should be happy now

**Comment by icewind1991** [comment]
I'm fine with this minimal path :+1:

**Comment by PVince81** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@nickvergessen mind retesting smashbox on this one? THX

**Comment by DeepDiver1975** [comment]
note to self: enable smashbox on prs ...

**Comment by davitol** [comment]
:+1:

**Comment by rullzer** [comment]
@PVince81 @nickvergessen I ran the `lib/oc-tests/test_sharePermissions.py -a` on smashbox... for the others it takes to much time on my machine.

**Comment by rullzer** [comment]
@cmonteroluque @DeepDiver1975 8.2 or -> 9.0? Your call..

**Comment by cmonteroluque** [comment]
so it seems we have an agreement about the minimal patch and it passes tests, why wouldn't this be ok for 8.2?

**Comment by rullzer** [comment]
> so it seems we have an agreement about the minimal patch and it passes tests, why wouldn't this be ok for 8.2?

I think it would be fine for 8.2. But since we are in RC1 wanted to have your OK to change (be it faulty) webdav behaviour. As there were some concerns about the patch possibly breaking stuff, but to my understanding all those issues have been resolved.

**Comment by PVince81** [comment]
I think this one should be fine for RC1
