### PR TITLE
Use DD-MM-YYYY consistently in share sidebar

### LINKED ISSUE #19549: Wrong format for expiration date in share dialogue
### Steps to reproduce

1. Share a folder
2. Set an expiration date

### Expected behaviour

There should be a human readable date in the filed, using the user's locale.

### Actual behaviour

A readable date appears briefly and it changes immediately to the format shown below

It also affects apps using the share dialogue and it seems the format can change if you make modifications using the desktop client, see https://github.com/owncloud/gallery/issues/398

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #19549

We used to display the response from the server. Which is in non ISO8601
format. Now this is weird since the datepickers shows us 'DD-MM-YYYY'
once a date is chosen.

Now use momentJS to properly format the date.
- Unit tests updated

CC: @oparoz @PVince81 @MorrisJobke @nickvergessen @jancborchardt

### CODE REVIEW

**Comment by oparoz** [comment]
Works on master :+1: 

Now, how to we backport this to the legacy OC.Share?

File: core/js/sharedialogexpirationview.js [hunk 1]
```diff
@@ -132,6 +132,11 @@
 
 			var isExpirationSet = !!this.model.get('linkShare').expiration || isExpirationEnforced;
 
+			var expiration;
+			if (isExpirationSet) {
+				expiration = moment(this.model.get('linkShare').expiration, 'YYYY-MM-DD').format('DD-MM-YYYY')
```
Comment (nickvergessen) [inline core/js/sharedialogexpirationview.js]: Should this be language dependent instead? e.g. en_US would use YYYY-DD-MM ?

Comment (MorrisJobke) [inline core/js/sharedialogexpirationview.js]: Use `.format('L')` and it is automatically adjusted to the locale: http://momentjs.com/ (see Multiple Locale Support) ;)

Comment (rullzer) [inline core/js/sharedialogexpirationview.js]: I know that but that would require more invasive changes. Currently the dateformatter outputs in `DD-MM-YYYY`. So this is just a quick fix.

Idealy we would use momentjs internally for dates and just for the datepicker covert to and from js dates (which is possible). But introducing that seems like a job for 9.0

**Comment by icewind1991** [comment]
:+1: looks good, tested

I agree that we should move to locale aware formatting for 9.0

**Comment by MorrisJobke** [comment]
@rullzer please create the backport PRs

**Comment by rullzer** [comment]
@MorrisJobke  Backport is not really an option here since the fix is intergrated into the sidebar stuff.
But we probably could fix it is a similar way for 8.1.x let me look into that tomorrow.

**Comment by rullzer** [comment]
Stable 8.1 backport in #19598
