### PR TITLE
dont show notification if federated share autoaccepted

### LINKED ISSUE #35067: automatically accept incoming federated shares generate a notification, accepting the share from there renames it
### Steps to reproduce
1. set up 2 servers
2. on server1 add server2 as trusted server
3. on server1 enable `Automatically accept remote shares from trusted servers `
4. share folder from server2 to server1

### Expected behaviour
share is accepted, no notification, or notification that informs about new share but does not have any buttons to accept it

### Actual behaviour
share is accepted, notification is shown allowing to accept the share again
doing so renames it to `folder (2)`

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
7.2
**ownCloud version:** (see ownCloud admin page)
10.2.0.1
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
RC1 tarball

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc1fqx9gxt25",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "172.17.0.1"
        ],
        "datadirectory": "\/home\/artur\/www\/owncloud-10.2.0\/rc1_a\/data",
        "overwrite.cli.url": "https:\/\/172.17.0.1\/owncloud-10.2.0\/rc1_a",
        "dbtype": "mysql",
        "version": "10.2.0.1",
        "logtimezone": "UTC",
        "apps_paths": [
            {
                "path": "\/home\/artur\/www\/owncloud-10.2.0\/rc1_a\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/home\/artur\/www\/owncloud-10.2.0\/rc1_a\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "ldapIgnoreNamingRules": false,
        "dbname": "owncloud-10-2-0-rc1-a",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "skeletondirectory": "\/home\/artur\/www\/owncloud-core\/apps\/testing\/data\/webUISkeleton",
        "groups.enable_medial_search": true
    }
}

```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - configreport: 0.2.0
  - dav: 0.4.0
  - encryption: 1.3.1
  - federatedfilesharing: 0.4.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_sharing: 0.11.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.10.1
  - firstrunwizard: 1.2.0
  - market: 0.4.0
  - notifications: 0.5.0
  - oauth2: 0.4.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
  - user_ldap: 0.13.0
Disabled:
  - external
  - user_external
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)

```

+-------------------------------+------------------------------------------------------------------------------------------------------------+
| Configuration                 | LDAPTestId                                                                                                 |
+-------------------------------+------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                                                                            |
| hasPagedResultSupport         |                                                                                                            |
| homeFolderNamingRule          |                                                                                                            |
| lastJpegPhotoLookup           | 0                                                                                                          |
| ldapAgentName                 | cn=admin,dc=owncloud,dc=com                                                                                |
| ldapAgentPassword             | ***                                                                                                        |
| ldapAttributesForGroupSearch  |                                                                                                            |
| ldapAttributesForUserSearch   |                                                                                                            |
| ldapBackupHost                |                                                                                                            |
| ldapBackupPort                |                                                                                                            |
| ldapBase                      | dc=owncloud,dc=com                                                                                         |
| ldapBaseGroups                | dc=owncloud,dc=com                                                                                         |
| ldapBaseUsers                 | dc=owncloud,dc=com                                                                                         |
| ldapCacheTTL                  | 600                                                                                                        |
| ldapConfigurationActive       | 1                                                                                                          |
| ldapDynamicGroupMemberURL     |                                                                                                            |
| ldapEmailAttribute            | mail                                                                                                       |
| ldapExperiencedAdmin          | 0                                                                                                          |
| ldapExpertUUIDGroupAttr       |                                                                                                            |
| ldapExpertUUIDUserAttr        | uid                                                                                                        |
| ldapExpertUsernameAttr        |                                                                                                            |
| ldapGroupDisplayName          | cn                                                                                                         |
| ldapGroupFilter               | (&(|(objectclass=posixGroup)))                                                                             |
| ldapGroupFilterGroups         |                                                                                                            |
| ldapGroupFilterMode           | 0                                                                                                          |
| ldapGroupFilterObjectclass    | posixGroup                                                                                                 |
| ldapGroupMemberAssocAttr      | memberUid                                                                                                  |
| ldapHost                      | localhost                                                                                                  |
| ldapIgnoreNamingRules         |                                                                                                            |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))(|(displayName=%uid)))) |
| ldapLoginFilterAttributes     | displayName                                                                                                |
| ldapLoginFilterEmail          | 1                                                                                                          |
| ldapLoginFilterMode           | 0                                                                                                          |
| ldapLoginFilterUsername       | 1                                                                                                          |
| ldapNestedGroups              | 0                                                                                                          |
| ldapOverrideMainServer        |                                                                                                            |
| ldapPagingSize                | 500                                                                                                        |
| ldapPort                      | 389                                                                                                        |
| ldapQuotaAttribute            |                                                                                                            |
| ldapQuotaDefault              |                                                                                                            |
| ldapTLS                       | 0                                                                                                          |
| ldapUserDisplayName           | displayName                                                                                                |
| ldapUserDisplayName2          |                                                                                                            |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                                                                             |
| ldapUserFilterGroups          |                                                                                                            |
| ldapUserFilterMode            | 0                                                                                                          |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                                              |
| ldapUserName                  | samaccountname                                                                                             |
| ldapUuidGroupAttribute        | auto                                                                                                       |
| ldapUuidUserAttribute         | auto                                                                                                       |
| turnOffCertCheck              | 0                                                                                                          |
| useMemberOfToDetectMembership | 1                                                                                                          |
+-------------------------------+------------------------------------------------------------------------------------------------------------+
```

### Client configuration
**Browser:**
FF
**Operating system:**
Ubuntu 18.04

### PR DESCRIPTION
**Pull request by karakayasemi**
## Description
No need to show a notification if federated share auto-accepted.

## Related Issue
- Fixes #35067

## Motivation and Context
Fixing bug.

### Steps to reproduce
1. set up 2 servers
2. on server1 add server2 as trusted server
3. on server1 enable `Automatically accept remote shares from trusted servers `
4. share folder from server2 to server1
5. share should be accepted and no notification.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

File: apps/federatedfilesharing/lib/FedShareManager.php [hunk 1]
```diff
@@ -163,20 +164,22 @@ public function createShare(Address $ownerAddress,
...
-		$declineAction = $notification->createAction();
-		$declineAction->setLabel('decline')
-			->setLink($link, 'DELETE');
-		$notification->addAction($declineAction);
-		$acceptAction = $notification->createAction();
-		$acceptAction->setLabel('accept')
-			->setLink($link, 'POST');
-		$notification->addAction($acceptAction);
-		$this->notificationManager->notify($notification);
+		if (!$this->federatedShareProvider->getAccepted($remote, $shareWith)) {
```
Comment (PVince81) [inline apps/federatedfilesharing/lib/FedShareManager.php]: the fix would certainly work like this

I wonder if there is some earlier location that is getting called but shouldn't ? did you consider other locations for this check ?

Comment (karakayasemi) [reply apps/federatedfilesharing/lib/FedShareManager.php]: Yes, I checked. It was only called in `FederatedShareProvider`'s `addShare` method to determine if it is auto-accepted or not. 
I also considered moving this notifying logic inside of the `FederatedShareProvider`. However, `NotificationManager` is not injected to `FederatedShareProvider`, then I assumed we want to handle notifications in this class.
IMHO, the current solution is fixing the problem with minimal change and it has no side effect.

Comment (PVince81) [reply apps/federatedfilesharing/lib/FedShareManager.php]: thanks for clarification!

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@karakayasemi please backport to release-10.2.0

**Comment by individual-it** [comment]
and stable10 branch

**Comment by PVince81** [comment]
no need for stable10 as we'll merge release-10.2.0 at the end

**Comment by sharidas** [comment]
Backport PR to release-10.2.0 branch https://github.com/owncloud/core/pull/35135
