### PR TITLE
read all relevant user attributes on login and user search, in one qu…

### LINKED ISSUE #17362: sharing notification by email not working for never logged on users
### Steps to reproduce
1. have ldap connection setup
2. share file with user (from LDAP) that has never logged on yet
3. select notifiy by email (email address also from LDAP) 

### Expected behaviour
ownCloud send email to the email address, also when this person has not yet logged into ownCloud.
This is important to introduce the new service all employees quickly!

### Actual behaviour
ownCloud warns the share creator, that no email can be sent!

sharing-notification-for-non-active-accounts

### Server configuration
**Operating system**:
sles 12
**Web server:**
apache 2.4
**Database:**
Oracle Rac
**PHP version:**
5.5.14
**ownCloud version:** (see ownCloud admin page)
8.0.3
**Updated from an older ownCloud or fresh install:**
7.0.5
**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
MS AD

### Client configuration
Firefox **Browser:**

**Operating system:**
Win 7

There is no ownCloud log entry for the warning in in the image picture above!

### PR DESCRIPTION
**Pull request by blizzz**
…ery. saves us some.

obsolotes #12943

fixes #17362 

Basically it does what #12943 did, but also reads the user attributes when users are being fetched, for instance in share dialog (except: avatar image).
- [ ] TODO: check performance impact (expectation: all in all better: saves LDAP requests, might cause more DB traffic)

Please review @MorrisJobke @Xenopathic @esakol @tkaufm or others

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by blizzz** [comment]
@rperezb could you get us some testing?

**Comment by tkaufm** [comment]
@blizzz
on my test-system it seems to work in first glance (quick and dirty).
Please be aware that I didn't had time by now for intensive tests, also regarding the performance, I will try to get back as soon i got some time.

Happy to help
Tobias

**Comment by MorrisJobke** [comment]
@blizzz This contains a merge conflict due to #18042 Can you have a look?

**Comment by blizzz** [comment]
@MorrisJobke yes, already on my list, gonna rebase it in a few.

**Comment by blizzz** [comment]
rebased, an adjustedment  to changed codebase was necessary. 

@tkaufm if you could confirm again with the latest  changes, this would be awesome :)

File: apps/user_ldap/lib/user/user.php [hunk 1]
```diff
@@ -155,6 +218,65 @@ public function getUsername() {
...
+			//deleted so we can clean up afterwards
+			$this->config->setUserValue(
+				$this->getUsername(), 'user_ldap', 'homePath', $path
+			);
+			return $path;
+		}
+
+		if($this->config->getAppValue('user_ldap', 'enforce_home_folder_naming_rule', true)) {
+			// a naming rule attribute is defined, but it doesn't exist for that LDAP user
+			throw new \Exception('Home dir attribute can\'t be read from LDAP for uid: ' . $this->getUsername());
```
Comment (MorrisJobke) [inline apps/user_ldap/lib/user/user.php]: This is fired even if my home folder naming rule is an empty string.

Comment (MorrisJobke) [inline apps/user_ldap/lib/user/user.php]: Previously this was inside the `if(   strpos($this->access->connection->homeFolderNamingRule, 'attr:') === 0 && $this->access->connection->homeFolderNamingRule !== 'attr:')`

**Comment by PVince81** [comment]
@blizzz any update ? (after your vacation)

**Comment by MorrisJobke** [comment]
@blizzz Ping :)

**Comment by blizzz** [comment]
lol, added another commit (locally) this second to fix your finding

**Comment by blizzz** [comment]
@MorrisJobke fixed, includes tests. Please try again, sänk ju.

**Comment by MorrisJobke** [comment]
Tested and works with existing users :+1:

**Comment by MorrisJobke** [comment]
@rperezb @davitol Can we get this in a QA cycle? Thanks :)

**Comment by blizzz** [comment]
Tested positively by @davitol https://github.com/owncloud/core/issues/17362#issuecomment-143193633

**Comment by blizzz** [comment]
@DeepDiver1975 merge?

**Comment by MorrisJobke** [comment]
@blizzz Can you create the backport request? This should go into 8.1.4 ;)

**Comment by blizzz** [comment]
Will do.

**Comment by PVince81** [comment]
Regression: https://github.com/owncloud/core/issues/19816
