### PR TITLE
Perform the filesize on the file that exists

### LINKED ISSUE #17247: Failing smashbox test
### Steps to reproduce

1. Install 8.1 
2. Run smashbox test test_shareDir.py

The test does the following:

1. User 1 creates a local directory and 3 local files in the directory
2. User 1 syncs the directory using owncloudcmd
3. User 1 shares the directory with user 2
4. User 2 syncs, modifies one of the files locally, and then resyncs
5. User 1 resyncs to get the modification
6. Check the log file for errors

### Expected behaviour

Test passes

### Actual behaviour

The file appears to be properly synced but the test fails due to an error in the server log file:

```
{"reqId":"Dvry5c9EOHOUr4J1j2W7","remoteAddr":"172.18.5.144","app":"PHP","message":"filesize(): stat failed fo
r \/var\/www\/html\/owncloud\/data\/user1\/files\/localShareDir\/TEST_FILE_USER_SHARE.dat.ocTransferId1595434
675.part at \/var\/www\/html\/owncloud\/lib\/private\/files\/storage\/local.php#149","level":3,"time":"2015-0
6-29T19:20:38+00:00"}
{"reqId":"Dvry5c9EOHOUr4J1j2W7","remoteAddr":"172.18.5.144","app":"PHP","message":"filesize(): stat failed fo
r \/var\/www\/html\/owncloud\/data\/user1\/files\/localShareDir\/TEST_FILE_USER_SHARE.dat.ocTransferId1595434
675.part at \/var\/www\/html\/owncloud\/lib\/private\/files\/storage\/local.php#149","level":3,"time":"2015-0
6-29T19:20:38+00:00"}
```
This error message was not present last week when testing 1.8.3rc1 with 8.1 and I do not see this error when testing 1.8.3 and 8.0.5

I tried to reproduce this using the webUI and could not.

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 RC1 (daily) Build:2015-06-29T03:08:30+00:00 774a38256d718363a7a501f4e6ff42e1a89dab3a

### Client configuration:

owncloudcmd veresion 1.8.3

@DeepDiver1975 @nickvergessen

### PR DESCRIPTION
**Pull request by nickvergessen**
Caused by the solution of 95602d4069a1eb9a45e1d08edeecc0d5b90e01ca and 9b336765b69bf7b7e2cd67a824862411b249aa4d

We changed the file path in `file_exists()` but still performed the `filesize()` on the original item.
@schiesbn mind having a quick look? The problem seems obvious to me.

cc @th3fallen @DeepDiver1975 

Fix #17247

### CODE REVIEW

File: lib/private/files/storage/wrapper/encryption.php [hunk 1]
```diff
@@ -364,8 +364,13 @@ public function fopen($path, $mode) {
 					$encryptionModule = $this->encryptionManager->getEncryptionModule($encryptionModuleId);
 				}
 
-				$size = $this->storage->filesize($path);
-				$unencryptedSize = $this->filesize($path);
+				if ($this->file_exists($realFile)) {
```
Comment (nickvergessen) [inline lib/private/files/storage/wrapper/encryption.php]: realFile choosen first, to match the order in https://github.com/owncloud/core/blob/2772e1e0ba63b03e00677675457a23017925aa25/lib/private/files/storage/wrapper/encryption.php#L617-L619

**Comment by schiesbn** [comment]
Not sure if this is correct. For choosing the correct cipher or to decide if it is a encrypted file or not we need to check the "realFile" in case of part files. But for the size we need the size of the file we actually write ("path"). If the file we write doesn't exists we shouldn't have a size because we write a file from scratch.

**Comment by nickvergessen** [comment]
Well, filesize() on a non-existing path throws an error. So we need to check it (what we did). But with the two commits from the PR description we checked 2 files for existance and performed the filesize() always on the same on.

**Comment by nickvergessen** [comment]
Okay, reading your comment again, we would do something like:
```php
				if ($this->file_exists($path)) {
					$size = $this->storage->filesize($path);
					$unencryptedSize = $this->filesize($path);
				} else {
					$size = $unencryptedSize = 0;
				}
```
?

**Comment by schiesbn** [comment]
> But with the two commits from the PR description we checked 2 files for existance and performed the filesize() always on the same on.

Here you take the filesize from "realFile":  https://github.com/owncloud/core/pull/17251/files#diff-a36b9c0307e0126dd50baa38fb4bb74aR368

And here from "path":https://github.com/owncloud/core/pull/17251/files#diff-a36b9c0307e0126dd50baa38fb4bb74aR371

But I think we need always the size from the file the stream wrapper really writes, which is "path", it doesn't matter if we rename it afterwards to "realFile" or not.

Your last comment just appears while I wrote this one, yes, I think that https://github.com/owncloud/core/pull/17251#issuecomment-117088064 might be the right approach.

**Comment by nickvergessen** [comment]
Okay, that works as well, no more message in the log and the test still passes. (I assume it already used value 0 because it didn't get a value back from the method).
So will update the patch, thanks @schiesbn

**Comment by schiesbn** [comment]
In the past $targetExists https://github.com/owncloud/core/pull/17251/files#diff-a36b9c0307e0126dd50baa38fb4bb74aR358 only checked the "path". So in the past we called filesize() only for files which exists, otherwise it was zero. Now that $targetExists also takes the real path into consideration to resolve the encryptio module correctly I think the approach now is correct. Now we are back to the behaviour we had before we changed $targetExists.


:+1:

**Comment by PVince81** [comment]
Code makes sense :+1:
