### PR TITLE
Share notification recipients should be added to list

### LINKED ISSUE #32008: Share notifications blocked by spamassassin
### Steps to reproduce
1. Create a link share (Sharing / Public Links / Create public link)
2. Send link via email

### Expected behaviour
Share notification should be delivered.

### Actual behaviour
Share notification gets blocked by spamassassin due to missing "To:" header.
`MISSING_HEADERS	Missing To: header`

### Server configuration
**Operating system**: Ubuntu 16.04.2 LTS

**Web server:** Apache/2.4.18

**Database:** MySQL

**PHP version:** PHP 7.0.30-0ubuntu0.16.04.1

**ownCloud version:** 10.0.8.5

**Updated from an older ownCloud or fresh install:** fresh install

#### ownCloud log (data/owncloud.log)
```
{"reqId":"sqy5dyXHHLdalpRxKLJn","level":0,"time":"2018-07-07T18:59:57+00:00","remoteAddr":"193.XX.XX.XX","user":"admin","app":"core","method":"POST","url":"\/oc10\/index.php\/core\/ajax\/share.php","message":"Sent mail to \"Array\n(\n)\n\" with subject \"admin shared \u00bbPhotos\u00ab with you\""}
```
(I did **not** remove anything from "message", the array is actually empty)

### PR DESCRIPTION
**Pull request by sharidas**
Share notification recipients should be added to list.
Adding them to bcc was causing spam filters to block
the emails. This change would solve the issue and
users get notified.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Add recipients to share notification by email to the 'to' field/list. So that spam filters would not block the emails.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/32008

## Motivation and Context

Add recipients to share notification by email to the 'to' field/list. So that spam filters would not block the emails.

## How Has This Been Tested?

- Configure ownCloud to enable share notification by email.
- Create a public link and add multiple recipients
- The emails received by recipients are in the to field.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by PVince81** [comment]
Now I think I remember why we didn't want to use a loop originally: if you set bcc to every single email, then the sender will get X similar emails where X is the number of recipients.

Here I suggest to simply add the sender in the array of "To" recipients so the sender will receive the message as is. @pmaier1 is that acceptable ?

**Comment by PVince81** [comment]
@sharidas let's go with the approach I proposed. I don't think there's a better approach

**Comment by pmaier1** [comment]
> Here I suggest to simply add the sender in the array of "To" recipients so the sender will receive the message as is. @pmaier1 is that acceptable ?

I think so, yes.

**Comment by sharidas** [comment]
I have updated the PR by adding senders email address to the 'to' list. Let me know if this looks ok @PVince81

**Comment by sharidas** [comment]
Backport PR https://github.com/owncloud/core/pull/32542

File: core/ajax/share.php [hunk 1]
```diff
@@ -179,48 +179,57 @@ function usersInGroup($gid, $search = '', $limit = -1, $offset = 0) {
 			]);
 
 			$options = [];
-			$options['bcc'] = $filter->getToAddress();
+			$results = [];
+			$toEmails = \explode(',', $filter->getToAddress());
+			//Lets get the senders email address and add to the 'to'
+			$toEmails []  = \OC::$server->getConfig()->getSystemValue('mail_smtpname', '');
```
Comment (PVince81) [inline core/ajax/share.php]: hmmm I don't understand what this is ?

File: core/ajax/share.php [hunk 2]
```diff
@@ -179,48 +179,57 @@ function usersInGroup($gid, $search = '', $limit = -1, $offset = 0) {
...
 			if (isset($_POST['bccSelf']) && $_POST['bccSelf'] === 'true') {
-				$options['bcc'] .= ',' . \OC::$server->getUserSession()->getUser()->getEMailAddress();
+				$toEmails [] = \OC::$server->getUserSession()->getUser()->getEMailAddress();
```
Comment (PVince81) [inline core/ajax/share.php]: this is the sender I meant all along, not the technical one but the semantic one: whoever created the public link and is clicking the button for getting the email out

File: core/ajax/share.php (hunk 1 above)
Comment (sharidas) [reply core/ajax/share.php]: Removed this change.

File: core/js/sharedialogmailview.js [hunk 3]
```diff
@@ -145,7 +145,7 @@
 			var $formSendIndicator = this.$el.find('.emailPrivateLinkForm--sending-indicator');
 			var  mail = {
 				 to      : this._addresses.join(','),
-				 bccSelf : this.$el.find('.emailPrivateLinkForm--emailBccSelf').is(':checked'),
+				 toSelf : this.$el.find('.emailPrivateLinkForm--emailBccSelf').is(':checked'),
```
Comment (PVince81) [inline core/js/sharedialogmailview.js]: you missed `emailBccSelf`. better grep for it in case it's used in the CSS files

**Review by PVince81 — COMMENTED** [review]
looks good, just one minor thing

File: core/js/sharedialogmailview.js (hunk 3 above)
Comment (sharidas) [reply core/js/sharedialogmailview.js]: Updated the PR. I grepped for `emailBccSelf` in the core and did not found in the CSS files. But after renaming it, the functionality is not broken. So it is safe with the new change.

**Review by PVince81 — APPROVED** [review]
:+1:

please adjust the backport PR

**Comment by phil-davis** [comment]
This caused a regression in issue #31845 PR #31847
See PR #32632 for proposed fix.
It is text reporting to the UI only, so nothing is broken in terms of actually sending email...
