### PR TITLE
Don't show mail in lock owner data if mail adress is empty string

### LINKED ISSUE #37878: Lock owner has extra brackets at end
### Steps to reproduce
1. As Alice, set your full name to "This is my full name"
2. As Alice, do not set an email address
3. Lock a file using the webUI manual locking
4. View the lock details

### Expected behaviour
Lock information has:
`This is my full name has locked this resource via /IM-6553-D13_1pdf`

(i.e. without the empty `()`)

### Actual behaviour
Lock information has:
`This is my full name () has locked this resource via /IM-6553-D13_1pdf`

### Server configuration
Current core master.

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
Bugfix: Don't show empty brackets in lock owner information if mail not set

## Related Issue

- Fixes https://github.com/owncloud/core/issues/37878

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by JanAckermann** [comment]
On the other hand we can just remove the extra () field as @DeepDiver1975 suggested in the recent issue

File: lib/private/Lock/Persistent/LockManager.php [hunk 1]
```diff
@@ -78,7 +78,7 @@ public function lock($storageId, $internalPath, $fileId, array $lockInfo) {
 			$user = $this->userSession->getUser();
 			if ($user !== null) {
 				$owner = $user->getDisplayName();
-				if ($user->getEMailAddress() !== null) {
+				if (!empty($user->getEMailAddress())) {
```
Comment (phil-davis) [inline lib/private/Lock/Persistent/LockManager.php:81]: I don't like these. In this case the email address should never be the string "0" or "0.0" so I guess there is no real email address that will evaluate to `empty()` `true`.

Comment (JanAckermann) [reply lib/private/Lock/Persistent/LockManager.php:81]: Well @DeepDiver1975 recommended getting rid of the extra data, as this data won't be updated if the user changes the email. I am also not quite sure who is able to see the email and it might not be GDPR compliant.

Comment (JanAckermann) [reply lib/private/Lock/Persistent/LockManager.php:81]: > so I guess there is no real email address that will evaluate to empty() true
Empty string evaluates to true, so I don't understand the objection

>In this case the email address should never be the string "0" or "0.0" 
And that is correct, isn't it?

Comment (phil-davis) [reply lib/private/Lock/Persistent/LockManager.php]: In this case `empty()` works, because the value being compared can never be `0`, `0.0`, "0" or "0.0"!

Comment (JanAckermann) [reply lib/private/Lock/Persistent/LockManager.php]: updated the condition

**Review by JammingBen — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]
works.

Note: to get this problem in the first place, an email address has to have been set for/by a new user. Then the user deleted the email address (sets it to the empty string, effectively). If a user never ever had an email address then this problem did not happen - the user's email address was effectively `null`.

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]
Test coverage?

**Review by DeepDiver1975 — APPROVED** [review]
