### PR TITLE
Only load app routes if the app has already been loaded

### LINKED ISSUE #18095: [regression] [master] App routes are loaded before the app itself
After #17961, app routes are loaded before the app itself is loaded, as the URLGenerator used in OC_Defaults requires a Router, which in turn loads all routes, but this all occurs before any apps are loaded. If an app does initialization in `appinfo/app.php` which is required in `appinfo/routes.php`, then that app will cause errors. I'm not sure if there are any apps that will display these issues, but it's still bad that the app routes are getting loaded before the app itself.

Relevant backtrace from when I noticed it (was unit testing at the time):

```
PHP  10. OC::init() /srv/local/owncloud/core/lib/base.php:1125
PHP  11. OC_Util::checkServer() /srv/local/owncloud/core/lib/base.php:608
PHP  12. OC_Defaults->__construct() /srv/local/owncloud/core/lib/private/util.php:571
PHP  13. OC\URLGenerator->linkToRoute() /srv/local/owncloud/core/lib/private/defaults.php:69
PHP  14. OC\Route\CachingRouter->generate() /srv/local/owncloud/core/lib/private/urlgenerator.php:65
PHP  15. OC\Route\Router->generate() /srv/local/owncloud/core/lib/private/route/cachingrouter.php:53
PHP  16. OC\Route\Router->loadRoutes() /srv/local/owncloud/core/lib/private/route/router.php:305
PHP  17. OC\Route\Router->requireRouteFile() /srv/local/owncloud/core/lib/private/route/router.php:155
PHP  18. include_once() /srv/local/owncloud/core/lib/private/route/router.php:315
```

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Fixes #18095 

If an app isn't loaded when the router tries to load routes, it marks itself as 'not loaded', so the next time a route is requested any non-loaded routes attempt to get loaded again.

cc @schiesbn @LukasReschke @PVince81 @DeepDiver1975

### CODE REVIEW

File: lib/private/route/router.php [hunk 1]
```diff
@@ -150,6 +150,12 @@ public function loadRoutes($app = null) {
 		\OC::$server->getEventLogger()->start('loadroutes' . $requestedApp, 'Loading Routes');
 		foreach ($routingFiles as $app => $file) {
 			if (!isset($this->loadedApps[$app])) {
+				if (!\OC_App::isAppLoaded($app)) {
+					// app MUST be loaded before app routes
+					// try again next time loadRoutes() is called
+					$this->loaded = false;
```
Comment (DeepDiver1975) [inline lib/private/route/router.php]: hmmm ... this might have a negative impact on perf? @icewind1991

Comment (Xenopathic) [inline lib/private/route/router.php]: This variable shortcuts loading all routes, but even when set to false each set of routes (an individual app) doesn't get reloaded due to the check on line 152: `if (!isset($this->loadedApps[$app])) {`

**Comment by Xenopathic** [comment]
@bartv2 @icewind1991 Please review, this fixes a regression

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by DeepDiver1975** [comment]
:+1:

File: lib/private/route/router.php (hunk 1 above)
Comment (nickvergessen) [inline lib/private/route/router.php]: While this helps loading the normal routes, it does not help loading ocs routes of apps.
I will make a second PR fixing this.

**Comment by Xenopathic** [comment]
This problem has manifested itself again...

Displaying the upgrade page results in the Router trying to load all app routes, even though no apps are loaded during the upgrade. This leads to a white screen when an upgrade is required: https://github.com/owncloud/core/pull/15914#issuecomment-131819171

@DeepDiver1975 @icewind1991 @schiesbn We have two options - re-merge this patch, or put a dirty `needUpgrade()` check before getting all app routes. Thoughts?

**Comment by PVince81** [comment]
Or revert this https://github.com/owncloud/core/pull/17961/files#diff-66338aea9c5877c3368c5c7b0ed484ebR69 and not call `linkToRoute` too early. This is what originally produced the series of fixes to try and make the router work earlier than normal.

**Comment by Xenopathic** [comment]
@PVince81 That was the original problem, fixed in #18202. This is more fundemental, and has been an issue in ownCloud for a while now. It's amazing it hasn't blown up yet - apparently according to @LukasReschke it has a few times.

Basically, somewhere in the upgrade code path, a Router is needed, which tries to load app routes, regardless of whether the app is loaded or not yet.
