### PR TITLE
fix uncaught exception on not permitted file types when setting avatar, fixes #17232

### LINKED ISSUE #17232: LDAP - avatar in format other than jpg/png throws exception
Hi,
when using LDAP with OwnCloud lib/private/avatar.php ( https://github.com/owncloud/core/blob/master/lib/private/avatar.php#L104 ) could make instance unusable for some users. If they have avatar in other format than jpg or png - they have 500 internal server error, in logs you just see exception from avatar.php.

Exception:
```javascript
{"Message":"Unknown filetype","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/user\/user.php(346): OC_Avatar->set(Object(OCP\\Image))\n#1 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/user\/user.php(319): OCA\\user_ldap\\lib\\user\\User->setOwnCloudAvatar()\n#2 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/user\/user.php(134): OCA\\user_ldap\\lib\\user\\User->updateAvatar()\n#3 \/var\/www\/html\/owncloud\/apps\/user_ldap\/user_ldap.php(213): OCA\\user_ldap\\lib\\user\\User->update()\n#4 \/var\/www\/html\/owncloud\/lib\/private\/user\/manager.php(113): OCA\\user_ldap\\USER_LDAP->userExists('user')\n#5 \/var\/www\/html\/owncloud\/lib\/private\/user\/manager.php(142): OC\\User\\Manager->get('user')\n#6 \/var\/www\/html\/owncloud\/lib\/private\/user.php(574): OC\\User\\Manager->userExists('user')\n#7 \/var\/www\/html\/owncloud\/lib\/private\/user.php(334): OC_User::userExists('user')\n#8 \/var\/www\/html\/owncloud\/lib\/base.php(774): OC_User::isLoggedIn()\n#9 \/var\/www\/html\/owncloud\/index.php(36): OC::handleRequest()\n#10 {main}","File":"\/var\/www\/html\/owncloud\/lib\/private\/avatar.php","Line":66} 
```

Steps to reproduce:
1. Use LDAP
2. Create user in LDAP with f.e. gif avatar.
3. Try to login to OwnCloud

or
1. Use LDAP
2. Create user in LDAP
3. Login to OwnCloud with that user
4. Set in LDAP gif avatar
5. Every link user opens - will give 500 Internal server error.

### PR DESCRIPTION
**Pull request by blizzz**
And refactors integration tests, because it adds one as well and we don't like to have code duplication, do we. The actual fix is just the third commit, which just adds a try-catch block and does some logging.

Please test and review @11mariom @hostingnuggets @MorrisJobke @tkaufm or others, thx.

@karlitschek also, request to backport to stable8.1 (complete), stable8 and stable7 (both fix only)

Fixes #17232

### CODE REVIEW

File: apps/user_ldap/lib/user/user.php [hunk 1]
```diff
@@ -342,7 +342,13 @@ private function setOwnCloudAvatar() {
 		}
 
 		$avatar = $this->avatarManager->getAvatar($this->uid);
-		$avatar->set($this->image);
+		try {
+			$avatar->set($this->image);
+		} catch (\Exception $e) {
```
Comment (MorrisJobke) [inline apps/user_ldap/lib/user/user.php]: Also log the full exception: `\OCP\Util::logException('user_ldap', $e);`... sometimes an exception only is a special class without a message ;)

**Comment by MorrisJobke** [comment]
Can those integration tests be executed on jenkins?

**Comment by blizzz** [comment]
> Can those integration tests be executed on jenkins?

Not at the moment, but it would be desirable.

For now, how you run them is documented here: https://github.com/owncloud/core/blob/master/apps/user_ldap/tests/integration/readme.md

Also it might make more sense to have something more general that we can use ownCloud wide.

File: apps/user_ldap/lib/user/user.php (hunk 1 above)
Comment (blizzz) [inline apps/user_ldap/lib/user/user.php]: Also or rather instead? It would mostly duplicate it (given the IAvatar PHPdoc is correct, only \Exception for a invalid format is to be expected, others that are thrown are ruled out before by biz logic - of course it may change over time), only with  more details about the exception.

Comment (MorrisJobke) [inline apps/user_ldap/lib/user/user.php]: I'm fine with this :)

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@davitol @SergioBertolinSG Can you help test this?

**Comment by MorrisJobke** [comment]
> @karlitschek also, request to backport to stable8.1 (complete), stable8 and stable7 (both fix only)

;)

**Comment by hostingnuggets** [comment]
+1 for backporting and please let us know which version will have this fix included.

**Comment by blizzz** [comment]
*rebased*

@hostingnuggets is this a "I tested it and it works +1"  or just an "i like it +1"?

**Comment by blizzz** [comment]
@karlitschek backport request is pending

**Comment by karlitschek** [comment]
backport is fine :-)

**Comment by blizzz** [comment]
thank you :)

**Comment by MorrisJobke** [comment]
@SergioBertolinSG @davitol @rperezb Can someone test this please? Thanks :)

**Comment by rperezb** [comment]
@MorrisJobke thanks for the ping, we have added this to the QA queue

**Comment by MorrisJobke** [comment]
@PVince81 Can you test this to get it in? :)

**Comment by PVince81** [comment]
@MorrisJobke I have no idea how to test this, especially how to put an avatar in LDAP.

**Comment by blizzz** [comment]
> I have no idea how to test this, especially how to put an avatar in LDAP.

```php
#!/usr/bin/php
<?php


  $dn = 'uid=zombie29579,ou=zombies,dc=example,dc=com';
  $adn = 'uid=owncloudagent,ou=Users,dc=example,dc=com';
  $apwd = '123456';
  $jpeg = file_get_contents('/tmp/ava.jpg');
  $host = 'localhost';
  $port = 389;

  $jp = array('jpegPhoto' => $jpeg);

  $cr = ldap_connect($host, $port);
  ldap_set_option($cr, LDAP_OPT_PROTOCOL_VERSION, 3);
  ldap_bind($cr, $adn, $apwd);
  ldap_mod_add($cr, $dn, $jp);
```

**Comment by SergioBertolinSG** [comment]
I've reproduced the 500 internal error in stable8.1. And I've tested it on stable8.1+this PR using a gif animated picture. Now there is no crash and the picture isn't shown (default picture with a character is shown instead). It says that the avatar is given by original account, but nothing about the format, perhaps not worthy to warn about it, just to have it clear.

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by blizzz** [comment]
Backport to stable8.1: https://github.com/owncloud/core/pull/17951

**Comment by MorrisJobke** [comment]
> also, request to backport to stable8.1 (complete), stable8 and stable7 (both fix only)

@blizzz Are you also preparing the other two PRs? Thanks :)

**Comment by blizzz** [comment]
@MorrisJobke yes, yes, right at it

**Comment by blizzz** [comment]
Backport to stable8: https://github.com/owncloud/core/pull/17953
Backport to stable7: https://github.com/owncloud/core/pull/17954
