### PR TITLE
Fix language level incompatibilties

### LINKED ISSUE #15463: GlobalStorageService.php incompatible with PHP 5.4
@PVince81 IDE helps :see_no_evil: 
@DeepDiver1975 Can we please get some static code checking for such stuff?

### PR DESCRIPTION
**Pull request by LukasReschke**
Arbitrary expressions in empty are allowed in PHP 5.5 and upwards. Seems to only affect master.

Fixed https://github.com/owncloud/core/issues/15463

### CODE REVIEW

**Comment by LukasReschke** [comment]
@DeepDiver1975 @PVince81 THX

File: apps/files_external/service/globalstoragesservice.php [hunk 1]
```diff
@@ -101,6 +101,7 @@ public function writeConfig($storages) {
 	 * @param string $signal signal to trigger
 	 */
 	protected function triggerHooks(StorageConfig $storage, $signal) {
+		// FIXME: Use as expression in empty once PHP 5.4 support is dropped
 		$applicableUsers = $storage->getApplicableUsers();
```
Comment (LukasReschke) [inline apps/files_external/service/globalstoragesservice.php]: Funny that it was already correct above and then wrong again below… :(

**Comment by PVince81** [comment]
Code looks good :+1:

**Comment by karlitschek** [comment]
good :+1:
