### PR TITLE
LDAP: when checking group for matching filter, also take base DN into…

### LINKED ISSUE #17516: Personal page broken for LDAP users after upgrade to 8.1
### Steps to reproduce
1. Upgrade to 8.1
2. Login as LDAP user
3. Browse to Personal page
4. The page will be blank and this error appear into log:
```
Call to a member function getGID() on a non-object at \/var\/www\/owncloud\/settings\/personal.php#127
```
5.I have temporary reactivate the page editing the file /var/www/owncloud/settings/personal.php and
  a) comment out this line
```
$groups2 = array_map(function($group) { return $group->getGID(); }, $groups);
```
  b) added
```
foreach ($groups as $group) {
   if (is_object($group)) {
     $groups2[] = $group->getGID();
   }
}
```

6. It seems as the problem is an element of array $groups is not an object so line #127 return an error and break page rendering.

### Expected behaviour
Open personal page

### Actual behaviour
Page blank

### Server configuration
**Operating system**: 
Ubuntu server 14.04

**Web server:**
Apache/2.4.7 (Ubuntu)

**Database:**
MySQL

**PHP version:**
PHP 5.5.9-1ubuntu4.11

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.1.0 (stable) 

**Updated from an older ownCloud or fresh install:**
Update from 8.0.4

**List of activated apps:**
 - activity: 2.0.1
 - files: 1.1.9
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - templateeditor: 0.1
 - user_ldap: 0.6.1
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '***',
  'passwordsalt' => '****',
  'secret' => '****',
  'trusted_domains' =>
  array (
    0 => 'ocloud.to.cnr.it',
  ),
  'datadirectory' => '/srv/data',
  'overwrite.cli.url' => 'https://ocloud.to.cnr.it',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => '***',
  'dbhost' => '***',
  'dbtableprefix' => '***',
  'dbuser' => '***',
  'dbpassword' => '***',
  'installed' => true,
  'forcessl' => true,
  'ldapIgnoreNamingRules' => false,

  'theme' => '',
  'maintenance' => false,
  'singleuser' => false,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** 
LDAP+ActiveDirectory (W 2003)

#### LDAP configuration (delete this part if not used)

+-------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                                                                                         |
+-------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                                                       |
| hasPagedResultSupport         |                                                                                                                                                                                         |
| homeFolderNamingRule          |                                                                                                                                                                                         |
| lastJpegPhotoLookup           | 0                                                                                                                                                                                       |
| ldapAgentName                 | ***                                                                                                                                              |
| ldapAgentPassword             | ***                                                                                                                                                                                     |
| ldapAttributesForGroupSearch  |                                                                                                                                                                                         |
| ldapAttributesForUserSearch   |                                                                                                                                                                                         |
| ldapBackupHost                | ***                                                                                                                                                                            |
| ldapBackupPort                | 389                                                                                                                                                                                     |
| ldapBase                      | DC=to,DC=cnr,DC=it                                                                                                                                                                      |
| ldapBaseGroups                | OU=UNR,DC=to,DC=cnr,DC=it                                                                                                                                                         |
| ldapBaseUsers                 | OU=UNR,DC=to,DC=cnr,DC=it                                                                                                                                                         |
| ldapCacheTTL                  | 600                                                                                                                                                                                     |
| ldapConfigurationActive       | 1                                                                                                                                                                                       |
| ldapEmailAttribute            | mail                                                                                                                                                                                    |
| ldapExperiencedAdmin          | 0                                                                                                                                                                                       |
| ldapExpertUUIDGroupAttr       | cn                                                                                                                                                                                      |
| ldapExpertUUIDUserAttr        | cn                                                                                                                                                                                      |
| ldapExpertUsernameAttr        |                                                                                                                                                                                         |
| ldapGroupDisplayName          | cn                                                                                                                                                                                      |
| ldapGroupFilter               | (&(|(objectclass=group))(|(cn=I_all)(cn=IPSP_all)))                                                                                                                                |
| ldapGroupFilterGroups         | I_all;IP_all                                                                                                                                                                     |
| ldapGroupFilterMode           | 0                                                                                                                                                                                       |
| ldapGroupFilterObjectclass    | group                                                                                                                                                                                   |
| ldapGroupMemberAssocAttr      | member                                                                                                                                                                                  |
| ldapHost                      | ***                                                                                                                                                                            |
| ldapIgnoreNamingRules         |                                                                                                                                                                                         |
| ldapLoginFilter               | (&(&(|(objectclass=user))(|(memberof=CN=osers,OU=IUfficioIT,OU=UNR,DC=to,DC=cnr,DC=it)))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))(|(sAMAccountName=%uid)))) |
| ldapLoginFilterAttributes     | sAMAccountName                                                                                                                                                                          |
| ldapLoginFilterEmail          | 1                                                                                                                                                                                       |
| ldapLoginFilterMode           | 0                                                                                                                                                                                       |
| ldapLoginFilterUsername       | 1                                                                                                                                                                                       |
| ldapNestedGroups              | 0                                                                                                                                                                                       |
| ldapNoCase                    | 1                                                                                                                                                                                       |
| ldapOverrideMainServer        | 0                                                                                                                                                                                       |
| ldapPagingSize                | 500                                                                                                                                                                                     |
| ldapPort                      | 389                                                                                                                                                                                     |
| ldapQuotaAttribute            | postOfficeBox                                                                                                                                                                           |
| ldapQuotaDefault              | 20 GB                                                                                                                                                                                   |
| ldapTLS                       | 0                                                                                                                                                                                       |
| ldapUserDisplayName           | displayname                                                                                                                                                                             |
| ldapUserFilter                | (&(|(objectclass=user))(|(|(memberof=CN=osers,OU=IUfficioIT,OU=UNR,DC=to,DC=cnr,DC=it)(primaryGroupID=15831))))                                                       |
| ldapUserFilterGroups          | ocloudUsers                                                                                                                                                                             |
| ldapUserFilterMode            | 0                                                                                                                                                                                       |
| ldapUserFilterObjectclass     | user                                                                                                                                                                                    |
| ldapUuidGroupAttribute        | auto                                                                                                                                                                                    |
| ldapUuidUserAttribute         | auto                                                                                                                                                                                    |
| turnOffCertCheck              | 0                                                                                                                                                                                       |
| useMemberOfToDetectMembership | 1                                                                                                                                                                                       |
+-------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+



### Logs



#### ownCloud log (data/owncloud.log)
"Call to a member function getGID() on a non-object at \/var\/www\/owncloud\/settings\/personal.php#127"

### PR DESCRIPTION
**Pull request by blizzz**
… consideration. Fixes #17516 

Integration test extended.

How to test:
1. LDAP Server must support memberOf.
2. Have an LDAP user with groups of different bases. 
3. Have Group base limited so that some groups are ruled out.
4. Log in with the LDAP user and go to Personal settings.

Before this patch: WPoD
After: Page load properly and all valid groups are shown.

Please test and review @MorrisJobke @giancarlobi @Xenopathic @11mariom or others

@karlitschek: this will require backport to stable8.1. Granted?

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1: 
please backport

**Comment by DeepDiver1975** [comment]
@giancarlobi can you please test this for for #17516 - THX

@rperezb maybe we can get some support on this from QA? THX

**Comment by DeepDiver1975** [comment]
@blizzz can I ask you to open a backport PR against 8.1? THX a lot

**Comment by blizzz** [comment]
Backport to stable8.1: https://github.com/owncloud/core/pull/17704

**Comment by blizzz** [comment]
still in need of reviewers and testers, maybe @davitol @benwilliams @johansmitsnl ?

**Comment by rperezb** [comment]
got it for  @owncloud/qa

File: apps/user_ldap/group_ldap.php [hunk 1]
```diff
@@ -382,7 +382,12 @@ public function getUserGroups($uid) {
 			if (is_array($groupDNs)) {
 				$groupDNs = $this->access->groupsMatchFilter($groupDNs);
 				foreach ($groupDNs as $dn) {
-					$groups[] = $this->access->dn2groupname($dn);
+					$groupName = $this->access->dn2groupname($dn);
+					if(is_string($groupName)) {
```
Comment (nickvergessen) [inline apps/user_ldap/group_ldap.php]: Should this check for `!== false` instead? Because that is what is described bellow. Also not sure what happens to php one day which returns `'1'` as an integer one day?

**Comment by jvillafanez** [comment]
Validated in 8.2 pre alpha (daily) Build:2015-07-24T03:10:53+00:00 582f07950f45d9e0bdfa8faaefa105cad5d39420 + this PR patch

File: apps/user_ldap/group_ldap.php (hunk 1 above)
Comment (blizzz) [inline apps/user_ldap/group_ldap.php]: True, but minor issue, because in that case we need to change a lot of other things as well. So I don't see  urgent need to change, also the backport is already applied, keeping it same is more comfortable for possible future backports, although it's not a huge issue either.
