### PR TITLE
received shares must go into share_folder when configured

### LINKED ISSUE #31342: [10.0.7] Federated shares doesn't appear in the /Shared folder
### Steps to reproduce
1. Configure in config.php ->  ` 'share_folder' => '/Shared', `
2. Accept a federated share
3. The Share appeas in Main folder 

### Expected behavior
Federated share should appear in `/Shared`

### Actual behavior
Federated share appea in Main folder `/`

### Server configuration
**Operating system**:

**Web server:**
Ubuntu 16.04.4 LTS

**PHP version:**
PHP 7.0.28-0ubuntu0.16.04.1 (cli) ( NTS )

**ownCloud version:** (see ownCloud admin page)
ownCloud 10.0.7

**Updated from an older ownCloud or fresh install:**
Updated 

**Where did you install ownCloud from:**
Tar files

**The content of config/config.php:**

```
    "system": {
        "instanceid": "ocuhsyihz2sp",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.damken.com",
            "damken.cloud"
        ],
        "datadirectory": "\/mnt\/owncloud\/data",
        "version": "10.0.7.2",
        "dbtype": "mysql",
        "dbhost": "127.0.0.1",
        "dbname": "ocdamken",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "installed": true,
        "allow_user_to_change_display_name": false,
        "skeletondirectory": "\/var\/www\/skeleton",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauth": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "30,180",
        "versions_retention_obligation": "30,90",
        "updatechecker": false,
        "logfile": "\/home\/www-data\/owncloud.log",
        "loglevel": 0,
        "logtimezone": "Europe\/Berlin",
        "cron_log": true,
        "maintenance": false,
        "singleuser": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "127.0.0.1",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "dav.chunk_base_dir": "\/tmp\/uploads",
        "supportedDatabases": [
            "mysql",
            "pgsql",
            "oci"
        ],
        "share_folder": "\/Shared",
        "minimum.supported.desktop.version": "2.2.4",
        "filesystem_check_changes": 1,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "files_external_allow_create_new_local": true,
        "license-key": "***REMOVED SENSITIVE VALUE***",
        "marketplace.key": "266f277976ec9ba02e0ad93510b2795c27ea9d0f6a01579fd9e6d50ed86128ff",
        "activity_expire_days": 60,
        "collabora_group": "real",
        "integrity.check.disabled": true,
        "smb.logging.enable": false,
        "mysql.utf8mb4": true,
        "debug": false,
        "log.conditions": {
            "apps": [
                "cron"
            ]
        }
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.6
  - bookmarks: 0.10.2
  - calendar: 1.5.7
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.4
  - dav: 0.3.2
  - diagnostics: 0.1.2
  - direct_menu: 0.11.0
  - enterprise_key: 0.1.4
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_clipboard: 0.7.1
  - files_external: 0.7.1
  - files_external_dropbox: 1.0.1
  - files_external_ftp: 0.2.0
  - files_paperhive: 1.0
  - files_reader: 1.2.3
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - impersonate: 0.2.0
  - logreader: 1.1.5
  - market: 0.2.4
  - notifications: 0.3.2
  - ownnote: 1.08
  - pong: true
  - provisioning_api: 0.5.0
  - ransomware_protection: 1.0.1
  - registration: 0.4.0
  - richdocuments: 2.0.5
  - serverinfo: 1.1.1.1
  - systemtags: 0.3.0
  - systemtags_management: 0.2.0
  - tasks: 0.9.6
  - templateeditor: 0.3
  - theme-damkencloud: 1.0.0
  - updatenotification: 0.2.1
  - windows_network_drive: 0.7.0
  - workflow: 0.2.6
Disabled:
  - admin_audit
  - announcementcenter
  - clockwork
  - customgroups
  - encryption
  - external
  - files_antivirus
  - files_ldap_home
  - files_pdfviewer
  - firewall
  - guests
  - oauth2
  - objectstore
  - password_policy
  - sharepoint
  - theme-enterprise
  - theme-example
  - twofactor_totp
  - user_external
  - user_ldap
  - user_shibboleth
  - xmas
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
NFS for main storage
WND for external storages

**Are you using encryption:** yes/no
NO

#### ownCloud log (data/owncloud.log)
(No log appears while reciving  or accepting the federated file)
```
{"reqId":"gQ5oGHfiNPNWRl8l6W4d","level":0,"time":"2018-05-02T17:30:12+02:00","remoteAddr":"87.148.35.15","user":"carlos","app":"no app in context","method":"GET","url":"/index.php/core/preview.png?file=[FILENAME]&x=32&y=32&forceIcon=0","message":"x: "}
{"reqId":"gQ5oGHfiNPNWRl8l6W4d","level":0,"time":"2018-05-02T17:30:12+02:00","remoteAddr":"87.148.35.15","user":"carlos","app":"core","method":"GET","url":"/index.php/core/preview.png?file=[FILENAME]&x=32&y=32&forceIcon=0","message":"Generating preview for "/[FILENAME]" with "OC\Preview\Movie""}
{"reqId":"lXwvYnTpc4oMeimoWAbZ","level":0,"time":"2018-05-02T17:37:42+02:00","remoteAddr":"87.148.35.15","user":"carlos","app":"no app in context","method":"GET","url":"/index.php/core/preview.png?file=[FILENAME]&c=305128af6e9b284d127563dc0f208b58&x=32&y=32&forceIcon=0","message":"x: "}
```

### PR DESCRIPTION
**Pull request by karakayasemi**
## Description
Federates shares currently does not respect to configured share folder. This PR resolves this bug.

## Related Issue
- Fixes #31342

## Motivation and Context
Resolving bug.

## How Has This Been Tested?
Manually by following below steps:
Scenario 1
- install two ownCloud instance
- add `'share_folder' => 'test'` to `config.php`'s of first instance
- share a file from second instance to first instance
- accept the share from first instance
- the file should be in `test` folder

Scenario 2
- install two ownCloud instance
- add second instance as a trusted server in first instance
- configure auto-accepting federated shares from trusted servers in first instance
- add `'share_folder' => 'test'` to `config.php`'s of first instance
- share a file from second instance to first instance
- the file should be in `test` folder

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

File: apps/files_sharing/tests/External/ManagerTest.php [hunk 1]
```diff
@@ -220,6 +220,23 @@ public function testAddShare() {
...
+			'token' => 'token1',
+			'password' => '',
+			'name' => '/SharedFolder',
+			'owner' => 'foobar',
+			'accepted' => true,
+			'user' => $this->uid,
+		];
+
+		// Add a accepted share for "user"
+		\call_user_func_array([$this->manager, 'addShare'], $shareData1);
```
Comment (jvillafanez) [inline apps/files_sharing/tests/External/ManagerTest.php]: why the "call_user_func_array"?

**Comment by jvillafanez** [comment]
did this feature work with federated shares? Maybe we should include an additional option to use a different folder for federated shares (pinging @pmaier1 for this).
We could have `shared_folder => Shared` and `federated_shared_folder => Federated_Shared`, or both keys could also be set up to use the same folder.

File: apps/files_sharing/tests/External/ManagerTest.php (hunk 1 above)
Comment (karakayasemi) [reply apps/files_sharing/tests/External/ManagerTest.php]: I followed syntax of the previous tests. I guess passing parameters as an array is easier.

**Comment by karakayasemi** [comment]
> 
> 
> did this feature work with federated shares? Maybe we should include an additional option to use a different folder for federated shares (pinging @pmaier1 for this).
> We could have `shared_folder => Shared` and `federated_shared_folder => Federated_Shared`, or both keys could also be set up to use the same folder.

There is an open issue for this feature and it was identified as bug. @pmaier1's thought is valuable for deciding whether separation of this configuration. I can modify the PR after decision.

**Comment by pmaier1** [comment]
I don't see a reason to split these folders. Why would you?

Generally speaking, federated sharing should be as transparent as possible to users (many users don't understand the concept), meaning for a regular user it should not make a difference whether a share is local or federated.

**Review by micbar — APPROVED** [review]
Tested in DamkenCloud. 👍

**Comment by micbar** [comment]
@karakayasemi please merge and backport.

**Comment by karakayasemi** [comment]
Backport PR: https://github.com/owncloud/core/pull/35396

**Review by cdamken — COMMENTED** [review]
now the share comes in the "/Shared" folder as desired.

But

in "Share with you"  still doesn't appear the shares.

**Comment by karakayasemi** [comment]
Hmm, in the related issue description, I could not see anything about "Shared with you" problem. @cdamken we may raise a new ticket for it.

**Comment by cdamken** [comment]
Your are right, it was not described above, I just notice it now

we can create a new ticket for that

Thanks! 😄
