### PR TITLE
make versions of shared files downloadable

### LINKED ISSUE #12221: Versioning + encryption: former versions are not decrypted when downloaded
When I download a former version of a text file from a shared folder, it is downloaded encrypted. I open this new issue after https://github.com/owncloud/core/issues/11761 and @schiesbn advice

### Steps to reproduce
1. UserA creates FolderA. 
2. UserA creates Welcome.txt in Folder A
3. UserA modifies Welcome.txt in order to have a previous version available: everything's fine until here
4. UserA shares FolderA with UserB
5. UserB downloads the previous version of Welcome.txt : the document is encrypted

### Expected behaviour
The document should be downloaded decrypted

### Server configuration
**Operating system**: Ubuntu 14.10
**Web server:** Apache 2.4.10
**Database:** MySQL Ver 14.14 Distrib 5.5.40
**PHP version:** 5.5.12
**ownCloud version:** 7.0.3
**List of activated apps:** Encryption
**Are you using external storage** No
**Are you using encryption:** yes

### Client configuration
**Browser:** FF 31
**Operating system:** Windows 8.1

### PR DESCRIPTION
**Pull request by schiessle**
fix download of versions from shared files.

Step to test:
- enable encryption
- user1 creates a file "test.txt"
- user1 edits the file so that we have at least one version
- user1 shares the file with user2
- login as user2
- try to download a version from the shared file

fix #12221

### CODE REVIEW

**Comment by karlitschek** [comment]
great :+1:

**Comment by MorrisJobke** [comment]
@karlitschek @schiesbn @DeepDiver1975 Should this be part of owncloud 8.0 or 8.1?

**Comment by karlitschek** [comment]
yes please

**Comment by MorrisJobke** [comment]
@karlitschek This was an "or"-question ;) 8.0 OR 8.1? Which one?

File: apps/files_encryption/lib/helper.php [hunk 1]
```diff
@@ -281,55 +281,68 @@ public static function getUser($path) {
...
-		}
+		if (count($split) > 3 && (
+			$split[2] === 'files' || $split[2] === 'files_versions' || $split[2] === 'cache')) {
 
-		$user = $split[0];
+			$user = $split[1];
 
-		if (\OCP\User::userExists($user)) {
-			return $user;
+			if (\OCP\User::userExists($user)) {
```
Comment (LukasReschke) [inline apps/files_encryption/lib/helper.php]: What about injecting `IUserManager` in this function and then use `\OCP\IUserManager::userExists`? 

That would actually make that function unit-testable. As far I can see it is not really tested now.

File: apps/files_encryption/lib/stream.php [hunk 2]
```diff
@@ -124,24 +125,31 @@ public function stream_open($path, $mode, $options, &$opened_path) {
...
+				$this->userId = \OC::$server->getUserSession()->getUser()->getUID();
+				break;
+			case Util::FILE_TYPE_VERSION:
+				$this->relPath = Helper::getPathFromVersion($this->rawPath);
+				$this->userId = Helper::getUserFromPath($this->rawPath);
+				break;
+			case Util::FILE_TYPE_CACHE:
+				$this->relPath = Helper::getPathFromCachedFile($this->rawPath);
+				Helper::mkdirr($this->rawPath, new \OC\Files\View('/'));
+				$this->userId = \OC::$server->getUserSession()->getUser()->getUID();
```
Comment (LukasReschke) [inline apps/files_encryption/lib/stream.php]: Can the UserSession get injected?

File: apps/files_encryption/lib/helper.php [hunk 3]
```diff
@@ -281,55 +281,68 @@ public static function getUser($path) {
...
+	public static function getUserFromPath($path) {
+		$normalized = \OC\Files\Filesystem::normalizePath($path);
+		$split = explode('/', $normalized);
 
-		// it is not a file relative to data/user/files
-		if (count($split) < 2 || ($split[1] !== 'files' && $split[1] !== 'cache')) {
-			return false;
-		}
+		if (count($split) > 3 && (
+			$split[2] === 'files' || $split[2] === 'files_versions' || $split[2] === 'cache')) {
```
Comment (LukasReschke) [inline apps/files_encryption/lib/helper.php]: This codefragment seems kinda duplicated within this PR - maybe reuse  `detectFileType` somehow?

File: apps/files_encryption/lib/helper.php [hunk 4]
```diff
@@ -454,6 +467,29 @@ public static function getPathFromTmpFile($tmpFile) {
 	}
 
 	/**
+	 * detect file type, encryption can read/write regular files, versions
+	 * and cached files
+	 *
+	 * @param string $path
+	 * @return int
+	 * @throw Exception\EncryptionException
```
Comment (LukasReschke) [inline apps/files_encryption/lib/helper.php]: `@throws`

File: apps/files_encryption/lib/helper.php [hunk 5]
```diff
@@ -281,55 +281,68 @@ public static function getUser($path) {
...
+	}
 
-		$trimmed = ltrim($path, '/');
-		$split = explode('/', $trimmed);
+	/**
+	 * extract user from path
+	 *
+	 * @param string $path
+	 * @return string user id
+	 * @throw OCA\Files_Encryption\Exception\EncryptionException
```
Comment (LukasReschke) [inline apps/files_encryption/lib/helper.php]: `@throws`

File: apps/files_encryption/lib/helper.php [hunk 6]
```diff
@@ -281,55 +281,68 @@ public static function getUser($path) {
 
 		// if no user is logged in we try to access a publicly shared files.
 		// In this case we need to try to get the user from the path
+		return self::getUserFromPath($path);
```
Comment (LukasReschke) [inline apps/files_encryption/lib/helper.php]: This is a change in behaviour. Previously this function returned `false` if no user has been found. However, now it can throw an exception as well.

Comment (LukasReschke) [inline apps/files_encryption/lib/helper.php]: Either adjust PHPDoc or catch the exception and return false.

File: apps/files_encryption/lib/helper.php [hunk 7]
```diff
@@ -281,55 +281,68 @@ public static function getUser($path) {
...
+
+	/**
+	 * get path to the corresponding file in data/user/files for a version
+	 *
+	 * @param string $path path to a version
+	 * @return string path to corresponding file relative to data/user/files
+	 */
+	public static function getPathFromVersion($path) {
+		$normalized = \OC\Files\Filesystem::normalizePath($path);
+		$split = explode('/', $normalized);
```
Comment (LukasReschke) [inline apps/files_encryption/lib/helper.php]: Code-duplication: Move into it's own private helper? (`splitPath`?)

File: apps/files_encryption/lib/helper.php [hunk 8]
```diff
@@ -281,55 +281,68 @@ public static function getUser($path) {
...
-				//prepare the folders
-				self::mkdirr($path, new \OC\Files\View('/'));
-			}
-		}
+	public static function getPathFromCachedFile($path) {
+		$normalized = \OC\Files\Filesystem::normalizePath($path);
+		$split = explode('/', $normalized);
+
+		// we skip /user/cache/transactionId
+		$sliced = array_slice($split, 4);
```
Comment (LukasReschke) [inline apps/files_encryption/lib/helper.php]: Add a count for `$split`? - While currently it might always be called in a way with proper paths this might change in future, maybe due to a bug or whatever.

I'd throw an error in case the array does not contain enough elements. Easiest approach to catch potential bugs in the future.

File: apps/files_encryption/lib/helper.php [hunk 9]
```diff
@@ -281,55 +281,68 @@ public static function getUser($path) {
...
+	 *
+	 * @param string $path path to a version
+	 * @return string path to corresponding file relative to data/user/files
+	 */
+	public static function getPathFromVersion($path) {
+		$normalized = \OC\Files\Filesystem::normalizePath($path);
+		$split = explode('/', $normalized);
+
+		// we skip user/files_versions
+		$sliced = array_slice($split, 3);
```
Comment (LukasReschke) [inline apps/files_encryption/lib/helper.php]: Also here: count `$split`

File: apps/files_encryption/lib/helper.php [hunk 10]
```diff
@@ -454,6 +467,29 @@ public static function getPathFromTmpFile($tmpFile) {
...
+	 * and cached files
+	 *
+	 * @param string $path
+	 * @return int
+	 * @throw Exception\EncryptionException
+	 */
+	public static function detectFileType($path) {
+	    $parts = explode('/', $path);
+
+	    switch($parts[2]) {
```
Comment (LukasReschke) [inline apps/files_encryption/lib/helper.php]: Count `$parts`

File: apps/files_encryption/lib/helper.php [hunk 11]
```diff
@@ -454,6 +467,29 @@ public static function getPathFromTmpFile($tmpFile) {
...
+			case 'files':
+				return Util::FILE_TYPE_FILE;
+			case 'files_versions':
+				return Util::FILE_TYPE_VERSION;
+			case 'cache':
+				return Util::FILE_TYPE_CACHE;
+			default:
+				throw new Exception\EncryptionException('Could not detect file type', Exception\EncryptionException::GENERIC);
```
Comment (LukasReschke) [inline apps/files_encryption/lib/helper.php]: What about moving this out of the switch and at the end of the function? - Then you can easily add the `count()` and don't have to duplicate the encryption exception.

File: apps/files_encryption/lib/proxy.php [hunk 12]
```diff
@@ -56,10 +56,12 @@ protected function isExcludedPath($path, $uid) {
 
 		$path = \OC\Files\Filesystem::normalizePath($path);
 
+		$parts = explode('/', $path);
+
 		// we only encrypt/decrypt files in the files and files_versions folder
 		if(
 			strpos($path, '/' . $uid . '/files/') !== 0 &&
-			strpos($path, '/' . $uid . '/files_versions/') !== 0) {
+			!($parts[2] === 'files_versions' && \OCP\User::userExists($parts[1]))) {
```
Comment (LukasReschke) [inline apps/files_encryption/lib/proxy.php]: Please use an helper (maybe one of the ones you added?) instead of accessing the array key directly here - very hard to understand.

File: apps/files_encryption/lib/stream.php [hunk 13]
```diff
@@ -124,24 +125,31 @@ public function stream_open($path, $mode, $options, &$opened_path) {
...
-		}
+		$fileType = Helper::detectFileType($this->rawPath);
 
-		if($this->relPath === false) {
-			\OCP\Util::writeLog('Encryption library', 'failed to open file "' . $this->rawPath . '" expecting a path to "files", "files_versions" or "cache"', \OCP\Util::ERROR);
-			return false;
+		switch ($fileType) {
+			case Util::FILE_TYPE_FILE:
+				$this->relPath = Helper::stripUserFilesPath($this->rawPath);
+				$this->userId = \OC::$server->getUserSession()->getUser()->getUID();
```
Comment (LukasReschke) [inline apps/files_encryption/lib/stream.php]: Same as https://github.com/owncloud/core/pull/13182/files#r22690428

File: apps/files_encryption/lib/helper.php (hunk 5 above)
Comment (LukasReschke) [inline apps/files_encryption/lib/helper.php]: Also needs to be prefixed with \

File: apps/files_encryption/tests/helper.php [hunk 14]
```diff
@@ -76,17 +76,25 @@ function testStripPartialFileExtensionWithTransferIdPath() {
...
-
+	function testGetPathFromVersion() {
 		// the relative path to /user/files/ that's what we want to get from getPathToRealFile()
 		$relativePath = "foo/bar/test.txt";
 
-		// test paths
+		// test path
 		$versionPath = "/user/files_versions/foo/bar/test.txt.v456756835";
+
+		$this->assertEquals($relativePath, \OCA\Files_Encryption\Helper::getPathFromVersion($versionPath));
```
Comment (LukasReschke) [inline apps/files_encryption/tests/helper.php]: That unit test is actually only testing the successful case and only a single one, I'd propose to use a [`Data Provider`](https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers) which allows to test more values without making the code more complicated.

You'd just need to create an array containing the input and the expected result, that way you could also test crazier paths than the one you're doing here.

Would also be great to test with input that won't work properly such as without `/user/files_versions` since you never can ensure that the function will always be called correctly the same way.

File: apps/files_encryption/tests/helper.php [hunk 15]
```diff
@@ -76,17 +76,25 @@ function testStripPartialFileExtensionWithTransferIdPath() {
...
+
+		// the relative path to /user/files/ that's what we want to get from getPathToRealFile()
+		$relativePath = "foo/bar/test.txt";
+
+		// test path
 		$cachePath = "/user/cache/transferid636483/foo/bar/test.txt";
 
-		$this->assertEquals($relativePath, \OCA\Files_Encryption\Helper::getPathToRealFile($versionPath));
-		$this->assertEquals($relativePath, \OCA\Files_Encryption\Helper::getPathToRealFile($cachePath));
+		$this->assertEquals($relativePath, \OCA\Files_Encryption\Helper::getPathFromCachedFile($cachePath));
```
Comment (LukasReschke) [inline apps/files_encryption/tests/helper.php]: DataProvider with some more tests would also be cool here.

File: apps/files_encryption/tests/testcase.php [hunk 16]
```diff
@@ -34,7 +34,8 @@ public static function loginHelper($user, $create = false, $password = false, $l
 		\OC_Util::tearDownFS();
 		\OC_User::setUserId('');
 		\OC\Files\Filesystem::tearDown();
-		\OC_User::setUserId($user);
+		\OC_User::setUserId($user); //FIXME can be removed if all \OCP\User::getUser() calls are removed
```
Comment (LukasReschke) [inline apps/files_encryption/tests/testcase.php]: Mhm… - I'm fairly sure the current implementation of `\OCP\User::getUser` in master is compatible with `setUser`. What is the reason for keeping this line here?

File: apps/files_encryption/lib/helper.php (hunk 1 above)
Comment (karlitschek) [inline apps/files_encryption/lib/helper.php]: lol.  @morrisjobke i meant 8.0 :-)

File: apps/files_encryption/lib/stream.php [hunk 17]
```diff
@@ -614,11 +613,9 @@ public function stream_close() {
 				// Check if OC sharing api is enabled
 				$sharingEnabled = \OCP\Share::isEnabled();
 
-				$util = new Util($this->rootView, $this->userId);
-
 				// Get all users sharing the file includes current user
-				$uniqueUserIds = $util->getSharingUsersArray($sharingEnabled, $this->relPath);
-				$checkedUserIds = $util->filterShareReadyUsers($uniqueUserIds);
+				$uniqueUserIds = $this->util->getSharingUsersArray($sharingEnabled, $this->relPath);
```
Comment (DeepDiver1975) [inline apps/files_encryption/lib/stream.php]: this->util? there is still a $util above - looks strange to me - THX

File: apps/files_encryption/lib/helper.php (hunk 1 above)
Comment (DeepDiver1975) [inline apps/files_encryption/lib/helper.php]: In case the helper class would not be static injecting IUserManager in the ctor would be the way to go - for now: let's keep it that way.

File: apps/files_encryption/lib/stream.php (hunk 17 above)
Comment (DeepDiver1975) [inline apps/files_encryption/lib/stream.php]: I was referring to $util in https://github.com/owncloud/core/pull/13182/files#diff-9b2838d73447a8a233abe1f76fdc8ae7R329 - which is a different function as I just detected - but still no needed I guess?

**Comment by PVince81** [comment]
:+1: tested, works.
Went through the code with @schiesbn, changes make sense

**Comment by LukasReschke** [comment]
This broke sharing: https://github.com/owncloud/core/issues/13270
