### PR TITLE
Fallback for crappy ancient distributions

### LINKED ISSUE #23181: Encryption no longer working after update from 8.2.2 to 9.0.0
### Steps to reproduce
1. Upgrade owncloud (manual upgrade since I'm on a shared host without root or shell access)
2. Upload new file

### Expected behaviour
File gets uploaded and encrypted as the existing files

### Actual behaviour
upload never finishes, errors in log

### Server configuration
**Operating system**:
Linux

**Web server:**
Apache

**Database:**
MySQL 5.1

**PHP version:**
5.5

**ownCloud version:** (see ownCloud admin page)
9.0

**Updated from an older ownCloud or fresh install:**
upgrade from 8.2

ERRORLOG:
{"reqId":"VuQexwouCIoAAGS1LvgAAAA4","remoteAddr":"IPADRESS","app":"PHP","message":"openssl_encrypt(): Unknown cipher algorithm at \PATH\/owncloud\/apps\/encryption\/lib\/crypto\/crypt.php#238","level":3,"time":"2016-03-12T13:51:03+00:00"}
{"reqId":"VuQexwouCIoAAGS1LvgAAAA4","remoteAddr":"IPADRESS","app":"encryption","message":"Encryption (symmetric) of content failed","level":3,"time":"2016-03-12T13:51:03+00:00"}
{"reqId":"VuQexwouCIoAAGS1LvgAAAA4","remoteAddr":"IPADRESS","app":"PHP","message":"openssl_encrypt(): Unknown cipher algorithm at \PATH\/owncloud\/apps\/encryption\/lib\/crypto\/crypt.php#238","level":3,"time":"2016-03-12T13:51:03+00:00"}
{"reqId":"VuQexwouCIoAAGS1LvgAAAA4","remoteAddr":"IPADRESS","app":"encryption","message":"Encryption (symmetric) of content failed","level":3,"time":"2016-03-12T13:51:03+00:00"}
{"reqId":"VuQexwouCIoAAGS1LvgAAAA4","remoteAddr":"IPADRESS","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \PATH\/owncloud\/lib\/private\/json.php:166) at \PATH\/owncloud\/lib\/private\/response.php#103","level":3,"time":"2016-03-12T13:51:03+00:00"}
{"reqId":"VuQezwouCIoAAGAdGzsAAAAU","remoteAddr":"IPADRESS","app":"PHP","message":"Undefined index: newVersionString at \PATH\/owncloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-12T13:51:11+00:00"}

what can I do since encryption can't be deactivated? please help!

### PR DESCRIPTION
**Pull request by LukasReschke**
Fixes https://github.com/owncloud/core/issues/23181

Totally untested. Installing a such old OpenSSL version in combination with a compatible PHP and libxml2 version of ownCloud takes multiple hours. Whoever wants to have that fun can do that. I won't :see_no_evil: 

It's quite a miracle to see custom maintained distributions having such an horrible mixup of broken old with somewhat decent new. Not that I'm keen about this. So whoever in the future will hate me for this should read https://github.com/owncloud/core/issues/23181#issuecomment-195806012 :wink: 

@lorddoumer Please test.
@karlitschek Ref https://github.com/owncloud/core/issues/23181#issuecomment-195815260

### CODE REVIEW

File: apps/encryption/lib/crypto/crypt.php [hunk 1]
```diff
@@ -266,6 +266,13 @@ public function getCipher() {
 			$cipher = self::DEFAULT_CIPHER;
 		}
 
+		// Workaround for OpenSSL 0.9.8. Fallback to an old cipher that should work.
+		if(OPENSSL_VERSION_NUMBER < 0x1000101f) {
```
Comment (LukasReschke) [inline apps/encryption/lib/crypto/crypt.php]: Got this version from https://github.com/openssl/openssl/blob/OpenSSL_1_0_1/crypto/opensslv.h#L28 :see_no_evil:

**Comment by lorddoumer** [comment]
working fine and fixes #23181 
thanks!

**Comment by PVince81** [comment]
@LukasReschke do we also have a warning in the admin page about such ancient versions ?

**Comment by PVince81** [comment]
Code looks good :+1:

**Comment by PVince81** [comment]
@schiesbn second review ?

**Comment by LukasReschke** [comment]
> @LukasReschke do we also have a warning in the admin page about such ancient versions ?

I'm not adding another error message there myself since I'm so fed up by the resulting discussions :disappointed_relieved: 

So let's just try to pseudo support it and do … :see_no_evil: … at least the patch is not too invasive.

**Comment by karlitschek** [comment]
Yes. We don't need a warning message. Problem of the outdated distribution.

**Comment by LukasReschke** [comment]
Stable9 is at https://github.com/owncloud/core/pull/23271

**Comment by rullzer** [comment]
:+1:
