### PR TITLE
Prefilter inaccessible shares in DefaultShareProvider::getSharedWith()

### LINKED ISSUE #26001: Lazy shared storage heII: ghost mounts
Found through https://github.com/owncloud/core/pull/25977

### Steps

1. Create two users "user0" and "user1"
1. Login as "user0"
1. Create folders "common/sub"
1. Share "sub" with "user1"
1. Delete "common"
1. Empty trashbin
1. Login as "user1"
1. PROPFIND on "sub"
1. Create a folder "sub"

### Expected
404 not found for PROPFIND, folder "sub" can be created.

### Actual
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>InvalidArgumentException</s:exception>
  <s:message>Jail rootPath is null</s:message>
</d:error>
```
Cannot create folder "sub" as "user1".

### Versions
9.1.1RC1 / stable9.1

The problem here is that due to lazy initialization, the mount system thinks that the mount is there until it gets initialized later. Then it turns out it's not supposed to be there but is still registered. So creating a folder with the same name fails.
And querying its existence also causes issues.

### PR DESCRIPTION
**Pull request by PVince81**
## Description

See https://github.com/owncloud/core/issues/26001 for context.
We need to prevent the shared mount provider to expose mounts where the source file is not accessible any more when in trash or completely deleted. This is important to avoid issues where the user cannot create a folder with the name of the mount point because it's still there but "ghosted".
This fix guarantees that the mount point is not present at all and all code paths for file operations won't be impaired by a ghost mount.

What this does: prefilter inaccessible shares in DefaultShareProvider::getSharedWith()

The DefaultShareProvider now does a DB-level check to find out whether file_source is accessible at all (deleted file) or whether it's in the trashbin of a home storage.

Note: One small corner case where the home storage id is in md5 form cannot be covered properly with this approach. This would only happen for user ids longer than `64 - strlen('home::')` which is 58 characters. LDAP ids are usually shorter than that.
## Related Issue

Fixes https://github.com/owncloud/core/issues/26001
## Motivation and Context

Pfff, because of shared storage HELL, that is. See context.
## How Has This Been Tested?
- [x] TEST: shared folder still received when not deleted
- [x] TEST: fileid pointing to non-existing file
- [x] TEST: fileid pointing at file in trash
- [x] TEST: create folder "sub" then restore the file as owner
- [x] TEST: rename another folder to "sub" when invisible/ghosted
- [x] TEST: "Shared with you" section in files app still shows existing valid entries
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
## Backports:
- [x] stable9.1
## Open TODOS:
- [x] write unit test

### CODE REVIEW

**Comment by PVince81** [comment]
Please review, I'd like to know whether this approach is acceptable before I dive into the pain of writing tests. Thanks.

File: lib/private/Share20/DefaultShareProvider.php [hunk 1]
```diff
@@ -591,11 +610,14 @@ public function getSharedWith($userId, $shareType, $node, $limit, $offset) {
 		if ($shareType === \OCP\Share::SHARE_TYPE_USER) {
 			//Get shares directly with this user
 			$qb = $this->dbConn->getQueryBuilder();
-			$qb->select('*')
-				->from('share');
+			$qb->select('s.*', 'f.fileid', 'f.path')
+				->selectAlias('st.id', 'storage_string_id')
+				->from('share', 's')
+				->leftJoin('s', 'filecache', 'f', 's.file_source = f.fileid')
+				->leftJoin('f', 'storages', 'st', 'f.storage = st.numeric_id');
```
Comment (PVince81) [inline lib/private/Share20/DefaultShareProvider.php]: ping DB experts @butonic @DeepDiver1975 

I hope this is acceptable... Will this kill Oracle ?

Else I can make subqueries for this, not sure about perf...

Comment (nickvergessen) [inline lib/private/Share20/DefaultShareProvider.php]: Yes, use $qb->expr()->eq()

Comment (PVince81) [inline lib/private/Share20/DefaultShareProvider.php]: Assuming "Yes" is the answer for the first question "I hope this is acceptable". Thanks.

I'll change it to use `$qb->expr()->eq()`

Comment (nickvergessen) [inline lib/private/Share20/DefaultShareProvider.php]: The yes was to "Will this kill Oracle ?"

**Comment by PVince81** [comment]
Test failures unrelated.

Please review @butonic @jvillafanez @DeepDiver1975 @VicDeo, needed for 9.1.1

File: lib/private/Share20/DefaultShareProvider.php [hunk 2]
```diff
@@ -582,6 +582,25 @@ public function getSharesByPath(Node $path) {
...
+	 * a share with accessible file (not trashed, not deleted)
+	 */
+	private function isAccessibleResult($data) {
+		// exclude shares leading to deleted file entries
+		if ($data['fileid'] === null) {
+			return false;
+		}
+
+		// exclude shares leading to trashbin on home storages
+		$pathSections = explode('/', $data['path'], 2);
```
Comment (jvillafanez) [inline lib/private/Share20/DefaultShareProvider.php]: What about external storages? Will they work properly?

Comment (PVince81) [inline lib/private/Share20/DefaultShareProvider.php]: Yes, see below, the crude check for home storage

**Comment by jvillafanez** [comment]
👍

**Comment by PVince81** [comment]
Rebased for hopefully passing tests

**Comment by PVince81** [comment]
stable9.1: https://github.com/owncloud/core/pull/26050

(yes, am optimistic about the tests...)
