### PR TITLE
Contacts API: replace raw image data with url

### LINKED ISSUE #23345: DAV app returns raw contact image instead of URL
### Steps to reproduce
1. Use OCP\Contacts\IManager::search
2. Use the 'PHOTO' attribute as url for the contacts image

### Expected behaviour
'PHOTO' should be a valid URL for an image that can be used in the browser, e.g. contact images in the mail app.

### Actual behaviour
'PHOTO' contains the raw image.

**ownCloud version:** (see ownCloud admin page)
9

That behavior changed when switching from the old contacts app to the new dav app and therefore breaks mail on oc9, see https://github.com/owncloud/mail/pull/1352 for a quick fix.

@DeepDiver1975 as discussed

### PR DESCRIPTION
**Pull request by georgehrke**
fixes https://github.com/owncloud/core/issues/23345
- [x] adjust tests

### CODE REVIEW

File: apps/dav/appinfo/routes.php [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+ * GNU Affero General Public License for more details.
+ *
+ * You should have received a copy of the GNU Affero General Public License, version 3,
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>
+ *
+ */
+
+return [
+	'routes' => [
+		['name' => 'photos#get', 'url' => '/contactsphoto/{addressbookId}/{contactUri}', 'verb' => 'GET'],
```
Comment (DeepDiver1975) [inline apps/dav/appinfo/routes.php]: hmmm ... I would have built this as part of the webdav routes

please note there are only 2 public http based protocols we support: webdav and ocs api.
routes like above are considered private and should not be exposed to 3rdparty - the mail and contacts apps are treated as 3rdparty

Comment (georgehrke) [inline apps/dav/appinfo/routes.php]: I'm not so sure about the webdav route, because this change only affects the PHP based Contacts API. Adding this to the WebDAV routes would require apps like the Mail app to implement a dav client just to fetch contact images 😕

Comment (DeepDiver1975) [inline apps/dav/appinfo/routes.php]: > Adding this to the WebDAV routes would require apps like the Mail app to implement a dav client just to fetch contact images :confused:

A GET is a GET is a GET .... :speak_no_evil:

Comment (georgehrke) [inline apps/dav/appinfo/routes.php]: > A GET is a GET is a GET ....

Well, there is some truth to this 🙈

Comment (georgehrke) [inline apps/dav/appinfo/routes.php]: Is there some "easy" straight forward way to register routes or do I need to write a plugin like in https://github.com/owncloud/core/blob/master/apps/dav/lib/Comments/CommentsPlugin.php#L86?

Comment (DeepDiver1975) [inline apps/dav/appinfo/routes.php]: here we go ... https://github.com/owncloud/core/pull/25121

File: apps/dav/lib/Server.php [hunk 2]
```diff
@@ -103,6 +104,7 @@ public function __construct(IRequest $request, $baseUri) {
 		// addressbook plugins
 		$this->server->addPlugin(new \OCA\DAV\CardDAV\Plugin());
 		$this->server->addPlugin(new VCFExportPlugin());
+		$this->server->addPlugin(new ImageExportPlugin());
```
Comment (DeepDiver1975) [inline apps/dav/lib/Server.php]: Must be added to the serverfactory as well for v1 routes

File: apps/dav/lib/CardDAV/AddressBookImpl.php [hunk 3]
```diff
@@ -207,11 +206,15 @@ protected function createEmptyVCard($uid) {
...
 	 * create array with all vCard properties
 	 *
+	 * @param string $uri
 	 * @param VCard $vCard
 	 * @return array
 	 */
-	protected function vCard2Array(VCard $vCard) {
-		$result = [];
+	protected function vCard2Array($uri, VCard $vCard) {
+		$result = [
```
Comment (georgehrke) [inline apps/dav/lib/CardDAV/AddressBookImpl.php]: @DeepDiver Is there some helper method to generate the full carddav url here?
I have access to the principal uris, but no direct access to addressbooks/users/admin/contacts/

Comment (DeepDiver1975) [inline apps/dav/lib/CardDAV/AddressBookImpl.php]: no helper method at hand - the addressbook name is in addressBookInfo or in the addrebook instance.

No idea if this helps. THX

File: apps/dav/lib/Server.php (hunk 2 above)
Comment (georgehrke) [inline apps/dav/lib/Server.php]: done

**Comment by georgehrke** [comment]
please review @DeepDiver1975 @ChristophWurst @PVince81

**Comment by ChristophWurst** [comment]
:+1: nice, works!

File: apps/dav/lib/CardDAV/ImageExportPlugin.php [hunk 4]
```diff
@@ -0,0 +1,119 @@
...
+
+use Sabre\CardDAV\Card;
+use Sabre\DAV\Server;
+use Sabre\DAV\ServerPlugin;
+use Sabre\HTTP\RequestInterface;
+use Sabre\HTTP\ResponseInterface;
+use Sabre\VObject\Parameter;
+use Sabre\VObject\Reader;
+
+class ImageExportPlugin extends ServerPlugin {
```
Comment (DeepDiver1975) [inline apps/dav/lib/CardDAV/ImageExportPlugin.php]: this plugin deserves some unit tests as well :see_no_evil:

File: apps/dav/lib/CardDAV/ImageExportPlugin.php [hunk 5]
```diff
@@ -0,0 +1,119 @@
...
+		try {
+			/** @var Parameter $type */
+			$type = $photo->parameters()['TYPE'];
+			$val = $photo->getValue();
+			return [
+				'Content-Type' => $type->getValue(),
+				'body' => $val
+			];
+		} catch(\Exception $ex) {
+//			$this->logger->debug($ex->getMessage());
```
Comment (DeepDiver1975) [inline apps/dav/lib/CardDAV/ImageExportPlugin.php]: remove or add logger

File: apps/dav/lib/Server.php (hunk 2 above)
Comment (DeepDiver1975) [inline apps/dav/lib/Server.php]: thx

**Comment by DeepDiver1975** [comment]
@ChristophWurst @Gomez did you test this with the mail app? does it work? THX

**Comment by Gomez** [comment]
Yeah works in Mail! Nice @georgehrke

File: apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php [hunk 6]
```diff
@@ -0,0 +1,151 @@
...
+
+	public function providesPhotoData() {
+		return [
+			'empty vcard' => [false, ''],
+			'vcard without PHOTO' => [false, "BEGIN:VCARD\r\nVERSION:3.0\r\nPRODID:-//Sabre//Sabre VObject 3.5.0//EN\r\nUID:12345\r\nFN:12345\r\nN:12345;;;;\r\nEND:VCARD\r\n"],
+			'vcard 3 with PHOTO' => [['Content-Type' => 'image/jpeg', 'body' => '12345'], "BEGIN:VCARD\r\nVERSION:3.0\r\nPRODID:-//Sabre//Sabre VObject 3.5.0//EN\r\nUID:12345\r\nFN:12345\r\nN:12345;;;;\r\nPHOTO;ENCODING=b;TYPE=JPEG:MTIzNDU=\r\nEND:VCARD\r\n"],
+			//
+			// TODO: these three below are not working - needs debugging
+			//
+//			'vcard 3 with PHOTO URL' => [['Content-Type' => 'image/jpeg', 'body' => '12345'], "BEGIN:VCARD\r\nVERSION:3.0\r\nPRODID:-//Sabre//Sabre VObject 3.5.0//EN\r\nUID:12345\r\nFN:12345\r\nN:12345;;;;\r\nPHOTO;TYPE=JPEG:http://example.org/photo.jpg\r\nEND:VCARD\r\n"],
```
Comment (DeepDiver1975) [inline apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php]: @georgehrke mind debugging these 3 cases and adjust the code accordingly?

Comment (georgehrke) [inline apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php]: Sure, I can take a look tomorrow

Comment (DeepDiver1975) [inline apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php]: Thx

Comment (georgehrke) [inline apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php]: How is http://example.org/photo.jpg supposed to return '12345' in the first place?

Comment (georgehrke) [inline apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php]: anyway, 'vcard 3 with PHOTO URL' seems to be a bug in Sabre/Vobject because `getValueType()` returns `BINARY`

Comment (georgehrke) [inline apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php]: 'vcard 4 with PHOTO' seems to be a bug in Sabre/Vobject as well, `getValueType()` returns `URI` although it should be `BINARY`

Comment (georgehrke) [inline apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php]: 'vcard 4 with PHOTO URL' is fixed now

Comment (DeepDiver1975) [inline apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php]: > How is http://example.org/photo.jpg supposed to return '12345' in the first place?

it's not :see_no_evil:

Comment (DeepDiver1975) [inline apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php]: please file issues upstream - thx

Comment (georgehrke) [inline apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php]: done - https://github.com/fruux/sabre-vobject/issues/325

Comment (DeepDiver1975) [inline apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php]: > done - fruux/sabre-vobject#325

THX

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by jancborchardt** [comment]
Oooh this is awesome! :) Great work!

Will it be backported as well?

**Comment by DeepDiver1975** [comment]
@georgehrke please prepare backport pr - we want to make oc9 users happy as well :see_no_evil:

**Comment by georgehrke** [comment]
sure

**Comment by PVince81** [comment]
stable9: https://github.com/owncloud/core/issues/25219
