### PR TITLE
Webdav PUT small file lock must be shared during hooks

### LINKED ISSUE #16900: Cannot run versions hook, file is locked
### Steps
1. Enable experimental files locking
2. Using cadaver, PUT a small text file (generated from https://baconipsum.com)
3. PUT it again to overwrite it

### Expected result
No errors in log.
Version properly created.

### Actual result
```
{"reqId":"EVhVN+4pQUfs13GXLu4y","remoteAddr":"127.0.0.1","app":"hook","message":"error while running hook (OCA\\Files_Versions\\Hooks::write_hook): folder\/bacon.txt is locked","level":3,"time":"2015-06-12T11:19:41+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/folder\/bacon.txt"}
```
No version created.

@icewind1991 something wrong with locking and hooks.
Should we rewrite files_versions to use storages instead of of views ?

### PR DESCRIPTION
**Pull request by PVince81**
Fixed code path for Webdav PUT of small files to use shared locks during
hook execution, and exclusive during the file operation

This makes it possible for versions to be copied by accessing the file
in a post_write hook.

Fixes https://github.com/owncloud/core/issues/16900

Please review @icewind1991 @DeepDiver1975 @nickvergessen 
Note that I had to change the hook type from exclusive back to shared to run the post hooks.

Locking during post hooks will also be done for other code paths here: https://github.com/owncloud/core/issues/16829#issuecomment-111502029

I added a unit test. Ideally I'd have wanted to also check the locks during the file operation, but that would require extraordinary gymnastics, so I left it for now. Still, the current test would fail without the fix applied.

### CODE REVIEW

File: tests/lib/testcase.php [hunk 1]
```diff
@@ -242,4 +242,39 @@ protected function runCommands() {
...
+	 * Check if the given path is locked with a given type
+	 *
+	 * @param \OC\Files\View $view view
+	 * @param string $path path to check
+	 * @param int $type lock type
+	 *
+	 * @return boolean true if the file is locked with the
+	 * given type, false otherwise
+	 */
+	protected function isFileLocked($view, $path, $type) {
```
Comment (nickvergessen) [inline tests/lib/testcase.php]: why is this here in testcase.php instead of your test file?

**Comment by icewind1991** [comment]
:+1: looks good

File: tests/lib/testcase.php (hunk 1 above)
Comment (PVince81) [inline tests/lib/testcase.php]: because it could be useful in other places.

Insist and I'll move it away.

**Comment by DeepDiver1975** [comment]
:+1:

File: tests/lib/testcase.php (hunk 1 above)
Comment (nickvergessen) [inline tests/lib/testcase.php]: This should be a base class for unit tests, if you want to make a helper class do it in a new file ;)

Comment (nickvergessen) [inline tests/lib/testcase.php]: Also missing typehint for the view

Comment (PVince81) [inline tests/lib/testcase.php]: Ok, I'll move it to the test class.
