### PR TITLE
let the encryption storage wrapper always update the file cache

### LINKED ISSUE #17594: [8.1] Incorrect filesize uploading files via Webdav as recipient using encryption
### Steps to reproduce
1. Upload a file using webdav (e.g. FileSync on Android) - here a 1.4 MB file - using the mode "use temporary files"
2. The uploaded file will be encrypted, put into the ownCloud filesystem and the filesize within the oc_filecache-database is set to the size of the encrypted file (1.9 MB). The flag "encrypted" will be not set within oc_filecache
3. Using the web-interface the JPG-file can be displayed (1.4MB) and downloaded (1.4MB) but the ownCloud-Windows-Client aborts with errors and the file cannot be downloaded using a browser and the direct webdav-link (the browser tries to download 1.9MB and aborts after 1.4MB)

### Expected behaviour
The filesize should be published to the webdav-clients correctly. The decrypted filesize has to be stored within oc_filecache and the flag "encrypted" has to be set to 1.

### Actual behaviour
The stored filesize is the size of the encrypted file so that ownCloud-Windows-Client and webdav-clients cannot operate any more. Setting up the correct (decrypted) filesize within the database fixes the problem immediatly!

The problem is not there on some files if you are using the Webinterface, because clicking on a file will decrypt the file to the temporary folder immediatly so that the correct file size will be published to the browser.

The problem seems to occure, if the webdav-client creates a temporary file for upload-process and moves this file after the upload completes (like FileSync does in default settings). Maybe this upload-encrypt-move-process has a bug!?

### Server configuration
**Operating system**:
Ubuntu 14.04.2 LTS

**Web server:**
Apache (unknown version)

**Database:**
SQL 5.4

**PHP version:**
PHP 5.5

**ownCloud version:** (see ownCloud admin page)
8.1.0.8

**Updated from an older ownCloud or fresh install:**
from an older installation (8.0.2)

**List of activated apps:**
 activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - documents: 0.10.0
 - encryption: 1.0.0
 - files: 1.1.9
 - files_gpxviewer_extended: 1.4
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - galleryplus: 13
 - mail: 0.1.3
 - music: 0.3.6
 - tasks: 0.6.0
 - updater: 0.6
Disabled:
 - external
 - files_external
 - gallery
 - ocsms
 - provisioning_api
 - templateeditor
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'xxxx',
  'passwordsalt' => 'xxxx',
  'trusted_domains' => 
  array (
    0 => 'www.xxxx.de',
    1 => 'cloud.xxxx.de',
    2 => 'xxxx.de',
  ),
  'datadirectory' => '/www/htdocs/xxxx/xxxx/cloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'xxxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxx',
  'dbpassword' => 'xxxx',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_from_address' => 'xxxx',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'xxxx.de',
  'forcessl' => true,
  'trashbin_retention_obligation' => 60,
  'trashbin_auto_expire' => true,
  'loglevel' => 2,
  'log_rotate_size' => false,
  'logtimezone' => 'Europe/Berlin',
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,
  'xframe_restriction' => false,
  'secret' => 'xxxx',
  'forceSSLforSubdomains' => true,
  'tempdirectory' => '/www/htdocs/xxxx/tmp',
  'enable_previews' => true,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
    4 => 'OC\\Preview\\Illustrator',
    5 => 'OC\\Preview\\Postscript',
    6 => 'OC\\Preview\\Photoshop',
    7 => 'OC\\Preview\\TIFF',
  ),
  'singleuser' => false,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
ownCloud Client 1.8.3
**Browser:**
Firefox 39

**Operating system:**
Windows 7 64-Bit

### PR DESCRIPTION
**Pull request by schiessle**
let the encryption storage wrapper always update the file cache, the cache can handle partial data correctly if the file doesn't already exists in the file cache.

If the file doesn't have a file cache entry the cache handles this partial data correctly. See discussion: https://github.com/owncloud/core/issues/17594#issuecomment-126652915

fix https://github.com/owncloud/core/issues/17594

### CODE REVIEW

**Comment by schiesbn** [comment]
cc @PVince81 this is the first one

I would suggest to backport this one in any case. cc @karlitschek

**Comment by PVince81** [comment]
:+1:

@DeepDiver1975 can you also review this ? (it's party code you wrote back then)

**Comment by PVince81** [comment]
@schiesbn can you prepare the backport PR in advance to save some time ?

**Comment by karlitschek** [comment]
:+1:  please backport

**Comment by PVince81** [comment]
@schiesbn 
```
Time: 36.06 minutes, Memory: 386.75Mb
10:31:01 
10:31:01 There were 4 failures:
10:31:01 
10:31:01 1) Test\Files\Storage\Wrapper\Encryption::testCopyEncryption with data set #0 ('source', 'target', true, false, false)
10:31:01 OC\Files\Cache\Cache::put('target', Array (...)) was not expected to be called more than once.
10:31:01 
10:31:01 /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/files/storage/wrapper/encryption.php:133
10:31:01 /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/tests/lib/files/storage/wrapper/encryption.php:292
10:31:01 
10:31:01 2) Test\Files\Storage\Wrapper\Encryption::testCopyEncryption with data set #1 ('source', 'target', true, true, false)
10:31:01 OC\Files\Cache\Cache::put('target', Array (...)) was not expected to be called more than once.
10:31:01 
10:31:01 /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/files/storage/wrapper/encryption.php:133
10:31:01 /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/tests/lib/files/storage/wrapper/encryption.php:292
10:31:01 
10:31:01 3) Test\Files\Storage\Wrapper\Encryption::testCopyEncryption with data set #2 ('source', '/subFolder/target', true, false, false)
10:31:01 OC\Files\Cache\Cache::put('/subFolder/target', Array (...)) was not expected to be called more than once.
10:31:01 
10:31:01 /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/files/storage/wrapper/encryption.php:133
10:31:01 /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/tests/lib/files/storage/wrapper/encryption.php:292
10:31:01 
10:31:01 4) Test\Files\Storage\Wrapper\Encryption::testCopyEncryption with data set #3 ('source', '/subFolder/target', true, true, true)
10:31:01 OC\Files\Cache\Cache::put('/subFolder/target', Array (...)) was not expected to be called more than once.
10:31:01 
10:31:01 /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/files/storage/wrapper/encryption.php:133
10:31:01 /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/tests/lib/files/storage/wrapper/encryption.php:292
```

File: lib/private/files/storage/wrapper/encryption.php [hunk 1]
```diff
@@ -127,12 +127,11 @@ public function filesize($path) {
 		$info = $this->getCache()->get($path);
 		if (isset($this->unencryptedSize[$fullPath])) {
 			$size = $this->unencryptedSize[$fullPath];
+			// update file cache
+			$info['encrypted'] = true;
+			$info['size'] = $size;
+			$this->getCache()->put($path, $info);
 
-			if (isset($info['fileid'])) {
```
Comment (DeepDiver1975) [inline lib/private/files/storage/wrapper/encryption.php]: hmmm .... I'd be happy if I did add a comment here why I insisted to have the if there ... don't remember ...

Comment (PVince81) [inline lib/private/files/storage/wrapper/encryption.php]: Last week I checked several git blame iterations but didn't find any clues.

Can we merge this then ?

**Comment by schiesbn** [comment]
@DeepDiver1975 @MorrisJobke please review it... We need this for 8.1.1

**Comment by MorrisJobke** [comment]
> We need this for 8.1.1

No way. I definitely not will review something that will packaged today and released tomorrow.

**Comment by MorrisJobke** [comment]
And I don't have proper insights into encryption stuff. @DeepDiver1975 Please review this. I don't feel good with this :(

**Comment by schiesbn** [comment]
@MorrisJobke This needs to go in, otherwise a lot of files uploaded to a shared folder will be broken. You have the choice. Deal with all the angry users or review this PR. This is also approved by @karlitschek

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by schiesbn** [comment]
@DeepDiver1975 Thanks for reviewing it!
