### PR TITLE
Fix issues where some user settings cannot be loaded when the user id…

### LINKED ISSUE #25684: Email password recovery: Case-sensitive username
### Steps to reproduce
1. Create user with upper/lowercase name, example "Destrid"
2. Logout
3. Try to get sent an email recovery by logging in with the wrong upper/lowercase combination of the username and any wrong password, example "destrid"
4. The system will not find an email corresponding to your username, unless you use the proper uppercase/lowercase username

### Expected behaviour
The server should fetch the user's email address and send the forgotten password email regardless of upper/lowercase username. It is not possible to create multiple usernames with the same name regardless of case (at least, not whenusing an external authentication method, which I have not tested).
It is also possible to login by using the wrong upper/lowercase on the username and the correct password

### Actual behaviour
[Screenshot](http://upload.destrid.com/2016-08-01/chrome2016-08-0123-54-26.png)
"Could not send the password reset email because there was no email address associated to that user. Please contact your administrator."

The email would be sent correctly if I had put the first "D" in uppercase (as it was registered on the server).

### Server configuration
**Operating system**: Debian 8 (jessie)

**Web server:** Apache 2.4.10

**Database:** Mysql 5.5.50-0

**PHP version:** 5.6.24-0

**ownCloud version:** 9.1.0

**Updated from an older ownCloud or fresh install:** Updated from 9.0

**Where did you install ownCloud from:** apt-get

**Signing status (ownCloud 9.0 and above):** 

```
No errors have been found.
```
**List of activated apps:**

```
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => 'ocnsonox5i8p',
  'passwordsalt' => '<This is a salty salt>',
  'secret' => 'This wouldn't be a secret if I told you what it was',
  'trusted_domains' => 
  array (
    0 => 'owncloud.destrid.com',
  ),
  'datadirectory' => '/var/www/owncloud.destrid.com/data',
  'overwrite.cli.url' => 'https://owncloud.destrid.com',
  'dbtype' => 'mysql',
  'version' => '9.1.0.15',
  'quota_include_external_storage' => true,
  'session_keepalive' => true,
  'session_lifetime' => 60 * 60 * 24,
  'remember_login_cookie_lifetime' => 60*60*24*15,
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '<Insert correct DB password here>',
  'logtimezone' => 'UTC',
  'installed' => true,
  'overwritewebroot' => '',
  'htaccess.RewriteBase' => '/',
  'check_for_working_htaccess' => true,
  'filesystem_check_changes' => 1,
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'theme' => '',
  'loglevel' => 0,
  'maintenance' => false,
  'mail_from_address' => 'no-reply',
  'mail_smtpmode' => 'sendmail',
  'mail_domain' => 'owncloud.destrid.com',
);
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:** Google Chrome 52.0.2743.82 m

**Operating system:** Windows 7 Ultimate Edition x64

#### Web server error log (These are the logs as they were while I was reproducing the bug a few times over the evening)
```
[Tue Aug 02 00:08:55.458438 2016] [core:info] [pid 21495] [client 92.140.211.94:52464] AH00128: File does not exist: /var/www/owncloud.destrid.com/favicon.ico, referer: https://owncloud.destrid.com/index.php/settings/integrity/failed
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"UHIqU8h2i8X5QsruUHGG","remoteAddr":"","app":"cron","message":"Run job with ID 11","level":0,"time":"2016-08-01T22:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"UHIqU8h2i8X5QsruUHGG","remoteAddr":"","app":"cron","message":"Finished job with ID 11","level":0,"time":"2016-08-01T22:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"UHIqU8h2i8X5QsruUHGG","remoteAddr":"","app":"cron","message":"Run job with ID 12","level":0,"time":"2016-08-01T22:15:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"UHIqU8h2i8X5QsruUHGG","remoteAddr":"","app":"no app in context","message":"Invalidating tokens older than 2016-07-31T22:15:04+00:00","level":1,"time":"2016-08-01T22:15:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"UHIqU8h2i8X5QsruUHGG","remoteAddr":"","app":"cron","message":"Finished job with ID 12","level":0,"time":"2016-08-01T22:15:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"UHIqU8h2i8X5QsruUHGG","remoteAddr":"","app":"cron","message":"Run job with ID 13","level":0,"time":"2016-08-01T22:15:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"UHIqU8h2i8X5QsruUHGG","remoteAddr":"","app":"cron","message":"Finished job with ID 13","level":0,"time":"2016-08-01T22:15:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"UHIqU8h2i8X5QsruUHGG","remoteAddr":"","app":"cron","message":"Run job with ID 16","level":0,"time":"2016-08-01T22:15:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"UHIqU8h2i8X5QsruUHGG","remoteAddr":"","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":0,"time":"2016-08-01T22:15:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"UHIqU8h2i8X5QsruUHGG","remoteAddr":"","app":"cron","message":"Finished job with ID 16","level":0,"time":"2016-08-01T22:15:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"UHIqU8h2i8X5QsruUHGG","remoteAddr":"","app":"cron","message":"Run job with ID 17","level":0,"time":"2016-08-01T22:15:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"UHIqU8h2i8X5QsruUHGG","remoteAddr":"","app":"cron","message":"Finished job with ID 17","level":0,"time":"2016-08-01T22:15:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"UHIqU8h2i8X5QsruUHGG","remoteAddr":"","app":"cron","message":"Run job with ID 2","level":0,"time":"2016-08-01T22:15:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"UHIqU8h2i8X5QsruUHGG","remoteAddr":"","app":"cron","message":"Finished job with ID 2","level":0,"time":"2016-08-01T22:15:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Run job with ID 3","level":0,"time":"2016-08-01T22:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Finished job with ID 3","level":0,"time":"2016-08-01T22:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Run job with ID 4","level":0,"time":"2016-08-01T22:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"files","message":"Exception: {\"Exception\":\"BadMethodCallException\",\"Message\":\"Not in batch\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php(143): OC\\\\Files\\\\Cache\\\\Propagator->commitBatch()\\n#1 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(87): OC\\\\Files\\\\Utils\\\\Scanner->backgroundScan('')\\n#2 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(111): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->runScanner(Object(OC\\\\User\\\\User))\\n#3 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(52): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->run(NULL)\\n#4 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#5 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/cron.php(122): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#6 {main}\",\"File\":\"\\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/Files\\\/Cache\\\/Propagator.php\",\"Line\":145}","level":3,"time":"2016-08-01T22:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Finished job with ID 4","level":0,"time":"2016-08-01T22:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Run job with ID 5","level":0,"time":"2016-08-01T22:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Finished job with ID 5","level":0,"time":"2016-08-01T22:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Run job with ID 6","level":0,"time":"2016-08-01T22:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Finished job with ID 6","level":0,"time":"2016-08-01T22:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Run job with ID 9","level":0,"time":"2016-08-01T22:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Finished job with ID 9","level":0,"time":"2016-08-01T22:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Run job with ID 10","level":0,"time":"2016-08-01T22:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Finished job with ID 10","level":0,"time":"2016-08-01T22:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Run job with ID 11","level":0,"time":"2016-08-01T22:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Finished job with ID 11","level":0,"time":"2016-08-01T22:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Run job with ID 12","level":0,"time":"2016-08-01T22:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"no app in context","message":"Invalidating tokens older than 2016-07-31T22:30:03+00:00","level":1,"time":"2016-08-01T22:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Finished job with ID 12","level":0,"time":"2016-08-01T22:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Run job with ID 1","level":0,"time":"2016-08-01T22:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Finished job with ID 1","level":0,"time":"2016-08-01T22:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Run job with ID 2","level":0,"time":"2016-08-01T22:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Finished job with ID 2","level":0,"time":"2016-08-01T22:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Run job with ID 13","level":0,"time":"2016-08-01T22:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Finished job with ID 13","level":0,"time":"2016-08-01T22:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Run job with ID 16","level":0,"time":"2016-08-01T22:30:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Finished job with ID 16","level":0,"time":"2016-08-01T22:30:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Run job with ID 17","level":0,"time":"2016-08-01T22:30:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Hp+h1Qn3VjWpHWrWavxq","remoteAddr":"","app":"cron","message":"Finished job with ID 17","level":0,"time":"2016-08-01T22:30:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"Nb2tssteGzVYSbkFod38","remoteAddr":"92.140.211.94","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name Documents\\\/Factures\\\/Kimsufi\\\/2016-08-01 Kimsufi.pdf could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(79): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Documents\\\/Factu...', 0)\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(251): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response), false)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpHead(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:HEAD', Array)\\n#8 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/remote.php(164): require_once('\\\/home\\\/www-data\\\/...')\\n#11 {main}\",\"File\":\"\\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":170,\"User\":\"Destrid\"}","level":0,"time":"2016-08-01T22:38:05+00:00","method":"HEAD","url":"\/remote.php\/webdav\/Documents\/Factures\/Kimsufi\/2016-08-01%20Kimsufi.pdf","user":"Destrid"}
{"reqId":"wnkfqwfZ2XxLe6zyzvoD","remoteAddr":"92.140.211.94","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name Documents\\\/Bulletins de paie\\\/2016-07-29 Feuille de temps Expectra.pdf could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(79): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Documents\\\/Bulle...', 0)\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(251): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response), false)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpHead(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:HEAD', Array)\\n#8 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/remote.php(164): require_once('\\\/home\\\/www-data\\\/...')\\n#11 {main}\",\"File\":\"\\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":170,\"User\":\"Destrid\"}","level":0,"time":"2016-08-01T22:39:55+00:00","method":"HEAD","url":"\/remote.php\/webdav\/Documents\/Bulletins%20de%20paie\/2016-07-29%20Feuille%20de%20temps%20Expectra.pdf","user":"Destrid"}
{"reqId":"ITQepfkOdgyConBcOzL6","remoteAddr":"92.140.211.94","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name Documents\\\/Bulletins de paie\\\/2016-07-29 Expectra Relev\\u00e9 d'heures.pdf could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(79): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Documents\\\/Bulle...', 0)\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(251): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response), false)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpHead(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:HEAD', Array)\\n#8 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/remote.php(164): require_once('\\\/home\\\/www-data\\\/...')\\n#11 {main}\",\"File\":\"\\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":170,\"User\":\"Destrid\"}","level":0,"time":"2016-08-01T22:40:58+00:00","method":"HEAD","url":"\/remote.php\/webdav\/Documents\/Bulletins%20de%20paie\/2016-07-29%20Expectra%20Relev%C3%A9%20d'heures.pdf","user":"Destrid"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Run job with ID 4","level":0,"time":"2016-08-01T22:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"files","message":"Exception: {\"Exception\":\"BadMethodCallException\",\"Message\":\"Not in batch\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php(143): OC\\\\Files\\\\Cache\\\\Propagator->commitBatch()\\n#1 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(87): OC\\\\Files\\\\Utils\\\\Scanner->backgroundScan('')\\n#2 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(111): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->runScanner(Object(OC\\\\User\\\\User))\\n#3 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(52): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->run(NULL)\\n#4 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#5 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/cron.php(122): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#6 {main}\",\"File\":\"\\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/Files\\\/Cache\\\/Propagator.php\",\"Line\":145}","level":3,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Finished job with ID 4","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Run job with ID 5","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"DeleteOrphanedItems","message":"0 orphaned system tag relations deleted","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"DeleteOrphanedItems","message":"0 orphaned user tag relations deleted","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"DeleteOrphanedItems","message":"0 orphaned comments deleted","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"DeleteOrphanedItems","message":"0 orphaned comment read marks deleted","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Finished job with ID 5","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Run job with ID 1","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Finished job with ID 1","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Run job with ID 2","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Finished job with ID 2","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Run job with ID 6","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Finished job with ID 6","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Run job with ID 9","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Finished job with ID 9","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Run job with ID 10","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Finished job with ID 10","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Run job with ID 11","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Finished job with ID 11","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Run job with ID 12","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"no app in context","message":"Invalidating tokens older than 2016-07-31T22:45:05+00:00","level":1,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Finished job with ID 12","level":0,"time":"2016-08-01T22:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Run job with ID 13","level":0,"time":"2016-08-01T22:45:06+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Finished job with ID 13","level":0,"time":"2016-08-01T22:45:06+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Run job with ID 3","level":0,"time":"2016-08-01T22:45:06+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Finished job with ID 3","level":0,"time":"2016-08-01T22:45:06+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Run job with ID 16","level":0,"time":"2016-08-01T22:45:06+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":0,"time":"2016-08-01T22:45:06+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Finished job with ID 16","level":0,"time":"2016-08-01T22:45:06+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Run job with ID 17","level":0,"time":"2016-08-01T22:45:06+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Finished job with ID 17","level":0,"time":"2016-08-01T22:45:06+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Run job with ID 19","level":0,"time":"2016-08-01T22:45:06+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oin02jt2aed5v1D7QHj1","remoteAddr":"","app":"cron","message":"Finished job with ID 19","level":0,"time":"2016-08-01T22:45:06+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Run job with ID 1","level":0,"time":"2016-08-01T23:00:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Finished job with ID 1","level":0,"time":"2016-08-01T23:00:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Run job with ID 2","level":0,"time":"2016-08-01T23:00:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Finished job with ID 2","level":0,"time":"2016-08-01T23:00:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Run job with ID 5","level":0,"time":"2016-08-01T23:00:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Finished job with ID 5","level":0,"time":"2016-08-01T23:00:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Run job with ID 6","level":0,"time":"2016-08-01T23:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Finished job with ID 6","level":0,"time":"2016-08-01T23:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Run job with ID 9","level":0,"time":"2016-08-01T23:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Finished job with ID 9","level":0,"time":"2016-08-01T23:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Run job with ID 10","level":0,"time":"2016-08-01T23:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Finished job with ID 10","level":0,"time":"2016-08-01T23:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Run job with ID 11","level":0,"time":"2016-08-01T23:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Finished job with ID 11","level":0,"time":"2016-08-01T23:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Run job with ID 12","level":0,"time":"2016-08-01T23:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"no app in context","message":"Invalidating tokens older than 2016-07-31T23:00:03+00:00","level":1,"time":"2016-08-01T23:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Finished job with ID 12","level":0,"time":"2016-08-01T23:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Run job with ID 13","level":0,"time":"2016-08-01T23:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Finished job with ID 13","level":0,"time":"2016-08-01T23:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Run job with ID 3","level":0,"time":"2016-08-01T23:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Finished job with ID 3","level":0,"time":"2016-08-01T23:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Run job with ID 4","level":0,"time":"2016-08-01T23:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"files","message":"Exception: {\"Exception\":\"BadMethodCallException\",\"Message\":\"Not in batch\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php(143): OC\\\\Files\\\\Cache\\\\Propagator->commitBatch()\\n#1 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(87): OC\\\\Files\\\\Utils\\\\Scanner->backgroundScan('')\\n#2 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(111): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->runScanner(Object(OC\\\\User\\\\User))\\n#3 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(52): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->run(NULL)\\n#4 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#5 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/cron.php(122): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#6 {main}\",\"File\":\"\\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/Files\\\/Cache\\\/Propagator.php\",\"Line\":145}","level":3,"time":"2016-08-01T23:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Finished job with ID 4","level":0,"time":"2016-08-01T23:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Run job with ID 16","level":0,"time":"2016-08-01T23:00:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Finished job with ID 16","level":0,"time":"2016-08-01T23:00:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Run job with ID 17","level":0,"time":"2016-08-01T23:00:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gVzJEOCaTF5Qz09MBRI9","remoteAddr":"","app":"cron","message":"Finished job with ID 17","level":0,"time":"2016-08-01T23:00:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Run job with ID 2","level":0,"time":"2016-08-01T23:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Finished job with ID 2","level":0,"time":"2016-08-01T23:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Run job with ID 5","level":0,"time":"2016-08-01T23:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Finished job with ID 5","level":0,"time":"2016-08-01T23:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Run job with ID 6","level":0,"time":"2016-08-01T23:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Finished job with ID 6","level":0,"time":"2016-08-01T23:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Run job with ID 3","level":0,"time":"2016-08-01T23:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Finished job with ID 3","level":0,"time":"2016-08-01T23:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Run job with ID 4","level":0,"time":"2016-08-01T23:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"files","message":"Exception: {\"Exception\":\"BadMethodCallException\",\"Message\":\"Not in batch\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php(143): OC\\\\Files\\\\Cache\\\\Propagator->commitBatch()\\n#1 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(87): OC\\\\Files\\\\Utils\\\\Scanner->backgroundScan('')\\n#2 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(111): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->runScanner(Object(OC\\\\User\\\\User))\\n#3 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(52): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->run(NULL)\\n#4 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#5 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/cron.php(122): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#6 {main}\",\"File\":\"\\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/Files\\\/Cache\\\/Propagator.php\",\"Line\":145}","level":3,"time":"2016-08-01T23:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Finished job with ID 4","level":0,"time":"2016-08-01T23:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Run job with ID 9","level":0,"time":"2016-08-01T23:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Finished job with ID 9","level":0,"time":"2016-08-01T23:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Run job with ID 10","level":0,"time":"2016-08-01T23:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Finished job with ID 10","level":0,"time":"2016-08-01T23:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Run job with ID 11","level":0,"time":"2016-08-01T23:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Finished job with ID 11","level":0,"time":"2016-08-01T23:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Run job with ID 12","level":0,"time":"2016-08-01T23:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"no app in context","message":"Invalidating tokens older than 2016-07-31T23:15:03+00:00","level":1,"time":"2016-08-01T23:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Finished job with ID 12","level":0,"time":"2016-08-01T23:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Run job with ID 13","level":0,"time":"2016-08-01T23:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Finished job with ID 13","level":0,"time":"2016-08-01T23:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Run job with ID 1","level":0,"time":"2016-08-01T23:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Finished job with ID 1","level":0,"time":"2016-08-01T23:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Run job with ID 16","level":0,"time":"2016-08-01T23:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":0,"time":"2016-08-01T23:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Finished job with ID 16","level":0,"time":"2016-08-01T23:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Run job with ID 17","level":0,"time":"2016-08-01T23:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"sX8MPA1PHfRCvib7coMV","remoteAddr":"","app":"cron","message":"Finished job with ID 17","level":0,"time":"2016-08-01T23:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Run job with ID 3","level":0,"time":"2016-08-01T23:30:01+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Finished job with ID 3","level":0,"time":"2016-08-01T23:30:01+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Run job with ID 4","level":0,"time":"2016-08-01T23:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"files","message":"Exception: {\"Exception\":\"BadMethodCallException\",\"Message\":\"Not in batch\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php(143): OC\\\\Files\\\\Cache\\\\Propagator->commitBatch()\\n#1 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(87): OC\\\\Files\\\\Utils\\\\Scanner->backgroundScan('')\\n#2 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(111): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->runScanner(Object(OC\\\\User\\\\User))\\n#3 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(52): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->run(NULL)\\n#4 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#5 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/cron.php(122): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#6 {main}\",\"File\":\"\\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/Files\\\/Cache\\\/Propagator.php\",\"Line\":145}","level":3,"time":"2016-08-01T23:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Finished job with ID 4","level":0,"time":"2016-08-01T23:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Run job with ID 5","level":0,"time":"2016-08-01T23:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Finished job with ID 5","level":0,"time":"2016-08-01T23:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Run job with ID 6","level":0,"time":"2016-08-01T23:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Finished job with ID 6","level":0,"time":"2016-08-01T23:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Run job with ID 1","level":0,"time":"2016-08-01T23:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Finished job with ID 1","level":0,"time":"2016-08-01T23:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Run job with ID 9","level":0,"time":"2016-08-01T23:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Finished job with ID 9","level":0,"time":"2016-08-01T23:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Run job with ID 10","level":0,"time":"2016-08-01T23:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Finished job with ID 10","level":0,"time":"2016-08-01T23:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Run job with ID 11","level":0,"time":"2016-08-01T23:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Finished job with ID 11","level":0,"time":"2016-08-01T23:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Run job with ID 12","level":0,"time":"2016-08-01T23:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"no app in context","message":"Invalidating tokens older than 2016-07-31T23:30:03+00:00","level":1,"time":"2016-08-01T23:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Finished job with ID 12","level":0,"time":"2016-08-01T23:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Run job with ID 13","level":0,"time":"2016-08-01T23:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Finished job with ID 13","level":0,"time":"2016-08-01T23:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Run job with ID 16","level":0,"time":"2016-08-01T23:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Finished job with ID 16","level":0,"time":"2016-08-01T23:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Run job with ID 17","level":0,"time":"2016-08-01T23:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Finished job with ID 17","level":0,"time":"2016-08-01T23:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Run job with ID 2","level":0,"time":"2016-08-01T23:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"oCfiiFHnObeTl3KkUDuS","remoteAddr":"","app":"cron","message":"Finished job with ID 2","level":0,"time":"2016-08-01T23:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Run job with ID 4","level":0,"time":"2016-08-01T23:45:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"files","message":"Exception: {\"Exception\":\"BadMethodCallException\",\"Message\":\"Not in batch\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php(143): OC\\\\Files\\\\Cache\\\\Propagator->commitBatch()\\n#1 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(87): OC\\\\Files\\\\Utils\\\\Scanner->backgroundScan('')\\n#2 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(111): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->runScanner(Object(OC\\\\User\\\\User))\\n#3 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(52): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->run(NULL)\\n#4 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#5 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/cron.php(122): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#6 {main}\",\"File\":\"\\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/Files\\\/Cache\\\/Propagator.php\",\"Line\":145}","level":3,"time":"2016-08-01T23:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Finished job with ID 4","level":0,"time":"2016-08-01T23:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Run job with ID 1","level":0,"time":"2016-08-01T23:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Finished job with ID 1","level":0,"time":"2016-08-01T23:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Run job with ID 5","level":0,"time":"2016-08-01T23:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Finished job with ID 5","level":0,"time":"2016-08-01T23:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Run job with ID 6","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Finished job with ID 6","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Run job with ID 9","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Finished job with ID 9","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Run job with ID 10","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Finished job with ID 10","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Run job with ID 11","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Finished job with ID 11","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Run job with ID 12","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"no app in context","message":"Invalidating tokens older than 2016-07-31T23:45:04+00:00","level":1,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Finished job with ID 12","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Run job with ID 2","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Finished job with ID 2","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Run job with ID 3","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Finished job with ID 3","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Run job with ID 13","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Finished job with ID 13","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Run job with ID 16","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Finished job with ID 16","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Run job with ID 17","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"6z3iXzO2MoqPkMPEx2Z9","remoteAddr":"","app":"cron","message":"Finished job with ID 17","level":0,"time":"2016-08-01T23:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Run job with ID 1","level":0,"time":"2016-08-02T00:00:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Finished job with ID 1","level":0,"time":"2016-08-02T00:00:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Run job with ID 5","level":0,"time":"2016-08-02T00:00:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"DeleteOrphanedItems","message":"0 orphaned system tag relations deleted","level":0,"time":"2016-08-02T00:00:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"DeleteOrphanedItems","message":"0 orphaned user tag relations deleted","level":0,"time":"2016-08-02T00:00:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"DeleteOrphanedItems","message":"0 orphaned comments deleted","level":0,"time":"2016-08-02T00:00:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"DeleteOrphanedItems","message":"0 orphaned comment read marks deleted","level":0,"time":"2016-08-02T00:00:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Finished job with ID 5","level":0,"time":"2016-08-02T00:00:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Run job with ID 2","level":0,"time":"2016-08-02T00:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Finished job with ID 2","level":0,"time":"2016-08-02T00:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Run job with ID 3","level":0,"time":"2016-08-02T00:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Finished job with ID 3","level":0,"time":"2016-08-02T00:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Run job with ID 4","level":0,"time":"2016-08-02T00:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"files","message":"Exception: {\"Exception\":\"BadMethodCallException\",\"Message\":\"Not in batch\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php(143): OC\\\\Files\\\\Cache\\\\Propagator->commitBatch()\\n#1 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(87): OC\\\\Files\\\\Utils\\\\Scanner->backgroundScan('')\\n#2 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(111): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->runScanner(Object(OC\\\\User\\\\User))\\n#3 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(52): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->run(NULL)\\n#4 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#5 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/cron.php(122): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#6 {main}\",\"File\":\"\\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/Files\\\/Cache\\\/Propagator.php\",\"Line\":145}","level":3,"time":"2016-08-02T00:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Finished job with ID 4","level":0,"time":"2016-08-02T00:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Run job with ID 6","level":0,"time":"2016-08-02T00:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Finished job with ID 6","level":0,"time":"2016-08-02T00:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Run job with ID 9","level":0,"time":"2016-08-02T00:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Finished job with ID 9","level":0,"time":"2016-08-02T00:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Run job with ID 10","level":0,"time":"2016-08-02T00:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Finished job with ID 10","level":0,"time":"2016-08-02T00:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Run job with ID 11","level":0,"time":"2016-08-02T00:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Finished job with ID 11","level":0,"time":"2016-08-02T00:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Run job with ID 12","level":0,"time":"2016-08-02T00:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"no app in context","message":"Invalidating tokens older than 2016-08-01T00:00:03+00:00","level":1,"time":"2016-08-02T00:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Finished job with ID 12","level":0,"time":"2016-08-02T00:00:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Run job with ID 13","level":0,"time":"2016-08-02T00:00:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Finished job with ID 13","level":0,"time":"2016-08-02T00:00:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Run job with ID 16","level":0,"time":"2016-08-02T00:00:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Finished job with ID 16","level":0,"time":"2016-08-02T00:00:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Run job with ID 17","level":0,"time":"2016-08-02T00:00:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"gs80AWUTBJfMt\/DqwuPt","remoteAddr":"","app":"cron","message":"Finished job with ID 17","level":0,"time":"2016-08-02T00:00:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Run job with ID 5","level":0,"time":"2016-08-02T00:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Finished job with ID 5","level":0,"time":"2016-08-02T00:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Run job with ID 2","level":0,"time":"2016-08-02T00:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Finished job with ID 2","level":0,"time":"2016-08-02T00:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Run job with ID 3","level":0,"time":"2016-08-02T00:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Finished job with ID 3","level":0,"time":"2016-08-02T00:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Run job with ID 4","level":0,"time":"2016-08-02T00:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"files","message":"Exception: {\"Exception\":\"BadMethodCallException\",\"Message\":\"Not in batch\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php(143): OC\\\\Files\\\\Cache\\\\Propagator->commitBatch()\\n#1 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(87): OC\\\\Files\\\\Utils\\\\Scanner->backgroundScan('')\\n#2 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(111): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->runScanner(Object(OC\\\\User\\\\User))\\n#3 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(52): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->run(NULL)\\n#4 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#5 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/cron.php(122): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#6 {main}\",\"File\":\"\\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/Files\\\/Cache\\\/Propagator.php\",\"Line\":145}","level":3,"time":"2016-08-02T00:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Finished job with ID 4","level":0,"time":"2016-08-02T00:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Run job with ID 6","level":0,"time":"2016-08-02T00:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Finished job with ID 6","level":0,"time":"2016-08-02T00:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Run job with ID 9","level":0,"time":"2016-08-02T00:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Finished job with ID 9","level":0,"time":"2016-08-02T00:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Run job with ID 10","level":0,"time":"2016-08-02T00:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Finished job with ID 10","level":0,"time":"2016-08-02T00:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Run job with ID 11","level":0,"time":"2016-08-02T00:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Finished job with ID 11","level":0,"time":"2016-08-02T00:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Run job with ID 12","level":0,"time":"2016-08-02T00:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"no app in context","message":"Invalidating tokens older than 2016-08-01T00:15:03+00:00","level":1,"time":"2016-08-02T00:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Finished job with ID 12","level":0,"time":"2016-08-02T00:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Run job with ID 13","level":0,"time":"2016-08-02T00:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Finished job with ID 13","level":0,"time":"2016-08-02T00:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Run job with ID 1","level":0,"time":"2016-08-02T00:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Finished job with ID 1","level":0,"time":"2016-08-02T00:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Run job with ID 16","level":0,"time":"2016-08-02T00:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":0,"time":"2016-08-02T00:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Finished job with ID 16","level":0,"time":"2016-08-02T00:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Run job with ID 17","level":0,"time":"2016-08-02T00:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"NErgEvflj17hm2SDQ0ks","remoteAddr":"","app":"cron","message":"Finished job with ID 17","level":0,"time":"2016-08-02T00:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Run job with ID 3","level":0,"time":"2016-08-02T00:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Finished job with ID 3","level":0,"time":"2016-08-02T00:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Run job with ID 4","level":0,"time":"2016-08-02T00:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"files","message":"Exception: {\"Exception\":\"BadMethodCallException\",\"Message\":\"Not in batch\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php(143): OC\\\\Files\\\\Cache\\\\Propagator->commitBatch()\\n#1 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(87): OC\\\\Files\\\\Utils\\\\Scanner->backgroundScan('')\\n#2 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(111): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->runScanner(Object(OC\\\\User\\\\User))\\n#3 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(52): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->run(NULL)\\n#4 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#5 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/cron.php(122): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#6 {main}\",\"File\":\"\\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/Files\\\/Cache\\\/Propagator.php\",\"Line\":145}","level":3,"time":"2016-08-02T00:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Finished job with ID 4","level":0,"time":"2016-08-02T00:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Run job with ID 5","level":0,"time":"2016-08-02T00:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Finished job with ID 5","level":0,"time":"2016-08-02T00:30:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Run job with ID 6","level":0,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Finished job with ID 6","level":0,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Run job with ID 9","level":0,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Finished job with ID 9","level":0,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Run job with ID 1","level":0,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Finished job with ID 1","level":0,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Run job with ID 2","level":0,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Finished job with ID 2","level":0,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Run job with ID 10","level":0,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Finished job with ID 10","level":0,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Run job with ID 11","level":0,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Finished job with ID 11","level":0,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Run job with ID 12","level":0,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"no app in context","message":"Invalidating tokens older than 2016-08-01T00:30:03+00:00","level":1,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Finished job with ID 12","level":0,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Run job with ID 13","level":0,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Finished job with ID 13","level":0,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Run job with ID 16","level":0,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Finished job with ID 16","level":0,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Run job with ID 17","level":0,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IQjUtiyia4TLARrsIopV","remoteAddr":"","app":"cron","message":"Finished job with ID 17","level":0,"time":"2016-08-02T00:30:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Run job with ID 4","level":0,"time":"2016-08-02T00:45:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"files","message":"Exception: {\"Exception\":\"BadMethodCallException\",\"Message\":\"Not in batch\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php(143): OC\\\\Files\\\\Cache\\\\Propagator->commitBatch()\\n#1 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(87): OC\\\\Files\\\\Utils\\\\Scanner->backgroundScan('')\\n#2 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(111): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->runScanner(Object(OC\\\\User\\\\User))\\n#3 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(52): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->run(NULL)\\n#4 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#5 \\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/cron.php(122): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#6 {main}\",\"File\":\"\\\/home\\\/www-data\\\/www\\\/owncloud.destrid.com\\\/lib\\\/private\\\/Files\\\/Cache\\\/Propagator.php\",\"Line\":145}","level":3,"time":"2016-08-02T00:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Finished job with ID 4","level":0,"time":"2016-08-02T00:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Run job with ID 5","level":0,"time":"2016-08-02T00:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Finished job with ID 5","level":0,"time":"2016-08-02T00:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Run job with ID 1","level":0,"time":"2016-08-02T00:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Finished job with ID 1","level":0,"time":"2016-08-02T00:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Run job with ID 2","level":0,"time":"2016-08-02T00:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Finished job with ID 2","level":0,"time":"2016-08-02T00:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Run job with ID 3","level":0,"time":"2016-08-02T00:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Finished job with ID 3","level":0,"time":"2016-08-02T00:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Run job with ID 6","level":0,"time":"2016-08-02T00:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Finished job with ID 6","level":0,"time":"2016-08-02T00:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Run job with ID 9","level":0,"time":"2016-08-02T00:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Finished job with ID 9","level":0,"time":"2016-08-02T00:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Run job with ID 10","level":0,"time":"2016-08-02T00:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Finished job with ID 10","level":0,"time":"2016-08-02T00:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Run job with ID 11","level":0,"time":"2016-08-02T00:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Finished job with ID 11","level":0,"time":"2016-08-02T00:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Run job with ID 12","level":0,"time":"2016-08-02T00:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"no app in context","message":"Invalidating tokens older than 2016-08-01T00:45:04+00:00","level":1,"time":"2016-08-02T00:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Finished job with ID 12","level":0,"time":"2016-08-02T00:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Run job with ID 13","level":0,"time":"2016-08-02T00:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Finished job with ID 13","level":0,"time":"2016-08-02T00:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Run job with ID 16","level":0,"time":"2016-08-02T00:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":0,"time":"2016-08-02T00:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Finished job with ID 16","level":0,"time":"2016-08-02T00:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Run job with ID 17","level":0,"time":"2016-08-02T00:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"ITWdRzlX\/o\/ofTmnhvVM","remoteAddr":"","app":"cron","message":"Finished job with ID 17","level":0,"time":"2016-08-02T00:45:04+00:00","method":"--","url":"--","user":"--"}
```

#### Browser log (console)
```
JQMIGRATE: Migrate is installed, version 1.4.0 https://owncloud.destrid.com/core/vendor/jquery-migrate/jquery-migrate.min.js?v=452ab8ad29475b8c4779cac421e41798
Javascript console: Failted to parse SourceMap: https://owncloud.destrid.com/core/vendor/jquery/dist/jquery.min.map
```

#### Browser log (network)

[Network log from Google Chrome's Developper tools](http://upload.destrid.com/2016-08-02/ownclouddestridcom.zip)

### PR DESCRIPTION
**Pull request by DeepDiver1975**
… differs in case sensitivity - fixes #25684

### CODE REVIEW

File: lib/private/User/Manager.php [hunk 1]
```diff
@@ -156,6 +156,11 @@ protected function getUserObject($uid, $backend, $cacheUser = true) {
 			return $this->cachedUsers[$uid];
 		}
 
+		$uid = $backend->loginName2UserName($uid);
+		if (isset($this->cachedUsers[$uid])) {
```
Comment (VicDeo) [inline lib/private/User/Manager.php]: @DeepDiver1975 what's the reason behind searching the cache twice?

Comment (DeepDiver1975) [inline lib/private/User/Manager.php]: Second time is done because of uid was remapped in the loginname2username call.

Lets say the user name is VicDeo but you Login with vicdeo: first time uid is vicdeo - second time uid is VicDeo

Comment (DeepDiver1975) [inline lib/private/User/Manager.php]: should we do a case insensitive search in the cache - it that what you are proposing.

**Comment by PVince81** [comment]
@VicDeo please rereview, comments were addressed I think

**Comment by VicDeo** [comment]
:+1: Works

**Comment by DeepDiver1975** [comment]
@PVince81 shall we backport this - this is biting our user base since ever ....

**Comment by PVince81** [comment]
@DeepDiver1975 I'd say backport at least to 9.1.1.
Not sure about previous versions.
