### PR TITLE
Fix dropbox storage to not store the whole file in memory

### LINKED ISSUE #4040: [External storage - Dropbox] Allowed memory size  exhausted
I don´t know why I get this messages but external storage is working really bad for me. Should I allow a certain OAuth adress in the app i created in Dropbox, or what seems to be the error?

```
Fatal	 PHP	 Allowed memory size of 536870912 bytes exhausted (tried to allocate 408230542 bytes) at /var/www/owncloud/3rdparty/Dropbox/OAuth/Curl.php#102	 12.07.2013 13:29:22
Fatal	 PHP	 Allowed memory size of 536870912 bytes exhausted (tried to allocate 408230542 bytes) at /var/www/owncloud/3rdparty/Dropbox/OAuth/Curl.php#102	 10.07.2013 10:45:28
Fatal	 PHP	 Call to a member function t() on a non-object at /var/www/owncloud/apps/files_mv/ajax/autocompletedir.php#48	 09.07.2013 23:24:33
Fatal	PHP	Call to a member function t() on a non-object at /var/www/owncloud/apps/files_mv/ajax/autocompletedir.php#48	09.07.2013 23:24
Fatal	PHP	Call to a member function t() on a non-object at /var/www/owncloud/apps/files_mv/ajax/autocompletedir.php#48	09.07.2013 23:24
```

I can also add that I have 22 GB on my Dropbox as we speak, and I´m not able to download the content from either WebDAV or OC web interferance. In OC web interferance I get "server error message". In WebDAV it loads in like 10 kB/s, thou I have a 100 MBit/s internet.

OS: Windows 7 Ultimate
Server: Ubuntu Server 12.04 LTS
OC: 5.0.8
WebDAV client: Netdrive

### PR DESCRIPTION
**Pull request by PVince81**
Since the library can only store the full response in memory on
download, we use an alternate client lib and set the correct headers to
be able to stream the content to a temp file.

Note: I had to patch the library and also note that the library is unmaintained and that we should really find some time to update to a better library... https://github.com/owncloud/core/issues/13841

Similar approach like for GDrive.

Fixes https://github.com/owncloud/core/issues/4040

Please review @LukasReschke @icewind1991 @Xenopathic

### CODE REVIEW

**Comment by enoch85** [comment]
Will this be backported?

File: apps/files_external/lib/dropbox.php [hunk 1]
```diff
@@ -248,10 +249,31 @@ public function fopen($path, $mode) {
...
-					$data = $this->dropbox->getFile($path);
-					file_put_contents($tmpFile, $data);
+					// slashes need to stay
+					$encodedPath = str_replace('%2F', '/', rawurlencode(trim($path, '/')));
+					$downloadUrl = 'https://api-content.dropbox.com/1/files/auto/' . $encodedPath;
+					$headers = $this->oauth->getOAuthHeader($downloadUrl, [], 'GET');
+
+					$client = \OC::$server->getHTTPClientService()->newClient();
+					try {
+						$tmpFile = \OC::$server->getTempManager()->getTemporaryFile($ext);
```
Comment (LukasReschke) [inline apps/files_external/lib/dropbox.php]: I don't see $ext defined in fopen

Comment (LukasReschke) [inline apps/files_external/lib/dropbox.php]: So maybe just `getTemporaryFile`?

**Comment by PVince81** [comment]
Possibly 9.0.1

File: apps/files_external/lib/dropbox.php (hunk 1 above)
Comment (PVince81) [inline apps/files_external/lib/dropbox.php]: Ah, copy-paste fail...

**Comment by PVince81** [comment]
Looks like that breaks unit tests.
At least when running them locally, they look much worse than https://github.com/owncloud/core/issues/19868

**Comment by PVince81** [comment]
Failing tests related to encoding, let's find out how much more we need to encode.

**Comment by PVince81** [comment]
I removed the `$ext` in the wrong file :disappointed:

**Comment by PVince81** [comment]
Ok, now it's giving the same old failures we already had in https://github.com/owncloud/core/issues/19868

File: apps/files_external/3rdparty/Dropbox/OAuth/Curl.php [hunk 2]
```diff
@@ -196,7 +196,7 @@ private function getOAuthBaseParams() {
      * @return array Array for request's headers section like
      * array('Authorization' => 'OAuth ...');
      */
-    private function getOAuthHeader($uri, $params, $method = 'GET', $oAuthParams = null) {
+    public function getOAuthHeader($uri, $params, $method = 'GET', $oAuthParams = null) {
```
Comment (icewind1991) [inline apps/files_external/3rdparty/Dropbox/OAuth/Curl.php]: can we list changes made to 3rdparty things somewhere?

File: apps/files_external/lib/dropbox.php [hunk 3]
```diff
@@ -248,10 +249,31 @@ public function fopen($path, $mode) {
...
-					file_put_contents($tmpFile, $data);
+					// slashes need to stay
+					$encodedPath = str_replace('%2F', '/', rawurlencode(trim($path, '/')));
+					$downloadUrl = 'https://api-content.dropbox.com/1/files/auto/' . $encodedPath;
+					$headers = $this->oauth->getOAuthHeader($downloadUrl, [], 'GET');
+
+					$client = \OC::$server->getHTTPClientService()->newClient();
+					try {
+						$tmpFile = \OC::$server->getTempManager()->getTemporaryFile();
+						$client->get($downloadUrl, [
```
Comment (icewind1991) [inline apps/files_external/lib/dropbox.php]: Why not set the http client to stream instead?

(see the dav fopen implementation for an example)

File: apps/files_external/3rdparty/Dropbox/OAuth/Curl.php (hunk 2 above)
Comment (PVince81) [inline apps/files_external/3rdparty/Dropbox/OAuth/Curl.php]: in general I'd agree, but @LukasReschke told me we already super-patched this lib before due to security issues.
Maybe I can try and track down his changes and add them to "patch.txt" too

Comment (LukasReschke) [inline apps/files_external/3rdparty/Dropbox/OAuth/Curl.php]: > in general I'd agree, but @LukasReschke told me we already super-patched this lib before due to security issues.

… the library was patched before that already as well … it's a nightmare :see_no_evil: 

I'd just do :see_no_evil: here and hope that at some point we switch to the proper Dropbox SDK.

File: apps/files_external/lib/dropbox.php (hunk 3 above)
Comment (PVince81) [inline apps/files_external/lib/dropbox.php]: Because it breaks encryption, see https://github.com/owncloud/core/issues/22590

Basically, in stream mode fread($fh, 8192) isn't guaranteed to return 8k bytes... need to call it repeateadly. And encryption expects this to be guaranteed. See also https://github.com/owncloud/core/issues/22286#issuecomment-197271231 where it was discovered to happen with FTP too :cry:

Comment (icewind1991) [inline apps/files_external/lib/dropbox.php]: Might be worth investing in making a buffering streamwrapper to wrap streams from external storages in to ensure they all behave as expected.

Could be used to add things like seek support and ensure fread returns the requested number of bytes

Comment (PVince81) [inline apps/files_external/lib/dropbox.php]: Yeah, something to think about for 9.1 perhaps. It is a prerequisite to be able to use streaming properly in the first place: https://github.com/owncloud/core/issues/5949

Comment (icewind1991) [inline apps/files_external/lib/dropbox.php]: Had a quick try at creating a wrapper to normalize the read/write behavior to always return the requested number of bytes https://github.com/icewind1991/Streams/blob/05a6f6127f76cb6ba38e235b5c4a312ebceaf7cc/src/RetryWrapper.php

Turn out I already made a wrapper to add seek support earlier :smile:

Comment (PVince81) [inline apps/files_external/lib/dropbox.php]: This wasn't even about seek, it's just about not using the library's way which stores the whole file in memory.

Comment (PVince81) [inline apps/files_external/lib/dropbox.php]: I'd still like to merge this as is as I'm not sure we'd want to introduce the wrapper in 9.0.1 (new code, like a new feature).

Comment (icewind1991) [inline apps/files_external/lib/dropbox.php]: I'm OK with merging this and then look into the wrapper magic for 9.1

**Comment by PVince81** [comment]
So can I get your thumbs up @icewind1991 @LukasReschke ?

@karlitschek backport to 9.0.1 ? (another memory issue, for dropbox download)

**Comment by karlitschek** [comment]
great. please backport

**Comment by LukasReschke** [comment]
:+1:

**Comment by icewind1991** [comment]
:+1:

**Comment by PVince81** [comment]
stable9: https://github.com/owncloud/core/pull/23372

**Comment by enoch85** [comment]
Thanks!
