### PR TITLE
Checksum intergration tests and fixes

### LINKED ISSUE #22693: Missing checksum intergration tests
I'm writing intergration tests for the current checksumming code. 
I have plans for the following tests:

- [x] Upload file with checksum
  - [x] Verify in propfind
  - [x] Verify in download header
- [x] Chunked upload with checksum
  - [x] Verify in propfind
  - [x] Verify in download header
- [x] Copy file with checksum should also copy the checksum
  - [x] Verify in propfind
  - [x] Verify in download header
- [x] Moving a file with checksum should also move the checksum
  - [x] Verify in propfind
  - [x] Verify in download header
- [x] Uploading a file with checksum and overwriting it with a file without cheksum should remove the checksum
  - [x] Verify in propfind
  - [x] Verify in download

I'm not sure yet but I think this will reveal some bugs already. (When switching from one approach to the other in the PR).

I think it would be good to have this in 9.0.1 since then we can detect breaking backports properly. And the impact *should* be minimal. FYI @PVince81 @cmonteroluque

### PR DESCRIPTION
**Pull request by rullzer**
FIxes https://github.com/owncloud/core/issues/22693

This introduces intergration tests for the checksumming code. And at the same time fixes the failing test cases :wink: 

CC: @PVince81 @MorrisJobke @SergioBertolinSG @nickvergessen

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@rullzer There are quite some CI failures ;)

**Comment by rullzer** [comment]
Mmmm I'm not sure why right now... but I'll look into them

**Comment by nickvergessen** [comment]
> OCA\DAV\Tests\Unit\Connector\Sabre\RequestTest\UploadTest::testBasicUpload
Undefined index: checksum

Soudns straight forward

File: apps/dav/lib/connector/sabre/file.php [hunk 1]
```diff
@@ -215,9 +215,13 @@ public function put($data) {
 				}
 			}
 
+			$this->refreshInfo();
+
 			if (isset($request->server['HTTP_OC_CHECKSUM'])) {
 				$checksum = trim($request->server['HTTP_OC_CHECKSUM']);
 				$this->fileView->putFileInfo($this->path, ['checksum' => $checksum]);
+			} else if ($this->getChecksum() !== NULL && $this->getChecksum() !== '') {
+				$this->fileView->putFileInfo($this->path, ['checksum' => '']);
```
Comment (DeepDiver1975) [inline apps/dav/lib/connector/sabre/file.php]: this is a quite critical change - not clearing the checkssum on a followup upload can cause serious issues

@cmonteroluque @PVince81 should go into 9.0 - sev1 - from my pov

**Comment by PVince81** [comment]
@rullzer is this ready for review ?

**Comment by rullzer** [comment]
Yes CI is ready... please review.

File: apps/dav/lib/connector/sabre/file.php [hunk 2]
```diff
@@ -215,9 +215,13 @@ public function put($data) {
 				}
 			}
 
+			$this->refreshInfo();
```
Comment (PVince81) [inline apps/dav/lib/connector/sabre/file.php]: I hope this won't have other side effects ?

Comment (rullzer) [inline apps/dav/lib/connector/sabre/file.php]: Should not... @icewind1991

Comment (PVince81) [inline apps/dav/lib/connector/sabre/file.php]: Why do you need this ? From what I remember this would refetch the FileInfo from the file cache (additional DB query). Is there a safer way around this ?

Comment (icewind1991) [inline apps/dav/lib/connector/sabre/file.php]: no way around this here, cache has just changed since we're uploading the file

**Comment by PVince81** [comment]
@rullzer looks like you missed adding the same stuff in `createFileChunked` ?
In the case of chunked upload, your new code would get bypassed

**Comment by rullzer** [comment]
No. We only do checksum handing on assembling of the file. Individual chunks are not checksummed

**Comment by PVince81** [comment]
@rullzer this has nothing to do with checksumming chunks.

The upload code unfortunately always had two separate code paths, so everything that is done for the first one needs to be done in the second one too. The chunking code path will assemble the chunks into a part file and then rename it to the final file. You'll need to add your code there as well.

See https://github.com/owncloud/core/blob/v8.2.2/lib/private/connector/sabre/file.php#L101
The return jumps out completely and skips your new code.

**Comment by PVince81** [comment]
See https://github.com/owncloud/core/blob/v8.2.2/lib/private/connector/sabre/file.php#L394

This means we'd also need integration tests with chunked upload. Trouble though is that we're testing through Webdav directly, which means we'd need to implement chunked upload in PHP...

File: apps/dav/lib/connector/sabre/file.php [hunk 3]
```diff
@@ -459,6 +463,14 @@ private function createFileChunked($data) {
 
 				$info = $this->fileView->getFileInfo($targetPath);
 
+				if (isset($request->server['HTTP_OC_CHECKSUM'])) {
+					$checksum = trim($request->server['HTTP_OC_CHECKSUM']);
+					$this->fileView->putFileInfo($targetPath, ['checksum' => $checksum]);
+				} else if ($info->getChecksum() !== NULL && $info->getChecksum() !== '') {
+					$this->fileView->putFileInfo($this->path, ['checksum' => '']);
+				}
```
Comment (rullzer) [inline apps/dav/lib/connector/sabre/file.php]: @PVince81 this is the chunked upload path

File: build/integration/features/checksums.feature [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+    Then The webdav checksum should be empty
+
+  Scenario: Overwriting a file with checksum should remove the checksum and not return it in the download header
+    Given user "user0" exists
+    And user "user0" uploads file "data/textfile.txt" to "/myChecksumFile.txt" with checksum "MD5:d70b40f177b14b470d1756a3c12b963a"
+    When user "user0" uploads file "data/textfile.txt" to "/myChecksumFile.txt"
+    And user "user0" downloads the file "/myChecksumFile.txt"
+    Then The OC-Checksum header should not be there
+
+  Scenario: Uploading a chunked file with checksum should return the checksum in the propfind
```
Comment (rullzer) [inline build/integration/features/checksums.feature]: @PVince81 and here the chunked upload test

**Comment by PVince81** [comment]
@rullzer sorry, I missed them.

However it seems that `refreshInfo` is only on one of the paths, is that on purpose ?

File: apps/dav/lib/connector/sabre/file.php [hunk 5]
```diff
@@ -459,6 +463,14 @@ private function createFileChunked($data) {
 
 				$info = $this->fileView->getFileInfo($targetPath);
```
Comment (rullzer) [inline apps/dav/lib/connector/sabre/file.php]: @PVince81 here is the info refresh. This is different for chunked files. Since we are actually on the last chunk. So updating that will not work.

File: apps/dav/lib/connector/sabre/file.php (hunk 2 above)
Comment (PVince81) [inline apps/dav/lib/connector/sabre/file.php]: I think the first `refreshInfo` is not needed for `$this->getChecksum() !== NULL` to work. At this point of the code the old cache info should already be available.

I agree that `refreshInfo` is required after `putFileInfo`, but please do it inside the `if` block when there was an actual call to `putFileInfo` (instead of always)

Comment (PVince81) [inline apps/dav/lib/connector/sabre/file.php]: The reason is because `refreshInfo` will do a SQL query to the database to read the info, and we want to avoid doing unneeded database calls.

File: apps/dav/lib/connector/sabre/file.php (hunk 3 above)
Comment (PVince81) [inline apps/dav/lib/connector/sabre/file.php]: Hmm, the reason we have `getFileInfo` was only to get the etag. Technically `refreshInfo` would have be better to make sure all the file node's info is refreshed.

You'll still need to call `refreshInfo` after `putFileInfo` calls to make sure the node's info is refreshed and subsequent calls to `$node->getChecksum()` return the correct value, like you did in the other code path.

File: apps/dav/lib/connector/sabre/file.php (hunk 2 above)
Comment (PVince81) [inline apps/dav/lib/connector/sabre/file.php]: Too bad we can't just set the checksum on the FileInfo object, that would save some DB queries. But doing so is probably risky and out of scope. `refreshInfo` will do for now.

File: apps/dav/lib/connector/sabre/file.php (hunk 3 above)
Comment (PVince81) [inline apps/dav/lib/connector/sabre/file.php]: What a mess this chunking logic... I found the reason why we can't use `refreshInfo` here: it's because the path doesn't point to the actual file but to the chunk...

Let's leave it as is, but important it to check whether the checksum header still contains the correct value. Because if it's calling `$node->getChecksum()` it will get the wrong one.

**Comment by PVince81** [comment]
@rullzer I made the changes, please review my commit.
Also phpcs told me that `NULL` must be `null`, looks like you did too much C++ recently ? :wink:

**Comment by rullzer** [comment]
@PVince81 looks good. If CI is happy so am I :) :+1: 

And yes :wink:

**Comment by DeepDiver1975** [comment]
@rullzer rebase required

**Comment by PVince81** [comment]
I'll rebase this.

Also smashbox failed locally but not on master:
```
2016-03-01 11:26:54,151 - ERROR - sharer - md5 of modified file /home/vincent/work/smashdir/test_shareFile/sharer/TEST_FILE_MODIFIED_USER_SHARE.dat did not change: expected 45b565af28a2998fa8d5dae7eb6e660e "md5 of modified file %s did not change%s: expected %s" % (fn, comment, md5)) failed in expect_modified() ["/home/vincent/work/workspace/smashbox/python/smashbox/utilities/__init__.py" at line 781]
```

**Comment by PVince81** [comment]
Looks like it's my commit that messes up the smashbox test... :cry:

**Comment by PVince81** [comment]
Rebased and fixed the smashbox issue.
