### PR TITLE
Fix DeleteOrphanedSharesJob

### LINKED ISSUE #16036: DeleteOrphanedSharesJob spams log
I think the log entry should be on debug rather then info.
```
{"reqId":"wfnmFT1\/goWwkiYLuFZM","remoteAddr":"127.0.0.1","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":1,"time":"2015-05-04T09:26:04+00:00"}
{"reqId":"+VwKmhnDRnmp+TUHY+SW","remoteAddr":"127.0.0.1","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":1,"time":"2015-05-04T09:34:47+00:00"}
{"reqId":"lsACVu4E9Elf5pbEZ2hp","remoteAddr":"127.0.0.1","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":1,"time":"2015-05-04T09:41:04+00:00"}
{"reqId":"ZAD64IfRzH4Afk\/KAlQ5","remoteAddr":"127.0.0.1","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":1,"time":"2015-05-04T09:42:30+00:00"}
{"reqId":"39bP7Uk7e+25CXOAoYPO","remoteAddr":"127.0.0.1","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":1,"time":"2015-05-04T09:44:24+00:00"}
{"reqId":"xCT04vWegShueRFrkwid","remoteAddr":"127.0.0.1","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":1,"time":"2015-05-04T09:46:09+00:00"}
{"reqId":"DvFmHTsDoZ0aWSZZK\/38","remoteAddr":"127.0.0.1","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":1,"time":"2015-05-04T10:04:02+00:00"}
```

@MorrisJobke @PVince81 (vacation :( )

### PR DESCRIPTION
**Pull request by MorrisJobke**
- remove unneeded use statements
- the the interval properly in the constructor
- set the log level to debug (from info) - fixes #16036 

cc @PVince81 @nickvergessen @DeepDiver1975

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

File: apps/files_sharing/lib/deleteorphanedsharesjob.php [hunk 1]
```diff
@@ -39,6 +37,13 @@ class DeleteOrphanedSharesJob extends TimedJob {
 	protected $defaultIntervalMin = 15;
 
 	/**
+	 * sets the correct interval for this timed job
+	 */
+	public function __construct(){
+		$this->interval = $this->defaultIntervalMin * 60;
```
Comment (LukasReschke) [inline apps/files_sharing/lib/deleteorphanedsharesjob.php]: :see_no_evil:

**Comment by LukasReschke** [comment]
:+1:

File: apps/files_sharing/lib/deleteorphanedsharesjob.php (hunk 1 above)
Comment (MorrisJobke) [inline apps/files_sharing/lib/deleteorphanedsharesjob.php]: I always wondered why this is logged that often and where this magic minutes interval comes from, because I didn't know it :D
