### PR TITLE
if user has enough permission, allow to increase permission

### LINKED ISSUE #35528: Permission of reshare cannot be increased
### Steps to reproduce
1. `user0` shares a folder `TMP` with `user1` with permissions 23 (can-share+read-update-create)
2. `user1` shares `TMP` with `user2` with permissions 17 (can-share+read)
3. `user1` tries to update the permissions of the share to 23

### Expected behaviour
Step 3 works, and the share now has permissions 23

### Actual behaviour
Step 3 returns a 404

### Server configuration
**Operating system**:
Ubuntu 18.04

**Web server:**
drone CI Apache

**Database:**
MySQL

**PHP version:**
7.*

**ownCloud version:** (see ownCloud admin page)
current master from git

A Gherkin acceptance test scenario that demonstrates the issue:
```
  Scenario Outline: Update of reshare can increase permissions to the maximum allowed
    Given using OCS API version "<ocs_api_version>"
    And user "user2" has been created with default attributes and without skeleton files
    And user "user0" has created folder "/TMP"
    And user "user0" has created a share with settings
      | path        | /TMP  |
      | shareType   | 0     |
      | shareWith   | user1 |
      | permissions | 23    |
    And user "user1" has created a share with settings
      | path        | /TMP  |
      | shareType   | 0     |
      | shareWith   | user2 |
      | permissions | 17    |
    When user "user1" updates the last share using the sharing API with
      | permissions | 23 |
    Then the OCS status code should be "404"
    And the HTTP status code should be "<http_status_code>"
    #Then the OCS status code should be "<ocs_status_code>"
    #And the HTTP status code should be "200"
    Examples:
      | ocs_api_version | http_status_code |
      | 1               | 200              |
      | 2               | 404              |
      #| ocs_api_version | ocs_status_code |
      #| 1               | 100             |
      #| 2               | 200             |
```

### PR DESCRIPTION
**Pull request by karakayasemi**
## Description
After https://github.com/owncloud/core/pull/35447 merged, it has become that only node owners can increase permissions on a share. It has lead to this regression: https://github.com/owncloud/core/issues/35528

This PR checks Session User's permission on the share node. If user has enough permission, it let session user to increase permission of the share.

## Related Issue
- Fixes #35528 

## Motivation and Context
Solving bug.

## How Has This Been Tested?
Followed the scenario described in the issue. Also, we have acceptance tests that are covering bug scenario.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [x] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by sharidas — APPROVED** [review]
LGTM :+1:

File: apps/files_sharing/lib/Controller/Share20OcsController.php [hunk 1]
```diff
@@ -921,8 +922,9 @@ private function canIncreasePermission(IShare $share) {
 		$shareHome = $this->rootFolder->getUserFolder($share->getSharedBy());
 		$nodes = $shareHome->getById($share->getNode()->getId());
 		foreach ($nodes as $node) {
+			$allowedPermissions = $node->getPermissions();
 			$nodeOwner = $node->getOwner()->getUID();
-			if ($nodeOwner !== $userObj->getUID()) {
+			if ($nodeOwner !== $userObj->getUID() && ($allowedPermissions < $permissions)) {
```
Comment (DeepDiver1975) [inline apps/files_sharing/lib/Controller/Share20OcsController.php]: Our permissions have no hierarchy in their values.
Sharing(16) > Write(8) -> does this imply that if a user has share permissions he has automatically write permissions?

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]
Please have a look at my comment above - I'm not happy ....

**Comment by patrickjahns** [comment]
@karakayasemi 
please add unit tests to cover your change and outline intended behavior

File: apps/files_sharing/lib/Controller/Share20OcsController.php (hunk 1 above)
Comment (karakayasemi) [reply apps/files_sharing/lib/Controller/Share20OcsController.php]: @DeepDiver1975 Thank you for pointing out this. Now, bit-wise operations used in comparison.

File: apps/files_sharing/lib/Controller/Share20OcsController.php [hunk 2]
```diff
@@ -906,13 +906,14 @@ public function updateShare($id) {
 	}
 
 	/**
-	 * If the user is not the owner of the share, then lets not allow to increase
-	 * the permission of the share.
+	 * If the user is not the owner of the share and has not enough permission on Node,
+	 * then lets not allow to increase the permission of the share.
 	 *
 	 * @param IShare $share
+	 * @param int $permissions
```
Comment (jvillafanez) [inline apps/files_sharing/lib/Controller/Share20OcsController.php]: This might need extra information. I don't understand where these permissions come from, nor what these permissions are used for.
As far as I know, you're allowed to increase the permissions only if you're the owner, so you have enough information from the user session and the share.

File: apps/files_sharing/lib/Controller/Share20OcsController.php [hunk 3]
```diff
@@ -921,8 +922,9 @@ private function canIncreasePermission(IShare $share) {
 		$shareHome = $this->rootFolder->getUserFolder($share->getSharedBy());
 		$nodes = $shareHome->getById($share->getNode()->getId());
 		foreach ($nodes as $node) {
+			$allowedPermissions = $node->getPermissions();
 			$nodeOwner = $node->getOwner()->getUID();
-			if ($nodeOwner !== $userObj->getUID()) {
+			if ($nodeOwner !== $userObj->getUID() && ($permissions & ~$allowedPermissions)) {
```
Comment (DeepDiver1975) [inline apps/files_sharing/lib/Controller/Share20OcsController.php]: Just to be sure - this is identical to https://github.com/owncloud/core/pull/35600/files#diff-faddd9984dfaf09a2b85d8dc4867207aR831

Who ever introduced bitfuxxing to owncloud:  :gun:

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]

File: apps/files_sharing/lib/Controller/Share20OcsController.php (hunk 3 above)
Comment (jvillafanez) [reply apps/files_sharing/lib/Controller/Share20OcsController.php]: yes. Better include at least a comment around so we know what this code is trying to do. It would be better to have function to handle these operations, but it's out of scope.

Comment (karakayasemi) [reply apps/files_sharing/lib/Controller/Share20OcsController.php]: I moved this logic to `hasEnoughPermissions` method and I singularized this check handling by using this method at least this class wide.

File: apps/files_sharing/lib/Controller/Share20OcsController.php (hunk 2 above)
Comment (karakayasemi) [reply apps/files_sharing/lib/Controller/Share20OcsController.php]: I changed variable name as `newPermissions`.

> As far as I know, you're allowed to increase the permissions only if you're the owner, so you have enough information from the user session and the share.

To fix regression, I have add additional condition to this method and update its phpdoc. Now, if the share node is mounted to Session User's home folder and Session User has enough permission to increase permission, The user can increase permission even he is not owner of the node.

File: apps/files_sharing/lib/Controller/Share20OcsController.php [hunk 4]
```diff
@@ -1263,4 +1265,15 @@ private function setShareAttributes(IShare $share, $formattedShareAttributes) {
...
 	}
+
+	/**
+	 * Check $newPermissions bit is a subset of $allowedPermissions
+	 *
+	 * @param int $allowedPermissions
+	 * @param int $newPermissions
+	 * @return boolean ,true if $allowedPermissions bit super set of $newPermissions bit, else false
+	 */
+	private function hasEnoughPermissions($allowedPermissions, $newPermissions) {
```
Comment (jvillafanez) [inline apps/files_sharing/lib/Controller/Share20OcsController.php]: `strictSubsetOf` might be a better name. `hasEnoughPermission` might sound like if $allowedPermissions is "read" and $newPermissions is "read+write" it should return true because "read+write" has enough permissions if "read" is allowed

Comment (karakayasemi) [reply apps/files_sharing/lib/Controller/Share20OcsController.php]: changed as `strictSubsetOf`

File: apps/files_sharing/tests/Controller/Share20OcsControllerTest.php [hunk 5]
```diff
@@ -3804,4 +3823,31 @@ public function testAcceptRejectShareOperationError($method, $target, $targetExi
...
+				$this->ocs,
+				'strictSubsetOf',
+				[$allowedPermissions, $newPermissions]
+			)
+		);
+	}
+
+	public function strictSubsetOfDataProvider() {
+		return [
+			[\bindec('11111'), \bindec('0111'), true],
```
Comment (DeepDiver1975) [inline apps/files_sharing/tests/Controller/Share20OcsControllerTest.php]: :+1:

**Review by DeepDiver1975 — APPROVED** [review]

File: apps/files_sharing/lib/Controller/Share20OcsController.php (hunk 2 above)
Comment (jvillafanez) [reply apps/files_sharing/lib/Controller/Share20OcsController.php]: The problem I have is that I read "*If the user is not the owner of the share*" and I think "*if the method is called "canIncreasePermission" this is fine*" but then I read "*has not enough permission on Node,*" and I don't know what to think. How we can know if the user has or not enough permissions?
There is also a parameter with newPermissions which, just reading the documentation, I don't understand what is used for. Are those the permissions we're expecting to be set later?

My main point here is that, if I already have problems to understand these changes (just a part of it, not all), I'm pretty sure next year I'll have no idea what this code do, and this will be something risky to touch because it isn't clear what the code should be doing (not what the code really does).

Don't be afraid of writing an explanation in the code as long as it helps to understand what the code is doing.

**Comment by micbar** [comment]
@karakayasemi new tests merged into release branch. Could you rebase?

**Comment by phil-davis** [comment]
Note: acceptance tests in `master` `stable10` and `release-10.2.1` are all the same. So for getting the first version of this PR reviewed, `master` base should be fine.
Then we also make the backport PRs to `stable10` and `release-10.2.1` and confirm CI is good there also.

**Comment by micbar** [comment]
@phil-davis @karakayasemi Sorry for my misleading comment.
Anyway, I would give CI a last chance to finish correctly.

**Comment by patrickjahns** [comment]
@ownclouders rebase

**Review by IljaN — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]

**Comment by karakayasemi** [comment]
Codecov came for backport PRs. I deleted old codecov report comments. I will try my chance with this way, started a new build.

**Comment by phil-davis** [comment]
Backports
`stable10` #35634 
`release-10.2.1` #35633
