### PR TITLE
[For 10.4] user is only allowed to see their own home trashbin

### LINKED ISSUE #36378: Trashbin api allows users to see trashbin content of other users.
### Steps to reproduce
0. Enable trashbin preview API.
1. Create user:
    `./occ user:add chameli`
2. As `chameli` delete a file eg `lorem.txt`
    `curl -X DELETE  http://localhost/core/remote.php/dav/files/chameli/lorem.txt -u chameli:qwerty`
3. As `user1`, send request to trashbin API for files of `chameli`.
```
curl -X PROPFIND http://172.17.0.1/oc/core/remote.php/dav/trash-bin/chameli -u user1:pass1 --data '<?xml version="1.0"?><d:propfind xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:ocs="http://open-collaboration-services.org/ns"><d:prop><oc:trashbin-original-filename/><oc:trashbin-original-location/><oc:trashbin-delete-timestamp/><d:getlastmodified/><d:getcontentlength/><d:resourcetype/></d:prop></d:propfind>' -v| xmllint --format -
```
### Expected behaviour
- The user should get 401 response (unauthorized)

### Actual behaviour
- The user can list all the contents of the trashbin for `chameli` in the trashbin api response
```xml
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/core/remote.php/dav/trash-bin/chameli/</d:href>
    <d:propstat>
      <d:prop>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
      <d:prop>
        <oc:trashbin-original-filename/>
        <oc:trashbin-original-location/>
        <oc:trashbin-delete-timestamp/>
        <d:getlastmodified/>
        <d:getcontentlength/>
      </d:prop>
      <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/core/remote.php/dav/trash-bin/chameli/2147490712</d:href>
    <d:propstat>
      <d:prop>
        <oc:trashbin-original-filename>lorem.txt</oc:trashbin-original-filename>
        <oc:trashbin-original-location>lorem.txt</oc:trashbin-original-location>
        <oc:trashbin-delete-timestamp>1573023465</oc:trashbin-delete-timestamp>
        <d:getlastmodified>Wed, 06 Nov 2019 06:57:41 GMT</d:getlastmodified>
        <d:getcontentlength>446</d:getcontentlength>
        <d:resourcetype/>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```

### Server configuration
**Operating system**: ubuntu18.04

**Web server:** apache2

**Database:** mysql

**PHP version:** 7.2

**ownCloud version:** (see ownCloud admin page) 10.3 (git)

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** git

**Signing status (ownCloud 9.0 and above):**

<!--
**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### ownCloud log (data/owncloud.log)
No log, even with `log-level` set to `0`.

### PR DESCRIPTION
**Pull request by karakayasemi**
## Description
User is only allowed to see their own home trashbin.

## Related Issue
- Fixes #36378

## Motivation and Context
Trashbin API had allowed users to see the trashbin content of other users. This bug has been resolved.

## How Has This Been Tested?
Followed #36378's reproduce steps. Also, acceptance tests already cover this issue.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [x] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

File: apps/dav/lib/TrashBin/RootCollection.php [hunk 1]
```diff
@@ -33,10 +34,15 @@ class RootCollection extends AbstractPrincipalCollection {
...
 	 * @param array $principalInfo
-	 * @return TrashBinHome
+	 * @return TrashBinHome | SimpleCollection
 	 */
 	public function getChildForPrincipal(array $principalInfo) {
-		return new TrashBinHome($principalInfo, new TrashBinManager());
+		list(, $name) = \Sabre\Uri\split($principalInfo['uri']);
+		$sessionUser = \OC::$server->getUserSession()->getUser();
+		if ($sessionUser === null || $name !== $sessionUser->getUID()) {
+			return new SimpleCollection($name);
```
Comment (karakayasemi) [inline apps/dav/lib/TrashBin/RootCollection.php]: Acceptance tests were expecting 401, as HTTP status code. I could throw a `NotAuthenticated` exception for this purpose. However, throwing an exception is violating the contract of the parent class abstract method. Because of that, I preferred to return `SimpleCollection` and adjust acceptance tests to expect 404 as the HTTP status code.

File: changelog/unreleased/36488 [hunk 2]
```diff
@@ -0,0 +1,6 @@
+Bugfix: Fix Trash-bin api to no allow users to see trash-bin content of other users
```
Comment (phil-davis) [inline changelog/unreleased/36488]:
```suggestion
Bugfix: Fix Trash-bin api to not allow users to see trash-bin content of other users
```

**Review by phil-davis — COMMENTED** [review]
Looks good from QA acceptance test point of view

**Comment by phil-davis** [comment]
@micbar this needs a developer technical review of the code, then IMO it can be merged for 10.4 release.

File: apps/dav/lib/TrashBin/RootCollection.php [hunk 3]
```diff
@@ -34,9 +35,15 @@ class RootCollection extends AbstractPrincipalCollection {
 	 *
 	 * @param array $principalInfo
 	 * @return TrashBinHome
+	 * @throws NotAuthenticated
 	 */
 	public function getChildForPrincipal(array $principalInfo) {
-		return new TrashBinHome($principalInfo, new TrashBinManager());
+		list(, $name) = \Sabre\Uri\split($principalInfo['uri']);
+		$sessionUser = \OC::$server->getUserSession()->getUser();
```
Comment (DeepDiver1975) [inline apps/dav/lib/TrashBin/RootCollection.php]: inject user session here - better unit testing capabilities then at the end

File: apps/dav/lib/TrashBin/RootCollection.php [hunk 4]
```diff
@@ -34,9 +35,15 @@ class RootCollection extends AbstractPrincipalCollection {
...
+		if ($sessionUser === null || $name !== $sessionUser->getUID()) {
+			throw new NotAuthenticated();
```
Comment (DeepDiver1975) [inline apps/dav/lib/TrashBin/RootCollection.php]: shall we log something here?

File: apps/dav/tests/unit/TrashBin/RootCollectionTest.php [hunk 5]
```diff
@@ -34,11 +35,32 @@ public function testGetName() {
 	}
 
 	public function testGetChildForPrincipal() {
+		/** @var IUser | \PHPUnit\Framework\MockObject\MockObject $user */
+		$user = $this->createMock(IUser::class);
+		$user->method('getUID')->willReturn('alice');
+		\OC::$server->getUserSession()->setUser($user);
```
Comment (DeepDiver1975) [inline apps/dav/tests/unit/TrashBin/RootCollectionTest.php]: user session should be mocked

File: changelog/unreleased/36488 [hunk 6]
```diff
@@ -0,0 +1,6 @@
+Bugfix: Fix Trash-bin api to not allow users to see trash-bin content of other users
+
+Trash-bin API had allowed users to see the trash-bin content of other users. This bug has been resolved.
```
Comment (DeepDiver1975) [inline changelog/unreleased/36488]: since this is a bug fix I assume that 'This bug has been resolved' - not needed sentence from my pov

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]

File: apps/dav/lib/TrashBin/RootCollection.php (hunk 3 above)
Comment (karakayasemi) [reply apps/dav/lib/TrashBin/RootCollection.php]: UserSession injected to class.

File: changelog/unreleased/36488 (hunk 6 above)
Comment (karakayasemi) [reply changelog/unreleased/36488]: 'This bug has been resolved' sentence removed.

File: apps/dav/lib/TrashBin/RootCollection.php (hunk 4 above)
Comment (karakayasemi) [reply apps/dav/lib/TrashBin/RootCollection.php]: I looked at similar classes, generally, we do not log anything in RootCollections, I could not find specific things to log. If you have any suggestions, I can add it.

**Comment by phil-davis** [comment]
@DeepDiver1975 or somebody - review again, and we can merge?

**Review by DeepDiver1975 — APPROVED** [review]
