### PR TITLE
redirect to error page if download failed

### LINKED ISSUE #16232: Corrupted shared file if the share recipent hasn't his encryption keys generated
### Steps to reproduce
1. Enable files_encryption and user_ldap apps
2. Setup a LDAP configuration in ownCloud with several users
3. Upload a file in userA account (checked with a local user but could be a LDAP user) having the encryption keys already generated
4. Share the file with a LDAP user (userB)
5. Enter the in userB account (for the first time) and download the file from there

### Expected behaviour
The file is downloaded correctly

### Actual behaviour
The file is downloaded corrupted. The userB MUST have entered his account and generated the encryption keys before the sharing take place.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 beta 1

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:**
- files_encryption
- files_external (probably not related)
- user_ldap (indirectly related, but probably reproducible without it)
- files_locking (probably not related)
- sharing

#### ownCloud log (data/owncloud.log)
```
{"reqId":"u8+s5hK+FeJILIGvToPu","remoteAddr":"10.40.10.254","app":"hook","message":"error while running hook (OC\\Encryption\\HookManager::postShared): Public Key missing for user: 3cf06726-8289-1034-8404-6b3cf12c4922","level":3,"time":"2015-05-11T09:21:56+00:00"}
{"reqId":"t0gf41zscnHrNJZjkbMT","remoteAddr":"10.40.10.254","app":"hook","message":"error while running hook (OC\\Encryption\\HookManager::postUnshared): Public Key missing for user: 3cf06726-8289-1034-8404-6b3cf12c4922","level":3,"time":"2015-05-11T09:23:24+00:00"}
{"reqId":"oaq0uaIfok+3Qzgy+8WF","remoteAddr":"10.40.10.254","app":"hook","message":"error while running hook (OC\\Encryption\\HookManager::postShared): Public Key missing for user: 3cf06726-8289-1034-8404-6b3cf12c4922","level":3,"time":"2015-05-11T09:23:55+00:00"}
{"reqId":"VjPgUIPBapjV7nTD54dE","remoteAddr":"10.40.30.21","app":"hook","message":"error while running hook (OCA\\Encryption\\Hooks\\UserHooks::login): Private Key missing for user: please try to log-out and log-in again","level":3,"time":"2015-05-11T09:24:58+00:00"}
```

### Notes
I think the main issue is that the sharing dialog shows all available users without filtering out the users who haven't login yet and don't have their keys generated (it shouldn't filter them out though). This implies that the "source" user can share his file with those users.

In addition, sharing with "already-logged-in" users might be affected by this issue because the hook might not be fully run and stop in the middle, so the sharing might not be take place for that user

### LINKED ISSUE #16264: Shared files with users existing before encryption cannot be decrypted by sharee
### Steps to reproduce

1. Create user1
2. Enable encryption app.
3. Enable encryption module in admin page.
4. Relogin.
5. Upload a file as admin.
6. Share it with user1.
7. Login with user1 (Relogin it a warning message request it).
8. Open with user1 the file shared by admin.

### Expected behaviour
user1 can open file.

### Actual behaviour
user1 can't decrypt file.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.
Encryption.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes

**Logs**
```
```
### Client configuration

**browser**
Chrome 41

### PR DESCRIPTION
**Pull request by schiessle**
- introduce general fallback if something goes wrong during download
- redirect to error page if the user tries to download a shared file for which the user doesn't has a share key

fix https://github.com/owncloud/core/issues/16232
fix https://github.com/owncloud/core/issues/16264

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

File: apps/encryption/lib/crypto/encryption.php [hunk 1]
```diff
@@ -268,8 +269,14 @@ public function encrypt($data) {
 	 *
 	 * @param string $data you want to decrypt
 	 * @return mixed decrypted data
+	 * @throws DecryptionFailedException
 	 */
 	public function decrypt($data) {
+		if (empty($this->fileKey)) {
+			$msg = 'Can not decrypt this file, probably this is a shared file.
```
Comment (DeepDiver1975) [inline apps/encryption/lib/crypto/encryption.php]: translation is missing

File: lib/private/helper.php [hunk 2]
```diff
@@ -1044,4 +1044,23 @@ private static function getGlobalStorageInfo() {
...
+
+	/**
+	 * redirect to error page
+	 *
+	 * @param $errorMessage
+	 * @throws Exception
+	 */
+	public static function redirectToErrorPage($errorMessage) {
+
+		$location = \OC_Helper::linkToAbsolute('core/templates', '500.php');
```
Comment (DeepDiver1975) [inline lib/private/helper.php]: please define a proper route and use that - THX

File: core/templates/500.php [hunk 3]
```diff
@@ -0,0 +1,28 @@
+<?php
+/** @var $_ array */
+/** @var $l OC_L10N */
+if(!isset($_)) {//also provide standalone error page
+	require_once '../../lib/base.php';
```
Comment (DeepDiver1975) [inline core/templates/500.php]: this is not needed - please us a route - https://github.com/owncloud/core/pull/16243/files#r30111471

File: lib/private/files.php [hunk 4]
```diff
@@ -142,39 +142,45 @@ public static function get($dir, $files, $only_header = false) {
...
+						\OC\Files\Filesystem::readfile($filename);
+					}
 				} else {
 					\OC\Files\Filesystem::readfile($filename);
 				}
-			} else {
-				\OC\Files\Filesystem::readfile($filename);
 			}
+		} catch (\Exception $ex) {
+			\OC_Helper::redirectToErrorPage($ex->getMessage());
```
Comment (DeepDiver1975) [inline lib/private/files.php]: i'm not really happy with this approach - rendering the error page is job of the caller of this method

File: core/templates/500.php [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+
+	$errorMessage = 'Unknown error, please contact your Administrator';
+	if (isset($_GET['errorMessage'])) {
+		$errorMessage = urldecode($_GET['errorMessage']);
```
Comment (LukasReschke) [inline core/templates/500.php]: It's a bad habit to have an error message configurable by the user as it might be used for social engineering. I am aware that there are other cases, some we fixed already and other are in work, but we shouldn't introduce more for now.

File: core/templates/500.php [hunk 6]
```diff
@@ -0,0 +1,28 @@
+<?php
+/** @var $_ array */
+/** @var $l OC_L10N */
+if(!isset($_)) {//also provide standalone error page
+	require_once '../../lib/base.php';
+
+	$errorMessage = 'Unknown error, please contact your Administrator';
```
Comment (LukasReschke) [inline core/templates/500.php]: If it is an unknown error and one should contact the administrator why not throwing an uncatched exception? It will print an error page with Request ID and the request ID will reference the failing stacktrace in the log.

Comment (schiesbn) [inline core/templates/500.php]: Because this does not always work, e.g. if something during a download fails.

For example try following:

1. create two users, admin and user1
2. enable encryption
3. re-login as admnin
4. upload a file and share it with user1
5. login as user1 and try to download the file
-> the download will fail because the file wasn't encrypted for user1 (user1 didn't had a valid key during sharing)

But the exception happens when the download already started which will lead to white error page from your browser. At this stage we no longer catch the exception correctly. That's why I added a try/catch block and re-direct to a error page in this case.
- now enable encryption
- logout and login agai

File: apps/encryption/lib/crypto/encryption.php (hunk 1 above)
Comment (schiesbn) [inline apps/encryption/lib/crypto/encryption.php]: normally we don't translate exception messages.

Comment (DeepDiver1975) [inline apps/encryption/lib/crypto/encryption.php]: but this exception is supposed to be shown to the user - right?

File: lib/private/files.php (hunk 4 above)
Comment (schiesbn) [inline lib/private/files.php]: This way we would need to identify every possible place where a download gets initiated. I prefer to handle the error directly where it occurs.

File: core/templates/500.php (hunk 5 above)
Comment (schiesbn) [inline core/templates/500.php]: What we do here is to pass on the exception message. We do this on various other places. Typically they get displayed in the yellow banner at the top of the page. In this case we are at a point where we already left the web interface and starting to serve the file from the webserver. So we need to re-direct to a error page and pass on the exception message.

Comment (LukasReschke) [inline core/templates/500.php]: Please open `http://localhost/master/core/templates/500.php?errorMessage=%50%6c%65%61%73%65%25%32%30%63%6f%6e%74%61%63%74%25%32%30%69%6e%63%69%64%65%6e%74%40%68%61%63%6b%65%72%2e%63%6f%6d%25%32%30%69%6e%63%6c%75%64%69%6e%67%25%32%30%79%6f%75%72%25%32%30%75%73%65%72%25%32%30%63%72%65%64%65%6e%74%69%61%6c%73%2e` and tell me again that this is a good idea ;-)

Yes – I know, we have similar things in other places as well and we are working on removing then. But we won't add new ones. The ones you refer to with the yellow banner is also pretty sure using a CSRF check so cannot be forced by an attacker ;-)

Either pass the error message using a variable applied to the response object / session / whatever or simply log the error. No magic please.

Comment (LukasReschke) [inline core/templates/500.php]: > Please open http://localhost/master/core/templates/500.php?errorMessage=%50%6c%65%61%73%65%25%32%30%63%6f%6e%74%61%63%74%25%32%30%69%6e%63%69%64%65%6e%74%40%68%61%63%6b%65%72%2e%63%6f%6d%25%32%30%69%6e%63%6c%75%64%69%6e%67%25%32%30%79%6f%75%72%25%32%30%75%73%65%72%25%32%30%63%72%65%64%65%6e%74%69%61%6c%73%2e and tell me again that this is a good idea ;-)

And yes: The regular users are actually doing what a web page tells them if the context does not make clear that this message is user-controlled. :see_no_evil:

Comment (LukasReschke) [inline core/templates/500.php]: Or to hide it even from the URL:  http://localhost/master/core/templates/500.php?errorMessage=%2550%256c%2565%2561%2573%2565%20%2563%256f%256e%2574%2561%2563%2574%20%2569%256e%2563%2569%2564%2565%256e%2574%40%2568%2561%2563%256b%2565%2572%252e%2563%256f%256d%20%2569%256e%2563%256c%2575%2564%2569%256e%2567%20%2579%256f%2575%2572%20%2575%2573%2565%2572%20%2563%2572%2565%2564%2565%256e%2574%2569%2561%256c%2573%252e

**Comment by schiesbn** [comment]
ok, "new" approach. I now catch the exception in the error files app.

File: apps/files/controller/downloadcontroller.php [hunk 7]
```diff
@@ -0,0 +1,52 @@
...
+		parent::__construct($appName, $request);
+	}
+
+	/**
+	 *
+	 * @NoAdminRequired
+	 * @NoCSRFRequired
+	 * @param string $errorMessage
+	 */
+	public function failed($errorMessage = 'Unknown error, please contact your Administrator') {
```
Comment (LukasReschke) [inline apps/files/controller/downloadcontroller.php]: Will still have the same problem as `$errorMessage` is still user-controlled input. - `http://localhost/master/index.php/apps/files/ajax/downloadFailed?errorMessage=foo`

Comment (LukasReschke) [inline apps/files/controller/downloadcontroller.php]: Basically if you pass a parameter to a function in the AppFramework it will try to resolve it:

1. First to a URL parameter in the routing part
2. Then to GET / POST and some other stuff in case of PUT etc…

Comment (schiesbn) [inline apps/files/controller/downloadcontroller.php]: But it would be OK if we could enable the CSRF check, right? Would this be possible? I'm not sure how to add a valid token to the redirect.

File: apps/files/controller/downloadcontroller.php [hunk 8]
```diff
@@ -0,0 +1,52 @@
...
+		$template = new \OC_Template( 'files', 'failure', 'guest' );
+		$template->assign('errorMessage', $errorMessage);
+		$template->printPage();
```
Comment (LukasReschke) [inline apps/files/controller/downloadcontroller.php]: Looks fishy. Try to return a TemplateResponse?

File: apps/files/controller/downloadcontroller.php (hunk 7 above)
Comment (LukasReschke) [inline apps/files/controller/downloadcontroller.php]: > But it would be OK if we could enable the CSRF check, right? Would this be possible? I'm not sure how to add a valid token to the redirect.

Would be possibly, yes. But one does not really want to have the token in the URL for logging purposes etc. I'm also pretty sure users are then just going to copy-paste the URLs in bug reports and thus leaking the token etc.

Why not going with an hard-coded error for now? Alternatively you can do some HMAC magic with the secret in the config file but I'd recommend against that.

File: apps/files/controller/downloadcontroller.php (hunk 8 above)
Comment (schiesbn) [inline apps/files/controller/downloadcontroller.php]: update is already prepared, I will push it together with some other minor changes after Jenkins finished.

File: apps/files/controller/downloadcontroller.php (hunk 7 above)
Comment (schiesbn) [inline apps/files/controller/downloadcontroller.php]: This PR is not about error logging but about giving the user a useful feedback why he can't read a file shared with him instead if a white browser page.

We detect the error in a encryption module. That's why the download fails in the files app. And I really don't want to create a redirect directly in the encryption app. For two reasons:

1. This would mean that we have to repeat the same logic every time a download fails for whatever reasons in any app. 

2. If decryption fails during download a error page is the right answer. But if decryption fails in a different situation a different answer might be better. That's why I really want to decide what to do on the right place. In this case this is: https://github.com/owncloud/core/pull/16243/files#diff-bf5278fcb7b34e55ed3153c34f7dfdf1R44

File: apps/files/ajax/download.php [hunk 9]
```diff
@@ -39,4 +39,10 @@
 	$files_list = array($files);
 }
 
-OC_Files::get($dir, $files_list, $_SERVER['REQUEST_METHOD'] == 'HEAD');
+try {
+
+	OC_Files::get($dir, $files_list, $_SERVER['REQUEST_METHOD'] == 'HEAD');
+
+} catch (\Exception $ex) {
+	\OCA\Files\Helper::redirectToErrorPage($ex->getMessage());
```
Comment (DeepDiver1975) [inline apps/files/ajax/download.php]: what about re-using this:

```php
	OC_Template::printErrorPage($ex->getMessage(), $ex->getHint());

Comment (DeepDiver1975) [inline apps/files/ajax/download.php]: ... or is the redirection necessary here?

THX

File: apps/files/controller/downloadcontroller.php (hunk 7 above)
Comment (LukasReschke) [inline apps/files/controller/downloadcontroller.php]: Well – needs to get solved otherwise still :see_no_evil:

**Comment by schiesbn** [comment]
> no new line in translatable strings please - will confuse translators - THX

removed

File: apps/files/ajax/download.php (hunk 9 above)
Comment (schiesbn) [inline apps/files/ajax/download.php]: Doesn't work in this case because the browser already started the download, so you will end up with a "fie not found" error from your browser.

Comment (DeepDiver1975) [inline apps/files/ajax/download.php]: > so you will end up with a "fie not found" error from your browser.

we can work on the http status code to be returned - but responding a download in case of error properly sounds reasonable.

Comment (schiesbn) [inline apps/files/ajax/download.php]: The problem is that this can happen relatively easy. Share a encrypted file with a group, add a new user to the group and try to download the group share as the new user... :boom: In this case a white "file not found" page is not acceptable from my point of view. We need to inform the user what went wrong and give him a way back. The same error page we had in ownCloud <= 8.0

Comment (DeepDiver1975) [inline apps/files/ajax/download.php]: well - isn't that WPOD more an issue of the way the download link is called?

e.g. using the download link with curl/wget should NOT return an html page

@LukasReschke on browser magic - me being a too little padawan in this area - THX

Comment (LukasReschke) [inline apps/files/ajax/download.php]: That is because `\OC_Files::get` is a huge function that does a lot of things that it is not supposed to do at all. One of it is calling `\OC_Files::sendHeaders` that adds some headers such as the Content-Disposition.

The approach used here is though a huge hack that is abusing the HTTP specification and we should not go that route. The proper solution is to catch and throw the errors before https://github.com/owncloud/core/blob/17271e84643a9b0d20f7a657c353847338b998b8/lib/private/files.php#L133 and then the headers are never added. – Then we also can use the `\OC_Template::printErrorPage` function and have solved the problem with regard to the error message.

Comment (schiesbn) [inline apps/files/ajax/download.php]: but that's not possible because at this point we didn't start to read the file so there is no way to detect that we can't read it. We want to catch the case where the download failed. We can't catch it before we tried to download the file.

Comment (LukasReschke) [inline apps/files/ajax/download.php]: > We want to catch the case where the download failed. We can't catch it before we tried to download the file.

Why? – I think it makes sense to not thinking of it as "downloading" but more as "reading".

When it comes to check if we can read a file I'm pretty sure it would make sense to actual have functions in the encryption code to check whether a user can open a file. I don't know our new crypto code though. Then we would just need to check that and throw an exception?

Comment (schiesbn) [inline apps/files/ajax/download.php]: We just check if the file exists and the permissions, if I remember correctly. Nothing I can catch in the storage wrapper.

Comment (schiesbn) [inline apps/files/ajax/download.php]: Let me try if I can intercept the isReadable() call and do something useful with it.

**Comment by schiesbn** [comment]
@LukasReschke Please have a look at the second commit. This shows a new approach to display the error message and works completely independent from the first commit. If we agree on this solution I will remove the first commit from the pull request.

**Comment by schiesbn** [comment]
After thinking about it. One drawback of the second solution is that for a folder download we have to check every single file which also includes reading the header for each file. This could become a performance issue. With the first approach we get the check for free.

File: lib/private/files.php [hunk 10]
```diff
@@ -129,52 +129,60 @@ public static function get($dir, $files, $only_header = false) {
...
 				} else {
 					\OC\Files\Filesystem::readfile($filename);
 				}
-			} else {
-				\OC\Files\Filesystem::readfile($filename);
 			}
+		} catch (\Exception $ex) {
+			$l = \OC::$server->getL10N('core');
+			$hint = method_exists($ex, 'getHint') ? $ex->getHint() : '';
+			\OC_Template::printErrorPage($l->t('Can\'t read file'), $hint);
```
Comment (LukasReschke) [inline lib/private/files.php]: I like this much more :+1:

**Comment by schiesbn** [comment]
OK, this PR now only contain the second approach. The first one also didn't handled folder downloads or downloads of multiple files correctly because if the zip-streamer started to create the zip file and send it to the client we can't intercept it correctly, not even with the redirect approach.

For now I think this fix is good enough and as good as what we had in oc <= 8.0

With the isReadable() method we could even think about checking this at the point where we mount the shares and only mount shares which can be read from the user. But that's something for 8.2.

For now let's get this fix in to get on the same level as 8.0 again.

**Comment by PVince81** [comment]
Is this still valid ? If yes, please rebase

**Comment by schiesbn** [comment]
@PVince81 yes, this PR is still valid... please review. Thanks!

**Comment by PVince81** [comment]
Works :+1: 

A possible improvement would be to detect if the Exception is an encryption exception and then adjust the message accordingly. Anyway, this PR is already an improvement.
