### PR TITLE
[stable10] fix multi gdrive external storage bug

### LINKED ISSUE #31154: second Googledrive does not open window to authenticate
### Steps to reproduce
1. Add Google drive as in the instructions
2. 
3.

### Expected behaviour
when pressing "sta toegang toe" (allow access) 
i expect to get a google sheet where the site requests access.

### Actual behaviour
nothing get a red square in frond of the drive name

### Server configuration
**Operating system**: Ubuntu server 16.04.4 LTS

**Web server:**  Apache2

**Database:** MySQL

**PHP version:** 7

**ownCloud version:** (see ownCloud admin page)
10.0.7 stable

**Updated from an older ownCloud or fresh install:**
Fresh with 
https://doc.owncloud.org/server/latest/admin_manual/installation/source_installation.html

**Where did you install ownCloud from:** apt-get

**Signing status (ownCloud 9.0 and above):** ?

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
https://op6sie.myqnapcloud.com/owncloud/index.php/settings/integrity/failed
No errors have been found.

**The content of config/config.php:**

[config_report_20180416.zip](https://github.com/owncloud/core/files/1917632/config_report_20180416.zip)

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```
root@owncloud:/var/www/owncloud# sudo -u www-data php ./occ app:list
Enabled:
  - audioplayer: 2.2.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_external_dropbox: 1.0.1
  - files_pdfviewer: 0.8.2
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.2.3
  - notifications: 0.3.2
  - ownbackup: 17.7.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - tasks: 0.9.6
  - templateeditor: 0.3
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_sharing
  - theme-example
  - user_external

**Are you using external storage, if yes which one:** local/smb/sftp/...
**Are you using encryption:** no
**Are you using an external user-backend, no

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 7/Ubuntu Desktop 16.04.4 LTS

Please tell me where to find the logs.
owncloud log has been found but unclear if there is sencitive data in?

Cheers Tonny

### LINKED ISSUE #31497: Google Drive external js fix
Owncloud 10 has an issue with Google drive external storage.
This issue are not appear in current gdrive git branch (global handler), but present in current version.
oauth2_step1 and step2 handlers are always registering to the first container. It must be added locally to the selecting tr.

Something like this one:
$(document).ready(function() {
	var backendId = 'googledrive';
	var backendUrl = OC.generateUrl('apps/files_external/ajax/oauth2.php');

	function generateUrl($tr) {
		// no mapping between client ID and Google 'project', so we always load the same URL
		return 'https://console.developers.google.com/';
	}

	OCA.External.Settings.mountConfig.whenSelectBackend(function($tr, backend, onCompletion) {
		if (backend === backendId) {
			var backendEl = $tr.find('.backend');
			var el = $(document.createElement('a'))
				.attr('href', generateUrl($tr))
				.attr('target', '_blank')
				.attr('title', t('files_external', 'Google Drive App Configuration'))
				.addClass('icon-settings svg')
			;
			el.on('click', function(event) {
				var a = $(event.target);
				a.attr('href', generateUrl($(this).closest('tr')));
			});
			el.tooltip({placement: 'top'});
			backendEl.append(el);
	/**
	 * ------- OAUTH2 Events ----------
	 * 
	 * The files_external_{backendId} app's CUSTOM JS should handle the OAuth2 events itself
	 * instead on relying on the core for the implemention. These two functions
	 * [1] OCA.External.Settings.OAuth2.getAuthUrl, [2] OCA.External.Settings.OAuth2.verifyCode
	 * abstract away the details of sending the request to backend for getting the AuthURL or
	 * verifying the code, mounting the storage config etc
	 */
	$tr.find('.configuration').unbind('oauth_step1').on('oauth_step1', function (event, data) {
		if (data['backend_id'] !== backendId) {
			return;	// means the trigger is not for this storage adapter
		}

		// Redirects the User on success else displays an alert (with error message sent by backend)
		OCA.External.Settings.OAuth2.getAuthUrl(backendUrl, data);
	});

	$tr.find('.configuration').unbind('oauth_step2').on('oauth_step2', function (event, data) {
		if (data['backend_id'] !== backendId || data['code'] === undefined) {
			return;		// means the trigger is not for this OAuth2 grant
		}

		OCA.External.Settings.OAuth2.verifyCode(backendUrl, data)
		.fail(function (message) {
			OC.dialogs.alert(message,
				t('files_external', 'Error verifying OAuth2 Code for ' + backendId)
			);
		})
	});

		}
	});

});

### PR DESCRIPTION
**Pull request by karakayasemi**
## Description
- Fixes bug on multiple gdrive account addition
- As @Lirein explained in https://github.com/owncloud/core/issues/31497#issue-325256774. currently `oauth2_step1` and `oauth_step2` handlers are always registering for the first container in `gdrive.js`. I moved them inside of `whenSelectBackend` event and registered each of them separately.

@op6sie, @Lirein please test if you available.

## Related Issue
fixes #31154 , fixes #31497

## Motivation and Context
Fixing bugs.

## How Has This Been Tested?
Try to add multiple gdrive external storage. It should work.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open Tasks:
- [x] Port to files_external_gdrive app

### CODE REVIEW

**Comment by karakayasemi** [comment]
@PVince81 as far as I understand, I should open a PR to master for the change in `apps/files_external/js/settings.js`. Also, I should port `gdrive.js` change to files_external_gdrive app. Is there any mistake?

File: apps/files_external/js/settings.js [hunk 1]
```diff
@@ -1132,7 +1132,10 @@ MountConfigListView.prototype = _.extend({
 					classOptions[parameter] = false;
 				}
 			} else {
-				classOptions[parameter] = $(input).val();
+				classOptions[parameter] = 'false';
+				if($(input).val()) {
```
Comment (karakayasemi) [inline apps/files_external/js/settings.js]: When the client side sent a parameter as null, the server is throwing `Http::STATUS_UNPROCESSABLE_ENTITY` exception. This change fixes it.

**Comment by karakayasemi** [comment]
something failed in js tests. I will look at it.

**Comment by karakayasemi** [comment]
@ownclouders rebase

**Comment by jvillafanez** [comment]
This requires careful testing and I don't think I have the environment to test this PR.
I'm particularly worried about when the events are triggered and whether the listeners will be ready to run. It might be possible that the events are triggered but the listeners aren't registered yet, and this will cause problems.

I'll skip my worries about optimization since they're probably quite small (we might be assigning different function instances for each storage, increasing memory usage), and I'm not a js expert, so we can ignore those.

The code looks fine, but I don't know if it works in all the possible scenarios.

**Comment by karakayasemi** [comment]
Since I only changed gdrive.js, I do not expect any regression in the other external storage providers. 
I tested changes manually with the following scenarios, all of that worked;
- Add single gdrive account. (no regression, working with current stable10 also)
- Add multiple gdrive accounts. (Not working with current stable10)
- Firstly, add an external owncloud storage and secondly add a gdrive account (Not working with current stable10)
- Firstly, add a gdrive account and secondly add an external owncloud storage. (no regression, working with current stable10 also)

**Comment by jvillafanez** [comment]
Any guarantee about the loading order of the gdrive.js and settings.js files? If there is no guarantee that the files will be loaded in a specific order, I'm not sure if there could be problems.

**Comment by jvillafanez** [comment]
I'm not sure 100% about this, but I guess the process goes as described below:
1. setting.js from files_external are always loaded first, then each custom js file added by the backend and then the ones added by the authentication mechanism.
2. As consequence, I expect the "document ready" function from the settings.js is executed before the ones from the backends (it has been registered first).
3. This means that the loadStorages function is called *before* the backends have given a chance to register their callbacks.

The reason this is working is because the "selectBackend" event, which is the one the backend is registering for with the "whenSelectBackend", is triggered in the "newStorage" function which is called as a success callback for an ajax call during the "loadStorage".
I suspect this callback (and probably any other) won't be executed until all the registered "document ready" functions finish, which means that the "whenSelectBackend" callbacks will be registered by that time.

Quite a difficult explanation to answer my question on https://github.com/owncloud/core/pull/34987#issuecomment-482471091

**Comment by jvillafanez** [comment]
@karakayasemi in case of multiple gdrive accounts, could you doble-check that there is only one request being made to the backend for the oauth events?

File: apps/files_external/js/gdrive.js [hunk 2]
```diff
@@ -22,38 +22,37 @@ $(document).ready(function() {
...
-	/**
-	 * ------- OAUTH2 Events ----------
-	 * 
-	 * The files_external_{backendId} app's CUSTOM JS should handle the OAuth2 events itself
-	 * instead on relying on the core for the implemention. These two functions
-	 * [1] OCA.External.Settings.OAuth2.getAuthUrl, [2] OCA.External.Settings.OAuth2.verifyCode
-	 * abstract away the details of sending the request to backend for getting the AuthURL or
-	 * verifying the code, mounting the storage config etc
-	 */
-	$('.configuration').on('oauth_step1', function (event, data) {
```
Comment (karakayasemi) [inline apps/files_external/js/gdrive.js]: Actually, the old code is registering listeners when `document.ready()` for all `.configuration` class elements. Whenever `oauth_step1` event triggered, all `.configuration` class elements are receiving this event and the below line (backend_id check) is preventing multiple ouath requests.
The problem here is new <tr> elements are not listening `oauth_step1` event, because of that grant access button is only working for elements that rendered before `document.ready()`

File: apps/files_external/js/gdrive.js [hunk 3]
```diff
@@ -22,38 +22,37 @@ $(document).ready(function() {
...
+			/**
+			 * ------- OAUTH2 Events ----------
+			 *
+			 * The files_external_{backendId} app's CUSTOM JS should handle the OAuth2 events itself
+			 * instead on relying on the core for the implemention. These two functions
+			 * [1] OCA.External.Settings.OAuth2.getAuthUrl, [2] OCA.External.Settings.OAuth2.verifyCode
+			 * abstract away the details of sending the request to backend for getting the AuthURL or
+			 * verifying the code, mounting the storage config etc
+			 */
+			$tr.find('.configuration').on('oauth_step1', function (event, data) {
```
Comment (karakayasemi) [inline apps/files_external/js/gdrive.js]: With this PR, we are registering `oauth_step` events for only related`<tr>` element when user select backend. IMHO, this way is safer than previous.

**Comment by karakayasemi** [comment]
Yes, I tried one more time with adding 5 gdrive accounts, oauth events only triggered for related `<tr> ` element. I added comments on the code to explain details from my perspective.
I have not much experience with jquery also. I may be wrong.

**Review by jvillafanez — APPROVED** [review]

**Comment by phil-davis** [comment]
I  do not see this in `10.2` or `10.2.1`. I  think it got merged to `stable10` just after the `release-10.2` branch was created, and so it is not yet in any release. So it will end up in `10.3`
