### PR TITLE
Trim path in changeLock

### LINKED ISSUE #16896: [Experimental files locking] Uploading files from a federated server to a locked folder returns 500
### Steps to reproduce

Having two servers 'serverA' and 'serverB' with experimental files locking enabled do:

1. Enable external storage app in 'serverA'.
2. Mount a SFTP folder.
3. Inside 'SFTP' create a folder 'SUBDIR'.
4. Use federated sharing to share 'SUBDIR' with 'admin' in 'serverB'.
5. Upload a 50MiB file in 'SUBDIR'.
6. Open 'serverB' and accept the federated folder.
7. (Using webdav or web ui) Delete 'SUBDIR'.
8. (Using webdav) Upload a small file from 'serverB'

### Expected behaviour
'serverB' gets an error 423 about locked folder.

### Actual behaviour
'serverB' gets 500 Internal server error when trying to upload.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Experimental files locking.
External storage.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
SFTP.

**Are you using encryption:** 
No.

**Logs**
```

```

### Client configuration

**browser**
Chrome 43
**webdav**
Cadaver

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/16896

@icewind1991 @SergioBertolinSG 
- [ ] TODO: add unit test

### CODE REVIEW

**Comment by nickvergessen** [comment]
mind changing `$path = rtrim($path, '/');` in `unlockFile` as well?
I think it would be nice if they are all the same.

Will have a look at that and unit tests after lunch.

**Comment by PVince81** [comment]
I changed the approach, please have a look.

Need to take some time to fix the new unit test

**Comment by icewind1991** [comment]
I dont think we need it in `unlockPath`/`lockPath` since those are called from `(un)lockFile` where that path is already normalized

:+1: otherwise

**Comment by PVince81** [comment]
>I dont think we need it in unlockPath/lockPath since those are called from (un)lockFile where that path is already normalized

That's what I thought at first, but then I thought what happens if someone suddenly decides to call these functions directly... so decided to be defensive here.

File: tests/lib/files/view.php [hunk 1]
```diff
@@ -1169,4 +1169,21 @@ public function dataLockPaths() {
...
 	}
+
+	public function testChangeLock() {
+		$view = new \OC\Files\View('/testuser/files/');
+
+		$view->lockFile('/test/sub', ILockingProvider::LOCK_SHARED);
+		$this->assertTrue($this->isFileLocked($view, '/test//sub', ILockingProvider::LOCK_SHARED));
+		$this->assertFalse($this->isFileLocked($view, '/test//sub', ILockingProvider::LOCK_EXCLUSIVE));
+
+		$view->changeLock('//test/sub', ILockingProvider::LOCK_EXCLUSIVE);
```
Comment (nickvergessen) [inline tests/lib/files/view.php]: test without leading slash?

File: lib/private/files/view.php [hunk 2]
```diff
@@ -1681,6 +1681,7 @@ private function getParents($path) {
 	 */
 	private function lockPath($path, $type) {
 		$absolutePath = $this->getAbsolutePath($path);
+		$absolutePath = Filesystem::normalizePath($absolutePath);
 		if (!$this->shouldLockFile($absolutePath)) {
 			return false;
 		}
```
Comment (nickvergessen) [inline lib/private/files/view.php]: Should
```
		$absolutePath = $this->getAbsolutePath($path);
		$absolutePath = Filesystem::normalizePath($absolutePath);
		if (!$this->shouldLockFile($absolutePath)) {
			return false;
		}
```

be it's one method, since all 5 methods share the code?

**Comment by nickvergessen** [comment]
> That's what I thought at first, but then I thought what happens if someone suddenly decides to call these functions directly... so decided to be defensive here.

I had the same thoughts when I introduced the `shouldLockFile` method ;)

File: lib/private/files/view.php (hunk 2 above)
Comment (PVince81) [inline lib/private/files/view.php]: Semantically, no. What would the method be called ?
I'd rather keep it as is for now.

**Comment by PVince81** [comment]
Will fix the unit tests to get this merged, seems this PR blocks a lot of things.

**Comment by PVince81** [comment]
I fixed the tests then squashed. Please rereview

**Comment by nickvergessen** [comment]
Needs rebase due to the other PR we merged?

**Comment by PVince81** [comment]
Rebased again.

@nickvergessen told me he approved this PR, counting as :+1:

**Comment by PVince81** [comment]
Here we go again, Jenkins PR https://github.com/owncloud/core/pull/16971
