### PR TITLE
Properly handle deleted users in UserMountCache

### LINKED ISSUE #27012: Error while posting comment in web view
### Steps to reproduce
1. user selects file in shared folder owned by xyz 
2. enters comment and presses post comment

### Expected behaviour
comment should be posted

### Actual behaviour
error occurs while posting comment

oC 9.1.3 EEe

### Server configuration
**Operating system**:
RHEL 7.2
**Web server:**
apache 2.4
**Database:**
mariadb

Browsers:
Chrome / Firefox / IE Edge

log file content:
```
Exception: {
"Exception":"TypeError","Message":"Argument 1 passed to OC\\Files\\Config\\CachedMountInfo::__construct() must implement interface OCP\\IUser, null given, called in \/var\/www\/html\/owncloud-9.1.3\/lib\/private\/Files\/Config\/UserMountCache.php on line 173",
"Code":0,
"Trace":"
#0 \/var\/www\/html\/owncloud-9.1.3\/lib\/private\/Files\/Config\/UserMountCache.php(173): OC\\Files\\Config\\CachedMountInfo->__construct(NULL, 6, 1829, '\/user1\/files\/...')
#1 [internal function]: OC\\Files\\Config\\UserMountCache->dbRowToMountInfo(Array)
#2 \/var\/www\/html\/owncloud-9.1.3\/lib\/private\/Files\/Config\/UserMountCache.php(206): array_map(Array, Array)
#3 \/var\/www\/html\/owncloud-9.1.3\/lib\/private\/Files\/Config\/UserMountCache.php(260): OC\\Files\\Config\\UserMountCache->getMountsForStorageId(6)
#4 \/var\/www\/html\/owncloud-9.1.3\/apps\/comments\/lib\/Activity\/Listener.php(80): OC\\Files\\Config\\UserMountCache->getMountsForFileId('20675')
#5 \/var\/www\/html\/owncloud-9.1.3\/apps\/comments\/appinfo\/app.php(50): OCA\\Comments\\Activity\\Listener->commentEvent(Object(OCP\\Comments\\CommentsEvent))
#6 [internal function]: OC_App::{closure}(Object(OCP\\Comments\\CommentsEvent), 'OCP\\\\Comments\\\\IC...', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))
#7 \/var\/www\/html\/owncloud-9.1.3\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php(181): call_user_func(Object(Closure), Object(OCP\\Comments\\CommentsEvent), 'OCP\\\\Comments\\\\IC...', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))
#8 \/var\/www\/html\/owncloud-9.1.3\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php(46): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'OCP\\\\Comments\\\\IC...', Object(OCP\\Comments\\CommentsEvent))
#9 \/var\/www\/html\/owncloud-9.1.3\/lib\/private\/Comments\/Manager.php(530): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('OCP\\\\Comments\\\\IC...', Object(OCP\\Comments\\CommentsEvent))
#10 \/var\/www\/html\/owncloud-9.1.3\/lib\/private\/Comments\/Manager.php(484): OC\\Comments\\Manager->insert(Object(OC\\Comments\\Comment))
#11 \/var\/www\/html\/owncloud-9.1.3\/apps\/dav\/lib\/Comments\/CommentsPlugin.php(243): OC\\Comments\\Manager->save(Object(OC\\Comments\\Comment))
#12 \/var\/www\/html\/owncloud-9.1.3\/apps\/dav\/lib\/Comments\/CommentsPlugin.php(119): OCA\\DAV\\Comments\\CommentsPlugin->createComment('files', '20675', Array, 'application\/jso...')
#13 [internal function]: OCA\\DAV\\Comments\\CommentsPlugin->httpPost(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
#14 \/var\/www\/html\/owncloud-9.1.3\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#15 \/var\/www\/html\/owncloud-9.1.3\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:POST', Array)
#16 \/var\/www\/html\/owncloud-9.1.3\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
#17 \/var\/www\/html\/owncloud-9.1.3\/apps\/dav\/lib\/Server.php(178): Sabre\\DAV\\Server->exec()
#18 \/var\/www\/html\/owncloud-9.1.3\/apps\/dav\/appinfo\/v2\/remote.php(29): OCA\\DAV\\Server->exec()
#19 \/var\/www\/html\/owncloud-9.1.3\/remote.php(164): require_once('\/var\/www\/html\/o...')
#20 {main}","File":"\/var\/www\/html\/owncloud-9.1.3\/lib\/private\/Files\/Config\/CachedMountInfo.php","Line":58}
```

The funny thing is, if the page gets reloaded, the comment appears successfully!

@butonic managed to mitigate the issue with a patch:
```
Index: lib/private/Files/Config/UserMountCache.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/private/Files/Config/UserMountCache.php	(revision )
+++ lib/private/Files/Config/UserMountCache.php	(revision )
@@ -170,6 +170,10 @@
 
 	private function dbRowToMountInfo(array $row) {
 		$user = $this->userManager->get($row['user_id']);
+		if($user === null) {
+			$this->logger->warning("User '{$row['user_id']}' not found by UserManager, faking User object");
+			$user = new \OC\User\User($row['user_id'], null);
+		}
 		return new CachedMountInfo($user, (int)$row['storage_id'], (int)$row['root_id'], $row['mount_point']);
 	}
 
```

### Tasks

- [ ] reproduce the issue locally
- [ ] write an integration test to reproduce this, if possible
- [ ] make a PR with the patch + unit tests

### PR DESCRIPTION
**Pull request by PVince81**
## Description
When encountering entries from a deleted user, discard such entries.

## Related Issue
Fixes https://github.com/owncloud/core/issues/27012

## How Has This Been Tested?
https://github.com/owncloud/core/issues/27012#issuecomment-275088061

Comments can be posted and no exceptions after the fix.
Also, the bogus entries with "unexist" are removed from `oc_mounts`.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Please review @butonic @jvillafanez @IljaN @VicDeo

### CODE REVIEW

**Comment by PVince81** [comment]
Testes passed on Jenkins

File: lib/private/Files/Config/UserMountCache.php [hunk 1]
```diff
@@ -170,10 +170,35 @@ private function removeFromCache(ICachedMountInfo $mount) {
 
 	private function dbRowToMountInfo(array $row) {
 		$user = $this->userManager->get($row['user_id']);
+		if ($user === null) {
+			// user does not exist any more, delete all mounts of that user directly
```
Comment (jvillafanez) [inline lib/private/Files/Config/UserMountCache.php]: This feels misplaced. I'm talking strictly about the code, not the behaviour. I'd expect the function to convert the row, not to delete things.

Maybe adding a private function `deleteSharesOfMissingUser` or similar, and move it to the `getMountsForUser` function just before starting the conversion might look better.

Comment (PVince81) [inline lib/private/Files/Config/UserMountCache.php]: The bug in question was from yet another code path using `dbRowToMountInfo`.

Another alternative would be to use a repair step I guess.

Comment (jvillafanez) [inline lib/private/Files/Config/UserMountCache.php]: I don't like to use a repair step for this because this could happen often and we can't keep on repairing over and over.

I don't have better alternative, so let's say "this is private stuff" 😄

**Comment by jvillafanez** [comment]
👍

**Comment by PVince81** [comment]
Maybe some day we'll use foreign keys and it will all be the job of cascading delete...

**Comment by PVince81** [comment]
Tests pass on Jenkins, results unpublished.

**Comment by PVince81** [comment]
I'll take care of the backports after the freeze.

**Comment by PVince81** [comment]
stable9.1: https://github.com/owncloud/core/pull/27488
stable9: https://github.com/owncloud/core/issues/27489
