### PR TITLE
Make sure to init the users Filesystem so we can add group shares

### LINKED ISSUE #20663: command line occ add user group issue
Having a problem when adding a user via command line
command 'occ user:add --password-from-env --display-name="name" --group="group1" new_uid'

When the command is run to add a user and the group does not exists, it works perfectly. 
When the command is run to add a user and the group exists, but has no shares, it works perfectly.
When the command is run to add a user and the group exists, but has files / folders shared to the group it adds the user, but exits with error

PHP Fatal error: Call to a member function file_exists() on null in /var/www/owncloud/lib/private/files/filesystem.php on line 688

User is created, but not added to any groups

This is running on Debian 7.9 and php 5.6. I have tested both OC 8.1.4 and 8.2.1

Both fail with the same error.

Thoughts?

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #20663 

@rullzer @PVince81 @itmands 

@karlitschek maybe we can backport this to 8.2 where the command was added.

### CODE REVIEW

File: core/command/user/add.php [hunk 1]
```diff
@@ -131,7 +132,15 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 			$output->writeln('Display name set to "' . $user->getDisplayName() . '"');
 		}
 
-		foreach ($input->getOption('group') as $groupName) {
+		$groups = $input->getOption('group');
+
+		if (!empty($groups)) {
+			// Make sure we init the Filesystem for the user, in case we need to
+			// init some group shares.
+			Filesystem::init($user->getUID(), '');
```
Comment (PVince81) [inline core/command/user/add.php]: or use `\OC::$server->getUserFolder()` ? I think it does that too and is public API.

Comment (PVince81) [inline core/command/user/add.php]: but that one will also init the user's skeleton files, so needs proper testing with encryption

Comment (nickvergessen) [inline core/command/user/add.php]: I had that first, but no it doesn't do what is needed.
We need `Filesystem::init()` because `Filesystem::file_exists()` is called, which calls it on the `$defaultInstance` view. But that is not set until `Filesystem::init()` and therefor throws:
```
PHP Fatal error:  Call to a member function file_exists() on a non-object in /home/nickv/ownCloud/master/core/lib/private/files/filesystem.php on line 693
```
`getUserFolder` only calls `\OC\Files\Filesystem::initMountPoints($userId)`, but that does not init the view.

**Comment by karlitschek** [comment]
good catch. please backport

**Comment by rullzer** [comment]
:+1: makes sense and I did not manage to break it yet..
Thanks for fixing :)

**Comment by nickvergessen** [comment]
@PVince81 final review?

**Comment by PVince81** [comment]
:+1:

**Comment by MorrisJobke** [comment]
> @karlitschek maybe we can backport this to 8.2 where the command was added.

@nickvergessen Could I ask you to prepare the backport PR?
