### PR TITLE
Fix read-only cache

### LINKED ISSUE #15551: nodeExists always returns true for files coming from shared folder from federated clouds
### Env
Master or oC8, PHP 5.5
2 oC instances on the same server

### Steps to reproduce
* Share **read-only** folder on oC1 **which is running oC 8.0**
* Attach share folder to oC2
* Launch a script on oC2 which tests the presence of a specific file **which doesn't exist** on oC1

Log the result like this
```
$this->logger->debug("Folder: {path}", ['path' => $folder->getPath()]);
$this->logger->debug("nodeExists : {test}", ['test' => $folder->nodeExists('CallMeSartre')]);
```

### Expected result
```
Folder: \/demo1\/files\/Shared from oC1
nodeExists : false
```

### Actual result
```
Folder: \/demo1\/files\/Shared from oC1
nodeExists : true
```

The same test works perfectly well on local folders.

### Logs
This is from the sharing server on oC8.0

```
"Undefined index: permissions at \/apps\/files_sharing\/lib\/readonlycache.php#16"
"Undefined index: storage_mtime at \/lib\/private\/files\/cache\/watcher.php#67"
"Undefined index: permissions at \/apps\/files_sharing\/lib\/readonlycache.php#16"
"Undefined index: fileid at \/lib\/private\/files\/cache\/cache.php#378"
"Undefined index: mimetype at \/lib\/private\/files\/cache\/cache.php#379"
"Undefined index: mimetype at \/lib\/private\/files\/cache\/watcher.php#73"
"Undefined index: permissions at \/apps\/files_sharing\/lib\/readonlycache.php#16"
"Undefined index: permissions at \/apps\/files_sharing\/lib\/readonlycache.php#16"
"Undefined index: mimetype at \/lib\/private\/files\/fileinfo.php#106"
"Undefined index: fileid at \/lib\/private\/files\/fileinfo.php#99"
"Undefined index: mimetype at \/lib\/private\/files\/fileinfo.php#106"
"Undefined index: etag at \/lib\/private\/files\/fileinfo.php#127"
```

### PR DESCRIPTION
**Pull request by oparoz**
Most methods which ask for a cache entry don't explicitly check if the result === false and will happily try to use whatever the cache is sending them.

The problem is that if a share is in read-only mode, all answers to queries about a file or folder's existence will be unreliable: the cache always returns an array which will be interpreted as a valid cache result.

This PR only fixes the result returned by the read-only cache.

Fixes #15551

@icewind1991 @PVince81 @nickvergessen

### CODE REVIEW

**Comment by nickvergessen** [comment]
This should have a test case

**Comment by oparoz** [comment]
I agree, but this is going to have to be written by a oC storage expert as I'm done wasting time on this.

**Comment by karlitschek** [comment]
@icewind1991 what do you think?

File: apps/files_sharing/tests/readonlycache.php [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
+ * GNU Affero General Public License for more details.
+ *
+ * You should have received a copy of the GNU Affero General Public License, version 3,
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>
+ *
+ */
+use OCA\Files_sharing\Tests\TestCase;
+
+class Test_Files_Sharing_ReadOnly_Cache extends TestCase {
```
Comment (nickvergessen) [inline apps/files_sharing/tests/readonlycache.php]: Please use namespace `OCA\Files_sharing\Tests` and the class name should then match the filename (apart from uppercase)

File: apps/files_sharing/tests/readonlycache.php [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+ * This program is distributed in the hope that it will be useful,
+ * but WITHOUT ANY WARRANTY; without even the implied warranty of
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
+ * GNU Affero General Public License for more details.
+ *
+ * You should have received a copy of the GNU Affero General Public License, version 3,
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>
+ *
+ */
+use OCA\Files_sharing\Tests\TestCase;
```
Comment (nickvergessen) [inline apps/files_sharing/tests/readonlycache.php]: This can be dropped, when you use the right namespace for this file

File: apps/files_sharing/tests/readonlycache.php [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+		$this->loader = new \OC\Files\Storage\StorageFactory();
+		$this->readOnlyMount = new \OC\Files\Mount\MountPoint($this->storage,
+			'/readonly', [[]], $this->loader);
+		$this->readOnlyStorage = $this->loader->getInstance($this->readOnlyMount,
+			'\OCA\Files_Sharing\ReadOnlyWrapper', ['storage' => $this->storage]);
+
+		$this->readOnlyCache = $this->readOnlyStorage->getCache();
+	}
+
+	protected function tearDown() {
```
Comment (nickvergessen) [inline apps/files_sharing/tests/readonlycache.php]: just drop this method, when you only call parent

File: apps/files_sharing/tests/readonlycache.php [hunk 4]
```diff
@@ -0,0 +1,105 @@
...
+		$this->assertFalse($this->readOnlyStorage->unlink('files/readonly/foo.txt'));
+		$this->assertTrue($this->readOnlyStorage->file_exists('files/readonly/foo.txt'));
+
+		$this->assertInstanceOf('\OCA\Files_Sharing\ReadOnlyCache', $this->readOnlyCache);
+	}
+
+	public function testGet() {
+		$result = $this->readOnlyCache->get('files/readonly/foo.txt');
+		$this->assertNotEmpty($result);
+
```
Comment (nickvergessen) [inline apps/files_sharing/tests/readonlycache.php]: split into two tests please, so they can fail both in one test run

File: apps/files_sharing/tests/readonlycache.php [hunk 5]
```diff
@@ -0,0 +1,105 @@
...
+	}
+
+	public function testGetFolderContents() {
+		$results = $this->readOnlyCache->getFolderContents('files/readonly');
+		$this->assertNotEmpty($results);
+
+		foreach ($results as $result) {
+			$this->assertNotEmpty($result);
+		}
+
```
Comment (nickvergessen) [inline apps/files_sharing/tests/readonlycache.php]: same here, please use two methods

**Comment by PVince81** [comment]
I retested server to server share and it still works properly (both "add to ownCloud" and remote shares), tested with files/folders combined with read-only and read-write permissions.
After unsharing, PROPFIND properly returns 404

:+1:

**Comment by karlitschek** [comment]
:+1:

File: apps/files_sharing/tests/readonlycache.php (hunk 4 above)
Comment (oparoz) [inline apps/files_sharing/tests/readonlycache.php]: OK, will do

File: apps/files_sharing/tests/readonlycache.php (hunk 5 above)
Comment (oparoz) [inline apps/files_sharing/tests/readonlycache.php]: OK, will do

File: apps/files_sharing/tests/readonlycache.php (hunk 1 above)
Comment (oparoz) [inline apps/files_sharing/tests/readonlycache.php]: OK, but will post a technical debt ticket because most are using this scheme
```
Test_Files_Sharing	18 sec	0		0		20		20	
Test_Files_Sharing_Api	1 min 29 sec	0		0		104		104	
Test_Files_Sharing_Backend	5.9 sec	0		0		4		4	
Test_Files_Sharing_Cache	1 min 0 sec	0		0		36		36	
Test_Files_Sharing_External_Storage::testStorageMountOptions	84 ms	0		0		24		24	
Test_Files_Sharing_Helper	1 sec	0		0		4		4	
Test_Files_Sharing_Mount	13 sec	0		0		16		16	
Test_Files_Sharing_Mount::testStripUserFilesPath	11 sec	0		0		24		24	
Test_Files_Sharing_Permissions	9.9 sec	0		0		8		8	
Test_Files_Sharing_ReadOnly_Cache	2.3 sec	0		0		12	+12	12	+12
Test_Files_Sharing_S2S_OCS_API	1.1 sec	0		0		8		8	
Test_Files_Sharing_S2S_OCS_API::testDeleteUser	1.5 sec	0		0		16		16	
Test_Files_Sharing_Storage	38 sec	0		0		44		44	
Test_Files_Sharing_Updater	16 sec	0		0		20		20	
Test_Files_Sharing_Watcher	7 sec	0		0		8		8	
Test_Files_Sharing::testFileSharePermissions
```

Comment (nickvergessen) [inline apps/files_sharing/tests/readonlycache.php]: They shouldn't and they will be updated when they are touched majorly anyway.

File: apps/files_sharing/tests/readonlycache.php [hunk 6]
```diff
@@ -0,0 +1,105 @@
...
+ * You should have received a copy of the GNU Affero General Public License, version 3,
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>
+ *
+ */
+namespace OCA\Files_Sharing\Tests;
+
+class ReadOnlyCache extends TestCase {
+
+	/**
+	 * @type \OC\Files\Storage\Storage
```
Comment (nickvergessen) [inline apps/files_sharing/tests/readonlycache.php]: Should be `@var` instead of type. (*sorry didn't see that in the beginning*)
You can also reduce this to one line, btw.
```php
/** @var \OC\Files\Storage\Storage */
protected $storage;

File: apps/files_sharing/tests/readonlycache.php [hunk 7]
```diff
@@ -0,0 +1,105 @@
...
+
+	/**
+	 * @type \OC\Files\Cache\Cache
+	 */
+	protected $readOnlyCache;
+
+	protected function setUp() {
+		parent::setUp();
+
+		//error_reporting(E_ERROR | E_PARSE);
```
Comment (nickvergessen) [inline apps/files_sharing/tests/readonlycache.php]: remove?

File: apps/files_sharing/tests/readonlycache.php (hunk 6 above)
Comment (oparoz) [inline apps/files_sharing/tests/readonlycache.php]: Hmmm... @var was deprecated and replaced by @type, but it seems they backtracked and I missed the memo:
https://github.com/phpDocumentor/fig-standards/commit/61c695c43d1b2c713acbfb3302f284c518421bc5

Will update

File: apps/files_sharing/tests/readonlycache.php (hunk 7 above)
Comment (oparoz) [inline apps/files_sharing/tests/readonlycache.php]: Yes, it was there so that you could see the before/after effect

**Comment by oparoz** [comment]
Squashed the cosmetic changes into the last commit

**Comment by oparoz** [comment]
What about the backport request? Without it, it means s2s only works reliably if you attach a share from a v8.1+ oC instance.

**Comment by MorrisJobke** [comment]
@karlitschek Should this be backported?

**Comment by MorrisJobke** [comment]
@karlitschek ping

**Comment by karlitschek** [comment]
Backport is fine after the next stable releases are out :-)

**Comment by MorrisJobke** [comment]
The readOnlyCache was removed with #15814, which utself was backported to 7.0.6 and 8.0.4 -> therefore this fix is not needed anymore in the stable versions

**Comment by oparoz** [comment]
I've just tested and it works as expected. Cool :)
