### PR TITLE
Exclude DAV CORS handling for non-browsers

### LINKED ISSUE #29793: Owncloud 10.0.4.4 DavFS issue
### Steps to reproduce
1. Upgrade to owncloud 10.0.4
2. Try to mount a davfs share

### Expected behaviour
The Share should be mounted

### Actual behaviour
/sbin/mount.davfs: mounting failed; the server does not support WebDAV

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** mysql 5.7

**PHP version:** 5.6

**ownCloud version:** (see ownCloud admin page) 10.0.4.4

**Updated from an older ownCloud or fresh install:** Updated from 10.0.3.3

**Where did you install ownCloud from:** from repo download.owncloud.org/download/repositories/stable/Ubuntu_16.04/ 

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.

```

**The content of config/config.php:**

```
{
    "system": {
        "forcessl": true,
        "installed": true,
        "dbtype": "mysql",
        "dbname": "owncloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "",
        "overwriteprotocol": "",
        "theme": "",
        "3rdpartyroot": "",
        "3rdpartyurl": "",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "knowledgebaseurl": "http:\/\/api.apps.owncloud.com\/v1",
        "appstoreenabled": true,
        "mail_smtpmode": "sendmail",
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": 25,
        "mail_smtpauth": false,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "appcodechecker": "",
        "updatechecker": false,
        "logtimezone": "Europe\/Zurich",
        "logfile": "\/var\/log\/owncloud.log",
        "loglevel": 0,
        "log_authfailip": true,
        "log_type": "owncloud",
        "log_query": false,
        "debug": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "instanceid": "513e28974df26",
        "datadirectory": "\/var\/www\/owncloud\/data",
        "version": "10.0.4.4",
        "maintenance": false,
        "trusted_domains": [
            "gland.netoxygen.ch",
            "ge.netoxygen.ch",
            "cloud.netoxygen.ch"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true
    }
}
```

**List of activated apps:**

```
Enabled:
  - calendar: 1.5.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.3
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.3
  - notifications: 0.3.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - theme-example
  - user_external
```

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** NO

### Client configuration
**Browser:** Davfs2

**Operating system:** Ubuntu 16.04

#### Web server error log
```
xxx.xxx.xxx:443 192.168.0.184 - - [07/Dec/2017:18:17:36 +0100] "OPTIONS /remote.php/webdav/ HTTP/1.1" 200 4378 "-" "davfs2/1.5.2 neon/0.30.1"
```

#### ownCloud log (data/owncloud.log)
```
Nothing is logged
```

I did a few tests and could detect some strange things.
I test to mount davfs from demo.ownloud.org and it works. But demo uses version 10.0.3.3 (a version on wich it was working for me before the upgrade).
Cadaver is working on my 10.0.4.4 owncloud but not davfs.
I did some tests using curl and can see that a simple curl to remote/webdav without autentication retunr a code 200 instead of a code 401

curl -D - -X OPTIONS  https:/xxx.xxx.xxx/remote.php/webdav/
```
HTTP/1.1 200 OK
Date: Thu, 07 Dec 2017 17:20:53 GMT
Server: Apache/2.4.18 (Ubuntu)
Set-Cookie: 513e28974df26=v4lef9aamd3vq82vnmseoeogr7; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=CNa9pkjoDLG4qfFuJKbAfqkw4u0cmDxHn48h8mynSofwD6KzHtpy%2FN3OvEoWPq8oAnPcipfIbRuxtEWO4m475nJgYW9RfdDTkbOxSasE5sjsFLqWdI7rRn%2B2uWwY%2BKAy; path=/; secure; httponly
Content-Security-Policy: default-src 'none';
Access-Control-Allow-Headers: authorization,OCS-APIREQUEST,Origin,X-Requested-With,Content-Type,Access-Control-Allow-Origin,X-OC-Mtime,OC-Checksum,OC-Total-Length,Depth,Destination,Overwrite
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,OPTIONS,POST,PUT,DELETE,MKCOL,PROPFIND,PATCH,PROPPATCH,REPORT,MOVE,COPY
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Content-Length: 0
Content-Type: text/html; charset=UTF-8
```
On demo
curl -D - -X OPTIONS  https://demo.owncloud.org/remote.php/webdav/
```
HTTP/1.1 401 Unauthorized
Cache-Control: no-store, no-cache, must-revalidate
Content-Length: 412
Content-Security-Policy: default-src 'none';
Content-Type: application/xml; charset=utf-8
Date: Thu, 07 Dec 2017 17:22:02 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Server: Apache
Set-Cookie: ocgj9l8b2hha=ncb9c78r10dng4mhuvsu4nbmj2; path=/; HttpOnly
Set-Cookie: oc_sessionPassphrase=VMe9TPNuHvzwpPdl8qTbsBHNcn2Xw0xAh9ZjQpAXDBU8917cvBLt2geLGuV%2B%2BmEdenAilycACi8%2B1fWBBMzr3MIpV62ygpVpV5uorCy7qhEMwwPjcNpZxIODZGQvmZg3; path=/; secure; HttpOnly
Strict-Transport-Security: max-age=15768000; preload
Www-Authenticate: Basic realm="ownCloud"
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: none
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured</s:message>
</d:error>`
```

It appears that davfs make a first OPTIONS call without authentication, waits for a 401 and then proceed to authentication.
Here are my davfs logs:
When connecting to my owncloud
```
Dec  7 18:23:51 dreis-desktop mount.davfs: davfs2 1.5.2
Dec  7 18:23:56 dreis-desktop mount.davfs: Initializing webdav
Dec  7 18:23:56 dreis-desktop mount.davfs: HTTP session to https://xxx.xxx.xxx:443 begins.
Dec  7 18:23:56 dreis-desktop mount.davfs: ah_create, for WWW-Authenticate
Dec  7 18:23:56 dreis-desktop mount.davfs: Running pre_send hooks
Dec  7 18:23:56 dreis-desktop mount.davfs: Sending request headers:#012OPTIONS /remote.php/webdav/ HTTP/1.1#015#012User-Agent: davfs2/1.5.2 neon/0.30.1#015#012Keep-Alive: #015#012Connection: TE, Keep-Alive#015#012TE: trailers#015#012Host: xxx.xxx.xxx
Dec  7 18:23:56 dreis-desktop mount.davfs: Sending request-line and headers:
Dec  7 18:23:56 dreis-desktop mount.davfs: Doing DNS lookup on xxx.xxx.xxx..
Dec  7 18:23:56 dreis-desktop mount.davfs: req: Connecting to 192.168.0.1:443
Dec  7 18:23:56 dreis-desktop mount.davfs: Request sent; retry is 0.
Dec  7 18:23:56 dreis-desktop mount.davfs: [status-line] < HTTP/1.1 200 OK
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] Date: Thu, 07 Dec 2017 17:23:56 GMT
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [date], Value: [Thu, 07 Dec 2017 17:23:56 GMT]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] Server: Apache/2.4.18 (Ubuntu)
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [server], Value: [Apache/2.4.18 (Ubuntu)]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] Set-Cookie: 513e28974df26=n3okeska5ece9ho3fnqrmf8o83; path=/; HttpOnly
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [set-cookie], Value: [513e28974df26=n3okeska5ece9ho3fnqrmf8o83; path=/; HttpOnly]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] Expires: Thu, 19 Nov 1981 08:52:00 GMT
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [expires], Value: [Thu, 19 Nov 1981 08:52:00 GMT]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [cache-control], Value: [no-store, no-cache, must-revalidate, post-check=0, pre-check=0]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] Pragma: no-cache
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [pragma], Value: [no-cache]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] Set-Cookie: oc_sessionPassphrase=FBhgCuRqIYjJ8B144mqsZapghFNcFokFFcOOKTNTPz5TDoQX5rW0%%2BonY3rkig4st6clqpHSpH3T%%2BYAXZEz8npZk46dqOp0e%%2BV2S4%%2F6Fcpi96KqWGsLCaHs83C6ACnpMY; path=/; secure; httponly
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [set-cookie], Value: [oc_sessionPassphrase=FBhgCuRqIYjJ8B144mqsZapghFNcFokFFcOOKTNTPz5TDoQX5rW0%%2BonY3rkig4st6clqpHSpH3T%%2BYAXZEz8npZk46dqOp0e%%2BV2S4%%2F6Fcpi96KqWGsLCaHs83C6ACnpMY; path=/; secure; httponly]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] Content-Security-Policy: default-src 'none';
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [content-security-policy], Value: [default-src 'none';]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] Access-Control-Allow-Headers: authorization,OCS-APIREQUEST,Origin,X-Requested-With,Content-Type,Access-Control-Allow-Origin,X-OC-Mtime,OC-Checksum,OC-Total-Length,Depth,Destination,Overwrite
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [access-control-allow-headers], Value: [authorization,OCS-APIREQUEST,Origin,X-Requested-With,Content-Type,Access-Control-Allow-Origin,X-OC-Mtime,OC-Checksum,OC-Total-Length,Depth,Destination,Overwrite]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] Access-Control-Allow-Origin: *
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [access-control-allow-origin], Value: [*]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] Access-Control-Allow-Methods: GET,OPTIONS,POST,PUT,DELETE,MKCOL,PROPFIND,PATCH,PROPPATCH,REPORT,MOVE,COPY
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [access-control-allow-methods], Value: [GET,OPTIONS,POST,PUT,DELETE,MKCOL,PROPFIND,PATCH,PROPPATCH,REPORT,MOVE,COPY]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] X-Content-Type-Options: nosniff
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [x-content-type-options], Value: [nosniff]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] X-XSS-Protection: 1; mode=block
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [x-xss-protection], Value: [1; mode=block]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] X-Robots-Tag: none
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [x-robots-tag], Value: [none]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] X-Frame-Options: SAMEORIGIN
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [x-frame-options], Value: [SAMEORIGIN]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] X-Download-Options: noopen
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [x-download-options], Value: [noopen]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] X-Permitted-Cross-Domain-Policies: none
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [x-permitted-cross-domain-policies], Value: [none]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] Content-Length: 0
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [content-length], Value: [0]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] Keep-Alive: timeout=5, max=100
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [keep-alive], Value: [timeout=5, max=100]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] Connection: Keep-Alive
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [connection], Value: [Keep-Alive]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr] Content-Type: text/html; charset=UTF-8
Dec  7 18:23:56 dreis-desktop mount.davfs: Header Name: [content-type], Value: [text/html; charset=UTF-8]
Dec  7 18:23:56 dreis-desktop mount.davfs: [hdr]
Dec  7 18:23:56 dreis-desktop mount.davfs: End of headers.
Dec  7 18:23:56 dreis-desktop mount.davfs: Running post_headers hooks
Dec  7 18:23:56 dreis-desktop mount.davfs: Running post_send hooks
Dec  7 18:23:56 dreis-desktop mount.davfs: ah_post_send (#0), code is 200 (want 401), WWW-Authenticate is (none)
Dec  7 18:23:56 dreis-desktop mount.davfs: Request ends, status 200 class 2xx, error line:#012200 OK
Dec  7 18:23:56 dreis-desktop mount.davfs: Running destroy hooks.
Dec  7 18:23:56 dreis-desktop mount.davfs: Request ends.
```

On demo.owncloud.org:
```
Dec  7 18:25:38 dreis-desktop mount.davfs: davfs2 1.5.2
Dec  7 18:25:41 dreis-desktop mount.davfs: Initializing webdav
Dec  7 18:25:41 dreis-desktop mount.davfs: HTTP session to https://demo.owncloud.org:443 begins.
Dec  7 18:25:41 dreis-desktop mount.davfs: ah_create, for WWW-Authenticate
Dec  7 18:25:41 dreis-desktop mount.davfs: Running pre_send hooks
Dec  7 18:25:41 dreis-desktop mount.davfs: Sending request headers:#012OPTIONS /remote.php/webdav/ HTTP/1.1#015#012User-Agent: davfs2/1.5.2 neon/0.30.1#015#012Keep-Alive: #015#012Connection: TE, Keep-Alive#015#012TE: trailers#015#012Host: demo.owncloud.org
Dec  7 18:25:41 dreis-desktop mount.davfs: Sending request-line and headers:
Dec  7 18:25:41 dreis-desktop mount.davfs: Doing DNS lookup on demo.owncloud.org...
Dec  7 18:25:41 dreis-desktop mount.davfs: req: Connecting to 136.243.60.151:443
Dec  7 18:25:41 dreis-desktop mount.davfs: Request sent; retry is 0.
Dec  7 18:25:41 dreis-desktop mount.davfs: [status-line] < HTTP/1.1 401 Unauthorized
Dec  7 18:25:41 dreis-desktop mount.davfs: [hdr] Cache-Control: no-store, no-cache, must-revalidate
Dec  7 18:25:41 dreis-desktop mount.davfs: Header Name: [cache-control], Value: [no-store, no-cache, must-revalidate]
Dec  7 18:25:41 dreis-desktop mount.davfs: [hdr] Content-Length: 412
Dec  7 18:25:41 dreis-desktop mount.davfs: Header Name: [content-length], Value: [412]
Dec  7 18:25:41 dreis-desktop mount.davfs: [hdr] Content-Security-Policy: default-src 'none';
Dec  7 18:25:41 dreis-desktop mount.davfs: Header Name: [content-security-policy], Value: [default-src 'none';]
Dec  7 18:25:41 dreis-desktop mount.davfs: [hdr] Content-Type: application/xml; charset=utf-8
Dec  7 18:25:41 dreis-desktop mount.davfs: Header Name: [content-type], Value: [application/xml; charset=utf-8]
Dec  7 18:25:41 dreis-desktop mount.davfs: [hdr] Date: Thu, 07 Dec 2017 17:25:41 GMT
Dec  7 18:25:41 dreis-desktop mount.davfs: Header Name: [date], Value: [Thu, 07 Dec 2017 17:25:41 GMT]
Dec  7 18:25:41 dreis-desktop mount.davfs: [hdr] Expires: Thu, 19 Nov 1981 08:52:00 GMT
Dec  7 18:25:41 dreis-desktop mount.davfs: Header Name: [expires], Value: [Thu, 19 Nov 1981 08:52:00 GMT]
Dec  7 18:25:41 dreis-desktop mount.davfs: [hdr] Pragma: no-cache
Dec  7 18:25:41 dreis-desktop mount.davfs: Header Name: [pragma], Value: [no-cache]
Dec  7 18:25:41 dreis-desktop mount.davfs: [hdr] Server: Apache
Dec  7 18:25:41 dreis-desktop mount.davfs: Header Name: [server], Value: [Apache]
Dec  7 18:25:41 dreis-desktop mount.davfs: [hdr] Set-Cookie: ocgj9l8b2hha=kegme5fuimqfo9bbkqb5inp4t6; path=/; HttpOnly
Dec  7 18:25:41 dreis-desktop mount.davfs: Header Name: [set-cookie], Value: [ocgj9l8b2hha=kegme5fuimqfo9bbkqb5inp4t6; path=/; HttpOnly]
Dec  7 18:25:41 dreis-desktop mount.davfs: [hdr] Set-Cookie: oc_sessionPassphrase=Xt80uNgZY6lCUHaRxLQ6%%2FlMN%%2B3gC8bDeH4yCjUvGS%%2F41LZeFomiu6bpAUMBcbSKAXDhBdadddF%%2B%%2F4isQ3LtBK2du16XPsGqPa1EtVo67zmHuASHxhKgx%%2BfBQ2EXCCBBw; path=/; secure; HttpOnly
Dec  7 18:25:41 dreis-desktop mount.davfs: Header Name: [set-cookie], Value: [oc_sessionPassphrase=Xt80uNgZY6lCUHaRxLQ6%%2FlMN%%2B3gC8bDeH4yCjUvGS%%2F41LZeFomiu6bpAUMBcbSKAXDhBdadddF%%2B%%2F4isQ3LtBK2du16XPsGqPa1EtVo67zmHuASHxhKgx%%2BfBQ2EXCCBBw; path=/; secure; HttpOnly]
Dec  7 18:25:41 dreis-desktop mount.davfs: [hdr] Strict-Transport-Security: max-age=15768000; preload
Dec  7 18:25:41 dreis-desktop mount.davfs: Header Name: [strict-transport-security], Value: [max-age=15768000; preload]
Dec  7 18:25:41 dreis-desktop mount.davfs: [hdr] Www-Authenticate: Basic realm="ownCloud"
Dec  7 18:25:41 dreis-desktop mount.davfs: Header Name: [www-authenticate], Value: [Basic realm="ownCloud"]
Dec  7 18:25:41 dreis-desktop mount.davfs: [hdr] X-Content-Type-Options: nosniff
Dec  7 18:25:41 dreis-desktop mount.davfs: Header Name: [x-content-type-options], Value: [nosniff]
Dec  7 18:25:41 dreis-desktop mount.davfs: [hdr] X-Download-Options: noopen
Dec  7 18:25:41 dreis-desktop mount.davfs: Header Name: [x-download-options], Value: [noopen]
Dec  7 18:25:41 dreis-desktop mount.davfs: [hdr] X-Frame-Options: SAMEORIGIN
Dec  7 18:25:41 dreis-desktop mount.davfs: Header Name: [x-frame-options], Value: [SAMEORIGIN]
Dec  7 18:25:41 dreis-desktop mount.davfs: [hdr] X-Permitted-Cross-Domain-Policies: none
Dec  7 18:25:41 dreis-desktop mount.davfs: Header Name: [x-permitted-cross-domain-policies], Value: [none]
Dec  7 18:25:41 dreis-desktop mount.davfs: [hdr] X-Robots-Tag: none
Dec  7 18:25:41 dreis-desktop mount.davfs: Header Name: [x-robots-tag], Value: [none]
Dec  7 18:25:41 dreis-desktop mount.davfs: [hdr] X-Xss-Protection: 1; mode=block
Dec  7 18:25:41 dreis-desktop mount.davfs: Header Name: [x-xss-protection], Value: [1; mode=block]
Dec  7 18:25:41 dreis-desktop mount.davfs: [hdr]
Dec  7 18:25:41 dreis-desktop mount.davfs: End of headers.
Dec  7 18:25:41 dreis-desktop mount.davfs: Running post_headers hooks
Dec  7 18:25:41 dreis-desktop mount.davfs: Reading 412 bytes of response body.
Dec  7 18:25:41 dreis-desktop mount.davfs: Got 322 bytes.
Dec  7 18:25:41 dreis-desktop mount.davfs: Reading 90 bytes of response body.
Dec  7 18:25:41 dreis-desktop mount.davfs: Got 90 bytes.
Dec  7 18:25:41 dreis-desktop mount.davfs: Running post_send hooks
Dec  7 18:25:41 dreis-desktop mount.davfs: ah_post_send (#0), code is 401 (want 401), WWW-Authenticate is Basic realm="ownCloud"
Dec  7 18:25:41 dreis-desktop mount.davfs: auth: Got challenge (code 401).
Dec  7 18:25:41 dreis-desktop mount.davfs: auth: Got 'Basic' challenge.
Dec  7 18:25:41 dreis-desktop mount.davfs: auth: Trying Basic challenge...
Dec  7 18:25:41 dreis-desktop mount.davfs: auth: Accepted Basic challenge.
Dec  7 18:25:41 dreis-desktop mount.davfs: Running pre_send hooks
Dec  7 18:25:41 dreis-desktop mount.davfs: auth: Sending 'Basic' response.
Dec  7 18:25:41 dreis-desktop mount.davfs: Sending request headers:#012OPTIONS /remote.php/webdav/ HTTP/1.1#015#012User-Agent: davfs2/1.5.2 neon/0.30.1#015#012Keep-Alive: #015#012Connection: TE, Keep-Alive#015#012TE: trailers#015#012Host: demo.owncloud.org#015#012Authorization: xxxxxxxxxxxxxxxxxx
Dec  7 18:25:41 dreis-desktop mount.davfs: Sending request-line and headers:
Dec  7 18:25:41 dreis-desktop mount.davfs: Request sent; retry is 1.
Dec  7 18:25:50 dreis-desktop mount.davfs: [status-line] < HTTP/1.1 200 OK
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] Accept-Ranges: bytes
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [accept-ranges], Value: [bytes]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] Allow: OPTIONS, GET, HEAD, DELETE, PROPFIND, PUT, PROPPATCH, COPY, MOVE, REPORT
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [allow], Value: [OPTIONS, GET, HEAD, DELETE, PROPFIND, PUT, PROPPATCH, COPY, MOVE, REPORT]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] Cache-Control: no-store, no-cache, must-revalidate
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [cache-control], Value: [no-store, no-cache, must-revalidate]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] Content-Length: 0
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [content-length], Value: [0]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] Content-Security-Policy: default-src 'none';
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [content-security-policy], Value: [default-src 'none';]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] Content-Type: text/html; charset=UTF-8
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [content-type], Value: [text/html; charset=UTF-8]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] Date: Thu, 07 Dec 2017 17:25:41 GMT
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [date], Value: [Thu, 07 Dec 2017 17:25:41 GMT]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] Dav: 1, 3, extended-mkcol
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [dav], Value: [1, 3, extended-mkcol]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] Expires: Thu, 19 Nov 1981 08:52:00 GMT
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [expires], Value: [Thu, 19 Nov 1981 08:52:00 GMT]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] Ms-Author-Via: DAV
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [ms-author-via], Value: [DAV]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] Pragma: no-cache
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [pragma], Value: [no-cache]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] Server: Apache
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [server], Value: [Apache]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] Set-Cookie: ocgj9l8b2hha=orp8cdblk3kcvu14808qi936t4; path=/; HttpOnly
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [set-cookie], Value: [ocgj9l8b2hha=orp8cdblk3kcvu14808qi936t4; path=/; HttpOnly]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] Set-Cookie: oc_sessionPassphrase=1c65yXjYeMHw8GMzizlc9%%2F4x2uIsUA2f5zJxEn%%2BQJduLkMRu%%2FE4HtFkrccB9YoeQlsKIlovhdsRcgKSHCurIjsyWKqzjq3NgRGJVHpg9%%2ByuUs%%2Bya9zY1uOuY5HtmlUCa; path=/; secure; HttpOnly
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [set-cookie], Value: [oc_sessionPassphrase=1c65yXjYeMHw8GMzizlc9%%2F4x2uIsUA2f5zJxEn%%2BQJduLkMRu%%2FE4HtFkrccB9YoeQlsKIlovhdsRcgKSHCurIjsyWKqzjq3NgRGJVHpg9%%2ByuUs%%2Bya9zY1uOuY5HtmlUCa; path=/; secure; HttpOnly]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] Set-Cookie: ocgj9l8b2hha=s2vlugbs714b4ajrcjjnlpv0k4; path=/; secure; HttpOnly
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [set-cookie], Value: [ocgj9l8b2hha=s2vlugbs714b4ajrcjjnlpv0k4; path=/; secure; HttpOnly]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] Set-Cookie: cookie_test=test; expires=Thu, 07-Dec-2017 18:25:50 GMT; Max-Age=3600
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [set-cookie], Value: [cookie_test=test; expires=Thu, 07-Dec-2017 18:25:50 GMT; Max-Age=3600]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] Strict-Transport-Security: max-age=15768000; preload
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [strict-transport-security], Value: [max-age=15768000; preload]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] X-Content-Type-Options: nosniff
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [x-content-type-options], Value: [nosniff]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] X-Download-Options: noopen
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [x-download-options], Value: [noopen]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] X-Frame-Options: SAMEORIGIN
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [x-frame-options], Value: [SAMEORIGIN]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] X-Permitted-Cross-Domain-Policies: none
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [x-permitted-cross-domain-policies], Value: [none]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] X-Robots-Tag: none
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [x-robots-tag], Value: [none]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr] X-Xss-Protection: 1; mode=block
Dec  7 18:25:50 dreis-desktop mount.davfs: Header Name: [x-xss-protection], Value: [1; mode=block]
Dec  7 18:25:50 dreis-desktop mount.davfs: [hdr]
Dec  7 18:25:50 dreis-desktop mount.davfs: End of headers.
Dec  7 18:25:50 dreis-desktop mount.davfs: Running post_headers hooks
Dec  7 18:25:50 dreis-desktop mount.davfs: Running post_send hooks
Dec  7 18:25:50 dreis-desktop mount.davfs: ah_post_send (#1), code is 200 (want 401), WWW-Authenticate is (none)
Dec  7 18:25:50 dreis-desktop mount.davfs: Request ends, status 200 class 2xx, error line:#012200 OK
Dec  7 18:25:50 dreis-desktop mount.davfs: Running destroy hooks.
Dec  7 18:25:50 dreis-desktop mount.davfs: Request ends.
Dec  7 18:25:50 dreis-desktop mount.davfs: ah_create, for WWW-Authenticate
Dec  7 18:25:50 dreis-desktop mount.davfs: Running pre_send hooks
Dec  7 18:25:50 dreis-desktop mount.davfs: auth: Sending 'Basic' response.
Dec  7 18:25:50 dreis-desktop mount.davfs: Sending request headers:#012PROPFIND /remote.php/webdav/ HTTP/1.1#015#012User-Agent: davfs2/1.5.2 neon/0.30.1#015#012Connection: TE#015#012TE: trailers#015#012Host: demo.owncloud.org#015#012Depth: 1#015#012Content-Length: 257#015#012Content-Type: application/xml#015#012Authorization: xxxxxxxxxxxxxxxxxx
Dec  7 18:25:50 dreis-desktop mount.davfs: Sending request-line and headers:
Dec  7 18:25:50 dreis-desktop mount.davfs: Sending request body:
Dec  7 18:25:50 dreis-desktop mount.davfs: Request sent; retry is 1.
Dec  7 18:25:51 dreis-desktop mount.davfs: [status-line] < HTTP/1.1 207 Multi-Status
Dec  7 18:25:51 dreis-desktop mount.davfs: [hdr] Cache-Control: no-store, no-cache, must-revalidate
Dec  7 18:25:51 dreis-desktop mount.davfs: Header Name: [cache-control], Value: [no-store, no-cache, must-revalidate]
Dec  7 18:25:51 dreis-desktop mount.davfs: [hdr] Content-Length: 2048
Dec  7 18:25:51 dreis-desktop mount.davfs: Header Name: [content-length], Value: [2048]
Dec  7 18:25:51 dreis-desktop mount.davfs: [hdr] Content-Security-Policy: default-src 'none';
Dec  7 18:25:51 dreis-desktop mount.davfs: Header Name: [content-security-policy], Value: [default-src 'none';]
Dec  7 18:25:51 dreis-desktop mount.davfs: [hdr] Content-Type: application/xml; charset=utf-8
Dec  7 18:25:51 dreis-desktop mount.davfs: Header Name: [content-type], Value: [application/xml; charset=utf-8]
Dec  7 18:25:51 dreis-desktop mount.davfs: [hdr] Date: Thu, 07 Dec 2017 17:25:50 GMT
Dec  7 18:25:51 dreis-desktop mount.davfs: Header Name: [date], Value: [Thu, 07 Dec 2017 17:25:50 GMT]
Dec  7 18:25:51 dreis-desktop mount.davfs: [hdr] Dav: 1, 3, extended-mkcol
Dec  7 18:25:51 dreis-desktop mount.davfs: Header Name: [dav], Value: [1, 3, extended-mkcol]
Dec  7 18:25:51 dreis-desktop mount.davfs: [hdr] Expires: Thu, 19 Nov 1981 08:52:00 GMT
Dec  7 18:25:51 dreis-desktop mount.davfs: Header Name: [expires], Value: [Thu, 19 Nov 1981 08:52:00 GMT]
Dec  7 18:25:51 dreis-desktop mount.davfs: [hdr] Pragma: no-cache
Dec  7 18:25:51 dreis-desktop mount.davfs: Header Name: [pragma], Value: [no-cache]
Dec  7 18:25:51 dreis-desktop mount.davfs: [hdr] Server: Apache
Dec  7 18:25:51 dreis-desktop mount.davfs: Header Name: [server], Value: [Apache]
Dec  7 18:25:51 dreis-desktop mount.davfs: [hdr] Set-Cookie: ocgj9l8b2hha=jkh4koh95cjq4v1t6imofl8a83; path=/; HttpOnly
Dec  7 18:25:51 dreis-desktop mount.davfs: Header Name: [set-cookie], Value: [ocgj9l8b2hha=jkh4koh95cjq4v1t6imofl8a83; path=/; HttpOnly]
Dec  7 18:25:51 dreis-desktop mount.davfs: [hdr] Set-Cookie: oc_sessionPassphrase=tUNkQFz9aCqHYIeJsEADndojKnPScXhHpnK9ygtKNRyuHhOUIG3ldTKo2tFnLFSuVuYyTk6yWAFDWMoYoej74tlGJddsUs%%2F07opRY2jgxR91%%2F1Gmh%%2FfdfT0i2nHZ%%2BO2j; path=/; secure; HttpOnly
Dec  7 18:25:51 dreis-desktop mount.davfs: Header Name: [set-cookie], Value: [oc_sessionPassphrase=tUNkQFz9aCqHYIeJsEADndojKnPScXhHpnK9ygtKNRyuHhOUIG3ldTKo2tFnLFSuVuYyTk6yWAFDWMoYoej74tlGJddsUs%%2F07opRY2jgxR91%%2F1Gmh%%2FfdfT0i2nHZ%%2BO2j; path=/; secure; HttpOnly]
Dec  7 18:25:51 dreis-desktop mount.davfs: [hdr] Set-Cookie: ocgj9l8b2hha=i76d3gg45m8gvd6grsr2kf9ku7; path=/; secure; HttpOnly
Dec  7 18:25:51 dreis-desktop mount.davfs: Header Name: [set-cookie], Value: [ocgj9l8b2hha=i76d3gg45m8gvd6grsr2kf9ku7; path=/; secure; HttpOnly]
Dec  7 18:25:51 dreis-desktop mount.davfs: [hdr] Set-Cookie: cookie_test=test; expires=Thu, 07-Dec-2017 18:25:51 GMT; Max-Age=3600
Dec  7 18:25:51 dreis-desktop mount.davfs: Header Name: [set-cookie], Value: [cookie_test=test; expires=Thu, 07-Dec-2017 18:25:51 GMT; Max-Age=3600]
Dec  7 18:25:51 dreis-desktop mount.davfs: [hdr] Strict-Transport-Security: max-age=15768000; preload
Dec  7 18:25:51 dreis-desktop mount.davfs: Header Name: [strict-transport-security], Value: [max-age=15768000; preload]
Dec  7 18:25:51 dreis-desktop mount.davfs: [hdr] Vary: Brief,Prefer
Dec  7 18:25:51 dreis-desktop mount.davfs: Header Name: [vary], Value: [Brief,Prefer]
Dec  7 18:25:51 dreis-desktop mount.davfs: [hdr] X-Content-Type-Options: nosniff
Dec  7 18:25:51 dreis-desktop mount.davfs: Header Name: [x-content-type-options], Value: [nosniff]
Dec  7 18:25:51 dreis-desktop mount.davfs: [hdr] X-Download-Options: noopen
Dec  7 18:25:51 dreis-desktop mount.davfs: Header Name: [x-download-options], Value: [noopen]
Dec  7 18:25:51 dreis-desktop mount.davfs: [hdr] X-Frame-Options: SAMEORIGIN
Dec  7 18:25:51 dreis-desktop mount.davfs: Header Name: [x-frame-options], Value: [SAMEORIGIN]
Dec  7 18:25:51 dreis-desktop mount.davfs: [hdr] X-Permitted-Cross-Domain-Policies: none
Dec  7 18:25:51 dreis-desktop mount.davfs: Header Name: [x-permitted-cross-domain-policies], Value: [none]
...
```

Any help would be great.
Regards,
David

### PR DESCRIPTION
**Pull request by PVince81**
## Description
CORS only makes sense for browsers and davfs has trouble with the OPTIONS logic from CORS.

## Related Issue
Fixes https://github.com/owncloud/core/issues/29793

## How Has This Been Tested?
- [x] TEST: Manual local test with davfs.
- [x] TEST: rerun sample app tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: apps/dav/lib/Connector/Sabre/CorsPlugin.php [hunk 1]
```diff
@@ -66,6 +67,12 @@ public function __construct(\OCP\IUserSession $userSession) {
 	public function initialize(\Sabre\DAV\Server $server) {
 		$this->server = $server;
 
+		if (strpos(strtolower($this->server->httpRequest->getHeader('user-agent')), 'mozilla/') === false) {
```
Comment (DeepDiver1975) [inline apps/dav/lib/Connector/Sabre/CorsPlugin.php]: Matching on the user agent is not the right thing to do as far as I can tell after reading a bit into the specs
If I understand correctly we shall only apply CORS handling on the server if the 'Origin' header is sent with the request ...

see 
https://www.html5rocks.com/en/tutorials/cors/
https://spring.io/understanding/CORS
https://github.com/nelmio/NelmioCorsBundle/blob/master/EventListener/CorsListener.php#L68

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]

File: apps/dav/lib/Connector/Sabre/CorsPlugin.php (hunk 1 above)
Comment (PVince81) [reply apps/dav/lib/Connector/Sabre/CorsPlugin.php]: That's even better, I'll adjust accordingly. Thanks for pointing out.

**Comment by PVince81** [comment]
I've adjusted and squashed to use the "Origin" header only for detection.

Tested and works fine with davfs mounting and also the example app from https://github.com/noveens/staticOwncloudWebapp

@DeepDiver1975

File: apps/dav/lib/Connector/Sabre/CorsPlugin.php [hunk 2]
```diff
@@ -49,6 +49,7 @@ class CorsPlugin extends \Sabre\DAV\ServerPlugin {
 	public function __construct(\OCP\IUserSession $userSession) {
 		$this->userSession = $userSession;
 		$this->extraHeaders['Access-Control-Allow-Headers'] = ["X-OC-Mtime", "OC-Checksum", "OC-Total-Length", "Depth", "Destination", "Overwrite"];
+		// TODO: use $this->server->getAllowedMethods($request->getPath()) in the right location
```
Comment (PVince81) [inline apps/dav/lib/Connector/Sabre/CorsPlugin.php]: https://github.com/owncloud/core/pull/29813

**Comment by PVince81** [comment]
- [ ] check if Origin is the same as current URL and skip CORS if that's the same

**Comment by PVince81** [comment]
I pushed something, unfinished... Need a utility function to properly compare domain + port with defaults (80, 443) in case they are specified still in case of quirky clients.

**Comment by PVince81** [comment]
Rebased, squashed.

I've added a `\OCP\Util::isSameDomain($url1, $url2)` function now in the first commit, with unit tests.
Then this method is used to check by CorsPlugin to detect cross-domain situations. If not cross-domain, it will skip CORS.

@DeepDiver1975 please re-review.

File: lib/public/Util.php [hunk 3]
```diff
@@ -749,4 +749,60 @@ public static function getStatusInfo($includeVersion = false, $serverHide = fals
...
+			$port = $parts['port'];
+		}
+
+		return $protocol . '://' . strtolower($host) . ':' . $port;
+	}
+
+	/**
+	 * Check whether the given URLs have the same protocol, domain and port.
+	 * This is useful to check a browser's cross-domain situation.
+	 * If this method returns true, a browser would consider both URLs to be
```
Comment (PVince81) [inline lib/public/Util.php]: changing this to `false`

File: lib/public/Util.php [hunk 4]
```diff
@@ -722,6 +722,7 @@ public static function getStatusInfo($includeVersion = false, $serverHide = fals
 
 		$installed = (bool) $systemConfig->getValue('installed', false);
 		$maintenance = (bool) $systemConfig->getValue('maintenance', false);
+		\OC_App::loadApps(['theme']);
```
Comment (DeepDiver1975) [inline lib/public/Util.php]: seems unrelated - rebase left over?

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]

File: lib/public/Util.php (hunk 4 above)
Comment (PVince81) [reply lib/public/Util.php]: indeed, no idea how this got here.

Comment (DeepDiver1975) [reply lib/public/Util.php]: no worries - stuff happens

**Comment by PVince81** [comment]
@DeepDiver1975 I've removed the bad line.

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/29874
