### PR TITLE
Handle returned null value in app level code

### LINKED ISSUE #17587: Update to 8.1 failure / could not fetch app info
Updating ownCloud to version 8.1.0, this may take a while.

Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updated "updater" to 0.6
Updated "files_sharing" to 0.6.2
Updated "files_trashbin" to 0.6.3
Updated "files_versions" to 1.0.6
Exception: Could not fetch app info!
The update was unsuccessful. Please report this issue to the ownCloud community.

### PR DESCRIPTION
**Pull request by MorrisJobke**
- getApplication on OCSClient can also return null (see https://github.com/owncloud/core/blob/e55e0ee945628fac297bf69cf5d67b3bfe75dbb0/lib/private/ocsclient.php#L238-238) this is now handled properly
- fixes #17587

@shiznix Please test this :)

cc @rullzer @Xenopathic @nickvergessen @karlitschek 

@karlitschek I would like to backport this to stable8.1

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1: please backport

**Comment by Xenopathic** [comment]
Could this still lead to issues if the type of `$remoteAppEntry` is not null, but also not an array? Would `is_array()` be a better check?

**Comment by MorrisJobke** [comment]
> Could this still lead to issues if the type of $remoteAppEntry is not null, but also not an array? Would is_array() be a better check?

true story. Let me fix this.

**Comment by MorrisJobke** [comment]
@Xenopathic Pushed ;)

**Comment by Xenopathic** [comment]
:+1:

File: settings/controller/appsettingscontroller.php [hunk 1]
```diff
@@ -189,7 +189,7 @@ public function listApps($category = 0, $includeUpdateInfo = true) {
 						if(!array_key_exists('level', $app) && array_key_exists('ocsid', $app)) {
 							$remoteAppEntry = $this->ocsClient->getApplication($app['ocsid'], \OC_Util::getVersion());
 
-							if(array_key_exists('level', $remoteAppEntry)) {
+							if(is_array($remoteAppEntry) && array_key_exists('level', $remoteAppEntry)) {
```
Comment (nickvergessen) [inline settings/controller/appsettingscontroller.php]: `isset($remoteAppEntry['level'])` does the same and would not have had the problem. I still wonder why someone prefers `array_key_exists()` over that.
