### PR TITLE
Fix hidpi previews on public page

### LINKED ISSUE #20576: Generated previews on public sharing page are not high-res
When viewing an image via a shared link, the generated thumbnail looks blurry on high-res screens. This worked fine in the past as far as I remember?

Easy to test by sharing a screenshot (or something else pixel-perfect) and viewing it on a smartphone.

@owncloud/thumbnails @owncloud/sharing

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes https://github.com/owncloud/core/issues/20576

cc @owncloud/sharing @jancborchardt

### CODE REVIEW

File: apps/files_sharing/js/public.js [hunk 1]
```diff
@@ -103,6 +103,10 @@ OCA.Sharing.PublicApp = {
 		};
 
 		var img = $('<img class="publicpreview" alt="">');
+		img.css({
+			'max-width': previewWidth,
+			'max-height': previewHeight
+		});
```
Comment (georgehrke) [inline apps/files_sharing/js/public.js]: [This rule](https://github.com/owncloud/core/blob/master/apps/files_sharing/css/public.css#L29) overwrites this at least for me.

**Comment by MorrisJobke** [comment]
Tested and works here (tested in Chrome, Safari and Firefox) :+1:

@georgehrke I can't see that the rule is overwritten. In every browser the direct style is overwrites the generic one from the CSS file.

**Comment by LukasReschke** [comment]
:+1:
