### PR TITLE
Proper separation of quota values in APIs

### LINKED ISSUE #27803: Default quota value should be set to a oC user when we choose this option
### Steps to reproduce

1. As oC admin go to Users page
2. Set quota as default for a userA
3. Login with the userA

### Expected behaviour

Quota value should be the one that was set as default

### Actual behaviour

No quota is available even changing the default quota value in users page

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:**

"version":""10.0.0.12""

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
```

### Client configuration

**browser**

 Mozilla

### PR DESCRIPTION
**Pull request by PVince81**
## Description
User::getQuota() and User::setQuota() are now reading the exact value as
set in the database instead of interpreting it. This is how it used to
behave.

Util::getUserQuota() is the method that interprets the quota for example
by replacing a default value with the default quota value from the app
config.

Basically the users page must show exactly what's stored in the DB and not interpret the values.

@DeepDiver1975 also fixes misinterpretation of default which should be "default", not "none" in account table.

## Related Issue
Fixes https://github.com/owncloud/core/issues/27803

## Motivation and Context
Bring back correct default quota behavior.

## How Has This Been Tested?
See steps in ticket.
Set one user to "Unlimited" in users page.
Set one user to "Default" in users page.
Set default quota to "1 GB".
Refresh page.

Before fix: quota appears as "1 GB" instead of selected values.
After fix: quota appears as whatever was selected before which is what is stored in DB.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Some unit tests may fail, we'll see.

@jvillafanez can you check whether this could influence LDAP default quota handling ?

@davitol

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2017-05-16 08-44-14

**Comment by jvillafanez** [comment]
> @jvillafanez can you check whether this could influence LDAP default quota handling ?

From 9.1.5 onwards, LDAP can accept "none" and "default" as quota values. Those exact values will be written as quota for the user. There is no further action over those values from the LDAP app.

**Comment by PVince81** [comment]
@jvillafanez thanks for confirming, that's exactly what I thought.

**Comment by PVince81** [comment]
Trying to debug this, seems we got a rabbit hole bug... looks like another file cache bug got revealed through this...

**Comment by PVince81** [comment]
ok got it. seems some tests or the mock might be returning "null" as quota which is misinterpreted as zero.

Fix will follow, also for the backport PR

**Comment by PVince81** [comment]
added null check when reading from config

**Comment by PVince81** [comment]
ok, a few more to go...
```
There were 3 failures:

1) OCA\Files_Versions\Tests\VersioningTest::testRename
Failed asserting that false is true.

/srv/www/htdocs/owncloud/apps/files_versions/tests/VersioningTest.php:345

2) OCA\Files_Versions\Tests\VersioningTest::testRenameInSharedFolder
Failed asserting that false is true.

/srv/www/htdocs/owncloud/apps/files_versions/tests/VersioningTest.php:393

3) OCA\Files_Versions\Tests\VersioningTest::testCopy
Failed asserting that false is true.

/srv/www/htdocs/owncloud/apps/files_versions/tests/VersioningTest.php:556

FAILURES!
Tests: 20, Assertions: 153, Failures: 3.
make: *** [Makefile:179: test-php] Error 1
```

But first: 🍔

**Comment by PVince81** [comment]
fixed versions too by bringing back the old code there.

I wonder if I should maybe change the code for trashbin and versions to use OC_Util::getUserQuota instead

**Comment by PVince81** [comment]
Just retested and there is one remaining issue: when setting the quota to "default" in the users page, it sometimes switches to the actual default value instead of staying "default".
I see that the account table does contain the value "default" so it might be in a different layer.

**Comment by PVince81** [comment]
AHA, the column first contains NULL which is not properly mapped to "default". Only once I set it to "default" explicitly it becomes "default".

**Comment by PVince81** [comment]
@DeepDiver1975 FYI https://github.com/owncloud/core/pull/27895/commits/0bd3418e2457ddad12638f52874de45b46f5051a

interpretation of quota is up to a higher layer

**Comment by PVince81** [comment]
Set default quota to 5 GB
- [x] TEST: newly created user in account table with "Null" sees "default" quota in users page, default quota properly applies in personal page, 5 GB
- [x] TEST: set user quota to "default", explicit "default" in account table, properly applies in personal page, 5 GB
- [x] TEST: set user quota to "unlimited", explicit "none" in account table, properly applies in personal page (unlimited)
- [x] TEST: set user quota to "1 GB", properly applies in personal page

**Comment by PVince81** [comment]
- [x] TEST: updating with the users from https://github.com/owncloud/core/pull/27896#issuecomment-301789865 to this branch keeps their correct quota both in users page and personal page

Interestingly the even users who had "default" explicitly set are getting NULL in the accounts table. Doesn't hurt.

Please re-review

**Comment by PVince81** [comment]
@individual-it weird thing that the quota UI tests fail on Firefox but not Chrome ?

File: apps/files_trashbin/lib/Trashbin.php [hunk 1]
```diff
@@ -678,6 +678,10 @@ private static function calculateFreeSpace($trashbinSize, $user) {
 			return 0;
 		}
 		$quota = $userObject->getQuota();
+		if ($quota === null || $quota === 'default') {
```
Comment (jvillafanez) [inline apps/files_trashbin/lib/Trashbin.php]: What about using `Util::getUserQuota(...)` and have all this calculations in one place?

Comment (PVince81) [inline apps/files_trashbin/lib/Trashbin.php]: at first I thought it wouldn't work because getUserQuota doesn't return null but would return `SPACE_UNLIMITED`. But I could just use that value for the below check.

I'll have a try.

**Comment by PVince81** [comment]
@jvillafanez https://github.com/owncloud/core/pull/27895/commits/29e8cd391e60fdf54abdeb58a70840cae4f0b8d3

**Comment by PVince81** [comment]
stable9.1: https://github.com/owncloud/core/issues/27896

(also updated)

**Comment by jvillafanez** [comment]
Code looks fine 👍

**Comment by PVince81** [comment]
shake that CI
