### PR TITLE
Make Backbone PROPPATCH work with options.wait mode

### LINKED ISSUE #87: Renaming of customgroups using web ui is not possible.
### Steps to reproduce

1. As admin user, create a custom group 'customgroup'.
2. As admin user, using the frontend rename 'customgroup' to 'renamedgroup'.

### Expected behaviour
Customgroup is renamed.

### Actual behaviour
It fails to rename the customgroup.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
10.0.3beta1
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.3.0","versionstring":"10.0.3 beta","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**
```
{"reqId":"cTxBi29Px0i4qvbOsG0n","level":4,"time":"2017-08-22T08:24:51+00:00","remoteAddr":"HIDDEN_IP","user":"admin","app":"webdav","method":"MKCOL","url":"\/remote.php\/dav\/customgroups\/groups\/soyprivado2","message":"Exception: {\"Message\":\"HTTP\\\/1.1 409 Group with display name \\\"soyprivado\\\" already exists\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Conflict\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/customgroups\\\/lib\\\/Dav\\\/GroupsCollection.php(124): OCA\\\\CustomGroups\\\\Dav\\\\GroupsCollection->createGroup('soyprivado2', 'soyprivado')\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1196): OCA\\\\CustomGroups\\\\Dav\\\\GroupsCollection->createExtendedCollection('soyprivado2', Object(Sabre\\\\DAV\\\\MkCol))\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(590): Sabre\\\\DAV\\\\Server->createCollection('customgroups\\\/gr...', Object(Sabre\\\\DAV\\\\MkCol))\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(234): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#9 \\\/opt\\\/owncloud\\\/remote.php(165): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#10 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/customgroups\\\/lib\\\/Dav\\\/GroupsCollection.php\",\"Line\":135,\"User\":\"admin\"}"}
```

### Client configuration

**Browser**
Chrome

cc @PVince81

### PR DESCRIPTION
**Pull request by PVince81**
## Description
In options.wait mode, no model.changes are available as they haven't
been set yet. So in this mode we simply get all properties and send
these with PROPPATCH.

## Related Issue
Fixes https://github.com/owncloud/customgroups/issues/87

## Motivation and Context
Better compatibility with backbone options.

## How Has This Been Tested?
Manual testing with customgroups ticket and JS unit test.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: core/js/oc-backbone-webdav.js [hunk 1]
```diff
@@ -236,7 +257,7 @@
 			options.type,
 			options.url,
 			headers,
-			options.data
+			JSON.stringify(options.data)
```
Comment (jvillafanez) [inline core/js/oc-backbone-webdav.js]: It makes me wonder if this has ever worked... Does this link with the `davSync` method below? If so, any reason to move the `JSON.stringify` up here?

Comment (PVince81) [inline core/js/oc-backbone-webdav.js]: We have some custom calls (ex: comments app) where it does a plain POST with JSON on the collection. Later on we decided that we didn't want POST any more so we're now using other methods. The reason I moved this down is because the stringification is only needed for this one code path.

Comment (jvillafanez) [inline core/js/oc-backbone-webdav.js]: Ok, fair enough.

**Review by jvillafanez — APPROVED** [review]

**Comment by jvillafanez** [comment]
Need to check the failing tests.

**Comment by phil-davis** [comment]
At the moment:
/home/travis/build/owncloud/core/tests/ui/features/files/renameFiles.feature:23
fails on every Travis job that runs it.
Waiting on #28749 to be merged, which should get master back to Travis-CI passing.

**Comment by PVince81** [comment]
rebased. now that the other fix is in I expect all will pass

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/28791

**Comment by PVince81** [comment]
Regression: https://github.com/owncloud/core/issues/28826
