### PR TITLE
When the Share API is disabled do not return shares

### LINKED ISSUE #22668: API share returns the shares that I make even API is disabled
### Steps to reproduce
1. Share files/folders with local user
2. Disable the API share
3. Request the list of shares by path

### Expected behaviour
The server does not return the list of shares I've made like in OC 8.2.2:

```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data/>
</ocs>
```

### Actual behaviour
The server with the disabled share API returns the shares that I had made in OC 9:

```
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
   <meta>
      <status>ok</status>
      <statuscode>100</statuscode>
      <message />
   </meta>
   <data>
      <element>
         <id>19</id>
         <share_type>6</share_type>
         <uid_owner>maria1</uid_owner>
         <displayname_owner>maria1</displayname_owner>
         <permissions>9</permissions>
         <stime>1456403728</stime>
         <parent />
         <expiration />
         <token>CXnzcLXsF6xq3iL</token>
         <uid_file_owner>maria1</uid_file_owner>
         <displayname_file_owner>maria1</displayname_file_owner>
         <path>/Documents</path>
         <item_type>folder</item_type>
         <storage_id>home::maria1</storage_id>
         <storage>7</storage>
         <item_source>24</item_source>
         <file_source>24</file_source>
         <file_parent>23</file_parent>
         <file_target />
         <share_with>maria@XXXXXXXXX</share_with>
         <share_with_displayname>maria@XXXXXXXX</share_with_displayname>
         <mail_send>0</mail_send>
      </element>
      <element>
         <id>6</id>
         <share_type>6</share_type>
         <uid_owner>maria1</uid_owner>
         <displayname_owner>maria1</displayname_owner>
         <permissions>7</permissions>
         <stime>1456394790</stime>
         <parent />
         <expiration />
         <token>FqQ4B2uOi9EbGan</token>
         <uid_file_owner>maria1</uid_file_owner>
         <displayname_file_owner>maria1</displayname_file_owner>
         <path>/Photos</path>
         <item_type>folder</item_type>
         <storage_id>home::maria1</storage_id>
         <storage>7</storage>
         <item_source>26</item_source>
         <file_source>26</file_source>
         <file_parent>23</file_parent>
         <file_target />
         <share_with>maria@XXXXXXXX</share_with>
         <share_with_displayname>maria@XXXXXXXX</share_with_displayname>
         <mail_send>0</mail_send>
      </element>
      <element>
         <id>1</id>
         <share_type>0</share_type>
         <uid_owner>maria1</uid_owner>
         <displayname_owner>maria1</displayname_owner>
         <permissions>31</permissions>
         <stime>1456392268</stime>
         <parent />
         <expiration />
         <token />
         <uid_file_owner>maria1</uid_file_owner>
         <displayname_file_owner>maria1</displayname_file_owner>
         <path>/carpeta de maria1</path>
         <item_type>folder</item_type>
         <storage_id>home::maria1</storage_id>
         <storage>7</storage>
         <item_source>36</item_source>
         <file_source>36</file_source>
         <file_parent>23</file_parent>
         <file_target>/carpeta de maria1</file_target>
         <share_with>admin</share_with>
         <share_with_displayname>admin</share_with_displayname>
         <mail_send>0</mail_send>
      </element>
      <element>
         <id>3</id>
         <share_type>0</share_type>
         <uid_owner>maria1</uid_owner>
         <displayname_owner>maria1</displayname_owner>
         <permissions>19</permissions>
         <stime>1456392300</stime>
         <parent />
         <expiration />
         <token />
         <uid_file_owner>maria1</uid_file_owner>
         <displayname_file_owner>maria1</displayname_file_owner>
         <path>/tutorial.pdf</path>
         <item_type>file</item_type>
         <storage_id>home::maria1</storage_id>
         <storage>7</storage>
         <item_source>30</item_source>
         <file_source>30</file_source>
         <file_parent>23</file_parent>
         <file_target>/tutorial.pdf</file_target>
         <share_with>admin</share_with>
         <share_with_displayname>admin</share_with_displayname>
         <mail_send>0</mail_send>
      </element>
      <element>
         <id>2</id>
         <share_type>3</share_type>
         <uid_owner>maria1</uid_owner>
         <displayname_owner>maria1</displayname_owner>
         <permissions>1</permissions>
         <stime>1456392280</stime>
         <parent />
         <expiration />
         <token>oaryYogLWndisKv</token>
         <uid_file_owner>maria1</uid_file_owner>
         <displayname_file_owner>maria1</displayname_file_owner>
         <path>/tutorial.pdf</path>
         <item_type>file</item_type>
         <storage_id>home::maria1</storage_id>
         <storage>7</storage>
         <item_source>30</item_source>
         <file_source>30</file_source>
         <file_parent>23</file_parent>
         <file_target>/tutorial.pdf</file_target>
         <share_with />
         <share_with_displayname />
         <url>http://XXXXXXXX</url>
         <mail_send>0</mail_send>
      </element>
   </data>
</ocs>
```

Server version: 
{"installed":true,"maintenance":false,"version":"9.0.0.13","versionstring":"9.0.0 beta 2","edition":""}

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #22668

Please verify @mRoRo @javiergonzper 

CC: @nickvergessen @PVince81 @MorrisJobke

### CODE REVIEW

File: lib/private/share20/manager.php [hunk 1]
```diff
@@ -917,6 +925,10 @@ public function getSharedWith($userId, $shareType, $node = null, $limit = 50, $o
 	 * @inheritdoc
 	 */
 	public function getShareById($id, $recipient = null) {
+		if (!$this->shareApiEnabled()) {
+			throw new ShareNotFound();
```
Comment (nickvergessen) [inline lib/private/share20/manager.php]: I'm not sure about this.
I think the config should be checked in the endpoint, not in the manager?

Why? Because when an app created shares, it should be possible to delete them via the share manager when it get's removed or whatever, but blocking this in the manager it is impossible.

Comment (rullzer) [inline lib/private/share20/manager.php]: Yeah thinking more about this that makes sense.
I'll fix it later today.

**Comment by mRoRo** [comment]
@rullzer For which server version will it be fixed? 9.0.0 or 9.0.1?  We'll send to Apple a new app version for validation today, so we should know if this will be fixed for 9.0.0 or in later versions.

**Comment by mRoRo** [comment]
:+1: With this PR API works as 8.2.2. It's solved

**Comment by rullzer** [comment]
@mRoRo I think 9.0.1... but you should already be able to verify if sharing is disabled using the capabilities API.

**Comment by rullzer** [comment]
This PR is against master. Milestone updated to 9.1

File: apps/files_sharing/api/share20ocs.php [hunk 2]
```diff
@@ -448,6 +460,10 @@ private function getSharesInDir($folder) {
 	 * @return \OC_OCS_Result
 	 */
 	public function getShares() {
+		if (!$this->shareManager->shareApiEnabled()) {
+			return new \OC_OCS_Result();
```
Comment (schiesbn) [inline apps/files_sharing/api/share20ocs.php]: Why is this the only place where we return a empty result instead of a 404 ?

Comment (rullzer) [inline apps/files_sharing/api/share20ocs.php]: because getShares can be empty.
If we do not have any shares we also return an empty set.

In my opinion it is like this. If I ask for a specific item. The server can tell me there is no item.
However if I say give me all items. Then I get back an empty set.

So maybe `return new \OC_OCS_Result([]);` would even be better.

Comment (schiesbn) [inline apps/files_sharing/api/share20ocs.php]: This is also what I thought. On the other hand it could make sense to tell the user that this functionality is not available instead of create the impression that the request worked fine and there are just no shares at the moment.

But if this is also how it worked in earlier version it makes sense to keep it that way, in order not to break existing APIs.

Comment (rullzer) [inline apps/files_sharing/api/share20ocs.php]: Well I actually think we should return a 503 here (service unavailable)... but lets do that for v2 of the API

Comment (schiesbn) [inline apps/files_sharing/api/share20ocs.php]: yes, let's clean this up for v2

**Comment by schiesbn** [comment]
code looks good :+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
@karlitschek I would like to request a backport to stable9 for this

**Comment by DeepDiver1975** [comment]
@rullzer needs rebase and conflict resolution - THX

**Comment by karlitschek** [comment]
backport should be safe. thanks! :+1:

**Comment by rullzer** [comment]
rebased

**Comment by rullzer** [comment]
Backport in #23493
