### PR TITLE
fix: web updater is now disabled by default + discourage users to use the web updater

### LINKED ISSUE #41149: Suggestion: Disable (Web-)Updater by default.
It seems the [Updater](https://github.com/owncloud/updater) shipped within ownCloud core releases has a long track of being the root cause for update failures (like recently seen in owncloud/updater#729 or owncloud/updater#726 but also in other GitHub / Forum user reports).

Another issue originating from using the Updater is the following as mentioned in https://github.com/owncloud/updater/issues/713#issuecomment-1867176111:

> Installations will get the "release" after they upgrade to a recent release. There is no automated/scripted way to update the updater in a existing older installation. So it can be a bit of a catch-22 if someone needs the updated updater in order to update!

Furthermore even the documentation at [Upgrade Options](https://doc.owncloud.com/server/10.13/admin_manual/maintenance/upgrading/upgrade.html#upgrade-options) is not recommending the Updater and most importantly also includes the following:

> This is not the recommended upgrade procedure, as builtin core upgrade scripts are error prone.

As (quite commonly happening) a user, especially the less technical firm ones usually won't read the documentation and just click on "Update" in the Web GUI which is leading rather sooner then later to a bad update experience (i never had any so far but not using the Updater at all).

In addition the Updater is also not enabled in the Enterprise edition according to [Upgrading ownCloud with the Updater App](https://doc.owncloud.com/server/10.13/admin_manual/maintenance/upgrading/update.html):

> The Updater app is not enabled and not supported in ownCloud Enterprise edition.

And finally the same page has also a warning / caution (which is usually also not really read):

> Do not use the Updater app in conjunction with [Scripts for the Script-Guided Installation](https://doc.owncloud.com/server/10.13/admin_manual/installation/manual_installation/manual_installation.html#script-guided-installation). See the link for more details.

With all that in mind wouldn't it make sense to disable the Updater by default in the Community Edition and tell the users that they need to enable and use it on their own risk?

- https://doc.owncloud.com/server/10.13/admin_manual/configuration/server/config_sample_php_parameters.html#disable-the-web-based-updater
- `'upgrade.disable-web' => true,` from e.g. the `config.sample.php`

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
The web updater is a relic of old times and can cause more trouble than help.
More details on #41149 

## Related Issue
- Fixes #41149 

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by mmattel — APPROVED** [review]

File: apps/updatenotification/lib/Controller/AdminController.php [hunk 1]
```diff
@@ -173,19 +161,4 @@ public function setChannel($channel) {
 		$this->config->setAppValue('core', 'lastupdatedat', 0);
 		return new DataResponse(['status' => 'success', 'data' => ['message' => $this->l10n->t('Updated channel')]]);
 	}
-
-	/**
-	 * @return DataResponse
-	 */
-	public function createCredentials() {
```
Comment (jvillafanez) [inline apps/updatenotification/lib/Controller/AdminController.php:180]: https://github.com/owncloud/core/blob/d25de58b64bc0979c6d20b46a347ae5153b5bf73/apps/updatenotification/appinfo/routes.php#L27 should also be removed.

**Review by jvillafanez — APPROVED** [review]
