### PR TITLE
fix possible infinite loop when reading groups in the wizard

### LINKED ISSUE #18297: LDAP Wizard Group Tab: infinite loop when having more than 400 groups
### Steps to reproduce
1. Have an LDAP with ~~more than~~ a multiple of 400 groups
2. Configure everything accordingly (assisted mode) until group tab
3. Go group tab

### Expected behaviour
Object classes and groups are being loaded

### Actual behaviour
Object classes are loaded, but groups are stuck in a infinite group

Seen with master. It appears that this line https://github.com/owncloud/core/blob/master/apps/user_ldap/lib/wizard.php#L435 returns always the first 400 groups, no matter the offset.

### PR DESCRIPTION
**Pull request by blizzz**
Fixes #18297 (issue contains test steps).

The integration test tests the case only indirectly, unfortunately, but better than nothing.

:warning: must be tested against AD. I cannot right now.

Please test and review @PVince81 @MorrisJobke @GreenArchon @davitol

### CODE REVIEW

**Comment by karlitschek** [comment]
looks good :+1:

File: apps/user_ldap/lib/access.php [hunk 1]
```diff
@@ -1465,6 +1465,30 @@ private function getPagedResultCookie($base, $filter, $limit, $offset) {
...
+	 * searchUsers() or searchGroups() call. count-methods are probably safe as
+	 * well. Don't rely on it with any fetchList-method.
+	 * @return bool
+	 */
+	public function hasMoreResults() {
+		if(!$this->connection->hasPagedResultSupport) {
+			return false;
+		}
+
+		if(empty($this->lastCookie) && $this->lastCookie !== '0') {
```
Comment (PVince81) [inline apps/user_ldap/lib/access.php]: I assume this->lastcookie is always a string ?

File: apps/user_ldap/lib/wizard.php [hunk 2]
```diff
@@ -438,7 +438,7 @@ public function fetchGroups($dbKey, $confKey) {
 				$groupEntries[] = $item;
 			}
 			$offset += $limit;
-		} while (count($groupNames) > 0 && count($groupNames) % $limit === 0);
```
Comment (PVince81) [inline apps/user_ldap/lib/wizard.php]: Should we keep this condition for non-AD / non-cookie situation ? (I have no idea about AD, just guessing)

File: apps/user_ldap/tests/integration/lib/integrationtestpaging.php [hunk 3]
```diff
@@ -0,0 +1,68 @@
+<?php
+/**
+ * Created by PhpStorm.
```
Comment (PVince81) [inline apps/user_ldap/tests/integration/lib/integrationtestpaging.php]: copyright?

File: apps/user_ldap/lib/wizard.php (hunk 2 above)
Comment (blizzz) [inline apps/user_ldap/lib/wizard.php]: You cannot do paging  without paged results. You may get more results without indeed, but depends on server settings. Both OpenLDAP and AD do support paged search and others (like 389DS or RHDS) as well. With such a big directory you'd not be happy without paged search anyway. As that condition was bogus and it's ugly to make it work with and without paged search I think it's reasonable to change it as it is.

File: apps/user_ldap/lib/access.php (hunk 1 above)
Comment (blizzz) [inline apps/user_ldap/lib/access.php]: yes

File: apps/user_ldap/tests/integration/lib/integrationtestpaging.php (hunk 3 above)
Comment (blizzz) [inline apps/user_ldap/tests/integration/lib/integrationtestpaging.php]: ty

File: apps/user_ldap/lib/wizard.php (hunk 2 above)
Comment (PVince81) [inline apps/user_ldap/lib/wizard.php]: Ok, makes sense

**Comment by PVince81** [comment]
@davitol @rperezb can we get this tested ? Thanks

**Comment by blizzz** [comment]
*rebased*

**Comment by davitol** [comment]
:+1: WFM testing against a LDAP. Pending to be tested with AD, ASAP I can test against it i'll write the result.

File: apps/user_ldap/lib/wizard.php (hunk 2 above)
Comment (nickvergessen) [inline apps/user_ldap/lib/wizard.php]: Shouldn't a simple
```php
		} while (count($result) < $limit);
```

Also work?

Because that is what we want to do, we want to loop, until there are less results then the limit.

Comment (blizzz) [inline apps/user_ldap/lib/wizard.php]: No, because LDAP. Some server may return empty pages inbetween while they still have results.

Comment (nickvergessen) [inline apps/user_ldap/lib/wizard.php]: Okay fine then

**Comment by davitol** [comment]
@blizzz  Tested with an AD and it also works fine. :shipit:

**Comment by blizzz** [comment]
Awesome, thx @davitol

**Comment by MorrisJobke** [comment]
@blizzz What about the backports?

**Comment by MorrisJobke** [comment]
@blizzz Once you are backporting: This also needs a backport ;)

**Comment by blizzz** [comment]
Backport to stable8.1: https://github.com/owncloud/core/pull/20163

**Comment by blizzz** [comment]
With stable8 either a straight port does not work and needs to be adjusted or i see something else. Will look again with a fresh mind.
