### PR TITLE
Fix URL generation

### LINKED ISSUE #16336: Download link in public link page downloads the whole folder
### Steps
1. Create a folder "test"
2. Put two files "test1.txt" and "test2.txt" in it
3. Share "test" with link
4. Open the link
5. In the row of "test1.txt", click on the "Download" link

### Expected result
Only "test1.txt" is downloaded

### Actual result
Zip file of the whole folder is delivered

### Versions
Happens on master (4789e87a5378776738706b48d0db1cf1d989709a)
Works properly on 8.0.3.

Wasn't something similar discovered/fixed recently ? @MorrisJobke @jancborchardt @LukasReschke ?

### PR DESCRIPTION
**Pull request by LukasReschke**
`params` in the `OC.generateUrl` function call only replaces all specified occurences of a key just like the l10n PHP functionality does.

This means that to build a query string we have to use `OC.buildQueryString` instead of the params parameters.

Fixes https://github.com/owncloud/core/issues/16336 which is a regression introduced with https://github.com/owncloud/core/commit/58a87d0babcb91aab75b45e630d2fc2fee15691e of https://github.com/owncloud/core/pull/15652.

Without this fix downloading single files from a public shared folder is not possible.

<hr/>
# Testplan
1. Share a folder on master publicly
2. Access the public link and downloading single files does download the whole folder as a ZIP
3. Apply the patch, clear your cache, downloading single files and all works again

### CODE REVIEW

**Comment by LukasReschke** [comment]
cc @oparoz  @PVince81 please test and review.

Thanks :smile:

**Comment by LukasReschke** [comment]
I will think how to add unit tests meanwhile.

**Comment by nickvergessen** [comment]
:+1:

**Comment by PVince81** [comment]
Am preparing unit tests, there is currently no test file for that section.

**Comment by PVince81** [comment]
@LukasReschke I added JS unit tests, please check them out :smile:

**Comment by oparoz** [comment]
I think it's the wrong approach, you don't fix the exception, you fix the method.

This does not work properly:
https://github.com/owncloud/core/blob/75268860fcac2afd1c3a77d0a4ac58ef8db0e9c9/core/js/js.js#L135

**Comment by PVince81** [comment]
@oparoz I think it is a confusion about how to use this. I was also confused the first time with generateUrl...
Here is an example how parameters can be used there: https://github.com/owncloud/core/blob/master/apps/files/js/search.js#L105

The substitution is done on "{xxx}" strings inside the URL, not appended.

**Comment by oparoz** [comment]
Ah, now I remember, thanks @PVince81 

In this case, it might be cleaner to use something like this:
`return OC.generateUrl('/s/' + token + '/download?path={path}&files={files}', params);`

**Comment by PVince81** [comment]
Feel free to make the change, I'm pretty sure @LukasReschke won't mind. :wink: 

If you do, please also make the token a parameter:
`return OC.generateUrl('/s/{token}/download?path={path}&files={files}', params);` (and make sure to have the token in "params"). I think this is the way it was designed to avoid string concatenation.

**Comment by oparoz** [comment]
I tested as is and the proper URL was generated, but I don't mind it staying as is. It will probably be changed in a future PR.

But I think this call will fail as well:
https://github.com/owncloud/core/blob/fix-url-generation/apps/files_sharing/js/public.js#L157

I changed it at the same time

**Comment by PVince81** [comment]
Hmm right. It is likely that "linkTo" isn't used anywhere so nobody found the issue until now.

**Comment by oparoz** [comment]
It's very possible. A quick search didn't reveal any use of that method. Only calls to OC.linkTo

**Comment by LukasReschke** [comment]
> Feel free to make the change, I'm pretty sure @LukasReschke won't mind. :wink:

Absolutely. Generally speaking hijacking my PRs with good intentions and not too questionable (as in could cause discussions) is always appreciated from my site. Just don't squash it then please ;)

File: apps/files_sharing/tests/js/publicAppSpec.js [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+				expect(fileList.getDownloadUrl(['a b c.txt', 'd e f.txt']))
+					.toEqual(OC.webroot + '/index.php/s/sh4tok/download?path=%2Fsubdir&files=%5B%22a%20b%20c.txt%22%2C%22d%20e%20f.txt%22%5D');
+			});
+			it('returns the correct ajax URL', function() {
+				expect(fileList.getAjaxUrl('test', {a:1, b:'x y'}))
+					.toEqual(OC.webroot + '/index.php/apps/files_sharing/ajax/test.php?a=1&b=x%20y&t=sh4tok');
+			});
+		});
+	});
+});
```
Comment (LukasReschke) [inline apps/files_sharing/tests/js/publicAppSpec.js]: Awesome @PVince81!!!!!

**Comment by rullzer** [comment]
If you select multiple files (not all of them). the download still generates a zip of the whole share.

**Comment by rullzer** [comment]
mmm apparently my cache was not completely flushed...  it does work.

:+1:

File: apps/files_sharing/tests/js/publicAppSpec.js (hunk 1 above)
Comment (PVince81) [inline apps/files_sharing/tests/js/publicAppSpec.js]: I know it can be painful to "bootstrap" a test file when there is none.
But now that it's there, no more excuses for not adding more tests for the public page :wink:
