### PR TITLE
fix copying folder across devices

### LINKED ISSUE #15315: Problem of remove folder
### Steps to reproduce
1. create a folder
2. click on remove folder

### Expected behaviour
folder should be in a trash

### Actual behaviour
folder is still here

### Server configuration
**Operating system**: CentOS 7
**Web server:** Apache
**Database:** MySQL
**PHP version:** 5.4
**ownCloud version:** 8.0.2
**Updated from an older ownCloud or fresh install:** 8.0.0
**List of activated apps:** LDAP
**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oc4v2ps1ccs5',
  'trusted_domains' =>
  array (
    0 => 'cloud.ensta.fr',
    1 => 'nuage.ensta.fr',
  ),
  'datadirectory' => '/var/data',
  'overwrite.cli.url' => 'https://cloud.ensta.fr/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_ligier',
  'installed' => true,
  'forcessl' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 0,
);

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** LDAP

#### ownCloud log (data/owncloud.log)

    {"reqId":"02dde82340af345ee1c48f30d8e18835","remoteAddr":"147.250.91.193","app":"PHP","message":"rename(): The first argument to copy() function cannot be a directory at \/var\/www\/html\/lib\/private\/files\/storage\/local.php#204","level":3,"time":"2015-03-30T12:10:17+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
    {"reqId":"02dde82340af345ee1c48f30d8e18835","remoteAddr":"147.250.91.193","app":"PHP","message":"rename(\/var\/data\/8d5dc32e-ea68-102f-9930-8ffa7bb38356\/files\/test-forum,\/var\/data\/8d5dc32e-ea68-102f-9930-8ffa7bb38356\/files_trashbin\/files\/test-forum.d1427717417): No such file or directory at \/var\/www\/html\/lib\/private\/files\/storage\/local.php#204","level":3,"time":"2015-03-30T12:10:17+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
    {"reqId":"02dde82340af345ee1c48f30d8e18835","remoteAddr":"147.250.91.193","app":"PHP","message":"Undefined index: \/var\/data\/8d5dc32e-ea68-102f-9930-8ffa7bb38356\/files\/test-forum at \/var\/www\/html\/apps\/files_locking\/lib\/lockingwrapper.php#140","level":3,"time":"2015-03-30T12:10:17+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #15315

cc @PVince81 @DeepDiver1975

### CODE REVIEW

File: lib/private/files/storage/local.php [hunk 1]
```diff
@@ -228,6 +228,19 @@ public function rename($path1, $path2) {
 				$this->unlink($path2);
 			}
 
+			if ($this->is_dir($path1)) {
+				// we cant move folders across devices, use copy instead
+				$stat1 = stat(dirname($this->getSourcePath($path1)));
+				$stat2 = stat(dirname($this->getSourcePath($path2)));
```
Comment (Xenopathic) [inline lib/private/files/storage/local.php]: Can we use `Filesystem::resolvePath()` instead of the expensive `stat()` to get the storages, then compare if the storages are the same?

**Comment by karlitschek** [comment]
looks good :+1:

File: lib/private/files/storage/local.php (hunk 1 above)
Comment (icewind1991) [inline lib/private/files/storage/local.php]: We need to know the physical device (hdd) the file is on, not the storage backend.

**Comment by DeepDiver1975** [comment]
@icewind1991 any chance to get this unit tested? THX

**Comment by icewind1991** [comment]
> any chance to get this unit tested? THX

Not without changing the jenkins setup, it requires part of the data directory being on a seperate device

File: lib/private/files/storage/local.php (hunk 1 above)
Comment (Xenopathic) [inline lib/private/files/storage/local.php]: Ah, sorry, I thought this was about external storages vs local storages. Does moving across (local) filesystems really not work?

**Comment by Xenopathic** [comment]
For reference:

> Version 	Description
> 5.3.1 	rename() can now rename files across drives in Windows.
> 5.0.0 	rename() can now also be used with some URL wrappers. Refer to Supported Protocols and Wrappers for a listing of which wrappers support rename().
> 4.3.3 	rename() may now be able to rename files across partitions on *nix based systems, provided the appropriate permissions are held. Warnings may be generated if the destination filesystem doesn't permit chown() or chmod() system calls to be made on files — for example, if the destination filesystem is a FAT filesystem. 

What does this aim to solve?

**Comment by DeepDiver1975** [comment]
> Not without changing the jenkins setup, it requires part of the data directory being on a seperate device

what about injecting stat return values - somehow?

**Comment by Xenopathic** [comment]
Hmm, no sign of this being fixed anytime soon: https://bugs.php.net/bug.php?id=54097

:+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:
