### PR TITLE
[tests-only] Make deleteLdapUsersAndGroups backward-compatible for oC10 user_ldap testing

### LINKED ISSUE #729: Acceptance tests failing
Last night all nightly acceptance test pipelines failed with a problem in `BeforeScenario # FeatureContext::before()`

For example https://drone.owncloud.com/owncloud/user_ldap/3872/24/12

`Empty password not allowed - see allowEmptyPassword option. (Laminas\Ldap\Exception\LdapException)`

core PR https://github.com/owncloud/core/pull/39893 was merged yesterday. That made changes to LDAP things in acceptance tests - so the code changes there should be examined.

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
The new code in #39893 tries to delete each user and group one-by-one from the LDAP server. It was not done that way previously - we used to just delete the whole user and group "ou".

Put "if" checks around the new code so that we do not do it when testing oC10. That gets the oC10 tests passing.
(We could investigate in more detail about exactly why deleting one-by-one does not work, but for now just put back the original behavior and get CI passing)

## Related Issue
- Fixes https://github.com/owncloud/user_ldap/issues/729

## How Has This Been Tested?
user_ldap PR https://github.com/owncloud/user_ldap/pull/731 passes.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

File: tests/acceptance/features/bootstrap/Provisioning.php [hunk 1]
```diff
@@ -853,19 +853,25 @@ public function setLdapSetting(string $configId, string $configKey, string $conf
...
-			);
+			if ($isOcisOrReva) {
+				$this->ldap->delete(
+					"cn=" . ldap_escape($group, "", LDAP_ESCAPE_DN) . ",ou=" . $this->ldapGroupsOU . "," . $this->ldapBaseDN,
+				);
+			}
 			$this->rememberThatGroupIsNotExpectedToExist($group);
 		}
-		if (!$this->skipImportLdif) {
+		if (!$isOcisOrReva || !$this->skipImportLdif) {
```
Comment (phil-davis) [inline tests/acceptance/features/bootstrap/Provisioning.php:874]: Note: we want to always execute this "if" block when we are doing regular oC10 testing (i.e. when not testing oCIS or reva) because in oC10 testing we delete the whole user and group ous and create them again for each test scenario.

**Review by individual-it — APPROVED** [review]
