### PR TITLE
if the mountpoint is accessible for all user the array should contain 'all'

### LINKED ISSUE #19532: Sharee cannot open shared file from an external storage (SMB) using encryption.
### Steps to reproduce

1. Mount SMB folder.
2. Enable encryption.
3. As admin logout and login.
4. As admin create a text file 'textfile.txt' inside the SMB folder.
5. As admin share it with 'user2'.
6. Login with 'user2' try to open 'textfile.txt'.

### Expected behaviour
Sharee can open the file without problems.

### Actual behaviour
500 error. Sharee is unable to open it.

### Server configuration
**Operating system**:
Cent OS 6.6

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.4

**ownCloud version:** (see ownCloud admin page)
Using enterprise theme.
{"installed":true,"maintenance":false,"version":"8.2.0.6","versionstring":"8.2 beta1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.
External storage
Encryption default module.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, SMB.

**Are you using encryption:** 
Yes.

**Server Logs**
```
with \"OC\\Preview\\TXT\"","level":0,"time":"2015-10-02T11:45:20+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Ffichero.txt.txt&c=412&x=32&y=32&forceIcon=0"}
{"reqId":"MQdsqXr4QCHHFN2PTktc","remoteAddr":"HIDED_IP","app":"admin_audit","message":"Read \"\/user3\/files\/fichero.txt.txt\" by user user3, owner: admin [CLIENT_IP: HIDED_IP]","level":1,"time":"2015-10-02T11:45:20+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Ffichero.txt.txt&c=412&x=32&y=32&forceIcon=0"}
{"reqId":"MQdsqXr4QCHHFN2PTktc","remoteAddr":"HIDED_IP","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":
```

### PR DESCRIPTION
**Pull request by schiessle**
fix https://github.com/owncloud/core/issues/19532

This code was introduced by  @PVince81 https://github.com/owncloud/core/commit/72632ad402bd905107db836ed0f9bfae825d6c52#diff-0f47b36d20317b1e2c180d98ff981cbdR53, please have a look to make sure that it doesn't break anything else.

I see the potential danger that the user "all" could collide with a real user "all". Probably this was one of the reason it was removed. Still we have quite some references to "all" alone in files_external, see https://github.com/owncloud/core/issues/19532#issuecomment-145007224, therefore I feel more comfortable to bring back the "all". At least for 8.2

Opinions...  @PVince81 @icewind1991 @Xenopathic @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
"all" was a special applicable value stored as is in mount.json.

After reading the config from disk we need to convert it to the new PHP config arrays format, so it won't be possible to remove all references to "all" until we get rid of the old mount.json format eventually.

File: apps/files_external/service/storagesservice.php [hunk 1]
```diff
@@ -111,10 +111,8 @@ protected function populateStorageConfigWithLegacyOptions(
 
 		if ($mountType === \OC_Mount_Config::MOUNT_TYPE_USER) {
 			$applicableUsers = $storageConfig->getApplicableUsers();
-			if ($applicable !== 'all') {
-				$applicableUsers[] = $applicable;
-				$storageConfig->setApplicableUsers($applicableUsers);
-			}
+			$applicableUsers[] = $applicable;
+			$storageConfig->setApplicableUsers($applicableUsers);
```
Comment (PVince81) [inline apps/files_external/service/storagesservice.php]: $applicableUsers needs to be an empty array when the configuration is applicable to all users. In mount.json this is done by using the string "all". Removing this can potential break that special case.

Regression testing will tell.

I agree that this is less than ideal. Maybe there should be a mount type "ALL" instead.

Comment (PVince81) [inline apps/files_external/service/storagesservice.php]: but if you say this is a regression then maybe the recent refactorings of files_external changed the behavior. Bisecting could tell.

**Comment by schiesbn** [comment]
@PVince81 so what would be your suggestion? Revert the changes in this PR and instead change the encryption code interpret a empty user array as "all"? Are your sure that there are no other areas in the code which still expect 'all' as part of the array?

**Comment by PVince81** [comment]
@schiesbn ah, I didn't know the encryption code was still relying on the value "all".

It used to work in 8.1. And since 8.2 @Xenopathic introduced the new APIs, so I guess encryption is using the new APIs ? If yes, then it is likely that these return the new format where the array is empty. In this case it makes sense to fix the encryption code instead.

**Comment by schiesbn** [comment]
@PVince81 encryption uses the old api, but the old api probably calls internally the new one? On the encryption side nothing changed since 8.1

**Comment by schiesbn** [comment]
I will prepare a second PR with the encryption changes, then we can compare and discuss

**Comment by PVince81** [comment]
I'd expect the new API to return the new structure, if you like I can check this later with a debugger. (unless @Xenopathic pops up with the answer :smile:)

**Comment by schiesbn** [comment]
> I'd expect the new API to return the new structure

That's probably true. But the old API seems to return the new structure too. At least I would say that encryption uses the old API: https://github.com/owncloud/core/blob/master/lib/private/encryption/util.php#L293

**Comment by PVince81** [comment]
Looks like it is supposed to convert it back to the old format, but omitted the "all" case, see https://github.com/owncloud/core/blob/master/apps/files_external/lib/config.php#L163 and https://github.com/owncloud/core/blob/master/apps/files_external/lib/config.php#L208

Just add some code that if "getApplicableUsers()" returns nothing, it must add "all"

**Comment by schiesbn** [comment]
@PVince81 are you sure? Is  ````$storage->getApplicableUsers()```` really only called for the old API?

**Comment by PVince81** [comment]
@schiesbn yes. The old API just returned a messy array (like `$mountEntry`). The new API works with nice objects (the StorageConfig class)

**Comment by schiesbn** [comment]
OK, I adjusted the PR... So this way it should be correct, right?

**Comment by schiesbn** [comment]
I will take care of the failing tests once we agree that this is the right approach

**Comment by PVince81** [comment]
No, your last change would break the expectations of consumers of the new API.

The correct approach is changing the code that converts the new format back to the old format.
Here https://github.com/owncloud/core/blob/master/apps/files_external/lib/config.php#L210 insert a line that if `$mountEntry['applicable']['users']` is empty, then auto-add "all" into that array.

**Comment by PVince81** [comment]
:+1: now it's correct :smile:

**Comment by schiesbn** [comment]
next try... now it should be correct, right?

**Comment by PVince81** [comment]
also take a minute to appreciate how shitty the old arrays looked like...

**Comment by icewind1991** [comment]
:+1: looks good
