### PR TITLE
Fix PHP memory leak in file_get_contents()

### LINKED ISSUE #20261: Desktop sync fails with big files (OC 8.2.0, client 2.0.2)
Hi,

I'm having a trouble uploading a 9GB file using desktop sync client 2.0.2 (and owncloud 8.2.0).

The uploading goes well but when uploading is done, owncloud starts to assemble the file. During the assembly a temporary file is created in the user's files folder.

Then, for some reason, the desktop client tries to sync the temporary file, it fails and syncing is restarted (including uploading of the 9GB file or at least the missing bits).

I have filesystem_check_changes = 0. Shouldn't it prevent stuff like this?

Would it be better to assemble the final file in the cache folder and then move the file to files folder after assembly is done?

### PR DESCRIPTION
**Pull request by MorrisJobke**
- ref https://bugs.php.net/bug.php?id=61961
- ref https://github.com/owncloud/core/issues/20261#issuecomment-180000256
- code is based on the proposal of @chriseqipe
- fixes #20261 

cc @icewind1991 @PVince81 @chriseqipe @ormajollila @guruz

### CODE REVIEW

File: lib/private/files/storage/local.php [hunk 1]
```diff
@@ -176,7 +176,12 @@ public function touch($path, $mtime = null) {
 	}
 
 	public function file_get_contents($path) {
-		return file_get_contents($this->getSourcePath($path));
+		// file_get_contents() has a memory leak: https://bugs.php.net/bug.php?id=61961
+		$filename = $this->getSourcePath($path);
+		$handle = fopen($filename,'rb');
+		$content = fread($handle, filesize($filename));
```
Comment (icewind1991) [inline lib/private/files/storage/local.php]: `stream_get_contents` ?

**Comment by icewind1991** [comment]
The memory leak described in the linked bug report seems unrelated, that one involves setting the max length parameter and has been fixed years ago

File: lib/private/files/storage/local.php (hunk 1 above)
Comment (PVince81) [inline lib/private/files/storage/local.php]: @MorrisJobke can you adjust it ?

@icewind1991 are we sure `stream_get_contents` doesn't have memory leaks on its own ?

**Comment by icewind1991** [comment]
Change is fine by me :+1:

**Comment by cdamken** [comment]
Tested and works fine :+1:

File: lib/private/files/storage/local.php (hunk 1 above)
Comment (MorrisJobke) [inline lib/private/files/storage/local.php]: I would keep it as it is, because this was tested and showed it works.

**Comment by MorrisJobke** [comment]
@karlitschek The original ticket was scheduled for 8.2.4 and this was also reported on 8.2.2. Backport?

**Comment by karlitschek** [comment]
nice. please backport

**Comment by MorrisJobke** [comment]
stable9: https://github.com/owncloud/core/pull/23784

**Comment by MorrisJobke** [comment]
stable8.2: https://github.com/owncloud/core/pull/23785

**Comment by nickvergessen** [comment]
This broke the texteditor for me...

**Comment by MorrisJobke** [comment]
> This broke the texteditor for me...

Please open a new ticket

File: lib/private/files/storage/local.php (hunk 1 above)
Comment (nickvergessen) [inline lib/private/files/storage/local.php]: Reading 0 bytes returns false instead of an empty string, breaking the texteditor app for newly created files....

adding
```php
		if (filesize($filename) === 0) {
			return '';
		}
```
before the fopen fixes the problem

Comment (MorrisJobke) [inline lib/private/files/storage/local.php]: Could you open a PR?

**Comment by nickvergessen** [comment]
Follow up https://github.com/owncloud/core/pull/23860
