### PR TITLE
fix issue with previews not being displayed if filename contains apostrophe

### LINKED ISSUE #14149: Previews not working when an apostrophe is present in name.
Previews not working when an apostrophe is present in name.

### PR DESCRIPTION
**Pull request by georgehrke**
fixes https://github.com/owncloud/core/issues/14149

please review @oparoz @PVince81 

There is no special escaping for an apostrophe (by $.param()).
This leads to issues with background-image: url(...)
Therefore we should wrap the url in double quotes.
This should not introduce new issues with double quotes as:
- we do not allow double quotes in names at all
- double quotes are escaped to %22 anyway

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@LukasReschke please review - smells like another url decode issue - thx

File: apps/files/js/filelist.js [hunk 1]
```diff
@@ -959,7 +959,7 @@
 						};
 					var previewUrl = this.generatePreviewUrl(urlSpec);
 					previewUrl = previewUrl.replace('(', '%28').replace(')', '%29');
```
Comment (LukasReschke) [inline apps/files/js/filelist.js]: Shouldn't that be before 950 as well?

**Comment by LukasReschke** [comment]
Makes sense – patch is reasonable :+1:

File: apps/files/js/filelist.js (hunk 1 above)
Comment (nickvergessen) [inline apps/files/js/filelist.js]: `lazyLoadPreview()` does the replacement already

**Comment by nickvergessen** [comment]
:+1:  works as expected

**Comment by nickvergessen** [comment]
Worth backporting @DeepDiver1975 ?

**Comment by DeepDiver1975** [comment]
> Worth backporting @DeepDiver1975 ?

should not hurt - open a pr please - THX

**Comment by georgehrke** [comment]
> should not hurt - open a pr please - THX

will take care

**Comment by DeepDiver1975** [comment]
> will take care

THX @georgehrke

**Comment by karlitschek** [comment]
yes. please backport
