### PR TITLE
Fixes #32090 - browser extension urls in origin header do not trigger…

### LINKED ISSUE #32090: WebDAV not working with other clients
### Steps to reproduce
1. Install Tusk Plugin for your browser (e.g. firefox or chrome). Alternatively it's not working with Buttercup plugin, too.
2. Try to connect to an owncloud installation via WebDAV.

### Expected behaviour
The connection should work. It should be possible to select files.

### Actual behaviour
There is an Server 500 error. Same issue with other plugins or clients for keePass files.

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.2

**ownCloud version:** 10.0.8.5

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** https://owncloud.org/download/

**Signing status (ownCloud 9.0 and above):** 10.0.8

```
No errors have been found.
```

**The content of config/config.php:**

```
{
    "basic": {
        "license key": "***REMOVED SENSITIVE VALUE***",
        "date": "Wed, 18 Jul 2018 21:38:03 +0000",
        "ownCloud version": "10.0.8.5",
        "ownCloud version string": "10.0.8",
        "ownCloud edition": "Community",
        "server OS": "Linux",
        "server OS version": "Linux dd11326 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64",
        "server SAPI": "fpm-fcgi",
        "webserver version": "Apache",
        "hostname": "upload.example.net",
        "user count": 7,
        "user directories": 7,
        "logged-in user": "julian"
    },
    "config": {
        "instanceid": "544b7e5e62a92",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "upload.example.net",
            "ssl-account.com\/oc.poemp.net\/",
            "ssl-account.com\/oc.poemp.net",
            "www.ssl-account.com\/oc.poemp.net\/",
            "https:\/\/ssl-account.com\/oc.poemp.net",
            "https:\/\/ssl-account.com\/oc.poemp.net\/",
            "oc.poemp.net",
            "https:\/\/upload.example.net",
            "https:\/\/www.upload.example.net"
        ],
        "cors.allowed-domains": [
            "moz-extension:\/\/2e14760a-fa4d-c74e-84bb-d5a958932786"
        ],
        "datadirectory": "\/www\/htdocs\/w011d346\/oc.poemp.net\/data",
        "dbtype": "mysql",
        "version": "10.0.8.5",
        "dbname": "d01c1e83",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "overwritehost": "upload.example.net",
        "overwriteprotocol": "https",
        "overwritewebroot": "",
        "forcessl": true,
        "loglevel": 2,
        "token_auth_enforced": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "debug": true,
        "trashbin_retention_obligation": "auto",
        "mail_smtpmode": "php",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    },
    "integritychecker": {
        "passing": true,
        "enabled": true,
        "result": []
    },
    "core": {
        "backgroundjobs_mode": "cron",
        "enable_external_storage": "yes",
        "global_cache_gc_lastrun": "1440704085",
        "installedat": "1414233706",
        "lastcron": "1531949401",
        "lastupdateResult": "[]",
        "lastupdatedat": "1531949058",
        "public_caldav": "calendar\/share.php",
        "public_calendar": "calendar\/share.php",
        "public_documents": "documents\/public.php",
        "public_files": "files_sharing\/public.php",
        "public_gallery": "gallery\/public.php",
        "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
        "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
        "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
        "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
        "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
        "remote_dav": "dav\/appinfo\/v2\/remote.php",
        "remote_files": "dav\/appinfo\/v1\/webdav.php",
        "remote_filesync": "files\/appinfo\/filesync.php",
        "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
        "repairlegacystoragesdone": "yes",
        "updater.secret.created": "1529572841",
        "vendor": "owncloud"
    },
    "apps": [
        {
            "id": "market",
            "name": "Market",
            "summary": "Integrate the ownCloud marketplace into your ownCloud",
            "description": "Easily manage ownCloud apps from within your ownCloud web interface. It connects your ownCloud with your marketplace account and lets you browse, install and update any apps from inside your ownCloud instance.\n\nPlease note: Since ownCloud X (10.0) every instance gets shipped with this app included. You do not need to install it separately. To use this application click on \"Files\" in the top left corner and click on \"Market\" (cart icon) (Administrator privileges required)",
            "licence": "AGPL",
            "author": "Thomas M\u00fcller, Felix Heidecke, Thomas B\u00f6rger, Philipp Schaffrath",
            "version": "0.2.4",
            "default_enable": "",
            "category": "tools",
            "screenshot": "https:\/\/raw.githubusercontent.com\/owncloud\/screenshots\/master\/market\/ownCloud-market-app.jpg",
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "10.0",
                        "max-version": "10.1"
                    }
                }
            },
            "background-jobs": {
                "job": "OCA\\Market\\CheckUpdateBackgroundJob"
            },
            "commands": [
                "OCA\\Market\\Command\\InstallApp",
                "OCA\\Market\\Command\\UnInstallApp",
                "OCA\\Market\\Command\\ListApps",
                "OCA\\Market\\Command\\UpgradeApp"
            ],
            "navigation": {
                "@attributes": {
                    "role": "admin"
                },
                "route": "market.page.index",
                "order": "100"
            },
            "info": [],
            "remote": [],
            "public": [],
            "types": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "two-factor-providers": [],
            "groups": null,
            "active": true,
            "internal": false,
            "level": 100,
            "removable": true,
            "preview": "\/apps\/market\/img\/market.svg",
            "previewAsIcon": true,
            "appconfig": {
                "enabled": "yes",
                "files_antivirus": "0.11.2",
                "installed_version": "0.2.4",
                "signed": "true",
                "types": ""
            }
        },
        {
            "id": "user_external",
            "name": "External user support",
            "description": "Use external user authentication methods like IMAP, SMB and FTP",
            "licence": "AGPL",
            "author": "Robin Appelman",
            "documentation": {
                "admin": "https:\/\/doc.owncloud.org\/server\/9.0\/admin_manual\/configuration_user\/user_auth_ftp_smb_imap.html"
            },
            "website": "https:\/\/github.com\/owncloud\/apps\/tree\/master\/user_external",
            "bugs": "https:\/\/github.com\/owncloud\/apps\/issues",
            "repository": {
                "@attributes": {
                    "type": "git"
                },
                "@value": "https:\/\/github.com\/owncloud\/apps.git"
            },
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "10.0",
                        "max-version": "10.0"
                    }
                }
            },
            "version": "0.4",
            "shipped": "true",
            "types": [
                "authentication",
                "prelogin"
            ],
            "ocsid": "166060",
            "info": [],
            "remote": [],
            "public": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "background-jobs": [],
            "two-factor-providers": [],
            "commands": [],
            "groups": null,
            "active": false,
            "internal": false,
            "level": 100,
            "removable": true,
            "preview": "\/apps\/user_external\/img\/app.svg",
            "previewAsIcon": true
        },
        {
            "id": "audioplayer",
            "name": "Audio Player",
            "summary": "Audio Player for Nextcloud and ownCloud",
            "description": "A music player for FLAC, MP3, MP4, streams, and more with playlist support and Share Player.\n\n- Multiple views (albums with covers and more) - Library scan and reset with command-line and browser - Specifying media folder (with exclude functionality) - Smart & Standard Playlists and playlist files - One Click Play from Files app - External cover support - Mobile view support - Favorites integration - Sidebar integration - Search integration - Stream URLs\n\nSee [README](https:\/\/github.com\/rello\/audioplayer\/blob\/master\/README.md) file for all supported MIME types and limitations.",
            "version": "2.3.0",
            "licence": "AGPL",
            "author": "Marcel Scherello",
            "namespace": "audioplayer",
            "documentation": {
                "user": "https:\/\/github.com\/rello\/audioplayer\/wiki#user-documentation",
                "admin": "https:\/\/github.com\/rello\/audioplayer\/wiki#admin-documentation"
            },
            "category": "multimedia",
            "website": "https:\/\/rello.github.io\/audioplayer",
            "bugs": "https:\/\/github.com\/rello\/audioplayer\/issues",
            "repository": {
                "@attributes": {
                    "type": "git"
                },
                "@value": "https:\/\/github.com\/rello\/audioplayer.git"
            },
            "discussion": "https:\/\/help.nextcloud.com\/c\/apps\/audioplayer",
            "screenshot": {
                "@attributes": {
                    "small-thumbnail": "https:\/\/raw.githubusercontent.com\/rello\/audioplayer\/master\/screenshots\/audioplayer_main_small.png"
                },
                "@value": "https:\/\/raw.githubusercontent.com\/rello\/audioplayer\/master\/screenshots\/audioplayer_main.png"
            },
            "dependencies": {
                "php": {
                    "@attributes": {
                        "min-version": "5.6",
                        "max-version": "7.2"
                    }
                },
                "nextcloud": {
                    "@attributes": {
                        "min-version": "12",
                        "max-version": "14"
                    }
                },
                "owncloud": {
                    "@attributes": {
                        "min-version": "9.1",
                        "max-version": "10.1"
                    }
                }
            },
            "types": [
                "filesystem"
            ],
            "repair-steps": {
                "post-migration": {
                    "step": "OCA\\audioplayer\\Migration\\Migration"
                },
                "install": [],
                "pre-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "info": [],
            "remote": [],
            "public": [],
            "background-jobs": [],
            "two-factor-providers": [],
            "commands": [],
            "groups": null,
            "active": true,
            "internal": false,
            "level": 100,
            "removable": true,
            "preview": "\/apps\/audioplayer\/img\/app.svg",
            "previewAsIcon": true,
            "appconfig": {
                "enabled": "yes",
                "installed_version": "2.3.0",
                "signed": "true",
                "types": "filesystem"
            }
        },
        {
            "id": "external",
            "name": "External Sites",
            "description": "This application allows an admin to add a link in the ownCloud web interface Apps menu that points to an external website. By simply entering the URL and the name for the external site, icon appears. When this icon is clicked by a user, the external website appears in the ownCloud frame. For the user, this external site appears as if it is part of ownCloud but, in fact, this can be any external URL.\n\nNote that the External Site link must use the same type of encryption as provided by ownCloud. In other words, if ownCloud is hosted on HTTPS, the link in the external site must also be HTTPS. The same is also true for HTTP. More information is available in the External Sites documentation.",
            "licence": "AGPL",
            "author": "Frank Karlitschek",
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "10.0",
                        "max-version": "10.0"
                    }
                }
            },
            "version": "1.2",
            "info": [],
            "remote": [],
            "public": [],
            "types": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "background-jobs": [],
            "two-factor-providers": [],
            "commands": [],
            "groups": null,
            "active": false,
            "internal": false,
            "level": 100,
            "removable": true,
            "preview": "\/apps\/external\/img\/external.svg",
            "previewAsIcon": true
        },
        {
            "id": "files_pdfviewer",
            "name": "PDF Viewer",
            "description": "This application integrates the PDF.js library into ownCloud. Using this application users can view their PDF files online without the need to download the file.\n\nWhen this application is enabled publicly shared PDF documents will also get shown in the PDF Viewer instead of only showing a single static snapshot of the document. The PDF viewer requires a modern browser and will not work with Microsoft\u00ae Internet Explorer\u00ae versions below 9.\n\nPDF.js is a JavaScript library developed by Mozilla, you can learn more about the PDF.js project at https:\/\/mozilla.github.io\/pdf.js\/",
            "licence": "AGPL",
            "author": "Thomas M\u00fcller, Lukas Reschke",
            "version": "0.8.2",
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "10.0",
                        "max-version": "10.0"
                    }
                }
            },
            "default_enable": "",
            "documentation": {
                "user": "https:\/\/doc.owncloud.org\/missing",
                "admin": "https:\/\/doc.owncloud.org\/missing",
                "developer": "https:\/\/doc.owncloud.org\/missing"
            },
            "website": "https:\/\/github.com\/owncloud\/files_pdfviewer",
            "bugs": "https:\/\/github.com\/owncloud\/files_pdfviewer\/issues",
            "category": "productivity",
            "repository": {
                "@attributes": {
                    "type": "git"
                },
                "@value": "https:\/\/github.com\/owncloud\/files_pdfviewer.git"
            },
            "screenshot": "https:\/\/github.com\/owncloud\/screenshots\/raw\/cd5f83007e6037af6733d847548d2766be69a8a0\/files_pdfviewer\/files_pdfviewer.png",
            "ocsid": "166049",
            "info": [],
            "remote": [],
            "public": [],
            "types": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "background-jobs": [],
            "two-factor-providers": [],
            "commands": [],
            "groups": null,
            "active": true,
            "internal": false,
            "level": 100,
            "removable": true,
            "preview": "\/apps\/files_pdfviewer\/img\/app.svg",
            "previewAsIcon": true,
            "appconfig": {
                "enabled": "yes",
                "installed_version": "0.8.2",
                "ocsid": "166049",
                "signed": "true",
                "types": ""
            }
        },
        {
            "id": "contacts",
            "name": "Contacts",
            "summary": "Manage your CardDAV contacts from a feature-rich web-interface",
            "description": "Contacts is a user interface for ownCloud's CardDAV server. ownCloud Server comes with a CardDAV component that allows users to synchronize and backup their address books with ownCloud and across multiple devices. It provides users with an alternative to proprietary contact synchronization services giving them back control over their data once more.\n\nThe Contacts application is an extension to ownCloud's CardDAV interface. It equips ownCloud with a feature-rich frontend for the CardDAV server component, supports multiple address books and empowers users to easily manage their contacts from a web interface for ownCloud. Users may find the URL for device synchronization (to configure synchronization in iOS, Android or other CardDAV-capable applications) in the 'Settings' section on the bottom left inside the application (link symbol). Furthermore users can share address books with other users or groups (read-only\/editable) enabling to synchronize address books not only across devices but also across users. In addition to managing synchronized contacts the application also offers a feature to import contacts from vCards (.vcf).",
            "licence": "AGPL",
            "author": "Hendrik Leppelsack, Thomas M\u00fcller, Alexander Weidinger, Jan-Christoph Borchardt, Tom Needham",
            "version": "1.5.4",
            "documentation": {
                "user": "https:\/\/doc.owncloud.org\/server\/10.0\/user_manual\/pim\/index.html",
                "admin": "https:\/\/doc.owncloud.org\/server\/10.0\/admin_manual\/configuration\/server\/occ_command.html?highlight=contacts#dav-commands",
                "developer": "https:\/\/github.com\/owncloud\/contacts\/blob\/master\/README.md"
            },
            "category": "productivity",
            "website": "https:\/\/github.com\/owncloud\/contacts",
            "bugs": "https:\/\/github.com\/owncloud\/contacts\/issues",
            "repository": {
                "@attributes": {
                    "type": "git"
                },
                "@value": "https:\/\/github.com\/owncloud\/contacts.git"
            },
            "screenshot": "https:\/\/raw.githubusercontent.com\/owncloud\/screenshots\/760f2783b03fd26cbc920188b672f5f5efe548c0\/contacts\/contacts.png",
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "9.0",
                        "max-version": "10.1"
                    }
                }
            },
            "info": [],
            "remote": [],
            "public": [],
            "types": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "background-jobs": [],
            "two-factor-providers": [],
            "commands": [],
            "groups": null,
            "active": true,
            "internal": false,
            "level": 100,
            "removable": true,
            "preview": "\/apps\/contacts\/img\/app.svg",
            "previewAsIcon": true,
            "appconfig": {
                "enabled": "yes",
                "installed_version": "1.5.4",
                "signed": "true",
                "types": ""
            }
        },
        {
            "id": "provisioning_api",
            "name": "Provisioning API",
            "description": "This application enables a set of APIs that external systems can use to create, edit, delete and query user attributes, query, set and remove groups, set quota and query total storage used in ownCloud. Group admin users can also query ownCloud and perform the same functions as an admin for groups they manage. The API also enables an admin to query for active ownCloud applications, application info, and to enable or disable an app remotely. Once the app is enabled, http requests can be used via a Basic Auth header to perform any of the functions listed above. More information is available in the Provisioning API documentation, including example calls and server responses.",
            "licence": "AGPL",
            "author": "Tom Needham",
            "default_enable": "",
            "documentation": {
                "admin": "https:\/\/doc.owncloud.org\/server\/10.0\/go.php?to=admin-provisioning-api"
            },
            "version": "0.5.0",
            "namespace": "Provisioning_API",
            "types": [
                "prevent_group_restriction"
            ],
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "10.0",
                        "max-version": "10.0"
                    }
                }
            },
            "info": [],
            "remote": [],
            "public": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "background-jobs": [],
            "two-factor-providers": [],
            "commands": [],
            "groups": null,
            "active": true,
            "internal": true,
            "level": 200,
            "removable": false,
            "preview": "\/apps\/provisioning_api\/img\/app.svg",
            "previewAsIcon": true,
            "appconfig": {
                "enabled": "yes",
                "installed_version": "0.5.0",
                "types": "prevent_group_restriction"
            }
        },
        {
            "id": "gallery",
            "name": "Gallery",
            "description": "Media gallery for ownCloud with the following features:\n\n- Support for large selection of media types (depending on server setup)\n\n- Large, zoomable previews\n\n- Sort images by name or date\n\n- Per album description and copyright statement\n\n- A la carte features\n\n- Image download straight from the slideshow or the gallery\n\n- Seamlessly jump between the gallery and the files view\n\n- Ignore folders containing a \".nomedia\" file\n\n- Native SVG support\n\n- Mobile support\n\nProvides a dedicated view of all images in a grid, adds image viewing capabilities to the files app and adds a gallery view to public links. Compatible with Firefox, Chrome and Internet Explorer 9+",
            "licence": "AGPL",
            "author": "Olivier Paroz, Robin Appelman",
            "version": "16.0.2",
            "namespace": "Gallery",
            "documentation": {
                "user": "https:\/\/github.com\/owncloud\/gallery\/blob\/master\/README.md",
                "admin": "https:\/\/github.com\/owncloud\/gallery\/blob\/master\/README.md",
                "developer": "https:\/\/github.com\/owncloud\/gallery\/blob\/master\/README.md"
            },
            "category": "Multimedia",
            "screenshot": "https:\/\/raw.githubusercontent.com\/owncloud\/screenshots\/0e38639046884e863afc654c5529c8014f7d42fb\/gallery\/gallery.png",
            "website": "https:\/\/github.com\/owncloud\/gallery",
            "bugs": "https:\/\/github.com\/owncloud\/gallery\/issues",
            "repository": {
                "@attributes": {
                    "type": "git"
                },
                "@value": "https:\/\/github.com\/owncloud\/gallery.git"
            },
            "dependencies": {
                "php": {
                    "@attributes": {
                        "min-version": "5.4",
                        "max-version": "7"
                    }
                },
                "owncloud": {
                    "@attributes": {
                        "min-version": "10.0",
                        "max-version": "10.0"
                    }
                }
            },
            "default_enable": "",
            "info": [],
            "remote": [],
            "public": [],
            "types": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "background-jobs": [],
            "two-factor-providers": [],
            "commands": [],
            "groups": null,
            "active": true,
            "internal": false,
            "level": 100,
            "removable": true,
            "preview": "\/apps\/gallery\/img\/app.svg",
            "previewAsIcon": true,
            "appconfig": {
                "enabled": "yes",
                "installed_version": "16.0.2",
                "signed": "true",
                "types": ""
            }
        },
        {
            "id": "encryption",
            "description": "In order to use this encryption module you need to enable server-side encryption in the admin settings. Once enabled this module will encrypt all your files transparently. The encryption is based on AES 256 keys. The module won't touch existing files, only new files will be encrypted after server-side encryption was enabled. It is also not possible to disable the encryption again and switch back to a unencrypted system. Please read the documentation to know all implications before you decide to enable server-side encryption.",
            "name": "Default encryption module",
            "licence": "AGPL",
            "author": "Bjoern Schiessle, Clark Tomlinson",
            "documentation": {
                "user": "https:\/\/doc.owncloud.org\/server\/10.0\/go.php?to=user-encryption",
                "admin": "https:\/\/doc.owncloud.org\/server\/10.0\/go.php?to=admin-encryption"
            },
            "rememberlogin": "false",
            "version": "1.3.1",
            "types": [
                "filesystem"
            ],
            "use-migrations": "true",
            "dependencies": {
                "lib": "openssl",
                "owncloud": {
                    "@attributes": {
                        "min-version": "10.0",
                        "max-version": "10.0"
                    }
                }
            },
            "commands": [
                "OCA\\Encryption\\Command\\SelectEncryptionType",
                "OCA\\Encryption\\Command\\RecreateMasterKey",
                "OCA\\Encryption\\Command\\MigrateKeys"
            ],
            "settings": {
                "admin": "OCA\\Encryption\\Panels\\Admin",
                "personal": "OCA\\Encryption\\Panels\\Personal"
            },
            "info": [],
            "remote": [],
            "public": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "background-jobs": [],
            "two-factor-providers": [],
            "groups": null,
            "active": false,
            "internal": true,
            "level": 200,
            "removable": false,
            "preview": "\/apps\/encryption\/img\/app.svg",
            "previewAsIcon": true
        },
        {
            "id": "systemtags",
            "name": "Collaborative tags",
            "description": "Collaborative tagging functionality which shares tags among users. Great for teams. (If you are a provider with a multi-tenancy installation, it is advised to deactivate this app as tags are shared.)",
            "licence": "AGPL",
            "author": "Vincent Petry",
            "default_enable": "",
            "version": "0.3.0",
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "10.0",
                        "max-version": "10.0"
                    }
                }
            },
            "namespace": "SystemTags",
            "types": [
                "logging"
            ],
            "info": [],
            "remote": [],
            "public": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "background-jobs": [],
            "two-factor-providers": [],
            "commands": [],
            "groups": null,
            "active": true,
            "internal": false,
            "level": 100,
            "removable": true,
            "appconfig": {
                "enabled": "yes",
                "installed_version": "0.3.0",
                "types": "logging"
            }
        },
        {
            "id": "calendar",
            "name": "Calendar",
            "summary": "A Calendar app for ownCloud",
            "description": "The Calendar app is a user interface for ownCloud's CalDAV server. Easily sync events from various devices with your ownCloud and edit them online.\n\n* \ud83d\ude80 **Integration with other ownCloud apps!** Currently Contacts - more to come. * \ud83c\udf10 **WebCal Support!** Want to see your favorite team\u2019s matchdays in your calendar? No problem! * \ud83d\ude4b **Attendees!** Invite people to your events.",
            "version": "1.5.7",
            "licence": "AGPL",
            "author": "Georg Ehrke, Raghu Nayyar, Bernhard Fr\u00f6hler",
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "9.1",
                        "max-version": "10.1"
                    }
                }
            },
            "documentation": {
                "user": "https:\/\/doc.owncloud.org\/server\/10.0\/user_manual\/pim\/calendar.html"
            },
            "category": "productivity",
            "screenshot": "https:\/\/raw.githubusercontent.com\/owncloud\/screenshots\/master\/calendar\/screenshot.png",
            "website": "https:\/\/github.com\/owncloud\/calendar\/",
            "bugs": "https:\/\/github.com\/owncloud\/calendar\/issues",
            "repository": {
                "@attributes": {
                    "type": "git"
                },
                "@value": "https:\/\/github.com\/owncloud\/calendar.git"
            },
            "info": [],
            "remote": [],
            "public": [],
            "types": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "background-jobs": [],
            "two-factor-providers": [],
            "commands": [],
            "groups": null,
            "active": true,
            "internal": false,
            "level": 100,
            "removable": true,
            "preview": "\/apps\/calendar\/img\/calendar.svg",
            "previewAsIcon": true,
            "appconfig": {
                "enabled": "yes",
                "installed_version": "1.5.7",
                "signed": "true",
                "types": ""
            }
        },
        {
            "id": "files_sharing",
            "name": "Share Files",
            "description": "This application enables users to share files within ownCloud. If enabled, the admin can choose which groups can share files. The applicable users can then share files and folders with other users and groups within ownCloud. In addition, if the admin enables the share link feature, an external link can be used to share files with other users outside of ownCloud. Admins can also enforce passwords, expirations dates, and enable server to server sharing via share links, as well as sharing from mobile devices. Turning the feature off removes shared files and folders on the server for all share recipients, and also on the sync clients and mobile apps. More information is available in the ownCloud Documentation.\n\n",
            "licence": "AGPL",
            "author": "Michael Gapczynski, Bjoern Schiessle",
            "default_enable": "",
            "version": "0.10.1",
            "types": [
                "filesystem"
            ],
            "use-migrations": "true",
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "10.0.2.4",
                        "max-version": "10.0"
                    }
                }
            },
            "public": {
                "files": "public.php"
            },
            "namespace": "Files_Sharing",
            "background-jobs": [
                "OCA\\Files_Sharing\\DeleteOrphanedSharesJob",
                "OCA\\Files_Sharing\\ExpireSharesJob"
            ],
            "commands": {
                "command": "OCA\\Files_Sharing\\Command\\CleanupRemoteStorages"
            },
            "info": [],
            "remote": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "two-factor-providers": [],
            "groups": null,
            "active": true,
            "internal": true,
            "level": 200,
            "removable": false,
            "preview": "\/apps\/files_sharing\/img\/app.svg",
            "previewAsIcon": true,
            "appconfig": {
                "enabled": "yes",
                "installed_version": "0.10.1",
                "types": "filesystem"
            }
        },
        {
            "id": "files_videoplayer",
            "name": "Video player",
            "description": "A responsive video player using a skinned version of Video.js\n\nBased on this app: https:\/\/apps.owncloud.com\/content\/show.php\/Video+Js?content=159670\n\nVideo.js: http:\/\/videojs.com\/\n\nSkin: https:\/\/github.com\/cabin\/videojs-sublime-skin",
            "version": "0.9.8",
            "licence": "MIT",
            "author": "Bj\u00f6rn Korella",
            "default_enable": "",
            "documentation": {
                "user": "https:\/\/github.com\/owncloud\/files_videoplayer\/blob\/master\/README.md",
                "admin": "https:\/\/github.com\/owncloud\/files_videoplayer\/blob\/master\/README.md",
                "developer": "https:\/\/github.com\/owncloud\/files_videoplayer\/blob\/master\/README.md"
            },
            "website": "https:\/\/github.com\/owncloud\/files_videoplayer",
            "bugs": "https:\/\/github.com\/owncloud\/files_videoplayer\/issues",
            "repository": {
                "@attributes": {
                    "type": "git"
                },
                "@value": "https:\/\/github.com\/owncloud\/files_videoplayer.git"
            },
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "10.0",
                        "max-version": "10.0"
                    }
                }
            },
            "info": [],
            "remote": [],
            "public": [],
            "types": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "background-jobs": [],
            "two-factor-providers": [],
            "commands": [],
            "groups": null,
            "active": true,
            "internal": false,
            "level": 100,
            "removable": true,
            "preview": "\/apps\/files_videoplayer\/img\/app.svg",
            "previewAsIcon": true,
            "appconfig": {
                "enabled": "yes",
                "installed_version": "0.9.8",
                "types": ""
            }
        },
        {
            "id": "theme-example",
            "name": "Example ownCloud Theme",
            "description": "This App provides the example ownCloud theme.",
            "licence": "AGPL",
            "author": "Philipp Schaffrath",
            "version": "1.0.0",
            "types": [
                "theme"
            ],
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "10.0",
                        "max-version": "10.0"
                    }
                }
            },
            "namespace": "Theme",
            "info": [],
            "remote": [],
            "public": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "background-jobs": [],
            "two-factor-providers": [],
            "commands": [],
            "groups": null,
            "active": false,
            "internal": false,
            "level": 100,
            "removable": true
        },
        {
            "id": "comments",
            "name": "Comments",
            "description": "Files app plugin to add comments to files",
            "licence": "AGPL",
            "author": "Arthur Schiwon, Vincent Petry",
            "default_enable": "",
            "version": "0.3.0",
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "10.0",
                        "max-version": "10.0"
                    }
                }
            },
            "types": [
                "logging",
                "dav"
            ],
            "sabre": {
                "plugins": {
                    "plugin": "OCA\\Comments\\Dav\\CommentsPlugin"
                },
                "collections": {
                    "collection": "OCA\\Comments\\Dav\\RootCollection"
                }
            },
            "info": [],
            "remote": [],
            "public": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "background-jobs": [],
            "two-factor-providers": [],
            "commands": [],
            "groups": null,
            "active": true,
            "internal": false,
            "level": 100,
            "removable": true,
            "appconfig": {
                "enabled": "yes",
                "installed_version": "0.3.0",
                "types": "logging"
            }
        },
        {
            "id": "federation",
            "name": "Federation",
            "description": "ownCloud Federation allows you to connect with other trusted ownClouds to exchange the user directory. For example this will be used to auto-complete external users for federated sharing.",
            "licence": "AGPL",
            "author": "Bjoern Schiessle",
            "version": "0.1.0",
            "namespace": "Federation",
            "category": "other",
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "10.0",
                        "max-version": "10.0"
                    }
                }
            },
            "default_enable": "",
            "types": [
                "authentication"
            ],
            "background-jobs": {
                "job": "OCA\\Federation\\SyncJob"
            },
            "commands": {
                "command": "OCA\\Federation\\Command\\SyncFederationAddressBooks"
            },
            "settings": {
                "admin": "OCA\\Federation\\Panels\\Admin"
            },
            "info": [],
            "remote": [],
            "public": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "two-factor-providers": [],
            "groups": null,
            "active": true,
            "internal": true,
            "level": 200,
            "removable": false,
            "preview": "\/apps\/federation\/img\/app.svg",
            "previewAsIcon": true,
            "appconfig": {
                "autoAddServers": "0",
                "enabled": "yes",
                "installed_version": "0.1.0",
                "types": "authentication"
            }
        },
        {
            "id": "files_versions",
            "name": "Versions",
            "licence": "AGPL",
            "author": "Frank Karlitschek, Bjoern Schiessle",
            "description": "This application enables ownCloud to automatically maintain older versions of files that are changed. When enabled, a hidden versions folder is provisioned in every user\u2019s directory and is used to store old file versions. A user can revert to an older version through the web interface at any time, with the replaced file becoming a version. ownCloud then automatically manages the versions folder to ensure the user doesn\u2019t run out of Quota because of versions. In addition to the expiry of versions, ownCloud\u2019s versions app makes certain never to use more than 50% of the user\u2019s currently available free space. If stored versions exceed this limit, ownCloud will delete the oldest versions first until it meets this limit. More information is available in the Versions documentation.\n\n",
            "version": "1.3.0",
            "types": [
                "filesystem"
            ],
            "namespace": "Files_Versions",
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "10.0",
                        "max-version": "10.0"
                    }
                }
            },
            "documentation": {
                "user": "https:\/\/doc.owncloud.org\/server\/10.0\/go.php?to=user-versions"
            },
            "default_enable": "",
            "background-jobs": {
                "job": "OCA\\Files_Versions\\BackgroundJob\\ExpireVersions"
            },
            "commands": [
                "OCA\\Files_Versions\\Command\\CleanUp",
                "OCA\\Files_Versions\\Command\\ExpireVersions"
            ],
            "info": [],
            "remote": [],
            "public": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "two-factor-providers": [],
            "groups": null,
            "active": true,
            "internal": true,
            "level": 200,
            "removable": false,
            "preview": "\/apps\/files_versions\/img\/app.svg",
            "previewAsIcon": true,
            "appconfig": {
                "enabled": "yes",
                "installed_version": "1.3.0",
                "types": "filesystem"
            }
        },
        {
            "id": "updatenotification",
            "name": "Update notification",
            "description": "Displays update notifications for ownCloud and provides the SSO for the updater.",
            "licence": "AGPL",
            "author": "Lukas Reschke",
            "version": "0.2.1",
            "namespace": "UpdateNotification",
            "default_enable": "",
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "10.0",
                        "max-version": "10.0"
                    }
                }
            },
            "background-jobs": {
                "job": "OCA\\UpdateNotification\\Notification\\BackgroundJob"
            },
            "settings": {
                "admin": "OCA\\UpdateNotification\\Controller\\AdminController"
            },
            "info": [],
            "remote": [],
            "public": [],
            "types": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "two-factor-providers": [],
            "commands": [],
            "groups": null,
            "active": true,
            "internal": true,
            "level": 200,
            "removable": false,
            "appconfig": {
                "core": "10.0.3",
                "enabled": "yes",
                "installed_version": "0.2.1",
                "types": ""
            }
        },
        {
            "id": "notifications",
            "name": "Notifications",
            "summary": "Notification system for internal events",
            "description": "This application adds an internal notification system to an ownCloud instance. Notifications are triggered by apps like the Announcement Center or Custom Groups and displayed via a bell indicator in the WebUI as well as via the ownCloud clients.",
            "category": "tools",
            "screenshot": "https:\/\/raw.githubusercontent.com\/owncloud\/promo\/e1dd604d66b4c5f765579b4c160de3268169ea3c\/ownCloud%20logo%20square.png",
            "licence": "AGPL",
            "author": "Joas Schilling, Thomas M\u00fcller",
            "version": "0.3.3",
            "types": [
                "logging"
            ],
            "default_enable": "",
            "website": "https:\/\/github.com\/owncloud\/notifications",
            "bugs": "https:\/\/github.com\/owncloud\/notifications\/issues",
            "repository": {
                "@attributes": {
                    "type": "git"
                },
                "@value": "https:\/\/github.com\/owncloud\/notifications.git"
            },
            "commands": {
                "command": "OCA\\Notifications\\Command\\Generate"
            },
            "settings": {
                "personal": "OCA\\Notifications\\Panels\\Personal\\NotificationsPanel"
            },
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "10.0.8",
                        "max-version": "10.1"
                    }
                }
            },
            "use-migrations": "true",
            "info": [],
            "remote": [],
            "public": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "background-jobs": [],
            "two-factor-providers": [],
            "groups": null,
            "active": true,
            "internal": false,
            "level": 100,
            "removable": true,
            "preview": "\/apps\/notifications\/img\/notifications.svg",
            "previewAsIcon": true,
            "appconfig": {
                "enabled": "yes",
                "installed_version": "0.3.3",
                "types": "logging"
            }
        },
        {
            "id": "files_trashbin",
            "name": "Deleted files",
            "description": "This application enables users to restore files that were deleted from the system. It displays a list of deleted files in the web interface, and has options to restore those deleted files back to their ownCloud file directories or remove them permanently from the system. Restoring a file also restores related file versions, if the versions application is enabled. When a file is deleted from a share, it can be restored in the same manner, though it is no longer shared. By default, these files remain in the trash bin for 30 days. To prevent a user from running out of disk space, the ownCloud Deleted files app will not utilize more than 50% of the currently available free quota for deleted files. If the deleted files exceed this limit, ownCloud deletes the oldest files until it gets below this limit. More information is available in the Deleted Files documentation.\n\n",
            "licence": "AGPL",
            "author": "Bjoern Schiessle",
            "default_enable": "",
            "version": "0.9.1",
            "types": [
                "filesystem"
            ],
            "use-migrations": "true",
            "namespace": "Files_Trashbin",
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "10.0.2.4",
                        "max-version": "10.0"
                    }
                }
            },
            "documentation": {
                "user": "https:\/\/doc.owncloud.org\/server\/10.0\/go.php?to=user-trashbin"
            },
            "background-jobs": {
                "job": "OCA\\Files_Trashbin\\BackgroundJob\\ExpireTrash"
            },
            "commands": [
                "OCA\\Files_Trashbin\\Command\\CleanUp",
                "OCA\\Files_Trashbin\\Command\\ExpireTrash"
            ],
            "info": [],
            "remote": [],
            "public": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "two-factor-providers": [],
            "groups": null,
            "active": true,
            "internal": true,
            "level": 200,
            "removable": false,
            "preview": "\/apps\/files_trashbin\/img\/app.svg",
            "previewAsIcon": true,
            "appconfig": {
                "enabled": "yes",
                "installed_version": "0.9.1",
                "types": "filesystem"
            }
        },
        {
            "id": "files_texteditor",
            "name": "Text Editor",
            "summary": "Edit text files on the fly",
            "description": "This application enables ownCloud users to view, save and edit text files in the file view. If enabled, an entry for 'Text file' is shown in the '+' button menu at the top of the files view. When clicked, a new text file opens in the browser and the file is saved into the current directory. Furthermore, when a text file is clicked in the file list, it will be opened and editable. If the permissions allow, a user can also edit shared files and save these changes right away in the file view. More information is available in the Text Editor documentation.",
            "licence": "AGPL",
            "author": "Tom Needham, Bj\u00f6rn Schie\u00dfle",
            "version": "2.2.1",
            "default_enable": "",
            "documentation": {
                "user": "https:\/\/github.com\/owncloud\/files_texteditor\/blob\/master\/README.md",
                "admin": "https:\/\/github.com\/owncloud\/files_texteditor\/blob\/master\/README.md",
                "developer": "https:\/\/github.com\/owncloud\/files_texteditor\/blob\/master\/README.md"
            },
            "category": "productivity",
            "website": "https:\/\/github.com\/owncloud\/files_texteditor",
            "bugs": "https:\/\/github.com\/owncloud\/files_texteditor\/issues",
            "repository": {
                "@attributes": {
                    "type": "git"
                },
                "@value": "https:\/\/github.com\/owncloud\/files_texteditor.git"
            },
            "screenshot": "https:\/\/raw.githubusercontent.com\/owncloud\/screenshots\/a068ff44c439aa4969ea37b60e45bed875bbbb98\/files_texteditor\/texteditor.png",
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "10.0",
                        "max-version": "10.0"
                    }
                }
            },
            "info": [],
            "remote": [],
            "public": [],
            "types": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "background-jobs": [],
            "two-factor-providers": [],
            "commands": [],
            "groups": null,
            "active": true,
            "internal": false,
            "level": 100,
            "removable": true,
            "preview": "\/apps\/files_texteditor\/img\/app.svg",
            "previewAsIcon": true,
            "appconfig": {
                "enabled": "yes",
                "installed_version": "2.2.1",
                "ocsid": "166051",
                "signed": "true",
                "types": ""
            }
        },
        {
            "id": "activity",
            "name": "Activity",
            "summary": "Keep track of events with Activity stream and email notifications",
            "description": "The ownCloud Activity application enables users to not only get a summarized overview of all file and folder events in their ownCloud, but also to receive notifications for such via email. The user can configure their individual Activity preferences in their personal settings and can decide in detail which file or folder actions should be listed in the Activity stream (accessible via the app launcher) and also for which file or folder actions the users wants to receive email notifications. The bulk email notifications can either be sent out hourly, daily or weekly to fit the specific needs of the individual user.\n\nFrom creation of new files or folders, to file or folder changes, updates, restores from trash bin, sharing activities, comments, tags and downloads from public share links - the ownCloud Activity app gathers all file or folder related actions in one place for the user to review. For users with lots of activity it is possible to limit the Activity stream to 'Favorites' in order to avoid noise. Furthermore the application provides filters to give users the means to maintain overview by reducing entries to relevant information.\n\nAnd there you have it - a complete overview of all file and folder activities in your ownCloud with the additional ability to receive activity notifications via email in a time interval of your choice. Never again miss an important event related to content in ownCloud and always be up-to-date on all activities of your files and folders.",
            "licence": "AGPL",
            "author": "Frank Karlitschek, Joas Schilling",
            "version": "2.3.6",
            "default_enable": "",
            "types": [
                "filesystem"
            ],
            "use-migrations": "true",
            "documentation": {
                "admin": "https:\/\/doc.owncloud.org\/server\/latest\/admin_manual\/configuration_server\/activity_configuration.html"
            },
            "website": "https:\/\/github.com\/owncloud\/activity\/",
            "bugs": "https:\/\/github.com\/owncloud\/activity\/issues",
            "repository": {
                "@attributes": {
                    "type": "git"
                },
                "@value": "https:\/\/github.com\/owncloud\/activity.git"
            },
            "screenshot": "https:\/\/raw.githubusercontent.com\/owncloud\/screenshots\/68550c2b7c53e6309132ca1c7b177adca976db0b\/activity\/activity.png",
            "category": "tools",
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "10.0.3",
                        "max-version": "10.0"
                    }
                }
            },
            "background-jobs": [
                "OCA\\Activity\\BackgroundJob\\EmailNotification",
                "OCA\\Activity\\BackgroundJob\\ExpireActivities"
            ],
            "navigation": {
                "order": "1",
                "route": "activity.Activities.showList"
            },
            "settings": {
                "personal": "OCA\\Activity\\PersonalPanel"
            },
            "info": [],
            "remote": [],
            "public": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "two-factor-providers": [],
            "commands": [],
            "groups": null,
            "active": true,
            "internal": false,
            "level": 100,
            "removable": true,
            "preview": "\/apps\/activity\/img\/activity.svg",
            "previewAsIcon": true,
            "appconfig": {
                "enabled": "yes",
                "installed_version": "2.3.6",
                "signed": "true",
                "types": "filesystem"
            }
        },
        {
            "id": "configreport",
            "name": "Admin Config Report",
            "description": "Generate a Config Report",
            "licence": "AGPL",
            "author": "owncloud.org",
            "version": "0.1.1",
            "namespace": "ConfigReport",
            "default_enable": [
                "",
                ""
            ],
            "types": [
                "filesystem"
            ],
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "9.1",
                        "max-version": "10.0"
                    }
                }
            },
            "shipped": "true",
            "commands": {
                "command": "OCA\\ConfigReport\\Command\\ConfigReport"
            },
            "settings": {
                "admin": "OCA\\ConfigReport\\AdminPanel"
            },
            "info": [],
            "remote": [],
            "public": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "background-jobs": [],
            "two-factor-providers": [],
            "groups": null,
            "active": true,
            "internal": true,
            "level": 200,
            "removable": false,
            "appconfig": {
                "enabled": "yes",
                "installed_version": "0.1.1",
                "types": "filesystem"
            }
        },
        {
            "id": "firstrunwizard",
            "name": "First run wizard",
            "description": "This application enables a pop-up window when a user first logs into ownCloud. This window welcomes new users to ownCloud, and contains links to the standard ownCloud desktop client, Android app, and the iOS app. The window also shows a link for accessing ownCloud via WebDAV. At any time, the first run wizard button can be opened again via the link on the personal page. The First run wizard can be customized to meet specific design goals, or to change links and messages. Create an appropriate theme following the Theming documentation, and changes to the look and feel of this Wizard are simple. More information is available in the First run wizard documentation, as well as the theming documentation.",
            "licence": "AGPL",
            "author": "Frank Karlitschek, Jan-Christoph Borchardt",
            "dependencies": {
                "owncloud": {
                    "@attributes": {
                        "min-version": "10.0",
                        "max-version": "10.0"
                    }
                }
            },
            "version": "1.1",
            "shipped": "true",
            "default_enable": "",
            "ocsid": "166055",
            "info": [],
            "remote": [],
            "public": [],
            "types": [],
            "repair-steps": {
                "install": [],
                "pre-migration": [],
                "post-migration": [],
                "live-migration": [],
                "uninstall": []
            },
            "background-jobs": [],
            "two-factor-providers": [],
            "commands": [],
            "groups": null,
            "active": true,
            "internal": false,
            "level": 100,
            "removable": true,
            "preview": "\/apps\/firstrunwizard\/img\/app.svg",
            "previewAsIcon": true,
            "appconfig": {
                "enabled": "yes",
                "installed_version": "1.1",
                "ocsid": "166055",
                "types": ""
            }
        }
    ],
    "phpinfo": {
        "bcmath": {
            "BCMath support": "enabled",
            "bcmath.scale": "0"
        },
        "bz2": {
            "BZip2 Support": "Enabled",
            "Stream Wrapper support": "compress.bzip2:\/\/",
            "Stream Filter support": "bzip2.decompress, bzip2.compress",
            "BZip2 Version": "1.0.6, 6-Sept-2010"
        },
        "calendar": {
            "Calendar support": "enabled"
        },
        "cgi-fcgi": {
            "php-fpm": "active",
            "cgi.discard_path": "0",
            "cgi.fix_pathinfo": "1",
            "cgi.force_redirect": "1",
            "cgi.nph": "0",
            "cgi.redirect_status_env": "no value",
            "cgi.rfc2616_headers": "0",
            "fastcgi.error_header": "no value",
            "fastcgi.logging": "1",
            "fpm.config": "no value"
        },
        "Core": {
            "PHP Version": "7.1.11-nmm1",
            "allow_url_fopen": "On",
            "allow_url_include": "On",
            "arg_separator.input": "&amp;",
            "arg_separator.output": "&amp;",
            "auto_append_file": "no value",
            "auto_globals_jit": "On",
            "auto_prepend_file": "no value",
            "browscap": "\/etc\/browscap.ini",
            "default_charset": [
                "UTF-8",
                "no value"
            ],
            "default_mimetype": "text\/html",
            "disable_classes": "no value",
            "disable_functions": "no value",
            "display_errors": [
                "Off",
                "On"
            ],
            "display_startup_errors": "Off",
            "doc_root": "no value",
            "docref_ext": "no value",
            "docref_root": "no value",
            "enable_dl": "Off",
            "enable_post_data_reading": "On",
            "error_append_string": "no value",
            "error_log": "no value",
            "error_prepend_string": "no value",
            "error_reporting": [
                "32767",
                "22519"
            ],
            "expose_php": "Off",
            "extension_dir": "\/usr\/lib\/php7\/20160303",
            "file_uploads": "On",
            "hard_timeout": "2",
            "highlight.comment": "#FF8000",
            "highlight.default": "#0000BB",
            "highlight.html": "#000000",
            "highlight.keyword": "#007700",
            "highlight.string": "#DD0000",
            "html_errors": "On",
            "ignore_repeated_errors": "Off",
            "ignore_repeated_source": "Off",
            "ignore_user_abort": "Off",
            "implicit_flush": "Off",
            "input_encoding": "no value",
            "internal_encoding": "no value",
            "log_errors": "On",
            "log_errors_max_len": "1024",
            "mail.add_x_header": "Off",
            "mail.force_extra_parameters": "no value",
            "mail.log": "no value",
            "max_execution_time": [
                "3600",
                "30"
            ],
            "max_file_uploads": "20",
            "max_input_nesting_level": "64",
            "max_input_time": "60",
            "max_input_vars": "3000",
            "memory_limit": [
                "512M",
                "128M"
            ],
            "open_basedir": "no value",
            "output_buffering": [
                "0",
                "no value"
            ],
            "output_encoding": "no value",
            "output_handler": "no value",
            "post_max_size": [
                "513M",
                "200M"
            ],
            "precision": "12",
            "realpath_cache_size": "4096K",
            "realpath_cache_ttl": "120",
            "register_argc_argv": "On",
            "report_memleaks": "On",
            "report_zend_debug": "On",
            "request_order": "no value",
            "sendmail_from": "no value",
            "sendmail_path": "\/usr\/sbin\/sendmail -t -i ",
            "serialize_precision": "100",
            "short_open_tag": "On",
            "SMTP": "localhost",
            "smtp_port": "25",
            "sql.safe_mode": "Off",
            "sys_temp_dir": "no value",
            "track_errors": "Off",
            "unserialize_callback_func": "no value",
            "upload_max_filesize": [
                "513M",
                "200M"
            ],
            "upload_tmp_dir": "no value",
            "user_dir": "no value",
            "user_ini.cache_ttl": "300",
            "user_ini.filename": ".user.ini",
            "variables_order": "EGPCS",
            "xmlrpc_error_number": "0",
            "xmlrpc_errors": "Off",
            "zend.assertions": "1",
            "zend.detect_unicode": "On",
            "zend.enable_gc": "On",
            "zend.multibyte": "Off",
            "zend.script_encoding": "no value",
            "zend.signal_check": "Off"
        },
        "ctype": {
            "ctype functions": "enabled"
        },
        "curl": {
            "cURL support": "enabled",
            "cURL Information": "7.47.0",
            "Age": "3",
            "Features": null,
            "AsynchDNS": "Yes",
            "CharConv": "No",
            "Debug": "No",
            "GSS-Negotiate": "No",
            "IDN": "Yes",
            "IPv6": "Yes",
            "krb4": "No",
            "Largefile": "Yes",
            "libz": "Yes",
            "NTLM": "Yes",
            "NTLMWB": "Yes",
            "SPNEGO": "Yes",
            "SSL": "Yes",
            "SSPI": "No",
            "TLS-SRP": "Yes",
            "HTTP2": "No",
            "GSSAPI": "Yes",
            "KERBEROS5": "Yes",
            "UNIX_SOCKETS": "Yes",
            "PSL": "No",
            "Protocols": "dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtmp, rtsp, smb, smbs, smtp, smtps, telnet, tftp",
            "Host": "x86_64-pc-linux-gnu",
            "SSL Version": "OpenSSL\/1.0.2g",
            "ZLib Version": "1.2.8"
        },
        "date": {
            "date\/time support": "enabled",
            "timelib version": "2016.05",
            "&quot;Olson&quot; Timezone Database Version": "2017.2",
            "Timezone Database": "internal",
            "Default timezone": "UTC",
            "date.default_latitude": "52.5194",
            "date.default_longitude": "13.4067",
            "date.sunrise_zenith": "90.583333",
            "date.sunset_zenith": "90.583333",
            "date.timezone": "Europe\/Berlin"
        },
        "dba": {
            "DBA support": "enabled",
            "Supported handlers": "cdb cdb_make db4 inifile flatfile",
            "dba.default_handler": "flatfile"
        },
        "dom": {
            "DOM\/XML": "enabled",
            "DOM\/XML API Version": "20031129",
            "libxml Version": "2.9.3",
            "HTML Support": "enabled",
            "XPath Support": "enabled",
            "XPointer Support": "enabled",
            "Schema Support": "enabled",
            "RelaxNG Support": "enabled"
        },
        "exif": {
            "EXIF Support": "enabled",
            "EXIF Version": "1.4 $Id: 8bdc0c8f27c2c9dd1f7551f1f9fe3ab57a06a4b1 $",
            "Supported EXIF Version": "0220",
            "Supported filetypes": "JPEG,TIFF",
            "exif.decode_jis_intel": "JIS",
            "exif.decode_jis_motorola": "JIS",
            "exif.decode_unicode_intel": "UCS-2LE",
            "exif.decode_unicode_motorola": "UCS-2BE",
            "exif.encode_jis": "no value",
            "exif.encode_unicode": "ISO-8859-15"
        },
        "fileinfo": {
            "fileinfo support": "enabled",
            "version": "1.0.5",
            "libmagic": "522"
        },
        "filter": {
            "Input Validation and Filtering": "enabled",
            "Revision": "$Id: cdc5e15bb616f10210b94ecd8789e66c927a375f $",
            "filter.default": "unsafe_raw",
            "filter.default_flags": "no value"
        },
        "ftp": {
            "FTP support": "enabled",
            "FTPS support": "enabled"
        },
        "gd": {
            "GD Support": "enabled",
            "GD Version": "bundled (2.1.0 compatible)",
            "FreeType Support": "enabled",
            "FreeType Linkage": "with freetype",
            "FreeType Version": "2.6.1",
            "GIF Read Support": "enabled",
            "GIF Create Support": "enabled",
            "JPEG Support": "enabled",
            "libJPEG Version": "8",
            "PNG Support": "enabled",
            "libPNG Version": "1.2.54",
            "WBMP Support": "enabled",
            "XPM Support": "enabled",
            "libXpm Version": "30411",
            "XBM Support": "enabled",
            "WebP Support": "enabled",
            "gd.jpeg_ignore_warning": "1"
        },
        "gettext": {
            "GetText Support": "enabled"
        },
        "gmp": {
            "gmp support": "enabled",
            "GMP version": "6.1.0"
        },
        "hash": {
            "hash support": "enabled",
            "Hashing Engines": "md2 md4 md5 sha1 sha224 sha256 sha384 sha512\/224 sha512\/256 sha512 sha3-224 sha3-256 sha3-384 sha3-512 ripemd128 ripemd160 ripemd256 ripemd320 whirlpool tiger128,3 tiger160,3 tiger192,3 tiger128,4 tiger160,4 tiger192,4 snefru snefru256 gost gost-crypto adler32 crc32 crc32b fnv132 fnv1a32 fnv164 fnv1a64 joaat haval128,3 haval160,3 haval192,3 haval224,3 haval256,3 haval128,4 haval160,4 haval192,4 haval224,4 haval256,4 haval128,5 haval160,5 haval192,5 haval224,5 haval256,5",
            "MHASH support": "Enabled",
            "MHASH API Version": "Emulated Support"
        },
        "htscanner": {
            "PECL Module version": "1.0.1 ($Id: htscanner.c 312503 2011-06-26 17:56:58Z derick $)",
            "htscanner.config_file": ".htaccess",
            "htscanner.default_docroot": "\/",
            "htscanner.default_ttl": "1",
            "htscanner.stop_on_error": "0",
            "htscanner.verbose": "0"
        },
        "http": {
            "Extension Version": "3.0.0RC1",
            "libz": "1.2.8",
            "libcurl": "7.47.0",
            "libevent": "2.0.21-stable",
            "libidn (IDNA2003)": [
                "0.29.1",
                "unknown"
            ],
            "http.etag.mode": "crc32b"
        },
        "iconv": {
            "iconv support": "enabled",
            "iconv implementation": "glibc",
            "iconv library version": "2.23",
            "iconv.input_encoding": "no value",
            "iconv.internal_encoding": "no value",
            "iconv.output_encoding": "no value"
        },
        "imagick": {
            "imagick module version": "3.4.3RC1",
            "imagick classes": "Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel",
            "Imagick compiled with ImageMagick version": "ImageMagick 6.8.9-9 Q16 x86_64 2016-04-18 http:\/\/www.imagemagick.org",
            "Imagick using ImageMagick library version": "ImageMagick 6.8.9-9 Q16 x86_64 2018-07-10 http:\/\/www.imagemagick.org",
            "ImageMagick copyright": "Copyright (C) 1999-2014 ImageMagick Studio LLC",
            "ImageMagick release date": "2018-07-10",
            "ImageMagick number of supported formats:": "215",
            "ImageMagick supported formats": "3FR, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FITS, FRACTAL, FTS, G3, GIF, GIF87, GRADIENT, GRAY, GROUP4, GV, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, ICB, ICO, ICON, INFO, INLINE, IPL, ISOBRL, JBG, JBIG, JNG, JNX, JPEG, JPG, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAP, MASK, MAT, MATTE, MEF, MIFF, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV",
            "imagick.locale_fix": "0",
            "imagick.progress_monitor": "0",
            "imagick.skip_version_check": "0"
        },
        "imap": {
            "IMAP c-Client Version": "2007f",
            "SSL Support": "enabled",
            "Kerberos Support": "enabled"
        },
        "interbase": {
            "Firebird\/InterBase Support": "dynamic",
            "Compile-time Client Library Version": "Firebird API version 25",
            "Run-time Client Library Version": "LI-V6.3.4.26856 Firebird 2.5",
            "ibase.allow_persistent": "On",
            "ibase.dateformat": "%Y-%m-%d",
            "ibase.default_charset": "no value",
            "ibase.default_db": "no value",
            "ibase.default_password": "no value",
            "ibase.default_user": "no value",
            "ibase.max_links": "Unlimited",
            "ibase.max_persistent": "Unlimited",
            "ibase.timeformat": "%H:%M:%S",
            "ibase.timestampformat": "%Y-%m-%d %H:%M:%S"
        },
        "intl": {
            "version": "1.1.0",
            "ICU version": "55.1",
            "ICU Data version": "55.1",
            "intl.default_locale": "no value",
            "intl.error_level": "0",
            "intl.use_exceptions": "0"
        },
        "json": {
            "json support": "enabled",
            "json version": "1.5.0"
        },
        "ldap": {
            "LDAP Support": "enabled",
            "RCS Version": "$Id: 0779387e5f88edc656159d12b9302a053e82cc79 $",
            "Total Links": "0\/unlimited",
            "API Version": "3001",
            "Vendor Name": "OpenLDAP",
            "Vendor Version": "20442",
            "SASL Support": "Enabled",
            "ldap.max_links": "Unlimited"
        },
        "libxml": {
            "libXML support": "active",
            "libXML Compiled Version": "2.9.3",
            "libXML Loaded Version": "20903",
            "libXML streams": "enabled"
        },
        "mailparse": {
            "Extension Version": "3.0.2",
            "Revision": "$Revision$",
            "mailparse.def_charset": "us-ascii"
        },
        "mbstring": {
            "Multibyte Support": "enabled",
            "Multibyte string engine": "libmbfl",
            "HTTP input encoding translation": "disabled",
            "libmbfl version": "1.3.2",
            "oniguruma version": "5.9.6",
            "Multibyte (japanese) regex support": "enabled",
            "Multibyte regex (oniguruma) version": "5.9.6",
            "mbstring.detect_order": "no value",
            "mbstring.encoding_translation": "Off",
            "mbstring.func_overload": "0",
            "mbstring.http_input": "no value",
            "mbstring.http_output": "no value",
            "mbstring.http_output_conv_mimetypes": "^(text\/|application\/xhtml\\+xml)",
            "mbstring.internal_encoding": "no value",
            "mbstring.language": "neutral",
            "mbstring.strict_detection": "Off",
            "mbstring.substitute_character": "no value"
        },
        "mcrypt": {
            "Version": "2.5.8",
            "Api No": "20021217",
            "Supported ciphers": "cast-128 gost rijndael-128 twofish arcfour cast-256 loki97 rijndael-192 saferplus wake blowfish-compat des rijndael-256 serpent xtea blowfish enigma rc2 tripledes",
            "Supported modes": "cbc cfb ctr ecb ncfb nofb ofb stream",
            "mcrypt.algorithms_dir": "no value",
            "mcrypt.modes_dir": "no value"
        },
        "mongodb": {
            "mongodb version": "1.1.8",
            "mongodb stability": "stable",
            "libmongoc version": "1.3.5",
            "libbson version": "1.3.5",
            "mongodb.debug": "no value"
        },
        "mysqli": {
            "Client API library version": "mysqlnd 5.0.12-dev - 20150407 - $Id: b396954eeb2d1d9ed7902b8bae237b287f21ad9e $",
            "Active Persistent Links": "0",
            "Inactive Persistent Links": "0",
            "Active Links": "0",
            "mysqli.allow_local_infile": "On",
            "mysqli.allow_persistent": "On",
            "mysqli.default_host": "no value",
            "mysqli.default_port": "3306",
            "mysqli.default_pw": "no value",
            "mysqli.default_socket": "\/var\/run\/mysqld\/mysqld.sock",
            "mysqli.default_user": "no value",
            "mysqli.max_links": "Unlimited",
            "mysqli.max_persistent": "Unlimited",
            "mysqli.reconnect": "Off",
            "mysqli.rollback_on_cached_plink": "Off"
        },
        "mysqlnd": {
            "Version": "mysqlnd 5.0.12-dev - 20150407 - $Id: b396954eeb2d1d9ed7902b8bae237b287f21ad9e $",
            "Compression": "supported",
            "core SSL": "supported",
            "extended SSL": "supported",
            "Command buffer size": "4096",
            "Read buffer size": "32768",
            "Read timeout": "31536000",
            "Collecting statistics": "Yes",
            "Collecting memory statistics": "No",
            "Tracing": "n\/a",
            "Loaded plugins": "mysqlnd,debug_trace,auth_plugin_mysql_native_password,auth_plugin_mysql_clear_password,auth_plugin_sha256_password",
            "API Extensions": "mysqli,pdo_mysql",
            "bytes_sent": "87370",
            "bytes_received": "451399",
            "packets_sent": "1070",
            "packets_received": "9947",
            "protocol_overhead_in": "39788",
            "protocol_overhead_out": "4280",
            "bytes_received_ok_packet": "0",
            "bytes_received_eof_packet": "0",
            "bytes_received_rset_header_packet": "3906",
            "bytes_received_rset_field_meta_packet": "0",
            "bytes_received_rset_row_packet": "3568",
            "bytes_received_prepare_response_packet": "211752",
            "bytes_received_change_user_packet": "227945",
            "packets_sent_command": "514",
            "packets_received_ok": "0",
            "packets_received_eof": "0",
            "packets_received_rset_header": "434",
            "packets_received_rset_field_meta": "0",
            "packets_received_rset_row": "494",
            "packets_received_prepare_response": "2981",
            "packets_received_change_user": "5996",
            "result_set_queries": "434",
            "non_result_set_queries": "60",
            "no_index_used": "93",
            "bad_index_used": "0",
            "slow_queries": "0",
            "buffered_sets": "434",
            "unbuffered_sets": "0",
            "ps_buffered_sets": "0",
            "ps_unbuffered_sets": "0",
            "flushed_normal_sets": "0",
            "flushed_ps_sets": "0",
            "ps_prepared_never_executed": "0",
            "ps_prepared_once_executed": "0",
            "rows_fetched_from_server_normal": "5562",
            "rows_fetched_from_server_ps": "0",
            "rows_buffered_from_client_normal": "5562",
            "rows_buffered_from_client_ps": "0",
            "rows_fetched_from_client_normal_buffered": "5562",
            "rows_fetched_from_client_normal_unbuffered": "0",
            "rows_fetched_from_client_ps_buffered": "0",
            "rows_fetched_from_client_ps_unbuffered": "0",
            "rows_fetched_from_client_ps_cursor": "0",
            "rows_affected_normal": "2",
            "rows_affected_ps": "0",
            "rows_skipped_normal": "5562",
            "rows_skipped_ps": "0",
            "copy_on_write_saved": "0",
            "copy_on_write_performed": "0",
            "command_buffer_too_small": "0",
            "connect_success": "21",
            "connect_failure": "0",
            "connection_reused": "0",
            "reconnect": "0",
            "pconnect_success": "0",
            "active_connections": "18446744073709551597",
            "active_persistent_connections": "0",
            "explicit_close": "20",
            "implicit_close": "0",
            "disconnect_close": "0",
            "in_middle_of_command_close": "0",
            "explicit_free_result": "434",
            "implicit_free_result": "0",
            "explicit_stmt_close": "0",
            "implicit_stmt_close": "0",
            "mem_emalloc_count": "0",
            "mem_emalloc_amount": "0",
            "mem_ecalloc_count": "0",
            "mem_ecalloc_amount": "0",
            "mem_erealloc_count": "0",
            "mem_erealloc_amount": "0",
            "mem_efree_count": "0",
            "mem_efree_amount": "0",
            "mem_malloc_count": "0",
            "mem_malloc_amount": "0",
            "mem_calloc_count": "0",
            "mem_calloc_amount": "0",
            "mem_realloc_count": "0",
            "mem_realloc_amount": "0",
            "mem_free_count": "0",
            "mem_free_amount": "0",
            "mem_estrndup_count": "0",
            "mem_strndup_count": "0",
            "mem_estrdup_count": "0",
            "mem_strdup_count": "0",
            "mem_edupl_count": "0",
            "mem_dupl_count": "0",
            "proto_text_fetched_null": "0",
            "proto_text_fetched_bit": "0",
            "proto_text_fetched_tinyint": "0",
            "proto_text_fetched_short": "116",
            "proto_text_fetched_int24": "0",
            "proto_text_fetched_int": "1551",
            "proto_text_fetched_bigint": "323",
            "proto_text_fetched_decimal": "0",
            "proto_text_fetched_float": "0",
            "proto_text_fetched_double": "0",
            "proto_text_fetched_date": "0",
            "proto_text_fetched_year": "0",
            "proto_text_fetched_time": "0",
            "proto_text_fetched_datetime": "0",
            "proto_text_fetched_timestamp": "0",
            "proto_text_fetched_string": "10362",
            "proto_text_fetched_blob": "0",
            "proto_text_fetched_enum": "4498",
            "proto_text_fetched_set": "0",
            "proto_text_fetched_geometry": "0",
            "proto_text_fetched_other": "0",
            "proto_binary_fetched_null": "0",
            "proto_binary_fetched_bit": "0",
            "proto_binary_fetched_tinyint": "0",
            "proto_binary_fetched_short": "0",
            "proto_binary_fetched_int24": "0",
            "proto_binary_fetched_int": "0",
            "proto_binary_fetched_bigint": "0",
            "proto_binary_fetched_decimal": "0",
            "proto_binary_fetched_float": "0",
            "proto_binary_fetched_double": "0",
            "proto_binary_fetched_date": "0",
            "proto_binary_fetched_year": "0",
            "proto_binary_fetched_time": "0",
            "proto_binary_fetched_datetime": "0",
            "proto_binary_fetched_timestamp": "0",
            "proto_binary_fetched_string": "0",
            "proto_binary_fetched_json": "0",
            "proto_binary_fetched_blob": "0",
            "proto_binary_fetched_enum": "0",
            "proto_binary_fetched_set": "0",
            "proto_binary_fetched_geometry": "0",
            "proto_binary_fetched_other": "0",
            "init_command_executed_count": "0",
            "init_command_failed_count": "0",
            "com_quit": "20",
            "com_init_db": "0",
            "com_query": "494",
            "com_field_list": "0",
            "com_create_db": "0",
            "com_drop_db": "0",
            "com_refresh": "0",
            "com_shutdown": "0",
            "com_statistics": "0",
            "com_process_info": "0",
            "com_connect": "0",
            "com_process_kill": "0",
            "com_debug": "0",
            "com_ping": "0",
            "com_time": "0",
            "com_delayed_insert": "0",
            "com_change_user": "0",
            "com_binlog_dump": "0",
            "com_table_dump": "0",
            "com_connect_out": "0",
            "com_register_slave": "0",
            "com_stmt_prepare": "0",
            "com_stmt_execute": "0",
            "com_stmt_send_long_data": "0",
            "com_stmt_close": "0",
            "com_stmt_reset": "0",
            "com_stmt_set_option": "0",
            "com_stmt_fetch": "0",
            "com_deamon": "0",
            "bytes_received_real_data_normal": "187074",
            "bytes_received_real_data_ps": "0"
        },
        "OAuth": {
            "PLAINTEXT support": "enabled",
            "RSA-SHA1 support": "enabled",
            "HMAC-SHA1 support": "enabled",
            "Request engine support": "php_streams, curl",
            "source version": "$Id$",
            "version": "2.0.0"
        },
        "odbc": {
            "Active Persistent Links": "0",
            "Active Links": "0",
            "ODBC library": "unixODBC",
            "ODBCVER": "0x0380",
            "ODBC_INCLUDE": "-I\/usr\/include",
            "ODBC_LFLAGS": "-L\/usr\/lib",
            "ODBC_LIBS": "-lodbc",
            "odbc.allow_persistent": "On",
            "odbc.check_persistent": "On",
            "odbc.default_cursortype": "Static cursor",
            "odbc.default_db": "no value",
            "odbc.default_pw": "no value",
            "odbc.default_user": "no value",
            "odbc.defaultbinmode": "return as is",
            "odbc.defaultlrl": "return up to 4096 bytes",
            "odbc.max_links": "Unlimited",
            "odbc.max_persistent": "Unlimited"
        },
        "openssl": {
            "OpenSSL support": "enabled",
            "OpenSSL Library Version": "OpenSSL 1.0.2g 1 Mar 2016",
            "OpenSSL Header Version": "OpenSSL 1.0.2g 1 Mar 2016",
            "Openssl default config": "\/usr\/lib\/ssl\/openssl.cnf",
            "openssl.cafile": "no value",
            "openssl.capath": "no value"
        },
        "pcre": {
            "PCRE (Perl Compatible Regular Expressions) Support": "enabled",
            "PCRE Library Version": "8.38 2015-11-23",
            "PCRE JIT Support": "enabled",
            "pcre.backtrack_limit": "1000000",
            "pcre.jit": "1",
            "pcre.recursion_limit": "100000"
        },
        "PDO": {
            "PDO drivers": "dblib, mysql, odbc, pgsql, sqlite"
        },
        "pdo_dblib": {
            "Flavour": "freetds"
        },
        "pdo_mysql": {
            "Client API version": "mysqlnd 5.0.12-dev - 20150407 - $Id: b396954eeb2d1d9ed7902b8bae237b287f21ad9e $",
            "pdo_mysql.default_socket": "\/var\/run\/mysqld\/mysqld.sock"
        },
        "PDO_ODBC": {
            "ODBC Connection Pooling": "Enabled, strict matching"
        },
        "pdo_pgsql": {
            "PostgreSQL(libpq) Version": "9.5.9",
            "Module version": "7.1.11-nmm1",
            "Revision": " $Id: 93712a6af603ebb2ee5792c5be271d4d03edfbde $"
        },
        "pdo_sqlite": {
            "SQLite Library": "3.11.0"
        },
        "pgsql": {
            "PostgreSQL(libpq) Version": "9.5.9",
            "PostgreSQL(libpq)": "PostgreSQL 9.5.9 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit",
            "Multibyte character support": "enabled",
            "SSL support": "enabled",
            "Active Persistent Links": "0",
            "Active Links": "0",
            "pgsql.allow_persistent": "On",
            "pgsql.auto_reset_persistent": "Off",
            "pgsql.ignore_notice": "Off",
            "pgsql.log_notice": "Off",
            "pgsql.max_links": "Unlimited",
            "pgsql.max_persistent": "Unlimited"
        },
        "Phar": {
            "Phar EXT version": "2.0.2",
            "Phar API version": "1.1.1",
            "SVN revision": "$Id: 59c11f4e29768bfbbf6f41cb469abd81d8655850 $",
            "Phar-based phar archives": "enabled",
            "Tar-based phar archives": "enabled",
            "ZIP-based phar archives": "enabled",
            "gzip compression": "enabled",
            "bzip2 compression": "enabled",
            "Native OpenSSL support": "enabled",
            "Phar based on pear\/PHP_Archive, original concept by Davey Shafik.Phar fully realized by Gregory Beaver and Marcus Boerger.Portions of tar implementation Copyright (c) 2003-2009 Tim Kientzle.": null,
            "phar.cache_list": "no value",
            "phar.readonly": "On",
            "phar.require_hash": "On"
        },
        "posix": {
            "Revision": "$Id: b691ca925e7a085e6929579c4eba8fed0732e0ef $"
        },
        "propro": {
            "Extension version": "2.0.0RC1"
        },
        "pspell": {
            "PSpell Support": "enabled"
        },
        "raphf": {
            "Extension version": "2.0.0RC1",
            "raphf.persistent_handle.limit": "-1"
        },
        "recode": {
            "Recode Support": "enabled",
            "Revision": "$Id: e175cff622634146da7151369502cde27702683e $"
        },
        "Reflection": {
            "Version": "$Id: fa936d2e1587e7b6b6c0f7235f4d9df7564a77ad $"
        },
        "session": {
            "Session Support": "enabled",
            "Registered save handlers": "files user",
            "Registered serializer handlers": "php_serialize php php_binary wddx",
            "session.auto_start": "Off",
            "session.cache_expire": "180",
            "session.cache_limiter": "nocache",
            "session.cookie_domain": "no value",
            "session.cookie_httponly": [
                "On",
                "Off"
            ],
            "session.cookie_lifetime": "0",
            "session.cookie_path": "\/",
            "session.cookie_secure": [
                "On",
                "Off"
            ],
            "session.gc_divisor": "100",
            "session.gc_maxlifetime": "1440",
            "session.gc_probability": "0",
            "session.lazy_write": "On",
            "session.name": [
                "544b7e5e62a92",
                "PHPSESSID"
            ],
            "session.referer_check": "no value",
            "session.save_handler": "files",
            "session.save_path": "\/tmp\/phpfpmsessions\/",
            "session.serialize_handler": "php",
            "session.sid_bits_per_character": "4",
            "session.sid_length": "32",
            "session.upload_progress.cleanup": "On",
            "session.upload_progress.enabled": "On",
            "session.upload_progress.freq": "1%",
            "session.upload_progress.min_freq": "1",
            "session.upload_progress.name": "PHP_SESSION_UPLOAD_PROGRESS",
            "session.upload_progress.prefix": "upload_progress_",
            "session.use_cookies": "On",
            "session.use_only_cookies": "On",
            "session.use_strict_mode": "Off",
            "session.use_trans_sid": "0"
        },
        "shmop": {
            "shmop support": "enabled"
        },
        "SimpleXML": {
            "Revision": "$Id: 50413b12ac745b94b27ffbdd5454e6e0d7809909 $",
            "Schema support": "enabled"
        },
        "soap": {
            "Soap Client": "enabled",
            "Soap Server": "enabled",
            "soap.wsdl_cache": "1",
            "soap.wsdl_cache_dir": "\/tmp",
            "soap.wsdl_cache_enabled": "1",
            "soap.wsdl_cache_limit": "5",
            "soap.wsdl_cache_ttl": "86400"
        },
        "SPL": {
            "Interfaces": "Countable, OuterIterator, RecursiveIterator, SeekableIterator, SplObserver, SplSubject",
            "Classes": "AppendIterator, ArrayIterator, ArrayObject, BadFunctionCallException, BadMethodCallException, CachingIterator, CallbackFilterIterator, DirectoryIterator, DomainException, EmptyIterator, FilesystemIterator, FilterIterator, GlobIterator, InfiniteIterator, InvalidArgumentException, IteratorIterator, LengthException, LimitIterator, LogicException, MultipleIterator, NoRewindIterator, OutOfBoundsException, OutOfRangeException, OverflowException, ParentIterator, RangeException, RecursiveArrayIterator, RecursiveCachingIterator, RecursiveCallbackFilterIterator, RecursiveDirectoryIterator, RecursiveFilterIterator, RecursiveIteratorIterator, RecursiveRegexIterator, RecursiveTreeIterator, RegexIterator, RuntimeException, SplDoublyLinkedList, SplFileInfo, SplFileObject, SplFixedArray, SplHeap, SplMinHeap, SplMaxHeap, SplObjectStorage, SplPriorityQueue, SplQueue, SplStack, SplTempFileObject, UnderflowException, UnexpectedValueException"
        },
        "sqlite3": {
            "SQLite3 module version": "7.1.11-nmm1",
            "SQLite Library": "3.11.0",
            "sqlite3.extension_dir": "no value"
        },
        "standard": {
            "Dynamic Library Support": "enabled",
            "Path to sendmail": "\/usr\/sbin\/sendmail -t -i",
            "assert.active": "1",
            "assert.bail": "0",
            "assert.callback": "no value",
            "assert.exception": "0",
            "assert.quiet_eval": "0",
            "assert.warning": "1",
            "auto_detect_line_endings": "0",
            "default_socket_timeout": "60",
            "from": "no value",
            "session.trans_sid_hosts": "no value",
            "session.trans_sid_tags": "a=href,area=href,frame=src,form=",
            "url_rewriter.hosts": "no value",
            "url_rewriter.tags": "a=href,area=href,frame=src,input=src,form=,fieldset=",
            "user_agent": "no value"
        },
        "sysvsem": {
            "Version": "7.1.11-nmm1"
        },
        "sysvshm": {
            "Version": "7.1.11-nmm1"
        },
        "tidy": {
            "libTidy Release": "25 March 2009",
            "Extension Version": "7.1.11-nmm1 ($Id: f764b98c87afe8ab43162db66290eced256fb9f1 $)",
            "tidy.clean_output": "no value",
            "tidy.default_config": "no value"
        },
        "tokenizer": {
            "Tokenizer Support": "enabled"
        },
        "wddx": {
            "WDDX Session Serializer": "enabled"
        },
        "xml": {
            "XML Support": "active",
            "XML Namespace Support": "active",
            "libxml2 Version": "2.9.3"
        },
        "xmlreader": {
            "XMLReader": "enabled"
        },
        "xmlwriter": {
            "XMLWriter": "enabled"
        },
        "xsl": {
            "XSL": "enabled",
            "libxslt Version": "1.1.28",
            "libxslt compiled against libxml Version": "2.9.3",
            "EXSLT": "enabled",
            "libexslt Version": "1.1.28"
        },
        "zip": {
            "Zip": "enabled",
            "Zip version": "1.13.5",
            "Libzip version": "1.1.2"
        },
        "zlib": {
            "Stream Wrapper": "compress.zlib:\/\/",
            "Stream Filter": "zlib.inflate, zlib.deflate",
            "Compiled Version": "1.2.8",
            "Linked Version": "1.2.8",
            "zlib.output_compression": "Off",
            "zlib.output_compression_level": "-1",
            "zlib.output_handler": "no value"
        },
        "Additional Modules": {
            "ionCube Loader": null
        },
        "Environment": {
            "USER": "w011d346",
            "HOME": "\/www\/htdocs\/w011d346"
        }
    }
}
```

**List of activated apps:**

```
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Webdav

### Client configuration
**Browser:** Firefox 

**Operating system:** MacOS 10.13.6

#### ownCloud log (data/owncloud.log)
```

  {
    "reqId": "W0@bpT33HS9CN5KXUd4DRwAAAA8",
    "level": 0,
    "time": "2018-07-18T19:57:26+00:00",
    "remoteAddr": "77.47.102.54",
    "user": "--",
    "app": "webdav",
    "method": "GET",
    "url": "\/remote.php\/dav\/files\/julian\/",
    "message": "Exception: {\"Message\":\"HTTP\\\/1.1 401 No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(278): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/remote.php(165): require_once('\\\/www\\\/htdocs\\\/w01...')\\n#7 {main},\",\"File\":\"\\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168,\"User\":false},"
  },
  {
    "reqId": "W0@cQQ1wvGg5Ho-688OrNQAAAAI",
    "level": 3,
    "time": "2018-07-18T20:00:02+00:00",
    "remoteAddr": "85.13.133.219",
    "user": "--",
    "app": "PHP",
    "method": "GET",
    "url": "\/cron",
    "message": "opendir(\/tmp): failed to open dir: Permission denied at \/www\/htdocs\/w011d346\/oc.poemp.net\/owncloud\/lib\/private\/TempManager.php#188"
  },
  {
    "reqId": "W0@eGPb-I42YZB2A5WOuzAAAAAI",
    "level": 0,
    "time": "2018-07-18T20:07:53+00:00",
    "remoteAddr": "77.47.102.54",
    "user": "--",
    "app": "webdav",
    "method": "OPTIONS",
    "url": "\/remote.php\/dav\/principals\/users\/julian\/",
    "message": "Exception: {\"Message\":\"HTTP\\\/1.1 401 No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(278): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/remote.php(165): require_once('\\\/www\\\/htdocs\\\/w01...')\\n#7 {main},\",\"File\":\"\\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168,\"User\":false},"
  },
  {
    "reqId": "W0@eGh441bM7fc-MUxDXjAAAAAU",
    "level": 0,
    "time": "2018-07-18T20:07:55+00:00",
    "remoteAddr": "77.47.102.54",
    "user": "--",
    "app": "webdav",
    "method": "PROPFIND",
    "url": "\/remote.php\/dav\/addressbooks\/users\/julian\/",
    "message": "Exception: {\"Message\":\"HTTP\\\/1.1 401 No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(278): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/remote.php(165): require_once('\\\/www\\\/htdocs\\\/w01...')\\n#7 {main},\",\"File\":\"\\\/www\\\/htdocs\\\/w011d346\\\/oc.poemp.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168,\"User\":false},"
  },
```

### PR DESCRIPTION
**Pull request by DeepDiver1975**
… CORS verification

## Description
Browser extension send an Origin header with an url which has the schema moz-extension or chromw-extension. We shall no perform CORS verification on these requests since they come from non-websites.

## Related Issue
- Fixes #32090 

## How Has This Been Tested?
- ~not tested personally with an extension~
- tested with firefox extension 'buttercup' - https://addons.mozilla.org/en-US/firefox/addon/buttercup-pw/?src=search
- maybe @julianpoemp can help testing if extensions work now

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by julianpoemp** [comment]
@DeepDiver1975 tested your new version again. Unfortunality it didn't work on my owncloud installation with Chrome (extensions Buttercup and Tusk). I replaced the old CorsPlugin.php with the new version.

My little change of your code before fixed even my issue with webdav on MacOS. With this fix the connection to webdav via Finder workes for me.

**Comment by julianpoemp** [comment]
I found the problem:
The return of ``$request->getHeader('Origin');`` is ``"null"`` as string and not al ``null``. Checked it with an easy if condition.

**Comment by alfredbuehler** [comment]
I was curious about the impact of that change on my ocpad. Surprisingly, the "<all_urls>" in the manifest.json is still required for oc10.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I found the problem:
> The return of $request->getHeader('Origin'); is "null" as string and not al null. That's why the condition if(empty($originHeader) does not trigger. Checked it with an easy if condition if($originHeader == "null")

but "null" is an invalid value - see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin
this is clearly a but in the extensions from my point of view

File: apps/dav/lib/Connector/Sabre/CorsPlugin.php [hunk 1]
```diff
@@ -147,4 +154,16 @@ public function setOptionsRequestHeaders(RequestInterface $request, ResponseInte
 			return false;
 		}
 	}
+
+	/**
+	 * @param string $originHeader
+	 * @return bool
+	 */
+	public function ignoreOriginHeader($originHeader) {
+		if (empty($originHeader)) {
```
Comment (PVince81) [inline apps/dav/lib/Connector/Sabre/CorsPlugin.php]: empty is evil and also matches the string "0"

Comment (PVince81) [reply apps/dav/lib/Connector/Sabre/CorsPlugin.php]: should we rather match the string "null" and not the object `null` here ?
as I understood this line was intended to catch the null case

**Comment by PVince81** [comment]
I'm fine catching null. Maybe add a PHPDoc comment to say this is sent by some clients that do not respect the spec.

**Review by PVince81 — CHANGES_REQUESTED** [review]
see comments

File: apps/dav/lib/Connector/Sabre/CorsPlugin.php (hunk 1 above)
Comment (DeepDiver1975) [reply apps/dav/lib/Connector/Sabre/CorsPlugin.php]: agreed on the evil empty.

I'm undecided about the "null" comparison ....

**Comment by julianpoemp** [comment]
if this is considered as evil, what Do you think about this?:
A new option in config.php, something  like "AllowNullOrigin", that is false by default. If set "null" and null as value for origin is allowed. In that way it's the admin's responsibility to allow it or not.

File: apps/dav/lib/Connector/Sabre/CorsPlugin.php (hunk 1 above)
Comment (PVince81) [reply apps/dav/lib/Connector/Sabre/CorsPlugin.php]: there is more benefit in adding it as more clients will work correctly again

we could consider this "bug" a regression because before we had CORS the mentioned client likely already worked as we had no Origin check, which would increase severity

I suggest we move forward with the null and add a warning. If there are tickets in said client trackers, you could refer these here as well. If in the future this gets fixed there, we can remove the workaround again.

**Comment by DeepDiver1975** [comment]
@PVince81 addressed please have a look again
@julianpoemp I decided to accept 'null' for now - let's see ...

**Comment by DeepDiver1975** [comment]
@PVince81 addressed please have a look again
@julianpoemp I decided to accept 'null' for now - let's see ...

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@julianpoemp mind testing this patch to confirm that the clients you use work now ?

**Comment by julianpoemp** [comment]
it works very fine! I tested it with Firefox, Chrome, Opera and Buttercup Extension on MacOS and Windows 10.

@DeepDiver1975 , @PVince81 thank you!
