### PR TITLE
Calculate the share statuses in js from the OCS Response

### LINKED ISSUE #22298: Incorrect share identifier for reshares
See https://github.com/owncloud/core/pull/22285/#issuecomment-182459777

Basically since we still use the old endpoint (ajax/share.php) to obtain the list of shared info for the current directory we can no longer get reshares correctly. Since that uses the old sharing code that has no idea about how to handle flat reshares.

This means:

1. user1 shares foo with user2
2. user2 shares foo by link

Now user2 does not see the corect share indicator in the webUI.

A possible fix would be to move the listing over to the OCS endpoint now. This is slightly less efficient (more data is transfered). But it is at least complete.

CC: @PVince81 @schiesbn

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #22298 

Right now this is only done on page load. We should do it on each directory traversal.

@PVince81 can you help out?

### CODE REVIEW

File: core/js/share.js [hunk 1]
```diff
@@ -52,15 +52,21 @@ OC.Share = _.extend(OC.Share || {}, {
...
+				if (result && result.ocs.meta.statuscode === 200) {
 					OC.Share.statuses = {};
-					$.each(result.data, function(item, data) {
-						OC.Share.statuses[item] = data;
+					$.each(result.ocs.data, function(it, share) {
+						if (!(share.item_source in OC.Share.statuses)) {
+							OC.Share.statuses[share.item_source] = {link: false};
+						}
+						if (share.share_type === OC.Share.SHARE_TYPE_LINK) {
+							OC.Share.statuses[share.item_source] = {link: true};
```
Comment (PVince81) [inline core/js/share.js]: Is that all ? I thought there were more statuses returned also for non-link shares ?

Comment (rullzer) [inline core/js/share.js]: yes that is all... at least what the old endpoint returned... in the future we might expand this to more info... since we can show who we shared with in the list now...

**Comment by rullzer** [comment]
Ok reloads working.

Please review: @PVince81 @nickvergessen @schiesbn

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by PVince81** [comment]
In 9.1 we can look into either making this a proper compact summary call, or to actually use the info returned by the share API to display the recipients in the indicator (to do so, set "data-recipients" on the row)

**Comment by MorrisJobke** [comment]
Tested and works :+1:
