### PR TITLE
Fix file permissions for SMB (read-only folders will be writeable)

### LINKED ISSUE #24608: Some sub-Folders on SMB/CIFS External Storage are read only. (You don't have permissions to upload or create files here.)
notes:
this happens both as user with pass-through, or as admin in admin settings.
both users have Full Control on the destination disk and share, also one user is owner of entire folder
(re-applied permissions).
both users can edit the entire share as expected with other clients - like windows explorer or ubuntu unity.
tried ` ./occ files:scan --all ` it completes, but did not help.

### Steps to reproduce
1. create new connection from OwnCloud to an existing SMB share (External Storage)
2. when browsing SMB storage with WebUI some sub-folders are read only.
these display "You don't have permissions to upload or create files here."
but in these 'Read Only' folders, the sub-folders continue to work as expected.
3. syncning with Client shows error - "not allowed because you don't have permission to add files in that folder", but can sync sub-folders of these.

### Expected behavior
Folder and its contents should be changeable by user

### Actual behavior
user can't edit contents of some folders, user can read contents, 
user can edit sub-folders of these read only folders.
user receives;
"You don't have permissions to upload or create files here."
or 
"not allowed because you don't have permission to add files in that folder"

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
Apache 2.4.7
**Database:**
MySQL 5.6
**PHP version:**
PHP 7
**ownCloud version:** (see ownCloud admin page)
9.0.2
**Updated from an older ownCloud or fresh install:**
update or fresh
**Where did you install ownCloud from:**
Ubuntu repo
**Signing status (ownCloud 9.0 and above):**

```
http://example.com/index.php/settings/integrity/failed 
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - agreedisclaimer: 1.0.0
  - comments: 0.2
  - dav: 0.1.6
  - documents: 0.12.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8.1
  - files_reader: 0.7.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - gallery: 14.5.0
  - music: 0.3.11
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
```

**The content of config/config.php:**

```
        "instanceid": "ocxxx15",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "sync2.xxx.com",
            "sync.xxx.com"
        ],
        "datadirectory": "\/mnt\/SYNC-data\/own-data",
        "overwrite.cli.url": "https:\/\/sync2.xxx.com:4443",
        "dbtype": "mysql",
        "dbname": "OC-XXX",
        "dbhost": "127.0.0.1",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "version": "9.0.2.2",
        "logtimezone": "America\/New_York",
        "loglevel": 0,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "ldapIgnoreNamingRules": false,
        "appstore.experimental.enabled": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "knowledgebaseenabled": false,
        "check_for_working_htaccess": true,
        "check_for_working_webdav": true,
        "has_internet_connection": true,
        "filesystem_check_changes": 1,
        "theme": "",
        "maintenance": false,
        "updatechecker": false
```

**Are you using external storage, if yes which one:** 
SFTP and SMB/CIFS

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:** 
no

### Client configuration
**Browser:**
Chrome, IE, Firefox (any)
**Operating system:**
Windows 7-10, 2008-2012. Ubuntu.
#### Web server error log
```
[Thu May 12 04:30:54.819769 2016] [mpm_prefork:notice] [pid 1184] AH00169: caught SIGTERM, shutting down
[Thu May 12 04:35:53.727423 2016] [ssl:warn] [pid 1177] AH01909: RSA certificate configured for owncloud:4443 does NOT include an ID which matches the server name
[Thu May 12 04:35:53.757048 2016] [ssl:warn] [pid 1177] AH01909: RSA certificate configured for owncloud:443 does NOT include an ID which matches the server name
[Thu May 12 04:35:57.320939 2016] [ssl:warn] [pid 1192] AH01909: RSA certificate configured for owncloud:4443 does NOT include an ID which matches the server name
[Thu May 12 04:35:57.321322 2016] [ssl:warn] [pid 1192] AH01909: RSA certificate configured for owncloud:443 does NOT include an ID which matches the server name
[Thu May 12 04:35:57.326638 2016] [mpm_prefork:notice] [pid 1192] AH00163: Apache/2.4.7 (Ubuntu) OpenSSL/1.0.1f configured -- resuming normal operations
[Thu May 12 04:35:57.326667 2016] [core:notice] [pid 1192] AH00094: Command line: '/usr/sbin/apache2'
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"o2E8cO1yOX\/UbAoMgkyU","remoteAddr":"4.1.14.103","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'Desktop\/$RECYCLE.BIN' is not accessible or present !!!","level":0,"time":"2016-05-12T14:39:15-04:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Documents-SMB\/Desktop","user":"A7E378AE-43A2-47CB-9075-9F0FAE1964DB_7507"}
{"reqId":"o2E8cO1yOX\/UbAoMgkyU","remoteAddr":"4.1.14.103","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'Desktop\/desktop.ini' is not accessible or present !!!","level":0,"time":"2016-05-12T14:39:15-04:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Documents-SMB\/Desktop","user":"A7E378AE-43A2-47CB-9075-9F0FAE1964DB_7507"}
{"reqId":"o2E8cO1yOX\/UbAoMgkyU","remoteAddr":"4.1.14.103","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'Desktop\/Thumbs.db' is not accessible or present !!!","level":0,"time":"2016-05-12T14:39:16-04:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Documents-SMB\/Desktop","user":"A7E378AE-43A2-47CB-9075-9F0FAE1964DB_7507"}
{"reqId":"o2E8cO1yOX\/UbAoMgkyU","remoteAddr":"4.1.14.103","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'Desktop\/$RECYCLE.BIN' is not accessible or present !!!","level":0,"time":"2016-05-12T14:39:16-04:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Documents-SMB\/Desktop","user":"A7E378AE-43A2-47CB-9075-9F0FAE1964DB_7507"}
{"reqId":"o2E8cO1yOX\/UbAoMgkyU","remoteAddr":"4.1.14.103","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'Desktop\/desktop.ini' is not accessible or present !!!","level":0,"time":"2016-05-12T14:39:16-04:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Documents-SMB\/Desktop","user":"A7E378AE-43A2-47CB-9075-9F0FAE1964DB_7507"}
{"reqId":"o2E8cO1yOX\/UbAoMgkyU","remoteAddr":"4.1.14.103","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'Desktop\/Thumbs.db' is not accessible or present !!!","level":0,"time":"2016-05-12T14:39:16-04:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Documents-SMB\/Desktop","user":"A7E378AE-43A2-47CB-9075-9F0FAE1964DB_7507"}
{"reqId":"o2E8cO1yOX\/UbAoMgkyU","remoteAddr":"4.1.14.103","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'Desktop\/$RECYCLE.BIN' is not accessible or present !!!","level":0,"time":"2016-05-12T14:39:16-04:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Documents-SMB\/Desktop","user":"A7E378AE-43A2-47CB-9075-9F0FAE1964DB_7507"}
{"reqId":"o2E8cO1yOX\/UbAoMgkyU","remoteAddr":"4.1.14.103","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'Desktop\/desktop.ini' is not accessible or present !!!","level":0,"time":"2016-05-12T14:39:16-04:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Documents-SMB\/Desktop","user":"A7E378AE-43A2-47CB-9075-9F0FAE1964DB_7507"}
{"reqId":"o2E8cO1yOX\/UbAoMgkyU","remoteAddr":"4.1.14.103","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'Desktop\/Thumbs.db' is not accessible or present !!!","level":0,"time":"2016-05-12T14:39:16-04:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Documents-SMB\/Desktop","user":"A7E378AE-43A2-47CB-9075-9F0FAE1964DB_7507"}
{"reqId":"o2E8cO1yOX\/UbAoMgkyU","remoteAddr":"4.1.14.103","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'Desktop\/$RECYCLE.BIN' is not accessible or present !!!","level":0,"time":"2016-05-12T14:39:16-04:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Documents-SMB\/Desktop","user":"A7E378AE-43A2-47CB-9075-9F0FAE1964DB_7507"}
{"reqId":"o2E8cO1yOX\/UbAoMgkyU","remoteAddr":"4.1.14.103","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'Desktop\/desktop.ini' is not accessible or present !!!","level":0,"time":"2016-05-12T14:39:16-04:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Documents-SMB\/Desktop","user":"A7E378AE-43A2-47CB-9075-9F0FAE1964DB_7507"}
{"reqId":"o2E8cO1yOX\/UbAoMgkyU","remoteAddr":"4.1.14.103","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'Desktop\/Thumbs.db' is not accessible or present !!!","level":0,"time":"2016-05-12T14:39:16-04:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Documents-SMB\/Desktop","user":"A7E378AE-43A2-47CB-9075-9F0FAE1964DB_7507"}
{"reqId":"XcFKByAxpG+lWz9Et2zD","remoteAddr":"4.1.14.103","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'Desktop\/$RECYCLE.BIN' is not accessible or present !!!","level":0,"time":"2016-05-12T14:39:16-04:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FDocuments-SMB%2FDesktop","user":"A7E378AE-43A2-47CB-9075-9F0FAE1964DB_7507"}
{"reqId":"XcFKByAxpG+lWz9Et2zD","remoteAddr":"4.1.14.103","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'Desktop\/desktop.ini' is not accessible or present !!!","level":0,"time":"2016-05-12T14:39:16-04:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FDocuments-SMB%2FDesktop","user":"A7E378AE-43A2-47CB-9075-9F0FAE1964DB_7507"}
{"reqId":"XcFKByAxpG+lWz9Et2zD","remoteAddr":"4.1.14.103","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'Desktop\/Thumbs.db' is not accessible or present !!!","level":0,"time":"2016-05-12T14:39:16-04:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FDocuments-SMB%2FDesktop","user":"A7E378AE-43A2-47CB-9075-9F0FAE1964DB_7507"}
{"reqId":"7cj+MxzJYcZhWcZP6gbW","remoteAddr":"4.1.14.103","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'Desktop\/$RECYCLE.BIN' is not accessible or present !!!","level":0,"time":"2016-05-12T14:39:25-04:00","method":"MOVE","url":"\/remote.php\/webdav\/Documents-SMB\/Desktop\/Prime95","user":"A7E378AE-43A2-47CB-9075-9F0FAE1964DB_7507"}
{"reqId":"7cj+MxzJYcZhWcZP6gbW","remoteAddr":"4.1.14.103","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'Desktop\/desktop.ini' is not accessible or present !!!","level":0,"time":"2016-05-12T14:39:25-04:00","method":"MOVE","url":"\/remote.php\/webdav\/Documents-SMB\/Desktop\/Prime95","user":"A7E378AE-43A2-47CB-9075-9F0FAE1964DB_7507"}
{"reqId":"7cj+MxzJYcZhWcZP6gbW","remoteAddr":"4.1.14.103","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'Desktop\/Thumbs.db' is not accessible or present !!!","level":0,"time":"2016-05-12T14:39:25-04:00","method":"MOVE","url":"\/remote.php\/webdav\/Documents-SMB\/Desktop\/Prime95","user":"A7E378AE-43A2-47CB-9075-9F0FAE1964DB_7507"}
{"reqId":"7cj+MxzJYcZhWcZP6gbW","remoteAddr":"4.1.14.103","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 403 Forbidden\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Forbidden\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(640): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree-&gt;move('Documents-SMB\\\/D...', 'Documents-SMB\\\/D...')\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin-&gt;httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter-&gt;emit('method:MOVE', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server-&gt;invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server-&gt;exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/objecttree.php\",\"Line\":218,\"User\":\"A7E378AE-43A2-47CB-9075-9F0FAE1964DB_7507\"}","level":0,"time":"2016-05-12T14:39:25-04:00","method":"MOVE","url":"\/remote.php\/webdav\/Documents-SMB\/Desktop\/Prime95","user":"A7E378AE-43A2-47CB-9075-9F0FAE1964DB_7507"}

```
image

image

image

image

thank you for your time everyone

### PR DESCRIPTION
**Pull request by jvillafanez**
Fix https://github.com/owncloud/core/issues/24608

Backport for OC9 should follow.

### CODE REVIEW

**Comment by icewind1991** [comment]
Shouldn't this also include a check if the path is the share root?

**Comment by jvillafanez** [comment]
It doesn't seems to be needed

**Comment by icewind1991** [comment]
ok, :+1:

File: apps/files_external/lib/Lib/Storage/SMB.php [hunk 1]
```diff
@@ -383,7 +383,7 @@ public function isReadable($path) {
 	public function isUpdatable($path) {
 		try {
 			$info = $this->getFileInfo($path);
-			return !$info->isHidden() && !$info->isReadOnly();
+			return !$info->isHidden() && (!$info->isReadOnly() || $this->is_dir($path));
```
Comment (PVince81) [inline apps/files_external/lib/Lib/Storage/SMB.php]: does readonly still work if the share itself is readonly ?

Comment (jvillafanez) [inline apps/files_external/lib/Lib/Storage/SMB.php]: Uploads will fail anywhere in the share if it's set as read-only. Anyway, I don't think we can't get the share configuration from the client.

Comment (PVince81) [inline apps/files_external/lib/Lib/Storage/SMB.php]: Seems I'm able to stat the share directly, getting this from `$this->share->getStat('')` =>
```
  $result[0]                     = (int) '2094732529';
  $result[1]                     = (int) '-676439979';
  $result[2]                     = (int) '16877';
  $result[3]                     = (int) '2';
  $result[4]                     = (int) '30';
  $result[5]                     = (int) '8';
  $result[6]                     = (int) '0';
  $result[7]                     = (int) '0';
  $result[8]                     = (int) '1467378490';
  $result[9]                     = (int) '1466774556';
  $result[10]                    = (int) '1466774556';
  $result[11]                    = (int) '512';
  $result[12]                    = (int) '0';
  $result['dev']                 = (int) '2094732529';
  $result['ino']                 = (int) '-676439979';
  $result['mode']                = (int) '16877';
  $result['nlink']               = (int) '2';
  $result['uid']                 = (int) '30';
  $result['gid']                 = (int) '8';
  $result['rdev']                = (int) '0';
  $result['size']                = (int) '0';
  $result['atime']               = (int) '1467378490';
  $result['mtime']               = (int) '1466774556';
  $result['ctime']               = (int) '1466774556';
  $result['blksize']             = (int) '512';
  $result['blocks']              = (int) '0';
```

Not sure which is the permission.
But as I see on master we also don't handle share permissions, so might be something to do separately.

**Comment by PVince81** [comment]
Tested, works :+1: 

However I tested only against a Linux Samba server. And to make permissions read-only I did `chmod u-w rofolder`. The folder still appeared read-write in ownCloud, as discussed.
But when uploading there, the Linux Samba didn't accept the file, which is expected due to the permissions.

I hope someone can test against a Windows Server.

**Comment by davitol** [comment]
👍  Using a WND backend located in a windows 2003 server
screen shot 2016-07-04 at 10 44 32

Now applying the patch, it is possible to add files in the R/O Subfolders

screen shot 2016-07-04 at 10 44 55

@jvillafanez will comment ASAP about other scenarios in this PR in order to clarify if it is needed more changes

**Comment by jvillafanez** [comment]
I'm checking if read-only folder can be deleted or not. As it is right now with this PR, all folders can be deleted from ownCloud, but there are errors deleting read-only folders.

We might need to adjust the delete permission.

**Comment by jvillafanez** [comment]
https://support.microsoft.com/en-us/kb/326549
> Note Unlike the Read-only attribute for a file, the Read-only attribute for a folder is typically ignored by Windows, Windows components and accessories, and other programs. For example, you can delete, rename, and change a folder with the Read-only attribute by using Windows Explorer.

I wonder if this still applies if we're accessing through SMB...

**Comment by jvillafanez** [comment]
It seems that it's possible to delete the folder from the windows explorer, but not from the windows console nor from smbclient.

Note that with the current ownCloud implementation, even though the folder isn't being deleted, its contents are deleted (or at least tried to)

**Comment by PVince81** [comment]
@jvillafanez how does Mac OS behave in regards to deleting the mount ?

**Comment by PVince81** [comment]
@jvillafanez any update ? Any risks ?

**Comment by jvillafanez** [comment]
If the SMB server is in windows, the server rejects the deletion of the read-only folder.

Regarding the mounts, they shouldn't be deleted anyway.

I'll have to have a look at the delete permissions.

File: apps/files_external/lib/Lib/Storage/SMB.php [hunk 2]
```diff
@@ -383,6 +383,17 @@ public function isReadable($path) {
 	public function isUpdatable($path) {
 		try {
 			$info = $this->getFileInfo($path);
+			return !$info->isHidden() && (!$info->isReadOnly() || $this->is_dir($path));
```
Comment (PVince81) [inline apps/files_external/lib/Lib/Storage/SMB.php]: a quick comment here would be nice to avoid future devs to scratch their head trying to understand why we allow writing for read-only folders

**Comment by PVince81** [comment]
@davitol mind doing another test against a Windows server in regards to the deletable part ?

**Comment by PVince81** [comment]
SMB tests against a Windows Server still pass:
```
± % ./autotest-external.sh sqlite smb-windows                                                                                              !10112
Using database oc_autotest
Setup environment for sqlite testing ...
Installing ....
ownCloud is not installed - only a limited number of commands are available
{"reqId":"3P008aRwh4IqcM89HenL","remoteAddr":"","app":"PHP","message":"file_put_contents(\/srv\/www\/htdocs\/owncloud\/data\/.htaccess): failed to open stream: Permission denied at \/srv\/www\/htdocs\/owncloud\/lib\/private\/Setup.php#500","level":3,"time":"2016-07-19T09:36:37+00:00","method":"--","url":"--","user":"--"}
{"reqId":"3P008aRwh4IqcM89HenL","remoteAddr":"","app":"PHP","message":"file_put_contents(\/srv\/www\/htdocs\/owncloud\/data\/index.html): failed to open stream: Permission denied at \/srv\/www\/htdocs\/owncloud\/lib\/private\/Setup.php#501","level":3,"time":"2016-07-19T09:36:37+00:00","method":"--","url":"--","user":"--"}
creating sqlite db
ownCloud was successfully installed
{"reqId":"3P008aRwh4IqcM89HenL","remoteAddr":"","app":"PHP","message":"chmod(): Operation not permitted at \/srv\/www\/htdocs\/owncloud\/lib\/private\/Log\/Owncloud.php#114","level":3,"time":"2016-07-19T09:36:38+00:00","method":"--","url":"--","user":"admin"}
Testing with sqlite ...
Run only smb-windows ...
files_external enabled
No coverage
PHPUnit 5.2.6 by Sebastian Bergmann and contributors.

Runtime:       PHP 5.6.23 with Xdebug 2.4.0
Configuration: /srv/www/htdocs/owncloud/tests/phpunit-autotest-external.xml

...............................................................  63 / 189 ( 33%)
............................................................... 126 / 189 ( 66%)
............................................................... 189 / 189 (100%)


Time: 1.68 seconds, Memory: 41.00Mb

OK (189 tests, 689 assertions)
skip: start-amazons3-ceph.sh
skip: start-ftp-morrisjobke.sh
skip: start-sftp-atmoz.sh
skip: start-smb-silvershell.sh
start: start-smb-windows.sh
name: smb-windows

No coverage
PHPUnit 5.2.6 by Sebastian Bergmann and contributors.

Runtime:       PHP 5.6.23 with Xdebug 2.4.0
Configuration: /srv/www/htdocs/owncloud/tests/phpunit-autotest-external.xml

................................................................. 65 / 77 ( 84%)
............                                                      77 / 77 (100%)

Time: 2.71 minutes, Memory: 31.75Mb

OK (77 tests, 346 assertions)
stop: stop-smb-windows.sh
skip: start-swift-ceph.sh
skip: start-webdav-apache.sh
skip: start-webdav-ownCloud.sh
```

Ideally we should add unit tests here, would require to mock the file info bit.

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by jvillafanez** [comment]
Will there be backports for 9.1 and 9.0?

**Comment by PVince81** [comment]
@jvillafanez yes, would be good to backport this to 9.1 and 9.0 if possible.

CC @cdamken @felixboehm

**Comment by cdamken** [comment]
> @jvillafanez yes, would be good to backport this to 9.1 and 9.0 if possible.

Yes, would be great to have them in those versions too! Thanks!
