### PR TITLE
[stable10] Introduce phpstan

### LINKED ISSUE #35773: Undefined variable: self at * Upgrade.php#245
### Steps to reproduce
1. Have installed 10.2.0
2. Use 10.2.1 files
3. Use ./occ upgrade
4. owncloud.log check

### Expected behaviour
No entry ``Undefined`` log

### Actual behaviour
Entry ``Undefined`` log

### Server configuration
**Operating system**: Debian

**Web server:** Nginx

**Database:** MySQL 

**PHP version:** 7.2.19

**ownCloud version:** 10.2.1

**Updated from an older ownCloud or fresh install:** Updated

**Where did you install ownCloud from:** tar.bz2

**Signing status (ownCloud 9.0 and above):** All o.k.

**The content of config/config.php:**

Non-relevant

**List of activated apps:**

Non-relevant

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
Non relevant

#### Web server error log
Non relevant

#### ownCloud log (data/owncloud.log)
```
{"reqId":"7MK26PEod2c4Va6bfJwy","level":3,"time":"2019-07-04T19:50:50+02:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined variable: self at \/var\/www\/owncloud\/core\/Command\/Upgrade.php#245"}
{"reqId":"7MK26PEod2c4Va6bfJwy","level":0,"time":"2019-07-04T19:50:50+02:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"starting upgrade from 10.2.0.5 to 10.2.1.4"}
{"reqId":"7MK26PEod2c4Va6bfJwy","level":3,"time":"2019-07-04T19:50:51+02:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"str_repeat(): Second argument has to be greater than or equal to 0 at \/var\/www\/owncloud\/lib\/composer\/symfony\/console\/Helper\/ProgressBar.php#509"}
```

#### Browser log
Non relevant

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
1) Backport of various commits from PR #31810 
2) Then fix other stuff in `stable10` that `phpstan` reports.

Also fixes #35773 

## Motivation and Context
When trying some things for "drop PHP  7.0" and for PHPunit7 I noticed some problems and ended up in some of the same code that was corrected/adjusted by `master` PR #31810 

Issue 

## How Has This Been Tested?
Local run of:
```
make test-php-phpstan
```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

File: apps/files_sharing/lib/Scanner.php [hunk 1]
```diff
@@ -89,7 +89,7 @@ public function scanFile($file, $reuseExisting = 0, $parentId = -1, $cacheData =
 		$sourceScanner = $this->getSourceScanner();
 		if ($sourceScanner instanceof NoopScanner) {
 			list(, $internalPath) = $this->storage->resolvePath($file);
-			return parent::scan($internalPath, $reuseExisting, $parentId, $cacheData, $lock);
+			return parent::scan($internalPath, self::SCAN_SHALLOW, $reuseExisting, $lock);
```
Comment (phil-davis) [inline apps/files_sharing/lib/Scanner.php]: Does this code ever get called?
The params were wrong.

File: .gitignore [hunk 2]
```diff
@@ -9,6 +9,7 @@
 /build/composer.phar
 /build/dist
 /build/phan.phar
+/build/phpstan.phar*
```
Comment (phil-davis) [inline .gitignore]: Note: this comes from the backport.
Similar to `/build/phan.phar` above it. these files should not even appear in the `build` directory these days - the tools are in `vendor-bin`

But we can remove these later. For now, this gets `stable10` matching `master`

File: apps/encryption/lib/Session.php [hunk 3]
```diff
@@ -78,7 +78,7 @@ public function getStatus() {
 	public function getPrivateKey() {
 		$key = $this->session->get('privateKey');
 		if ($key === null) {
-			throw new Exceptions\PrivateKeyMissingException('please try to log-out and log-in again', 0);
+			throw new Exceptions\PrivateKeyMissingException('please try to log-out and log-in again');
```
Comment (phil-davis) [inline apps/encryption/lib/Session.php]: This is a bit weird, but it happens in other places also - the first parameter is supposed to be the "text" version of the user name. Whatever text is passed ends up getting into the text of the exception.

File: lib/private/Files/External/InvalidStorage.php [hunk 4]
```diff
@@ -26,6 +26,8 @@
 
 class InvalidStorage extends FailedStorage {
 	public function __construct($params) {
+		$params['exception'] = new StorageNotAvailableException();
```
Comment (phil-davis) [inline lib/private/Files/External/InvalidStorage.php]: `php` (and `phpstan`) wants the constructor to have a `$params` arg like `FailedStorage`
But then `phpstan` complains that `$params` is not used.
So this code uses it ;)

File: lib/private/Files/Storage/Temporary.php [hunk 5]
```diff
@@ -29,7 +29,11 @@
  */
 class Temporary extends Local {
 	public function __construct($arguments = null) {
-		parent::__construct(['datadir' => \OC::$server->getTempManager()->getTemporaryFolder()]);
+		if (!\is_array($arguments)) {
+			$arguments = [];
+		}
+		$arguments['datadir'] = \OC::$server->getTempManager()->getTemporaryFolder();
```
Comment (phil-davis) [inline lib/private/Files/Storage/Temporary.php]: `phpstan` complained about unused `$arguments` - so this code uses `$arguments`

File: lib/private/Share/Share.php [hunk 6]
```diff
@@ -640,7 +640,7 @@ public static function shareItem($itemType, $itemSource, $shareType, $shareWith,
 		$l = \OC::$server->getL10N('lib');
 
 		if ($backend->isShareTypeAllowed($shareType) === false) {
-			$message = 'Sharing %s failed, because the backend does not allow shares from type %i';
+			$message = 'Sharing %s failed, because the backend does not allow shares from type %d';
```
Comment (phil-davis) [inline lib/private/Share/Share.php]: This looks like an actual bug. I will fix the same thing in the next line also.

File: lib/private/legacy/util.php [hunk 7]
```diff
@@ -1326,14 +1326,6 @@ public static function clearOpcodeCache() {
 		if (\function_exists('accelerator_reset')) {
 			accelerator_reset();
 		}
-		// XCache
-		if (\function_exists('xcache_clear_cache')) {
```
Comment (phil-davis) [inline lib/private/legacy/util.php]: Is this OK to backport?
Or is there some compatibility issue for old apps or?

File: settings/Middleware/SubadminMiddleware.php [hunk 8]
```diff
@@ -61,7 +61,7 @@ public function __construct(ControllerMethodReflector $reflector,
 	public function beforeController($controller, $methodName) {
 		if (!$this->reflector->hasAnnotation('NoSubadminRequired')) {
 			if (!$this->isSubAdmin) {
-				throw new NotAdminException('Logged in user must be a subadmin');
```
Comment (phil-davis) [inline settings/Middleware/SubadminMiddleware.php]: `NotAdminException` does not accepts any parameter. And it inherits from a parent that has no parameter.
I made a new `NotSubadminException` which can have this text.
Is that the reasonable thing to do?

File: lib/private/legacy/util.php (hunk 7 above)
Comment (DeepDiver1975) [reply lib/private/legacy/util.php]: Xcache is dead. Just kill it

File: lib/private/Share/Share.php (hunk 6 above)
Comment (phil-davis) [reply lib/private/Share/Share.php]: done

File: lib/private/Files/External/InvalidStorage.php (hunk 4 above)
Comment (phil-davis) [reply lib/private/Files/External/InvalidStorage.php]: The mystery is that in `master` the constructor has no parameters, and `phpstan` does not complain in `master` ???

**Comment by micbar** [comment]
Great! Passes CI

**Comment by phil-davis** [comment]
> Great! Passes CI

yes, I fought with that for a bit - there s a list of small commits in this PR that are extra to what happened in `master`. I am currently convincing myself about why `master` passes without those. One of the obvious reasons is that `encryption` is not in `master`.

File: lib/private/Files/External/InvalidStorage.php (hunk 4 above)
Comment (phil-davis) [reply lib/private/Files/External/InvalidStorage.php]: See for answer: https://github.com/owncloud/core/pull/32051#issuecomment-509196336

File: phpstan.neon [hunk 9]
```diff
@@ -22,12 +24,15 @@ parameters:
     - %currentWorkingDirectory%/apps/*/appinfo/routes.php
     - %currentWorkingDirectory%/apps/*/composer/*
     - %currentWorkingDirectory%/apps/*/3rdparty/*
+    - %currentWorkingDirectory%/apps/files/appinfo/update.php
```
Comment (phil-davis) [inline phpstan.neon]: This is because `apps/files/appinfo/update.php` was deleted from `master` by #33209 so it never had to be considered in the `master` PHPstan.

The code is not a class, it is just some old script. It gives:
```
 ------ -------------------------------------------------------------------------------------------------------------------------------- 
  Line   apps/files/appinfo/update.php                                                                                                   
 ------ -------------------------------------------------------------------------------------------------------------------------------- 
  52     Function owncloud_reset_encrypted_flag not found while trying to analyse it - autoloading is probably not configured properly.  
  72     Function owncloud_reset_encrypted_flag not found.                                                                               
  79     Function owncloud_reset_encrypted_flag not found.                                                                               
 ------ -------------------------------------------------------------------------------------------------------------------------------- 

```
and I couldn't work out how to "autoload" it. Seems not worth more time, so ignore it, and maybe delete it in #35781

File: apps/encryption/lib/Session.php (hunk 3 above)
Comment (phil-davis) [reply apps/encryption/lib/Session.php]: This is `encryption` app code - so was not being analyzed by `phpstan` in `master` because it does not exist in `master`

File: apps/files_external/lib/Lib/Storage/AmazonS3.php [hunk 10]
```diff
@@ -73,6 +73,10 @@ class AmazonS3 extends \OCP\Files\Storage\StorageAdapter {
 	 * @var int in seconds
 	 */
 	private $rescanDelay = 10;
+	/**
+	 * @var string
+	 */
+	private $id;
```
Comment (phil-davis) [inline apps/files_external/lib/Lib/Storage/AmazonS3.php]: This whole file does not exist any more in `master` so that is why `phpstan` did not report about it in `master`

File: lib/private/AppFramework/DependencyInjection/DIContainer.php [hunk 11]
```diff
@@ -317,7 +317,7 @@ public function __construct($appName, $urlParams = []) {
 				'Accessing the API class is deprecated! Use the appropriate ' .
 				'services instead!'
 			);
-			return new API($c['AppName']);
+			return new API();
```
Comment (phil-davis) [inline lib/private/AppFramework/DependencyInjection/DIContainer.php]: This code was removed in `master` by PR #33110 
So that is why it only gets noticed in this backport.

File: lib/private/Share/Share.php [hunk 12]
```diff
@@ -640,8 +640,8 @@ public static function shareItem($itemType, $itemSource, $shareType, $shareWith,
 		$l = \OC::$server->getL10N('lib');
 
 		if ($backend->isShareTypeAllowed($shareType) === false) {
-			$message = 'Sharing %s failed, because the backend does not allow shares from type %i';
-			$message_t = $l->t('Sharing %s failed, because the backend does not allow shares from type %i', [$itemSourceName, $shareType]);
+			$message = 'Sharing %s failed, because the backend does not allow shares from type %d';
```
Comment (phil-davis) [inline lib/private/Share/Share.php]: This code was removed in `master` by PR #26608
So that is why `phpstan` did not notice it in `master`

File: settings/Middleware/SubadminMiddleware.php (hunk 8 above)
Comment (phil-davis) [reply settings/Middleware/SubadminMiddleware.php]: This code went to the user_management app and disappeared from core `master` in core PR #30960 
So that is why `phpstan` did not notice it n core `master`

File: phpstan.neon [hunk 13]
```diff
@@ -32,6 +32,7 @@ parameters:
     # specific app excludes
     # eventually move into app directories and use neon includes for better separation
     - %currentWorkingDirectory%/apps/dav/bin
+    - %currentWorkingDirectory%/lib/private/Memcache/APC.php
```
Comment (phil-davis) [inline phpstan.neon]: exclude `APC.php`  for now. 
It will disappear with #34936 when we drop PHP 7.0
(probably we could do the commit to drop APC and xcache now - whatever)

File: lib/private/AppFramework/Core/API.php [hunk 14]
```diff
@@ -167,7 +167,7 @@ public function clearHook($signalClass=false, $signalName=false) {
 	 * @deprecated Use \OC::$server->getJobList()->add();
 	 */
 	public function addRegularTask($className, $methodName) {
-		\OCP\Backgroundjob::addRegularTask($className, $methodName);
+		\OCP\BackgroundJob::addRegularTask($className, $methodName);
```
Comment (phil-davis) [inline lib/private/AppFramework/Core/API.php]: This file was deleted in `master` PRP #33110 
So that is why `phpstan` in `master` did not notice this problem.

**Comment by phil-davis** [comment]
If #35781 and #35782 backports are approved and merged, then I can rebase this and it will remove a couple of not-essential commits.

I have followed up all the extra commits in this PR and noted the reasons that they are needed - mostly because the code here in `stable10` was deleted from `master`.

**Comment by phil-davis** [comment]
Latest CI has a "hung" job that will timeout and get cancelled.
I will restart CI again tomorrow.

**Comment by phil-davis** [comment]
@DeepDiver1975 @micbar @patrickjahns I don't see anything more that I can tidy up here.
It would be nice to fix these things in `stable10` and also get `phpstan` running.

Please review.

**Review by DeepDiver1975 — APPROVED** [review]
