### PR TITLE
When calling file_put_contents clear the checksum

### LINKED ISSUE #23782: TextEditor: Checksum not invalidated on file change
### Steps to reproduce
1. Create a text file with the sync client 
2. Wait until it is synced.
3. Check that it has a checksum in the database, which was sent from the client.
4. Edit the file from the built in texteditor, let it save.
5. See that the checksum of the file has not changed.

### Expected behaviour
When a file is changed, the checksum on the server needs to be recalculated. If that can not be done, it needs at least to be invalidated.

Having a wrong checksum for a file is a critical problem as the client will complain about a corrupted file.

### Server configuration
**Operating system**:
Linux 
**Web server:**
apache 
**Database:**
mysql 
**PHP version:**
5.5.14
**ownCloud version:** (see ownCloud admin page)
9.0.x, master branch, 15833d9843c3ff7c0cb51b95f8610bddb044472d
**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**
git
**Are you using external storage, if yes which one:** local/smb/sftp/...
no external storage
**Are you using encryption:** yes/no
no encryption
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no user-backend.

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #23782 and #23783

If a file is changed we should reset the checksum.
- Unit test added

To test:
- Upload a file with checksum
  `curl -u admin:admin http://localhost/master/remote.php/webdav/foo.txt -X PUT -T foo.txt -H "OC-Checksum: foobar"`
- Check the file cache. This file should have the checksum foobar
- Download the file the OC-Checksum header should be set
- Now edit the file in the texteditor and close it
- Check the file cache. This file should have an empty checksum
- Download the file the OC-Checksum header should not be set

Test 2:
- Upload a file with checksum
  `curl -u admin:admin http://localhost/master/remote.php/webdav/foo.txt -X PUT -T foo.txt -H "OC-Checksum: foobar"`
- Check the file cache. This file should have the checksum foobar
- Download the file the OC-Checksum header should be set
- Now edit the file directly on disk
- Run `./occ files:scan admin`
- Check the file cache. This file should have an empty checksum
- Download the file the OC-Checksum header should not be set

CC: @PVince81 @nickvergessen @MorrisJobke @dragotin

### CODE REVIEW

File: lib/private/files/cache/updater.php [hunk 1]
```diff
@@ -126,6 +126,9 @@ public function update($path, $time = null) {
 			$this->cache->correctFolderSize($path, $data);
 		}
 		$this->correctParentStorageMtime($path);
+		if ($data['mimetype'] !== 'httpd/unix-directory') {
+			$this->clearChecksum($path);
```
Comment (PVince81) [inline lib/private/files/cache/updater.php]: okay, I guess there is no easy way to integrate this change in one of the existing database calls.

@icewind1991 or is there a better moment ?

Comment (rullzer) [inline lib/private/files/cache/updater.php]: Well it gets kind of messy trying to cram this into the scan call I think

Comment (icewind1991) [inline lib/private/files/cache/updater.php]: I think it would make sense in general to clear the checksum in the scanner if it detects a change

Comment (PVince81) [inline lib/private/files/cache/updater.php]: @icewind1991 This will likely be needed too for the other issue https://github.com/owncloud/core/issues/23783 but would it also cover the text editor / file_put_contents issue too ?

Comment (rullzer) [inline lib/private/files/cache/updater.php]: scanFile indeed might be a good place...

**Comment by rullzer** [comment]
Moved the check to the scanFile. Patch is simpler and cleaner.

@PVince81 @icewind1991 please have another look.

**Comment by icewind1991** [comment]
Code looks good :+1:

**Comment by rullzer** [comment]
@karlitschek we should backport this to 9.0.2

**Comment by karlitschek** [comment]
great. fix makes sense. please backport to stable9

**Comment by PVince81** [comment]
- [x] TEST: text editor save clears checksum
- [x] TEST: occ files:scan with unchanged file leaves checksum alone
- [x] TEST: occ files:scan when file was changed directly on disk properly resets checksum

**Comment by PVince81** [comment]
- [x] TEST: file changed remotely on SFTP ext storage, GET the file directly => checksum properly cleared

Looks good :+1:

**Comment by PVince81** [comment]
@rullzer can you prepare the backport PR ?

**Comment by rullzer** [comment]
Backport in #24129
