### PR TITLE
Fixed problem about removing trusted servers accidentally

### LINKED ISSUE #22127: Trusted servers in federation app can be removed without clicking in the trashbin button.
### Steps to reproduce

1. Enable federation app.
2. Make a federation share with another user from other server.
3. Open admin page and go to the federation section.

### Expected behaviour
For deleting the trusted server you need to click on the trashbin icon.

### Actual behaviour
The entire row is a big delete button. This can easily lead to accidental deletions.

screen shot 2016-02-04 at 13 31 36

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.8","versionstring":"9.0 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

```
```

### Client configuration

**browser**
Chrome, Firefox

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
Fixes https://github.com/owncloud/core/issues/22127

Please review @PVince81 @jvillafanez

### CODE REVIEW

File: apps/federation/js/settings-admin.js [hunk 1]
```diff
@@ -56,10 +56,10 @@ $(document).ready(function () {
...
 	});
 
-	// remove trusted server from list
-	$( "#listOfTrustedServers" ).on('click', 'li', function() {
-		var id = $(this).attr('id');
-		var $this = $(this);
+// remove trusted server from list
+	$( "#listOfTrustedServers" ).on('click', 'li > .icon-delete', function() {
+		var id = $(this).parent().attr('id');
+		var $this = $(this).parent();
```
Comment (nickvergessen) [inline apps/federation/js/settings-admin.js]: turn around and then use `var id = $this.attr('id');` ?

**Comment by nickvergessen** [comment]
Works and feels much better :+1:

File: apps/federation/js/settings-admin.js (hunk 1 above)
Comment (SergioBertolinSG) [inline apps/federation/js/settings-admin.js]: The parent's id is the one needed.

**Comment by nickvergessen** [comment]
Newly added items still have the old HTML, needs adjusting in `apps/federation/js/settings-admin.js`

File: apps/federation/js/settings-admin.js (hunk 1 above)
Comment (nickvergessen) [inline apps/federation/js/settings-admin.js]: yes, I know, but that is what you get with:
```js
var $this = $(this).parent(),
	id = $this.attr('id');
```

:wink:

**Comment by nickvergessen** [comment]
Works now, @SergioBertolinSG when you fixed comments, you can leave a comment, so reviewers get another notification and know they can look again :wink:

**Comment by SergioBertolinSG** [comment]
@nickvergessen Sure, sorry.

**Comment by PVince81** [comment]
Code looks good :+1:

File: apps/federation/js/settings-admin.js [hunk 2]
```diff
@@ -56,10 +57,10 @@ $(document).ready(function () {
...
 	});
 
-	// remove trusted server from list
-	$( "#listOfTrustedServers" ).on('click', 'li', function() {
-		var id = $(this).attr('id');
-		var $this = $(this);
+// remove trusted server from list
+	$( "#listOfTrustedServers" ).on('click', 'li > .icon-delete', function() {
+		var $this = $(this).parent();
+		id = $this.attr('id');
```
Comment (MorrisJobke) [inline apps/federation/js/settings-admin.js]: This introduced a global variable. Maybe make it local again to avoid side effects. cc @PVince81 @SergioBertolinSG

Comment (SergioBertolinSG) [inline apps/federation/js/settings-admin.js]: Changed here https://github.com/owncloud/core/pull/25153
