### PR TITLE
 Install new shipped apps on upgrade

### LINKED ISSUE #19925: Webdav broken on master after updating from 8.2
Still broken it seems, likely due to the recent DAV changes:

```
  % curl -D - -X PROPFIND http://localhost/owncloud/remote.php/webdav/                                                                                                                                                               
HTTP/1.0 500 Internal Server Error
Date: Wed, 21 Oct 2015 08:55:05 GMT
Server: Apache/2.4.16 (Linux/SUSE)
X-Powered-By: PHP/5.6.13
Set-Cookie: ockbfur1449k=8vp5co76cea7i55p8iumnj1rfnoeeun4qnjgote4nq6dsi9hhar0; path=/owncloud; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=2vBbuWHMxaj5Nsn%2Ff23hStG1Y%2BR6KtXOJ24FSEdW3lOrsWx61mGLBchS1fRZdPMuNcg4VG5NOfPnxf7QKAWMk3b4hnER7BKE1Vli3eP%2FrVgub7Fc%2BrFS9JxzLT0God7G; path=/owncloud; httponly
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Robots-Tag: none
Content-Length: 0
Connection: close
Content-Type: text/html; charset=UTF-8
```

Logs:
```
{"reqId":"K\/789MGToRAKmV7DxNuB","remoteAddr":"127.0.0.1","app":"PHP","message":"require_once(\/srv\/www\/htdocs\/owncloud\/apps\/files\/appinfo\/remote.php): failed to open stream: No such file or directory at \/srv\/www\/htdocs\/owncloud\/remote.php#137","level":3,"time":"2015-10-21T08:55:59+00:00","method":"OPTIONS","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"K\/789MGToRAKmV7DxNuB","remoteAddr":"127.0.0.1","app":"PHP","message":"require_once(): Failed opening required '\/srv\/www\/htdocs\/owncloud\/apps\/files\/appinfo\/remote.php' (include_path='\/srv\/www\/htdocs\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib:\/srv\/www\/htdocs\/owncloud\/3rdparty\/pear\/console_getopt:\/srv\/www\/htdocs\/owncloud\/3rdparty\/pear\/archive_tar:\/srv\/www\/htdocs\/owncloud\/3rdparty\/pear\/pear_exception:\/srv\/www\/htdocs\/owncloud\/3rdparty\/pear\/pear-core-minimal\/src:\/srv\/www\/htdocs\/owncloud\/lib\/private:\/srv\/www\/htdocs\/owncloud\/config:\/srv\/www\/htdocs\/owncloud\/3rdparty:\/srv\/www\/htdocs\/owncloud\/apps:\/srv\/www\/htdocs\/owncloud\/apps2:\/srv\/www\/htdocs\/owncloud\/apps3:\/srv\/www\/htdocs\/owncloud\/lib:.:\/usr\/share\/php5:\/usr\/share\/php5\/PEAR:\/srv\/www\/htdocs\/owncloud') at \/srv\/www\/htdocs\/owncloud\/remote.php#137","level":3,"time":"2015-10-21T08:55:59+00:00","method":"OPTIONS","url":"\/owncloud\/remote.php\/webdav\/"}
```

This is on master d0aeb268d687f803e62069c852bcd7a1a86eadee which contains the recent fixes.

@DeepDiver1975 can you have a look ?

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #19925

@PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Works now :+1:

**Comment by MorrisJobke** [comment]
This should also increase the version number of core and the dav app is missing a version number.

Besides that :+1:

**Comment by MorrisJobke** [comment]
I added both and now it works :+1:

File: lib/private/updater.php [hunk 1]
```diff
@@ -315,6 +315,9 @@ private function doUpgrade($currentVersion, $installedVersion) {
 		if ($this->updateStepEnabled) {
 			$this->doCoreUpgrade();
 
+			// install new shipped apps on upgrade
+			OC_Installer::installShippedApps();
```
Comment (nickvergessen) [inline lib/private/updater.php]: Awkward! :bomb: :boom: 

This enables all apps again, although you intentionally disabled them, on **every minor** update!
What you actually mean is `installShippedAppsThatAreNotIntentionallyDisabled()`

@DeepDiver1975 @karlitschek

Comment (DeepDiver1975) [inline lib/private/updater.php]: Not really because in enables shipped apps which are not yet installed and are marked as enable_by_default

```php
							if(!OC_Installer::isInstalled($filename)) {
								$info=OC_App::getAppInfo($filename);
								$enabled = isset($info['default_enable']);
								if( $enabled ) {
									OC_Installer::installShippedApp($filename);
									OC_Appconfig::setValue($filename, 'enabled', 'yes');
								}
							}

Comment (PVince81) [inline lib/private/updater.php]: He upgraded and suddenly all apps were enabled (he showed me), including all enterprise ones (which he had checked out), even though they weren't enabled before

Comment (DeepDiver1975) [inline lib/private/updater.php]: > He upgraded and suddenly all apps were enabled (he showed me), including all enterprise ones (which he had checked out), even though they weren't enabled before

grrrrr .... can somebody please debug into this? THX

Comment (nickvergessen) [inline lib/private/updater.php]: Will do tomorrow

Comment (DeepDiver1975) [inline lib/private/updater.php]: THX  @nickvergessen

Comment (nickvergessen) [inline lib/private/updater.php]: Okay, so the problem on my site was that I never had those apps installed. Before installing my oC I change the app directory, so it does not install all those apps.
Now that they have been installed once, they are not enabled anymore, so I guess it works like intended. Normally people don't upload apps they don't enable, this is just a problem when you have one repo with all the apps in it.

:shipit:
