### PR TITLE
Do not lock the encryption key storage

### LINKED ISSUE #16843: Exceptions in server log running test with files_locking enabled
### Steps to reproduce

1. Install 8.1 with encryption and files_locking enabled
2. Run new smashbox test test_dirDepthUpload.py which is currently in the dir-depth-rb-2 branch

### Expected behaviour

Test passes with no errors in the server log

### Actual behaviour

I see the following errors in the server log (this is from two different runs):

```

{"reqId":"jUjdv\/nlXcRqucE8RdOi","remoteAddr":"172.18.5.144","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 files\\\/f9213687e3cf4914be130096c259d91f is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('TEST_FILE_NEW_U...', Resource id #33)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('upload_dir_0\\\/TE...', Resource id #33, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":117}","level":4,"time":"2015-06-09T15:18:50+00:00"}
{"reqId":"F0sVdw+lj6qUZ9waVnat","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:18:54+00:00"}
{"reqId":"WxIlFdgxSYKY8xbj2ev3","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:18:54+00:00"}
{"reqId":"L9bQ\/sl8Q2Y9gCfhjVai","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:18:54+00:00"}
{"reqId":"gGDQRWBef6DhmQqROExL","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:18:54+00:00"}
{"reqId":"Lhi+KR7vMi82tUwyeSC9","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:18:54+00:00"}
{"reqId":"1NXvAtZnGxfSsvjfeZOV","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:18:56+00:00"}
{"reqId":"eYdv8unIGaznwa776Y4F","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:18:58+00:00"}


```

and from a second run:

```

{"reqId":"jlp1GD1dygwOO6VWcfal","remoteAddr":"172.18.5.144","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 files\\\/af523733991f665d733e29a73f3391b0 is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('TEST_FILE_NEW_U...', Resource id #33)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('upload_dir_0\\\/up...', Resource id #33, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":117}","level":4,"time":"2015-06-09T15:15:52+00:00"}
{"reqId":"UvdQLPMR+dpdcj9Mm4CY","remoteAddr":"172.18.5.144","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 files\\\/e003c124b615e6ba30cd568ee0a569e9 is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('TEST_FILE_NEW_U...', Resource id #33)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('upload_dir_0\\\/up...', Resource id #33, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":117}","level":4,"time":"2015-06-09T15:15:52+00:00"}
{"reqId":"KD2GsYB8XOFnOLf5yrqR","remoteAddr":"172.18.5.144","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 files\\\/e6b9a9846c58166a2d6c6fa94d8ad149 is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('TEST_FILE_NEW_U...', Resource id #33)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('upload_dir_0\\\/up...', Resource id #33, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":117}","level":4,"time":"2015-06-09T15:15:52+00:00"}
{"reqId":"t+DVHrjMUu7Ad60RBU03","remoteAddr":"172.18.5.144","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 files\\\/beb747696d9234440a421a43a4b765c7 is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('TEST_FILE_NEW_U...', Resource id #33)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('upload_dir_0\\\/up...', Resource id #33, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":117}","level":4,"time":"2015-06-09T15:15:52+00:00"}
{"reqId":"Yaf7TtZWXhrjJVhWPTOh","remoteAddr":"172.18.5.144","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 files\\\/aeb2519251e150a57ea0b9d24a3b109a is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('TEST_FILE_NEW_U...', Resource id #33)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('upload_dir_0\\\/up...', Resource id #33, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":117}","level":4,"time":"2015-06-09T15:15:52+00:00"}
{"reqId":"OGBthQadmfwFaHNqMd7v","remoteAddr":"172.18.5.144","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 files\\\/30bf02a6a0e939e834186cfbcc274dd7 is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('TEST_FILE_NEW_U...', Resource id #33)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('upload_dir_0\\\/up...', Resource id #33, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":117}","level":4,"time":"2015-06-09T15:15:52+00:00"}
{"reqId":"al5zGraEq\/LQNrqPMNSp","remoteAddr":"172.18.5.144","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 files\\\/b48e7079ffcc4c5335db7479cc5a465e is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('TEST_FILE_NEW_U...', Resource id #33)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('upload_dir_0\\\/up...', Resource id #33, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":117}","level":4,"time":"2015-06-09T15:15:55+00:00"}
{"reqId":"qzEEm80al3js+2R\/I8fR","remoteAddr":"172.18.5.144","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 files\\\/c7cb567e5e3754803c3bd08b809095cc is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('TEST_FILE_NEW_U...', Resource id #33)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('upload_dir_0\\\/up...', Resource id #33, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":117}","level":4,"time":"2015-06-09T15:15:55+00:00"}
{"reqId":"w\/LhncUWYmgcoxNry+Lm","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:15:56+00:00"}
{"reqId":"w5s\/NwMJr\/C\/mx2LMl5B","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:15:56+00:00"}
{"reqId":"dJQmd02ZG\/yruWu83vrM","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:15:56+00:00"}
{"reqId":"\/wRhEk8oSb\/Od2eyXl7Y","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:15:56+00:00"}
{"reqId":"cRTafru0+g+ml8eAdlGp","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:15:57+00:00"}
{"reqId":"x\/q+wHcdg4EPzxyAUtW+","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:15:57+00:00"}
{"reqId":"AfAS\/3ogCPceVPUMIhJV","remoteAddr":"172.18.5.144","app":"PHP","message":"Module 'redis' already loaded at Unknown#0","level":3,"time":"2015-06-09T15:15:57+00:00"}

```

I could not reproduce the error when running the same test with files_locking disabled.

### Server 1 Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 2 (daily) Build:2015-06-08T03:08:20+00:00 35421487610462b12e3600954f23a777c54abee3

### PR DESCRIPTION
**Pull request by nickvergessen**
The question is, whether this PR is the right way to go. There might be other apps that suffer from the same problem. See https://github.com/owncloud/core/issues/16843#issuecomment-111138392 for more details on the problem.

It is mandatory, that we write the encryption keys, when we write the file, because otherwise we might run into data loss?

Fix #16843 

@schiesbn @PVince81 @icewind1991 @DeepDiver1975

### CODE REVIEW

**Comment by nickvergessen** [comment]
If we decide that this is the way to go, I will add unit test (if possible)

File: lib/private/files/view.php [hunk 1]
```diff
@@ -1740,4 +1760,29 @@ public function unlockFile($path, $type) {
...
+	 * Examples:
+	 * 		/user/files_encryption/path-to-file
+	 * 		/files_encryption/path-to-file
+	 *
+	 * @param string $path
+	 * @return bool
+	 */
+	protected function shouldLockFile($path) {
+		$path = Filesystem::normalizePath($path);
+		if (substr_count($path, '/') >= 3) {
```
Comment (PVince81) [inline lib/private/files/view.php]: Might be better to just directly explode it ?

I don't understand the variations of path segment count.

Comment (PVince81) [inline lib/private/files/view.php]: Maybe try using "getAbsolutePath($path)" to get the absolute path, then remove the first section and check the second one.

I think it is correct to have the check here.

@icewind1991 what do you think ?

**Comment by PVince81** [comment]
Or should we make this "opt-in" and limit it to "files" ? And let other apps register their folders (like files_trashbin) to also have locking ?

File: lib/private/files/view.php (hunk 1 above)
Comment (icewind1991) [inline lib/private/files/view.php]: Yes, `getAbsolutePath` is the way to go here

Comment (nickvergessen) [inline lib/private/files/view.php]: Well anyway, the question in first place is, should we filter it like this, or should we jsut only lock files/ anyway?

Comment (icewind1991) [inline lib/private/files/view.php]: I would go with only locking files

**Comment by nickvergessen** [comment]
@schiesbn @PVince81 @icewind1991 updated to use absolute path, return a value and added tests for the new behaviour (and also when absolute path is taken into account)

File: lib/private/files/view.php [hunk 2]
```diff
@@ -1730,14 +1759,46 @@ public function lockFile($path, $type) {
...
+	 * Only lock files in data/user/files/
+	 *
+	 * @param string $path Absolute path to the file/folder we try to (un)lock
+	 * @return bool
+	 */
+	protected function shouldLockFile($path) {
+		$path = Filesystem::normalizePath($path);
+
+		if (substr_count($path, '/') >= 3) {
+			// E.g.: /username/files/path-to-file
```
Comment (PVince81) [inline lib/private/files/view.php]: How about using trim($path, '/') to have a more predictable explode ?
In that case you'd only need a single if.

File: lib/private/files/view.php [hunk 3]
```diff
@@ -1730,14 +1759,46 @@ public function lockFile($path, $type) {
 	 *
 	 * @param string $path the path of the file to lock relative to the view
 	 * @param int $type \OCP\Lock\ILockingProvider::LOCK_SHARED or \OCP\Lock\ILockingProvider::LOCK_EXCLUSIVE
+	 * @return bool False if the path is excluded from locking, true otherwise
 	 */
 	public function unlockFile($path, $type) {
 		$path = rtrim($path, '/');
+
+		$absolutePath = $this->getAbsolutePath($path);
+		if (!$this->shouldLockFile($absolutePath)) {
```
Comment (PVince81) [inline lib/private/files/view.php]: Looks great

File: lib/private/files/view.php (hunk 2 above)
Comment (nickvergessen) [inline lib/private/files/view.php]: the multiple if statements are required because of the `/` after `files`

If we want to combine them, we need to:
```php
return $pathSegments[2] === 'files' || strpos($pathSegments[2], 'files/') === 0;
```

So the question is just where we handle the multiple cases, in the return line or by using 2 if statements

Comment (PVince81) [inline lib/private/files/view.php]: Yes, that's why I suggest that you just strip the "/" at the end in case there is one.
```php
$path = trim($path, '/');
$segments = explode($path, '/'); // no limit
if ($segments[2] === 'files') { ... }
```

Comment (PVince81) [inline lib/private/files/view.php]: no need for strpos

Comment (nickvergessen) [inline lib/private/files/view.php]: Ah i didn't think about removing the limit... will push after jenkins reported

**Comment by nickvergessen** [comment]
Pushed again

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by PVince81** [comment]
Nice. I'll have a quick test soon.
This will fit nicely with my other PR https://github.com/owncloud/core/pull/16892#issuecomment-111443322 (which I will rebase afterwards)

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
Dammit, merged too early ? Here comes the second Jenkins... Let's hope.

**Comment by PVince81** [comment]
Ah no, refresh issue. IGNORE IGNORE
