### PR TITLE
Throw exception if memcache misconfigured or missing

### LINKED ISSUE #16696: Server status shows file locking disabled  even though it's enabled in config.php
### Steps to reproduce

1. Install 8.1 
2. Enable and configure file locking in config.php

### Expected behaviour

Server status on admin page shows that Experimental file lock is enabled

### Actual behaviour

Server status on admin page shows that Experimental file lock is NOT enabled

Scrubbed config.php:

```
<?php
$CONFIG = array (
  'supportedDatabases' =>
  array (
    0 => 'mysql',
    1 => 'pgsql',
    2 => 'oci',
    3 => 'mssql',
  ),
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => 'x.x.x.x',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'http://localhost',
  0 => 'x.x.x.x',
  'dbtype' => 'mysql',
  'version' => '8.1.0.6',
  'dbname' => 'owncloud',
  'dbhost' => 'x.x.x.x',
  'dbtableprefix' => '',
  'dbuser' => 'oc_at_admin',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => '',
  'license-key' => '',
  'filelocking.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '127.0.0.1',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'loglevel' => 0,
  'ldapIgnoreNamingRules' => false,
);


```

p353

### Server 1 Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 2 (daily) Build:2015-06-02T03:08:51+00:00 1acdef5e347e368ca99014084e30c9b69f1df181

### PR DESCRIPTION
**Pull request by PVince81**
Instead of falling back to null memcache, throw exceptions.
Also throw file locking specific exceptions in case the class is not
available.

Fixes https://github.com/owncloud/core/issues/16696

@DeepDiver1975 @icewind1991 @jnfrmarks 

Note, it is very difficult to control how and where the exception message is displayed because sometimes it happens too early. But at least even with a white page there is something in the log.

So here is the new behavior:
1) If file locking is disabled: no error
2) File locking enabled but missing locking cache class: exception in web UI (full page, app not usable)
3) File locking enabled, locking cache configured, but PHP module missing: white page, exception in web UI (full page, app not usable)
4) All enabled, but redis server not running: app is usable but any file operation will return "500 redis went away".
5) If memcache is configured for "local" and "distributed" but the class is missing: white page, exception in log (because autoloading needs it and cannot work, so there is no way to show a page there)

I hope that is enough. Consequently I removed the "Server status" section in the admin page, as the errors can be inferred through other means.

I didn't want to add an extra redis check for EVERY operation because it means we need to connect to redis even when we don't need to.

### CODE REVIEW

**Comment by icewind1991** [comment]
Makes sense :+1:

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Nice ... The link in the @owncloud-bot response is missing ;)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 Nice ... The link in the @owncloud-bot response is missing ;)

click on the red cross on the commit - I have no idea why the link is now missing - this plugin drived me nuts .....

**Comment by DeepDiver1975** [comment]
https://ci.owncloud.org/job/pull-request-analyser-ng-simple/12749/

File: lib/private/memcache/factory.php [hunk 1]
```diff
@@ -62,12 +62,25 @@ public function __construct($globalPrefix,
...
 		}
-		if (!($distributedCacheClass && $distributedCacheClass::isAvailable())) {
+		if (!$distributedCacheClass) {
 			$distributedCacheClass = $localCacheClass;
 		}
+
+		if (!$localCacheClass::isAvailable()) {
+			throw new \OC\HintException(
+				'Missing memcache class ' . $localCacheClass . ' for local cache',
+				'Is the matching PHP module installed and enabled ?'
```
Comment (nickvergessen) [inline lib/private/memcache/factory.php]: Should be translatable?

File: lib/private/memcache/factory.php [hunk 2]
```diff
@@ -62,12 +62,25 @@ public function __construct($globalPrefix,
...
 			$localCacheClass = self::NULL_CACHE;
 		}
-		if (!($distributedCacheClass && $distributedCacheClass::isAvailable())) {
+		if (!$distributedCacheClass) {
 			$distributedCacheClass = $localCacheClass;
 		}
+
+		if (!$localCacheClass::isAvailable()) {
+			throw new \OC\HintException(
+				'Missing memcache class ' . $localCacheClass . ' for local cache',
```
Comment (nickvergessen) [inline lib/private/memcache/factory.php]: Should be translatable?

File: lib/private/memcache/factory.php [hunk 3]
```diff
@@ -62,12 +62,25 @@ public function __construct($globalPrefix,
...
+				'Is the matching PHP module installed and enabled ?'
+			);
+		}
+		if (!$distributedCacheClass::isAvailable()) {
+			throw new \OC\HintException(
+				'Missing memcache class ' . $distributedCacheClass . ' for distributed cache',
```
Comment (nickvergessen) [inline lib/private/memcache/factory.php]: Should be translatable?

File: lib/private/memcache/factory.php [hunk 4]
```diff
@@ -62,12 +62,25 @@ public function __construct($globalPrefix,
...
+				'Is the matching PHP module installed and enabled ?'
```
Comment (nickvergessen) [inline lib/private/memcache/factory.php]: Should be translatable?

File: lib/private/server.php [hunk 5]
```diff
@@ -431,6 +431,10 @@ public function __construct($webRoot) {
 				if (!($memcache instanceof \OC\Memcache\NullCache)) {
 					return new MemcacheLockingProvider($memcache);
 				}
+				throw new HintException(
+					'File locking is enabled but the locking cache class was not found',
```
Comment (nickvergessen) [inline lib/private/server.php]: Should be translatable?

File: lib/private/server.php [hunk 6]
```diff
@@ -431,6 +431,10 @@ public function __construct($webRoot) {
...
+					'Please check the "memcache.locking" setting and make sure the matching PHP module is installed and enabled'
```
Comment (nickvergessen) [inline lib/private/server.php]: Should be translatable?

File: settings/templates/admin.php [hunk 7]
```diff
@@ -528,18 +528,6 @@
 		<li><a target="_blank" href="<?php p(link_to_docs('admin-security')); ?>"><?php p($l->t('Hardening and security guidance'));?> ↗</a></li>
 	</ul>
 </div>
-<div class="section" id="server-status">
-	<h2><?php p($l->t('Server Status'));?></h2>
-	<ul>
-		<li>
-			<?php if ($_['fileLockingEnabled']) {
-				p($l->t('Experimental File Lock is enabled.'));
```
Comment (nickvergessen) [inline settings/templates/admin.php]: Hu, why is this removed?
And if removing is correct, how about removing the related code in settings/admin.php as well?

File: lib/private/memcache/factory.php (hunk 1 above)
Comment (PVince81) [inline lib/private/memcache/factory.php]: Most other env-related HintException did not have translated strings for some reason, not sure why.

File: settings/templates/admin.php (hunk 7 above)
Comment (PVince81) [inline settings/templates/admin.php]: Ah, I missed removing the other part.

Now that you mention it, it might make sense to still show it.
The difference would be that the "enabled" value only matches the config.php setting "filelocking.enabled".
Because if there is a config issue you cannot reach this page due to the new exceptions.

I'll bring it back for now.

**Comment by PVince81** [comment]
- [ ] translated hint exceptions
- [ ] bring back the "server status" setting

**Comment by PVince81** [comment]
After discussion on IRC, I decided to not translate the HintExceptions which are admin-only, just like other ones.

I added back the section in the admin page.

Please review.

**Comment by nickvergessen** [comment]
The exceptions seem little helpful.
If I configure redis correctly I get the normal page.
Then I change the available method to require a higher version then I have:
```php
	static public function isAvailable() {
		return extension_loaded('redis')
			&& version_compare(phpversion('redis'), 9.9.9', '>=');
	}
```
and I just get a blank page?

**Comment by PVince81** [comment]
See the different cases here: https://github.com/owncloud/core/pull/16832#issue-86599544
In some, we are able to show an exception. In some we aren't.

I seem to have forgotten the wrong redis version check. I'd expect that one to show a HintException, but only if you use Redis for the locking cache, not the other ones.
Any setup issue with the "local" or "distributed" cache will cause a white page, because we need those for autoloader.

**Comment by PVince81** [comment]
@nickvergessen I tried changing the required version to 9.9.9 and I get an error page:
"File locking is enabled but the locking cache class was not found
Please check the "memcache.locking" setting and make sure the matching PHP module is installed and enabled"

I suspect you probably set redis for the "local" and/or "distributed" cache. In the latter case it is not possible to show an error page because autoloading cannot work.

The purpose of this PR is mostly to show an error page or an exception in the log in case file locking was misconfigured.

Please have another look @nickvergessen @DeepDiver1975

File: lib/private/memcache/factory.php (hunk 1 above)
Comment (DeepDiver1975) [inline lib/private/memcache/factory.php]: Because it requires the server to be up and running to properly read translation strings and apply translation logic - if there are issues during initialization of the server -> :boom:

**Comment by DeepDiver1975** [comment]
> Please have another look @nickvergessen @DeepDiver1975

THX :+1:

**Comment by DeepDiver1975** [comment]
waiting on @nickvergessen to comment on https://github.com/owncloud/core/pull/16832#issuecomment-112000084

**Comment by nickvergessen** [comment]
:+1: I indeed had it also set for `memcache.distributed`, works when its only set for locking

**Comment by blizzz** [comment]
This throws an exception with occ for me (OC\HintException: [0]: Missing memcache class \OC\Memcache\APCu for local cache (Is the matching PHP module installed and enabled ?)), while web interface is working.

**Comment by nickvergessen** [comment]
Make sure your php.ini for cli loads the module aswell?

**Comment by blizzz** [comment]
Doh. The module was loaded, but a config switch missing m(
