### PR TITLE
fixed overwriting templates through themes

### LINKED ISSUE #18243: Problem with override
I'm trying to override
/settings/templates/users/part.userlist.php

With
/themes/MyTheme/core/settings/templates/users/part.userlist.php
Css is overriding, but I can't override php

The same with

/settings/js/users/users.js
and
/themes/MyTheme/core/settings/js/users/users.js

Is this a bug? Or I'm doing something wrong?

### PR DESCRIPTION
**Pull request by phisch**
## Description
This change allows themes to override php templates. Your theme can live inside an app `apps/my-theme-app` or inside the themes directory `themes/my-theme`. If you want to override an app template, you would mimic its file location inside your theme directory e.g. `apps/my-theme-app/apps/files/templates/list.php`. Overwriting core templates works the same way, e.g. `themes/my-theme/settings/templates/users/part.userlist.php` or `apps/my-theme-app/core/templates/login.php`. Just mimic the directory of the template you want to override, no exceptions or anything.

## Related Issue
fixes #18243

## Motivation and Context
Inside templates the `OC_Template:inc` method is used to render other templates. This method ignores themes. This means those templates could not be overwritten by themes.

## How Has This Been Tested?
This is testes manually, automated testing might require the presence of a theme, not entirely sure what the best way to test this would be.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

@DeepDiver1975 @butonic @PVince81

### CODE REVIEW

File: lib/private/Template/Base.php [hunk 1]
```diff
@@ -156,20 +174,20 @@ public function fetchPage($additionalParams = null) {
 	 * @param string $file
 	 * @param array|null $additionalParams
 	 * @return string content
+	 * @throws \Exception
 	 *
 	 * Includes the template file, fetches its output
 	 */
 	protected function load($file, $additionalParams = null) {
-		// Register the variables
+		// This variables will be used inside templates, they are not unused!
```
Comment (PVince81) [inline lib/private/Template/Base.php]: ah, got it. "not unused". Maybe add "do not remove!"

**Comment by PVince81** [comment]
Makes sense 👍 
Took me a while to find the core of the fix in `inc` and when I found it I remembered that you mentioned it in your comment.

File: lib/private/Template/Base.php (hunk 1 above)
Comment (PhilippSchaffrath) [inline lib/private/Template/Base.php]: I got confused because it looks like they are unused. But they are used inside templates. Just wanted to add a comment so it's more clear what is happening here.
