### PR TITLE
[IE9] Don't send link share password placeholder

### LINKED ISSUE #16511: [IE9] Password is lost from the textbox when clicking in the textbox of shared link
### Steps to reproduce
1. Try a file to a user of another server by link.
2. Write down a password
3. Click again in the textbox of the link

### Expected behaviour

Password should be kept

### Actual behaviour
Password disappears. (gif below with the behaviour)

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Internet Explorer 9 & Firefox

pwdlost

### PR DESCRIPTION
**Pull request by PVince81**
When exiting the password field in the share dialog, IE9 would
mistakenly think that the password has changed and would send the
placeholder.

This fix prevents changing the password whenever the placeholder is set
as value.

Fixes https://github.com/owncloud/core/issues/16511#issuecomment-148668819

@davitol @MorrisJobke @rullzer @nickvergessen

### CODE REVIEW

File: core/js/sharedialoglinkshareview.js [hunk 1]
```diff
@@ -157,7 +154,8 @@
 			var $input = this.$el.find('#linkPassText');
 			$input.removeClass('error');
 			var password = $input.val();
-			if(password === '') {
+			// in IE9 the password might be the placeholder due to bugs in the placeholders polyfill
```
Comment (MorrisJobke) [inline core/js/sharedialoglinkshareview.js]: In my case the placeholder is the translated string of the placeholder an not stars. Therefore it still sends the request with the placeholder as password

Comment (PVince81) [inline core/js/sharedialoglinkshareview.js]: Weird, I never see anything else than stars after setting the password.

What are your exact steps ?

Comment (MorrisJobke) [inline core/js/sharedialoglinkshareview.js]: Yes. After setting the password. The trick with IE8-10 is: To have placeholders the input fields get the placeholder text assigned as value (looks like the placeholder is there) and then once they get focus the value is vanished and the actual typed in text is used as value. To be able to do the same with password fields they are on the fly migrated to usual inout fields. Get then the text of the placeholder as value (it looks like a placeholder text) and on focus they are converted to password fields to not reveal the password in the plain input field. Therefore you need to check for the translated version of the placeholder ;)

**Comment by PVince81** [comment]
@MorrisJobke I added the second message too, please try again

**Comment by PVince81** [comment]
Okay, need to solve conflicts first

**Comment by PVince81** [comment]
Here we go, ready to review @MorrisJobke @rullzer @nickvergessen

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by davitol** [comment]
:+1:

**Comment by MorrisJobke** [comment]
The original issue was filed against 8.2.1 #16511 

@karlitschek Is this okay to backport?

**Comment by karlitschek** [comment]
@MorrisJobke Please backport

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/core/pull/20101
