### PR TITLE
[For 10.4] Include expiration option for user and group shares

### LINKED ISSUE #36545: Test: the fields of the last response should not include does not work with 'expiration' field
The following step does not work if we try to check for `ANY_VALUE`:
```feature
Then the fields of the last response should not include
  | expiration | ANY_VALUE |
```

### Analysis:
[This is due to how `strtotime()` works](https://www.php.net/manual/en/function.strtotime.php#refsect1-function.strtotime-returnvalues). This needs to be handled somewhere here:
https://github.com/owncloud/core/blob/f37a6dc2774d54c16b3fe9b9cff30138bc4a23d7/tests/acceptance/features/bootstrap/Sharing.php#L662-L671

strtotime is passed `ANY_VALUE` which when fails returns `FALSE`. That, when passed to `date()` 
returns the Unix epoch (i.e. 1st January 1970), and the content to assert is no longer `ANY_VALUE`.

This when passed to `doesFieldValueMatchExpectedContent()` then returns false even though the field is still there.

https://github.com/owncloud/core/blob/f37a6dc2774d54c16b3fe9b9cff30138bc4a23d7/tests/acceptance/features/bootstrap/Sharing.php#L629-L645

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
This is a re-submit of PR #36324 and then PR #36531 with the commits squashed and rebased to the current master (that has "drop PHP 7.0" and phpunit7).

Please work on top of this in a separate branch for making acceptance tests or fixing bugs. Then we need to cherry-pick tests and bugs fixes into here in a controlled manner so that we do not write over each other's work.

Excerpt from the feature file:

* As a user I want to set an expiration date for collaborators in order to stay in control of access permissions by giving time-based access instead of granting access forever or until I manually remove the collaborator.
* As a user I want to automatically limit my responsibility for a guest account. Guests are bound to being a collaborator. If they are not a collaborator of any resource, they can't log in anymore.
* As an admin I want to set a default expiration date without enforcement to give a recommendation to users and help them maintain control over their resources. Still, I don't want to force or annoy users as some may have reasons to collaborate on resources for a longer or unrestricted amount of time, e.g., in projects.
* As an admin I have to follow corporate policies which dictate that data exchange between employees or also with externals may only take place for a certain maximum amount of time to prevent data leaks by human mistake or negligence.

## Related Issue
- Fixes https://github.com/owncloud/enterprise/issues/2001
- Fixes #36545 [Acceptance tests related]

## How Has This Been Tested?
CI acceptance tests added for:
- [x] new capabilities added in capabilities API
- [x] setting/clearing the new user and group expiration settings in the admin sharing settings UI page
- [x] sharing with users and groups with/without expiration date on the UI
- [x] using the sharing API to directly share/reshare/change share with default or specified expiry dates

## Screenshots:
Anmerkung 2019-11-11 133034

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
@individual-it acceptance tests are done. Please have a quick review (code should be the same as the previous PR) of test code.

**Comment by phil-davis** [comment]
@micbar @PVince81 please allocate whoever is appropriate to review the run-time code

**Comment by phil-davis** [comment]
Outstanding things to sort out:
- [ ] issue #36568 - when these `expireDate` options are off, a client can still send API requests to create a share with an expire date. The API responds with success and has set an expire date.
- [ ] issue #36569 - the default expire days can be set to zero `0`. That results in shares getting created that expire today (I guess they will expire at midnight today).

**Comment by micbar** [comment]
@phil-davis 
We clarified the requirements here:

This feature should not disabled
The settins only have an influence on
- setting a default value
- enforcing it

The UI part will be always hidden in a dropdown.

Does that clarify it?

**Comment by jvillafanez** [comment]
Trying to clarify a bit the couple of issues:

> issue #36568 - when these expireDate options are off, a client can still send API requests to create a share with an expire date. The API responds with success and has set an expire date.

There is no option to enable or disable the feature. The checkbox in the setting page is to set or not a default date and to enforce or not such default date as max date. If the checkbox is unchecked, it means that there is no default date set (or it should be ignored), but you can still set the expiration date normally.
From my point of view, it's fine that the clients can send API requests with any date, taking into account that the feature will be always enabled.

>  issue #36569 - the default expire days can be set to zero 0. That results in shares getting created that expire today (I guess they will expire at midnight today).

Personally, I don't think this is bad assuming it works. I also have some doubts about the current behaviour: it might expire at the beginning of the day, so it might be "expired on creation", but I don't think it will be much of a problem as long as the admin doesn't enforce it.
You can think that the admin, without enforcing a maximum date, is trying to force you to either set a different date or explicitly remove the expiration.

I agree we should probably control that scenario, but I don't think it's critical because if 0 is allowed I guess anyone can expect that the shares will expire today. It might not be useful, but as long as it doesn't break anything and the behaviour is clear I think we can live with that.

**Comment by phil-davis** [comment]
Re: 0 expire days and issue #36569  - see item 5 in #36550 where a decision was made that 0 is not allowed. (I am just pointing to where the decision was made, for information. IMO @jvillafanez analysis above is also valid)

**Comment by phil-davis** [comment]
I have merged the changes from #36587 and squashed this PR. CI should be good. Final reviews are needed.

File: core/js/sharedialogshareelistview.js [hunk 1]
```diff
@@ -384,6 +425,47 @@
...
+		onRemoveExpiration: function(event) {
+			var shareId = $(event.target).closest('li').data('share-id');
+
+			this.model.updateShare( shareId, {
+				expireDate: null
+			});
+		},
+
+		onToggleShareDetails: function() {
+			var $target = $(event.target);
```
Comment (jvillafanez) [inline core/js/sharedialogshareelistview.js]: I'm missing an "event" variable here.

File: core/img/actions/time.svg:Zone.Identifier [hunk 2]
```diff
@@ -0,0 +1,4 @@
+[ZoneTransfer]
```
Comment (jvillafanez) [inline core/img/actions/time.svg:Zone.Identifier]: What do we need this file for?

File: core/js/sharedialogshareelistview.js [hunk 3]
```diff
@@ -240,6 +269,8 @@
 		},
 
 		render: function() {
+			var self =this;
```
Comment (jvillafanez) [inline core/js/sharedialogshareelistview.js]: in case you touch this file, include a space `var self = this;`

File: core/js/sharedialogshareelistview.js [hunk 4]
```diff
@@ -384,6 +425,47 @@
...
+			$el.datepicker({
+				minDate: "+1d",
+				dateFormat : 'dd-mm-yy',
+				onSelect : function() {
+					self._onExpirationChange(el)
+				}
+			});
+
+			if (params.enforced)
+				$el.datepicker( "option", "maxDate", "+" + params.maxDate + 'd' );
```
Comment (jvillafanez) [inline core/js/sharedialogshareelistview.js]: code block here
```
if (....) {
  ....
}
```

**Comment by jvillafanez** [comment]
I haven't checked the acceptance tests.

**Comment by phil-davis** [comment]
@felixheidecke tests are passing, so I believe this works.
Can you respond to the review comments please?

File: tests/acceptance/features/apiShareManagementBasic/createShare.feature [hunk 5]
```diff
@@ -1619,3 +1619,664 @@ Feature: sharing
...
+      | file_target | /FOLDER  |
+      | uid_owner   | user0    |
+      | expiration  | +15 days |
+      | share_with  | user1    |
+    Examples:
+      | ocs_api_version | ocs_status_code | http_status_code |
+      | 1               | 100             | 200              |
+      | 2               | 200             | 200              |
+
+  @skipOnOcV10.3 @issue-36568
```
Comment (individual-it) [inline tests/acceptance/features/apiShareManagementBasic/createShare.feature]: that issue is out-of-date

File: tests/acceptance/features/apiShareManagementBasic/createShare.feature [hunk 6]
```diff
@@ -1619,3 +1619,664 @@ Feature: sharing
...
+    Given using OCS API version "<ocs_api_version>"
+    And user "user1" has been created with default attributes and without skeleton files
+    When user "user0" creates a share using the sharing API with settings
+      | path        | /FOLDER    |
+      | shareType   | user       |
+      | shareWith   | user1      |
+      | permissions | read,share |
+      | expireDate  | +15 days   |
+    Then the OCS status code should be "<ocs_status_code>"
+    # And the HTTP status code should be "400"
```
Comment (individual-it) [inline tests/acceptance/features/apiShareManagementBasic/createShare.feature]: 400 is not expected any-more

File: tests/acceptance/features/apiShareManagementBasic/createShare.feature [hunk 7]
```diff
@@ -1619,3 +1619,664 @@ Feature: sharing
...
+      | uid_owner   | user0    |
+      | share_with  | user1    |
+      | expiration  | +15 days |
+    Examples:
+      | ocs_api_version | ocs_status_code | http_status_code |
+      | 1               | 100             | 200              |
+      | 2               | 200             | 200              |
+
+  @skipOnOcV10.3
+  Scenario Outline: sharing with expiration date is enabled but not enforced, user shares with expiration date and then disables
```
Comment (individual-it) [inline tests/acceptance/features/apiShareManagementBasic/createShare.feature]:
```suggestion
  Scenario Outline: sharing with default expiration date set but not enforced, user shares with expiration date and then default expiration date is unset
```

File: tests/acceptance/features/apiShareManagementBasic/createShare.feature [hunk 8]
```diff
@@ -1619,3 +1619,664 @@ Feature: sharing
...
+    And user "user0" gets the info of the last share using the sharing API
+    Then the fields of the last response should include
+      | expiration | +30 days |
+    Examples:
+      | ocs_api_version |
+      | 1               |
+      | 2               |
+
+  @skipOnOcV10.3
+  Scenario Outline: sharing with expiration date enforced for users, user shares to the group
```
Comment (individual-it) [inline tests/acceptance/features/apiShareManagementBasic/createShare.feature]:
```suggestion
  Scenario Outline: sharing with expiration date enforced for users, user shares to a group without setting an expiration date
```

File: tests/acceptance/features/apiShareReshare/reShare.feature [hunk 9]
```diff
@@ -530,3 +530,286 @@ Feature: sharing
...
+    And the OCS status code should be "<ocs_status_code>"
+    And the information of the last share of user "user1" should include
+      | expiration | +3 days |
+    Examples:
+      | ocs_api_version | ocs_status_code |
+      | 1               | 100             |
+      | 2               | 200             |
+
+  @skipOnOcV10.3
+  Scenario Outline: Default expiration date for resharing with user using the sharing API with expire days set
```
Comment (individual-it) [inline tests/acceptance/features/apiShareReshare/reShare.feature]: confusing, sounds like there is an expiration date only for resharing

File: tests/acceptance/features/bootstrap/Sharing.php [hunk 10]
```diff
@@ -209,8 +208,15 @@ public function userCreatesAShareWithSettings($user, $body) {
 			} else {
 				$fd['shareType'] = null;
 			}
-		}
 
+			Assert::assertFalse(
+				isset($fd['expireDate'], $fd['expireDateAsString']),
```
Comment (individual-it) [inline tests/acceptance/features/bootstrap/Sharing.php]: expireDateAsString  is not documented as possible option in the table

File: tests/acceptance/features/bootstrap/WebUISharingContext.php [hunk 11]
```diff
@@ -170,37 +170,132 @@ public function theUserSharesFileFolderWithUserUsingTheWebUI(
...
+	 * @param string $days
+	 * @param string $type
+	 * @param string $receiver
+	 *
+	 * @return void
+	 * @throws Exception
+	 */
+	public function expirationDateShouldBe($days, $type, $receiver) {
+		if (\strtotime($days) !== false) {
+			Assert::assertEquals(\date('d-m-Y', \strtotime($days)), $this->sharingDialog->getExpirationDateFor($receiver, $type));
```
Comment (individual-it) [inline tests/acceptance/features/bootstrap/WebUISharingContext.php]: line too long

File: tests/acceptance/features/bootstrap/WebUISharingContext.php [hunk 12]
```diff
@@ -228,6 +323,45 @@ public function theUserSharesFileFolderWithUserOrGroupUsingTheWebUI(
...
+	 * @param string $folder
+	 * @param string $group
+	 * @param int $maxRetries
+	 * @param bool $quiet
+	 *
+	 * @return void
+	 * @throws \Exception
+	 */
+	public function theUserSharesFileFolderWithGroupUsingTheWebUI(
+		$folder, $group, $maxRetries = STANDARD_RETRY_COUNT, $quiet = false
```
Comment (individual-it) [inline tests/acceptance/features/bootstrap/WebUISharingContext.php]:
```suggestion
		resource, $group, $maxRetries = STANDARD_RETRY_COUNT, $quiet = false
```

File: tests/acceptance/features/bootstrap/WebUISharingContext.php [hunk 13]
```diff
@@ -228,6 +323,45 @@ public function theUserSharesFileFolderWithUserOrGroupUsingTheWebUI(
...
+	 * @param string $remote
+	 * @param string $name
+	 * @param int $maxRetries
+	 * @param bool $quiet
+	 *
+	 * @return void
+	 * @throws \Exception
+	 */
+	public function theUserSharesFileFolderWithUserOrGroupUsingTheWebUI(
+		$folder, $userOrGroup, $remote, $name, $maxRetries = STANDARD_RETRY_COUNT, $quiet = false
```
Comment (individual-it) [inline tests/acceptance/features/bootstrap/WebUISharingContext.php]:
```suggestion
		$resource, $userOrGroup, $remote, $name, $maxRetries = STANDARD_RETRY_COUNT, $quiet = false
```

File: tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature [hunk 14]
```diff
@@ -152,3 +152,85 @@ Feature: admin sharing settings
     And the administrator has browsed to the admin sharing settings page
     When the administrator disables add server automatically once a federation share was created successfully using the webUI
     Then the config key "autoAddServers" of app "federation" should have value "0"
+
+  @skipOnOcV10.3
+  Scenario: enable default expiration date for user shares
```
Comment (individual-it) [inline tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature]:
```suggestion
  Scenario: set default expiration date for user shares
```

File: tests/acceptance/features/webUISharingExternal/federationSharing.feature [hunk 15]
```diff
@@ -278,8 +278,8 @@ Feature: Federation Sharing - sharing with users on other cloud storages
     And user "user1" re-logs in to "%remote_server%" using the webUI
     And the user accepts the offered remote shares using the webUI
     And user "user1" from server "REMOTE" shares "/simple-folder (2)" with user "user2" from server "LOCAL" using the sharing API
-    And the user sets the sharing permissions of user "user2@%local_server%/ (federated)" for "simple-folder (2)" using the webUI to
```
Comment (individual-it) [inline tests/acceptance/features/webUISharingExternal/federationSharing.feature]: why do we change that existing test?

File: tests/acceptance/features/webUISharingInternalGroups/shareWithGroupUsingExpirationDate.feature [hunk 16]
```diff
@@ -0,0 +1,285 @@
...
+      | user1    |
+      | user2    |
+    And user "user3" has been created with default attributes and skeleton files
+    And these groups have been created:
+      | groupname |
+      | grp1      |
+    And user "user1" has been added to group "grp1"
+    And user "user2" has been added to group "grp1"
+
+  Scenario: expiration date is disabled for sharing with groups, user shares with a group
```
Comment (individual-it) [inline tests/acceptance/features/webUISharingInternalGroups/shareWithGroupUsingExpirationDate.feature]:
```suggestion
  Scenario: default expiration date is not set for sharing with groups, user shares with a group
```

**Review by individual-it — DISMISSED** [review]
Most comments I made are about wording, specially because now the expiration date is not enabled/disabled but the default-expiration date can be set or not
Please apply the comments also to similar places in the rest of the feature files, I did not comment every single line

Additionally it would be good to also check if the share really was created or not, checking only the response might not be enough

File: tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature (hunk 14 above)
Comment (phil-davis) [reply tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature]: IMO this is OK - this scenario enables the "default expiration date" feature, without actually setting the expiration days. (the expiration days defaults to 7)

File: tests/acceptance/features/webUISharingExternal/federationSharing.feature (hunk 15 above)
Comment (phil-davis) [reply tests/acceptance/features/webUISharingExternal/federationSharing.feature]: The federated server is running daily-master-qa and/or latest (10.3.2 release) during CI. The way that the sharing permissions "dropdown" is opened has changed in this PR, so the code is trying to click-to-open with a changed xpath. So this step does not work like that on the "old" federated server.

So it has been changed do it it with the API.

In the long-term we actually cannot rely on the UI on the federated server. We should refactor any webUI scenarios so that they never actually login to the webUI on the remote federated server. For scenarios like this, that do webUI actions on both of the local and remote servers, the scenario will have to be split into 2 scenarios... I raised issue https://github.com/owncloud/core/issues/36607

File: tests/acceptance/features/apiShareManagementBasic/createShare.feature (hunk 5 above)
Comment (phil-davis) [reply tests/acceptance/features/apiShareManagementBasic/createShare.feature]: fix coming

File: tests/acceptance/features/apiShareManagementBasic/createShare.feature [hunk 17]
```diff
@@ -1619,3 +1619,664 @@ Feature: sharing
...
+      | uid_owner   | user0    |
+      | expiration  | +15 days |
+      | share_with  | user1    |
+    Examples:
+      | ocs_api_version | ocs_status_code | http_status_code |
+      | 1               | 100             | 200              |
+      | 2               | 200             | 200              |
+
+  @skipOnOcV10.3 @issue-36568
+  Scenario Outline: sharing with expiration date is not enabled, user shares with expiration date set
```
[the remark this answers is not in the document]
Comment (phil-davis) [reply tests/acceptance/features/apiShareManagementBasic/createShare.feature]: fix coming - we are adding the word "default" but keeping "enabled" as discussed

File: tests/acceptance/features/apiShareManagementBasic/createShare.feature [hunk 18]
```diff
@@ -1619,3 +1619,664 @@ Feature: sharing
     When the public downloads file "parent.txt" from inside the last public shared folder using the old public WebDAV API
     Then the value of the item "//s:message" in the response should be ""
     And the HTTP status code should be "404"
+
+  @skipOnOcV10.3
+  Scenario Outline: sharing with expiration date enabled but not enforced, user shares without specifying expireDate
```
[the remark this answers is not in the document]
Comment (phil-davis) [reply tests/acceptance/features/apiShareManagementBasic/createShare.feature]: fix coming - we are adding the word "default" but keeping "enabled" as discussed

File: tests/acceptance/features/apiShareManagementBasic/createShare.feature (hunk 6 above)
Comment (phil-davis) [reply tests/acceptance/features/apiShareManagementBasic/createShare.feature]: fix coming

File: tests/acceptance/features/apiShareManagementBasic/createShare.feature (hunk 7 above)
Comment (phil-davis) [reply tests/acceptance/features/apiShareManagementBasic/createShare.feature]: fix coming - we are adding the word "default" but keeping "enabled" as discussed

File: tests/acceptance/features/apiShareManagementBasic/createShare.feature (hunk 8 above)
Comment (phil-davis) [reply tests/acceptance/features/apiShareManagementBasic/createShare.feature]: fix coming

File: tests/acceptance/features/apiShareReshare/reShare.feature (hunk 9 above)
Comment (phil-davis) [reply tests/acceptance/features/apiShareReshare/reShare.feature]: adjusted the scenario descriptions in all these added scenarios

File: tests/acceptance/features/bootstrap/WebUISharingContext.php (hunk 12 above)
Comment (skshetry) [reply tests/acceptance/features/bootstrap/WebUISharingContext.php]: This function was split. I'd suggest we do this in the separate PR, instead of working on this PR itself, as it has gotten too large. We can create a separate issue with the list of fixes required after this PR is merged.

**Comment by phil-davis** [comment]
@felixheidecke still getting JS test failing https://drone.owncloud.com/owncloud/core/22056/7/6

**Comment by phil-davis** [comment]
I cherry-picked the code from #36609 just now.

**Comment by phil-davis** [comment]
IMO CI will pass and this now works.
Time for somebody to review and (hopefully) approve.

**Comment by individual-it** [comment]
Tests look good :+1:

**Comment by phil-davis** [comment]
I just merged PR #36572 "Add share indicator in webUI"
That has some conflicts here - resolving that now...

File: core/js/sharedialogshareelistview.js (hunk 1 above)
Comment (PVince81) [reply core/js/sharedialogshareelistview.js]: seems this is likely not covered by tests, so might not even be working

File: tests/acceptance/features/bootstrap/WebUISharingContext.php (hunk 13 above)
Comment (phil-davis) [reply tests/acceptance/features/bootstrap/WebUISharingContext.php]: This is a general var name refactoring that we can do separately some day.

**Review by lordelix — APPROVED** [review]

File: tests/acceptance/features/apiShareManagementBasic/createShare.feature [hunk 19]
```diff
@@ -1619,3 +1619,715 @@ Feature: sharing
...
+      | expiration  | +15 days |
+      | share_with  | grp1     |
+    And the response when user "user1" gets the info of the last share should include
+      | expiration | +15 days |
+    Examples:
+      | ocs_api_version | ocs_status_code | http_status_code |
+      | 1               | 100             | 200              |
+      | 2               | 200             | 200              |
+
+  @skipOnOcV10.3 @issue-36568
```
Comment (PVince81) [inline tests/acceptance/features/apiShareManagementBasic/createShare.feature]: seems https://github.com/owncloud/core/issues/36568 is closed now ?

**Review by PVince81 — COMMENTED** [review]
In general looks fine to me except for:
- the weird file with svg+suffix as extension
- the function that uses `event` but has none define which is likely broken

File: tests/acceptance/features/apiShareManagementBasic/createShare.feature [hunk 20]
```diff
@@ -1619,3 +1619,715 @@ Feature: sharing
...
+    And group "grp1" has been created
+    And user "user1" has been added to group "grp1"
+    When user "user0" creates a share using the sharing API with settings
+      | path        | /FOLDER    |
+      | shareType   | group      |
+      | shareWith   | grp1       |
+      | permissions | read,share |
+      | expireDate  | +15 days   |
+    Then the OCS status code should be "<ocs_status_code>"
+    # And the HTTP status code should be "400"
```
Comment (phil-davis) [inline tests/acceptance/features/apiShareManagementBasic/createShare.feature]: And I had removed one of these yesterday, missed this one.
At this stage probably best to merge this PR and then I will make a little PR to cleanup the "crud" in this scneario.

File: tests/acceptance/features/apiShareManagementBasic/createShare.feature (hunk 19 above)
Comment (phil-davis) [reply tests/acceptance/features/apiShareManagementBasic/createShare.feature]: hmmm - yes, we decided that was expected behaviour.
See my other comment below - I can make a little PR after this one to cleanup this.

**Comment by phil-davis** [comment]
> In general looks fine to me except for:
> 
>     * the weird file with svg+suffix as extension
> 
>     * the function that uses `event` but has none define which is likely broken

@felixheidecke or whoever is the dev who knows about this code, please respond to this and other outstanding comments.

File: core/js/sharedialogshareelistview.js (hunk 3 above)
Comment (phil-davis) [reply core/js/sharedialogshareelistview.js]: fixed it just now

File: core/js/sharedialogshareelistview.js (hunk 4 above)
Comment (phil-davis) [reply core/js/sharedialogshareelistview.js]: fixed it just now

File: tests/acceptance/features/apiShareManagementBasic/createShare.feature (hunk 19 above)
Comment (phil-davis) [reply tests/acceptance/features/apiShareManagementBasic/createShare.feature]: fixed it just now

File: tests/acceptance/features/apiShareManagementBasic/createShare.feature (hunk 20 above)
Comment (phil-davis) [reply tests/acceptance/features/apiShareManagementBasic/createShare.feature]: fixed it just now

**Comment by felixheidecke** [comment]
Aaaaand done!

File: core/js/sharedialogshareelistview.js (hunk 1 above)
Comment (felixheidecke) [reply core/js/sharedialogshareelistview.js]: It works without passing `event` in. I guess it's already available within the method.
Added it for stringency.
