### PR TITLE
Prevent certain DBs throwing exceptions on same-value updates

### LINKED ISSUE #23123: Unable to login via LDAP, exception OCP\PreConditionNotMetException
### Steps to reproduce
1. Upgrade from 8.x to 9.0.0
2. Attempt to log in

### Expected behaviour
Login successful

### Actual behaviour
Login unsuccessful

### Server configuration
**Operating system**: CentOS 7, fully patched.

**Web server:** Apache httpd-2.4.6-40.el7.centos.x86_64

**Database:** MariaDB mariadb-5.5.44-2.el7.centos.x86_64

**PHP version:** php-5.4.16-36.el7_1.x86_64

**ownCloud version:** (see ownCloud admin page) 9.0.0 (stable)

**Updated from an older ownCloud or fresh install:** Updated.

**Where did you install ownCloud from:** Owncloud YUM repository

**Signing status (ownCloud 9.0 and above):** Good

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - announcementcenter: true
  - calendar: true
  - comments: 0.2
  - contacts: true
  - dav: 0.1.5
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_external: 0.4
  - user_ldap: 0.8.0
Disabled:
  - encryption
  - ownnote
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "5154b2aca4681",
        "check_for_working_htaccess": true,
        "datadirectory": "\/srv\/owncloud",
        "dbtype": "mysql",
        "dbname": "ownCloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "mysql01.mossholder.com",
        "dbtableprefix": "oc_",
        "forcessl": true,
        "installed": true,
        "loglevel": 0,
        "maintenance": false,
        "mail_from_address": "mail",
        "mail_smtpmode": "php",
        "mail_domain": "mossholder.com",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "overwritewebroot": "\/owncloud",
        "overwrite.cli.url": "\/owncloud",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbdriveroptions": {
            "1012": "\/etc\/ipa\/ca.crt"
        },
        "updatechecker": false,
        "trusted_domains": [
            "home.mossholder.com"
        ],
        "theme": "",
        "version": "9.0.0.19"
    }
}

```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)

```
+-------------------------------+---------------------------------------------+
| Configuration                 |                                             |
+-------------------------------+---------------------------------------------+
| hasMemberOfFilterSupport      |                                             |
| hasPagedResultSupport         |                                             |
| homeFolderNamingRule          | attr:uid                                    |
| lastJpegPhotoLookup           | 0                                           |
| ldapAgentName                 |                                             |
| ldapAgentPassword             | ***                                         |
| ldapAttributesForGroupSearch  |                                             |
| ldapAttributesForUserSearch   |                                             |
| ldapBackupHost                |                                             |
| ldapBackupPort                |                                             |
| ldapBase                      | dc=mossholder,dc=com                        |
| ldapBaseGroups                | cn=groups,cn=accounts,dc=mossholder,dc=com  |
| ldapBaseUsers                 | cn=users,cn=accounts,dc=mossholder,dc=com   |
| ldapCacheTTL                  | 600                                         |
| ldapConfigurationActive       | 1                                           |
| ldapDynamicGroupMemberURL     |                                             |
| ldapEmailAttribute            | mail                                        |
| ldapExperiencedAdmin          | 0                                           |
| ldapExpertUUIDGroupAttr       | ipaUniqueID                                 |
| ldapExpertUUIDUserAttr        | ipaUniqueID                                 |
| ldapExpertUsernameAttr        | uid                                         |
| ldapGroupDisplayName          | cn                                          |
| ldapGroupFilter               | (|(objectclass=posixgroup))      |
| ldapGroupFilterGroups         |                                             |
| ldapGroupFilterMode           | 1                                           |
| ldapGroupFilterObjectclass    | nestedgroup                                 |
| ldapGroupMemberAssocAttr      | uniqueMember                                |
| ldapHost                      | ldaps://ipa01.mossholder.com/               |
| ldapIgnoreNamingRules         |                                             |
| ldapLoginFilter               | (&(|(objectclass=inetorgperson))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                             |
| ldapLoginFilterEmail          | 0                                           |
| ldapLoginFilterMode           | 0                                           |
| ldapLoginFilterUsername       | 1                                           |
| ldapNestedGroups              | 1                                           |
| ldapOverrideMainServer        | 0                                           |
| ldapPagingSize                | 500                                         |
| ldapPort                      | 636                                         |
| ldapQuotaAttribute            |                                             |
| ldapQuotaDefault              |                                             |
| ldapTLS                       | 0                                           |
| ldapUserDisplayName           | displayname                                 |
| ldapUserDisplayName2          |                                             |
| ldapUserFilter                | (|(objectclass=inetorgperson))  |
| ldapUserFilterGroups          |                                             |
| ldapUserFilterMode            | 1                                           |
| ldapUserFilterObjectclass     | inetorgperson                               |
| ldapUuidGroupAttribute        | auto                                        |
| ldapUuidUserAttribute         | auto                                        |
| turnOffCertCheck              | 0                                           |
| useMemberOfToDetectMembership | 1                                           |
+-------------------------------+---------------------------------------------+
```

### Client configuration
**Browser:**  Firefox, Chrome

**Operating system:** Linux, Mac, Windows 7

#### Web server error log
```
192.251.13.62 - - [10/Mar/2016:15:50:11 -0500] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:50:41 -0500] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:51:11 -0500] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:51:41 -0500] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:52:11 -0500] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:52:41 -0500] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:53:11 -0500] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:53:22 -0500] "GET /owncloud/index.php?logout=true&requesttoken=FQAcfCILFCMQPggACh8%2FM3c%2FPQVHOjszEQsgZRRALho%3D%3AltmMTmbmHhZnPvOy2QmghwcWSsMJE8XmV26%2B2R%2BFfZQ%3D HTTP/1.1" 302 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:53:22 -0500] "GET /owncloud/ HTTP/1.1" 200 10833 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:53:22 -0500] "GET /owncloud/core/vendor/jsTimezoneDetect/jstz.js?v=e2ca0d2c7ee45de3475b8c5d1d6ada1d HTTP/1.1" 304 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:53:22 -0500] "GET /owncloud/index.php/core/js/oc.js?v=e2ca0d2c7ee45de3475b8c5d1d6ada1d HTTP/1.1" 200 2956 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:53:22 -0500] "GET /owncloud/core/js/visitortimezone.js?v=e2ca0d2c7ee45de3475b8c5d1d6ada1d HTTP/1.1" 304 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:53:22 -0500] "GET /owncloud/core/js/lostpassword.js?v=e2ca0d2c7ee45de3475b8c5d1d6ada1d HTTP/1.1" 304 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:53:22 -0500] "GET /owncloud/core/js/login.js?v=e2ca0d2c7ee45de3475b8c5d1d6ada1d HTTP/1.1" 304 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:53:28 -0500] "POST /owncloud/ HTTP/1.1" 200 10891 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
192.251.13.62 - - [10/Mar/2016:15:53:28 -0500] "GET /owncloud/index.php/core/js/oc.js?v=e2ca0d2c7ee45de3475b8c5d1d6ada1d HTTP/1.1" 200 2956 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"

```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VuHeyHbCr8YW0RaWOJ2KhQAAAAQ","remoteAddr":"192.251.13.62","app":"user_ldap","message":"Exception: {\"Exception\":\"OCP\\\\PreConditionNotMetException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/allconfig.php(222): OC\\\\DB\\\\Connection->setValues('preferences', Array, Array, Array)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/user\\\/user.php(368): OC\\\\AllConfig->setUserValue('mattcm', 'user_ldap', 'displayName', 'Matt Mossholder')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/user\\\/user.php(383): OCA\\\\user_ldap\\\\lib\\\\user\\\\User->store('displayName', 'Matt Mossholder')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/user\\\/user.php(182): OCA\\\\user_ldap\\\\lib\\\\user\\\\User->composeAndStoreDisplayName('Matt Mossholder')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(732): OCA\\\\user_ldap\\\\lib\\\\user\\\\User->processAttributes(Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(705): OCA\\\\user_ldap\\\\lib\\\\Access->batchApplyUserAttributes(Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(678): OCA\\\\user_ldap\\\\lib\\\\Access->fetchListOfUsers('(&(|(objectclas...', Array)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php(103): OCA\\\\user_ldap\\\\lib\\\\Access->fetchUsersByLoginName('mattcm', Array, 1)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php(120): OCA\\\\user_ldap\\\\USER_LDAP->getLDAPUserByLoginName('mattcm')\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/user\\\/manager.php(183): OCA\\\\user_ldap\\\\USER_LDAP->checkPassword(*** username and password replaced ***)\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/user\\\/session.php(219): OC\\\\User\\\\Manager->checkPassword(*** username and password replaced ***)\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/user.php(162): OC\\\\User\\\\Session->login(*** username and password replaced ***)\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(1073): OC_User::login(*** username and password replaced ***)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(969): OC::tryFormLogin()\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(931): OC::handleLogin()\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php\",\"Line\":297}","level":3,"time":"2016-03-10T20:53:28+00:00","method":"POST","url":"\/owncloud\/"}
{"reqId":"VuHeyHbCr8YW0RaWOJ2KhQAAAAQ","remoteAddr":"192.251.13.62","app":"core","message":"Login failed: 'mattcm' (Remote IP: '192.251.13.62')","level":2,"time":"2016-03-10T20:53:28+00:00","method":"POST","url":"\/owncloud\/"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
A PreconditionNotMetException must only be thrown if explicit preconditions are specified for setValues(), not if the value is merely the same as was already in the DB.

The new test doesn't fail for me locally, but has been reported to be an issue elsewhere in this scenario ( #23123 ). The key point is that certain DBs may optimize updates to not affect any rows, which incorrectly causes a PreconditionNotMetException to be thrown (even though no preconditions were set). We should only throw that exception if there are preconditions set.

The test changes were to make the state a bit more consistent, so that the test table is always destroyed after every test.

Fixes #23123 hopefully, waiting on testing feedback from user.

cc @blizzz @DeepDiver1975

### CODE REVIEW

**Comment by blizzz** [comment]
Code looks good, and i am still able to log in :D :+1:

**Comment by blizzz** [comment]
Tested successfully by @mossholderm (https://github.com/owncloud/core/issues/23123#issuecomment-195569625), counting as :+1:

**Comment by blizzz** [comment]
@karlitschek i vote for backport to stable9, fixes login issues in some setups. OK?

**Comment by karlitschek** [comment]
@DeepDiver1975 what is your opinion about a backport?

File: lib/private/db/connection.php [hunk 1]
```diff
@@ -293,7 +293,7 @@ public function setValues($table, array $keys, array $values, array $updatePreco
 			$updateQb->where($where);
 			$affected = $updateQb->execute();
 
-			if ($affected === 0) {
+			if ($affected === 0 && $updatePreconditionValues) {
```
Comment (LukasReschke) [inline lib/private/db/connection.php]: Scrutinizer:

> The expression $updatePreconditionValues of type array is implicitly converted to a boolean; are you sure this is intended? If so, consider using  ! empty($expr) instead to make it clear that you intend to check for an array without elements.

Comment (Xenopathic) [inline lib/private/db/connection.php]: The expressions are entirely equivalent... this version is semantically more useful though IMHO

**Comment by cmonteroluque** [comment]
ok to backport?

File: lib/private/db/connection.php (hunk 1 above)
Comment (icewind1991) [inline lib/private/db/connection.php]: I would prefer the explicit empty

**Comment by DeepDiver1975** [comment]
> what is your opinion about a backport?

should not hurt and has been proven to fix a live issue 

@blizzz please open backport prs - THX

**Comment by DeepDiver1975** [comment]
Waiting for ci until merge ....

**Comment by DeepDiver1975** [comment]
rebased - I want all db ci jobs green on this one

**Comment by MorrisJobke** [comment]
> rebased - I want all db ci jobs green on this one

Rebased again. I will open a swift test fix PR later.

**Comment by blizzz** [comment]
Backport to stable9 goes here: https://github.com/owncloud/core/pull/23309
