### PR TITLE
[Tests-Only] Reporting expected failures when running a single feature

### LINKED ISSUE #37815: Reporting of unexpected failures when running just a single feature
If a developer runs just a single feature, e.g. putting
```
make test-acceptance-api BEHAT_FEATURE=tests/acceptance/features/apiComments/editComments.feature
```

and `EXPECTED_FAILURES_FILE` is defined,

then `tests/acceptance/run.sh` does understand to check just the expected failures for the `apiComments` suite - that is a good start.

But it will also report about expected failures in other feature files like `apiComments/createComments.feature`

1) Make it smarter so that when running just a single feature, it only processes expected failure for the feature.
2) Make it even smarter so that when running just a single scenario, it only processes expected failure for that exact scenario line number (if that is not "too hard" to do)

### PR DESCRIPTION
**Pull request by swoichha**
## Description
Reporting log when running just a single feature or single scenario that are listed in `expected-failure.txt`. Previously we used to get the log about scenarios that were actually running and also for scenarios that were not running but were listed in `expected-failure`.

## Related Issue
- Fixes https://github.com/owncloud/core/issues/37815

## How Has This Been Tested?
- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

File: tests/acceptance/run.sh [hunk 1]
```diff
@@ -1228,8 +1228,17 @@ else
...
+  for unexpected_passed_value in "${UNEXPECTED_PASSED_SCENARIOS[@]}"
+  do
+    if [[ $unexpected_passed_value != *"${BEHAT_FEATURE}"* ]]
+    then
+     tput setaf 3; echo "runsh: There were no unexpected passed scenarios throughout the test run."
+    else
+      tput setaf 3; echo "runsh: Total unexpected passed scenarios throughout the test run:"
+      tput setaf 1; printf "%s\n" "${UNEXPECTED_PASSED_SCENARIOS[@]}"
+    fi
+  done
```
Comment (kiranparajuli589) [inline tests/acceptance/run.sh:1240]: IMO Logging inside the for loop will be confusing.
```suggestion
    ACTUAL_UNEXPECTED_PASS=()
    # if running a single scenario
    if [[ -n "${BEHAT_FEATURE}" && "${BEHAT_FEATURE}" == *":"* ]]
        then
            for unexpected_passed_value in "${UNEXPECTED_PASSED_SCENARIOS[@]}"
            do
                # check only for the running feature
                if [[ $unexpected_passed_value != *"${BEHAT_FEATURE}"* ]]
                then
                    ACTUAL_UNEXPECTED_PASS+="${unexpected_passed_value}"
                fi
            done
    else
        ACTUAL_UNEXPECTED_PASS="${UNEXPECTED_PASSED_SCENARIOS[@]}"
    fi
    tput setaf 3; echo "runsh: Total unexpected passed scenarios throughout the test run:"
    tput setaf 1; printf "%s\n" "${ACTUAL_UNEXPECTED_PASS[@]}"
```

Comment (swoichha) [reply tests/acceptance/run.sh]: Yes, that would be confusing. But now it has been fixed.

File: tests/acceptance/run.sh [hunk 2]
```diff
@@ -1229,8 +1229,25 @@ else
...
 if [ "${UNEXPECTED_SUCCESS}" = true ]
 then
+  ACTUAL_UNEXPECTED_PASS=()
+  # if running a single scenario
+  if [[ -n "${BEHAT_FEATURE}" && "${BEHAT_FEATURE}" == *":"* ]]
+  then
+    for unexpected_passed_value in "${UNEXPECTED_PASSED_SCENARIOS[@]}"
+    do
+      # check only for the running feature
+      if [[ $unexpected_passed_value != *"${BEHAT_FEATURE}"* ]]
```
Comment (phil-davis) [inline tests/acceptance/run.sh:1239]: Should this be the other way around? We want to add the to ACTUAL_UNEXPECTED_PASS if it is the BEHAT_FEATURE.

Also,
- I think BEHAT_FEATURE is set to something like `tests/acceptance/features/apiComments/comments.feature:42` but the "unexpected" array will have just `apiComments/comments.feature:42` in it. See code that calculates `SUITE_SCENARIO` from the end of a path.
- it needs to not match entries like `apiComments/comments.feature:421` - the last `*` here is probably not needed.

It might be easier to use the bash regex-match operator `=~` - then you can match strings exactly at the start or end. See examples in `run.sh` that use `=~`

Or actually I think that after extracting the ``apiComments/comments.feature:42` part from BEHAT_FEATURE then you can check for an exact match - no need for "glob *" or regex.

Comment (swoichha) [reply tests/acceptance/run.sh:1239]: `BEHAT_FEATURE` is set to `apiComments/comments.feature:42` as well. So, I think we can directly check for an exact match using`==` by removing the first and last `*` from `*"${BEHAT_FEATURE}"* ]]`

File: tests/acceptance/run.sh [hunk 3]
```diff
@@ -1229,8 +1229,25 @@ else
 fi
 if [ "${UNEXPECTED_SUCCESS}" = true ]
 then
+  ACTUAL_UNEXPECTED_PASS=()
+  # if running a single scenario
+  if [[ -n "${BEHAT_FEATURE}" && "${BEHAT_FEATURE}" == *":"* ]]
```
Comment (kiranparajuli589) [inline tests/acceptance/run.sh:1234]:
```suggestion
  # if running a single feature
  if [[ -n "${BEHAT_FEATURE}" && "${BEHAT_FEATURE}" != *":"* ]]
```

**Comment by kiranparajuli589** [comment]
lgtm :+1:

**Review by kiranparajuli589 — COMMENTED** [review]
lgtm

**Review by phil-davis — APPROVED** [review]
