### PR TITLE
Fix search operations for the Node API

### LINKED ISSUE #19544: Node API: search operations don't work on the top folder of external shares
### Steps to reproduce

```
$folder = $this->rootFolder->get('/admin/files/mounted_external_owncloud')
$result = $folder->searchByMime('image')
var_dump($result);
```

### Expected result

An array full of Files

### Actual result

An empty result

### Notes

Querying a sub-folder works...

```
$folder = $this->rootFolder->get('/admin/files/mounted_external_owncloud/subfolder')
$result = $folder->searchByMime('image')
var_dump($result);
```

@icewind1991 @PVince81

### PR DESCRIPTION
**Pull request by oparoz**
Fix for _Node API: search operations don't work on the top folder of external shares_
Fixes https://github.com/owncloud/core/issues/19544
- [x] Add test to cover this case

@icewind1991 @PVince81 @Xenopathic @nickvergessen if you could let me know if you have any objection.

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by PVince81** [comment]
Maybe one day we'll need some good utility functions to avoid all these unreliable string gymnastics.

:+1:

**Comment by DeepDiver1975** [comment]
@karlitschek  requesting backport - this is broken since 8.0

**Comment by karlitschek** [comment]
please backport!

**Comment by DeepDiver1975** [comment]
@oparoz can you come up with unit tests? THX

**Comment by oparoz** [comment]
> @oparoz can you come up with unit tests? THX

I want to, but if someone could point me in the right direction when it comes to easily mock a mounted share. None of the test in that class use one and apparently they behave differently.

**Comment by DeepDiver1975** [comment]
> I want to, but if someone could point me in the right direction when it comes to easily mock a mounted share. None of the test in that class use one and apparently they behave differently.

@nickvergessen mind helping out here? THX

**Comment by nickvergessen** [comment]
hi @oparoz please poke me on IRC when you got time, will help with the tests then

File: lib/private/files/node/folder.php [hunk 1]
```diff
@@ -222,7 +222,7 @@ private function searchCommon($method, $args) {
 
 		$results = call_user_func_array(array($cache, $method), $args);
 		foreach ($results as $result) {
-			if ($internalRootLength === 0 or substr($result['path'], 0, $internalRootLength) === $internalPath) {
+			if ($internalRootLength === 1 or substr($result['path'], 0, $internalRootLength) === $internalPath) {
 				$result['internalPath'] = $result['path'];
 				$result['path'] = substr($result['path'], $internalRootLength);
```
Comment (nickvergessen) [inline lib/private/files/node/folder.php]: this needs fixing as well

Comment (nickvergessen) [inline lib/private/files/node/folder.php]: https://gist.github.com/nickvergessen/99922e71746849f1f2a8

Comment (icewind1991) [inline lib/private/files/node/folder.php]: I think the current way is correct

Comment (nickvergessen) [inline lib/private/files/node/folder.php]:
```
1) Test\Files\Node\Folder::testSearch
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'/bar/foo/qwerty'
+'/bar/foo/oo/qwerty'
```

Unit test says no

Comment (icewind1991) [inline lib/private/files/node/folder.php]: They run fine for me (and jenkins)...

Comment (nickvergessen) [inline lib/private/files/node/folder.php]: there are no tests yet, so in my patch you can see the one line i changed in the test file.
@oparoz will copy that test so we have it for both values, empty and non-empty

Comment (icewind1991) [inline lib/private/files/node/folder.php]: Ok I added an extra unit test to test this specific case and that fails

```
Failed asserting that two strings are equal.
Expected :/bar/foo/qwerty
Actual   :/bar/oo/qwerty
```

Your proposed solution is still incorrect from what I can tell

**Comment by icewind1991** [comment]
Ok, I changed the fix for the original issue to correct the value for `$internalPath` so the `substr` is done correctly

**Comment by oparoz** [comment]
Works for me :+1:

**Comment by DeepDiver1975** [comment]
failing unit test should pass once rebased ....


````
Test_Files_Sharing_Mount::testShareMountLoseParentFolder
Failed asserting that 8 is identical to 1.

/ssd/jenkins/workspace/core-ci-linux@2/database/sqlite/label/SLAVE/apps/files_sharing/tests/sharedmount.php:74

**Comment by icewind1991** [comment]
oracle is being stubborn again

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@oparoz can I ask you to open a backport pr? THX

**Comment by oparoz** [comment]
@DeepDiver1975 OK

**Comment by oparoz** [comment]
Computer says no

> fetch origin fix-search-for-node-api:fix-search-for-node-api
fatal: Couldn't find remote ref fix-search-for-node-api
Unexpected end of command stream

**Comment by icewind1991** [comment]
Cherry pick the commits instead

**Comment by oparoz** [comment]
Ah, from master... OK
