### PR TITLE
fix computerFileSize to parse correctly, prerapation to fix #25358

### LINKED ISSUE #25358: Improve quota validation including a regexp which matches expected formats
Curently an admin user can enter a number probably followed by letters.
For example: "200", "15MB" or "5 GB" "20B".
Basically it's a number probably followed by letters.

Also floating point can be entered, but only in english style "2.5GB". Using a non english format for floats will lead to an old bug "4,5GB" also something like "45/0". 

So the proposed enhancement by @PVince81 in https://github.com/owncloud/core/pull/25253 is to develop a regexp to validate better this values.

### PR DESCRIPTION
**Pull request by individual-it**
## Description
I've added some more tests for computerFileSize and they would fail, so fixed
the function to be more picky on what input to accept and try to parse and also fixed the rounding of values without units

## Motivation and Context
@PVince81 mentioned this function in the context of fixing #25358 but it does not work correct
1. input of "B" would return "NaN" and not null
2. invalid values like "40/0" or "40,30 kb" would be parsed
3. negative values would be parsed and returned as negative values
4. values without unit would not be rounded to full bytes. 125.5 would return 125.5, but I don't think oC runs on 4bit systems :-)

That are exact the problems we have in #25358
After this PR is accepted I'm happy to look into fixing #25358

## How Has This Been Tested?
wrote more tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: core/js/tests/specs/coreSpec.js [hunk 1]
```diff
@@ -605,7 +611,14 @@ describe('Core base tests', function() {
 					['119.2 GB', 127990025421],
 					['119.2gb', 127990025421],
 					['116.4 TB', 127983153473126],
-					['116.4tb', 127983153473126]
+					['116.4tb', 127983153473126],
+					['8776656778888777655.4tb', 9.650036181387265e+30],
```
Comment (PVince81) [inline core/js/tests/specs/coreSpec.js]: Looks like we're already ready for the next century's storage requirements 😆

File: core/js/js.js [hunk 2]
```diff
@@ -1770,12 +1766,18 @@ OC.Util = {
 			'p': 1024 * 1024 * 1024 * 1024 * 1024
 		};
 
-		var matches = s.match(/([kmgtp]?b?)$/i);
-		if (matches[1]) {
-			bytes = bytes * bytesArray[matches[1]];
+		var matches = s.match(/^[\s+]?([0-9]*)(\.([0-9]+))?( +)?([kmgtp]?b?)$/i);
```
Comment (PVince81) [inline core/js/js.js]: I suggest to pre-create the regexp and store it in a hidden variable `this._computerFileSizeRegexp` or so.
I'm not sure if modern Javascript engines recompile the Regexp every time or whether it already caches it somewhere.

To be safe, store it somewhere so if this function is called in a loop it will run a bit faster.

File: core/js/tests/specs/coreSpec.js (hunk 1 above)
Comment (individual-it) [inline core/js/tests/specs/coreSpec.js]: living in the foothills of the Himalayas I know about huge clouds, so better be prepared, who knows what the climate change will bring ;-)

File: core/js/js.js (hunk 2 above)
Comment (individual-it) [inline core/js/js.js]: changed it. please check it

**Comment by PVince81** [comment]
Looks better 👍

**Review by PVince81 — APPROVED** [review]

**Comment by individual-it** [comment]
thought that a user might enter values with white spaces, and that should be possible and valid

**Comment by PVince81** [comment]
Oh, screw Jenkins...

I ran the JS tests locally and they pass.
