### PR TITLE
Fix RHDS ldap paged search, Issue #17173

### LINKED ISSUE #17173: RHDS ldap paged search, incomplete data results or 0 users
RHDS ldap paged search, incomplete data results or 0 users

Hello,
We have been struggling with a kind of incompatibility between owncloud 8.0.4 and RHDS 9.1 on RHEL regarding paged searches.

Some searchs are interpreted by owncloud as incomplete number of results or even zero results, even when we know there are users corresponding to the filters.

After some digging into code we discovered that Owncloud counts results of paged searches until it finds a zero content page.

AFAIK, this does not follow RFC 2696 for reliably knowing when the result finished, as the only reliable control is an empty cookie (rhds distorts this by returning "0").

Some valid ldap queries return the first pages with no data (only comments) but valid cookie, followed by pages with data, maybe even other no data pages, more data pages, etc, until return of an empty null cookie.
This is a valid behaviour of a ldap server, as per rfc 2696.

By reading also https://github.com/owncloud/core/blob/master/apps/user_ldap/lib/access.php at the private function count($filter, $base, $attr = null, $limit = null, $offset = null, $skipHandling = false) implementation it seems that control is done only by data content until zero on a page , not by cookie.

Did we wrongly understand the rfc 2696 and or the code?
https://www.ietf.org/rfc/rfc2696.txt

What If we disable paged searches, may it overload servers?

Regards.
Andre Felipe

### Steps to reproduce
1. RHDS 9.1
2. Tens of thousands users in each LDAP branch from a common root.
3. Try to configure LDAP filter wizard up to the common root.

### Expected behaviour
The LDAP filter wizard should display sum of all users on server common root.
The users of different branches should be able to login

### Actual behaviour
The LDAP filter wizard display zero users, despite filter being triple checked on command line.
But configuring filter to only a branch gives expected results.

### Server configuration
**Operating system**:
Debian GNU/Linux 7.x running on VmWare 5.5

**Web server:**
Apache 2.2.22

**Database:**
Postgresql 9.4.1 backported and packaged for Debian 7.x

**PHP version:**
5.4.41

**ownCloud version:** (see ownCloud admin page)
8.0.4 (stable)

**Updated from an older ownCloud or fresh install:**
8.0.2

**List of activated apps:**
LDAP, Federated cloud sharing, mail templates, cron, sharing, security, email server, log.

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'our_instance_id',
  'passwordsalt' => 'our_salt',
  'secret' => 'our_SECRET',
  'enable_avatars' => false,
  'trusted_domains' => 
  array (
    0 => '127.0.0.1',
    1 => 'our_domain',
  ),
  'datadirectory' => '/opt/data/p_07275_our_name',
  'overwrite.cli.url' => 'our_url',
  'dbtype' => 'pgsql',
  'version' => '8.0.4.2',
  'dbname' => 'dbp_07275_our_name',
  'dbhost' => 'our_db_server_ip:our_db_server_port',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owner_our_name_p',
  'dbpassword' => 'our_db_password',
  'installed' => true,
  'overwriteprotocol' => 'https',
  'loglevel' => 2,
  'logfile' => '/var/log/owncloud.log',
  'asset-pipeline.enabled' => false,
  'logtimezone' => 'America/Sao_Paulo',
  'log_query' => true,
  'ldapIgnoreNamingRules' => false,
  'ldapUserCleanupInterval' => 0,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'our_name',
  'mail_domain' => 'our_domain',
  'mail_smtphost' => 'our_smtp_relay',
  'mail_smtpport' => '25',
  'has_internet_connection' => false,
  'trashbin_retention_obligation' => 30,
  'trashbin_auto_expire' => true,
  'activity_expire_days' => 30,
  'check_for_working_htaccess' => true,
  'enable_previews' => false,
  'theme' => 'our_theme',
  'serpro.admingroup' => 'our_admin_group',
  'serpro.ldapserver' => 'our_ldap_server',
  'serpro.ldapport' => 389,
  'serpro.ldapuser' => 'cn=our_user,ou=our_ou,ou=corp,dc=our_dc,dc=gov,dc=br',
  'serpro.basedn' => 'dc=gov,dc=br',
  'maintenance' => false,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
Using NFSv4 storage mounted on local point and mapped by "our_directory_attribute" user attribute.

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)

   appid   |              configkey               |                                        configvalue                                         
-----------+--------------------------------------+--------------------------------------------------------------------------------------------
 user_ldap | cleanUpJobOffset                     | 0
 user_ldap | installed_version                    | 0.5.0
 user_ldap | types                                | authentication
 user_ldap | enabled                              | yes
 user_ldap | s01ldap_tls                          | 0
 user_ldap | s01ldap_host                         | our_ldap_server
 user_ldap | s01ldap_dn                           | uid=our_user,ou=our_ou,ou=corp,dc=our_dc,dc=gov,dc=br
 user_ldap | s01ldap_agent_password               | our_ldap_agent_password
 user_ldap | s01ldap_userfilter_objectclass       | inetOrgPerson
 user_ldap | s01ldap_email_attr                   | mail
 user_ldap | s01ldap_user_filter_mode             | 1
 user_ldap | s01has_memberof_filter_support       | 
 user_ldap | s01ldap_group_filter_mode            | 1
 user_ldap | s01ldap_login_filter_mode            | 1
 user_ldap | s01ldap_experienced_admin            | 1
 user_ldap | s01ldap_userlist_filter              | (&(objectclass=our_object)(objectClass=person)(phpgwAccountType=u)(phpgwAccountStatus=A))
 user_ldap | s01ldap_login_filter                 | (&(objectclass=our_object)(mail=%uid)(phpgwAccountType=u)(phpgwAccountStatus=A))
 user_ldap | s01ldap_group_filter                 | (&(objectclass=our_object)(objectClass=posixGroup))
 user_ldap | s01ldap_configuration_active         | 1
 user_ldap | s01ldap_display_name                 | cn
 user_ldap | s01ldap_quota_attr                   | our_quota_attr
 user_ldap | s01ldap_quota_def                    | 1000000000
 user_ldap | s01ldap_override_main_server         | 0
 user_ldap | s01ldap_attributes_for_user_search   | mail                                                                                      +
           |                                      | sn                                                                                        +
           |                                      | givenName
 user_ldap | s01home_folder_naming_rule           | attr:our_directory_attribute
 user_ldap | s01ldap_port                         | 389
 user_ldap | s01ldap_backup_host                  | 
 user_ldap | s01ldap_backup_port                  | 
 user_ldap | s01ldap_nocase                       | 0
 user_ldap | s01ldap_turn_off_cert_check          | 0
 user_ldap | s01ldap_userfilter_groups            | 
 user_ldap | s01ldap_groupfilter_objectclass      | 
 user_ldap | s01ldap_groupfilter_groups           | 
 user_ldap | s01ldap_group_display_name           | cn
 user_ldap | s01ldap_group_member_assoc_attribute | uniqueMember
 user_ldap | s01ldap_loginfilter_email            | 0
 user_ldap | s01ldap_loginfilter_username         | 1
 user_ldap | s01ldap_loginfilter_attributes       | 
 user_ldap | s01ldap_attributes_for_group_search  | 
 user_ldap | s01ldap_expert_username_attr         | 
 user_ldap | s01ldap_expert_uuid_user_attr        | 
 user_ldap | s01ldap_cache_ttl                    | 600
 user_ldap | s01ldap_expert_uuid_group_attr       | 
 user_ldap | s01last_jpegPhoto_lookup             | 0
 user_ldap | s01ldap_nested_groups                | 0
 user_ldap | s01ldap_paging_size                  | 500
 user_ldap | s01ldap_base                         | dc=our_dc,dc=gov,dc=br
 user_ldap | s01ldap_base_groups                  | dc=our_dc,dc=gov,dc=br
 user_ldap | s01ldap_base_users                   | dc=our_dc,dc=gov,dc=br
(49 registros)

### Client configuration
**Browser:**
Mostly Firefox 24.8.0 ESR, IE  and Gogle Chrome

**Operating system:**
Ubuntu Linux 12.04 and Windows 7

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

### PR DESCRIPTION
**Pull request by esakol**
Please,

Take a look at the changes.

Fixes #17173

### CODE REVIEW

**Comment by esakol** [comment]
This contribution is MIT Licensed.

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by MorrisJobke** [comment]
Whitespace free diff: https://github.com/owncloud/core/pull/18294/files?w=1

File: apps/user_ldap/lib/access.php [hunk 1]
```diff
@@ -867,9 +872,16 @@ private function count($filter, $base, $attr = null, $limit = null, $offset = nu
...
+			$hasMorePages = $this->processPagedSearchStatus($sr, $filter, $base, $count, $limitPerPage,
 										$offset, $pagedSearchOK, $skipHandling);
 			$offset += $limitPerPage;
+			/* ++ Fixing RHDS searches with pages with zero results ++
+			 * Ignoring continue value got from countEntriesInSearchResults()
+			 * previous implementation always got $continue equals false if
+			 * page have 0 results.
+			 * Continue now depends on $hasMorePages value
+			 */
+			$continue = $pagedSearchOK && $hasMorePages;
```
Comment (blizzz) [inline apps/user_ldap/lib/access.php]: thus we can remove the third parameter from countEntriesInSearchResults, which would have brought bake the $continue value before (reference param). It should be the only usage of the method.

File: apps/user_ldap/lib/access.php [hunk 2]
```diff
@@ -828,6 +828,11 @@ private function processPagedSearchStatus($sr, $filter, $base, $iFoundItems, $li
 				\OCP\Util::writeLog('user_ldap', 'Paged search was not available', \OCP\Util::INFO);
 			}
 		}
+		/* ++ Fixing RHDS searches with pages with zero results ++
+		 * Return cookie status. If not null we know we have more pages
+		 * even if $iFoundItems == 0
+		 */
+		return is_null($cookie) ? FALSE : TRUE;
```
Comment (blizzz) [inline apps/user_ldap/lib/access.php]: Could you also fix the  return statement in the PHP doc? Looks like something got mixed up there even earlier.

File: apps/user_ldap/lib/access.php [hunk 3]
```diff
@@ -911,38 +923,53 @@ private function search($filter, $base, $attr = null, $limit = null, $offset = n
...
+				return array();
 			}
-		}
 
-		$findings = array();
-		foreach($sr as $res) {
-			$findings = array_merge($findings, $this->ldap->getEntries($cr	, $res ));
-		}
+			// Do the server-side sorting
+			foreach(array_reverse($attr) as $sortAttr){
```
Comment (blizzz) [inline apps/user_ldap/lib/access.php]: this actually can/should only when paged search is not present as it is not supported per RFC. But this would blow the scope, we can do it in an extra PR.

**Comment by blizzz** [comment]
@esakol Thank you very much. I have some points, but in general this looks good code-wise. I will drive some tests either later today or Monday. 

I just have one question remaining: When pulling users and increasing offset (e.g. scrolling in the user management), and there will be pages without results inbetween, the subsequent request would load (partly?) the same users users again, because the effective offset was already higher. Correct?

Additionally it would be good to have integration tests… if those gaps in results can be enforced somehow programmatically in the directory. Are there possibly docker images with RHDS around that can be used?

**Comment by PVince81** [comment]
@blizzz any update regarding testing ?

**Comment by blizzz** [comment]
@esakol 

Groups are fetched twice:
y a a y 4

Also users appear to be find twice (there are only 6 in that configuration):

y a a y 4

It appears we're doing work twice atm, while this is visible only in few places: users only when counting, groups additionally in the Wizard boxes and using command line search:

```
$ suww ./occ ldap:search "" --limit=30  --group
Discoverer
Elite
GreenLegion
Hackers
Icecream
Mice
PHP Hackers
QA
calTargets
sysagents
workgroupT55
Discoverer
Elite
GreenLegion
Hackers
Icecream
Mice
PHP Hackers
QA
calTargets
sysagents
workgroupT55
```

Could you look into it?

**Comment by blizzz** [comment]
P.S.: I tested only with OpenLDAP so far.

**Comment by MorrisJobke** [comment]
@blizzz I think this need to go into 9.0 -> if not so please change the milestone again.

**Comment by esakol** [comment]
Have found the problem with Openldap, it seems when we don't have more pages Openldap responds with an empty string. I'm gonna apply the changes and commit it as soon as possible.

**Comment by esakol** [comment]
Hi, can someone look into this test failure? It looks like something is missing.

**Comment by MorrisJobke** [comment]
@esakol There were issues with PRs from forks. @DeepDiver1975 Did you know more?

**Comment by blizzz** [comment]
@esakol could you try to rebase?

**Comment by esakol** [comment]
Branch updated and rebased.

**Comment by jancborchardt** [comment]
@owncloud/ldap can you test this? You can also use this shorthand mention to get your pull requests reviewed. :)

**Comment by gig13** [comment]
@MorrisJobke @bboule 
Has this been tested with AD? Is it relevant with AD?

**Comment by blizzz** [comment]
tests are not running, because it's a fork, I'll create a branch for jenkins.

**Comment by blizzz** [comment]
Integration tests are succeeding (run only locally).

File: apps/user_ldap/lib/access.php [hunk 4]
```diff
@@ -865,14 +865,13 @@ private function executeSearch($filter, $base, &$attr = null, $limit = null, $of
 	 * @param bool $pagedSearchOK whether a paged search has been executed
 	 * @param bool $skipHandling required for paged search when cookies to
 	 * prior results need to be gained
-	 * @return array|false array with the search result as first value and pagedSearchOK as
-	 * second | false if not successful
+	 * @return bool cookie validity, true if we have more pages, false otherwise.
```
Comment (blizzz) [inline apps/user_ldap/lib/access.php]: null is also possible, which is return when $skipHandling is true. Thus return type should be bool|null.

**Comment by blizzz** [comment]
:+1: tested with OpenLDAP. 
AD is also required, I'd need to finish setting up a new test server first.

This is a good chance to test compatibility with other LDAP servers, but I do not really expect issue. @alex42ka @tomcat-sdb @GreenArchon @ckruetze @alexweirig @Xenopathic @frankuit

**Comment by MorrisJobke** [comment]
@davitol can we get a test for this from QA?

**Comment by MorrisJobke** [comment]
Unit tests passed in #20635

**Comment by davitol** [comment]
> AD is also required, I'd need to finish setting up a new test server first.

Smoke tested with AD and it seems to work fine

**Comment by blizzz** [comment]
Will be shipped with 9.0 early next year.

Since it's not a regression I would not vote to backport it, unless significant demand for having it in 8.2 pops up.
