### PR TITLE
DAV now returns file name with Content-Disposition header

### LINKED ISSUE #23176: xml file is converted do txt downloading in chrome
### Steps to reproduce
1. upload xml file to owncloud
2. download file with chrome (works fine in firefox, ie and edge), choose download from the pop-up menu, it works ok if the download link from selected file check box is used. 
3. 

### Expected behaviour
the file extension of the downloaded file should be xml

### Actual behaviour
the file is converted to txt

### Server configuration
centos 7
**Web server:**
nginx
**Database:**
mariadb 10.1
**PHP version:**
5.6.18
**ownCloud version:** (see ownCloud admin page)
9.0.0
**Updated from an older ownCloud or fresh install:**
updated from 8.2.2
**Where did you install ownCloud from:**
tar
**Signing status (ownCloud 9.0 and above):**

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
chrome
**Operating system:**
windows 10

### PR DESCRIPTION
**Pull request by PVince81**
Fixes issue where Chrome would append ".txt" to XML files when downloaded in the web UI

Fixes https://github.com/owncloud/core/issues/23176

Please review @owncloud/filesystem @DeepDiver1975 @nickvergessen @rullzer 

Would be best to backport this to 9.0 because that's where the issue first appeared, at the time where we switched the web UI to use the Webdav endpoint for downloads.

CC @DeepDiver1975 @dragotin

### CODE REVIEW

**Comment by PVince81** [comment]
- [x] TEST: old dav endpoint still works (since we touched FilesPlugin)
- [x] TEST: new dav endpoint still works (since we touched FilesPlugin)
- [x] TEST: downloading an XML file with chrome properly returns an XML file

**Comment by guruz** [comment]
👍

File: apps/dav/lib/Connector/Sabre/FilesPlugin.php [hunk 1]
```diff
@@ -225,7 +235,18 @@ function httpGet(RequestInterface $request, ResponseInterface $response) {
...
 		// adds a 'Content-Disposition: attachment' header
 		if ($this->downloadAttachment) {
-			$response->addHeader('Content-Disposition', 'attachment');
+			$filename = $node->getName();
+			if ($this->request->isUserAgent(
+				[
+					\OC\AppFramework\Http\Request::USER_AGENT_IE,
+					\OC\AppFramework\Http\Request::USER_AGENT_ANDROID_MOBILE_CHROME,
+					\OC\AppFramework\Http\Request::USER_AGENT_FREEBOX,
+				])) {
```
Comment (rullzer) [inline apps/dav/lib/Connector/Sabre/FilesPlugin.php]: why this dark magic? That is going to bite us at some point...

Comment (nickvergessen) [inline apps/dav/lib/Connector/Sabre/FilesPlugin.php]: It's copied from Sabre\Auth,

don't know if it really is that dark, seems like the only way

**Comment by icewind1991** [comment]
Looks good :+1:

File: apps/dav/lib/Connector/Sabre/FilesPlugin.php (hunk 1 above)
Comment (rullzer) [inline apps/dav/lib/Connector/Sabre/FilesPlugin.php]: ok fair enough...

**Comment by rullzer** [comment]
Should we have intergration tests for this?

**Comment by rullzer** [comment]
O and failing intergration tests:

> 06:38:18 
06:38:18 --- Failed scenarios:
06:38:18 
06:38:18     /var/lib/jenkins/jenkins-slave/workspace/ocs-api-integration-tests-ci@2/build/integration/features/webdav-related.feature:80
06:38:18     /var/lib/jenkins/jenkins-slave/workspace/ocs-api-integration-tests-ci@2/build/integration/features/webdav-related.feature:95
06:38:18

**Comment by PVince81** [comment]
Ok, I'll have a look. Thanks

**Comment by PVince81** [comment]
Fixed the integration test, glad that it exists :smile:

**Comment by rullzer** [comment]
:+1:

**Comment by PVince81** [comment]
stable9: https://github.com/owncloud/core/pull/25052
