### PR TITLE
do not fail update or installation when .htaccess file is not writable

### LINKED ISSUE #34471: Can't setup with non-writable htaccess
As far as I remember, some setups are configured fully read-only, or some admins don't want to let the web server write anything in the PHP tree, so they disable it.

We should allow non-writable htaccess.

This PR https://github.com/owncloud/core/pull/32230 makes it throw an exception.

We should soften it and output a warning on the console when it happens.

@individual-it

### PR DESCRIPTION
**Pull request by individual-it**
## Description
since https://github.com/owncloud/core/pull/32230 an exception is thrown when the .htaccess is read-only but it has to be possible to install or update oC when the .htaccess file is not writeable
but when `occ maintenance:update:htaccess` and the file cannot be updated the command should fail

## Related Issue
- Fixes  #34471

## Motivation and Context
see issue

## How Has This Been Tested?
- install oC with R/O `.htaccess`
- install oC with R/W `.htaccess`
- update oC with R/O `.htaccess`
- run `occ maintenance:update:htaccess` with R/O `.htaccess`
- run `occ maintenance:update:htaccess` with R/W `.htaccess`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

File: lib/private/Setup.php [hunk 1]
```diff
@@ -472,11 +468,11 @@ public static function updateHtaccess() {
 
 		if ($content !== '') {
 			$fileWriteResult = @\file_put_contents(
-				$setupHelper->pathToHtaccess(), $htaccessContent . $content . "\n"
+				self::pathToHtaccess(), $htaccessContent . $content . "\n"
 			);
 			if ($fileWriteResult === false) {
```
Comment (phil-davis) [inline lib/private/Setup.php]: Looks good - the "real" exception is still thrown here, if we did get here and still the htaccess file could not be written.

**Review by phil-davis — COMMENTED** [review]
Looks good to me.
I will let @PVince81 give the final approval.

**Comment by individual-it** [comment]
tried hard to add more unit tests but the whole install/update code is hard to test

File: lib/private/Setup.php [hunk 2]
```diff
@@ -425,11 +425,7 @@ public static function updateHtaccess() {
 			$webRoot = !empty(\OC::$WEBROOT) ? \OC::$WEBROOT : '/';
 		}
 
-		$setupHelper = new \OC\Setup($config, \OC::$server->getIniWrapper(),
```
Comment (PVince81) [inline lib/private/Setup.php]: I think the class exists in this form due to unit testing.
I'm unsure whether we should remove it like this but I don't mind if it doesn't break anything...

**Review by PVince81 — APPROVED** [review]
:+1:

setup works again on my env

**Comment by PVince81** [comment]
@individual-it please backport

**Comment by phil-davis** [comment]
Backport ``stable10`` #34486
