### PR TITLE
Fix the group selector drop down

### LINKED ISSUE #31739: "Exclude groups from sharing" checkbox broken on master branch
### Steps to reproduce
1. Install ownCloud from github, master branch (https://github.com/owncloud/core/commit/9edd97a8646a76af7834fd967a8b71aa37829c91)
2. Create several groups
3. Go to the settings page, sharing section
4. Mark "exclude groups form sharing" checkbox
5. Try to exclude an specific group

### Expected behaviour
Groups can be selected

### Actual behaviour
The selection loads forever

screen shot 2018-06-12 at 18 02 09

It works fine on stable10

### Server configuration
**Operating system**: ubuntu 16.04

**Web server:** apache 2.4

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** master

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** github

### PR DESCRIPTION
**Pull request by sharidas**
This change gets the group selector drop
down

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Fix the group selector in the core. After moving the code to user_management app, the ajax request to get the groups available for the user did not worked. The reason for this is there is no controller in the core to address the request. This PR fixes the issue.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/31739

## Motivation and Context

Fix the group selector in the core. After moving the code to user_management app the ajax request to get the groups available for user did not worked in the master branch of core. There was no route and controller to address the request. This PR tries to fix the issue by adding a new route and controller to core which accepts the request and provides the response back.

## How Has This Been Tested?

- Login as admin and create users `group1`, `group2`
- Tick the exclude shares check box mentioned in the issue
- Admin user can see `admin`, `group1` and `group2` listed.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by sharidas** [comment]
Current state of the PR:
- [x] Added `MetaData.php` from `user_management` to core
- [x] Created a new controller for the group selector request.
- [ ] Update the unit tests

File: settings/Controller/GroupsSelectController.php [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+
+	/**
+	 * @NoAdminRequired
+	 *
+	 * @param string $pattern
+	 * @param bool $filterGroups
+	 * @param int $sortGroups
+	 * @return DataResponse
+	 */
+	public function index($pattern = '', $filterGroups = false, $sortGroups = MetaData::SORT_USERCOUNT) {
```
Comment (DeepDiver1975) [inline settings/Controller/GroupsSelectController.php]: you need all parameters here?

File: lib/private/MetaData.php [hunk 2]
```diff
@@ -0,0 +1,200 @@
...
+ * You should have received a copy of the GNU Affero General Public License, version 3,
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>
+ *
+ */
+
+namespace OC;
+
+use OCP\IUserSession;
+
+class MetaData {
```
Comment (DeepDiver1975) [inline lib/private/MetaData.php]: As explained I don't want to see this class in code

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]

**Comment by sharidas** [comment]
Current state of the PR:
- Added separate controller for group selector
- This PR has no dependency with user_management. Meaning, user_management remains untouched.
- Added unit test for the change made.

File: settings/Controller/GroupsController.php [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+	 */
+	public function getGroupsForUser() {
+		$user = $this->userSession->getUser();
+
+		if ($user === null) {
+			return new DataResponse(
+				[
+					'status' => 'error',
+					'data' => [
+						'message' => 'No groups available'
```
Comment (DeepDiver1975) [inline settings/Controller/GroupsController.php]: this message is wrong

File: settings/Controller/GroupsController.php [hunk 4]
```diff
@@ -0,0 +1,102 @@
...
+			[
+				'data' => ['adminGroups' => $adminGroups, 'groups' => $userGroups]
+			], Http::STATUS_OK);
+	}
+
+	/**
+	 * @param $isAdmin
+	 * @param IUser $user
+	 * @param string $search
+	 * @return array|\OCP\IGroup[]
```
Comment (DeepDiver1975) [inline settings/Controller/GroupsController.php]: why array? IGroup[] is sufficient

File: settings/Controller/GroupsController.php [hunk 5]
```diff
@@ -0,0 +1,102 @@
...
+
+use OCP\AppFramework\Controller;
+use OCP\AppFramework\Http;
+use OCP\AppFramework\Http\DataResponse;
+use OCP\IGroupManager;
+use OCP\IRequest;
+use OCP\IUser;
+use OCP\IUserSession;
+
+class GroupsController extends Controller {
```
Comment (DeepDiver1975) [inline settings/Controller/GroupsController.php]: PHPDoc

File: settings/Controller/GroupsController.php [hunk 6]
```diff
@@ -0,0 +1,102 @@
...
+	private $groupManager;
```
Comment (DeepDiver1975) [inline settings/Controller/GroupsController.php]: PHPDoc

File: settings/Controller/GroupsController.php [hunk 7]
```diff
@@ -0,0 +1,102 @@
...
+	private $userSession;
+	public function __construct(string $appName,
```
Comment (DeepDiver1975) [inline settings/Controller/GroupsController.php]: PHPDoc

File: settings/Controller/GroupsController.php [hunk 8]
```diff
@@ -0,0 +1,102 @@
...
+								IUserSession $userSession) {
+		parent::__construct($appName, $request);
+		$this->groupManager = $groupManager;
+		$this->userSession = $userSession;
+	}
+
+	/**
+	 * Get the groups for the user
+	 *
+	 * @NoAdminRequired
```
Comment (DeepDiver1975) [inline settings/Controller/GroupsController.php]: Usually we add a no csrf annotation to GET requests ... please have a second look and see if needed ...

File: settings/Controller/GroupsController.php [hunk 9]
```diff
@@ -0,0 +1,102 @@
...
+		}
+
+		$adminGroups = [];
+		$userGroups = [];
+		$isAdmin = $this->groupManager->isAdmin($user->getUID());
+		$groups = $this->getGroups($isAdmin, $user, '');
+		foreach ($groups as $group) {
+			if ($group->getGID() === 'admin') {
+				$adminGroup['id'] = $group->getGID();
+				$adminGroup['name'] = $group->getGID();
```
Comment (DeepDiver1975) [inline settings/Controller/GroupsController.php]: there is a getDisplayName afaik - please adapt

File: tests/Settings/Controller/GroupsControllerTest.php [hunk 10]
```diff
@@ -0,0 +1,142 @@
...
+use OC\Settings\Controller\GroupsController;
+use OCP\AppFramework\Http\DataResponse;
+use OCP\IGroup;
+use OCP\IGroupManager;
+use OCP\IRequest;
+use OCP\ISubAdminManager;
+use OCP\IUser;
+use OCP\IUserSession;
+
+class GroupsControllerTest extends TestCase {
```
Comment (DeepDiver1975) [inline tests/Settings/Controller/GroupsControllerTest.php]: PHPDoc

File: tests/Settings/Controller/GroupsControllerTest.php [hunk 11]
```diff
@@ -0,0 +1,142 @@
...
+	private $appName;
```
Comment (DeepDiver1975) [inline tests/Settings/Controller/GroupsControllerTest.php]: PHPDoc

File: tests/Settings/Controller/GroupsControllerTest.php [hunk 12]
```diff
@@ -0,0 +1,142 @@
...
+	private $request;
```
Comment (DeepDiver1975) [inline tests/Settings/Controller/GroupsControllerTest.php]: PHPDoc

File: tests/Settings/Controller/GroupsControllerTest.php [hunk 13]
```diff
@@ -0,0 +1,142 @@
...
+	private $groupManager;
```
Comment (DeepDiver1975) [inline tests/Settings/Controller/GroupsControllerTest.php]: PHPDoc

File: tests/Settings/Controller/GroupsControllerTest.php [hunk 14]
```diff
@@ -0,0 +1,142 @@
...
+	private $userSession;
```
Comment (DeepDiver1975) [inline tests/Settings/Controller/GroupsControllerTest.php]: PHPDoc

File: tests/Settings/Controller/GroupsControllerTest.php [hunk 15]
```diff
@@ -0,0 +1,142 @@
...
+	private $groupsController;
```
Comment (DeepDiver1975) [inline tests/Settings/Controller/GroupsControllerTest.php]: PHPDoc

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]

**Comment by sharidas** [comment]
@DeepDiver1975 kindly review my change. The updated PR includes:
- [x] Updated the message when the user is null
- [x] Added missing PHP Doc ( for both controller and the test )
- [x] Updated the get request with `NoCSRFRequired` annotation. Grepped through the source code, and figured out that the GET requests are using the same. Hence adapting it.
- [x] Updated the code to use `getDisplayName` for the group name ( earlier getGID was used ).
- [x] Updated the code to return `IGroup[]` ( earlier it was array|IGroup[] )

**Comment by PVince81** [comment]
@sharidas mind adding a summary at the top to explain why this PR fixes the issue ?

I see a lot of controller stuff being shuffled around but it's not clear why this helps fixing the issue.

**Comment by sharidas** [comment]
@PVince81 
> @sharidas mind adding a summary at the top to explain why this PR fixes the issue ?
> 
> I see a lot of controller stuff being shuffled around but it's not clear why this helps fixing the issue.

I have updated the `Description` and `Motivation and Context` section of the PR. A breif summary has been added to know why this change is added.

**Comment by PVince81** [comment]
@sharidas is this a brand new controller written from scratch or does it reuse some of the code that was moved to the user_management app ?

**Comment by sharidas** [comment]
> @sharidas is this a brand new controller written from scratch or does it reuse some of the code that was moved to the user_management app ?

@PVince81 Yes this is a new controller. It is inspired or lets say influenced from user_management's https://github.com/owncloud/user_management/blob/master/lib/Controller/GroupsController.php. Here is the comment, which helped to create this PR https://github.com/owncloud/user_management/pull/96#issuecomment-436304331. Also I have tried to avoid code duplication while writing this controller. Hope this address your query.

File: settings/Controller/GroupsController.php [hunk 16]
```diff
@@ -0,0 +1,124 @@
...
+
+		$adminGroups = [];
+		$userGroups = [];
+		$isAdmin = $this->groupManager->isAdmin($user->getUID());
+		$groups = $this->getGroups($isAdmin, $user, '');
+		foreach ($groups as $group) {
+			if ($group->getGID() === 'admin') {
+				$adminGroup['id'] = $group->getGID();
+				$adminGroup['name'] = $group->getDisplayName();
+				$adminGroup['userCount'] = 1;
```
Comment (PVince81) [inline settings/Controller/GroupsController.php]: I think there can be more than one user in the admin group

**Review by PVince81 — COMMENTED** [review]
See comment.
Looks ok otherwise.

**Comment by sharidas** [comment]
Current state of the PR

- [x] Replaced admin users count from `1` to `$group->count('')`. This was from the request https://github.com/owncloud/core/pull/33442#discussion_r233865426. I have verified with the latest change, the code does grab all the users from admin or non admin groups.

Hence kindly request for review @PVince81

**Comment by sharidas** [comment]
- [x] Updated the test with more than one user in a group.
  - [x] Though there is a test which I updated in this version, I have tried to add another test. In the new test I have not used mocks. It directly alters the db.

@PVince81 I have updated the new version with the unit tests updated. I missed updating the test, in my previous version :(

**Comment by PVince81** [comment]
@sharidas can you click "resolve conversation" on the review items that you solved ?

**Comment by sharidas** [comment]
> @sharidas can you click "resolve conversation" on the review items that you solved ?

I have clicked "resolve conversation" on the review items, that were solved with respect to the current state of the PR.

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by phil-davis** [comment]
Note: This PR would need to be backported to `stable10` if we some-day release the `user_management` app as a separate app, along with a core 10.* release.
