### PR TITLE
Do not remove linkshare if there is none

### LINKED ISSUE #19550: Error when unsharing link
### Steps to reproduce
1. Go to the Server Client with Admin
2. Go to the Sharing option 
3. Select the option "Enforce password protection"

4. Go to Files
5. Share a folder
6. Select the option Share by link
7. **Untick the option**

### Expected behaviour
The box should be unticked and the password field should disappear

### Actual behaviour

unshare_error

If you click on share link again, the password field now disappears

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #19550

If the password is enforced we can't create a link share right away but
just show the password field. Untoggling the link sharing should not try
to remove the share.

TODO:
- [x] sidebare sharing unit tests for passwords

We really should have proper js unit tests for the passwords.
@PVince81 basically I can't get https://github.com/owncloud/core/blob/master/core/js/sharedialoglinkshareview.js#L118 to toggle the visibility in the unit tests. Can you help out?

### CODE REVIEW

**Comment by oparoz** [comment]
Works :+1:

**Comment by schiesbn** [comment]
code looks good :+1: as soon as the test pass

**Comment by rullzer** [comment]
@PVince81 unit test finally done. please have a look.

File: core/js/tests/specs/sharedialogviewSpec.js [hunk 1]
```diff
@@ -231,6 +231,42 @@ describe('OC.Share.ShareDialogView', function() {
...
+		describe('password', function() {
+			var slideToggleStub;
+
+			beforeEach(function() {
+				$('#allowShareWithLink').val('yes');
+				configModel.set({
+					enforcePasswordForPublicLink: false
+				});
+
+				slideToggleStub = sinon.stub($.fn, 'slideToggle');
```
Comment (PVince81) [inline core/js/tests/specs/sharedialogviewSpec.js]: please call `slideToggleStub.restore()` in `afterEach`

Comment (rullzer) [inline core/js/tests/specs/sharedialogviewSpec.js]: Fixed

**Comment by PVince81** [comment]
:+1:
