### PR TITLE
getJailedPath expects $path to have a trailing / 

### LINKED ISSUE #25464: Error sharing a Shared Folder
Hi!
I think this issue is related to 704 on iOS project (don´t know hot to relate this with an issue located on other project) @nasli 

After upgrading to 9.0.3.2 there is another problem sharing shared resources.

### Steps to reproduce
1. i have two users, userOne and userTwo
2. userOne shares a folder with full permissions to userTwo
3. userTwo tries to create a share link on a file of his shared folder using the web UI
4. the 'loading' icon never stops, the link is never created
5. in the UI the 'shared link' icon apprears but the link doesn't exists

### Expected behaviour
The link of the shared resource should be created

### Actual behaviour
1. the 'loading' icon never stops, the link is never created
2. after refreshing the page (f5) in the UI the 'shared link' icon apprears but the link doesn't exists

### Server configuration
Web server: Apache 2.4
Database: MySQL
PHP version: 7
OwnCloud: 9.0.3.2 upgraded from 9.0.2.2

### Client configuration
**Browser:**
Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0

**Operating system:**
Windows 8.1

#### ownCloud log (data/owncloud.log)

`{"reqId":"sS6ysMKz2\/KHpqweRGG3","remoteAddr":"192.168.1.73","app":"PHP","message":"OCP\\Files\\NotFoundException:  at \/var\/www\/owncloud\/apps\/files_sharing\/api\/share20ocs.php#110","level":3,"time":"2016-07-13T07:27:34+00:00","method":"POST","url":"\/owncloud\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json","user":"userTwo"}`

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #25464

### CODE REVIEW

**Comment by pako81** [comment]
Tested on 9.0.4. Works THX!

**Comment by DeepDiver1975** [comment]
@pako81 mind retesting? I had to change the fix in order to avoid regressions in other areas :dizzy_face:

**Comment by pako81** [comment]
@DeepDiver1975 :+1:  yes, seems to work for already existing files/folders as well as for newly created ones.

File: lib/private/Files/Cache/Wrapper/CacheJail.php [hunk 1]
```diff
@@ -58,6 +58,9 @@ protected function getSourcePath($path) {
 	 * @return null|string the jailed path or null if the path is outside the jail
 	 */
 	protected function getJailedPath($path) {
+		if ($this->root === '') {
+			return $path;
```
Comment (PVince81) [inline lib/private/Files/Cache/Wrapper/CacheJail.php]: @DeepDiver1975 Mind explaining how this fix fits in with the PR description ? (no reference to slashes here)
Maybe add a comment in the code to clarify for future reference.

Comment (DeepDiver1975) [inline lib/private/Files/Cache/Wrapper/CacheJail.php]: The shared storage is a jailed storage and usually in case of sharing the jailed storage is some folder down somewhere in the users folders structure.
Not in case of sharing a mounted external storage - then the mount point itself is shared and it is the root of the mount which gets jailed.

**Comment by PVince81** [comment]
Makes sense :+1:

**Comment by DeepDiver1975** [comment]
stable9.1: https://github.com/owncloud/core/pull/25737

**Comment by DeepDiver1975** [comment]
stable9: https://github.com/owncloud/core/pull/25738
