### PR TITLE
[tests-only][full-ci]Fix Intermittent fail webUIUpload/upload.feature:131

### LINKED ISSUE #39549: Intermittent fail webUIUpload/upload.feature:131
I noticed this fail in a PR just now. I am not sure if it fails very often, but it will be good to investigate.

https://drone.owncloud.com/owncloud/core/33888/150/16
```
  Background:                                                                              # /drone/src/tests/acceptance/features/webUIUpload/upload.feature:8
    Given user "Alice" has been created with default attributes and without skeleton files # FeatureContext::userHasBeenCreatedWithDefaultAttributesAndWithoutSkeletonFiles()

  @files_sharing-app-required
  Scenario: upload overwriting a file into a public share                                               # /drone/src/tests/acceptance/features/webUIUpload/upload.feature:131
    Given user "Alice" has created folder "/simple-folder"                                              # FeatureContext::userHasCreatedFolder()
    And user "Alice" has uploaded file "filesForUpload/lorem.txt" to "/simple-folder/lorem.txt"         # FeatureContext::userHasUploadedAFileTo()
    And user "Alice" has created a public link share with settings                                      # FeatureContext::userHasCreatedAPublicLinkShareWithSettings()
      | path        | /simple-folder     |
      | permissions | read,update,create |
    When the public accesses the last created public link using the webUI                               # WebUISharingContext::thePublicAccessesTheLastCreatedPublicLinkUsingTheWebUI()
INFORMATION: timed out waiting for ajax calls to start
Upload overwriting lorem.txt and got 1 notifications including You don’t have permission to upload or create files here

INFORMATION: timed out waiting for ajax calls to start
Upload overwriting lorem.txt and got 2 notifications including You don’t have permission to upload or create files here

INFORMATION: timed out waiting for ajax calls to start
    And the user uploads overwriting file "lorem.txt" using the webUI and retries if the file is locked # WebUIFilesContext::theUserUploadsOverwritingFileUsingTheWebUIRetry()
      │ INFORMATION: timed out waiting for ajax calls to startUpload overwriting lorem.txt and got 1 notifications including You don’t have permission to upload or create files here
      │ INFORMATION: timed out waiting for ajax calls to startUpload overwriting lorem.txt and got 2 notifications including You don’t have permission to upload or create files here
      │ INFORMATION: timed out waiting for ajax calls to start
      WebUIFilesContext::choiceInUploadConflictDialogWebUI file upload conflict dialog expected but not found (Exception)
    Then file "lorem.txt" should be listed on the webUI                                                 # WebUIFilesContext::fileFolderShouldBeListedOnTheWebUI()
    When user "Alice" logs in using the webUI                                                           # WebUILoginContext::logInWithUsernameUsingTheWebUI()
    And the content of "simple-folder/lorem.txt" should be the same as the local "lorem.txt"            # WebUIFilesContext::theContentOfShouldBeTheSameAsTheLocal()
SCENARIO RESULT: (fail)
```

### PR DESCRIPTION
**Pull request by SwikritiT**
## Description

This PR adds one sec pause to ` getOcDialogs()` function

## Related Issue

- Fixes https://github.com/owncloud/core/issues/39549

## How Has This Been Tested?

- CI https://github.com/owncloud/core/pull/39690

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

File: tests/acceptance/features/lib/OwncloudPage.php [hunk 1]
```diff
@@ -273,6 +273,7 @@ public function getOcDialogs(): array {
 			$ocDialog->setElement($element);
 			$ocDialogs[] = $ocDialog;
 		}
+		sleep(1);
```
Comment (phil-davis) [inline tests/acceptance/features/lib/OwncloudPage.php:276]: please write comments about why this is "a good thing" to do.
We don't want too many sleeps like this in the code, but if we have to, then the reasons need to be commented.

Comment (phil-davis) [reply tests/acceptance/features/lib/OwncloudPage.php:278]: At this point in the code `$ocDialogs` array is already constructed. It is either empty or has one or more dialogs in the array. Waiting 1 second will not help the code to find a dialog.

Maybe the `sleep` just helps to be more sure confident that the dialog(s) have properly rendered and are ready for the test code to interact with elements in the dialog.

Should the sleep happen at the start of this function?

Should it call something like `$this->waitForOutstandingAjaxCalls($session)` rather than having a fixed sleep?

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Note: not many test scenarios use the dialogs, so, IMO, this short hard-coded delay is better than the random test fails.
