### PR TITLE
Fix errors reported by phpstan 0.12.92

### LINKED ISSUE #38971: Missing return statements
https://github.com/phpstan/phpstan/releases/tag/0.12.92 was released a day ago.

That implements extra checks for methods that should return something but do not - https://github.com/phpstan/phpstan-src/commit/26560811765f0a93462180526b552834966c161b

`make test-php-phpstan` is now failing with errors like:
```
------ ------------------------------------------------------------------------------------------------ 
  Line   lib/public/Search/PagedProvider.php                                                             
 ------ ------------------------------------------------------------------------------------------------ 
  55     Method OCP\Search\PagedProvider::search() should return array but return statement is missing.  
 ------ ------------------------------------------------------------------------------------------------ 

```

and
```
------ --------------------------------------------------------------------------------------------- 
  Line   core/Command/Status.php                                                                      
 ------ --------------------------------------------------------------------------------------------- 
  49     Method OC\Core\Command\Status::execute() should return int but return statement is missing.  
 ------ --------------------------------------------------------------------------------------------- 
```

These are just 2 examples of about 90 errors reported.

Fix the methods so that they either return what they say, or fix the PHPdoc to say that they return nothing.

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
`phpstan` released 0.12.92 last night. That "fixed/enhanced" checks on methods that should return something, but do not.

This PR fixes the errors that were reported.

Many of the errors were the `execute()` method of Symfony commands. That method should return `0` on success, but many of the commands did not have a `return 0` at the end of the `execute()` method when the command has finished. Those were easy to fix.

I made comments through the diff listing to explain what I did.

Note: CI currently fails in `master` and in `release-10.8.0` - we need to either apply fixes like these, or pin `phpstan` to `0.12.91` in each branch.

Note: if we apply these fixes, what do I put in a changelog?

## Related Issue
- Fixes #38971 

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

File: apps/dav/lib/Connector/Sabre/AppEnabledPlugin.php [hunk 1]
```diff
@@ -78,7 +78,7 @@ public function initialize(\Sabre\DAV\Server $server) {
 	 * This method is called before any HTTP after auth and checks if the user has access to the app
 	 *
 	 * @throws \Sabre\DAV\Exception\Forbidden
-	 * @return bool
+	 * @return void
```
Comment (phil-davis) [inline apps/dav/lib/Connector/Sabre/AppEnabledPlugin.php:81]: This does not return anything, and the callers do not expect anything to be returned. IMO the PHPdoc was not correct.

File: apps/dav/lib/Connector/Sabre/CorsPlugin.php [hunk 2]
```diff
@@ -150,7 +150,7 @@ public function setCorsHeaders(RequestInterface $request, ResponseInterface $res
 	 * @param RequestInterface $request
 	 * @param ResponseInterface $response
 	 *
-	 * @return false
+	 * @return false|void
```
Comment (phil-davis) [inline apps/dav/lib/Connector/Sabre/CorsPlugin.php:153]: If this follows the "doing nothing" path, then it "returns" `void`.
I just added that to the PHPdoc. 
But maybe it should always return `false`? Or?

File: apps/files_sharing/lib/Controller/ShareesController.php [hunk 3]
```diff
@@ -375,7 +375,7 @@ protected function getGroups($search) {
 
 	/**
 	 * @param string $search
-	 * @return array possible sharees
+	 * @return void
```
Comment (phil-davis) [inline apps/files_sharing/lib/Controller/ShareesController.php:378]: This method is called `getRemote` - it "gets" the information into `$this->result`. It does not actually return anything, so I adjusted the PHP doc.

File: apps/files_sharing/lib/SharedMount.php [hunk 4]
```diff
@@ -108,7 +108,6 @@ private function verifyMountPoint(\OCP\Share\IShare $share, array $mountpoints)
 	 *
 	 * @param string $newPath
 	 * @param \OCP\Share\IShare $share
-	 * @return bool
```
Comment (phil-davis) [inline apps/files_sharing/lib/SharedMount.php:111]: This method does not return anything, and the callers do not expect anything to be returned. I deleted the PHP doc.

File: apps/files_sharing/lib/SharedStorage.php [hunk 5]
```diff
@@ -479,6 +479,6 @@ public function lockNodePersistent($internalPath, array $lockInfo) {
 	}
 
 	public function unlockNodePersistent($internalPath, array $lockInfo) {
-		parent::unlockNodePersistent($this->getSourcePath($internalPath), $lockInfo);
+		return parent::unlockNodePersistent($this->getSourcePath($internalPath), $lockInfo);
```
Comment (phil-davis) [inline apps/files_sharing/lib/SharedStorage.php:482]: Similar to `lockNodePersistent`, `unlockNodePersistent` is supposed to return the result.
I wonder if this will help any callers, or?

File: core/Command/Encryption/ChangeKeyStorageRoot.php [hunk 6]
```diff
@@ -100,7 +100,9 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 			$this->util->setKeyStorageRoot($newRoot);
 			$output->writeln('');
 			$output->writeln("Key storage root successfully changed to <info>$newRootDescription</info>");
+			return 0;
 		}
+		return 1;
```
Comment (phil-davis) [inline core/Command/Encryption/ChangeKeyStorageRoot.php:105]: This will make the command exit with error status if something goes wrong.
It might help any script that runs this command and wants to know if it succeeded or failed.

File: core/Command/Encryption/SetDefaultModule.php [hunk 7]
```diff
@@ -62,6 +62,8 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 			$output->writeln('<info>Set default module to "' . $moduleId . '"</info>');
 		} else {
 			$output->writeln('<error>The specified module "' . $moduleId . '" does not exist</error>');
+			return 1;
```
Comment (phil-davis) [inline core/Command/Encryption/SetDefaultModule.php:65]: This will now exit with error status if the module does not exist.

File: core/Command/Maintenance/DataFingerprint.php [hunk 8]
```diff
@@ -73,6 +73,8 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 			$fingerprint = \md5($this->timeFactory->getTime());
 			$this->config->setSystemValue('data-fingerprint', $fingerprint);
 			$this->logger->info("Data fingerprint was set by $osUser@$server to $fingerprint");
+			return 0;
 		}
+		return 1;
```
Comment (phil-davis) [inline core/Command/Maintenance/DataFingerprint.php:78]: This will now exit with an error status if the data fingerprint is not updated.

File: core/Migrations/Version20180302155233.php [hunk 9]
```diff
@@ -51,5 +51,8 @@ public function sql(IDBConnection $connection) {
 			->where($qb->expr()->eq('share_type', $qb->expr()->literal(2)))
 			->andWhere($qb->expr()->eq('permissions', $qb->expr()->literal(0)))
 			->execute();
+		// This sql() method is supposed to return an array of sql statements
+		// The meeded update has been done above, so return an empty array.
```
Comment (phil-davis) [inline core/Migrations/Version20180302155233.php:55]:
```suggestion
		// The needed update has been done above, so return an empty array.
```

File: lib/private/Encryption/Keys/Storage.php [hunk 10]
```diff
@@ -200,6 +201,7 @@ public function deleteAltUserStorageKeys($uid) {
 
 			return false;
 		}
+		return false;
```
Comment (phil-davis) [inline lib/private/Encryption/Keys/Storage.php:204]: This will return false if encryption is not enabled - it used to "return" void. `false` should be better.

File: lib/private/Files/Storage/DAV.php [hunk 11]
```diff
@@ -416,6 +416,7 @@ public function fopen($path, $mode) {
 				self::$tempFiles[$tmpFile] = $path;
 				return \fopen('close://' . $tmpFile, $mode);
 		}
+		return false;
```
Comment (phil-davis) [inline lib/private/Files/Storage/DAV.php:419]: If we get here, then the `mode` did not match any of the switch cases. We did not `fopen()` anything, so we better return false.

File: lib/private/Files/Storage/Wrapper/Wrapper.php [hunk 12]
```diff
@@ -637,8 +637,9 @@ public function unlockNodePersistent($internalPath, array $lockInfo) {
 		$storage = $this->getWrapperStorage();
 		if ($storage->instanceOfStorage(IPersistentLockingStorage::class)) {
 			'@phan-var \OCP\Files\Storage\IPersistentLockingStorage $storage';
-			$storage->unlockNodePersistent($internalPath, $lockInfo);
+			return $storage->unlockNodePersistent($internalPath, $lockInfo);
```
Comment (phil-davis) [inline lib/private/Files/Storage/Wrapper/Wrapper.php:640]: This has a boolean result, so return it.

File: lib/private/Files/Storage/Wrapper/Wrapper.php [hunk 13]
```diff
@@ -637,8 +637,9 @@ public function unlockNodePersistent($internalPath, array $lockInfo) {
...
 		}
+		return false;
```
Comment (phil-davis) [inline lib/private/Files/Storage/Wrapper/Wrapper.php:642]: Somehow this was not `IPersistentLockingStorage` and so we did nothing.
I chose to return `false`.
Or should it return `true`?

File: lib/private/Repair/RepairMismatchFileCachePath.php [hunk 14]
```diff
@@ -110,7 +110,6 @@ public function setCountOnly($countOnly) {
 	 * @param string $wrongPath wrong path of the entry to fix
 	 * @param int $correctStorageNumericId numeric idea of the correct storage
 	 * @param string $correctPath value to which to set the path of the entry
-	 * @return bool true for success
```
Comment (phil-davis) [inline lib/private/Repair/RepairMismatchFileCachePath.php:113]: The method does not return anything, and callers are not expecting it to return anything. I removed the PHP doc.

File: lib/private/Settings/SettingsManager.php [hunk 15]
```diff
@@ -226,6 +226,7 @@ private function getBuiltInSections($type) {
 				new Section('additional', $this->l->t('Additional'), -10, 'more'),
 			];
 		}
+		return [];
```
Comment (phil-davis) [inline lib/private/Settings/SettingsManager.php:229]: If some othe `$typ` is passed, then I guess we should return an empty array.

File: lib/private/Settings/SettingsManager.php [hunk 16]
```diff
@@ -390,6 +392,7 @@ protected function loadPanel($className) {
 					'Class: {class} not an instance of OCP\Settings\ISettings',
 					['class' => $className]
 				);
+				return false;
```
Comment (phil-davis) [inline lib/private/Settings/SettingsManager.php:395]: The caller needs to be able to more clearly know that there is no "proper" panel, so I returned false here.

File: lib/private/Settings/SettingsManager.php [hunk 17]
```diff
@@ -425,10 +428,11 @@ public function loadPanels($type) {
 			// Attempt to load the panel
 			try {
 				$panel = $this->loadPanel($panelClassName);
-				$section = $this->loadSection($type, $panel->getSectionID());
-				$this->panels[$type][$section->getID()][] = $panel;
-				$this->sections[$type][$section->getID()] = $section;
-				// Now try and initialise the ISection from the panel
+				if ($panel !== false) {
```
Comment (phil-davis) [inline lib/private/Settings/SettingsManager.php:431]: And now we can avoid trying to do these lines of code if `$panel` has nothing.

File: lib/private/Setup/MySQL.php [hunk 18]
```diff
@@ -137,7 +137,6 @@ private function connect() {
 	/**
 	 * @param $username
 	 * @param IDBConnection $connection
-	 * @return array
```
Comment (phil-davis) [inline lib/private/Setup/MySQL.php:140]: This does not return anything, and callers to not expect a return value, so I deleted the PHP doc.

File: lib/private/Theme/Theme.php [hunk 19]
```diff
@@ -63,7 +63,6 @@ public function getName() {
 
 	/**
 	 * @param string $baseDirectory
-	 * @return string
```
Comment (phil-davis) [inline lib/private/Theme/Theme.php:66]: This is a setter method. No return value.

File: lib/private/URLGenerator.php [hunk 20]
```diff
@@ -205,20 +205,21 @@ private function getImagePath($app, $imageName) {
 			$file = $directory . $imageName;
 
 			if ($themeDirectory !== ''
-				&& $imagePath = $this->getImagePathOrFallback($this->theme->getBaseDirectory() . '/' . $themeDirectory . $file)
```
Comment (phil-davis) [inline lib/private/URLGenerator.php:208]: Unused var.

File: lib/private/URLGenerator.php [hunk 21]
```diff
@@ -205,20 +205,21 @@ private function getImagePath($app, $imageName) {
...
+				&& $this->getImagePathOrFallback($this->theme->getBaseDirectory() . '/' . $themeDirectory . $file)
 			) {
 				return $this->theme->getWebPath() . $file;
 			}
 
-			if ($imagePath = $this->getImagePathOrFallback($this->environmentHelper->getServerRoot() . $file)) {
```
Comment (phil-davis) [inline lib/private/URLGenerator.php:213]: Unused var.

File: lib/private/URLGenerator.php [hunk 22]
```diff
@@ -205,20 +205,21 @@ private function getImagePath($app, $imageName) {
...
+			if ($this->getImagePathOrFallback($this->environmentHelper->getServerRoot() . $file)) {
 				return $webRoot . $file;
 			}
 		}
+		return '';
```
Comment (phil-davis) [inline lib/private/URLGenerator.php:217]: If we get here, then "something is wrong/not found".
I return the empty string (rather than letting it "return void")

File: lib/private/URLGenerator.php [hunk 23]
```diff
@@ -228,6 +229,7 @@ private function getImagePathOrFallback($file) {
 				return $location;
 			}
 		}
+		return false;
```
Comment (phil-davis) [inline lib/private/URLGenerator.php:232]: Callers of this method test its value in a "boolean" way. If we don't find the file, then it seems good to return `false`

File: lib/private/User/RemoteUser.php [hunk 24]
```diff
@@ -107,6 +107,7 @@ public function setPassword($password, $recoveryPassword = null) {
 	 * @inheritdoc
 	 */
 	public function getHome() {
+		return '';
```
Comment (phil-davis) [inline lib/private/User/RemoteUser.php:110]: This method is supposed to return a string.
What to return in this case?
Empty string seems better than "void".

File: lib/public/Search/PagedProvider.php [hunk 25]
```diff
@@ -52,7 +52,7 @@ public function __construct($options) {
 	 */
 	public function search($query) {
 		// old apps might assume they get all results, so we use SIZE_ALL
-		$this->searchPaged($query, 1, self::SIZE_ALL);
+		return $this->searchPaged($query, 1, self::SIZE_ALL);
```
Comment (phil-davis) [inline lib/public/Search/PagedProvider.php:55]: The PHPdoc says that this should return an array of results.
This looks easy to fix - but it worries me why this "missing return" has not been causing problems.

File: tests/Core/Command/Encryption/DecryptAllTest.php [hunk 26]
```diff
@@ -255,6 +255,6 @@ public function testExecuteConfirm($confirmVal) {
 			->method('isEnabled')
 			->willReturn(true);
 
-		$this->assertNull($this->invokePrivate($instance, 'execute', [$this->consoleInput, $this->consoleOutput]));
+		$this->assertEquals(0, $this->invokePrivate($instance, 'execute', [$this->consoleInput, $this->consoleOutput]));
```
Comment (phil-davis) [inline tests/Core/Command/Encryption/DecryptAllTest.php:258]: The command `execute()` method is supposed to return `0` for success, and now it does.

File: tests/Core/Command/User/ResetPasswordTest.php [hunk 27]
```diff
@@ -96,7 +96,7 @@ public function testResetPasswordFromEnv() {
 			->method('get')
 			->willReturn($user);
 
-		$this->assertNull($this->invokePrivate($this->resetPassword, 'execute', [$input, $output]));
+		$this->assertEquals(0, $this->invokePrivate($this->resetPassword, 'execute', [$input, $output]));
```
Comment (phil-davis) [inline tests/Core/Command/User/ResetPasswordTest.php:99]: The command `execute()` method is supposed to return `0` for success, and now it does.

File: vendor-bin/phpstan/composer.json [hunk 28]
```diff
@@ -1,5 +1,5 @@
 {
     "require": {
-        "phpstan/phpstan": "^0.12.71"
+        "phpstan/phpstan": "^0.12.92"
```
Comment (phil-davis) [inline vendor-bin/phpstan/composer.json:3]: `0.12.92` implements the improved checks that find this stufff. So make sure it is the minimum version of `phpstan` that we use.

**Review by micbar — CHANGES_REQUESTED** [review]
let us merge after the release

**Comment by phil-davis** [comment]
> let us merge after the release

I will make PRs to pin `phpstan` to the previous patch version. That will get CI  green in both `master` and `release-10.8.0`

**Comment by phil-davis** [comment]
`release-10.8.0` has been merged back. I have rebased this PR. It is ready for review.

File: apps/files_external/lib/Command/Applicable.php [hunk 29]
```diff
@@ -151,5 +151,6 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 			'users' => $applicableUsers,
 			'groups' => $applicableGroups
 		]);
+		return 0;
```
Comment (JammingBen) [inline apps/files_external/lib/Command/Applicable.php:154]: This method also returns `404` in some cases, which is not consistent with the Symfony docs.

Not sure if we should make it part of this PR, but I think `return 1` is more fitting. However, we would need to check if the returned `404` is used somewhere. Usually these `execute()` methods don't get called from the outside, except in the tests. Could be possible that the tests do some assertions with `404`.

File: apps/files_external/lib/Command/Config.php [hunk 30]
```diff
@@ -78,6 +78,7 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 		} else {
 			$this->getOption($mount, $key, $output);
 		}
+		return 0;
```
Comment (JammingBen) [inline apps/files_external/lib/Command/Config.php:81]: More `404` returns, see above.

File: apps/files_external/lib/Command/Delete.php [hunk 31]
```diff
@@ -107,5 +107,6 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 		}
 
 		$this->globalService->removeStorage($mountId);
+		return 0;
```
Comment (JammingBen) [inline apps/files_external/lib/Command/Delete.php:110]: More `404` returns, see above.

File: apps/files_external/lib/Command/Verify.php [hunk 32]
```diff
@@ -81,6 +81,7 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 			'code' => $mount->getStatus(),
 			'message' => $mount->getStatusMessage()
 		]);
+		return 0;
```
Comment (JammingBen) [inline apps/files_external/lib/Command/Verify.php:84]: More `404` returns, see above.

File: apps/files_sharing/lib/Controller/ShareesController.php (hunk 3 above)
Comment (JammingBen) [reply apps/files_sharing/lib/Controller/ShareesController.php:378]: Confusing name for this method, I expect `get...()` to actually return something, not set something 😄 
Just on a side note, I know it's been there for ages probably.

File: core/Command/Config/Import.php [hunk 33]
```diff
@@ -85,6 +85,7 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 		}
 
 		$output->writeln('<info>Config successfully imported from: ' . $importFile . '</info>');
+		return 0;
```
Comment (JammingBen) [inline core/Command/Config/Import.php:88]: There is an empty `return` above in line 68 -> `return 1;`.

**Review by micbar — APPROVED** [review]

File: core/Command/Encryption/DecryptAll.php [hunk 34]
```diff
@@ -189,5 +189,6 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 			$this->resetSingleUserAndTrashbin();
 			throw $e;
 		}
+		return 0;
```
Comment (JammingBen) [inline core/Command/Encryption/DecryptAll.php:192]: Empty return above in line 150 -> `return 0;`. And a `return null` in line 140, unsure about this one 🤷  Probably `return 2` as the command is invalid?

File: core/Command/Group/ListGroups.php [hunk 35]
```diff
@@ -61,5 +61,6 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 			return $group->getGID();
```
Comment (JammingBen) [inline core/Command/Group/ListGroups.php:61]: Once again unsure about the return here, might be used in the tests though.

File: core/Command/L10n/CreateJs.php [hunk 36]
```diff
@@ -64,6 +64,7 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 		foreach ($languages as $lang) {
 			$this->writeFiles($app, $path, $lang, $output);
 		}
+		return 0;
```
Comment (JammingBen) [inline core/Command/L10n/CreateJs.php:67]: Empty return above in line 57 -> `return 1;`

File: core/Command/TwoFactorAuth/Disable.php [hunk 37]
```diff
@@ -59,5 +59,6 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 		}
 		$this->manager->disableTwoFactorAuthentication($user);
 		$output->writeln("Two-factor authentication disabled for user $uid");
+		return 0;
```
Comment (JammingBen) [inline core/Command/TwoFactorAuth/Disable.php:62]: Empty return above in line 58 -> `return 1`;

File: core/Command/TwoFactorAuth/Enable.php [hunk 38]
```diff
@@ -59,5 +59,6 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 		}
 		$this->manager->enableTwoFactorAuthentication($user);
 		$output->writeln("Two-factor authentication enabled for user $uid");
+		return 0;
```
Comment (JammingBen) [inline core/Command/TwoFactorAuth/Enable.php:62]: Empty return above in line 58 -> `return 1;`

File: core/Command/User/Disable.php [hunk 39]
```diff
@@ -59,5 +59,6 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 
 		$user->setEnabled(false);
 		$output->writeln('<info>The specified user is disabled</info>');
+		return 0;
```
Comment (JammingBen) [inline core/Command/User/Disable.php:62]: Empty return above in line 57 -> `return 1;`

File: core/Command/User/Enable.php [hunk 40]
```diff
@@ -59,5 +59,6 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 
 		$user->setEnabled(true);
 		$output->writeln('<info>The specified user is enabled</info>');
+		return 0;
```
Comment (JammingBen) [inline core/Command/User/Enable.php:62]: Empty return above in line 57 -> `return 1;`

File: core/Command/User/LastSeen.php [hunk 41]
```diff
@@ -70,5 +70,6 @@ protected function execute(InputInterface $input, OutputInterface $output) {
 			$output->writeln($user->getUID() .
 				'`s last login: ' . $date->format('d.m.Y H:i'));
 		}
+		return 0;
```
Comment (JammingBen) [inline core/Command/User/LastSeen.php:73]: Empty return above in line 60 -> `return 1;`

**Review by JammingBen — COMMENTED** [review]
Found some more inconsistencies with return values in Commands, see my annotations. IMO this is a good PR to tackle those as well.

File: apps/files_external/lib/Command/Applicable.php (hunk 29 above)
Comment (phil-davis) [reply apps/files_external/lib/Command/Applicable.php:154]: Make a script containing:
```
exit 404
```

Execute the script and see the exit status:
```
./script.sh
echo $?
148
```

404-256=148. These kind of script/command exit codes are limited to 0 to 255. So 404 actually provides exit code 148 back to the thing that executed the command.

I  will change it to 1,

File: apps/files_sharing/lib/Controller/ShareesController.php (hunk 3 above)
Comment (phil-davis) [reply apps/files_sharing/lib/Controller/ShareesController.php:378]: It does "get" the data, and remembers it internally in the class. But yes, the function name is not the best. IMO we don't touch that now.

File: core/Command/Group/ListGroups.php (hunk 35 above)
Comment (phil-davis) [reply core/Command/Group/ListGroups.php:61]: That is inside the function of \array_map - it is not a return out of `execute()`

I added:
```
use OCP\IGroup;
```
because the IDE didn't understand what sort of object `$group` is.

**Comment by phil-davis** [comment]
Review comments addressed and rebased. IMO this is ready to merge when CI passes.

**Comment by JammingBen** [comment]
The assertion in https://github.com/owncloud/core/blob/eebd754771a99bc44820eb67a6d57cea238e6b86/tests/Core/Command/Encryption/DecryptAllTest.php#L258 seems to be wrong now. Other than that, LGTM!

**Comment by phil-davis** [comment]
I need to sort the unit test cases out...

File: tests/Core/Command/Encryption/DecryptAllTest.php [hunk 42]
```diff
@@ -255,6 +255,6 @@ public function testExecuteConfirm($confirmVal) {
 			->method('isEnabled')
 			->willReturn(true);
 
-		$this->assertNull($this->invokePrivate($instance, 'execute', [$this->consoleInput, $this->consoleOutput]));
+		$this->assertEquals(2, $this->invokePrivate($instance, 'execute', [$this->consoleInput, $this->consoleOutput]));
```
Comment (JammingBen) [inline tests/Core/Command/Encryption/DecryptAllTest.php:258]: `2` is just returned for the last argument of the data provider. So you'll need something like:

```
if (($confirmVal !== 'yes') && ($confirmVal !== 'no')) {
	$expected = 2;
} else {
	$expected = 0;
}

$this->assertEquals($expected, $this->invokePrivate($instance, 'execute', [$this->consoleInput, $this->consoleOutput]));
```

Comment (phil-davis) [reply tests/Core/Command/Encryption/DecryptAllTest.php]: I have put the expected exit code in the data provider:
```
	public function providesConfirmVal() {
		return [
			['yes', 0],
			['no', 0],
			['foo', 2]
		];
	}
```

**Review by JammingBen — APPROVED** [review]
🚀
