### PR TITLE
avoid $this->cache being null 

### LINKED ISSUE #13491: Server-to-server mount fails on master
As soon as a server to server share was accepted the file scanner will fail and the user will no longer see the file listing. The problem was introduced with this PR:  https://github.com/owncloud/core/pull/13377

If I disable the trash bin I can see the file listing again. 

I get this error in the apache log:

```
[Tue Jan 20 00:15:11.808999 2015] [:error] [pid 7803] [client 127.0.0.1:54169] PHP Fatal error:  Call to a member function getIncomplete() on null in /home/schiesbn/public_html/owncloud/master/lib/private/files/cache/scanner.php on line 331, referer: http://localhost/~schiesbn/owncloud/master/index.php/apps/files/
[Tue Jan 20 00:15:11.809041 2015] [:error] [pid 7803] [client 127.0.0.1:54169] PHP Stack trace:, referer: http://localhost/~schiesbn/owncloud/master/index.php/apps/files/
[Tue Jan 20 00:15:11.809054 2015] [:error] [pid 7803] [client 127.0.0.1:54169] PHP   1. {main}() /home/schiesbn/public_html/owncloud/master/index.php:0, referer: http://localhost/~schiesbn/owncloud/master/index.php/apps/files/
[Tue Jan 20 00:15:11.809065 2015] [:error] [pid 7803] [client 127.0.0.1:54169] PHP   2. OC::handleRequest() /home/schiesbn/public_html/owncloud/master/index.php:28, referer: http://localhost/~schiesbn/owncloud/master/index.php/apps/files/
[Tue Jan 20 00:15:11.809074 2015] [:error] [pid 7803] [client 127.0.0.1:54169] PHP   3. OC\\Route\\Router->match() /home/schiesbn/public_html/owncloud/master/lib/base.php:763, referer: http://localhost/~schiesbn/owncloud/master/index.php/apps/files/
[Tue Jan 20 00:15:11.809085 2015] [:error] [pid 7803] [client 127.0.0.1:54169] PHP   4. call_user_func:{/home/schiesbn/public_html/owncloud/master/lib/private/route/router.php:250}() /home/schiesbn/public_html/owncloud/master/lib/private/route/router.php:250, referer: http://localhost/~schiesbn/owncloud/master/index.php/apps/files/
[Tue Jan 20 00:15:11.809094 2015] [:error] [pid 7803] [client 127.0.0.1:54169] PHP   5. __lambda_func() /home/schiesbn/public_html/owncloud/master/lib/private/route/router.php:250, referer: http://localhost/~schiesbn/owncloud/master/index.php/apps/files/
[Tue Jan 20 00:15:11.809102 2015] [:error] [pid 7803] [client 127.0.0.1:54169] PHP   6. require_once() /home/schiesbn/public_html/owncloud/master/lib/private/route/route.php(135) : runtime-created function:1, referer: http://localhost/~schiesbn/owncloud/master/index.php/apps/files/
[Tue Jan 20 00:15:11.809113 2015] [:error] [pid 7803] [client 127.0.0.1:54169] PHP   7. OC\\Files\\Utils\\Scanner->backgroundScan() /home/schiesbn/public_html/owncloud/master/apps/files/ajax/scan.php:29, referer: http://localhost/~schiesbn/owncloud/master/index.php/apps/files/
[Tue Jan 20 00:15:11.809135 2015] [:error] [pid 7803] [client 127.0.0.1:54169] PHP   8. OC\\Files\\Cache\\Scanner->backgroundScan() /home/schiesbn/public_html/owncloud/master/lib/private/files/utils/scanner.php:108, referer: http://localhost/~schiesbn/owncloud/master/index.php/apps/files/
```

At the moment I don't know what's wrong with the storage wrapper of the trashbin, @icewind1991 do you have an idea?

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #13491

@schiesbn @icewind1991 @PVince81 please review - thx

### CODE REVIEW

File: apps/files_sharing/lib/external/storage.php [hunk 1]
```diff
@@ -103,7 +103,7 @@ public function getId() {
 	}
 
 	public function getCache($path = '', $storage = null) {
-		if (!$storage) {
+		if (is_null($this->cache)) {
```
Comment (LukasReschke) [inline apps/files_sharing/lib/external/storage.php]: I wonder if it wouldn't make sense if we start enforcing non-type juggling comparisons on such simple conditions as well. We already do it with `!==` and `===`

I know this might make the code look more cluttering but considering such bugs…

Comment (LukasReschke) [inline apps/files_sharing/lib/external/storage.php]: Regardless of that: What is $storage now for?

Comment (LukasReschke) [inline apps/files_sharing/lib/external/storage.php]: Ah – it's an interface implementation – :+1: then.

**Comment by icewind1991** [comment]
:+1: looks good

File: apps/files_sharing/lib/external/storage.php (hunk 1 above)
Comment (schiesbn) [inline apps/files_sharing/lib/external/storage.php]: @LukasReschke I agree. I try to do this already for some time for all my code changes

**Comment by schiesbn** [comment]
@DeepDiver1975 Thanks for taking care of it... I will try it in a few minutes. :smile:

**Comment by PVince81** [comment]
:+1: fixes the issue

**Comment by PVince81** [comment]
@owncloud-bot retest this please, I need it!!

**Comment by MorrisJobke** [comment]
> I need it!!

:smiley:
