### PR TITLE
Fallback to complete Memcached flush if getAllKeys fails

### LINKED ISSUE #18849: Memcached broken, invalid argument supplied for foreach()
I don't know if it worked before, but with the latest Memcached all unit tests fail. Some debugging reveals the problem is with `->getAllKeys()`, which returns FALSE now. I suspect Memcached changed some behaviour with the (undocumented) `stats cachedump` protocol command, which PHP uses when `->getAllKeys()` is called.

In summary, we can no longer clear the cache with Memcached, and trying to throws an error as we don't properly check the return from `->getAllKeys()`... I can't think of a sensible fallback to that, other than just calling `->flush()` and removing ALL keys, not just those for the ownCloud instance...

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Newer Memcached's do not support the underlying protocol commands that getAllKeys() is implemented with. We should fallback to clearing everything in that case, as causing (temporary) performance problems for other applications on the server is better than having stale cached data.

cc @LukasReschke @karlitschek @DeepDiver1975 @icewind1991 @MorrisJobke 

Fixes #18849

### CODE REVIEW

**Comment by karlitschek** [comment]
Agreed. Anything else will lead to problems. :+1:

**Comment by Xenopathic** [comment]
The question is, because this seems to affect all newer versions of Memcached, do we backport this?

**Comment by karlitschek** [comment]
yes. we should backport. This could trigger interesting bugs.

File: tests/lib/memcache/memcached.php [hunk 1]
```diff
@@ -26,4 +26,27 @@ protected function setUp() {
...
+		$this->instance->set('1_value1', $value);
+		$this->instance->set('1_value2', $value);
+		$this->instance->set('2_value1', $value);
+		$this->instance->set('3_value1', $value);
+
+		$this->assertTrue($this->instance->clear('1_'));
+
+		$this->assertFalse($this->instance->hasKey('1_value1'));
+		$this->assertFalse($this->instance->hasKey('1_value2'));
+		//$this->assertTrue($this->instance->hasKey('2_value1'));
```
Comment (nickvergessen) [inline tests/lib/memcache/memcached.php]: Add a comment why this is commented out?

Comment (Xenopathic) [inline tests/lib/memcache/memcached.php]: See the top line of the function

Comment (nickvergessen) [inline tests/lib/memcache/memcached.php]: well the test may (or may not) grow infinite, so the comment should be right next to the commented line instead of the beginning of the method

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by Xenopathic** [comment]
@owncloud-bot retest this please

**Comment by Xenopathic** [comment]
Oracle failure caused by #18799, other DB tests pass -> merge
