### PR TITLE
Fix multi-file download

### LINKED ISSUE #26664: Shared folder with hyphen in name can't be downloaded
### Steps to reproduce
1. Login to owncloud
2. Create a folder with the name "test" and a subfolder with a hyphen in it ("2016-11-21" for example)
3. Upload any file into test/2016-11-21 folder
4. Share the folder "test" via link (without password or expiration)
5. Logout of owncloud and go to the shared link URL
6. Select the folder "2016-11-21" and click on "Download"

### Expected behaviour
A zip file should be downloaded, that contains all files of the folder "2016-11-21"

### Actual behaviour
An error message "File not found
The specified document has not been found on the server.
You can click here to return to ownCloud." appears

### Server configuration
**Operating system**: Debian Jessie 8.6

**Web server:** Apache 2 (2.4.10-10+deb8u5)

**Database:** MariaDB 5.5.51

**PHP version:** PHP 5.6.27-0+deb8u1

**ownCloud version:** ownCloud 9.1.2 (stable)

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** apt-repository (owncloud-files package)

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - notes
  - user_external
  - user_ldap

```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "oc6fw0jhk5i5",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud-test"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/owncloud-test",
        "dbtype": "mysql",
        "version": "9.1.2.5",
        "dbname": "owncloudtest",
        "dbhost": "nas",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true
    }
}
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox ESR 45.5.0

**Operating system:** Windows 7 Enterprise

#### Web server error log
```
access.log:
192.168.178.101 - - [21/Nov/2016:09:14:00 +0100] "GET /index.php/s/BEXX9uQlCf58nCr HTTP/1.1" 200 3962 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
192.168.178.101 - - [21/Nov/2016:09:14:01 +0100] "GET /apps/files_sharing/css/public.css?v=65d56d2e6ca5c46fa03adc731692e1e5 HTTP/1.1" 200 1330 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
192.168.178.101 - - [21/Nov/2016:09:14:01 +0100] "GET /apps/files_sharing/css/mobile.css?v=65d56d2e6ca5c46fa03adc731692e1e5 HTTP/1.1" 200 958 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
192.168.178.101 - - [21/Nov/2016:09:14:02 +0100] "GET /apps/files_sharing/js/public.js?v=65d56d2e6ca5c46fa03adc731692e1e5 HTTP/1.1" 200 4232 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
192.168.178.101 - - [21/Nov/2016:09:14:01 +0100] "GET /index.php/core/js/oc.js?v=65d56d2e6ca5c46fa03adc731692e1e5 HTTP/1.1" 200 3201 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
192.168.178.101 - BEXX9uQlCf58nCr [21/Nov/2016:09:14:03 +0100] "PROPFIND /public.php/webdav/ HTTP/1.1" 207 2143 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
192.168.178.101 - - [21/Nov/2016:09:14:03 +0100] "GET /index.php/apps/gallery/config.public?extramediatypes=1&token=BEXX9uQlCf58nCr HTTP/1.1" 200 786 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
192.168.178.101 - - [21/Nov/2016:09:14:03 +0100] "GET /cron.php HTTP/1.1" 200 750 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
192.168.178.101 - - [21/Nov/2016:09:14:06 +0100] "GET /index.php/s/BEXX9uQlCf58nCr/download?path=%2F&files=2016-11-21&downloadStartSecret=v0vjnyhcfxp HTTP/1.1" 404 10158 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
192.168.178.101 - - [21/Nov/2016:09:14:07 +0100] "GET /index.php/core/js/oc.js?v=65d56d2e6ca5c46fa03adc731692e1e5 HTTP/1.1" 200 3201 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
192.168.178.101 - - [21/Nov/2016:09:14:07 +0100] "GET /index.php/apps/gallery/config?extramediatypes=1 HTTP/1.1" 401 736 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
192.168.178.101 - - [21/Nov/2016:09:14:07 +0100] "GET /cron.php HTTP/1.1" 200 750 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"

error.log: is empty
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"ipWvhYeC5r12d8UR6jbd","remoteAddr":"192.168.178.101","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/apps\/
files_sharing\/lib\/Controllers\/ShareController.php#442","level":3,"time":"2016-11-21T08:14:06+00:00","method":"GET","url":"\/index.php\/s\/BEXX9uQlCf58nCr\
/download?path=%2F&files=2016-11-21&downloadStartSecret=v0vjnyhcfxp","user":"--"}
{"reqId":"wRj1tXK6CZnNdKEXM0Qd","remoteAddr":"192.168.178.101","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/apps\/
files_sharing\/lib\/Controllers\/ShareController.php#442","level":3,"time":"2016-11-21T08:14:13+00:00","method":"GET","url":"\/index.php\/s\/BEXX9uQlCf58nCr\
/download?path=%2F&files=2016-11-21&downloadStartSecret=v0vjnyhcfxp","user":"--"}
{"reqId":"Y1Z1pCw4Fk\/TkZy5xPb\/","remoteAddr":"192.168.178.101","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/apps
\/files_sharing\/lib\/Controllers\/ShareController.php#442","level":3,"time":"2016-11-21T08:14:22+00:00","method":"GET","url":"\/index.php\/s\/BEXX9uQlCf58nC
r\/download?path=%2F&files=2016-11-21&downloadStartSecret=v0vjnyhcfxp","user":"--"}
{"reqId":"7PE4wl1dbSyl9kzN2kkJ","remoteAddr":"192.168.178.101","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/apps\/
files_sharing\/lib\/Controllers\/ShareController.php#442","level":3,"time":"2016-11-21T08:14:30+00:00","method":"GET","url":"\/index.php\/s\/BEXX9uQlCf58nCr\
/download?path=%2F&files=2016-11-21&downloadStartSecret=v0vjnyhcfxp","user":"--"}
{"reqId":"5vDRU3M895+vFlCYOCng","remoteAddr":"192.168.178.101","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/apps\/
files_sharing\/lib\/Controllers\/ShareController.php#442","level":3,"time":"2016-11-21T08:14:39+00:00","method":"GET","url":"\/index.php\/s\/BEXX9uQlCf58nCr\
/download?path=%2F&files=2016-11-21&downloadStartSecret=v0vjnyhcfxp","user":"--"}
{"reqId":"9VMxFwWQScVndxZwlx8x","remoteAddr":"192.168.178.101","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/apps\/
files_sharing\/lib\/Controllers\/ShareController.php#442","level":3,"time":"2016-11-21T08:14:48+00:00","method":"GET","url":"\/index.php\/s\/BEXX9uQlCf58nCr\
/download?path=%2F&files=2016-11-21&downloadStartSecret=v0vjnyhcfxp","user":"--"}
{"reqId":"2MM1TK1pmu4d7O6AIc9n","remoteAddr":"192.168.178.101","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/apps\/
files_sharing\/lib\/Controllers\/ShareController.php#442","level":3,"time":"2016-11-21T08:14:56+00:00","method":"GET","url":"\/index.php\/s\/BEXX9uQlCf58nCr\
/download?path=%2F&files=2016-11-21&downloadStartSecret=v0vjnyhcfxp","user":"--"}
{"reqId":"+P6Z77l6KgOcz6+PhwuH","remoteAddr":"192.168.178.101","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/apps\/
files_sharing\/lib\/Controllers\/ShareController.php#442","level":3,"time":"2016-11-21T08:15:05+00:00","method":"GET","url":"\/index.php\/s\/BEXX9uQlCf58nCr\
/download?path=%2F&files=2016-11-21&downloadStartSecret=v0vjnyhcfxp","user":"--"}
{"reqId":"CYvqRyrFVqI5k2Tfc2iQ","remoteAddr":"192.168.178.101","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/apps\/
files_sharing\/lib\/Controllers\/ShareController.php#442","level":3,"time":"2016-11-21T08:15:14+00:00","method":"GET","url":"\/index.php\/s\/BEXX9uQlCf58nCr\
/download?path=%2F&files=2016-11-21&downloadStartSecret=v0vjnyhcfxp","user":"--"}
{"reqId":"Ht5XO+ieJ1YnBL2rd3TY","remoteAddr":"192.168.178.101","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/apps\/
files_sharing\/lib\/Controllers\/ShareController.php#442","level":3,"time":"2016-11-21T08:15:23+00:00","method":"GET","url":"\/index.php\/s\/BEXX9uQlCf58nCr\
/download?path=%2F&files=2016-11-21&downloadStartSecret=v0vjnyhcfxp","user":"--"}
{"reqId":"hH93Nyu4aCpksyotH3ZE","remoteAddr":"192.168.178.101","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/apps\/
files_sharing\/lib\/Controllers\/ShareController.php#442","level":3,"time":"2016-11-21T08:15:32+00:00","method":"GET","url":"\/index.php\/s\/BEXX9uQlCf58nCr\
/download?path=%2F&files=2016-11-21&downloadStartSecret=v0vjnyhcfxp","user":"--"}
{"reqId":"qMxOQEvH7vEwxQkJ\/l8z","remoteAddr":"192.168.178.101","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/apps\
/files_sharing\/lib\/Controllers\/ShareController.php#442","level":3,"time":"2016-11-21T08:15:41+00:00","method":"GET","url":"\/index.php\/s\/BEXX9uQlCf58nCr
\/download?path=%2F&files=2016-11-21&downloadStartSecret=v0vjnyhcfxp","user":"--"}
{"reqId":"GKe75ldiKeePVdXRE7U1","remoteAddr":"192.168.178.101","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/apps\/
files_sharing\/lib\/Controllers\/ShareController.php#442","level":3,"time":"2016-11-21T08:15:50+00:00","method":"GET","url":"\/index.php\/s\/BEXX9uQlCf58nCr\
/download?path=%2F&files=2016-11-21&downloadStartSecret=v0vjnyhcfxp","user":"--"}
```

### PR DESCRIPTION
**Pull request by PVince81**
## Description
On some environments, PHP parses some file names differently instead of
returning NULL. For example a date like "2016-12-01" would get parsed
as the integer value "2016".

This fix changes the internal URL download format to use either a
single "files" parameter or multiple "files[]" parameters to specify
files to download.

## Related Issue
Fixes https://github.com/owncloud/core/issues/26664

## Motivation and Context
See ticket

## How Has This Been Tested?
- [x] TEST: regular file list download single file
- [x] TEST: regular file list download multiple files
- [x] TEST: regular file list download single folder called `["abc", "def"]`
- [x] TEST: public file file list download single file
- [x] TEST: public file list download multiple files
- [x] TEST: public file list download single folder called `["abc", "def"]`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### Backports
- [ ] stable9.1
- [ ] others ?

This URL is supposed to be private, but it is likely that some apps might be using it so we might want to include a fallback to JSON parsing in case the old format is still used ?

Please review @DeepDiver1975 @VicDeo @jvillafanez @PhilippSchaffrath

### CODE REVIEW

**Comment by jvillafanez** [comment]
I think it should be easier to only consider multi-file downloads if this feature is isolated. If you want to download just a file, send an array with just an item

**Comment by PhilippSchaffrath** [comment]
:+1: 

@jvillafanez this code is pretty straight forward already imo.

**Comment by PVince81** [comment]
@jvillafanez is this better https://github.com/owncloud/core/pull/26751/commits/60e8aa2493fa24696da90710cdadfc71664bc339 ?

File: apps/files/ajax/download.php [hunk 1]
```diff
@@ -30,13 +30,18 @@
...
 \OC::$server->getSession()->close();
 
-$files = isset($_GET['files']) ? (string)$_GET['files'] : '';
+// files must be an array with multiple "files[]=one.txt&files[]=two.txt"
+$files_list = isset($_GET['files']) ? $_GET['files'] : '';
 $dir = isset($_GET['dir']) ? (string)$_GET['dir'] : '';
 
-$files_list = json_decode($files);
-// in case we get only a single file
+if (is_string($files_list) && strlen($filesList) === 0) {
```
Comment (jvillafanez) [inline apps/files/ajax/download.php]: `$filesList` isn't defined

**Comment by jvillafanez** [comment]
Looks a bit better for me.

File: apps/files/ajax/download.php (hunk 1 above)
Comment (PVince81) [inline apps/files/ajax/download.php]: Fixed

Comment (jvillafanez) [inline apps/files/ajax/download.php]: did you forget to push? 😄

**Comment by PVince81** [comment]
@jvillafanez yeah... pushed now

**Comment by jvillafanez** [comment]
👍

**Comment by PVince81** [comment]
Fixed JS tests

**Comment by PVince81** [comment]
Feels a bit risky to backport, I'd rather not.
