### PR TITLE
Fix X-Robots-Tag header valid values check

### LINKED ISSUE #40713: X-Robots-Tag security check
Hi, 
I'm running ownCloud (docker version) behind a proxy with a subpath configuration. I recently noticed that if I override the header X-Robots-Tag the security check fails.

Digging in the code I found this https://github.com/owncloud/core/blob/v10.12.0/core/js/setupchecks.js#L237

Currently the only accepted value for the robots tag is `none` but:

- duplicate headers are acceptable https://stackoverflow.com/questions/4371328/are-duplicate-http-response-headers-acceptable
- the value `none` is only used by Google. Check this https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name and https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers. 
- `X-Robots-Tag': 'noindex nofollow'`, should be considered as valid

As of today, if I want to add other values to x-robots-tag that would not be possible, without raising a false positive warning.

curl output of  https://my_beautiful_fqdn/owncloud

```
< x-robots-tag: none
< x-frame-options: SAMEORIGIN
< x-download-options: noopen
< x-permitted-cross-domain-policies: none
< location: /owncloud/
< strict-transport-security: max-age=15724800; includeSubDomains
< x-robots-tag: noindex, nofollow, nosnippet, noarchive
```

@osianderG (cc)

### Steps to reproduce

1. Specify another x-robots-tag header with value different from none in your proxy 
2. curl -vvvv https://your_beautiful_fqdn/owncloud (2 x-robots-tag headers are shown)

### Expected behaviour

No warning raised if `none` or `noindex+nofollow+<other custom values>` values are specified

### Actual behaviour

A warning is raised

### Server configuration

**ownCloud version:** 10.12.0

**Updated from an older ownCloud or fresh install:** updated from 10.11.0

**Where did you install ownCloud from:** docker official image

### PR DESCRIPTION
**Pull request by rizlas**
## Description

Currently the only accepted value for the robots tag is `none` but:

- duplicate headers are acceptable https://stackoverflow.com/questions/4371328/are-duplicate-http-response-headers-acceptable
- the value `none` is only used by Google. Check this https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name and https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers. 
- `X-Robots-Tag': 'noindex nofollow'`, should be considered as valid

## Related Issue
- Fixes [#40713](https://github.com/owncloud/core/issues/40713)

## Motivation and Context
Allow all the possible values of x-robots-tag header and handle duplicate headers if OC is behind a proxy

## How Has This Been Tested?
- test environment: fully working environment with OC 10.12 (docker)
- test case 1: x-robots-tag header values: `'none, noindex, nofollow, nosnippet, noarchive'`
- test case 2: x-robots-tag header values: `'none, nosnippet, noarchive'`
- test case 3: x-robots-tag header values: `'none'`
- test case 4: x-robots-tag header values: `'nofollow, nosnippet'` [security warning raised]
- test case 5: x-robots-tag header values: `'nosnippet, noarchive'` [security warning raised]
- test case 6: x-robots-tag header values: `'noindex, nofollow'`
- test case 7: x-robots-tag header values: `''` [security warning raised]

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

File: changelog/unreleased/40715 [hunk 1]
```diff
@@ -0,0 +1,7 @@
+Bugfix: X-Robots-Tag header valid values check
```
Comment (ho4ho) [inline changelog/unreleased/40715:1]:
```suggestion
Enhancement: X-Robots-Tag header valid values check
```

Thinking not bug but improvement by support more newer tags

File: changelog/unreleased/40715 [hunk 2]
```diff
@@ -0,0 +1,7 @@
+Enhancement: Improve X-Robots-Tag header values check
+
+Setup checks now allows other values other than "none" for X-Robots-Tag header.
+If "none" or "noindex" and "nofollow" are missing, a security warning is raised.
+Previously a header value with "noindex" and "nofollow" wasn't allowed event if it was valid.
```
Comment (phil-davis) [inline changelog/unreleased/40715:5]:
```suggestion
Previously a header value with "noindex" and "nofollow" wasn't allowed even though it was valid.
```

File: core/js/setupchecks.js [hunk 3]
```diff
@@ -238,17 +238,30 @@
...
 
 				for (var header in securityHeaders) {
-					if(!xhr.getResponseHeader(header) || xhr.getResponseHeader(header).toLowerCase() !== securityHeaders[header].toLowerCase()) {
+					if (header === 'X-Robots-Tag') {
+						xRobotsTagValues = [];
+						if(xhr.getResponseHeader(header)) {
+							xRobotsTagValues = xhr.getResponseHeader(header).split(',').map(item=>item.trim());
+						}
+
+						if (!xRobotsTagValues.includes('none') && !(xRobotsTagValues.includes('noindex') && xRobotsTagValues.includes('nofollow'))) {
```
Comment (phil-davis) [inline core/js/setupchecks.js:254]: I think that this check will allow the tag to be set to all 3 - "none","noindex","nofollow" - but if something does that then I suppose it is strange but will work OK.

**Comment by phil-davis** [comment]
Reviewers - after review is all done, merge this and include in 10.12.1 or wait?

File: core/js/setupchecks.js (hunk 3 above)
Comment (rizlas) [reply core/js/setupchecks.js:254]: Hi,
yes you're right. It'll allow header value "none, noindex, nofollow".

Comment (jvillafanez) [reply core/js/setupchecks.js:254]: I'm not sure if we still support IE11, but I'd try to keep compatibility just in case. "include" doesn't seem to be supported in IE11. Same for the `=>` operator a couple of lines above

File: core/js/setupchecks.js [hunk 4]
```diff
@@ -238,17 +238,30 @@
...
+							messages.push({
+								msg: t('core', 'The "{header}" HTTP header is misconfigured. Expected values are "none" or "noindex, nofollow". This is a potential security or privacy risk and we recommend adjusting this setting.', {header: header}),
+								type: OC.SetupChecks.MESSAGE_TYPE_WARNING
+							});
+						}
+					}
+					else if(!xhr.getResponseHeader(header) || xhr.getResponseHeader(header).toLowerCase() !== securityHeaders[header].toLowerCase()) {
```
Comment (jvillafanez) [inline core/js/setupchecks.js:261]: To keep the same style:
```
if (.....) {
  .....
} else if (.....) {
  .....
}
```
or
```
if (.....) {
  .....
} else {
  if (.....) {
    .....
  }
}
```

**Comment by jvillafanez** [comment]
You might also want to create a function in order to move all the checks there. The idea would be to add support for arrays, so you could use `'X-Robots-Tag': 'none'` or `'X-Robots-Tag': ['none', 'noindex', 'nofollow'],`.

Note that I'm just commenting about the code itself. I don't know if the code is right or wrong.

**Comment by jnweiger** [comment]
> Reviewers - after review is all done, merge this and include in 10.12.1 or wait?

I'd say wait. 
a) because 10.12.1 is about to be shipped. and 
b) this one touches security - hardening related topics. We need deeper understanding why we recommend 'none'.
Reference:
https://doc.owncloud.com/server/next/admin_manual/configuration/server/harden_server.html#use-of-security-related-headers-on-the-web-server

File: core/js/setupchecks.js (hunk 3 above)
Comment (rizlas) [reply core/js/setupchecks.js:254]: Thank you, I'll try to make it compatible.

File: core/js/setupchecks.js (hunk 4 above)
Comment (rizlas) [reply core/js/setupchecks.js]: Thank you. Fixed with last commit.

**Comment by rizlas** [comment]
@jvillafanez array is used only during validation. It is not a valid type input. Imho a separate function is not needed.

@jnweiger combinations of `none, noindex, nofollow, nosnippet, noarchive` are 32 (2^5) and they are:

```
''
none
noindex
nofollow
nosnippet
noarchive
none, noindex
none, nofollow
none, nosnippet
none, noarchive
noindex, nofollow
noindex, nosnippet
noindex, noarchive
nofollow, nosnippet
nofollow, noarchive
nosnippet, noarchive
none, noindex, nofollow
none, noindex, nosnippet
none, noindex, noarchive
none, nofollow, nosnippet
none, nofollow, noarchive
none, nosnippet, noarchive
noindex, nofollow, nosnippet
noindex, nofollow, noarchive
noindex, nosnippet, noarchive
nofollow, nosnippet, noarchive
none, noindex, nofollow, nosnippet
none, noindex, nofollow, noarchive
none, noindex, nosnippet, noarchive
none, nofollow, nosnippet, noarchive
noindex, nofollow, nosnippet, noarchive
none, noindex, nofollow, nosnippet, noarchive
```

With the current code these combinations are **not** valid:

```
''
noindex
nofollow
nosnippet
noarchive
noindex, nosnippet
noindex, noarchive
nofollow, nosnippet
nofollow, noarchive
nosnippet, noarchive
noindex, nosnippet, noarchive
nofollow, nosnippet, noarchive
```

On the contrary these are valid input:

```
none
none, noindex
none, nofollow
none, nosnippet
none, noarchive
noindex, nofollow
none, noindex, nofollow
none, noindex, nosnippet
none, noindex, noarchive
none, nofollow, nosnippet
none, nofollow, noarchive
none, nosnippet, noarchive
noindex, nofollow, nosnippet
noindex, nofollow, noarchive
none, noindex, nofollow, nosnippet
none, noindex, nofollow, noarchive
none, noindex, nosnippet, noarchive
none, nofollow, nosnippet, noarchive
noindex, nofollow, nosnippet, noarchive
none, noindex, nofollow, nosnippet, noarchive
```

**Review by jvillafanez — APPROVED** [review]
This should be fine assuming there won't be changes in the checks. I mean, the "X-Robots-Tag" header will be the only exception to the exact match of key - values we're checking.

**Comment by phil-davis** [comment]
10.12.1 has been merged back to master, so we can merge new stuff like this.

**Review by phil-davis — APPROVED** [review]

**Comment by rizlas** [comment]
Thank you
