### PR TITLE
Dont lower the mtime of a folder when propagating changes

### LINKED ISSUE #14172: Change-Date of a folder in the webinterface shows wrong time
I discovered that in the webview of owncloud the "latest modified" timestamp ist not as I epect it to be. Maybe I am wrong, than please correct me.

Steps to reproduce the error:
1) Create a folder (a) with a client and let it sync with owncloud
2) Create a NEW file (b1) (with current timestamp as modfied date) and save it into that folder
3) let it sync with owncloud - when viewing the parent folder of (a) in ownclouds webview it shows the timestamp of file (b1) as latest modified date - so far so good.
4) Move a old file (b2) (PDF, or what ever) with an very olde modified timestamp into the folder (a)
5) Let it sync with owncloud - when viewing the parent folder of (a) in ownclouds webview it says that the latest modified date is the one of file (b2). Which means very, very old.

I would epect owncloud to display the most up to date timestamp of file (b1) or the time when I moved the old file (b1) into the folder (a). 
This means I have moved an old file into my folder and suddendly the latest modified date jumps back a view years :-)

### PR DESCRIPTION
**Pull request by icewind1991**
When touching the mtime of a file (such as when uploading trough the sync client) the mtime is propagated to the parent folders.
This changes it to only increase mtimes when propagating to make sure the mtime of a folder is equal to the highest mtime of the files contained in the folder instead of setting it to the mtime of the latest uploaded file.

Fixes #14172

@zocker22  can you verify that this fixes the problem for you

cc @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by zocker22** [comment]
@icewind1991 Yes, I tested it an can confirm that this fixed the problem.

**Comment by DeepDiver1975** [comment]
:+1:

File: lib/private/files/cache/changepropagator.php [hunk 1]
```diff
@@ -59,8 +59,8 @@ public function propagateChanges($time = null) {
 			list($storage, $internalPath) = $this->view->resolvePath($parent);
 			if ($storage) {
 				$cache = $storage->getCache();
-				$id = $cache->getId($internalPath);
-				$cache->update($id, array('mtime' => $time, 'etag' => $storage->getETag($internalPath)));
+				$entry = $cache->get($internalPath);
+				$cache->update($entry['fileid'], array('mtime' => max($time, $entry['mtime']), 'etag' => $storage->getETag($internalPath)));
```
Comment (PVince81) [inline lib/private/files/cache/changepropagator.php]: Isn't `$time` already more recent than any file ? (except if the server have timezone/time drift issues)

Comment (PVince81) [inline lib/private/files/cache/changepropagator.php]: I mean this row here makes sense, but I don't understand why it didn't work before, even though `$time` is supposed to be the most recent time already.

**Comment by DeepDiver1975** [comment]
@PVince81 sorry - review race condition :speak_no_evil:

File: lib/private/files/cache/changepropagator.php (hunk 1 above)
Comment (icewind1991) [inline lib/private/files/cache/changepropagator.php]: `$time` can be lower when it comes from a `touch`

Comment (PVince81) [inline lib/private/files/cache/changepropagator.php]: Makes sense, thanks for the clarification.
