### PR TITLE
[UI test] improve details dialog

### LINKED ISSUE #33330: [webUI tests] stale element reference checking thumbnail in details panel
The following scenario, and similar ones that check the thumbnail in the details panel, sometimes fail:
```
  Scenario: the recipient user should be able to view different areas of details panel in Shared with you page # /drone/src/tests/acceptance/features/webUIFiles/fileDetails.feature:70
    Given the user has shared the folder "simple-folder" with the user "User Two" using the webUI              # WebUISharingContext::theUserSharesTheFileFolderWithTheUserUsingTheWebUI()
    And the user re-logs in as "user2" using the webUI                                                         # WebUILoginContext::theUserRelogsInUsingTheWebUI()
    When the user browses to the shared-with-you page                                                          # WebUIFilesContext::theUserBrowsesToTheSharedWithYouPage()
    Then the folder "simple-folder (2)" should be listed on the webUI                                          # WebUIFilesContext::theFileFolderShouldBeListedOnTheWebUI()
    When the user opens the file action menu of the folder "simple-folder (2)" in the webUI                    # WebUIFilesContext::theUserOpensTheFileActionMenuOfTheFolderInTheWebui()
    And the user clicks the details file action in the webUI                                                   # WebUIFilesContext::theUserClicksTheFileActionInTheWebui()
    Then the details dialog should be visible in the webUI                                                     # WebUIFilesContext::theDetailsDialogShouldBeVisibleInTheWebui()
    And the thumbnail should be visible in the details panel                                                   # WebUIFilesContext::theThumbnailShouldBeVisibleInTheDetailsPanel()
      WebDriver\Exception\StaleElementReference: stale element reference: element is not attached to the page document
        (Session info: chrome=70.0.3538.77)
        (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.4.0-135-generic x86_64) in /drone/src/lib/composer/instaclick/php-webdriver/lib/WebDriver/Exception.php:155
      Stack trace:
      #0 /drone/src/lib/composer/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(157): WebDriver\Exception::factory(10, 'stale element r...')
      #1 /drone/src/lib/composer/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(218): WebDriver\AbstractWebDriver->curl('POST', '/execute', Array)
      #2 /drone/src/lib/composer/instaclick/php-webdriver/lib/WebDriver/Container.php(224): WebDriver\AbstractWebDriver->__call('execute', Array)
      #3 /drone/src/lib/composer/behat/mink-selenium2-driver/src/Selenium2Driver.php(288): WebDriver\Container->__call('execute', Array)
      #4 /drone/src/lib/composer/behat/mink-selenium2-driver/src/Selenium2Driver.php(263): Behat\Mink\Driver\Selenium2Driver->executeJsOnElement(Object(WebDriver\Element), 'return argument...', true)
      #5 /drone/src/lib/composer/behat/mink-selenium2-driver/src/Selenium2Driver.php(554): Behat\Mink\Driver\Selenium2Driver->executeJsOnXpath('((//html/.//*[c...', 'return {{ELEMEN...')
      #6 /drone/src/lib/composer/behat/mink/src/Element/NodeElement.php(129): Behat\Mink\Driver\Selenium2Driver->getAttribute('((//html/.//*[c...', 'style')
      #7 /drone/src/tests/acceptance/features/bootstrap/WebUIFilesContext.php(287): Behat\Mink\Element\NodeElement->getAttribute('style')
      #8 [internal function]: WebUIFilesContext->theThumbnailShouldBeVisibleInTheDetailsPanel()
```
e.g. it happened just now in core: https://drone.owncloud.com/owncloud/core/12093/493
and it has happened sometimes in when running with encryption and/or object store (files_primary_s3) - those are apps that have some impact on the backend timing/performance...

### PR DESCRIPTION
**Pull request by individual-it**
## Description
improve the details dialog page

- move getDetailsDialog as every files page can show those: every type of a files page can have a details dialog, so move it to FilePageBasic
- wait till details dialog is loaded: wait in appropriate places till the dialog is loaded, and wait when receiving a `StaleElementReference`
- use always the details dialog element inside the dialog pageobject: set the NodeElement of the dialog in the pageobject and run `find()` from inside that element where-ever possible. This makes sure we don't accidentally find elements that are outside the dialog
- check visibility of thumbnail: actually check if the thumbnail is visible

## Related Issue

- Fixes #33330 at least I hope so

## Motivation and Context
make the UI tests more robust 

## How Has This Been Tested?
:robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

File: tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php [hunk 1]
```diff
@@ -242,19 +278,46 @@ public function addComment($content) {
...
 	 */
 	public function deleteComment($content) {
-		$commentList = $this->find("xpath", $this->getCommentXpath($content));
+		$commentList = $this->detailsDialogElement->find(
+			"xpath", $this->getCommentXpath($content)
+		);
+		$this->assertElementNotNull(
+			$commentList,
+			__METHOD__ .
+			" could not find comment with conteht $content"
```
Comment (phil-davis) [inline tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php]: s/conteht/content

File: tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php [hunk 2]
```diff
@@ -242,19 +278,46 @@ public function addComment($content) {
...
 
-		$commentDeleteButton = $commentEditForm->find("xpath", $this->commentDeleteButtonXpath);
+		$commentDeleteButton = $commentEditForm->find(
+			"xpath", $this->commentDeleteButtonXpath
+		);
+		$this->assertElementNotNull(
+			$commentDeleteButton,
+			__METHOD__ .
+			" xpath: $this->commentDeleteButtonXpath" .
+			"could not find comment delete button form"
```
Comment (phil-davis) [inline tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php]: Delete "form" from the text?

File: tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php [hunk 3]
```diff
@@ -389,10 +454,24 @@ public function deleteTag($tagName) {
...
 
-				$deleteBtn = $this->find("xpath", $this->tagDeleteButtonInTagXpath);
+				$deleteBtn = $this->find(
+					"xpath", $this->tagDeleteButtonInTagXpath
+				);
+				$this->assertElementNotNull(
+					$deleteBtn,
+					__METHOD__ .
+					" xpath: $this->tagDeleteButtonInTagXpath" .
+					" could not find tag edit button"
```
Comment (phil-davis) [inline tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php]: s/edit/delete

File: tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php [hunk 4]
```diff
@@ -475,14 +556,16 @@ public function waitTillPageIsLoaded(
 				}
 			} catch (ElementNotFoundException $e) {
 				// Just loop and try again if the element was not found yet.
+			} catch (StaleElementReference $e) {
```
Comment (phil-davis) [inline tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php]: The real fix! Looks like a good thing.

**Comment by individual-it** [comment]
backport in  #33535

**Review by phil-davis — APPROVED** [review]
Looks good, and maybe CI will also pass reliably. Thanks
