### PR TITLE
Delete orphaned shares in a background job

### LINKED ISSUE #14664: Stray share entries in DB after deleting parent folder
### Steps to reproduce
1. Create a folder "test"
2. Create/upload a file "test/file.txt"
3. Share "test/file.txt" with link
4. Delete "test"
5. Check "oc_shares"

### Expected result
The share entry is gone.

### Actual result
The share entry still exists.
Also, the link share can still be opened and shows a page with an empty file or folder!

### Versions
ownCloud 6 (stable6)
ownCloud 7 (stable7)
ownCloud 8 (stable8)
master

@schiesbn I vaguely remember that there were technical issues (maybe performance) if we want to properly delete all shares

### PR DESCRIPTION
**Pull request by PVince81**
Partial fix for https://github.com/owncloud/core/issues/12323
Fixes https://github.com/owncloud/core/issues/14664
- ~~integrate with CleanTags to avoid code duplication: https://github.com/owncloud/core/blob/master/lib/repair/cleantags.php~~ maybe later...

Even though this solves the issue in a "brutal" manner by simply deleting ALL orphaned shares it feels hacky.
I could add code to find all child elements but that would take more time.

@DeepDiver1975 @icewind1991

### CODE REVIEW

File: apps/files_sharing/tests/updater.php [hunk 1]
```diff
@@ -115,6 +115,28 @@ function testDeleteParentFolder() {
...
+
+		$foldersShared = \OCP\Share::getItemsShared('file');
+		$this->assertCount(1, $foldersShared);
+
+		$this->view->unlink($this->folder);
+
+		$foldersShared = \OCP\Share::getItemsShared('file');
+		$this->assertCount(1, $foldersShared);
+
+		// TODO: run commands
```
Comment (icewind1991) [inline apps/files_sharing/tests/updater.php]: #14644 provides `$this->runCommands()` for that

File: apps/files_sharing/command/deleteorphanedsharescommand.php [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+namespace OCA\Files_sharing\Command;
+
+use OCP\Command\ICommand;
+use OCP\IDBConnection;
+
+/**
+ * Delete all share entries that have no matching entries in the file cache table.
+ */
+class DeleteOrphanedSharesCommand implements ICommand {
+	public function __construct() {
```
Comment (icewind1991) [inline apps/files_sharing/command/deleteorphanedsharescommand.php]: unneeded code

**Comment by PVince81** [comment]
Fixes https://github.com/owncloud/core/issues/6985

File: apps/files_sharing/tests/updater.php (hunk 1 above)
Comment (icewind1991) [inline apps/files_sharing/tests/updater.php]: #14644 is now merged

Comment (PVince81) [inline apps/files_sharing/tests/updater.php]: I know, I need to get my hands dirty again here :smile:

**Comment by PVince81** [comment]
@MorrisJobke check this out, you asked about the SQL query to delete orphaned shares

**Comment by PVince81** [comment]
- [ ] make it work with SQLite
- [ ] make a background job instead of a command

**Comment by PVince81** [comment]
Added unit test and special case for SQLite.

**Comment by MorrisJobke** [comment]
```
Test\BackgroundJob\DeleteOrphanedSharesJobTest::testClearShares
Orphaned shares deleted
Failed asserting that actual size 1 matches expected size 0.

/var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/apps/files_sharing/tests/deleteorphanedsharesjobtest.php:99
```

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
Jenkins PR: #15428

**Comment by PVince81** [comment]
After discussing with @MorrisJobke we decided to go the sub-query approach which works for all DBs (note that the current approach also fails on PostgreSQL).

I'll make the change.

**Comment by PVince81** [comment]
- [ ] make sure we don't delete non-file shares, need to check item_type

**Comment by PVince81** [comment]
Since we're failing anyway let's take the opportunity to squash....

File: apps/files_sharing/appinfo/app.php [hunk 3]
```diff
@@ -51,6 +51,8 @@
 OCP\Util::addScript('files_sharing', 'share');
 OCP\Util::addScript('files_sharing', 'external');
 
+\OC::$server->getJobList()->add('OCA\Files_sharing\Lib\DeleteOrphanedSharesJob');
```
Comment (PVince81) [inline apps/files_sharing/appinfo/app.php]: @nickvergessen do you have a suggestion where to register this instead of here ? (in the other PR you mentioned the fact that it would query oc_jobs to check for existence for every request)

**Comment by PVince81** [comment]
Jenkins PR: https://github.com/owncloud/core/pull/15442

**Comment by PVince81** [comment]
Retested with a shared address book. I can confirm that only the orphaned folder share was deleted.

**Comment by PVince81** [comment]
@icewind1991 @nickvergessen @DeepDiver1975 @LukasReschke review ?

**Comment by MorrisJobke** [comment]
Squashed and jenkins PR update pushed :)

**Comment by PVince81** [comment]
Individual test pass locally but not on Jenkins, possibly a side-effect of other tests:
```
12:24:51 1) Test\BackgroundJob\DeleteOrphanedSharesJobTest::testClearShares
12:24:51 Orphaned shares deleted
12:24:51 Failed asserting that actual size 1 matches expected size 0.
12:24:51 
12:24:51 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/apps/files_sharing/tests/deleteorphanedsharesjobtest.php:122
```

I'll see what I can do.

File: apps/files_sharing/appinfo/app.php (hunk 3 above)
Comment (nickvergessen) [inline apps/files_sharing/appinfo/app.php]: We need a method that is only called on enabling an app. I don't think that is the case currently.
I'd suggest `OCP\AppFramework\App`

Comment (nickvergessen) [inline apps/files_sharing/appinfo/app.php]: However, most apps use Application as a class name for their `OCP\AppFramework\App` implementation, but since it is not mandatory, I think we either need to change this requirement, if an app wants to make use of this mechanism, or we need to add the option for providing the class name via info.xml, because otherwise we can not know, which class we need to create and call the `enable()` method on.

Comment (PVince81) [inline apps/files_sharing/appinfo/app.php]: Yes, or something like a "cron.php" in appinfo where only cron jobs are registered.
Or have the job manager detect whether we're actually running cron.php, if not then ignore everything.

**Comment by PVince81** [comment]
Rebased onto master

File: apps/files_sharing/appinfo/app.php (hunk 3 above)
Comment (nickvergessen) [inline apps/files_sharing/appinfo/app.php]: and have yet another file to load? :P 
I think application should be fine, as it can be reused for other cases aswell.

Comment (PVince81) [inline apps/files_sharing/appinfo/app.php]: You're talking about the new API/functions that we thought about adding to the Application class, right ? Nothing that already exists ?

I saw that the activity app also registers its jobs in app.php, so I guess that part isn't ready yet. https://github.com/owncloud/activity/blob/master/appinfo/app.php#L50

**Comment by PVince81** [comment]
Jenkins PR: https://github.com/owncloud/core/pull/15457

**Comment by PVince81** [comment]
Still the same:
```
05:24:53 1) Test\BackgroundJob\DeleteOrphanedSharesJobTest::testClearShares
05:24:53 Orphaned shares deleted
05:24:53 Failed asserting that actual size 1 matches expected size 0.
```

File: apps/files_sharing/appinfo/app.php (hunk 3 above)
Comment (nickvergessen) [inline apps/files_sharing/appinfo/app.php]: Yes, please at least put a FIXME in the code, so we remember that this is bad when someone wants to copy it ;)

Comment (PVince81) [inline apps/files_sharing/appinfo/app.php]: Will do.

Also raised ticket https://github.com/owncloud/core/issues/15460 to discuss this further

**Comment by PVince81** [comment]
The test doesn't work any more because somehow the trashbin appears and moves the files to trash instead of a full deletion. For some reason it didn't many commits ago.

I'll try and find a solution.

**Comment by nickvergessen** [comment]
@PVince81 related to storage wrapping?

**Comment by PVince81** [comment]
Jenkins PR: https://github.com/owncloud/core/pull/15466

**Comment by PVince81** [comment]
@nickvergessen yes, but the wrapping is normal here (not a bug).
But for the sake of unit testing, I disabled the trashbin (like we do in other places)

**Comment by PVince81** [comment]
Tests passed, please review @MorrisJobke @DeepDiver1975 @LukasReschke @nickvergessen

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
maybe @rullzer or @Xenopathic want to review this? ;)

**Comment by MorrisJobke** [comment]
@LukasReschke @nickvergessen @DeepDiver1975 Reviewers needed :)

**Comment by karlitschek** [comment]
:+1:
