### PR TITLE
Scale up the font on larger previews

### LINKED ISSUE #15634: Blank text file previews
### Steps to reproduce:
1. Checkout git master (1a2475227b6777e016ec931ddae533437bfbb2dd)
2. Setup OC from scratch
3. Upload a text file

### Expected result
Text file has preview

### Actual result
Text file preview is blank/white.
Other previews work fine.

### Versions
openSUSE Factory
php5-5.6.7-1.1.x86_64
apache2-2.4.12-2.1.x86_64
ImageMagick-6.9.0.9-1.1.x86_64

Breaking commit: 6c327f8331617652ef0b268d51edc6a23624e33c (about max preview size)

@georgehrke @oparoz please have a look

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #15634, #11469

@georgehrke @PVince81

### CODE REVIEW

**Comment by nickvergessen** [comment]
@oparoz

**Comment by karlitschek** [comment]
:+1:

**Comment by oparoz** [comment]
That works for small 36x36 previews but not for publicly shared links
publicpreview

**Comment by oparoz** [comment]
I think there are a few open tickets asking for those large previews to be rendered as text directly, but I don't remember what's holding that back.

**Comment by nickvergessen** [comment]
Well the other idea would be to not use the max-size thumb trick for txt previews. But then we would need to extend the API of the preview providers, so they can specify whether or not they support the max-size trick

**Comment by oparoz** [comment]
I don't think the max preview is to blame. This has never worked properly, so it would be best to fix the txt provider imo.

**Comment by nickvergessen** [comment]
@oparoz well but if we use a font size that looks good on the public page (sharing thing), then you get a not-readable 36*36 preview, because that is just a resized version of the public page preview.

**Comment by oparoz** [comment]
Txt seems to be the only exception, so maybe it best to fix the public page than mess with the preview system?
Maybe use 3 instead of 5 for now so that small previews work and large previews are a bit less bad?
`$fontSize = ($maxX) ? (int) ((3 / 36) * $maxX) : 5; //5px`

**Comment by oparoz** [comment]
There are plenty of exceptions already in the public page
https://github.com/owncloud/core/blob/master/apps/files_sharing/js/public.js#L104-L117

**Comment by nickvergessen** [comment]
Closing in favor of #15652

**Comment by nickvergessen** [comment]
Okay, not really replaced, since this one fixes the mini previews, while the other one fixes the public page

File: lib/private/preview/txt.php [hunk 1]
```diff
@@ -55,7 +55,7 @@ public function getThumbnail($path, $maxX, $maxY, $scalingup, $fileview) {
 
 		$lines = preg_split("/\r\n|\n|\r/", $content);
 
-		$fontSize = 5; //5px
+		$fontSize = ($maxX) ? (int) ((5 / 36) * $maxX) : 5; //5px
```
Comment (nickvergessen) [inline lib/private/preview/txt.php]: @oparoz 
> Txt seems to be the only exception, so maybe it best to fix the public page than mess with the preview system?
Maybe use 3 instead of 5 for now so that small previews work and large previews are a bit less bad?
`$fontSize = ($maxX) ? (int) ((3 / 36) * $maxX) : 5; //5px`

Comment (nickvergessen) [inline lib/private/preview/txt.php]: @oparoz I used `5 / 36` because this is the original font size that was used.

Comment (oparoz) [inline lib/private/preview/txt.php]: OK

**Comment by oparoz** [comment]
:+1: from me, if used in combination with #15652 and if that's the sane thing to do.

**Comment by nickvergessen** [comment]
@MorrisJobke another review? ;)

**Comment by MorrisJobke** [comment]
:+1:
