### PR TITLE
Fix static tags filtering in the backend

### LINKED ISSUE #34440: Static tags should be filtered in the server
### Steps to reproduce
1. Create static tags by assigning to the groups, say `group1`
2. Login as a user , say `user1` who does not belongs to `goup1`
3. Navigate to the tags page
4. Open the web dev tools to see the request and response
5. Try to get the filters by clicking on the `Select tags to filter by`
6. Verify the reponse, it will have static tags.

### Expected behaviour
The response should not have static tags 

### Actual behaviour
The response does have static tags

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** mysql

**PHP version:** 7.2

**ownCloud version:** (see ownCloud admin page) stable10 branch

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

### PR DESCRIPTION
**Pull request by sharidas**
Fix static tags filtering in the backend.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Static tags filtering was done in the frontend https://github.com/owncloud/core/pull/34116. We need to do this in the backend. The filtering is done in the method `getchildren()`. If th user does not have privilege to see the static tags, in the search, then it should be hidden for him/her.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/34440

## Motivation and Context

The backend should provide the tags which could be viewed by the user. Basically it helps the UI to filter it out.

## How Has This Been Tested?

- Create 3 users `admin`, `user1` and `user2`.
- Create 2 groups `group1` and assign `user1` to it. `user2` is assigned to `group2`.
- As `admin` user create 4 tags `visibleTag`, `restrictTag` ( `group1` is assgined to it ), `staticTag` ( `group2` is assigned to it) , `invisibleTag`.
- Login as `user2` and navigate to tags page, the user would see `staticTag`
    - response captured from the dev console 
```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/testing3/remote.php/dav/systemtags/</d:href>
    <d:propstat>
      <d:prop>
        <oc:id/>
        <oc:display-name/>
        <oc:user-visible/>
        <oc:user-editable/>
        <oc:user-assignable/>
        <oc:editable-in-group/>
        <oc:can-assign/>
      </d:prop>
      <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/testing3/remote.php/dav/systemtags/2</d:href>
    <d:propstat>
      <d:prop>
        <oc:id>2</oc:id>
        <oc:display-name>restrictTag</oc:display-name>
        <oc:user-visible>true</oc:user-visible>
        <oc:user-editable>false</oc:user-editable>
        <oc:user-assignable>false</oc:user-assignable>
        <oc:editable-in-group>false</oc:editable-in-group>
        <oc:can-assign>false</oc:can-assign>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/testing3/remote.php/dav/systemtags/3</d:href>
    <d:propstat>
      <d:prop>
        <oc:id>3</oc:id>
        <oc:display-name>staticTag</oc:display-name>
        <oc:user-visible>true</oc:user-visible>
        <oc:user-editable>false</oc:user-editable>
        <oc:user-assignable>true</oc:user-assignable>
        <oc:editable-in-group>true</oc:editable-in-group>
        <oc:can-assign>true</oc:can-assign>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/testing3/remote.php/dav/systemtags/1</d:href>
    <d:propstat>
      <d:prop>
        <oc:id>1</oc:id>
        <oc:display-name>visibleTag</oc:display-name>
        <oc:user-visible>true</oc:user-visible>
        <oc:user-editable>true</oc:user-editable>
        <oc:user-assignable>true</oc:user-assignable>
        <oc:editable-in-group>false</oc:editable-in-group>
        <oc:can-assign>true</oc:can-assign>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```
- Login as `user1` and navigate to tags page, the user would not see `staticTag`.
    - response captured from the dev console
```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/testing3/remote.php/dav/systemtags/</d:href>
    <d:propstat>
      <d:prop>
        <oc:id/>
        <oc:display-name/>
        <oc:user-visible/>
        <oc:user-editable/>
        <oc:user-assignable/>
        <oc:editable-in-group/>
        <oc:can-assign/>
      </d:prop>
      <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/testing3/remote.php/dav/systemtags/2</d:href>
    <d:propstat>
      <d:prop>
        <oc:id>2</oc:id>
        <oc:display-name>restrictTag</oc:display-name>
        <oc:user-visible>true</oc:user-visible>
        <oc:user-editable>false</oc:user-editable>
        <oc:user-assignable>false</oc:user-assignable>
        <oc:editable-in-group>true</oc:editable-in-group>
        <oc:can-assign>true</oc:can-assign>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/testing3/remote.php/dav/systemtags/1</d:href>
    <d:propstat>
      <d:prop>
        <oc:id>1</oc:id>
        <oc:display-name>visibleTag</oc:display-name>
        <oc:user-visible>true</oc:user-visible>
        <oc:user-editable>true</oc:user-editable>
        <oc:user-assignable>true</oc:user-assignable>
        <oc:editable-in-group>false</oc:editable-in-group>
        <oc:can-assign>true</oc:can-assign>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

File: apps/dav/tests/unit/SystemTag/SystemTagsByIdCollectionTest.php [hunk 1]
```diff
@@ -178,6 +179,57 @@ public function testGetChildrenNonAdmin() {
...
+		return [
+			[true], //User belongs to static tags group
+			[false], //User does not belong to static tags group
+		];
+	}
+
+	/**
+	 * @dataProvider providesGetChildrenWithStaticTagsAndOtherTags
+	 */
+	public function testGetChildrenWithStaticTagsAndOtherTags($staticTagGroup) {
```
Comment (PVince81) [inline apps/dav/tests/unit/SystemTag/SystemTagsByIdCollectionTest.php]: you're reusing almost none of the code, so doesn't make sense to use a flag here. just write two separate methods

File: apps/dav/lib/SystemTag/SystemTagsByIdCollection.php [hunk 2]
```diff
@@ -120,6 +120,20 @@ public function getChildren() {
...
+		 */
+		$tags =  \array_filter($tags, function ($tag) {
+			if (!$tag->isUserEditable() && $tag->isUserAssignable()) {
+				$user = $this->userSession->getUser();
+				if (($user !== null) &&
+					!$this->tagManager->canUserUseStaticTagInGroup($tag, $user)) {
+					return;
+				}
+			}
+			return $tag;
```
Comment (PVince81) [inline apps/dav/lib/SystemTag/SystemTagsByIdCollection.php]: return true ? this isn't array_map

**Review by PVince81 — COMMENTED** [review]
see comments

File: apps/dav/tests/unit/SystemTag/SystemTagsByIdCollectionTest.php (hunk 1 above)
Comment (sharidas) [reply apps/dav/tests/unit/SystemTag/SystemTagsByIdCollectionTest.php]: Splitted into 2 methods.

File: apps/dav/lib/SystemTag/SystemTagsByIdCollection.php (hunk 2 above)
Comment (sharidas) [reply apps/dav/lib/SystemTag/SystemTagsByIdCollection.php]: Returned true. And null `return;` is changed to `return false;`

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by sharidas** [comment]
Backport to stable10: https://github.com/owncloud/core/pull/34557
