### PR TITLE
[Tests-Only] Make PROPFIND response href test checks more flexible

### LINKED ISSUE #471: make steps that check the PROPFIND response less specific
OCIS storage tests like `apiOcisSpecific/apiWebdavProperties2-getFileProperties.feature:65` fail because the order of responses are different that expected

`And the value of the item "//d:response[2]/d:href" in the response to user "Alice" should match "/remote\.php\/<expected_href>\/file1.txt/"`
if the response has that file1.txt in the first item the test would fail, but the response actually is fine

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Make a more generic test step for checking for entries of files in a PROPFIND of a folder.
The step is more flexible so that the files do not have to be in a specific sorted order - they can be in any order in the list of files in the response.

## Related Issue
- Fixes https://github.com/owncloud/ocis-reva/issues/471

## How Has This Been Tested?
CI and local test runs

PR https://github.com/owncloud/ocis-reva/pull/474 to demonstrate this passes in `owncloud/ocis-reva`

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

File: tests/acceptance/features/bootstrap/WebDavPropertiesContext.php [hunk 1]
```diff
@@ -617,6 +617,45 @@ public function assertValueOfItemInResponseRegExp($xpath, $pattern) {
...
+			);
+		}
+
+		$user = $this->featureContext->getActualUsername($user);
+		$pattern = $this->featureContext->substituteInLineCodes(
+			$pattern, $user, ['preg_quote' => ['/']]
+		);
+
+		$index = 0;
+		while (true) {
```
Comment (PVince81) [inline tests/acceptance/features/bootstrap/WebDavPropertiesContext.php:644]: I suppose you could have used a "do...while" here

**Review by PVince81 — APPROVED** [review]
:+1:

File: tests/acceptance/features/bootstrap/WebDavPropertiesContext.php (hunk 1 above)
Comment (phil-davis) [reply tests/acceptance/features/bootstrap/WebDavPropertiesContext.php:644]: True, I didn't revisit the loop at the end of coding. As it turned out the test+break is at the end of the loop, so do-while would have worked. For now I will leave it as-is - we want to get this in and working.
