### PR TITLE
[Tests-Only] Undefined index value in server log is fixed

### LINKED ISSUE #138: Undefined index: value
While running some password_policy tests locally I noticed my PHP dev server output:
```
...
[Wed Mar 18 17:29:32 2020] 192.168.1.22:35444 [200]: /status.php
[Wed Mar 18 17:29:32 2020] 192.168.1.22:35446 [200]: /status.php
[Wed Mar 18 17:29:32 2020] 192.168.1.22:35448 [200]: /status.php
[Wed Mar 18 17:29:32 2020] 192.168.1.22:35450 [200]: /status.php
[Wed Mar 18 17:29:32 2020] 192.168.1.22:35452 [207]: /remote.php/webdav/folder-to-share
[Wed Mar 18 17:29:32 2020] Undefined index: value at /home/phil/git/owncloud/core/apps-external/testing/lib/Config.php#102
[Wed Mar 18 17:29:32 2020] 192.168.1.22:35458 [200]: /ocs/v2.php/apps/testing/api/v1/apps
[Wed Mar 18 17:29:32 2020] 192.168.1.22:35460 [200]: /ocs/v2.php/apps/testing/api/v1/apps
[Wed Mar 18 17:29:33 2020] 192.168.1.22:35466 [200]: /ocs/v2.php/apps/testing/api/v1/occ
[Wed Mar 18 17:29:33 2020] 192.168.1.22:35474 [200]: /ocs/v2.php/apps/testing/api/v1/opcache
[Wed Mar 18 17:29:33 2020] 192.168.1.22:35476 [200]: /ocs/v2.php/apps/testing/api/v1/occ
[Wed Mar 18 17:29:33 2020] 192.168.1.22:35480 [200]: /ocs/v2.php/apps/testing/api/v1/opcache
[Wed Mar 18 17:29:34 2020] 192.168.1.22:35484 [200]: /ocs/v2.php/apps/testing/api/v1/lockprovisioning
[Wed Mar 18 17:29:34 2020] 192.168.1.22:35488 [200]: /ocs/v1.php/apps/testing/api/v1/apps
[Wed Mar 18 17:29:34 2020] 192.168.1.22:35490 [200]: /ocs/v2.php/apps/testing/api/v1/occ
[Wed Mar 18 17:29:34 2020] 192.168.1.22:35492 [200]: /ocs/v2.php/apps/testing/api/v1/opcache
...
```

Something is calling the testing app to set some setting(s) and is not sending `value`

Investigate.

(Probably this will be something in `run.sh` or a BeforeScenario of the ordinary test environment setup - ~likely it needs fixing in core - just a guess~ - it does not happen when I run a core scenario, so next guess is something in password_policy BeforeScenario)

### PR DESCRIPTION
**Pull request by Talank**
## Description
Code to check for array of value in `App Parameter Values` has been added in afterscenario. The error was causing undefined index problem in log as described in https://github.com/owncloud/testing/issues/138

## Related Issue
Fixes https://github.com/owncloud/testing/issues/138

## How Has This Been Tested?
locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

File: tests/TestHelpers/AppConfigHelper.php [hunk 1]
```diff
@@ -286,6 +286,13 @@ public static function modifyAppConfigs(
 		$user,
 		$password, $appParameterValues, $ocsApiVersion = 2
 	) {
+		if (\is_array($appParameterValues)) {
+			foreach ($appParameterValues as $key => $value) {
+				if (isset($value['value']) && \is_array($value['value'])) {
+					$appParameterValues[$key]['value'] = \implode("", $appParameterValues[$key]['value']);
```
Comment (phil-davis) [inline tests/TestHelpers/AppConfigHelper.php]: I did some debugging and when this happens the original XML in the testing app looks like:
```
   <element>
    <configkey>types</configkey>
    <value></value>
    <appid>password_policy</appid>
    <phptype>string</phptype>
    <stringValue>start::end</stringValue>
   </element>
```
I added those `phptype` and `stringValue` to see what is happening.
The `value` is the empty string. That ends up getting back from the testing app and being saved by the BeforeScenario as a SimpleXmlElement that becomes an empty array after a JSON encode-decode.
e.g.
```
   array(5) {
     'configkey' =>
     string(5) "types"
     'value' =>
     array(0) {
     }
     'appid' =>
     string(15) "password_policy"
     'phptype' =>
     string(6) "string"
     'stringValue' =>
     string(10) "start::end"
   }
```
For our use-case we always have an empty array, so `implode` concatenates 0 empty strings together which results in an empty string.

The code here does no harm. If some real things come in the array some day, this will try concatenating them as strings. The value is supposed to be string - so that is the most reasonable thing to do.

Comment (dpakach) [inline tests/TestHelpers/AppConfigHelper.php]: I think you can just set empty string here.

**Review by phil-davis — APPROVED** [review]
