### PR TITLE
Prioritise Basic Auth header over Cookie

### LINKED ISSUE #11400: Accounts mixed on webdav sync
This bug is tested on two different servers. This bug seems to be introduced between oc6.0.4 and oc7.0.1. oc6 seems not affected. If a different alias is used for each account, everything works as expected.

### Steps to reproduce
1. Create 2 accounts on an owncloud server
2. Create a text file test1.txt in account A and test2.txt in account B
3. Create both accounts in PDFexpert
4. Sync account A in PDFexpert
5. Sync account B in PDFexpert

### Expected behaviour
Account A contains a file test1.txt, account B contains a file test2.txt

### Actual behaviour
Both accounts are equal. Account A has a file test2.txt and there is no test1.txt. Account B is correct. The incorrect file list of A is not synced back to owncloud.

### Server configuration
**Operating system**: Ubuntu 14.04 / Ubuntu 12.04

**Web server:** Apache/2.4.7 (Ubuntu) / Apache/2.2.22 (Ubuntu)

**Database:** MySQL 5.5.38 / Postgresql

**PHP version:**  5.5.9-1ubuntu4.4 / 5.3.10-1ubuntu3.14 with Suhosin-Patch

**ownCloud version:** 7.0.1 (ubuntu) / 7.0.2 (git)

**Updated from an older ownCloud or fresh install:** updated from oc7.0.0 / updated from oc6.0.4

**List of activated apps:** Uppon request

**The content of config/config.php:** Uppon request

**Are you using external storage, if yes which one:** local storage / local storage

**Are you using encryption:** no / disk encryption

### Client configuration
**Browser:** PDFexpert 4.7.8, 5.2 and Documents 5

**Operating system:** iOS 7 and iOS 8

#### Web server error log
```
10.74.0.203 - test1 [02/Oct/2014:20:45:32 +0200] "OPTIONS /remote.php/webdav HTTP/1.1" 200 2181 "-" "ReaddleDAV PDFExpert/4.7.7.2 (redirects)"
10.74.0.203 - test2 [02/Oct/2014:20:45:50 +0200] "OPTIONS /remote.php/webdav HTTP/1.1" 200 1302 "-" "ReaddleDAV PDFExpert/4.7.7.2 (redirects)"
10.74.0.203 - test1 [02/Oct/2014:20:45:51 +0200] "OPTIONS /remote.php/webdav HTTP/1.1" 200 965 "-" "ReaddleDAV PDFExpert/4.7.7.2 (redirects)"
10.74.0.203 - test1 [02/Oct/2014:20:45:51 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 3562 "-" "ReaddleDAV PDFExpert/4.7.7.2 (redirects)"
10.74.0.203 - test2 [02/Oct/2014:20:46:03 +0200] "OPTIONS /remote.php/webdav HTTP/1.1" 200 1158 "-" "ReaddleDAV PDFExpert/4.7.7.2 (redirects)"
10.74.0.203 - test2 [02/Oct/2014:20:46:03 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 3562 "-" "ReaddleDAV PDFExpert/4.7.7.2 (redirects)"
```

#### ownCloud log (data/owncloud.log)
```
No entries
```

#### Browser log
```
Not available
```

### PR DESCRIPTION
**Pull request by LukasReschke**
There are a lot of clients that support multiple WebDAV accounts in the same application. However, they resent all the cookies they received from one of the accounts also to the other one. In the case of ownCloud this means that we will always show the user from the session and not the user that is specified in the basic authentication header.

This patch adds a workaround the following way:
1. If the user authenticates via the Sabre Auth Connector add a hint to the session that this was authorized via Basic Auth (this is to prevent logout CSRF)
2. If the request contains this hint and the username specified in the basic auth header differs from the one in the session relogin the user using basic auth

Fixes https://github.com/owncloud/core/issues/11400 and https://github.com/owncloud/core/issues/13245 and probably some other issues as well.

This requires proper testing also considering LDAP / Shibboleth and whatever instances.

@DeepDiver1975 FYI

### CODE REVIEW

**Comment by LukasReschke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
```
00:31:32.224 There was 1 error:
00:31:32.224 
00:31:32.224 1) OCA\Files_Encryption\Tests\Webdav::testWebdavPUT
00:31:32.225 session_regenerate_id(): Cannot regenerate session id - headers already sent
00:31:32.225 
00:31:32.225 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/lib/private/user.php:215
00:31:32.225 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/lib/private/connector/sabre/auth.php:59
00:31:32.225 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/3rdparty/sabre/dav/lib/Sabre/DAV/Auth/Backend/AbstractBasic.php:77
00:31:32.225 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/lib/private/connector/sabre/auth.php:118
00:31:32.225 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/lib/private/connector/sabre/auth.php:100
00:31:32.225 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/3rdparty/sabre/dav/lib/Sabre/DAV/Auth/Plugin.php:108
00:31:32.225 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php:433
00:31:32.225 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php:455
00:31:32.225 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php:214
00:31:32.225 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/apps/files_encryption/tests/webdav.php:248
00:31:32.225 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/apps/files_encryption/tests/webdav.php:117
```

**Comment by LukasReschke** [comment]
Encryption phun. – Love it… Will take a look later.

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please

**Comment by LukasReschke** [comment]
Look I was able to kill the Job execution – great fun… – Let's see how we can "fix" this otherwise…

**Comment by LukasReschke** [comment]
This is caused by Unit Test madness in the encryption app which does some black magic that it is certainly not supposed to do. (using `ob_start()` and `ob_get_contents()` etc…)

**Comment by LukasReschke** [comment]
Just as a remark: Whatever https://github.com/owncloud/core/blob/60c4cb1dd669a0c40abcff50a636d7b4cb6469e0/apps/files_encryption/tests/webdav.php#L98-L151 and https://github.com/owncloud/core/blob/60c4cb1dd669a0c40abcff50a636d7b4cb6469e0/apps/files_encryption/tests/webdav.php#L205-L258 are supposed to test – sending a faked WebDAV request and abusing `$_SERVER`, `ob`-functions and Co. is *NOT* unit-testing…

Honestly stuff like the following do certainly not belong in our unit tests:

```php

// set server vars
$_SERVER['REQUEST_METHOD'] = 'OPTIONS';
$_SERVER['REQUEST_METHOD'] = 'PUT';
$_SERVER['REQUEST_URI'] = '/remote.php/webdav' . $filename;
$_SERVER['HTTP_AUTHORIZATION'] = 'Basic dGVzdC13ZWJkYXYtdXNlcjE6dGVzdC13ZWJkYXYtdXNlcjE=';
$_SERVER['CONTENT_TYPE'] = 'application/octet-stream';
$_SERVER['PATH_INFO'] = '/webdav' . $filename;
$_SERVER['CONTENT_LENGTH'] = strlen($this->dataShort);
// handle webdav request
$this->handleWebdavRequest($this->dataShort);
```

**Comment by LukasReschke** [comment]
```php
	 * @note this init procedure is copied from /apps/files/appinfo/remote.php
```

?????????

**Comment by LukasReschke** [comment]
Furthermore that "test" has side effects without end… – Preparing another over ugly hack …

**Comment by LukasReschke** [comment]
And another checkout fail……

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please

**Comment by LukasReschke** [comment]
The "Unit" tests should pass now

**Comment by DeepDiver1975** [comment]
let me see if this stuff still works ..... :wink:

**Comment by LukasReschke** [comment]
:see_no_evil: :hear_no_evil: :speak_no_evil:

**Comment by DeepDiver1975** [comment]
Testing mirall against this branch in a mod_shib envrionment - works :+1:

**Comment by DeepDiver1975** [comment]
works as in
- [ ] setup the connection
- [ ] download files
- [ ] chunked upload

**Comment by DeepDiver1975** [comment]
cadaver works as well

File: lib/private/connector/sabre/auth.php [hunk 1]
```diff
@@ -22,25 +22,49 @@
...
+	 * @param string $password
 	 * @return bool
 	 */
 	protected function validateUserPass($username, $password) {
-		if (OC_User::isLoggedIn()) {
+		if (OC_User::isLoggedIn() &&
+			$this->isDavAuthenticated($username)
+		) {
 			OC_Util::setupFS(OC_User::getUser());
 			return true;
```
Comment (DeepDiver1975) [inline lib/private/connector/sabre/auth.php]: in this case the session is not closed - intended?

Comment (LukasReschke) [inline lib/private/connector/sabre/auth.php]: I doubt it… – Adjusting…

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
@LukasReschke looks like @owncloud-bot needs a new branch to operate on ...

**Comment by LukasReschke** [comment]
How could I say nay to my good old pal @owncloud-bot: https://github.com/owncloud/core/pull/13483

**Comment by LukasReschke** [comment]
CI is happy now.

**Comment by MorrisJobke** [comment]
Tested with cadaver against user_ldap

**Comment by MorrisJobke** [comment]
:+1:
