### PR TITLE
Repair job to fix permissions for avatars

### LINKED ISSUE #22978: Missing Avatar after upgrade from 8.2.3 to 9.0.0
### Steps to reproduce
1. Have an avatar set in ownCloud. Mind: in the user home directory, there is only avatar.jpg, but no avatar.32.jpg
2. Do the upgrade
3. Login, or go to Personal or Users page

### Expected behaviour
Avatar is visible as it was before

### Actual behaviour
No Avatar in the header (but also no display name), placeholders in other places.

Copying the avatar.jpg file to avatar.32.jpg brings it back.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache 2

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** Update from 8.2.3

**Where did you install ownCloud from:** Tarball

**Signing status (ownCloud 9.0 and above):** awesome

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'datadirectory' => '/var/lib/owncloud/ovin-data',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'installedat' => '1326327271.69',
  'lastupdatedat' => '1338667774.87',
  'dbname' => 'foobar',
  'dbhost' => 'localhost',
  'dbtableprefix' => '',
  'dbuser' => 'barfoo',
  'dbpassword' => 'foo',
  'installed' => true,
  'instanceid' => '123456',
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 1,
  'trusted_domains' => 
  array (
    0 => 'foo.de',
    1 => 'bar.de',
    2 => 'foobar.cu',
  ),
  'secret' => 'sadf',
  'share_folder' => '/Shared',
  'asset-pipeline.enabled' => false,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/minion/ovin/apps',
      'url' => '/apps',
      'writable' => true,
    ),
    1 => 
    array (
      'path' => '/var/www/minion/apps-extra',
      'url' => '/../apps-extra',
      'writable' => true,
    ),
  ),
  'appstoreenabled' => true,
  'trashbin_retention_obligation' => 'auto',
);

```

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** FF 44

**Operating system:** Antergos Linux

#### ownCloud log (data/owncloud.log)

Nothing wrt Avatars

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #22978

On some older installations the permissions for the userRoot and the
avatars are not correct. This breaks since we now use the Node API in
the avatar code.

This repair job makes sure that the permissions are set correctly.
- Unit tests added

CC: @PVince81 @nickvergessen @icewind1991 @blizzz 

@karlitschek should be backported to 9.0 since that is where the issue originally happend.

### CODE REVIEW

File: tests/lib/Repair/AvatarPermissionsTest.php [hunk 1]
```diff
@@ -0,0 +1,188 @@
...
+ *
+ * You should have received a copy of the GNU Affero General Public License, version 3,
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>
+ *
+ */
+namespace Test\Repair;
+use OCP\Migration\IOutput;
+
+/**
+ * Tests for the cleaning the tags tables
```
Comment (nickvergessen) [inline tests/lib/Repair/AvatarPermissionsTest.php]: nop

File: tests/lib/Repair/AvatarPermissionsTest.php [hunk 2]
```diff
@@ -0,0 +1,188 @@
...
+ *
+ * @group DB
+ *
+ * @see \OC\Repair\AvatarPermissionsTest
+ */
+class AvatarPermissionsTest extends \Test\TestCase {
+
+	/** @var \OC\Repair\CleanTags */
```
Comment (nickvergessen) [inline tests/lib/Repair/AvatarPermissionsTest.php]: nop

**Comment by karlitschek** [comment]
Great fix. Makes sense to backport 👍

File: tests/lib/Repair/AvatarPermissionsTest.php [hunk 3]
```diff
@@ -0,0 +1,188 @@
...
+	/** @var \OCP\IDBConnection */
+	protected $connection;
+
+	/** @var IOutput */
+	private $outputMock;
+
+	protected function setUp() {
+		parent::setUp();
+
+		$this->outputMock = $this->getMockBuilder('\OCP\Migration\IOutput')
```
Comment (nickvergessen) [inline tests/lib/Repair/AvatarPermissionsTest.php]: unused

File: lib/private/Repair/AvatarPermissions.php [hunk 4]
```diff
@@ -0,0 +1,92 @@
...
+
+	/**
+	 * Make sure all user roots have permissions 23 (all but share)
+	 *
+	 */
+	protected function fixUserRootPermissions() {
+		$qb = $this->connection->getQueryBuilder();
+		$qb->select('numeric_id')
+			->from('storages')
+			->where($qb->expr()->like('id', 'home::%'));
```
Comment (nickvergessen) [inline lib/private/Repair/AvatarPermissions.php]:
```
Column not found: 1054 Unknown column 'home::%' in 'where clause'
```

Needs to be a parameter in qb2

File: lib/private/Repair/AvatarPermissions.php [hunk 5]
```diff
@@ -0,0 +1,92 @@
...
+			->andWhere($qb2->expr()->neq('permissions', $qb2->createNamedParameter(23)));
+
+		$qb2->execute();
+	}
+
+	protected function fixAvatarPermissions() {
+		$qb = $this->connection->getQueryBuilder();
+		$qb->select('numeric_id')
+			->from('storages')
+			->where($qb->expr()->like('id', 'home::%'));
```
Comment (nickvergessen) [inline lib/private/Repair/AvatarPermissions.php]:
```
Column not found: 1054 Unknown column 'home::%' in 'where clause'
```

Needs to be a parameter in qb2

File: tests/lib/Repair/AvatarPermissionsTest.php [hunk 6]
```diff
@@ -0,0 +1,181 @@
...
+ * but WITHOUT ANY WARRANTY; without even the implied warranty of
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
+ * GNU Affero General Public License for more details.
+ *
+ * You should have received a copy of the GNU Affero General Public License, version 3,
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>
+ *
+ */
+namespace Test\Repair;
+use OCP\Migration\IOutput;
```
Comment (nickvergessen) [inline tests/lib/Repair/AvatarPermissionsTest.php]: unused

File: lib/private/Repair/AvatarPermissions.php (hunk 4 above)
Comment (nickvergessen) [inline lib/private/Repair/AvatarPermissions.php]: Or see https://github.com/owncloud/core/blob/8fbb63d3166378ca63d6d0e6d21fa08d8d8be268/lib/private/SystemTag/SystemTagManager.php#L143-L146

**Comment by rullzer** [comment]
All fixed. Review time!

**Comment by nickvergessen** [comment]
Looks good, but lets wait for tests

**Comment by PVince81** [comment]
Guess which one failed ?

```
1) Test\Repair\AvatarPermissionsTest::testFixUserRootPermissions with data set #0 ('home::user', '', 0, 23)
07:56:22 Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("path", "storage", "permissions") VALUES(?, ?, ?)' with params ["", 1049, 0]:
07:56:22 
07:56:22 ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:68
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:78
07:56:22 
07:56:22 Caused by
07:56:22 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:214
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:987
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:78
07:56:22 
07:56:22 2) Test\Repair\AvatarPermissionsTest::testFixUserRootPermissions with data set #1 ('home::user', 'foo', 0, 0)
07:56:22 Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("path", "storage", "permissions") VALUES(?, ?, ?)' with params ["foo", 1050, 0]:
07:56:22 
07:56:22 ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:68
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:78
07:56:22 
07:56:22 Caused by
07:56:22 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:214
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:987
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:78
07:56:22 
07:56:22 3) Test\Repair\AvatarPermissionsTest::testFixUserRootPermissions with data set #2 ('home::user', 'avatar.jpg', 0, 0)
07:56:22 Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("path", "storage", "permissions") VALUES(?, ?, ?)' with params ["avatar.jpg", 1051, 0]:
07:56:22 
07:56:22 ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:68
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:78
07:56:22 
07:56:22 Caused by
07:56:22 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:214
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:987
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:78
07:56:22 
07:56:22 4) Test\Repair\AvatarPermissionsTest::testFixUserRootPermissions with data set #3 ('ABC::user', '', 0, 0)
07:56:22 Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("path", "storage", "permissions") VALUES(?, ?, ?)' with params ["", 1052, 0]:
07:56:22 
07:56:22 ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:68
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:78
07:56:22 
07:56:22 Caused by
07:56:22 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:214
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:987
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:78
07:56:22 
07:56:22 5) Test\Repair\AvatarPermissionsTest::testFixUserRootPermissions with data set #4 ('ABC::user', 'foo', 0, 0)
07:56:22 Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("path", "storage", "permissions") VALUES(?, ?, ?)' with params ["foo", 1053, 0]:
07:56:22 
07:56:22 ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:68
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:78
07:56:22 
07:56:22 Caused by
07:56:22 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:214
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:987
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:78
07:56:22 
07:56:22 6) Test\Repair\AvatarPermissionsTest::testFixAvatarPermissions with data set #0 ('home::user', '', 0, 0)
07:56:22 Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("path", "storage", "permissions") VALUES(?, ?, ?)' with params ["", 1054, 0]:
07:56:22 
07:56:22 ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:68
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:110
07:56:22 
07:56:22 Caused by
07:56:22 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:214
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:987
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:110
07:56:22 
07:56:22 7) Test\Repair\AvatarPermissionsTest::testFixAvatarPermissions with data set #1 ('home::user', 'avatar.jpg', 0, 27)
07:56:22 Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("path", "storage", "permissions") VALUES(?, ?, ?)' with params ["avatar.jpg", 1055, 0]:
07:56:22 
07:56:22 ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:68
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:110
07:56:22 
07:56:22 Caused by
07:56:22 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:214
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:987
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:110
07:56:22 
07:56:22 8) Test\Repair\AvatarPermissionsTest::testFixAvatarPermissions with data set #2 ('home::user', 'avatar.png', 0, 27)
07:56:22 Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("path", "storage", "permissions") VALUES(?, ?, ?)' with params ["avatar.png", 1056, 0]:
07:56:22 
07:56:22 ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:68
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:110
07:56:22 
07:56:22 Caused by
07:56:22 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:214
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:987
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:110
07:56:22 
07:56:22 9) Test\Repair\AvatarPermissionsTest::testFixAvatarPermissions with data set #3 ('home::user', 'avatar.32.png', 0, 27)
07:56:22 Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("path", "storage", "permissions") VALUES(?, ?, ?)' with params ["avatar.32.png", 1057, 0]:
07:56:22 
07:56:22 ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:68
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:110
07:56:22 
07:56:22 Caused by
07:56:22 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:214
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:987
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:110
07:56:22 
07:56:22 10) Test\Repair\AvatarPermissionsTest::testFixAvatarPermissions with data set #4 ('home::user', 'mine.txt', 0, 0)
07:56:22 Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("path", "storage", "permissions") VALUES(?, ?, ?)' with params ["mine.txt", 1058, 0]:
07:56:22 
07:56:22 ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:68
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:110
07:56:22 
07:56:22 Caused by
07:56:22 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:214
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:987
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:110
07:56:22 
07:56:22 11) Test\Repair\AvatarPermissionsTest::testFixAvatarPermissions with data set #5 ('ABC::user', '', 0, 0)
07:56:22 Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("path", "storage", "permissions") VALUES(?, ?, ?)' with params ["", 1059, 0]:
07:56:22 
07:56:22 ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:68
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:110
07:56:22 
07:56:22 Caused by
07:56:22 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:214
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:987
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:110
07:56:22 
07:56:22 12) Test\Repair\AvatarPermissionsTest::testFixAvatarPermissions with data set #6 ('ABC::user', 'avatar.jpg', 0, 0)
07:56:22 Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("path", "storage", "permissions") VALUES(?, ?, ?)' with params ["avatar.jpg", 1060, 0]:
07:56:22 
07:56:22 ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:68
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:110
07:56:22 
07:56:22 Caused by
07:56:22 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:214
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:987
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:110
07:56:22 
07:56:22 13) Test\Repair\AvatarPermissionsTest::testFixAvatarPermissions with data set #7 ('ABC::user', 'avatar.png', 0, 0)
07:56:22 Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("path", "storage", "permissions") VALUES(?, ?, ?)' with params ["avatar.png", 1061, 0]:
07:56:22 
07:56:22 ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:68
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:110
07:56:22 
07:56:22 Caused by
07:56:22 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:214
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:987
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:110
07:56:22 
07:56:22 14) Test\Repair\AvatarPermissionsTest::testFixAvatarPermissions with data set #8 ('ABC::user', 'avatar.32.png', 0, 0)
07:56:22 Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("path", "storage", "permissions") VALUES(?, ?, ?)' with params ["avatar.32.png", 1062, 0]:
07:56:22 
07:56:22 ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:68
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:110
07:56:22 
07:56:22 Caused by
07:56:22 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:214
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:987
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:110
07:56:22 
07:56:22 15) Test\Repair\AvatarPermissionsTest::testFixAvatarPermissions with data set #9 ('ABC::user', 'mine.txt', 0, 0)
07:56:22 Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("path", "storage", "permissions") VALUES(?, ?, ?)' with params ["mine.txt", 1063, 0]:
07:56:22 
07:56:22 ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:68
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:110
07:56:22 
07:56:22 Caused by
07:56:22 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."path_hash")
07:56:22 
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:214
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:987
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/Connection.php:209
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/DB/QueryBuilder/QueryBuilder.php:141
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:155
07:56:22 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:110
07:56:22 
```

**Comment by rullzer** [comment]
of course... man... oracle... will take care...

**Comment by nickvergessen** [comment]
I pushed a fix, lets see

**Comment by nickvergessen** [comment]
oracle still failing with one last test:
```
There was 1 failure:

1) Test\Repair\AvatarPermissionsTest::testFixUserRootPermissions with data set #0 ('home::user', '', 0, 23)
Failed asserting that 0 is identical to 23.

/ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:185
/ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/Repair/AvatarPermissionsTest.php:82
```

**Comment by rullzer** [comment]
Oracle seems happy!

**Comment by icewind1991** [comment]
Code looks good :+1:

**Comment by nickvergessen** [comment]
Okay bye since this is a repairstep, but in general ors are expensive and should be avoided. Otherwise we could switch depending on the connection->getPlatform result

**Comment by rullzer** [comment]
Ah right the platform stuff... yeah lets fix that indeed...

**Comment by rullzer** [comment]
Ok now using platform...

**Comment by PVince81** [comment]
looks like pgsql had a hiccup :frowning:

**Comment by rullzer** [comment]
Rebased...

**Comment by rullzer** [comment]
Postgres is still having trouble... but is unrelated to this PR from my POV... final review time

File: lib/private/Repair/AvatarPermissions.php [hunk 7]
```diff
@@ -0,0 +1,115 @@
...
+		} else {
+			$path = $qb2->expr()->eq('path', $qb2->createNamedParameter(''));
+		}
+
+		$qb2->update('filecache')
+			->set('permissions', $qb2->createNamedParameter(23))
+			->where($path)
+			->andWhere($qb2->expr()->in('storage', $qb2->createFunction($qb->getSQL())))
+			->andWhere($qb2->expr()->neq('permissions', $qb2->createNamedParameter(23)))
+			->setParameter('like', 'home::%');
```
Comment (PVince81) [inline lib/private/Repair/AvatarPermissions.php]: ew, this will not work with LDAP and long storage IDs :cry:

Comment (PVince81) [inline lib/private/Repair/AvatarPermissions.php]: you will need to use the Storage/Cache API to find the matching storage and adjust permissions

Comment (rullzer) [inline lib/private/Repair/AvatarPermissions.php]: why? ldap also has home::.... right?

Comment (PVince81) [inline lib/private/Repair/AvatarPermissions.php]: there is some twisted logic in the storage id code: if the actual storage id string is bigger than the column width (64?) then it will convert it to the md5 of the storage id instead. With LDAP user ids it is more likely to happen.

See https://github.com/owncloud/core/wiki/Storage-IDs#random-numberstring

It has and is still a nightmare...

Comment (nickvergessen) [inline lib/private/Repair/AvatarPermissions.php]: hmpf, should have the same as with `share::` that is keeping the prefix outside of the md5.

Comment (rullzer) [inline lib/private/Repair/AvatarPermissions.php]: uhm pfff... fair enough... but lets try to fix that separatly then... As this will not break those...

Comment (nickvergessen) [inline lib/private/Repair/AvatarPermissions.php]: Fixing some is better then fixing none

Comment (PVince81) [inline lib/private/Repair/AvatarPermissions.php]: There might be another way using `oc_mounts`: since 9.0 whenever a user has logged in at least once, their mounts points are listed under `oc_mounts`. So the storage entry is `select storage_id from oc_mounts where user_id=$userid and mount_point="/" + $userid + "/"`

@icewind1991 correct ?

Comment (nickvergessen) [inline lib/private/Repair/AvatarPermissions.php]: string concatenation in nested sql incoming :-O

Comment (rullzer) [inline lib/private/Repair/AvatarPermissions.php]: O that is nasty... I still propose to merge this and have a separate job that does the query magic...

Comment (nickvergessen) [inline lib/private/Repair/AvatarPermissions.php]: second job could search for "not starting with `home::`, `local::` and `shared::`" and then only analyze those, but I agree, lets get this in and continue in a second PR

Comment (PVince81) [inline lib/private/Repair/AvatarPermissions.php]: A second job to fill in the gaps ?  Ideally there should be only one job that does the work to its full extent. Because else later if a dev fixes a bug in one, they might forget the second one...

The sad part is that it requires iterating over users https://github.com/owncloud/core/blob/v9.0.2/lib/private/repair/repairlegacystorages.php#L214

Comment (PVince81) [inline lib/private/Repair/AvatarPermissions.php]: Okay, I the piece that iterates over user should be added in this same job, not in a separate one.
In this case this PR is acceptable as a start.

Comment (rullzer) [inline lib/private/Repair/AvatarPermissions.php]: fair enough

**Comment by PVince81** [comment]
@rullzer how to test ? I guess manually set the permissions wrong in the database ?

**Comment by rullzer** [comment]
@PVince81 yes... the only way indeed... look at the test so see.

**Comment by rullzer** [comment]
Rebased so solve conflict

**Comment by PVince81** [comment]
Tested, works :+1: 

I set the permissions to 0 on the user's storage root and also on the avatar files. The UI would not show them any more. Then I ran the upgrade (had to increase version.php) with this PR and the avatars were back.

**Comment by PVince81** [comment]
@rullzer please prepare the backport PR for 9.0

**Comment by rullzer** [comment]
Stable9 in #25068
