### PR TITLE
Catch storage exception in scanner for remote shares

### LINKED ISSUE #13089: OC 8 Alpha 1: Files for User are not shown (unbekannter Fehler)
### Steps to reproduce
1. LogIn and go to files App
2. Just one user is affected, see the Logs

### Expected behaviour
Show users Files 

### Actual behaviour
Users Files are not shown, "Unbekannter Fehler" is thrown in the UI. This only happens for one user, all the others are not affected. Please look at the log below (unauthenticated user...)

### Server configuration
Operating system: Ubuntu 14.04
Web server: apache2
Database: mySQL
PHP version: PHP 5.5.9-1ubuntu4.5
ownCloud version: Owncloud 8 Alpha 1
Updated from an older ownCloud or fresh install: update from master from 22.12.
Are you using external storage: yes, local file system
Are you using encryption: no

### Logs
```
{"reqId":"80ed4c39a6f230382edb0a527a4b855b","remoteAddr":"2a02:2450:102d:1fd:9ef3:87ff:feb2:3d02","app":"files_external","message":"Not authenticated","level":3,"time":"January 03, 2015 12:57:14"}
{"reqId":"80ed4c39a6f230382edb0a527a4b855b","remoteAddr":"2a02:2450:102d:1fd:9ef3:87ff:feb2:3d02","app":"files_external","message":"Not authenticated","level":3,"time":"January 03, 2015 12:57:14"}
{"reqId":"80ed4c39a6f230382edb0a527a4b855b","remoteAddr":"2a02:2450:102d:1fd:9ef3:87ff:feb2:3d02","app":"files_external","message":"Not authenticated","level":3,"time":"January 03, 2015 12:57:14"}
{"reqId":"80ed4c39a6f230382edb0a527a4b855b","remoteAddr":"2a02:2450:102d:1fd:9ef3:87ff:feb2:3d02","app":"files","message":"Exception: {\"Message\":\"Not authenticated\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Client.php(179): Sabre\\\\DAV\\\\Client->request('PROPFIND', '', '<?xml version=\\\"...', Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(463): Sabre\\\\DAV\\\\Client->propFind('', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(98): OC\\\\Files\\\\Storage\\\\DAV->getPermissions('')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(115): OC\\\\Files\\\\Cache\\\\Scanner->getData('')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1027): OC\\\\Files\\\\Cache\\\\Scanner->scanFile('')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(795): OC\\\\Files\\\\View->getDirectoryContent('\\\/', '')\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/lib\\\/helper.php(176): OC\\\\Files\\\\Filesystem::getDirectoryContent('\\\/')\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/list.php(28): OCA\\\\Files\\\\Helper::getFiles('\\\/', 'name', false)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 [internal function]: __lambda_func(Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_267', Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(748): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#12 \\\/var\\\/www\\\/owncloud\\\/index.php(28): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Client.php\",\"Line\":422}","level":4,"time":"January 03, 2015 12:57:15"}
```

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/13089
- [x] Requires https://github.com/owncloud/core/pull/13506 to be merged first

Please review @icewind1991 @DeepDiver1975 @MorrisJobke @nickvergessen @schiesbn 

Needs extensive testing, especially with sync client:
#### Test with:
- [x] remote share without password
- [x] remote share with password (this is broken for some other reason to be looked into, but should fail gracefully)
- [x] sync with remote share without password
- [x] sync with remote share with password
- [x] test expiring a remote share, folder will disappear

### CODE REVIEW

**Comment by derkostka** [comment]
Fixes #13089 :+1: 

Warning in Log:
{"reqId":"b982fff5b9647356bc46c98a7d366886","remoteAddr":"2a02:2450:102d:1fd:219:e3ff:fe04:2514","app":"PHP","message":"Declaration of OCA\\Files_Sharing\\External\\Scanner::scanFile() should be compatible with OC\\Files\\Cache\\Scanner::scanFile($file, $reuseExisting = 0) at \/var\/www\/owncloud\/apps\/files_sharing\/lib\/external\/scanner.php#0","level":3,"time":"January 20, 2015 20:06:20","method":"GET","url":"\/index.php\/apps\/files\/ajax\/list.php?dir=%2F&sort=name&sortdirection=asc"}

**Comment by PVince81** [comment]
@derkostka thanks for spotting, fixed now.

Rebased onto master to include the required fix.

**Comment by PVince81** [comment]
- [x] test with temporarily unavailable storage, make it available again

All seems to work (apart from the password one, to be investigated here https://github.com/owncloud/core/issues/13526

**Comment by PVince81** [comment]
I added yet another change.

If the scanner did not run yet for the external share (brand new one) but curl returns "no route to host", the code throws a generic `\Exception` because we don' want to parse curl's error string for that. Anyway, in cases like this where a storage becomes unavailable, it now fails gracefully and still shows the file list. (before that last commit the spinner would stay forever)

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

File: apps/files_sharing/lib/external/scanner.php [hunk 1]
```diff
@@ -18,8 +23,32 @@ public function scan($path, $recursive = self::SCAN_RECURSIVE, $reuse = -1) {
 		$this->scanAll();
 	}
 
+	public function scanFile($path, $reuseExisting = 0) {
+		try {
+			return parent::scanFile($path, $reuseExisting);
+		} catch (\Sabre\DAV\Exception $e) {
```
Comment (DeepDiver1975) [inline apps/files_sharing/lib/external/scanner.php]: hmm - from my understanding a sabre dav exception should be caught within the storage and be properly converted to our exceptions.

File: apps/files_sharing/lib/external/scanner.php [hunk 2]
```diff
@@ -18,8 +23,32 @@ public function scan($path, $recursive = self::SCAN_RECURSIVE, $reuse = -1) {
...
+		}
+	}
+
 	public function scanAll() {
-		$data = $this->storage->getShareInfo();
+		try {
+			$data = $this->storage->getShareInfo();
+		} catch (\Exception $e) {
+			$this->storage->checkStorageAvailability();
+			throw new \Exception('Error while scanning remote share: ' . $e->getMessage());
```
Comment (DeepDiver1975) [inline apps/files_sharing/lib/external/scanner.php]: can we add info on the storage or path where this fails?

File: apps/files_sharing/lib/external/scanner.php (hunk 1 above)
Comment (PVince81) [inline apps/files_sharing/lib/external/scanner.php]: I tried that before: need to add the exception to ALL methods in the storage then. 
The failing one was `Storage::getMimeType()`

In this specific case the exception was "AuthenticationException" which we could  convert to ForbiddenException.

Also note that this scanner implementation is kind of part of the storage :smile: (the storage returns it)

So not sure if we really need to make this change.

File: apps/files_sharing/lib/external/scanner.php (hunk 2 above)
Comment (PVince81) [inline apps/files_sharing/lib/external/scanner.php]: - [ ] add storage id / storage URL in exception

**Comment by PVince81** [comment]
Fixed exceptions.

Also I added an additional fix here to catch the "wrong password" case whenever a remote share is just being added: https://github.com/owncloud/core/pull/13525/files#diff-c463069c55f33934fa9d755dff8eb13cR62

This is actually the reason for the original bug: because of https://github.com/owncloud/core/pull/13540 the password wasn't sent in the ajax request. So the remote share was imported but without the correct password, which means that initial scanning couldn't work, which caused the issue at https://github.com/owncloud/core/issues/13089

The case that was covered so far was when the remote share password changes. In such case, the scanning already worked once so this error here was never triggered.

Anyway, to make sure this doesn't happen again, now ajax/external.php is preventing to import remote shares that have the wrong password. A proper dialog can be added later in 8.1 (this PR is about failing gracefully in other cases, mostly)

**Comment by PVince81** [comment]
Jenkins PR here: https://github.com/owncloud/core/pull/13551

**Comment by PVince81** [comment]
Tests passed there: https://github.com/owncloud/core/pull/13551#issuecomment-70849437

And suprisingly Jenkins worked again here

**Comment by MorrisJobke** [comment]
> And suprisingly Jenkins worked again here

As it is the exact same commit github is smart enough to put the green checkmark also on this PRs commit ;)

**Comment by PVince81** [comment]
Rebased

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by DeepDiver1975** [comment]
> :+1: looks good

sorry - but looks good is not enough for me on this critical change - please test - THX

**Comment by icewind1991** [comment]
tested, all looks good

**Comment by PVince81** [comment]
Thanks a lot!

**Comment by derkostka** [comment]
the fix works, i get another warning however:
{"reqId":"562fc2302cc437023e7fdd4437fdead4","remoteAddr":"2a02:2450:102d:318:219:e3ff:fe04:2514","app":"PHP","message":"Class 'OC\\Files\\View' not found at \/var\/www\/owncloud\/lib\/private\/files\/filesystem.php#298","level":3,"time":"January 22, 2015 20:02:22"}

File: apps/files_sharing/lib/external/scanner.php [hunk 3]
```diff
@@ -18,12 +23,42 @@ public function scan($path, $recursive = self::SCAN_RECURSIVE, $reuse = -1) {
...
+		} catch (ForbiddenException $e) {
+			$this->storage->checkStorageAvailability();
+		} catch (NotFoundException $e) {
+			// if the storage isn't found, the call to
+			// checkStorageAvailable() will verify it and remove it
+			// if appropriate
+			$this->storage->checkStorageAvailability();
+		} catch (StorageInvalidException $e) {
+			$this->storage->checkStorageAvailability();
+		} catch (StorageNotAvailable $e) {
```
Comment (LukasReschke) [inline apps/files_sharing/lib/external/scanner.php]: Mhm… Shouldn't that be `StorageNotAvailableException`?

**Comment by LukasReschke** [comment]
Guys, please when you review stuff please take a second to take a look at the errors pointed out by Scrutinizer. In this case it looks like 10 errors are false-positives (possibly bug in Scrutinizer) but https://github.com/owncloud/core/pull/13525#discussion_r23418126 is very much valid…

File: apps/files_sharing/ajax/external.php [hunk 4]
```diff
@@ -46,14 +46,39 @@
...
 	$storage = $mount->getStorage();
+	try {
+		// check if storage exists
+		$storage->checkStorageAvailability();
+	} catch (\OCP\Files\StorageInvalidException $e) {
+		// note: checkStorageAvailability will already remove the invalid share
+		\OCP\JSON::error(
+			array(
+				'data' => array(
+					'message' => $l->t("Could not authenticate to remote share, password might be wrong")
```
Comment (LukasReschke) [inline apps/files_sharing/ajax/external.php]: Single quotes when double quotes are not required.

File: apps/files_sharing/ajax/external.php [hunk 5]
```diff
@@ -46,14 +46,39 @@
...
+				)
+			)
+		);
+		exit();
+	} catch (\Exception $e) {
+		$externalManager->removeShare($mount->getMountPoint());
+		\OCP\JSON::error(array('data' => array('message' => $l->t("Storage not valid"))));
```
Comment (LukasReschke) [inline apps/files_sharing/ajax/external.php]: Single quotes when double quotes are not required.

File: apps/files_sharing/ajax/external.php [hunk 6]
```diff
@@ -46,14 +46,39 @@
...
+	}
 	$result = $storage->file_exists('');
 	if ($result) {
-		$storage->getScanner()->scanAll();
-		\OCP\JSON::success();
+		try {
+			$storage->getScanner()->scanAll();
+			\OCP\JSON::success();
+		} catch (\OCP\Files\StorageInvalidException $e) {
+			\OCP\JSON::error(array('data' => array('message' => $l->t("Storage not valid"))));
```
Comment (LukasReschke) [inline apps/files_sharing/ajax/external.php]: Single quotes when double quotes are not required.

File: apps/files_sharing/ajax/external.php [hunk 7]
```diff
@@ -46,14 +46,39 @@
...
+		} catch (\Exception $e) {
+			\OCP\JSON::error(array('data' => array('message' => $l->t("Couldn't add remote share"))));
```
Comment (LukasReschke) [inline apps/files_sharing/ajax/external.php]: Single quotes when double quotes are not required.

Comment (LukasReschke) [inline apps/files_sharing/ajax/external.php]: Maybe it would make sense as well to log the error somewhere?

File: apps/files_sharing/lib/external/scanner.php [hunk 8]
```diff
@@ -18,12 +23,42 @@ public function scan($path, $recursive = self::SCAN_RECURSIVE, $reuse = -1) {
...
+			);
+		}
 		if ($data['status'] === 'success') {
 			$this->addResult($data['data'], '');
 		} else {
-			throw new \Exception('Error while scanning remote share');
+			throw new \Exception(
+				'Error while scanning remote share: "' .
+				$this->storage->getRemote() . '" ' .
+				$e->getMessage()
```
Comment (LukasReschke) [inline apps/files_sharing/lib/external/scanner.php]: Where is `$e` defined?

Comment (LukasReschke) [inline apps/files_sharing/lib/external/scanner.php]: Proper IDE setup helps:

screen shot 2015-01-23 at 00 02 38

File: apps/files_sharing/lib/external/storage.php [hunk 9]
```diff
@@ -142,27 +142,47 @@ public function hasUpdated($path, $time) {
...
+			if ($this->testRemote()) {
+				// valid ownCloud instance means that the public share no longer exists
+				// since this is permanent (re-sharing the file will create a new token)
+				// we remove the invalid storage
+				$this->manager->removeShare($this->mountPoint);
+				$this->manager->getMountManager()->removeMount($this->mountPoint);
+				throw new StorageInvalidException();
+			} else {
+				// ownCloud instance is gone, likely to be a temporary server configuration error
 				throw $e;
```
Comment (LukasReschke) [inline apps/files_sharing/lib/external/storage.php]: screen shot 2015-01-23 at 00 04 52

File: lib/private/files/storage/dav.php [hunk 10]
```diff
@@ -529,8 +548,27 @@ public function hasUpdated($path, $time) {
...
+	 * Convert sabre DAV exception to a storage exception,
+	 * then throw it
+	 *
+	 * @param \Sabre\Dav\Exception $e sabre exception
+	 * @throws StorageInvalidException if the storage is invalid, for example
+	 * when the authentication expired or is invalid
+	 * @throws StorageNotAvailableException if the storage is not available,
+	 * which might be temporary
+	 */
+	private function convertSabreException(\Sabre\Dav\Exception $e) {
```
Comment (LukasReschke) [inline lib/private/files/storage/dav.php]: Add some unit tests for this? You can use `\Test_Helper::invokePrivate` for that.

File: lib/private/files/view.php [hunk 11]
```diff
@@ -1037,7 +1037,17 @@ public function getDirectoryContent($directory, $mimetype_filter = '') {
...
-						$subScanner->scanFile('');
+						try {
+							$subScanner->scanFile('');
+						} catch (\OCP\Files\StorageNotAvailableException $e) {
+							continue;
+						} catch (\OCP\Files\StorageInvalidException $e) {
+							continue;
+						} catch (\Exception $e) {
+							// sometimes when the storage is not available it can be any exception
+							\OC_Log::write('core', 'Exception while scanning storage "' . $subStorage->getId() . '": ' . $e->getMessage(), \OC_Log::ERROR);
```
Comment (LukasReschke) [inline lib/private/files/view.php]: screen shot 2015-01-23 at 00 08 34

**Comment by LukasReschke** [comment]
:-1: requires some adjustments. – Didn't test functionality. Pure code review.

File: apps/files_sharing/lib/external/scanner.php [hunk 12]
```diff
@@ -18,12 +23,42 @@ public function scan($path, $recursive = self::SCAN_RECURSIVE, $reuse = -1) {
 		$this->scanAll();
 	}
 
+	public function scanFile($path, $reuseExisting = 0) {
```
Comment (LukasReschke) [inline apps/files_sharing/lib/external/scanner.php]: PHPDoc please

File: apps/files_sharing/lib/external/scanner.php [hunk 13]
```diff
@@ -18,12 +23,42 @@ public function scan($path, $recursive = self::SCAN_RECURSIVE, $reuse = -1) {
...
+			// if appropriate
+			$this->storage->checkStorageAvailability();
+		} catch (StorageInvalidException $e) {
+			$this->storage->checkStorageAvailability();
+		} catch (StorageNotAvailable $e) {
+			$this->storage->checkStorageAvailability();
+		}
+	}
+
 	public function scanAll() {
```
Comment (LukasReschke) [inline apps/files_sharing/lib/external/scanner.php]: When already touching this please add PHPDoc as well

File: apps/files_sharing/ajax/external.php (hunk 4 above)
Comment (PVince81) [inline apps/files_sharing/ajax/external.php]: Was a copy paste :frowning:

File: apps/files_sharing/ajax/external.php (hunk 7 above)
Comment (nickvergessen) [inline apps/files_sharing/ajax/external.php]: Would have to use the utf8 ´ then, or escape the single quote

**Comment by PVince81** [comment]
Fixes, please re-review.

**Comment by PVince81** [comment]
I'll make another Jenkins PR

**Comment by derkostka** [comment]
I re-tested your changes. OSX Client also works fine for me (did some up/downloads yesterday using txt files and also zip archives). :+1:

**Comment by PVince81** [comment]
Thanks a lot @derkostka for your help all along :smile: 

Jenkins PR here: https://github.com/owncloud/core/pull/13664

**Comment by PVince81** [comment]
Tests passed, merge ?

File: apps/files_sharing/ajax/external.php [hunk 14]
```diff
@@ -42,20 +42,71 @@
...
+		\OCP\JSON::error(
+			array(
+				'data' => array(
+					'message' => $l->t('Could not authenticate to remote share, password might be wrong')
+				)
+			)
+		);
+		exit();
+	} catch (\Exception $e) {
+		throw new StorageNotAvailableException(get_class($e).": ".$e->getMessage());
```
Comment (nickvergessen) [inline apps/files_sharing/ajax/external.php]: missing the `\` ?

File: apps/files_sharing/ajax/external.php [hunk 15]
```diff
@@ -42,20 +42,71 @@
...
+		\OCP\Util::writeLog(
```
Comment (nickvergessen) [inline apps/files_sharing/ajax/external.php]: Log is never written

Comment (nickvergessen) [inline apps/files_sharing/ajax/external.php]: unreachable

File: apps/files_sharing/ajax/external.php (hunk 14 above)
Comment (nickvergessen) [inline apps/files_sharing/ajax/external.php]: This should be `\OCP\Files\StorageNotAvailableException`

So if tests pass, it seems to miss a test case ;)

Comment (PVince81) [inline apps/files_sharing/ajax/external.php]: There are no unit tests for that :frowning:

Comment (nickvergessen) [inline apps/files_sharing/ajax/external.php]: Well see the image below, some IDEs report that the class does not exist ;)

File: apps/files_sharing/ajax/external.php [hunk 16]
```diff
@@ -42,20 +42,71 @@
...
+			'files_sharing',
+			'Invalid remote storage: ' . get_class($e) . ': ' . $e->getMessage(),
+			\OCP\Util::DEBUG
+		);
+		$externalManager->removeShare($mount->getMountPoint());
+		\OCP\JSON::error(array('data' => array('message' => $l->t('Storage not valid'))));
+		exit();
```
Comment (nickvergessen) [inline apps/files_sharing/ajax/external.php]: since the `throw` above, everything afterwards can be removed

File: lib/private/files/view.php [hunk 17]
```diff
@@ -1037,7 +1037,22 @@ public function getDirectoryContent($directory, $mimetype_filter = '') {
...
+							continue;
+						} catch (\OCP\Files\StorageInvalidException $e) {
+							continue;
+						} catch (\Exception $e) {
+							// sometimes when the storage is not available it can be any exception
+							\OCP\Util::writeLog(
+								'core',
+								'Exception while scanning storage "' . $subStorage->getId() . '": ' .
+								get_class($e) . ': ' . $e->getMessage(),
+								\OC_Log::ERROR
```
Comment (nickvergessen) [inline lib/private/files/view.php]: `\OCP\Util::ERROR`

**Comment by nickvergessen** [comment]
Looks good, apart from:
- [ ] broken exception name
- [ ] unreachable code
- [ ] use of deprecated OC_Log

poke again when fixed, for a +1

**Comment by PVince81** [comment]
- [ ] try adding unit tests, at least it would get these various code paths covered

**Comment by PVince81** [comment]
@nickvergessen please have another look. Thanks.

I'll retrigger Jenkins separately.

File: apps/files_sharing/ajax/external.php [hunk 18]
```diff
@@ -42,20 +42,70 @@
...
+	} catch (\Exception $e) {
+		\OCP\Util::writeLog(
+			'files_sharing',
+			'Invalid remote storage: ' . get_class($e) . ': ' . $e->getMessage(),
+			\OCP\Util::DEBUG
+		);
+		$externalManager->removeShare($mount->getMountPoint());
+		\OCP\JSON::error(array('data' => array('message' => $l->t('Storage not valid'))));
+		throw new \OCP\Files\StorageNotAvailableException(get_class($e).': '.$e->getMessage());
```
Comment (nickvergessen) [inline apps/files_sharing/ajax/external.php]: magicians need to tell me whether outputting something + throwing an exception is the right thing to do.
the previous catch only does JSON::error() and then exits, which I think should be done here aswell.

Comment (PVince81) [inline apps/files_sharing/ajax/external.php]: I wasn't sure either. I thought that this file might be called somehow from base.php so throwing the exception will... hmmmm right, it will return an error page, which we don't want.

I'll add back `exit()`.

**Comment by LukasReschke** [comment]
:+1:

**Comment by PVince81** [comment]
@nickvergessen @MorrisJobke second review ? (there were a few fixes since last time)

**Comment by MorrisJobke** [comment]
testing ... ;)

**Comment by MorrisJobke** [comment]
Works :+1: (all files are synced now and work)

**Comment by MorrisJobke** [comment]
Jenkins PR #13675

**Comment by PVince81** [comment]
Another Jenkins PR, hopefully the last one: https://github.com/owncloud/core/pull/13714

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/core/pull/13714#issuecomment-71697160 <- success
