### PR TITLE
Fix reshare permission change to not impair other deletion code

### LINKED ISSUE #13445: OC8.0 beta - Shared folder is not removed from "shared with you" listing.
### Steps to reproduce
1. OC8.0.0-betta-1 clean install 
2. create 2 users A and B
3. User A shares own Documents folder to B as can edit but cannot delete
4. User B renames the folder to DocumentsfromA
5. User A unshare folder
6. User B see still DocumentsfromA in the "shared with you" 

### Expected behaviour
DocumentsfromA in the "shared with you" should wanish as well.

### Actual behaviour
User B see still DocumentsfromA in the "shared with you" 

### Server configuration
**Operating system**: Ubuntu 14.04LTS 

**Web server:** Apache/2.4.10 (Ubuntu)

**Database:** MySQL

**PHP version:** 5.5.20-1+deb.sury.org~trusty+1

**ownCloud version:** (see ownCloud admin page)
8.0.0 beta 1

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default 
**The content of config/config.php:**
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'oc80.aip.de',
  ),
  'datadirectory' => '/var/www/testoc/oc80/owncloud/data',
  'overwrite.cli.url' => 'http://oc80.aip.de',
  'dbtype' => 'mysql',
  'version' => '8.0.0.1',
  'dbname' => 'oc80',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc80',
  'dbpassword' => 'xxxxxxx',
  'installed' => true,
   'asset-pipeline.enabled' => true,
);
```
Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

### Client configuration
**Browser:** FF34.x

**Operating system:**
Ubuntu LTS14.01

#### ownCloud log (data/owncloud.log)
Error 	files_sharing 	No owner found for reshare 	2015-01-18T18:07:58+00:00
Error 	files_sharing 	No owner found for reshare 	2015-01-18T18:07:58+00:00
Error	files_sharing	No owner found for reshare	2015-01-18T18:07:39+00:00
Error	files_sharing	No owner found for reshare	2015-01-18T18:07:39+00:00
Error	files_sharing	No owner found for reshare	2015-01-18T18:07:39+00:00
Error	files_sharing	No owner found for reshare

### PR DESCRIPTION
**Pull request by PVince81**
A recent change that prevents reshare permission changes to delete group
share children had the side-effect of also preventing group share
children deletion when it needed to be done.

This fix adds an extra flag to isolate the "reshare permission change"
deletion case and keep the other ones as they were before, not only to
fix the regression but also fix other potential regressions in code that
uses this method.

Also updated the comment because now Helper::delete() is no longer
limited to reshares but also applies to group share children.

Fixes https://github.com/owncloud/core/issues/13445

Please review @schiesbn @icewind1991 @DeepDiver1975 @MorrisJobke

### CODE REVIEW

**Comment by icewind1991** [comment]
Looks good

File: lib/private/share/helper.php [hunk 1]
```diff
@@ -79,13 +79,14 @@ public static function generateTarget($itemType, $itemSource, $shareType, $share
 	}
 
 	/**
-	 * Delete all reshares of an item
+	 * Delete all reshares and group share children of an item
 	 * @param int $parent Id of item to delete
 	 * @param bool $excludeParent If true, exclude the parent from the delete (optional)
 	 * @param string $uidOwner The user that the parent was shared with (optional)
 	 * @param int $newParent new parent for the childrens
+	 * @param bool $excludeGroupChildre exclude group children elements
```
Comment (PeterPablo) [inline lib/private/share/helper.php]: This should read `$excludeGroupChildren` (missing `n`).

Comment (MorrisJobke) [inline lib/private/share/helper.php]: @PVince81 I fixed this no brainer ;)

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please
