### PR TITLE
Accept to ocm group 2

### LINKED ISSUE #40530: OCM sharing to groups not supported?
### Steps to reproduce
1. create a regular group or a custom group called 'mygroup' on server2.com
2. log in to server1.com
3. click a file and go to Share ...
4. type "mygroup@server2.com" as the recipient

### Expected behaviour
As described in [the OCM spec](https://cs3org.github.io/OCM-API/docs.html?branch=develop&repo=OCM-API&user=cs3org) the `shareWith` of an OCM share can be a username or a group name.
### Actual behaviour
The sharing will fail with a "user 'mygroup' not found" error, thrown from [these line of code](https://github.com/owncloud/core/blob/08a63ec/apps/federatedfilesharing/lib/Controller/OcmController.php#L226-L230)

**ownCloud version:** (see ownCloud admin page)
lastest master

### PR DESCRIPTION
**Pull request by shokri-navid**
## Description

 These are the hooks we need in the core repo to allow the [FederatedGroups app](https://github.com/SURFnet/rd-sram-integration/tree/main/federatedgroups) to deal with outgoing and incoming OCM shares to group.
 ## Related Issue
* Fixes [OCM sharing to groups not supported? #40530](https://github.com/owncloud/core/issues/40530)

 ## Motivation and Context
 ## How Has This Been Tested?
* test environment:
* test case 1:
* test case 2:
* ...

 ## Screenshots (if appropriate):
 ## Types of changes

* [ ]  Bug fix (non-breaking change which fixes an issue)
* [ ]  New feature (non-breaking change which adds functionality)
* [ ]  Database schema changes (next release will require increase of minor version instead of patch)
* [ ]  Breaking change (fix or feature that would cause existing functionality to change)
* [ ]  Technical debt
* [ ]  Tests only (no source changes)

 ## Checklist:
* [ ]  Code changes
* [ ]  Unit tests added
* [ ]  Acceptance tests added
* [ ]  Documentation ticket raised:
* [ ]  Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
Who is reviewing this PR?
What release is it likely to be done for?
How do we proceed?
@pako81 maybe you know what happens next?

**Comment by pako81** [comment]
Let's still target master here and try to get it in 10.13. @jvillafanez can you maybe review this as apparently you already had look at this?

File: apps/files_sharing/lib/Controllers/ExternalSharesController.php [hunk 1]
```diff
@@ -131,11 +151,30 @@ public function destroy($id) {
 				]
 			);
 			$this->dispatcher->dispatch($event, 'remoteshare.declined');
-			$this->externalManager->declineShare($id);
+			$manager->declineShare($id);
 		}
 		return new JSONResponse();
 	}
 
+	private function initGroupManager() {
```
Comment (jvillafanez) [inline apps/files_sharing/lib/Controllers/ExternalSharesController.php:159]: we probably should rename this function. There is a "groupManager" which is widely used (https://github.com/owncloud/core/blob/master/lib/public/IGroupManager.php) so it might be confusing.

**Review by jvillafanez — APPROVED** [review]
just a tiny change from my side, but I think it's ok.
I can't test it, so I assume it works as intended.

**Comment by pako81** [comment]
@shokri-navid @michielbdejong please see above and address the change request if possible.

**Comment by pako81** [comment]
@shokri-navid @michielbdejong if this is needed for 10.13 then it would need to be merged till end of this week. We want to have 10.13 code freeze after that.

File: apps/files_sharing/lib/Controllers/ExternalSharesController.php (hunk 1 above)
Comment (MahdiBaghbani) [reply apps/files_sharing/lib/Controllers/ExternalSharesController.php]: @jvillafanez Hi, I've changed the name a bit to "initGroupExternalManager", it should not be confused with simple "groupManager" anymore since it explicitly declares it is external.

If it still counts as confusing name, let me know.

**Comment by MahdiBaghbani** [comment]
@pako81 @jvillafanez Hi, would you look at the change and see if this is good to merge?

**Comment by jvillafanez** [comment]
good to merge from my side

**Review by phil-davis — APPROVED** [review]

**Review by pako81 — APPROVED** [review]
