### PR TITLE
Fix importing of certificates

### LINKED ISSUE #19601: Importing certificates does not work
```
{"reqId":"VhO3DcCoASUAADxifVoAAAAC","remoteAddr":"::1","app":"PHP","message":"Call to undefined method OCA\\Files_External\\Service\\BackendService::getBackendsVisibleFor() at \/Users\/lukasreschke\/Documents\/Programming\/master\/settings\/controller\/certificatecontroller.php#126","level":3,"time":"2015-10-06T11:57:01+00:00"}
```

Regression of https://github.com/owncloud/core/pull/19139 as far I can tell

### PR DESCRIPTION
**Pull request by LukasReschke**
Fixes https://github.com/owncloud/core/issues/19601

@MorrisJobke @Xenopathic THX

### CODE REVIEW

File: settings/controller/certificatecontroller.php [hunk 1]
```diff
@@ -122,8 +122,9 @@ public function removePersonalRootCertificate($certificateIdentifier) {
 	protected function isCertificateImportAllowed() {
 		$externalStorageEnabled = $this->appManager->isEnabledForUser('files_external');
 		if ($externalStorageEnabled) {
-			$backendService = \OC_Mount_Config::$app->getContainer()->query('OCA\Files_External\Service\BackendService');
-			if ($backendService->getBackendsVisibleFor(\OCA\Files_External\Service\BackendService::VISIBILITY_PERSONAL)) {
+			/** @var \OCA\Files_External\Service\BackendService $backendService */
+			$backendService = \OC_Mount_Config::$app->getContainer()->query('\OCA\Files_External\Service\BackendService');
+			if ($backendService->isUserMountingAllowed()) {
```
Comment (LukasReschke) [inline settings/controller/certificatecontroller.php]: Seems not to be `false` if mounting is not possible. Mhm…

**Comment by karlitschek** [comment]
good :+1:

File: settings/personal.php [hunk 2]
```diff
@@ -119,7 +119,9 @@
 $enableCertImport = false;
 $externalStorageEnabled = \OC::$server->getAppManager()->isEnabledForUser('files_external');
 if ($externalStorageEnabled) {
-	$enableCertImport = true;
+	/** @var \OCA\Files_External\Service\BackendService $backendService */
+	$backendService = \OC_Mount_Config::$app->getContainer()->query('\OCA\Files_External\Service\BackendService');
+	$enableCertImport = $backendService->isUserMountingAllowed();
```
Comment (LukasReschke) [inline settings/personal.php]: @schiesbn This will now only show the import if external storage mount by users are allowed. - Previously already if the files_external app is enabled.

I guess you don't have any problems with that?

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by icewind1991** [comment]
tested, looks good :+1:

File: settings/personal.php (hunk 2 above)
Comment (schiesbn) [inline settings/personal.php]: sounds reasonable. Beside the fact that it makes it harder to add additional certificates for server2server sharing (https://github.com/owncloud/core/issues/19370#issuecomment-145818272). But it doesn't make a huge difference.

**Comment by schiesbn** [comment]
works and code looks good :+1:

**Comment by PVince81** [comment]
:+1:
