### PR TITLE
Remove whitespace from base-DNs

### LINKED ISSUE #17964: LDAP: when sanitizing, also trim dn
It may happen that when configuring an LDAP connection, by accident a white space is added to the base DN. This will result in not working LDAP logins, because the check on whether the user belongs to a configured base DN will fail, as the user will not have that whitespace.

### PR DESCRIPTION
**Pull request by Takuto88**
Fixes #17964. 

I've tried to implement trimming in `Connection::doCriticalValidation()` as hinted in the issue. However, this does not work that way. Everything that is changed during that method call is somehow being reset to its original value afterwards. I am not sure why that is. As far as my understanding of the code goes, this should not happen.

Because of this, I've opted to implement trim when saving these specific config values in `Configuration::setConfiguration()` which works reliably for me. 

cc @blizzz: Please review. Thanks

### CODE REVIEW

File: apps/user_ldap/lib/configuration.php [hunk 1]
```diff
@@ -146,6 +146,7 @@ public function setConfiguration($config, &$applied = null) {
 			}
 
 			$setMethod = 'setValue';
+            $trim = false;
```
Comment (DeepDiver1975) [inline apps/user_ldap/lib/configuration.php]: indentation

File: apps/user_ldap/lib/configuration.php [hunk 2]
```diff
@@ -155,6 +156,7 @@ public function setConfiguration($config, &$applied = null) {
 				case 'ldapBase':
 				case 'ldapBaseUsers':
 				case 'ldapBaseGroups':
+                    $trim = true;// Prevent login errors due to whitespace
```
Comment (DeepDiver1975) [inline apps/user_ldap/lib/configuration.php]: indentation

File: apps/user_ldap/lib/configuration.php [hunk 3]
```diff
@@ -276,14 +278,18 @@ protected function getMultiLine($varName) {
...
-	protected function setMultiLine($varName, $value) {
+	protected function setMultiLine($varName, $value, $trim = false) {
 		if(empty($value)) {
 			$value = '';
 		} else if (!is_array($value)) {
 			$value = preg_split('/\r\n|\r|\n|;/', $value);
 			if($value === false) {
 				$value = '';
-			}
+			} else if($trim) {
```
Comment (DeepDiver1975) [inline apps/user_ldap/lib/configuration.php]: indentation

**Comment by DeepDiver1975** [comment]
@blizzz

File: apps/user_ldap/lib/configuration.php [hunk 4]
```diff
@@ -276,14 +278,18 @@ protected function getMultiLine($varName) {
 	 * @param string $varName
 	 * @param array|string $value
 	 */
-	protected function setMultiLine($varName, $value) {
+	protected function setMultiLine($varName, $value, $trim = false) {
```
Comment (LukasReschke) [inline apps/user_ldap/lib/configuration.php]: Please adjust PHPDoc

File: apps/user_ldap/lib/configuration.php [hunk 5]
```diff
@@ -329,11 +335,11 @@ protected function getValue($varName) {
 	}
 
 	/**
-	 * @param string $varName
+	 * @param string $varName
```
Comment (LukasReschke) [inline apps/user_ldap/lib/configuration.php]: Uneeded space?

File: apps/user_ldap/lib/configuration.php [hunk 6]
```diff
@@ -329,11 +335,11 @@ protected function getValue($varName) {
 	}
 
 	/**
-	 * @param string $varName
+	 * @param string $varName 
 	 * @param mixed $value
 	 */
-	protected function setValue($varName, $value) {
-		$this->config[$varName] = $value;
+	protected function setValue($varName, $value, $trim = false) {
```
Comment (LukasReschke) [inline apps/user_ldap/lib/configuration.php]: Please adjust PHPDoc as well

**Comment by Takuto88** [comment]
Thanks for the feedback. I've updated the file accordingly. Also, the logic has been changed so that trim also works on non-array values on `Configuration::setMutliLine()` and non string values on `Configuration::setValue()` are ignored.

**Comment by LukasReschke** [comment]
Is it possible to add unit tests for these?

**Comment by blizzz** [comment]
Actually we can simplify it and work without the $trim parameter,  just trim all the string settings. Trimming is always safe, except for the password. For this we can check in setValue() (ugly) or introduce another where we don't do any manipulation to strings like setUnmodifiedValue() or setRawValue() and apply this method for the password. This could be called from within setMultiLine  as well to avoid an extra trim.

**Comment by blizzz** [comment]
@Takuto88 an update about https://github.com/owncloud/core/pull/18484#issuecomment-134169732?

**Comment by blizzz** [comment]
OK, I finished this as suggested in https://github.com/owncloud/core/pull/18484#issuecomment-134169732 and added unit tests for setting the configuration items.

@davitol @LukasReschke @MorrisJobke review and testing would be awesome

**Comment by MorrisJobke** [comment]
Tested and works :+1:

I rebased this on current master for easier testing.

**Comment by davitol** [comment]
:+1: WFM

**Comment by LukasReschke** [comment]
Potential regression: https://github.com/owncloud/core/issues/19793
