### PR TITLE
[Tests-Only] Handle expected failures or success for webui rerun

### LINKED ISSUE #37810: CI still fails even if a rerun of a UI test passes
PR #37785  added some new logic to keep track of acceptance test scenarios that fail, and report them all at the end.

But now if a UI test fails, and it is automatically rerun, and the rerun passes then the test pipeline still fails. For example:
https://drone.owncloud.com/owncloud/core/26336/105/15
```
--- Failed scenarios:

    /drone/src/tests/acceptance/features/webUICreateDelete/createFoldersEdgeCases.feature:53

35 scenarios (34 passed, 1 failed)
371 steps (367 passed, 1 failed, 3 skipped)
21m53.22s (25.35Mb)
webUI test run failed with exit status: 1
Rerun failed scenario: /drone/src/tests/acceptance/features/webUICreateDelete/createFoldersEdgeCases.feature:53
@webUI @insulated @disablePreviews
Feature: create folder
  As a user
  I want to create folders
  So that I can organise my data structure

  Background:                                                                              # /drone/src/tests/acceptance/features/webUICreateDelete/createFoldersEdgeCases.feature:7
    Given user "Alice" has been created with default attributes and without skeleton files # FeatureContext::userHasBeenCreatedWithDefaultAttributesAndWithoutSkeletonFiles()
    And user "Alice" has logged in using the webUI                                         # WebUILoginContext::theUserHasLoggedInUsingTheWebUI()
    And the user has browsed to the files page                                             # WebUIFilesContext::theUserBrowsesToTheFilesPage()

SCENARIO RESULT: (pass)
  @smokeTest @skipOnLDAP
  Scenario Outline: Create a sub-folder inside an existing folder with problematic name # /drone/src/tests/acceptance/features/webUICreateDelete/createFoldersEdgeCases.feature:43
    Given user "Alice" has created folder <folder>                                      # FeatureContext::userHasCreatedFolder()
    And the user has reloaded the current page of the webUI                             # WebUIGeneralContext::theUserReloadsTheCurrentPageOfTheWebUI()
    When the user opens folder <folder> using the webUI                                 # WebUIFilesContext::theUserOpensFolderNamedUsingTheWebUI()
    And the user creates a folder with the name "sub-folder" using the webUI            # WebUIFilesContext::theUserCreatesAFolderUsingTheWebUI()
    Then folder "sub-folder" should be listed on the webUI                              # WebUIFilesContext::fileFolderShouldBeListedOnTheWebUI()
    When the user reloads the current page of the webUI                                 # WebUIGeneralContext::theUserReloadsTheCurrentPageOfTheWebUI()
    Then folder "sub-folder" should be listed on the webUI                              # WebUIFilesContext::fileFolderShouldBeListedOnTheWebUI()

    Examples:
      | folder |
      | "0"    |

1 scenario (1 passed)
10 steps (10 passed)
0m34.81s (22.70Mb)
runsh: Total 35 scenarios (34 passed, 1 failed)
runsh: Exit code of main run: 0
runsh: Total unexpected failed scenarios throughout the test run:
webUICreateDelete/createFoldersEdgeCases.feature:53
runsh: There were no unexpected success.
make: *** [test-acceptance-webui] Error 1
Makefile:215: recipe for target 'test-acceptance-webui' failed
```

`tests/acceptance/run.sh` needs more logic so that it understands if all the rerun scenarios have actually passed.

### PR DESCRIPTION
**Pull request by kiranparajuli589**
## Related Issue
- Fixes https://github.com/owncloud/core/issues/37810

### CODE REVIEW

**Comment by kiranparajuli589** [comment]
So far I've done removing webui unexpected failed or passed scenarios from the array just before the re-run starts.

https://github.com/owncloud/core/blob/33c64ea3d56ec20e5d0cbc0f745ed2c04589b7f8/tests/acceptance/run.sh#L537

@phil-davis At this part of code, while rerun, so should we have to check for the unexpected failures or success again?

File: tests/acceptance/run.sh [hunk 1]
```diff
@@ -537,9 +538,16 @@ function run_behat_tests() {
 				${BEHAT} --colors --strict -c ${BEHAT_YML} -f junit -f pretty ${BEHAT_SUITE_OPTION} --tags ${BEHAT_FILTER_TAGS} ${FAILED_SCENARIO_PATH} -v  2>&1 | tee -a ${TEST_LOG_FILE}
 				BEHAT_EXIT_STATUS=${PIPESTATUS[0]}
 				if [ ${BEHAT_EXIT_STATUS} -ne 0 ]
+					# The scenario was not expected to fail but had failed and is present the
+					# unexpected_failures list. We've checked the scenario with a re-run and
+					# it passed. So it is needed to be removed from the unexpected_failures list
+					UNEXPECTED_FAILED_SCENARIOS=("${UNEXPECTED_FAILED_SCENARIOS[@]/$SUITE_SCENARIO}")
 				then
```
Comment (phil-davis) [inline tests/acceptance/run.sh:545]:
```suggestion
				if [ ${BEHAT_EXIT_STATUS} -eq 0 ]
				then
					# The scenario was not expected to fail but had failed and is present in the
					# unexpected_failures list. We've checked the scenario with a re-run and
					# it passed. So it can be removed from the unexpected_failures list
					UNEXPECTED_FAILED_SCENARIOS=("${UNEXPECTED_FAILED_SCENARIOS[@]/$SUITE_SCENARIO}")
				else
```

File: tests/acceptance/run.sh [hunk 2]
```diff
@@ -537,9 +538,16 @@ function run_behat_tests() {
...
 					echo "webUI test rerun failed with exit status: ${BEHAT_EXIT_STATUS}"
 					PASSED=false
+					# The scenario is not expected to fail but is failing also after the rerun.
+					# Since it is already reported in the unexpected_failures list, so no need
+					# to touch that again. Just continue.
```
Comment (phil-davis) [inline tests/acceptance/run.sh:550]:
```suggestion
					# The scenario is not expected to fail but is failing also after the rerun.
					# Since it is already reported in the unexpected_failures list, there is no need
					# to touch that again. Just continue.
```

**Review by phil-davis — COMMENTED** [review]
This is a good idea. I think it will work. I made suggestions to make the code valid.

**Comment by phil-davis** [comment]
Note: there are also various uses of `PASSED=false` and `PASSED=true` that are not actually used any more in this script. But it would be best to clean those up in a refactoring PR that comes after this one.

File: tests/acceptance/run.sh [hunk 3]
```diff
@@ -537,9 +538,16 @@ function run_behat_tests() {
 				${BEHAT} --colors --strict -c ${BEHAT_YML} -f junit -f pretty ${BEHAT_SUITE_OPTION} --tags ${BEHAT_FILTER_TAGS} ${FAILED_SCENARIO_PATH} -v  2>&1 | tee -a ${TEST_LOG_FILE}
 				BEHAT_EXIT_STATUS=${PIPESTATUS[0]}
 				if [ ${BEHAT_EXIT_STATUS} -ne 0 ]
+					# The scenario was not expected to fail but had failed and is present the
+					# unexpected_failures list. We've checked the scenario with a re-run and
+					# it passed. So it is needed to be removed from the unexpected_failures list
+					UNEXPECTED_FAILED_SCENARIOS=("${UNEXPECTED_FAILED_SCENARIOS[@]/$SUITE_SCENARIO}")
```
Comment (phil-davis) [inline tests/acceptance/run.sh:544]: IMO this just removes the string `$SUITE_SCENARIO` from the text of any element of the array. The array index is still there, and for example becomes the empty string.

If the scenario was `webUILogin/login.feature:11` then:

1) the entry in the array for that will become the empty string
2) an entry for `webUILogin/login.feature:117` will become just `7`

Item (1) means that the array will still have the same number of entries. The test at the end that checks that `UNEXPECTED_FAILED_SCENARIOS` array has 0 entries is going to fail.

Item (2) means that when you are unlucky, some other "random" scenario is going to get its name... chopped off.

You might have to use more code that copies `UNEXPECTED_FAILED_SCENARIOS`, loops through the copy, and creates a new `UNEXPECTED_FAILED_SCENARIOS` that has all except `SUITE_SCENARIO`

**Comment by kiranparajuli589** [comment]
Thank you @phil-davis for your nice suggestions. I've addressed your comments. Please review it again!

**Review by phil-davis — APPROVED** [review]
I squashed the commits.
This looks logical and readable (as much as bash array handling is readable :)
