### PR TITLE
Call final unlink in trash wrapper's storage

### LINKED ISSUE #13557: Delete file on non-local storage does not properly delete file
### Steps to reproduce
1. Mount a remote share through server to server sharing
2. Run cadaver for the receiving user
3. `cd remoteshare`
4. `put test.txt` (upload a file)
5. `rm test.txt`
6. `ls`

### Expected result
File is deleted

### Actual result
Even though the deletion call succeeded, the file is still there.

### Versions
OC 8 master ff5715779c56ceacc870307bf25f4e769ff22a1a

I'll have a look.

### PR DESCRIPTION
**Pull request by PVince81**
In the case of cross-storage delete, the files are copied to the trash,
then deleted. The final delete on the source storage would still reach
the trash wrapper.

This fix makes forwards that second call to the wrapped storage to make
the final delete work.

It fixes the issue with remote shares, local shares and external
storage.

Fixes https://github.com/owncloud/core/issues/13557

### CODE REVIEW

**Comment by PVince81** [comment]
@DeepDiver1975 @icewind1991 @schiesbn @MorrisJobke

**Comment by PVince81** [comment]
This is the final delete in question: https://github.com/owncloud/core/blob/master/lib/private/files/view.php#L529

In @icewind1991's cross-storage PR, it would still happen here: https://github.com/owncloud/core/pull/13360/files#diff-43d02ea7c0da1686b8ca6e343392cff1R493

**Comment by PVince81** [comment]
- [ ] add unit test

**Comment by icewind1991** [comment]
makes sense :+1:

**Comment by PVince81** [comment]
- [ ] check/fix the relevant failing unit tests

**Comment by PVince81** [comment]
@schiesbn it looks like the versioning code is running after file deletion, but still tries to operate on the non-deleted file. Possibly something wrong with the running order.

**Comment by schiesbn** [comment]
Versioning listening to a pre- and post-delete hook. The post delete hook who actually deletes the versions shouldn't try to operate on the deleted file but use the information collected in the pre-hook

**Comment by PVince81** [comment]
Okay. I was just guessing. Will have a look later, struggling with the unit test for now.

**Comment by PVince81** [comment]
Added unit test for "single storage delete" and "cross storage delete" in 5c3cd71

There is still an issue: the deleted file lands in "files_trashbin/files/subtest.txt.d12345" instead of "files_trashbin/files/substorage/subtest.txt.d12345". Need to look into it.

@icewind1991 I hope that my way of setting up the FS is acceptable

**Comment by PVince81** [comment]
- [ ] properly cleanup homes + delete test user in tearDown

**Comment by PVince81** [comment]
I debugged a bit and it looks like during the "trashbin" test run, the storage was wrapped multiple times by the storage wrapper:
```
/srv/www/htdocs/owncloud/lib/private/files/storage/local.php:138
/srv/www/htdocs/owncloud/lib/private/files/storage/wrapper/wrapper.php:202
/srv/www/htdocs/owncloud/apps/files_sharing/lib/sharedstorage.php:235
/srv/www/htdocs/owncloud/apps/files_sharing/lib/sharedstorage.php:490
/srv/www/htdocs/owncloud/lib/private/files/storage/wrapper/wrapper.php:357
/srv/www/htdocs/owncloud/lib/private/files/storage/wrapper/wrapper.php:357
/srv/www/htdocs/owncloud/lib/private/files/cache/watcher.php:67
/srv/www/htdocs/owncloud/apps/files_sharing/lib/watcher.php:37
/srv/www/htdocs/owncloud/lib/private/files/view.php:932
/srv/www/htdocs/owncloud/lib/private/files/filesystem.php:782
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/trashbin.php:39
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/trashbin.php:232
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/trashbin.php:190
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/storage.php:48
/srv/www/htdocs/owncloud/apps/files_sharing/lib/sharedstorage.php:285
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/storage.php:58
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/storage.php:58
/srv/www/htdocs/owncloud/lib/private/files/view.php:529
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/trashbin.php:170
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/storage.php:48
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/storage.php:58
/srv/www/htdocs/owncloud/lib/private/files/view.php:529
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/trashbin.php:170
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/storage.php:48
/srv/www/htdocs/owncloud/lib/private/files/view.php:792
/srv/www/htdocs/owncloud/lib/private/files/view.php:437
/srv/www/htdocs/owncloud/lib/private/files/filesystem.php:642
/srv/www/htdocs/owncloud/apps/files_trashbin/tests/trashbin.php:209
```

**Comment by PVince81** [comment]
Hmm probably not, I tried cleaning up the storage wrappers after the tests and it still happens.

Need to understand what is happening exactly.

**Comment by PVince81** [comment]
At this point:
```
0  OCA\Files_Trashbin\Storage->unlink() /srv/www/htdocs/owncloud/apps/files_trashbin/lib/storage.php:41
1  OC\Files\View->basicOperation() /srv/www/htdocs/owncloud/lib/private/files/view.php:792
2  OC\Files\View->unlink() /srv/www/htdocs/owncloud/lib/private/files/view.php:437
3  OC\Files\Filesystem::unlink() /srv/www/htdocs/owncloud/lib/private/files/filesystem.php:652
4  Test_Trashbin->testExpireOldFilesShared() /srv/www/htdocs/owncloud/apps/files_trashbin/tests/trashbin.php:211
5  ReflectionMethod->invokeArgs() /home/vincent/.composer/vendor/phpunit/phpunit/src/Framework/TestCase.php:905
6  PHPUnit_Framework_TestCase->runTest() /home/vincent/.composer/vendor/phpunit/phpunit/src/Framework/TestCase.php:905
7  PHPUnit_Framework_TestCase->runBare() /home/vincent/.composer/vendor/phpunit/phpunit/src/Framework/TestCase.php:775
8  PHPUnit_Framework_TestResult->run() /home/vincent/.composer/vendor/phpunit/phpunit/src/Framework/TestResult.php:643
9  PHPUnit_Framework_TestCase->run() /home/vincent/.composer/vendor/phpunit/phpunit/src/Framework/TestCase.php:711
10 PHPUnit_Framework_TestSuite->run() /home/vincent/.composer/vendor/phpunit/phpunit/src/Framework/TestSuite.php:751
11 PHPUnit_TextUI_TestRunner->doRun() /home/vincent/.composer/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:423
12 PHPUnit_TextUI_Command->run() /home/vincent/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:186
13 PHPUnit_TextUI_Command::main() /home/vincent/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:138
14 {main}          /home/vincent/.composer/vendor/phpunit/phpunit/phpunit:56
```

The wrapper evaluates as follows:
```
$this                            = (object|OCA\Files_Trashbin\Storage[3]);
  $this->mountPoint              = (string[48]) '/test-trashbin-user2/files/trashTest-1421874853/';
  $this->deletedFiles            = (array[0]);
  $this->storage                 = (object|OCA\Files_Trashbin\Storage[3]);
    $this->storage->mountPoint   = (string[48]) '/test-trashbin-user2/files/trashTest-1421874853/';
    $this->storage->deletedFiles = (array[0]);
    $this->storage->storage      = (object|OC\Files\Storage\Shared[8]);
      $this->storage->storage->share = (array[19])+;
      $this->storage->storage->files = (array[1])+;
      $this->storage->storage->cache = (null);
      $this->storage->storage->scanner = (null);
      $this->storage->storage->permissioncache = (null);
      $this->storage->storage->watcher = (null);
      $this->storage->storage->storageCache = (null);
      $this->storage->storage->cachedFiles = (array[0]);
```

The wrapper does seem to be added twice. The trouble with this is that `deletedFiles[]` is not static. So calling `unlink()` on the second level wrapper will call `move2trash()` again and restarting a similar loop.

**Comment by PVince81** [comment]
@icewind1991 if I change setupStorage to this:
```php
	public static function setupStorage() {
		\OC\Files\Filesystem::addStorageWrapper(
			'oc_trashbin',
		   	function ($mountPoint, $storage) {
				if ($storage->instanceOfStorage('\OCA\Files_Trashbin\Storage')) {
					// do not wrap twice!
					return $storage;
				}
				return new \OCA\Files_Trashbin\Storage(array('storage' => $storage, 'mountPoint' => $mountPoint));
			}
		);
	}
```

I do see that the wrapper is set twice. Maybe a side-effect of calling setUpFS multiple times.
Maybe we should fix addStorageWrapper() to not re-wrap if the wrapper was already registered.
I raised https://github.com/owncloud/core/pull/13577 to discuss this general issue.

**Comment by PVince81** [comment]
- [ ] solve duplicate wrapping issue: https://github.com/owncloud/core/pull/13577

Note: even if the solution from that PR the tests are failing for other reasons. Will look into that tomorrow.

**Comment by PVince81** [comment]
@icewind1991 if the fix to avoid duplicate is too intrusive, we can minimize the risk by adding the check only in the trashbin storage wrapper and have the proper fix go to 8.1

**Comment by PVince81** [comment]
@schiesbn I assume it is expected that a shared file deleted by a recipient will land in both the owner and the recipient's trashbin. (this is what seems to happen here)

**Comment by PVince81** [comment]
If this cannot be fixed by the end of the week I suggest to revert the trashbin storage wrapper changes. Even if I manage to fix this, I have the feeling we will likely find other side effects / regressions later.

While the trashbin storage might improve performance, I could have spent this time to fix other more important bugs/regressions (like s2s sharing) and the trashbin deletion performance could have waited for 8.1.

**Comment by PVince81** [comment]
I pushed the changes from https://github.com/owncloud/core/pull/13577 here as they are needed.

**Comment by PVince81** [comment]
The versions app still doesn't find the original file because it was deleted already:
```
1) Test_Trashbin::testExpireOldFilesShared
filemtime(): stat failed for /dev/shm/data-autotest/test-trashbin-user1/files/trashTest-1421923445/user1-4.txt

/srv/www/htdocs/owncloud/lib/private/files/storage/local.php:138
/srv/www/htdocs/owncloud/lib/private/files/storage/wrapper/wrapper.php:202
/srv/www/htdocs/owncloud/apps/files_sharing/lib/sharedstorage.php:235
/srv/www/htdocs/owncloud/apps/files_sharing/lib/sharedstorage.php:490
/srv/www/htdocs/owncloud/lib/private/files/storage/wrapper/wrapper.php:357
/srv/www/htdocs/owncloud/lib/private/files/cache/watcher.php:67
/srv/www/htdocs/owncloud/apps/files_sharing/lib/watcher.php:37
/srv/www/htdocs/owncloud/lib/private/files/view.php:932
/srv/www/htdocs/owncloud/lib/private/files/filesystem.php:795
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/trashbin.php:39
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/trashbin.php:232
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/trashbin.php:190
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/storage.php:48
/srv/www/htdocs/owncloud/apps/files_sharing/lib/sharedstorage.php:285
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/storage.php:58
/srv/www/htdocs/owncloud/lib/private/files/view.php:529
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/trashbin.php:170
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/storage.php:48
/srv/www/htdocs/owncloud/lib/private/files/view.php:792
/srv/www/htdocs/owncloud/lib/private/files/view.php:437
/srv/www/htdocs/owncloud/lib/private/files/filesystem.php:655
/srv/www/htdocs/owncloud/apps/files_trashbin/tests/trashbin.php:209
```

It goes up to "retainStorageVersions" where it fails to find the file in `getUIDAndOwner()`:

0  OCA\Files_Trashbin\Trashbin::move2trash() /srv/www/htdocs/owncloud/apps/files_trashbin/lib/trashbin.php:190
1  OCA\Files_Trashbin\Storage->unlink() /srv/www/htdocs/owncloud/apps/files_trashbin/lib/storage.php:48
2  OC\Files\Storage\Shared->unlink() /srv/www/htdocs/owncloud/apps/files_sharing/lib/sharedstorage.php:285
3  OCA\Files_Trashbin\Storage->unlink() /srv/www/htdocs/owncloud/apps/files_trashbin/lib/storage.php:58
4  OC\Files\View->rename() /srv/www/htdocs/owncloud/lib/private/files/view.php:529
5  OCA\Files_Trashbin\Trashbin::move2trash() /srv/www/htdocs/owncloud/apps/files_trashbin/lib/trashbin.php:170
6  OCA\Files_Trashbin\Storage->unlink() /srv/www/htdocs/owncloud/apps/files_trashbin/lib/storage.php:48
7  OC\Files\View->basicOperation() /srv/www/htdocs/owncloud/lib/private/files/view.php:792
8  OC\Files\View->unlink() /srv/www/htdocs/owncloud/lib/private/files/view.php:437
9  OC\Files\Filesystem::unlink() /srv/www/htdocs/owncloud/lib/private/files/filesystem.php:655
10 Test_Trashbin->testExpireOldFilesShared() /srv/www/htdocs/owncloud/apps/files_trashbin/tests/trashbin.php:209
11 ReflectionMethod->invokeArgs() /home/vincent/.composer/vendor/phpunit/phpunit/src/Framework/TestCase.php:905
12 PHPUnit_Framework_TestCase->runTest() /home/vincent/.composer/vendor/phpunit/phpunit/src/Framework/TestCase.php:905
13 PHPUnit_Framework_TestCase->runBare() /home/vincent/.composer/vendor/phpunit/phpunit/src/Framework/TestCase.php:775
14 PHPUnit_Framework_TestResult->run() /home/vincent/.composer/vendor/phpunit/phpunit/src/Framework/TestResult.php:643
15 PHPUnit_Framework_TestCase->run() /home/vincent/.composer/vendor/phpunit/phpunit/src/Framework/TestCase.php:711
16 PHPUnit_Framework_TestSuite->run() /home/vincent/.composer/vendor/phpunit/phpunit/src/Framework/TestSuite.php:751
17 PHPUnit_TextUI_TestRunner->doRun() /home/vincent/.composer/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:423
18 PHPUnit_TextUI_Command->run() /home/vincent/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:186
19 PHPUnit_TextUI_Command::main() /home/vincent/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:138
20 {main}          /home/vincent/.composer/vendor/phpunit/phpunit/phpunit:56

**Comment by PVince81** [comment]
Workflow:
1) in tests/trashbin.php:209: unlink is called with "trashTest-1421923798/user1-4.txt"
2) The unlink operation goes up to the wrapper which called `move2trash()` with "trashTest-1421923798/user1-4.txt"
Wrapped storage is as follows:
```
$this                            = (object|OCA\Files_Trashbin\Storage[3]);
  $this->mountPoint              = (string[48]) '/test-trashbin-user2/files/trashTest-1421923798/';
  $this->deletedFiles            = (array[1])+;
  $this->storage                 = (object|OC\Files\Storage\Shared[8]);
```
3) move2trash calls `rename()` on '/files/trashTest-1421923798/user1-4.txt', '/files_trashbin/files/user1-4.txt.d1421923957'
4) after the stream copy, it calls $storage->unlink() with "user1-4.txt" on the source storage which is still wrapped (same as above)
5) `unlink()` finds that the files are already in `deletedFiles[]` so proceeds to the `else` block that calls `$this->storage->unlink()` on the wrapped storage which is a shared storage
6) The shared storage resolves to user1's storage and does `unlink()` there with 'files/trashTest-1421923798/user1-4.txt';
Here it is:
```
$this                            = (object|OCA\Files_Trashbin\Storage[3]);
  $this->mountPoint              = (string[21]) '/test-trashbin-user1/';
  $this->deletedFiles            = (array[0]);
  $this->storage                 = (object|OC\Files\Storage\Home[9]);
    $this->storage->id           = (string[25]) 'home::test-trashbin-user1';
    $this->storage->user         = (object|OC\User\User[8])+;
    $this->storage->datadir      = (string[43]) '/dev/shm/data-autotest/test-trashbin-user1/';
    $this->storage->cache        = (object|OC\Files\Cache\HomeCache[5])+;
    $this->storage->scanner      = (null);
    $this->storage->permissioncache = (null);
    $this->storage->watcher      = (null);
    $this->storage->storageCache = (null);
    $this->storage->cachedFiles  = (array[0]);
```
7) In this storage wrapper for user1, `deleteFiles[]` is still empty, so proceeds to call `move2trash()` again
8) `rename()` now called on '/files/trashTest-1421923798/user1-4.txt' and '/files_trashbin/files/user1-4.txt.d1421924203';
9) then again `$storage->unlink()` on "user1-4.txt", the one after delete
10) That one is intercepted by the wrapper from 6), "deletedFile[]" contains the file, so it proceeds to the underlying storage's unlink
11) That underlying storage happens to be a shared storage too, that resolves to this wrapper:
```
$this                            = (object|OCA\Files_Trashbin\Storage[3]);
  $this->mountPoint              = (string[21]) '/test-trashbin-user1/';
  $this->deletedFiles            = (array[1])+;
  $this->storage                 = (object|OC\Files\Storage\Home[9]);
    $this->storage->id           = (string[25]) 'home::test-trashbin-user1';
    $this->storage->user         = (object|OC\User\User[8])+;
    $this->storage->datadir      = (string[43]) '/dev/shm/data-autotest/test-trashbin-user1/';
    $this->storage->cache        = (object|OC\Files\Cache\HomeCache[5])+;
    $this->storage->scanner      = (null);
    $this->storage->permissioncache = (null);
    $this->storage->watcher      = (null);
    $this->storage->storageCache = (null);
    $this->storage->cachedFiles  = (array[0]);
```
WEIRD, this is the exact same wrapper. So the shared storage resolves back to the same wrapper.
12) Here `deletedFiles[]` already contains the file (same as 10)
13) So it calls unlink on the underlying storage, which is now the real storage: the source file is now gone! (same wrapper instance but different underlying storage ? weird)
14) Then it continues in the last move2trash() we had at 7)
15) The call of that inner move2trash tries and call `retainVersions()` with "trashTest-1421923798/user1-4.txt" and "user1-4.txt";
16) And that call calls `getUIDAndOwner()` which in turn calls `getFileInfo()` with "trashTest-1421923798/user1-4.txt"

but that file is already gone.

**Comment by DeepDiver1975** [comment]
> While the trashbin storage might improve performance, I could have spent this time to fix other more important bugs/regressions (like s2s sharing) and the trashbin deletion performance could have waited for 8.1.

FYI: in this special case fixing a performance issue means preventing data loss in conjunction with the sync client. As soon as webdav operations are running too long the client will get http timeouts which can result in data consistency hick ups. This is the only reason why such performance improvements got scheduled for 8.0

**Comment by PVince81** [comment]
Ok, understood. I missed that info in the PR.

I'll see what I can do to save this.

**Comment by PVince81** [comment]
I'm running through the stable7 workflow and it is as follows (for comparison):
1) test/trashbin.php:209 calls unlink() on the test file
2) pre-unlink hook calls "Trashbin\Hooks::remove_hook()" which itself calls "move2trash()"
3) "move2trash()" copies all files over to the trashbin with "copyRecursive"
4) Then it calls `retainVersions()`. At this time, the file **still exists** on the source storage.
5) Then it does `copyFilesToOwner()` (which seem to be done in a different way on master, but works nonetheless)
6) Then after the hook comes back, the regular "unlink()" operation is called on the storage (which goes through shared storage, etc) to delete the file

So on master this is definitely an issue with the order of operations.
The final `unlink` I put in this PR needs to happen much much later.

**Comment by PVince81** [comment]
@schiesbn `copy_recursive` used to use a `touch()` operation but seems to be missing in the new workflow on master and possibly affect expiration. Was this intended ?

**Comment by PVince81** [comment]
Ok I see. In the regular `rename()` case the file would keep its mtime.
But in the case of cross-storage rename which triggers a copy, the target file would have a new mtime.
I'll try and throw in a touch() there.

**Comment by PVince81** [comment]
Hmmmmmmmmm easier said than done... need to not only touch the source + path but do this recursively for all copied files. Basically the same as `copy_recursive`.
One idea would be to detect the cross-storage situation before doing `$view->rename` and falling back to the old `copy_recursive` instead of letting the view do the non mtime-preserving copy implicitly. But that will not be future compatible with @icewind1991's changes.

Or cache the mtime of all files to be deleted, and then reapply it to the file tree that was just copied to the trashbin.

**Comment by PVince81** [comment]
Next try: make a function "rename_recursive" that is like the old "copy_recursive" but uses rename instead. It will also incorporate the "touch" logic.

**Comment by PVince81** [comment]
Here we go, finally got all tests passing.

@icewind1991 @schiesbn please review and let me know if this solution is acceptable.

**Comment by PVince81** [comment]
Well if Jenkins fails anyway I took the opportunity to squash everything.
Here is the Jenkins PR: https://github.com/owncloud/core/pull/13605

**Comment by icewind1991** [comment]
Fine by me like this, once we have the improved cross storage move we should be able to use that and get a cleaner sollution

**Comment by PVince81** [comment]
Thanks.

I ran the sqlite tests locally and got this:
```
1) Test_Files_Sharing_Mount::testDeleteParentOfMountPoint
filesize(): stat failed for /dev/shm/data-autotest/test-share-user1/files/folder_share_storage_test/share-api-storage.txt

/srv/www/htdocs/owncloud/lib/private/files/storage/local.php:121
/srv/www/htdocs/owncloud/lib/private/files/storage/wrapper/wrapper.php:121
/srv/www/htdocs/owncloud/lib/private/files/view.php:792
/srv/www/htdocs/owncloud/lib/private/files/view.php:268
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/trashbin.php:827
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/trashbin.php:169
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/storage.php:48
/srv/www/htdocs/owncloud/lib/private/files/view.php:792
/srv/www/htdocs/owncloud/lib/private/files/view.php:437
/srv/www/htdocs/owncloud/apps/files_sharing/tests/sharedmount.php:134
```

I'll see what I can do.
After that: manual testing.

File: lib/private/files/storage/storagefactory.php [hunk 1]
```diff
@@ -23,9 +23,25 @@ class StorageFactory implements IStorageFactory {
 	 *
 	 * @param string $wrapperName
 	 * @param callable $callback
+	 * @return true if the wrapper was added, false if there was already a wrapper with this
```
Comment (LukasReschke) [inline lib/private/files/storage/storagefactory.php]: You are lying in terms of PHPDoc here. When you write it that way PHPDoc will say that the only return type is `true` as it can't do black magic to find out the real return type ;-)

Thus this should be `@return bool … your text …`

File: lib/private/files/storage/storagefactory.php [hunk 2]
```diff
@@ -23,9 +23,25 @@ class StorageFactory implements IStorageFactory {
...
+		if (isset($this->storageWrappers[$wrapperName])) {
+			return false;
+		}
 		$this->storageWrappers[$wrapperName] = $callback;
+		return true;
+	}
+
+	/**
+	 * Remove a storage wrapper by name.
+	 * Note: internal method only to be used for cleanup
```
Comment (LukasReschke) [inline lib/private/files/storage/storagefactory.php]: You can use `@internal` for that. Proper IDEs will display that properly.
http://www.phpdoc.org/docs/latest/references/phpdoc/tags/internal.html

File: lib/public/files/storage/istoragefactory.php [hunk 3]
```diff
@@ -19,6 +19,8 @@
 	 *
 	 * @param string $wrapperName
 	 * @param callable $callback
+	 * @return true if the wrapper was added, false if there was already a wrapper with this
```
Comment (LukasReschke) [inline lib/public/files/storage/istoragefactory.php]: Same as https://github.com/owncloud/core/pull/13561/files#r23419734

**Comment by PVince81** [comment]
Hmmm tests pass locally now... probably a race condition / time dependent condition

**Comment by PVince81** [comment]
Okay, happens only sometimes locally.

I believe the problem is that the trashbin storage wrapper isn't removed after the tests, so it will influence other tests. I'll compare with master.

**Comment by PVince81** [comment]
A new Jenkins PR is born: https://github.com/owncloud/core/pull/13623

**Comment by icewind1991** [comment]
- [] When deleting a file from a shared folder the file is added to the trashbin twice
- [] When deleting a folder from a shared folder, the content of the folder is added to the root of the trashbin (twice) and the folder created in the trashbin (twice) is empty

**Comment by icewind1991** [comment]
Regular (non shared) files and external storages seem to work fine

**Comment by PVince81** [comment]
@icewind1991 I saw that the file is added twice, but it's once for user1 and once for user2. Is that what you observed ? I believe that this is expected behavior. @schiesbn can you help clarify ?

**Comment by PVince81** [comment]
@icewind1991 I checked the behavior at commit d2d6472 (before the trashbin storage changes) and if you delete a file as recipient, it does land in both user's trashbin (owner too). So I think this is expected.

Since this question is popping up over and over again, I raised https://github.com/owncloud/documentation/issues/777 to add this to the documentation.

**Comment by PVince81** [comment]
Seems there's a second race condition on sqlite, but only happens on Jenkins:
```
06:35:48 1) Test_Trashbin::testExpireOldFilesShared
06:35:48 Failed asserting that 3 is identical to 2.
06:35:48 
06:35:48 /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/apps/files_trashbin/tests/trashbin.php:228
06:35:48 /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/apps/files_trashbin/tests/trashbin.php:214
```

fun times!

**Comment by icewind1991** [comment]
It was added twice to both the owner and the recipient (so 4 copies in total)

**Comment by icewind1991** [comment]
Problem seems to be caused by encryption

**Comment by icewind1991** [comment]
Fixed the duplicated (caused by the delete recursion by the shared storage) by only moving files from the current user to the trash.

**Comment by PVince81** [comment]
Updated Jenkins PR with the new commits: https://github.com/owncloud/core/pull/13623#commits-pushed-64ba352

**Comment by PVince81** [comment]
Getting this again on this branch:
```
1) Test_Files_Sharing_Mount::testDeleteParentOfMountPoint
filesize(): stat failed for /dev/shm/data-autotest/test-share-user1/files/folder_share_storage_test/share-api-storage.txt

/srv/www/htdocs/owncloud/lib/private/files/storage/local.php:121
/srv/www/htdocs/owncloud/lib/private/files/storage/wrapper/wrapper.php:121
/srv/www/htdocs/owncloud/lib/private/files/view.php:792
/srv/www/htdocs/owncloud/lib/private/files/view.php:268
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/trashbin.php:827
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/trashbin.php:169
/srv/www/htdocs/owncloud/apps/files_trashbin/lib/storage.php:48
/srv/www/htdocs/owncloud/lib/private/files/view.php:792
/srv/www/htdocs/owncloud/lib/private/files/view.php:437
/srv/www/htdocs/owncloud/apps/files_sharing/tests/sharedmount.php:134
```

Looks like I missed one location for `removeStorageWrappers()` https://github.com/owncloud/core/pull/13561/files#diff-b843ff63a67d2fdaef71de93ed89d480R96, will fix

**Comment by PVince81** [comment]
And now... same failure but on mysql 

Are you kidding me?

**Comment by PVince81** [comment]
I reviewed the additional commits from @icewind1991 and agree with the changes.

Will do some manual testing now (with encryption and ext storage enabled):
- [x] delete local file/folder: appears in trashbin, file correctly deleted on disk
- [x] delete shared file/folder as owner: only in owner's trashbin, file correctly deleted on disk
- [x] delete shared file/folder as recipient: appears in both owner and recipient's trashbin, file correctly deleted on disk
- [ ] delete file/folder from external storage, file/folder appears in trashbin of deleting user only and is correctly removed from ext storage
- [ ] unshare from self: no trashbin interaction
- [ ] unshare from others: no trashbin interaction
- [ ] versions are kept after restore in local/shared/ext cases

**Comment by PVince81** [comment]
Jenkins PR passed: https://github.com/owncloud/core/pull/13623

@schiesbn @DeepDiver1975 @nickvergessen @LukasReschke @MorrisJobke please review

File: apps/files_trashbin/tests/storage.php [hunk 4]
```diff
@@ -0,0 +1,102 @@
...
+	/**
+	 * @var \OC\Files\View
+	 */
+	private $userView;
+
+	protected function setUp() {
+		parent::setUp();
+
+		$this->user = $this->getUniqueId('user');
+		\OC_User::createUser($this->user, $this->user);
```
Comment (MorrisJobke) [inline apps/files_trashbin/tests/storage.php]: From scrutinizer:

The method `OC_User::createUser()` has been deprecated with message: Use `\OC::$server->getUserManager->createUser($uid, $password)`

**Comment by PVince81** [comment]
You can stop reviewing... we're not done with this wrapper.
I discovered this issue with versions: https://github.com/owncloud/core/issues/13634
This is also related to the trashbin storage wrapper.

This means that additional fixes are needed for versions, which also means complete retest of the trash wrapper will be needed.

I'll continue pushing to this branch.

**Comment by PVince81** [comment]
I added unit tests here https://github.com/owncloud/core/commit/a1cc9eea56a39646e679fd42b6a33249f9aad170 for the versions and also to reproduce the issue from https://github.com/owncloud/core/issues/13634 (test first approach)

If you comment out the `setupStorage()` row you'll notice that the test `testKeepFileAndVersionsWhenMovingBetweenStorages` passes (the other one fail, ignore them)

The problem is that the `$view->rename()` operation will trigger copy + unlink in a cross-storage situation. That "unlink()" call still goes through the wrapper and deletes the versions.

@icewind1991 @schiesbn I will continue working on this next week. Feel free to take over in the meantime if you like.

**Comment by PVince81** [comment]
@icewind1991 @schiesbn please have a look at my solution for the versions issue here: https://github.com/owncloud/core/commit/02b9bad81b51a37dd60cab34b80796c79390c426

File: lib/private/files/storage/storagefactory.php [hunk 5]
```diff
@@ -21,11 +21,35 @@ class StorageFactory implements IStorageFactory {
...
+	 *
+	 * @param string $wrapperName name of the wrapper
+	 * @internal
+	 */
+	public function removeStorageWrapper($wrapperName) {
```
Comment (nickvergessen) [inline lib/private/files/storage/storagefactory.php]: Missing from the interface, is that intentional?

Comment (PVince81) [inline lib/private/files/storage/storagefactory.php]: Yes, tagged as "internal" for that purpose.

**Comment by icewind1991** [comment]
> @icewind1991 @schiesbn please have a look at my solution for the versions issue here: 02b9bad

I'm fine with that solution for now, for 8.1 I would like to move away from using the view in the trash wrapper and work directly on the storages and then we should be able to get rid of this "hack"

**Comment by PVince81** [comment]
@icewind1991 thanks for the feedback. I agree with the future changes.

I'll redo the manual testing according to the steps here: https://github.com/owncloud/core/pull/13561#issuecomment-71206427

**Comment by PVince81** [comment]
#### Versions tests
- [x] move file+versions to ext storage then back
- [ ] move file+versions to shared folder as recipient then back :no_entry_sign: FAIL, possibly unrelated, will check on master/stable7
- [x] move file+versions to shared folder as owner then back

**Comment by PVince81** [comment]
The failing manual test is unrelated to this PR and happens on OC 7 as well, raised as https://github.com/owncloud/core/issues/13671

Please review.

**Comment by PVince81** [comment]
Bonus testing (also with encryption+locking enabled):
- [x] share ext storage mount point, test trashbin + restore
- [x] share ext storage subdir, test trashbin + restore
(versions are not preserved due to the bug mentionned before)

**Comment by PVince81** [comment]
@schiesbn @icewind1991 please review again, a lot has changed since last time.

**Comment by icewind1991** [comment]
:+1: tested, looks good

File: lib/public/files/storage/istoragefactory.php (hunk 3 above)
Comment (LukasReschke) [inline lib/public/files/storage/istoragefactory.php]: Still needs adjustment

**Comment by LukasReschke** [comment]
:+1:

**Comment by PVince81** [comment]
Tests passed for the commit before the last one.
As the last one only affects phpdoc => merge.
(also it seems Jenkins is sleeping now)
