### PR TITLE
redirect to new login route

### LINKED ISSUE #25097: Wrong redirection from index.php/settings/personal when not logged in.
### Steps to reproduce
1. In the browser, log off from owncloud:
2. Go to `http://<owncloud_url>/index.php/settings/personal#devices`
3. log in

### Expected behaviour

You end up in the `index.php/settings/personal#devices`  page.
And can manage your device.

### Actual behaviour

You arrive in the file app. 

Actually, when requesting, `/~owncloud/index.php/settings/personal`
We first are redirected to  `/~owncloud/index.php?redirect_url=%2F%7Eowncloud%2Findex.php%2Fsettings%2Fpersonal`  (that's normal)
But then we are redirected once more to  `/~owncloud/index.php/login` and the original url is forgoten.

### Server configuration
**Operating system**: Archlinux

**Web server:** Apache

**Database:** Sqlite

**PHP version:** 7

**ownCloud version:** master branch

**Where did you install ownCloud from:** git

### PR DESCRIPTION
**Pull request by ChristophWurst**
fixes #25097

Apparently that piece of code redirected to the index page, which worked before we had the explicit /login route.

@ogoffart @PVince81 @rullzer review please

### CODE REVIEW

**Comment by ChristophWurst** [comment]
can be tested with ``/settings/personal#devices``. Routes like ``/apps/files`` were redirected correctly.

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
Second review ? @nickvergessen @rullzer @icewind1991

File: lib/private/legacy/util.php [hunk 1]
```diff
@@ -962,11 +962,12 @@ public static function checkDataDirectoryValidity($dataDirectory) {
...
 		if (!OC_User::isLoggedIn()) {
-			header('Location: ' . \OCP\Util::linkToAbsolute('', 'index.php',
-					[
-						'redirect_url' => \OC::$server->getRequest()->getRequestUri()
-					]
-				)
+			header('Location: ' . \OC::$server->getURLGenerator()->linkToRoute(
+						'core.login.showLoginForm',
+						[
+							'redirect_url' => urlencode(\OC::$server->getRequest()->getRequestUri()),
```
Comment (icewind1991) [inline lib/private/legacy/util.php]: afaik the url generator takes care of url encoding itself

Comment (ChristophWurst) [inline lib/private/legacy/util.php]: it indeed encodes parameters, but when testing it, the ``settings/personal?devices`` route was redirected to ``http://localhost/login?redirect_url=/settings/personal%3Fdevices``. Should those slashes be encoded or not? It seems like the ``UrlGenerator`` does not encode all special chars.

Comment (ChristophWurst) [inline lib/private/legacy/util.php]: see https://github.com/owncloud/3rdparty/blob/12f9071624285bf465157730fc8d43d7a7d7fbd2/symfony/routing/Generator/UrlGenerator.php#L50-L76

Comment (icewind1991) [inline lib/private/legacy/util.php]: > Should those slashes be encoded or not?

They don't need to, and it produces nicer urls to keep them as is

https://github.com/owncloud/3rdparty/blob/12f9071624285bf465157730fc8d43d7a7d7fbd2/symfony/routing/Generator/UrlGenerator.php#L292

**Comment by nickvergessen** [comment]
Works, but the `#devices` is lost when 2FA is enabled.

**Comment by ChristophWurst** [comment]
Seems like we need a little client-side hack to keep the anchor across requests http://stackoverflow.com/questions/8744299/how-to-detect-the-request-uri-along-with-anchor-tag-in-a-php-script

**Comment by ChristophWurst** [comment]
Added the little client-side hack to keep the anchor. URLs like ``http://localhost/settings/personal?section=devices`` are 'redirected' client-side to ``http://localhost/settings/personal?section=devices#devices``.

@nickvergessen @PVince81 please re-review

File: settings/js/personal.js [hunk 2]
```diff
@@ -368,6 +368,17 @@ $(document).ready(function () {
...
 	});
 	view.reload();
+
+	// 'redirect' to anchor sections
+	// anchors are lost on redirects (e.g. while solving the 2fa challenge) otherwise
+	// example: /settings/person?section=devices will result in /settings/person?#devices
+	if (!window.location.hash) {
+		var query = OC.parseQueryString(location.search);
+		if (query && query.section) {
+			OC.Util.History.replaceState({});
```
Comment (PVince81) [inline settings/js/personal.js]: As long as we never have any other params on this page, this is ok.

In general we might want to do:
```js
delete query.section;
OC.Util.History.replaceState(query);
```
to preserve the other params.

You can leave it as is for now.

**Comment by PVince81** [comment]
Tested, works :+1: 

@guruz @icewind1991 @georgehrke second review ?

File: lib/private/legacy/util.php (hunk 1 above)
Comment (icewind1991) [inline lib/private/legacy/util.php]: This will double urlencode the requesturi which might cause issues

**Comment by guruz** [comment]
👍
