### PR TITLE
Fix systemtatgs get,create and update API

### LINKED ISSUE #34594: The SystemTagManager API should behave as it was before for methods like createTag, getTag
### Steps to reproduce
1. The SystemTagManager API like createTag(), getTag() should behave as before. Meaning even if the last argument is not provided to these methods, the behaviour of the tags created should be as expected. The last argument is causing problems with behaviour of tags created. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

### PR DESCRIPTION
**Pull request by sharidas**
Fix systemtags get, create and update API.
Due to recent changes made to add static tags,
the API changes are not compatible with the
older version. Hence to make them work as
before, minor changes are made.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Because of recent changes made to add static tags, there were changes made to `getTag`, `createTag` and `updateTag`. As a result they were not compatible with the older versions of oC. For example: when any of these methods were called by the user without last argument `userEditable`, the results were not as expected. The user gets result which were incorrect. Hence this change would help to rectify this problem. The API's should not break.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/34594

## Motivation and Context

Fix the API breakage that happened in the systemtags for `getTag`, `createTag` and `updateTag` methods.

## How Has This Been Tested?

- Tested with unit test.
- Tested by adding small snippet code to create tag, get tag and update it and verify. Sample code :
```
\OC::$server->getSystemTagManager()->createTag('invisibleTag', false, false);
$tag = \OC::$server->getSystemTagManager()->getTag('invisibleTag', false, false);
\OC::$server->getSystemTagManager()->updateTag($tag->getId(), 'visibleTag', true, true);
```
And the output captured for the values in `$tag`:
```
name = invisibleTag
UserVisible = 0
UserAssignable = 0
UserEditable 0
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

File: lib/private/SystemTag/SystemTagManager.php [hunk 1]
```diff
@@ -192,10 +201,19 @@ public function getTag($tagName, $userVisible, $userAssignable, $userEditable =
...
-		$userEditable = (int)$userEditable;
+
+		/**
+		 * Change made inorder to make sure this API should not be broken,
+		 * if variable $userEditable is not passed to this method.
+		 */
+		if ($userEditable === null) {
+			$userEditable = 1;
+		} elseif (\is_bool($userEditable)) {
+			$userEditable = (int)$userEditable;
```
Comment (PVince81) [inline lib/private/SystemTag/SystemTagManager.php]: it's a bit weird to check whether it's a boolean and then convert it to an int.

I also still wonder why we used ints below instead of boolean

**Review by PVince81 — APPROVED** [review]
:+1: fine for now

**Comment by PVince81** [comment]
@sharidas please backport

**Comment by sharidas** [comment]
Backport PR: https://github.com/owncloud/core/pull/34610
