### PR TITLE
Prevent getting a version expiry list when no versions available

### LINKED ISSUE #38373: Trying to access array offset on value of type bool at
### Steps to reproduce
1. I have no idea why this error popped up

### Expected behaviour
No php error message

### Actual behaviour
`Trying to access array offset on value of type bool at \/var\/www\/owncloud\/apps\/files_versions\/lib\/Storage.php#579`

This is the erroring line is:
`$nextVersion = $firstVersion['version'] - $step;`

### Server configuration
**Operating system**: Ubuntu 20.04

**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.4

**ownCloud version:** 10.6 stable

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** tar

**Signing status (ownCloud 9.0 and above):**

```
all green
```

**The content of config/config.php:**

[config_report_20210203.zip](https://github.com/owncloud/core/files/5916971/config_report_20210203.zip)

**List of activated apps:**

```
Enabled:
  - activity: 2.6.0
  - audioplayer: 2.8.4
  - comments: 0.3.0
  - configreport: 0.2.0
  - dav: 0.6.0
  - federatedfilesharing: 0.5.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_clipboard: 1.0.3
  - files_external: 0.7.1
  - files_external_dropbox: 1.2.0
  - files_external_ftp: 0.2.1
  - files_mediaviewer: 1.0.4
  - files_pdfviewer: 0.11.2
  - files_sharing: 0.14.0
  - files_texteditor: 2.3.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firstrunwizard: 1.2.0
  - market: 0.6.0
  - notifications: 0.5.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.4.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - guests
  - user_external
```

**Are you using external storage, if yes which one:** local/smb/gd

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:** Opera

**Operating system:** W10x64Pro

#### Web server error log
```
No relevant entry
```

#### ownCloud log (data/owncloud.log)
```
Trying to access array offset on value of type bool at \/var\/www\/owncloud\/apps\/files_versions\/lib\/Storage.php#579
```

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
Previous to this little fix, when getting a version expiry list with an empty `$version` array, OC ran into an error. Not a critical one, but still not nice and spams the `owncloud.log` file.

**How does this happen?**

Versions of a file expire at a certain point of time. When a version is added to a file, an expiry command is scheduled via cronjob. Eventually the cronjob runs and will expire (=delete) the version of this file. But it is also possible to clean up all versions in between those two actions, for instance with the command `occ version:cleanup`. When the cronjob runs afterwards, no versions will be available to expire -> error.

**Steps to reproduce:**

* Create a new file, then edit that file -> a version will be created.
* Clean up all versions: `occ version:cleanup`.
* Run cronjob to expire versions: `occ system:cron`.
* Check your `owncloud.log` file, it should've logged the error: `Trying to access array offset on value of type bool at /path/to/your/owncloud`.

## Related Issue
- Fixes https://github.com/owncloud/core/issues/38373

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

File: apps/files_versions/lib/Storage.php [hunk 1]
```diff
@@ -538,7 +538,7 @@ private static function getHumanReadableTimestamp($timestamp) {
 	protected static function getExpireList($time, $versions, $quotaExceeded = false) {
 		$expiration = self::getExpiration();
 
-		if ($expiration->shouldAutoExpire()) {
+		if ($expiration->shouldAutoExpire() && \count($versions) > 0) {
```
Comment (jvillafanez) [inline apps/files_versions/lib/Storage.php:541]: `!empty($versions)` might be faster

**Review by jvillafanez — APPROVED** [review]
I don't expect a really big list of versions (maybe 100 at most), so the performance impact should be minimal. No real need to change anything.

**Review by phil-davis — APPROVED** [review]

**Review by AlexAndBear — APPROVED** [review]
