### PR TITLE
Bypass apps blocking for daily/git channel

### LINKED ISSUE #33819: [master] Cannot upgrade from stable10 to master due to max-version
As agreed in https://github.com/owncloud/core/pull/33360, we skip max-version check for the git and daily channel on install.

We should also do so when running `occ upgrade` and any related operations.

Currently upgrading from stable10 to master gives errors:
```
2018-12-07T14:19:21+00:00 Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.                                                                                                                               
2018-12-07T14:19:21+00:00 Repair warning: Please install or update the following apps manually or disable them with:
occ app:disable activity                                                                                                               
occ app:disable files_texteditor                                                                                                       
occ app:disable files_videoplayer                                                                                                      
occ app:disable market                                                                                                                 
occ app:disable notifications                                                                                                          
2018-12-07T14:19:21+00:00 Repair warning: For manually updating, see https://doc.owncloud.org/server/11.0/go.php?to=admin-marketplace-apps                                                                                                                                    
2018-12-07T14:19:21+00:00 OC\RepairException: Upgrade is not possible
2018-12-07T14:19:21+00:00 Update failed
```

@DeepDiver1975 FYI

### PR DESCRIPTION
**Pull request by VicDeo**
## Description
As agreed in #33360, we skip max-version check for the git and daily channel on install.
We should also do so when running occ upgrade and any related operations.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/33819

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:
- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

File: lib/private/Repair/Apps.php [hunk 1]
```diff
@@ -207,7 +207,13 @@ public function run(IOutput $output) {
 		$hasBlockingMissingApps = \count($failedMissingApps);
 		$hasBlockingIncompatibleApps = \count($failedIncompatibleApps);
 
-		if ($hasBlockingIncompatibleApps || $hasBlockingMissingApps) {
+		$skipBlockingAppsCheck = !\in_array(
```
Comment (phil-davis) [inline lib/private/Repair/Apps.php]: This should be the reverse? Take off the not ``!`` and it works for me.

File: lib/private/Repair/Apps.php [hunk 2]
```diff
@@ -207,7 +207,13 @@ public function run(IOutput $output) {
...
+			Util::getChannel(),
+			['git', 'daily']
+		);
+		if ($skipBlockingAppsCheck === false
+			&&($hasBlockingIncompatibleApps || $hasBlockingMissingApps)
```
Comment (phil-davis) [inline lib/private/Repair/Apps.php]: Will code-style complain about no space in ``&&(``
(not sure if those kind of checks have been enabled yet)

File: lib/private/Repair/Apps.php (hunk 1 above)
Comment (VicDeo) [reply lib/private/Repair/Apps.php]: true

File: lib/private/Repair/Apps.php [hunk 3]
```diff
@@ -205,7 +205,11 @@ public function run(IOutput $output) {
 		}
 
 		$hasBlockingMissingApps = \count($failedMissingApps);
-		$hasBlockingIncompatibleApps = \count($failedIncompatibleApps);
+		$skipBlockingAppsCheck = \in_array(
+			Util::getChannel(),
+			['git', 'daily']
```
Comment (PVince81) [inline lib/private/Repair/Apps.php]: add ", true" for strict check

**Comment by PVince81** [comment]
@VicDeo please update unit test or state why it's not possible.

File: lib/private/Repair/Apps.php (hunk 3 above)
Comment (VicDeo) [reply lib/private/Repair/Apps.php]: done

**Comment by VicDeo** [comment]
@PVince81  possible [in a way that I don't like]. Added.

**Comment by VicDeo** [comment]
Stable10: https://github.com/owncloud/core/pull/33861

**Comment by VicDeo** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by VicDeo** [comment]
@PVince81 please rereview

File: tests/lib/Repair/AppsTest.php [hunk 4]
```diff
@@ -79,6 +79,33 @@ public function testMarketEnableVersionCompareCurrent() {
...
+		];
+	}
+
+	/**
+	 * @dataProvider dataTestHasBlockingIncompatibleApps
+	 * @param string $channel
+	 * @param string[] $blockingApps
+	 * @param bool $expectedResult
+	 */
+	public function testHasBlockingIncompatibleApps($channel, $blockingApps, $expectedResult) {
```
Comment (PVince81) [inline tests/lib/Repair/AppsTest.php]: achievement unlocked: codecov pleaser :-D

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@VicDeo I don't think we need to backport as it would only affect updating apps from OC < 10
