### PR TITLE
fix runtime caching in ldap's user manager, fixes #17631

### LINKED ISSUE #17631: 8.1 php ldap segfault when some users login
Upgraded from 8.0.5 to 8.1 on Ubuntu 14.04.2 LTS using deb package from repo http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.04/

Now when some users login the php process segfaults in the ldap library. Doesn't effect all users. When an effected user attempts to login, owncloud generates thousands of queries in a loop to the ldap server and CPU goes to 100% until the process segfaults.

```
Jul 13 09:03:40 hostname kernel: [1567616.839869] php5-fpm[10623]: segfault at 7ffef0922b40 ip 00007fb6100d55e2 sp 00007ffef0922b10 error 6 in libldap_r-2.4.so.2.8.3[7fb6100c2000+4d000]
Jul 13 09:04:12 hostname kernel: [1567648.823291] php5-fpm[10637]: segfault at 7ffef0922b40 ip 00007fb6100d55e2 sp 00007ffef0922b10 error 6 in libldap_r-2.4.so.2.8.3[7fb6100c2000+4d000]
Jul 13 09:04:44 hostname kernel: [1567680.722195] php5-fpm[10599]: segfault at 7ffef0922b40 ip 00007fb6100d55e2 sp 00007ffef0922b10 error 6 in libldap_r-2.4.so.2.8.3[7fb6100c2000+4d000]
Jul 13 09:05:16 hostname kernel: [1567712.781160] php5-fpm[10608]: segfault at 7ffef0922b40 ip 00007fb6100d55e2 sp 00007ffef0922b10 error 6 in libldap_r-2.4.so.2.8.3[7fb6100c2000+4d000]
Jul 13 09:05:48 hostname kernel: [1567744.849465] php5-fpm[10653]: segfault at 7ffef0922b40 ip 00007fb6100d55e2 sp 00007ffef0922b10 error 6 in libldap_r-2.4.so.2.8.3[7fb6100c2000+4d000]
Jul 13 09:06:19 hostname kernel: [1567776.664817] php5-fpm[10661]: segfault at 7ffef0922b40 ip 00007fb6100d55e2 sp 00007ffef0922b10 error 6 in libldap_r-2.4.so.2.8.3[7fb6100c2000+4d000]
Jul 13 09:06:52 hostname kernel: [1567808.746284] php5-fpm[10673]: segfault at 7ffef0922b40 ip 00007fb6100d55e2 sp 00007ffef0922b10 error 6 in libldap_r-2.4.so.2.8.3[7fb6100c2000+4d000]
Jul 13 09:07:24 hostname kernel: [1567840.915549] php5-fpm[10681]: segfault at 7ffef0922b40 ip 00007fb6100d55e2 sp 00007ffef0922b10 error 6 in libldap_r-2.4.so.2.8.3[7fb6100c2000+4d000]
Jul 13 09:07:56 hostname kernel: [1567872.782323] php5-fpm[10683]: segfault at 7ffef0922b40 ip 00007fb6100d55e2 sp 00007ffef0922b10 error 6 in libldap_r-2.4.so.2.8.3[7fb6100c2000+4d000]
Jul 13 09:08:28 hostname kernel: [1567904.752068] php5-fpm[10690]: segfault at 7ffef0922b40 ip 00007fb6100d55e2 sp 00007ffef0922b10 error 6 in libldap_r-2.4.so.2.8.3[7fb6100c2000+4d000]
```

### PR DESCRIPTION
**Pull request by blizzz**
Comes with unit tests!

How to reproduce:
1. Have LDAP backend enabled and users shall have jpegPhoto set. Also set the Cache TTL to 0 (might require Apache2 restart with APCu)
2. Log in once (probably succeed). Wait 24hrs or do `delete from oc_preferences where userid = 'zombie79' and configkey = 'lastFeatureRefresh';` where zombie79 should be replaced with the LDAP users ownCloud username (see Users page if in doubt)
3. Try to re-login. If you did not log out before, logging out is enough, too. 

Before this: OC ends up in an infinite loop, aka loading until server/PHP crashes.

With the patch: all fine

Please test and review @benwilliams @Nick-Lock @johansmitsnl @MorrisJobke 

@karlitschek backport request to 8.1 (fixes #17631 and crucial because of no backup cache), but also for 8.0 and 7.0 (not that severe, but change is small and unit tests are provided).

### CODE REVIEW

**Comment by johansmitsnl** [comment]
After the fix the the cron seems to continue normally.

File: apps/user_ldap/tests/user/manager.php [hunk 1]
```diff
@@ -173,6 +177,10 @@ public function testGetByUidExisting() {
         $manager->setLdapAccess($access);
         $user = $manager->get($uid);
 
+		// Now we fetch the user again. If this leads to a failing test,
+		// runtime caching the manager is broken.
+		$user = $manager->get($uid);
+
```
Comment (MorrisJobke) [inline apps/user_ldap/tests/user/manager.php]: Intendation

**Comment by nickvergessen** [comment]
Looks good :+1:

**Comment by benwilliams** [comment]
Confirmed that it solves issue when user logging in.

File: apps/user_ldap/tests/user/manager.php (hunk 1 above)
Comment (blizzz) [inline apps/user_ldap/tests/user/manager.php]: woah, the file is full of spaces not tabs :scream:

**Comment by blizzz** [comment]
Hint: adding ?w=1 to the files URL (as in https://github.com/owncloud/core/pull/17723/files?w=1) hides whitespace changes.

**Comment by blizzz** [comment]
@benwilliams and @johansmitsnl successful testing go as :+1: -> merging. Thanks guys!

**Comment by blizzz** [comment]
@karlitschek is backporting ok(see description)?

**Comment by Nick-Lock** [comment]
Sorry for the delay, as promised I was unavailable all weekend :) Unfortunately I'm going to have to be the difficult one here - for me this patch actually makes things worse!

Firstly, I could not reproduce the initial problem by deleting the DB entry detailed above. However, I do not know if I have the jpegPhoto set for users or the Cache TTL set to 0 (how do I check/alter this?).

Assuming that this was a local quirk for my installation, I applied the changes in this patch and the login screen went back to being a blank white page with this stack trace:

```
[Mon Jul 20 11:31:24.379208 2015] [:error] [pid 31040] [client 192.xxx.2.44:53998] PHP Fatal error:  Cannot access empty property in /var/www/owncloud/apps/user_ldap/lib/user/manager.php on line 113
[Mon Jul 20 11:31:24.379248 2015] [:error] [pid 31040] [client 192.xxx.2.44:53998] PHP Stack trace:
[Mon Jul 20 11:31:24.379292 2015] [:error] [pid 31040] [client 192.xxx.2.44:53998] PHP   1. {main}() /var/www/owncloud/remote.php:0
[Mon Jul 20 11:31:24.379377 2015] [:error] [pid 31040] [client 192.xxx.2.44:53998] PHP   2. OC_App::loadApps() /var/www/owncloud/remote.php:116
[Mon Jul 20 11:31:24.379429 2015] [:error] [pid 31040] [client 192.xxx.2.44:53998] PHP   3. OC_App::loadApp() /var/www/owncloud/lib/private/app.php:99
[Mon Jul 20 11:31:24.379474 2015] [:error] [pid 31040] [client 192.xxx.2.44:53998] PHP   4. OC_App::requireAppFile() /var/www/owncloud/lib/private/app.php:120
[Mon Jul 20 11:31:24.379506 2015] [:error] [pid 31040] [client 192.xxx.2.44:53998] PHP   5. require_once() /var/www/owncloud/lib/private/app.php:139
[Mon Jul 20 11:31:24.379549 2015] [:error] [pid 31040] [client 192.xxx.2.44:53998] PHP   6. OCP\\App::isEnabled() /var/www/owncloud/apps/user_ldap/appinfo/app.php:65
[Mon Jul 20 11:31:24.379597 2015] [:error] [pid 31040] [client 192.xxx.2.44:53998] PHP   7. OC_App::isEnabled() /var/www/owncloud/lib/public/app.php:142
[Mon Jul 20 11:31:24.379641 2015] [:error] [pid 31040] [client 192.xxx.2.44:53998] PHP   8. OC\\App\\AppManager->isEnabledForUser() /var/www/owncloud/lib/private/app.php:270
[Mon Jul 20 11:31:24.379689 2015] [:error] [pid 31040] [client 192.xxx.2.44:53998] PHP   9. OC\\User\\Session->getUser() /var/www/owncloud/lib/private/app/appmanager.php:120
[Mon Jul 20 11:31:24.379739 2015] [:error] [pid 31040] [client 192.xxx.2.44:53998] PHP  10. OC\\User\\Manager->get() /var/www/owncloud/lib/private/user/session.php:158
[Mon Jul 20 11:31:24.379783 2015] [:error] [pid 31040] [client 192.xxx.2.44:53998] PHP  11. OCA\\user_ldap\\USER_LDAP->userExists() /var/www/owncloud/lib/private/user/manager.php:132
[Mon Jul 20 11:31:24.379830 2015] [:error] [pid 31040] [client 192.xxx.2.44:53998] PHP  12. OCA\\user_ldap\\lib\\user\\Manager->get() /var/www/owncloud/apps/user_ldap/user_ldap.php:202
[Mon Jul 20 11:31:24.379875 2015] [:error] [pid 31040] [client 192.xxx.2.44:53998] PHP  13. OCA\\user_ldap\\lib\\user\\Manager->createInstancyByUserName() /var/www/owncloud/apps/user_ldap/lib/user/manager.php:191
[Mon Jul 20 11:31:24.379930 2015] [:error] [pid 31040] [client 192.xxx.2.44:53998] PHP  14. OCA\\user_ldap\\lib\\user\\Manager->createAndCache() /var/www/owncloud/apps/user_ldap/lib/user/manager.php:165
```

This is quite probably our installation at fault! I'm not going to claim that the patch doesn't work, as everyone else seems quite happy. :)

**Comment by karlitschek** [comment]
yes. please backport :+1:

**Comment by blizzz** [comment]
Thank you @Nick-Lock, our basic rule is to have two thumbs to get PRs merged, if there are no votes against, so I did it already. Your input is nevertheless highly appreciated!

>  However, I do not know if I have the jpegPhoto set for users or the Cache TTL set to 0 (how do I check/alter this?).

If your users have avatars, then jpegPhoto is set for those (on AD it can be thumbnailPhoto, too, does not make a difference). 

The cache TTL can be configured in the Advanced LDAP settings, also you can check it on command line using occ ldap:show-config

> This is quite probably our installation at fault! I'm not going to claim that the patch doesn't work, as everyone else seems quite happy. :)

Possibly. This sounds unlikely to happen, and if, you would have seen the message before. But let's investigate it to be on the safe side. Could you paste the createAndCache method in your /var/www/owncloud/apps/user_ldap/lib/user/manager.php? Should be lines 108-116. You did apply it against OC 8.1?

**Comment by Nick-Lock** [comment]
/blush

I typo'd the change to that function - I'd managed to put "$this->$users" instead of "$this->users"

@blizzz Thanks for your patience. I'm very green at OC administration, so I hope I'm not treading on too many toes :)

I can confirm that it now works with the above patch (*correctly applied*) in place.

For the record:
jpegPhoto is on
Cache TTL was previously 600, it's now 0 but the DB delete above didn't break our installation with either value set (!?)
'version' in config/config.php is 8.1.0.8. There is a package update pending; I have been waiting until we finished with this issue before installing. I will install the update, and check this patch against it :)

**Comment by blizzz** [comment]
@Nick-Lock no problem. Again, thank you for getting into it, testing and confirming that this issue is solved with the patch :)

**Comment by blizzz** [comment]
> Cache TTL was previously 600, it's now 0 but the DB delete above didn't break our installation with either value set (!?)

Since OC 8.1 you need to configure a cache. Without, this has no effect, confer https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/performance_tuning.html#caching

**Comment by blizzz** [comment]
> yes. please backport :+1:

ty, will do a bit later today

**Comment by Nick-Lock** [comment]
Now with APCu 4.0.7 installed and configured, upgraded OC via the openSUSE repositories to package version "owncloud:all/unknown 8.1.0-3" (Ubuntu 14.04) and re-aplied this patch without typos...

Works fine :)

Thanks to everyone for the quick fix!

**Comment by davitol** [comment]
:+1: works fine in version":"8.1.0.8","versionstring":"8.1.0","edition
