### PR TITLE
Check target name on rename with web UI

### LINKED ISSUE #16401: Wrong error message trying to rename a file with / at the end of the name
### Steps to reproduce
1. Create a new file.
2. Try to rename it using ' / ' character at the final

### Expected behaviour

An error message should be shown about reserved characters

### Actual behaviour

The error shown says "The name is alreadt used in the folder..."

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"

captura de pantalla 2015-05-18 a las 11 27 17

### PR DESCRIPTION
**Pull request by PVince81**
When renaming over the web UI, check early that the target name is
valid.

This prevents nonsensical error messages when renaming to a name with a
trailing backslash.

Fixes https://github.com/owncloud/core/issues/16401

Test by renaming either to "*" or to a file name with a trailing backslash.

Please review @LukasReschke @icewind1991 @DeepDiver1975 @davitol @nickvergessen

### CODE REVIEW

**Comment by LukasReschke** [comment]
Discussed this with @PVince81, thanks for taking care :+1:

**Comment by karlitschek** [comment]
:+1:  looks good

File: apps/files/lib/app.php [hunk 1]
```diff
@@ -74,6 +74,17 @@ public function rename($dir, $oldname, $newname) {
 			'data'		=> NULL
 		);
 
+		try {
+			// check if the new name is conform to file name restrictions
+			$this->view->verifyPath($dir, $newname);
+		} catch (\OCP\Files\InvalidPathException $ex) {
+			$result['data'] = array(
+				'message'	=> $this->l10n->t($ex->getMessage()),
```
Comment (nickvergessen) [inline apps/files/lib/app.php]: This is not going to be translated, unless the messages are already used in a normal `$l->t()` somewhere else.

**Comment by davitol** [comment]
:+1: Fixed
