### PR TITLE
[full-ci] Allow renaming two files with the same name but different paths

### LINKED ISSUE #20722: When I favored two files with same name
In this situation,if I want to rename file in favorite page,there will be something wrong.So I think,maybe we should modify this.

### LINKED ISSUE #35174: Bug in renaming files/folders in shared with pages
### Steps to reproduce
1. create folder `nf1/newfolder`  `test`
2. share folder `nf1/newfolder` `test` by public link or with any users 
3.  browse to `shared  with others`/`shared by link` page based on the type of share 
4. try renaming `test` to `newfolder` 

### Expected behaviour
Folder `test` should be renamed  to `newfolder` as `test` and `newfolder` are in different path

### Actual behaviour
`test` folder cannot be renamed as `newfolder`

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:**Mysql

**PHP version:**7.2

**ownCloud version:** (see ownCloud admin page) 11.0.0 prealpha (git)

**Updated from an older ownCloud or fresh install:**Fresh

**Where did you install ownCloud from:**git 

### Client configuration
**Browser:**  Version 73.0.3683.103 (Official Build) (64-bit)

**Operating system:**Ubuntu 18.04

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
Bugfix: Allow renaming two files with the same name but different paths

With this change, we allow renaming a file to an existing file name,
when the path differs.
This happens for example when the user creates the file
'/mydirname/text.txt' and '/mytext.txt' then mark both as favorite.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/20722
- Fixes https://github.com/owncloud/core/issues/35174

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiAuthWebDav-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32818/48/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProvisioning-v1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32818/53/1

**Comment by JanAckermann** [comment]
@phil-davis should we add acceptance tests for https://github.com/owncloud/core/issues/20722 ?

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiFederationToShares2-10.7.0-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32818/112/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareCreateSpecialToRoot2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32818/59/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingAutocomp1-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32818/138/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProvisioning-v2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32818/54/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareReshareToShares2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32818/75/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingPublic2-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32820/145/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingPublic2-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32824/145/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingPublic2-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32825/145/1

**Comment by phil-davis** [comment]
Note: there is another scenario, which is a different existing feature:
- `abc.txt` and `def.txt` in the root folder
- favorite `abc.txt`
- on the Favorites page, try to rename `abc.txt` to `def.txt`
- it lets you try, but then a notification is displayed "The name "def.txt" is already used in the folder "/". Please choose a different name."

It would be nice if the on-the-fly rename code in the JavaScript could "understand" that the proposed name is already used. But that would require more real-time code that checks with the server on every character as it is typed, or when starting the "Rename" input, the JavaScript would have to get a list of all the files in the foldder of that item, so that it could check as the user types. Maybe not feasible.

**Comment by phil-davis** [comment]
Rebased to get fresh CI.

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingPublic2-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32848/145/1

**Comment by phil-davis** [comment]
@JanAckermann I sorted out the `shareByPublicLink` test scenario that originally had a wrong `Then` step that actually did not check the right thing, and did not fail. But the scenario fails now because when I rename a resource on the "Shared by link" page, the hover text for the actual location of the resource does not get updated. See the screen-shot where I renamed "test"  to "wwwwww" but the hover-text was still "ttt/test" (that folder is a sub-folder of folder "ttt")
hover-text-does-not-match-rename

There is the same problem on the "Shared with others" page.

If you can sort out the hover-text being updated (data-original-title) on rename, then the test scenario should pass.

The "Favorites" page does not seem to have any hover-text to give the user a clue where the resource really is. When I have 2 files with the same name on the Favorites page, I don't know how I can know which file is from which folder. If we can have some similar way for the user to know which resource is from where, then we can make test scenarios.

**Comment by JanAckermann** [comment]
@phil-davis Thx, will take care

**Comment by JanAckermann** [comment]
@phil-davis 
> If we can have some similar way for the user to know which resource is from where, then we can make test scenarios.

this has been introduced just know, do you want to adjust the tests?

File: tests/acceptance/features/lib/FilesPageElement/SharedByLinkFileRow.php [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+ *
+ * You should have received a copy of the GNU Affero General Public License
+ * along with this program. If not, see <http://www.gnu.org/licenses/>
+ *
+ */
+
+namespace Page\FilesPageElement;
+
+/**
+ * Object of a row on the FilesPage
```
Comment (phil-davis) [inline tests/acceptance/features/lib/FilesPageElement/SharedByLinkFileRow.php:27]: I need to fix this comment.

File: tests/acceptance/features/webUISharingPublic2/shareByPublicLink.feature [hunk 2]
```diff
@@ -218,8 +218,9 @@ Feature: Share by public link
     And the user has browsed to the shared-by-link page
     When the user renames folder "test" to "newfolder" using the webUI
     Then the following folder should be listed on the webUI
-      | newfolder |
-      | newfolder |
+      | name-parts |
```
Comment (phil-davis) [inline tests/acceptance/features/webUISharingPublic2/shareByPublicLink.feature:221]: I thought that I adjusted this scenario. The changes have got lost somewhere. I will have a look locally...

Comment (JanAckermann) [reply tests/acceptance/features/webUISharingPublic2/shareByPublicLink.feature:221]: Oh, sorry there was a little accident while rebasing :-1:

Comment (phil-davis) [reply tests/acceptance/features/webUISharingPublic2/shareByPublicLink.feature]: fixed

File: tests/acceptance/features/lib/FilesPageElement/SharedByLinkFileRow.php (hunk 1 above)
Comment (phil-davis) [reply tests/acceptance/features/lib/FilesPageElement/SharedByLinkFileRow.php]: done

**Comment by phil-davis** [comment]
I will come banck when CI is done, and look what happens and then see what other tests can be added.

**Comment by JanAckermann** [comment]
@phil-davis friendly ping =)

**Review by phil-davis — COMMENTED** [review]
LGTM. I tried various renaming to matching and not matching names on the Favorites page and the Shared by Link page  and it works fine. Tests pass.

I found one little thing in the changelog!

File: apps/files/js/favoritesfilelist.js [hunk 3]
```diff
@@ -91,6 +91,16 @@ $(document).ready(function() {
...
 					// prepend empty dir info because original handler
 					result.unshift({});
+
+					for (var i = 0; i < result.length; i++) {
+						/**
+						 * Set extraData to file path and name
+						 * if the file is not in user's root home directory
+						 */
+						if (result[i].path !== '/') {
+							result[i].extraData = result[i].path + '/' + result[i].name;
```
Comment (jvillafanez) [inline apps/files/js/favoritesfilelist.js:101]: Variable name seems misleading. Something like `result[i].extraData['fullPath'] = ...` fits better, and it can also be extended with more information if needed.
Alternatively, `result[i].fullPath = ...` could be an option, although it might collide at some point with other data.

Comment (JanAckermann) [reply apps/files/js/favoritesfilelist.js:101]: This is not how the extraData record is working in the webUI!
Please have a closer look to the code.

**Review by phil-davis — APPROVED** [review]
LGTM now - works.
@jvillafanez please review again

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/32907/31/8
```
+ phpdbg -d memory_limit=6G -rr ../lib/composer/bin/phpunit --configuration phpunit-autotest-external.xml --coverage-clover output/coverage/autotest-external-clover-sqlite-sftp.xml ../apps/files_external/tests/Storage/SftpTest.php
[Welcome to phpdbg, the interactive PHP debugger, v7.4.23]
To get help using phpdbg type "help" and press enter
[Please report bugs to <http://bugs.php.net/report.php>]
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Runtime:       PHPDBG 7.4.23
Configuration: phpunit-autotest-external.xml

.................................E............................... 65 / 92 ( 70%)
...........................                                       92 / 92 (100%)

Time: 00:31.609, Memory: 80.63 MB

There was 1 error:

1) OCA\Files_External\Tests\Storage\SftpTest::testMove with data set #7 ('/single ' quote.txt', '/tar'get.txt')
fwrite() expects parameter 1 to be resource, bool given

/drone/src/lib/private/Files/Storage/Common.php:207
/drone/src/tests/lib/Files/Storage/Storage.php:193
/drone/src/tests/lib/Files/Storage/Storage.php:226

ERRORS!
Tests: 92, Assertions: 369, Errors: 1.
```

That is a strange unit test fail - nothing to do with this PR. I will restart CI.

File: apps/files/js/favoritesfilelist.js (hunk 3 above)
Comment (jvillafanez) [reply apps/files/js/favoritesfilelist.js:101]: Ok, it's used in the filelist.js file, in the `_createRow` method, which is around 4 levels deeper in the stacktrace. Since that code is already there, renaming the variable is kind of out of scope.

**Review by jvillafanez — APPROVED** [review]
